#!/bin/sh
lib_files=/usr/local/lib/rtp
b_flag=
args=

while [ $# != 0 ] ; do
	case "$1" in
	-b)	b_flag="y";;
	*)	args="$args $1";;
	esac
	shift
done

if [ "$b_flag" != "" ]; then
	exec cc -w -g -Qpath $lib_files/with_cpp/ $args
else
	exec cc -w -g -Qpath $lib_files/without_cpp/ $args
fi
