h52430
s 00002/00002/00068
d D 8.1 93/06/04 18:47:41 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00050/00032/00020
d D 6.5 91/03/16 17:05:10 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00003/00013/00049
d D 6.4 90/06/24 21:18:05 trent 5 4
c new copyright & new pathnames (utmp)
e
s 00015/00004/00047
d D 6.3 88/09/19 21:11:57 bostic 4 3
c Berkeley copyright
e
s 00009/00006/00042
d D 6.2 86/05/20 22:53:27 karels 3 2
c inetd, english
e
s 00001/00001/00047
d D 6.1 85/04/27 14:53:22 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00048/00000/00000
d D 5.1 85/04/27 14:52:44 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 4
.\"
I 4
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH COMSAT 8C "18 July 1983"
E 2
I 2
D 4
.TH COMSAT 8C "%Q%"
E 4
I 4
D 6
.TH COMSAT 8 "%Q%"
E 4
E 2
.UC 5
.SH NAME
comsat \- biff server
.SH SYNOPSIS
D 5
.B /etc/comsat
E 5
I 5
.B comsat
E 5
.SH DESCRIPTION
.I Comsat
E 6
I 6
.Dd %Q%
.Dt COMSAT 8
.Os BSD 4.2
.Sh NAME
.Nm comsat
.Nd biff server
.Sh SYNOPSIS
.Nm comsat
.Sh DESCRIPTION
.Nm Comsat
E 6
D 3
is the server process which listens for reports of incoming mail
E 3
I 3
is the server process which receives reports of incoming mail
E 3
and notifies users if they have requested this service.
D 6
.I Comsat
D 3
listens on a datagram port associated with the ``biff'' service
E 3
I 3
receives messages on a datagram port associated with the ``biff'' service
E 6
I 6
.Nm Comsat
receives messages on a datagram port associated with the
.Dq biff
service
E 6
E 3
specification (see
D 3
.IR services (5))
for one line messages of the form
E 3
I 3
D 6
.IR services (5)
E 6
I 6
.Xr services 5
E 6
and
D 6
.IR inetd (8)).
The one line messages are of the form
E 3
.PP
.ti +0.5i
user@mailbox-offset
.PP
E 6
I 6
.Xr inetd 8 ) .
The one line messages are of the form:
.Pp
.Dl user@mailbox-offset
.Pp
E 6
If the
D 6
.I user
E 6
I 6
.Em user
E 6
specified is logged in to the system and the associated terminal has
D 6
the owner execute bit turned on (by a ``biff y''), the
.I offset
E 6
I 6
the owner execute bit turned on (by a
.Dq Li biff y ) ,
the
.Em offset
E 6
is used as a seek offset into the appropriate mailbox file and
the first 7 lines or 560 characters of the message are printed
on the user's terminal.  Lines which appear to be part of
D 6
the message header other than the ``From'', ``To'', ``Date'',
or ``Subject'' lines are not included in the displayed message.
.SH FILES
.DT
D 5
/etc/utmp	to find out who's logged on and on what terminals
E 5
I 5
/var/run/utmp	to find out who's logged on and on what terminals
E 5
.SH "SEE ALSO"
D 3
biff(1)
E 3
I 3
biff(1), inetd(8)
E 3
.SH BUGS
E 6
I 6
the message header other than the
.Dq From ,
.Dq \&To ,
.Dq Date ,
or
.Dq Subject
lines are not included in the displayed message.
.Sh FILES
.Bl -tag -width /var/run/utmp -compact
.It Pa /var/run/utmp
to find out who's logged on and on what terminals
.El
.Sh SEE ALSO
.Xr biff 1 ,
.Xr inetd 8
.Sh BUGS
E 6
The message header filtering is prone to error.
I 3
The density of the information presented is near the theoretical minimum.
E 3
D 6
.PP
E 6
I 6
.Pp
E 6
Users should be notified of mail which arrives on other
D 3
machines than the one they are currently logged in to.
E 3
I 3
machines than the one to which they are currently logged in.
E 3
D 6
.PP
E 6
I 6
.Pp
E 6
The notification should appear in a separate window so it
does not mess up the screen.
I 6
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 6
E 1
