h35096
s 00011/00015/00033
d D 1.2 91/05/17 16:13:40 sellgren 2 1
c upgrade to tapers version
e
s 00048/00000/00000
d D 1.1 91/05/17 16:12:45 sellgren 1 0
c date and time created 91/05/17 16:12:45 by sellgren
e
u
U
t
T
I 2
.\" %W% (CSRG - distribution) %G%
E 2
I 1
.so HEADERS
.NH
.ND
.sp 4
.ce 2
\fB\s14University of California Sites
.sp 2
\s12Checklist for Receiving 4.3BSD
.sp 3
.LP
In order for University of California sites to receive 4.3BSD,
D 2
the following steps should be taken:
E 2
I 2
the following items are needed:      
E 2
.sp
.RS
.IP 1. 5
D 2
Contact Pam True (415) 642-6348 at UC Berkeley's Materiel
Management Office for an application for an additional
CPU authorization under the University's Software 
Agreement with AT&T, a copy of which should be sent to us.
E 2
I 2
A copy of your CPU authorization under the University's
Software Agreement with AT&T.  This can be obtained by 
contacting Pam True on (415) 642-6348 at UC Berkeley's Materiel
Management Office. If you are upgrading your license from
4.2BSD and do not have a new CPU, this is not necessary. 
E 2
.sp
.IP 2. 5
D 2
Send a letter requesting  4.3BSD, stating that you have read
and understood the License Agreement of The Regents of the 
University of California and that your department                  
will abide by it.  This letter should be signed
E 2
I 2
A letter of authorization.
This letter should be signed
E 2
by the Department Head or duly designated representative. 
.sp 
.IP 3. 5
D 2
Send an IOC or Recharge Form for $1000 ($600 for update).
E 2
I 2
An IOC or Recharge Form for $1000.00 ($600.00 for update).
E 2
.sp
.IP 4. 5
D 2
Send a completed Site Information Form and Equipment List.
.sp
.IP 5. 5
Send a completed Order Form specifying tape density and documentation
format required.
E 2
I 2
A completed Site Information Form and Equipment List.
E 2
.sp3
.RS
Send all documents to:
.sp 
.RS
.nf
Pauline Schwartz
Distribution Coordinator
Computer Systems Research Group
Computer Science Division, EECS
University of California
Berkeley, Ca.  94720
E 1
