h18036
s 00002/00002/00158
d D 8.1 93/06/05 10:47:08 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00094/00084/00066
d D 6.4 91/03/16 17:05:45 cael 4 3
c macro and text revision (-mdoc version 3)
e
s 00002/00012/00148
d D 6.3 90/06/24 21:26:54 trent 3 2
c new copyright & pathnames (XNSrouted)
e
s 00016/00005/00144
d D 6.2 88/09/19 20:52:47 bostic 2 1
c appropriate copyright notice
e
s 00149/00000/00000
d D 6.1 86/06/04 11:14:51 mckusick 1 0
c first released with 4.3BSD
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 2
I 2
D 4
.\" Copyright (c) 1986 The Regents of the University of California.
E 4
I 4
D 5
.\" Copyright (c) 1986, 1991 The Regents of the University of California.
E 4
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1986, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
E 2
.\"
I 2
D 3
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 3
I 3
.\" %sccs.include.redist.man%
E 3
.\"
E 2
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\"     %W% (Berkeley) %G%
E 4
.\"
D 2
.TH XNSROUTED 8C "%Q%"
E 2
I 2
D 4
.TH XNSROUTED 8 "%Q%"
E 2
.UC 6
.SH NAME
XNSrouted \- NS Routing Information Protocol daemon
.SH SYNOPSIS
D 3
.B /etc/XNSrouted
E 3
I 3
.B XNSrouted
E 3
[
.B \-s
] [
.B \-q
] [
.B \-t
] [
.I logfile
]
.SH DESCRIPTION
.I XNSrouted
E 4
I 4
.Dd %Q%
.Dt XNSROUTED 8
.Os BSD 4.3
.Sh NAME
.Nm XNSrouted
.Nd NS Routing Information Protocol daemon
.Sh SYNOPSIS
.Nm XNSrouted
.Op Fl q
.Op Fl s
.Op Fl t
.Op Ar logfile
.Sh DESCRIPTION
.Nm XNSrouted
E 4
is invoked at boot time to manage the Xerox NS routing tables.
The NS routing daemon uses the Xerox NS Routing
Information Protocol in maintaining up to date kernel routing
table entries.
D 4
.PP
E 4
I 4
.Pp
Available options:
.Bl -tag -width logfile
.It Fl q
Do not supply routing information (opposite of
.Fl s
option below).
.It Fl s
Forces 
.Nm XNSrouted
to supply routing information whether it is acting as an internetwork
router or not.
.It Fl t
All packets sent or received are
printed on the standard output.  In addition,
.Nm XNSrouted
will not divorce itself from the controlling terminal
so that interrupts from the keyboard will kill the process.
.It Ar logfile
Name of file in which 
.Nm XNSrouted Ns 's
actions should be logged.  This log contains information
about any changes to the routing tables and a history of
recent messages sent and received which are related to
the changed route.
.El
.Pp
E 4
In normal operation
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
listens
for routing information packets.  If the host is connected to
multiple NS networks, it periodically supplies copies
of its routing tables to any directly connected hosts
and networks.
D 4
.PP
E 4
I 4
.Pp
E 4
When
D 4
.I XNSrouted
is started, it uses the SIOCGIFCONF
.I ioctl
E 4
I 4
.Nm XNSrouted
is started, it uses the
.Dv SIOCGIFCONF
.Xr ioctl 2
E 4
to find those
directly connected interfaces configured into the
D 4
system and marked ``up'' (the software loopback interface
E 4
I 4
system and marked
.Dq up
(the software loopback interface
E 4
is ignored).  If multiple interfaces
are present, it is assumed the host will forward packets
between networks.
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
then transmits a 
D 4
.I request
E 4
I 4
.Em request
E 4
packet on each interface (using a broadcast packet if
the interface supports it) and enters a loop, listening
for
D 4
.I request
E 4
I 4
.Em request
E 4
and
D 4
.I response
E 4
I 4
.Em response
E 4
packets from other hosts.
D 4
.PP
E 4
I 4
.Pp
E 4
When a
D 4
.I request
E 4
I 4
.Em request
E 4
packet is received, 
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
formulates a reply based on the information maintained in its
internal tables.  The
D 4
.I response
E 4
I 4
.Em response
E 4
packet generated contains a list of known routes, each marked
D 4
with a ``hop count'' metric (a count of 16, or greater, is
considered ``infinite'').  The metric associated with each
E 4
I 4
with a
.Dq hop count
metric (a count of 16, or greater, is
considered
.Dq infinite ) .
The metric associated with each
E 4
route returned provides a metric
D 4
.IR "relative to the sender" .
.PP
.I Response
E 4
I 4
.Em relative to the sender .
.Pp
.Em Response
E 4
packets received by
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
are used to update the routing tables if one of the following
conditions is satisfied:
D 4
.TP
(1)
E 4
I 4
.Bl -bullet
.It
E 4
No routing table entry exists for the destination network
or host, and the metric indicates the destination is ``reachable''
(i.e. the hop count is not infinite).
D 4
.TP
(2)
E 4
I 4
.It
E 4
The source host of the packet is the same as the router in the
existing routing table entry.  That is, updated information is
being received from the very internetwork router through which
packets for the destination are being routed.
D 4
.TP
(3)
E 4
I 4
.It
E 4
The existing entry in the routing table has not been updated for
some time (defined to be 90 seconds) and the route is at least
as cost effective as the current route.
D 4
.TP
(4)
E 4
I 4
.It
E 4
The new route describes a shorter route to the destination than
the one currently stored in the routing tables; the metric of
the new route is compared against the one stored in the table
to decide this.
D 4
.PP
E 4
I 4
.El
.Pp
E 4
When an update is applied,
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
records the change in its internal tables and generates a
D 4
.I response
E 4
I 4
.Em response
E 4
packet to all directly connected hosts and networks.
D 4
.I Routed
E 4
I 4
.Xr Routed 8
E 4
waits a short period
of time (no more than 30 seconds) before modifying the kernel's
routing tables to allow possible unstable situations to settle.
D 4
.PP
E 4
I 4
.Pp
E 4
In addition to processing incoming packets,
D 4
.I XNSrouted
E 4
I 4
.Nm XNSrouted
E 4
also periodically checks the routing table entries.
If an entry has not been updated for 3 minutes, the entry's metric
is set to infinity and marked for deletion.  Deletions are delayed
an additional 60 seconds to insure the invalidation is propagated
to other routers.
D 4
.PP
E 4
I 4
.Pp
E 4
Hosts acting as internetwork routers gratuitously supply their
routing tables every 30 seconds to all directly connected hosts
and networks.
D 4
.PP
Supplying the
.B \-s
option forces 
.I XNSrouted
to supply routing information whether it is acting as an internetwork
router or not.
E 4
I 4
.Sh SEE ALSO
.Xr idp 4
.Rs
.%T "Internet Transport Protocols"
.%R "XSIS 028112"
.%Q "Xerox System Integration Standard"
.Re
.Sh HISTORY
E 4
The
D 4
.B \-q
option is the opposite of the
.B \-s
option.  If the
.B \-t
option is specified, all packets sent or received are
printed on the standard output.  In addition,
.I XNSrouted
will not divorce itself from the controlling terminal
so that interrupts from the keyboard will kill the process.
Any other argument supplied is interpreted as the name
of file in which 
.IR XNSrouted 's
actions should be logged.  This log contains information
about any changes to the routing tables and a history of
recent messages sent and received which are related to
the changed route.
.SH "SEE ALSO"
``Internet Transport Protocols'', XSIS 028112, Xerox System Integration
Standard.
.br
D 2
idp(4P)
E 2
I 2
idp(4)
E 4
I 4
.Nm
command appeared in
.Bx 4.3 .
E 4
E 2
E 1
