h16719
s 00002/00002/00041
d D 8.1 93/06/06 16:04:15 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00009/00008/00034
d D 6.5 91/05/09 17:07:43 cael 8 7
c mdoc version three/deleted AUTHOR section
e
s 00002/00000/00040
d D 6.4 91/03/14 00:15:37 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00040
d R 6.4 91/03/13 20:32:20 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00000/00001/00040
d D 6.3 90/06/26 01:00:54 cael 5 4
c converted man page
e
s 00030/00024/00011
d D 6.2 90/06/11 05:59:44 cael 4 3
c converted man page
e
s 00001/00001/00034
d D 6.1 85/04/29 14:59:32 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00003/00033
d D 5.1 85/04/29 14:59:18 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00036/00000/00000
d D 4.1 85/04/29 14:59:01 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 9
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
E 4
.\"
D 2
.TH PXREF 1 4/8/79
E 2
I 2
D 3
.TH PXREF 1 "8 April 1979"
E 3
I 3
D 4
.TH PXREF 1 "%Q%"
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
I 7
D 8
.Vx
.Vx
E 8
E 7
.Dd %Q%
.Dt PXREF 1
I 8
.Os
E 8
E 4
E 3
E 2
D 5
.UC
E 5
D 4
.SH NAME
pxref \- Pascal cross-reference program
.SH SYNOPSIS
.B pxref
[
.BR \- ""
]
name
.SH DESCRIPTION
.I Pxref
E 4
I 4
.Sh NAME
.Nm pxref
.Nd Pascal cross-reference program
.Sh SYNOPSIS
.Nm pxref
.Op Fl
.Ar name
.Sh DESCRIPTION
.Nm Pxref
E 4
makes a line numbered listing and a cross-reference of identifier usage
for the program in
D 4
.I name.
D 2
The optional `\fB\-\fR' argument suppresses the listing.
The keywords
E 2
I 2
The optional `\fB\-\fP' argument suppresses the listing.  The keywords
E 2
.B goto
E 4
I 4
.Ar name .
The optional
.Sq Fl
argument suppresses the listing.  The keywords
.Ic goto
E 4
and
D 4
.B label
E 4
I 4
.Ic label
E 4
are treated as identifiers for the purpose of the cross-reference.
D 4
.B Include
E 4
I 4
.Ic Include
E 4
directives are not processed, but cause the placement of an entry
indexed by `#include' in the cross-reference.
D 4
.SH "SEE ALSO"
Berkeley Pascal User's Manual
.SH AUTHOR
E 4
I 4
.Sh SEE ALSO
D 8
.Em Berkeley Pascal User's Manual
.Sh AUTHOR
E 4
Niklaus Wirth
E 8
I 8
.Rs
.%T "Berkeley Pascal User's Manual"
.Re
E 8
D 4
.SH BUGS
E 4
I 4
.Sh HISTORY
D 8
.Nm Pxref
appeared in 3 BSD.
E 8
I 8
The
.Nm pxref
command appeared in
.Bx 3.0 .
E 8
.Sh BUGS
E 4
Identifiers are trimmed to 10 characters.
E 1
