h30084
s 00003/00003/00110
d D 8.2 94/05/05 17:06:43 bostic 7 6
c past tense the appears
c From: "Chris G. Demetriou" <cgd@postgres.Berkeley.EDU>
e
s 00002/00002/00111
d D 8.1 93/06/06 14:51:08 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00003/00110
d D 5.5 93/03/23 18:57:35 cael 5 4
c update .Os and history from .Ud to .Bx 4.4
e
s 00027/00005/00086
d D 5.4 91/11/11 15:34:06 bostic 4 3
c add -p option, rearrangement/cleanup
e
s 00018/00010/00073
d D 5.3 91/11/10 09:57:49 bostic 3 2
c cleanup in lots of ways, no real modifications of behavior
e
s 00007/00007/00076
d D 5.2 91/08/05 12:23:52 bostic 2 1
c minor cleanups
e
s 00083/00000/00000
d D 5.1 91/06/29 13:29:57 bostic 1 0
c date and time created 91/06/29 13:29:57 by bostic
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
D 7
.\" Copyright (c) 1991, 1993
E 7
I 7
.\" Copyright (c) 1991, 1993, 1994
E 7
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	%W% (Berkeley) %G%
.\"
.Dd "%Q%"
.Dt ID 1
D 5
.UC
E 5
I 5
.Os BSD 4.4
E 5
.Sh NAME
.Nm id
.Nd return user identity
.Sh SYNOPSIS
.Nm id
.Op Ar user
.Nm id
.Fl G Op Fl n
.Op Ar user
.Nm id
.Fl g Op Fl nr
.Op Ar user
.Nm id
I 4
.Fl p
.Nm id
E 4
.Fl u Op Fl nr
.Op Ar user
.Sh DESCRIPTION
The
.Nm id
utility displays the user and group names and numeric IDs, of the
calling process, to the standard output.
D 3
If the real and effective IDs are different both are displayed,
E 3
I 3
If the real and effective IDs are different, both are displayed,
E 3
otherwise only the real ID is displayed.
.Pp
If a
.Ar user
(login name or user ID)
is specified, the user and group IDs of that user are displayed.
In this case, the real and effective IDs are assumed to be the same.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl G
D 3
Display all of the different group IDs (effective, real and supplementary)
as white-space separated numbers.
E 3
I 3
Display the different group IDs (effective, real and supplementary)
as white-space separated numbers, in no particular order.
E 3
.It Fl g
D 3
Display only the effective group ID as a number.
E 3
I 3
Display the effective group ID as a number.
E 3
.It Fl n
D 3
Display the name of the user or group ID instead of the number.
E 3
I 3
Display the name of the user or group ID for the
.Fl G ,
.Fl g
and
.Fl u
options instead of the number.
If any of the ID numbers cannot be mapped into names, the number will be
displayed as usual.
I 4
.It Fl p
Make the output human-readable.
If the user name returned by
.Xr getlogin 2
is different from the login name referenced by the user ID, the name
returned by
.Xr getlogin 2
is displayed, preceded by the keyword ``login''.
The user ID as a name is displayed, preceded by the keyword ``uid''.
If the effective user ID is different from the real user ID, the real user
ID is displayed as a name, preceded by the keyword ``euid''.
If the effective group ID is different from the real group ID, the real group
ID is displayed as a name, preceded by the keyword ``rgid''.
The list of groups to which the user belongs is then displayed as names,
preceded by the keyword ``groups''.
Each display is on a separate line.
E 4
E 3
.It Fl r
D 3
Display the real ID instead of the effective ID.
E 3
I 3
Display the real ID for the
.Fl g
and
.Fl u
options instead of the effective ID.
E 3
.It Fl u
D 3
Display only the effective user ID as a number.
E 3
I 3
Display the effective user ID as a number.
E 3
.El
D 3
.Pp
If any of the ID numbers cannot be mapped into names, the number is displayed
instead.
E 3
.Pp
The
D 2
historic
.Xr groups 1
command is equivalent to:
.Nm id Fl Gn Op Ar user .
.Pp
The
E 2
.Nm id
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
D 4
.Xr groups 1 ,
.Xr who 1 ,
.Xr whoami 1
E 4
I 4
.Xr who 1
E 4
.Sh STANDARDS
The
D 2
.Nm logname
E 2
I 2
.Nm id
E 2
function is expected to conform to
.St -p1003.2 .
.Sh HISTORY
I 2
The
historic
.Xr groups 1
D 4
command is equivalent to:
.Nm id Fl Gn Op Ar user .
E 4
I 4
command is equivalent to
.Dq Nm id Fl Gn Op Ar user .
.Pp
The
historic
.Xr whoami 1
command is equivalent to
.Dq Nm id Fl un .
E 4
.Pp
E 2
The
D 7
.Nm
D 5
command is
.Ud .
E 5
I 5
command appears in
E 7
I 7
.Nm id
command first appeared in
E 7
.Bx 4.4 .
E 5
E 1
