h27698
s 00000/00001/00146
d D 8.3 94/04/19 08:50:24 bostic 16 15
c don't note strfile.8, it's not a real man page
e
s 00002/00001/00145
d D 8.2 93/11/17 05:17:48 bostic 15 14
c typo
e
s 00002/00002/00144
d D 8.1 93/05/31 17:01:37 bostic 14 13
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00002/00146
d D 6.11 92/07/17 15:45:34 bostic 13 12
c Ken Arnold requested that he not be associated with fortune any more
e
s 00003/00000/00145
d D 6.10 91/11/21 11:40:05 bostic 12 11
c make -a mention -o
e
s 00076/00078/00069
d D 6.9 91/08/09 23:00:40 cael 11 10
c mdoc version three
e
s 00001/00011/00146
d D 6.8 90/06/23 17:32:06 trent 10 9
c new copyright notice
e
s 00010/00005/00147
d D 6.7 89/09/07 12:34:43 bostic 9 8
c more cleanups, make clear non/offensive dichotomy
e
s 00015/00002/00137
d D 6.6 89/09/07 11:30:11 bostic 8 7
c minor reworking, add the Wisconsin explanation
e
s 00052/00064/00087
d D 6.5 89/09/07 09:53:58 bostic 7 6
c rewhack/cleanup
e
s 00104/00018/00047
d D 6.4 89/09/06 14:18:05 bostic 6 5
c new distribution from Ken Arnold
e
s 00014/00003/00051
d D 6.3 89/09/05 16:42:44 bostic 5 4
c add Berkeley specific copyright notices
e
s 00001/00001/00053
d D 6.2 88/10/19 20:44:25 bostic 4 3
c don't use full path name
e
s 00001/00001/00053
d D 6.1 85/05/20 17:33:38 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00007/00011/00047
d D 5.1 85/05/20 17:33:13 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00058/00000/00000
d D 4.1 85/05/20 17:32:50 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 11
.\" Copyright (c) 1985 The Regents of the University of California.
E 11
I 11
D 14
.\" Copyright (c) 1985, 1991 The Regents of the University of California.
E 11
.\" All rights reserved.
E 14
I 14
.\" Copyright (c) 1985, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 14
.\"
I 7
.\" This code is derived from software contributed to Berkeley by
.\" Ken Arnold.
.\"
E 7
D 10
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 10
I 10
.\" %sccs.include.redist.man%
E 10
E 5
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH FORTUNE 6
E 2
I 2
D 3
.TH FORTUNE 6 "1 February 1983"
E 3
I 3
D 11
.TH FORTUNE 6 "%Q%"
E 3
E 2
.UC 4
.SH NAME
fortune \- print a random, hopefully interesting, adage
.SH SYNOPSIS
D 2
.B fortune
E 2
I 2
D 4
.B /usr/games/fortune
E 4
I 4
D 6
.B fortune
E 6
I 6
D 7
.B /usr/games/fortune
E 7
I 7
.B fortune
E 7
E 6
E 4
E 2
[
D 7
.B \-
] [
D 6
.B \-wslao
E 6
I 6
.B \-fwslaoe
E 7
I 7
.B \-aefilosw
E 7
E 6
]
D 6
..[ file ]
E 6
I 6
[
.B \-m
.I pattern
D 7
.B \-i
E 7
]
D 7
[ [ \fIN\fP% ] \fIfile\fP/\fIdir\fP/\fBall\fP ]
E 7
I 7
[ [
.IR N%
]
.I file/dir/all
]
E 7
E 6
.SH DESCRIPTION
E 11
I 11
.Dd %Q%
.Dt FORTUNE 6
.Os BSD 4
.Sh NAME
.Nm fortune
.Nd "print a random, hopefully interesting, adage"
.Sh SYNOPSIS
.Nm fortune
.Op Fl aefilosw
.Op Fl m Ar pattern
.Oo
.Op Ar \&N%
.Ar file/dir/all
.Oc
.Sh DESCRIPTION
E 11
D 6
.I Fortune
D 2
with no arguments
prints out a random adage. The flags mean:
.sp
E 2
I 2
with no arguments prints out a random adage. The flags mean:
E 6
I 6
When
D 11
.I fortune
E 11
I 11
.Nm fortune
E 11
D 7
is run with no arguments
it prints out a random epigram. The flags mean:
E 6
.PP
E 2
.TP 5
I 6
.B \-f
Print out the list of files
which would be searched,
but don't print a fortune.
E 6
.B \-w
D 6
Waits before termination
E 6
I 6
Wait before termination
E 6
for an amount of time calculated from the number of characters in the message.
This is useful if it is executed as part of the logout procedure
D 2
to guarantee that the message can be read
before the screen is cleared.
E 2
I 2
to guarantee that the message can be read before the screen is cleared.
E 2
.TP 5
.B \-s
D 6
Short messages only.
E 6
I 6
Short apothegms only.
E 6
.TP 5
.B \-l
D 6
Long messages only.
E 6
I 6
Long dictums only.
E 7
I 7
is run with no arguments it prints out a random epigram.
I 9
Epigrams are divided into several categories, where each category
is subdivided into those which are potentially offensive and those
which are not.
E 9
The options are as follows:
E 7
E 6
D 11
.TP
D 7
.B \-o
D 6
Choose from an alternate list of adages,
E 6
I 6
Choose from an alternate list of aphorisms,
E 6
D 2
often used for portentially offensive ones.
E 2
I 2
often used for potentially offensive ones.
E 2
.TP
E 7
.B \-a
E 11
I 11
.Bl -tag -width flag
.It Fl a
E 11
D 6
Choose from either list of adages.
E 6
I 6
D 9
Choose from either list of maxims.
E 9
I 9
Choose from all lists of maxims, both offensive and not.
I 12
(See the
.Fl o
option for more information on offensive fortunes.)
E 12
E 9
D 11
.TP
I 7
.B \-e
E 11
I 11
.It Fl e
E 11
Consider all fortune files to be of equal size (see discussion below
on multiple files).
D 11
.TP
.B \-f
E 11
I 11
.It Fl f
E 11
Print out the list of files which would be searched, but don't
print a fortune.
D 11
.TP
.B \-l
E 11
I 11
.It Fl l
E 11
Long dictums only.
D 11
.TP
E 7
.B \-m
E 11
I 11
.It Fl m
E 11
Print out all fortunes which match the regular expression
D 7
.I pattern .
E 7
I 7
D 11
.IR pattern .
E 11
I 11
.Ar pattern .
E 11
E 7
See
D 11
.BR regex (3)
E 11
I 11
.Xr regex 3
E 11
D 7
or
.BR regcmp (3)
for description of patterns.
E 7
I 7
for a description of patterns.
E 7
D 11
.TP
I 7
.B \-o
E 11
I 11
.It Fl o
E 11
D 9
Choose from an alternate list of potentially offensive aphorisms.
E 9
I 9
Choose only from potentially offensive aphorisms.
E 9
I 8
D 11
.ft B
E 11
I 11
.Bf -symbolic
E 11
D 9
Please, please, please do not request a potentially offensive fortune
if you do not believe, deep down in your heart, that you are willing
E 9
I 9
Please, please, please request a potentially offensive fortune if and
only if you believe, deep down in your heart, that you are willing
E 9
to be offended.
I 9
D 11
(And that if you are, you'll just quit using -o rather than give us
E 11
I 11
(And that if you are, you'll just quit using
.Fl o
rather than give us
E 11
grief about it, okay?)
E 9
D 11
.ft R
.PP
.in +5
E 11
I 11
.Ef
.Bd -filled -offset indent
E 11
\&... let us keep in mind the basic governing philosophy
of The Brotherhood, as handsomely summarized in these words:
we believe in healthy, hearty laughter -- at the expense of
the whole human race, if needs be.
Needs be.
D 11
.br
.in +10
-- H. Allen Smith, "Rude Jokes"
E 8
.TP
.B \-s
E 11
I 11
.Bd -filled -offset indent-two -compact
--H. Allen Smith, "Rude Jokes"
.Ed
.Ed
.It Fl s
E 11
Short apothegms only.
D 11
.TP
E 7
.B \-i
E 11
I 11
.It Fl i
E 11
Ignore case for
D 11
.B \-m
E 11
I 11
.Fl m
E 11
patterns.
D 11
.TP
D 7
.B \-e
Consider all fortune files to be of equal size
(see below on multiple files).
E 7
I 7
.B \-w
E 11
I 11
.It Fl w
E 11
Wait before termination for an amount of time calculated from the
number of characters in the message.
This is useful if it is executed as part of the logout procedure
to guarantee that the message can be read before the screen is cleared.
E 7
E 6
D 11
.PP
E 11
I 11
.El
.Pp
E 11
D 6
..The user may specify a file of adages.
..This file must be created by strfile(6),
..and be given by the user as
...it file.
..Only one such file may be named,
..subsequent ones are ignored.
E 6
I 6
The user may specify alternate sayings.
D 7
You can specify a specific file,
a directory which contains one or more files,
or the special word
E 7
I 7
You can specify a specific file, a directory which contains one or
more files, or the special word
E 7
D 11
.B all
E 11
I 11
.Em all
E 11
which says to use all the standard databases.
D 7
The files must be created
using
E 7
I 7
D 8
The files must be created using
E 7
.B strfile (8) .
E 8
D 7
Any of these may be preceded by a percentage,
which is a number
E 7
I 7
Any of these may be preceded by a percentage, which is a number
E 7
D 11
.I N
E 11
I 11
.Ar N
E 11
D 7
between 0 and 100 inclusive,
followed by a
E 7
I 7
between 0 and 100 inclusive, followed by a
E 7
D 11
.B % .
E 11
I 11
.Ar % .
E 11
D 7
If it is,
there will be a
E 7
I 7
If it is, there will be a
E 7
D 11
.I N
E 11
I 11
.Ar N
E 11
D 7
percent probability
that an adage will be picked from that file or directory.
If the percentages
do not sum to 100,
and there are specifications without percentages,
the remaining percent
will apply to those files and/or directories,
in which case
the probability of selecting from one of them
will be based on their relative sizes.
E 7
I 7
percent probability that an adage will be picked from that file
or directory.
If the percentages do not sum to 100, and there are specifications
without percentages, the remaining percent will apply to those files
and/or directories, in which case the probability of selecting from
one of them will be based on their relative sizes.
E 7
D 11
.PP
E 11
I 11
.Pp
E 11
D 7
As an example,
given two databases
E 7
I 7
As an example, given two databases
E 7
D 11
.B funny
E 11
I 11
.Em funny
E 11
and
D 11
.B not-funny ,
E 11
I 11
.Em not-funny ,
E 11
with
D 11
.B funny
E 11
I 11
.Em funny
E 11
D 7
twice as big,
saying
E 7
I 7
twice as big, saying
E 7
D 11
.RS
E 11
I 11
.Bd -literal -offset indent
E 11
fortune funny not-funny
D 11
.RE
E 11
I 11
.Ed
.Pp
E 11
will get you fortunes out of
D 11
.B funny
E 11
I 11
.Em funny
E 11
two-thirds of the time.
The command
D 11
.RS
E 11
I 11
.Bd -literal -offset indent
E 11
fortune 90% funny 10% not-funny
D 11
.RE
E 11
I 11
.Ed
.Pp
E 11
will pick out 90% of its fortunes from
D 11
.B funny
E 11
I 11
.Em funny
E 11
D 7
(the ``10% not-funny'' is unecessary,
since 10% is all that's left).
E 7
I 7
D 9
(the ``10% not-funny'' is unecessary, since 10% is all that's left).
E 9
I 9
(the ``10% not-funny'' is unnecessary, since 10% is all that's left).
E 9
E 7
The
D 11
.B \-e
E 11
I 11
.Fl e
E 11
option says to consider all files equal;
thus
D 11
.RS
fortune \-e
.RE
E 11
I 11
.Bd -literal -offset indent
fortune -e
.Ed
.Pp
E 11
is equivalent to
D 11
.RS
fortune 50% funny 50% not-funny
.RE
E 6
D 2
.sp
Mail suggestions for new fortunes to "fortune".
E 2
.SH FILES
D 2
/usr/lib/fortunes.dat
E 2
I 2
D 7
/usr/games/lib/fortunes.dat
E 7
I 7
/usr/share/games/fortune
E 7
E 2
.SH AUTHOR
Ken Arnold
D 6
...SH SEE\ ALSO
..strfile(6)
E 6
I 6
.SH "SEE ALSO"
regex(3), regcmp(3), strfile(8)
E 11
I 11
.Bd -literal -offset indent
D 15
fortune 50% funny 50% notEm -funny
E 15
I 15
fortune 50% funny 50% not
.Em -funny
E 15
.Ed
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /usr/share/games/fortune
.El
D 13
.Sh AUTHOR
.An Ken Arnold
E 13
.Sh SEE ALSO
.Xr regex 3 ,
.Xr regcmp 3 ,
D 16
.Xr strfile 8
E 16
E 11
E 6
E 1
