h37291
s 00006/00000/01334
d D 8.6 94/06/01 21:16:26 ah 25 24
c page breaks for 4.4BSD manuals
e
s 00001/00011/01333
d D 8.5 94/03/01 09:09:17 dab 24 23
c Change the synopsis line so that all the options
c that don't take arguments are combined rather than being
c listed one by one.
e
s 00388/00108/00956
d D 8.4 94/02/03 08:53:28 dab 23 22
c Update the manual page to reflect reality
e
s 00004/00000/01060
d D 8.3 94/01/05 12:26:40 mckusick 22 21
c describe the -E option
e
s 00008/00008/01052
d D 8.2 93/12/30 15:39:24 mckusick 21 20
c copyediting for Usenix manuals
e
s 00002/00002/01058
d D 8.1 93/06/06 16:33:30 bostic 20 19
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00274/00299/00786
d D 6.16 91/07/27 17:06:56 cael 19 18
c mdoc version three
e
s 00003/00003/01082
d D 6.15 91/06/03 13:10:13 sellgren 18 17
c fix escape character
e
s 00002/00000/01083
d D 6.14 91/03/14 00:28:06 cael 17 15
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/01083
d R 6.14 91/03/13 20:38:22 cael 16 15
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00004/00001/01079
d D 6.13 90/07/28 10:07:57 cael 15 14
c fix SYNOPSIS line
e
s 00024/00006/01056
d D 6.12 90/07/28 00:23:53 karels 14 13
x 13
c restore 6.10 changes, add -a and mods to environ
e
s 00007/00143/00919
d D 6.11 90/07/24 22:52:07 cael 13 12
c .Xr botch fix
e
s 00143/00007/00919
d D 6.10 90/06/28 12:58:15 borman 12 11
c Lots of bugfixes, add the ENVIRON and X-DISPLAY-LOC
c options, "-l user" to the command line, diagnostic flags.
e
s 00518/00547/00408
d D 6.9 90/06/11 06:00:53 cael 11 10
c converted man page
e
s 00022/00001/00933
d D 6.8 89/09/01 15:48:24 borman 10 9
c  RFC 1091 term type support, STATUS support, BINARY changes
e
s 00604/00264/00330
d D 6.7 89/08/22 09:13:30 borman 9 7
c Add support for LINEMODE option
e
s 00604/00264/00330
d R 6.7 89/08/22 09:06:26 borman 8 7
c Add support for the LINEMODE option
e
s 00015/00004/00579
d D 6.6 88/09/21 17:56:29 bostic 7 6
c Berkeley copyright notice
e
s 00001/00003/00582
d D 6.5 86/05/10 20:12:53 mckusick 6 5
c format
e
s 00039/00033/00546
d D 6.4 86/05/08 16:14:00 karels 5 4
c minor touchups
e
s 00519/00043/00060
d D 6.3 86/05/04 12:08:59 minshall 4 3
c This corresponds with the new, 4.3, telnet command.
e
s 00001/00000/00102
d D 6.2 86/02/05 05:03:15 lepreau 3 2
c ^D now == quit
e
s 00002/00002/00100
d D 6.1 85/04/29 21:17:54 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00102/00000/00000
d D 5.1 85/04/29 21:17:41 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 7
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 11
.\" Copyright (c) 1983 The Regents of the University of California.
E 11
I 11
D 20
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
E 11
.\" All rights reserved.
E 20
I 20
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 20
E 7
.\"
I 7
D 11
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 11
I 11
D 19
.\" %sccs.include.redist.man%
E 19
I 19
.\" %sccs.include.redist.roff%
E 19
E 11
.\"
E 7
D 11
.\"	%W% (Berkeley) %G%
E 11
I 11
D 19
.\"     %W% (Berkeley) %G%
E 19
I 19
.\"	%W% (Berkeley) %G%
E 19
E 11
.\"
I 17
D 19
.Vx
.Vx
E 19
E 17
D 2
.TH TELNET 1C "18 July 1983"
E 2
I 2
D 7
.TH TELNET 1C "%Q%"
E 7
I 7
D 11
.TH TELNET 1 "%Q%"
E 7
E 2
.UC 5
.SH NAME
D 4
telnet \- user interface to the TELNET protocol
E 4
I 4
D 6
telnet \- user interface to the
.B TELNET
protocol
E 6
I 6
D 9
telnet \- user interface to the \s-1TELNET\s0 protocol
E 9
I 9
telnet \- User interface to the \s-1TELNET\s0 protocol
E 9
E 6
E 4
.SH SYNOPSIS
D 9
telnet [ host [ port ] ]
E 9
I 9
\fBtelnet\fR [\fB\-d\fR] [\fB\-n \fItracefile\fR] [\fIhost\fR [\fIport\fR]]
E 9
.SH DESCRIPTION
E 11
I 11
.Dd %Q%
.Dt TELNET 1
.Os BSD 4.2
.Sh NAME
.Nm telnet
.Nd user interface to the 
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
protocol
.Sh SYNOPSIS
.Nm telnet
D 23
.Op Fl d
E 23
I 23
D 24
.Op Fl 8
.Op Fl E
.Op Fl F
.Op Fl K
.Op Fl L
E 24
I 24
.Op Fl 8EFKLacdfrx
E 24
.Op Fl S Ar tos
.Op Fl X Ar authtype
E 23
I 14
D 24
.Op Fl a
E 14
D 23
.Op Fl n Ar tracefile
E 23
I 23
.Op Fl c
.Op Fl d
E 24
E 23
I 12
D 13
D 14
.Op Fl l Ar user
E 14
.Op Fl e Ar escapechar
I 15
D 19
.Ob
E 19
I 19
D 23
.Oo
E 23
I 23
D 24
.Op Fl f
E 24
.Op Fl k Ar realm
E 23
E 19
E 15
I 14
.Op Fl l Ar user
I 23
.Op Fl n Ar tracefile
D 24
.Op Fl r
.Op Fl x
E 24
.Oo
E 23
E 14
E 13
E 12
D 15
.Op Ar host Op Ar port
E 15
I 15
.Ar host
.Op port
D 19
.Oe
E 19
I 19
.Oc
E 19
E 15
.Sh DESCRIPTION
E 11
D 9
.I Telnet
D 4
is used to communicate with another host using the TELNET protocol.  If 
E 4
I 4
is used to communicate with another host using the
.B TELNET
protocol.
E 9
I 9
The
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
command
D 11
is used to communicate with another host using the \s-1TELNET\s+1 protocol.
E 9
If 
E 4
D 9
.I telnet
is invoked without arguments, it enters command mode,
indicated by its prompt (\*(lqtelnet>\*(rq).
E 9
I 9
.B telnet
E 11
I 11
is used to communicate with another host using the 
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
protocol.
If
.Nm telnet
E 11
is invoked without the
D 11
.I host
E 11
I 11
.Ar host
E 11
argument, it enters command mode,
D 11
indicated by its prompt (\^\fBtelnet>\fR\^).
E 11
I 11
indicated by its prompt
.Pq Nm telnet\&> .
E 11
E 9
In this mode, it accepts and executes the commands listed below.
If it is invoked with arguments, it performs an
D 4
.I open
E 4
I 4
D 11
.B open
E 4
command (see below) with those arguments.
.PP
E 11
I 11
.Ic open
command with those arguments.
.Pp
Options:
D 19
.Tw Fl
.Tp Fl d
E 19
I 19
.Bl -tag -width indent
D 23
.It Fl d
E 19
Sets the initial value of the
.Ic debug
toggle to
D 19
.Li TRUE
I 14
.Tp Fl a
E 19
I 19
.Dv TRUE
E 23
I 23
.It Fl 8
Specifies an 8-bit data path.  This causes an attempt to
negotiate the
.Dv TELNET BINARY
option on both input and output.
.It Fl E
Stops any character from being recognized as an escape character.
.It Fl F
If Kerberos V5 authentication is being used, the
.Fl F
option allows the local credentials to be forwarded
to the remote system, including any credentials that
have already been forwarded into the local environment.
.It Fl K
Specifies no automatic login to the remote system.
.It Fl L
Specifies an 8-bit data path on output.  This causes the
BINARY option to be negotiated on output.
.It Fl S Ar tos
Sets the IP type-of-service (TOS) option for the telnet
connection to the value
.Ar tos,
which can be a numeric TOS value
or, on systems that support it, a symbolic
TOS name found in the /etc/iptos file.
.It Fl X Ar atype 
Disables the
.Ar atype
type of authentication.
E 23
.It Fl a
E 19
Attempt automatic login.
D 19
Currently, this sends the user name via the USER variable
of the ENVIRON option if supported by the remote system.
E 19
I 19
Currently, this sends the user name via the
.Ev USER
variable
of the
.Ev ENVIRON
option if supported by the remote system.
E 19
The name used is that of the current user as returned by
.Xr getlogin 2
if it agrees with the current user ID,
otherwise it is the name associated with the user ID.
E 14
D 19
.Tp Cx Fl n
.Cx \&\ \&
.Ar tracefile
.Cx
E 19
I 19
D 23
.It Fl n Ar tracefile 
E 19
Opens
.Ar tracefile
for recording trace information.
See the
.Ic set tracefile
command below.
E 23
I 23
.It Fl c
Disables the reading of the user's
.Pa \&.telnetrc
file.  (See the
.Ic toggle skiprc
command on this man page.)
.It Fl d
Sets the initial value of the
.Ic debug
toggle to
.Dv TRUE
.It Fl e Ar escape char 
Sets the initial
.Nm
.Nm telnet
escape character to
.Ar escape char.
If
.Ar escape char
is omitted, then
there will be no escape character.
.It Fl f
If Kerberos V5 authentication is being used, the
.Fl f
option allows the local credentials to be forwarded to the remote system.
I 25
.ne 1i
E 25
.It Fl k Ar realm
If Kerberos authentication is being used, the
.Fl k
option requests that telnet obtain tickets for the remote host in
realm realm instead of the remote host's realm, as determined
by
.Xr krb_realmofhost 3 .
E 23
I 12
D 13
D 19
.Tp Cx Fl l
.Cx \&\ \&
.Ar user
.Cx
E 19
I 19
.It Fl l Ar user 
E 19
When connecting to the remote system, if the remote system
D 19
understands the ENVIRON option, then
E 19
I 19
understands the
.Ev ENVIRON
option, then
E 19
.Ar user
will be sent to the remote system as the value for the variable USER.
I 14
This option implies the
.Fl a
option.
E 14
This option may also be used with the
.Ic open
command.
D 19
.Tp Cx Fl e
.Cx \&\ \&
.Ar escape char
.Cx
E 19
I 19
D 23
.It Fl e Ar escape char 
E 19
Sets the initial
.Nm
D 19
.B telnet
E 19
I 19
.Nm telnet
E 19
escape character to
.Ar escape char.
If
.Ar escape char
is ommitted, then
there will be no escape character.
I 22
.It Fl E
The
.Fl E
option stops any character from being recognized as an escape character.
E 23
I 23
.It Fl n Ar tracefile 
Opens
.Ar tracefile
for recording trace information.
See the
.Ic set tracefile
command below.
.It Fl r
Specifies a user interface similar to
.Xr rlogin 1 .
In this
mode, the escape character is set to the tilde (~) character,
unless modified by the -e option.
.It Fl x
Turns on encryption of the data stream if possible.  This
option is not available outside of the United States and
Canada.
E 23
E 22
E 13
E 12
D 19
.Tp Ar host
E 19
I 19
.It Ar host
E 19
Indicates the official name, an alias, or the Internet address
of a remote host.
D 19
.Tp Ar port
E 19
I 19
.It Ar port
E 19
Indicates a port number (address of an application).  If a number is
not specified, the default
.Nm telnet
port is used.
D 19
.Tp
E 19
I 19
.El
E 19
.Pp
I 23
When in rlogin mode, a line of the form ~.  disconnects from the
remote host; ~ is the telnet escape character.
Similarly, the line ~^Z suspends the telnet session.
The line ~^] escapes to the normal telnet escape prompt.
.Pp
E 23
E 11
Once a connection has been opened,
D 9
.I telnet
D 4
enters input mode.
In this mode, text typed is sent to the remote host.  To issue
E 4
I 4
enters an input mode.
The input mode entered will be either \*(lqcharacter at a time\*(rq
or \*(lqline by line\*(rq
E 9
I 9
D 11
\fBtelnet\fR
E 11
I 11
.Nm telnet
E 11
will attempt to enable the
D 11
\s-1TELNET LINEMODE\s+1
E 11
I 11
D 19
.Li TELNET LINEMODE
E 19
I 19
.Dv TELNET LINEMODE
E 19
E 11
option.
If this fails, then
D 11
\fBtelnet\fR
E 11
I 11
.Nm telnet
E 11
will revert to one of two input modes:
D 11
either \*(lqcharacter at a time\*(rq
or \*(lqold line by line\*(rq
E 11
I 11
either \*(Lqcharacter at a time\*(Rq
or \*(Lqold line by line\*(Rq
E 11
E 9
depending on what the remote system supports.
D 11
.PP
I 9
When \s-1LINEMODE\s+1 is enabled, character processing is done on the
E 11
I 11
.Pp
When 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
is enabled, character processing is done on the
E 11
local system, under the control of the remote system.  When input
editing or character echoing is to be disabled, the remote system
will relay that information.  The remote system will also relay
changes to any special characters that happen on the remote
system, so that they can take effect on the local system.
D 11
.PP
E 9
In \*(lqcharacter at a time\*(rq mode, most
E 11
I 11
.Pp
In \*(Lqcharacter at a time\*(Rq mode, most
E 11
text typed is immediately sent to the remote host for processing.
D 11
.PP
D 9
In \*(lqline by line\*(rq mode, all text is echoed locally,
E 9
I 9
In \*(lqold line by line\*(rq mode, all text is echoed locally,
E 11
I 11
.Pp
In \*(Lqold line by line\*(Rq mode, all text is echoed locally,
E 11
E 9
and (normally) only completed lines are sent to the remote host.
D 11
The \*(lqlocal echo character\*(rq (initially \*(lq^E\*(rq) may be used
E 11
I 11
The \*(Lqlocal echo character\*(Rq (initially \*(Lq^E\*(Rq) may be used
E 11
to turn off and on the local echo
(this would mostly be used to enter passwords
without the password being echoed).
D 11
.PP
D 9
In either mode, if the
.I localchars
D 5
toggle (see below) is TRUE,
E 5
I 5
toggle is TRUE (the default in line mode; see below),
E 9
I 9
If the \s-1LINEMODE\s+1 option is enabled, or if the
.B localchars
toggle is TRUE (the default for \*(lqold line by line\*(lq; see below),
E 11
I 11
.Pp
If the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option is enabled, or if the
.Ic localchars
D 19
toggle is TRUE (the default for \*(Lqold line by line\*(Lq; see below),
E 19
I 19
toggle is
.Dv TRUE
(the default for \*(Lqold line by line\*(Lq; see below),
E 19
E 11
E 9
E 5
the user's
D 9
.IR quit ,
.IR intr ,
E 9
I 9
D 11
.BR quit ,
.BR intr ,
E 11
I 11
.Ic quit  ,
.Ic intr ,
E 11
E 9
and
D 9
.I flush
E 9
I 9
D 11
.B flush
E 11
I 11
.Ic flush
E 11
E 9
characters are trapped locally, and sent as
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
protocol sequences to the remote side.
I 9
D 11
If \s-1LINEMODE\s+1 has ever been enabled, then the user's
.B susp
E 11
I 11
If 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
has ever been enabled, then the user's
.Ic susp
E 11
and
D 11
.B eof
E 11
I 11
.Ic eof
E 11
are also sent as
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
protocol sequences,
and
D 11
.B quit
is sent as a \s-1TELNET ABORT\s+1 instead of \s-1BREAK\s+1.
E 11
I 11
.Ic quit
is sent as a 
D 19
.Li TELNET ABORT
E 19
I 19
.Dv TELNET ABORT
E 19
instead of 
D 19
.Li BREAK
E 19
I 19
.Dv BREAK
E 19
E 11
E 9
There are options (see
D 11
.B toggle
D 9
.I autoflush
E 9
I 9
.B autoflush
E 11
I 11
.Ic toggle
.Ic autoflush
E 11
E 9
and
D 11
.B toggle
D 9
.I autosynch
E 9
I 9
.B autosynch
E 11
I 11
.Ic toggle
.Ic autosynch
E 11
E 9
below)
which cause this action to flush subsequent output to the terminal
(until the remote host acknowledges the
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
sequence) and flush previous terminal input
(in the case of
D 9
.I quit
E 9
I 9
D 11
.B quit
E 11
I 11
.Ic quit
E 11
E 9
and
D 9
.IR intr ).
E 9
I 9
D 11
.BR intr ).
E 9
.PP
E 11
I 11
.Ic intr  ) .
.Pp
E 11
While connected to a remote host,
E 4
D 9
.I telnet
E 9
I 9
D 11
\fBtelnet\fR
E 11
I 11
.Nm telnet
E 11
E 9
D 4
commands when in input mode, precede them with the
E 4
I 4
command mode may be entered by typing the
E 4
D 9
.I telnet
E 9
I 9
D 11
\fBtelnet\fR
E 9
D 2
\*(lqescape character\*(rq (initially \*(lq^[\*(rq).
E 2
I 2
\*(lqescape character\*(rq (initially \*(lq^]\*(rq).
E 11
I 11
.Nm telnet
D 18
\*(Lqescape character\*(Rq (initially \*(Lq^
\*(Rq).
E 18
I 18
\*(Lqescape character\*(Rq (initially \*(Lq^]\*(Rq).
E 18
E 11
E 2
When in command mode, the normal terminal editing conventions are available.
D 11
.PP
I 4
D 9
.B COMMANDS
E 9
I 9
Options:
.TP 8
\fB\-d\fR
Sets the initial value of the \fBdebug\fR toggle to \s-1TRUE\s+1.
.TP
\fB\-n\fI tracefile\fR
Opens \fItracefile\fR for recording trace information.
See the \fBset tracefile\fR command below.
.TP
\fIhost\fR
Indicates the official name, an alias, or the Internet address
of a remote host.
.TP
\fIport\fR
Indicates a port number (address of an application).  If a number is
not specified, the default \fBtelnet\fR port is used.
E 9
.PP
E 4
D 9
The following commands are available.
E 9
I 9
The following \fBtelnet\fR commands are available.
E 11
I 11
.Pp
D 18
The following .Nm telnet
E 18
I 18
The following
.Nm telnet
E 18
commands are available.
E 11
E 9
D 4
Only enough of each command to uniquely identify it need be typed.
E 4
I 4
Only enough of each command to uniquely identify it need be typed
(this is also true for arguments to the
D 11
.BR mode ,
.BR set ,
.BR toggle ,
I 9
.BR unset ,
.BR slc ,
E 11
I 11
.Ic mode  ,
.Ic set ,
.Ic toggle  ,
.Ic unset ,
.Ic slc  ,
I 12
D 13
.Ic environ ,
E 13
E 12
E 11
E 9
and
D 11
.B display
E 11
I 11
.Ic display
E 11
commands).
E 4
D 11
.PP
D 9
.TP
D 4
\fBopen\fP \fIhost\fP [ \fIport\fP ]
Open a connection to the named host.  If the no port number
E 4
I 4
.B open \fIhost\fP \fR[\fP \fIport\fP \fR]\fP
.br
Open a connection to the named host.
If no port number
E 4
is specified, 
.I telnet
D 4
will attempt to contact a TELNET server at the default port.
E 4
I 4
will attempt to contact a
.B TELNET
server at the default port.
E 4
The host specification may be either a host name (see 
.IR hosts (5))
D 4
or an Internet address specified in the \*(lqdot notation\*(rq.
E 4
I 4
or an Internet address specified in the \*(lqdot notation\*(rq (see
.IR inet (3N)).
E 4
.TP
E 9
I 9
.TP 10
E 9
.B close
D 4
Close a TELNET session and return to command mode.
E 4
I 4
.br
E 11
I 11
.Pp
D 19
.Tw Ic
.Tp Ic close
E 19
I 19
.Bl -tag -width "mode type"
I 23
.It Ic auth Ar argument ... 
The auth command manipulates the information sent through the
.Dv TELNET AUTHENTICATE
option.  Valid arguments for the
auth command are as follows:
.Bl -tag -width "disable type"
.It Ic disable Ar type
Disables the specified type of authentication.  To
obtain a list of available types, use the
.Ic auth disable \&?
command.
.It Ic enable Ar type
Enables the specified type of authentication.  To
obtain a list of available types, use the
.Ic auth enable \&?
command.
.It Ic status
Lists the current status of the various types of
authentication.
.El
E 23
.It Ic close
E 19
E 11
Close a
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
session and return to command mode.
E 4
D 11
.TP
D 9
.B quit
E 9
I 9
.B display \fR[\fP \fIargument...\fP \fR]\fP
E 9
D 4
Close any open TELNET session and exit 
E 4
I 4
.br
E 11
I 11
D 19
.Tp Cx Ic display
.Cx \&\ \&
.Ar argument ...
.Cx
E 19
I 19
.It Ic display Ar argument ... 
E 19
E 11
D 9
Close any open
.B TELNET
session and exit 
E 4
.IR telnet .
I 3
An end of file (in command mode) will also close a session and exit.
E 9
I 9
Displays all, or some, of the
D 11
.B set
E 11
I 11
.Ic set
E 11
and
D 11
.B toggle
E 11
I 11
.Ic toggle
E 11
values (see below).
I 23
.It Ic encrypt Ar argument ...
The encrypt command manipulates the information sent through the
.Dv TELNET ENCRYPT
option.
.Pp
Note:  Because of export controls, the
.Dv TELNET ENCRYPT
option is not supported outside of the United States and Canada.
.Pp
Valid arguments for the encrypt command are as follows:
.Bl -tag -width Ar
.It Ic disable Ar type Ic [input|output]
Disables the specified type of encryption.  If you
omit the input and output, both input and output
are disabled.  To obtain a list of available
types, use the
.Ic encrypt disable \&?
command.
.It Ic enable Ar type Ic [input|output]
Enables the specified type of encryption.  If you
omit input and output, both input and output are
enabled.  To obtain a list of available types, use the
.Ic encrypt enable \&?
command.
.It Ic input
This is the same as the
.Ic encrypt start input
command.
.It Ic -input
This is the same as the
.Ic encrypt stop input
command.
.It Ic output
This is the same as the
.Ic encrypt start output
command.
.It Ic -output
This is the same as the
.Ic encrypt stop output
command.
.It Ic start Ic [input|output]
Attempts to start encryption.  If you omit
.Ic input
and
.Ic output,
both input and output are enabled.  To
obtain a list of available types, use the
.Ic encrypt enable \&?
command.
.It Ic status
Lists the current status of encryption.
.It Ic stop Ic [input|output]
Stops encryption.  If you omit input and output,
encryption is on both input and output.
.It Ic type Ar type
Sets the default type of encryption to be used
with later
.Ic encrypt start
or
.Ic encrypt stop
commands.
.El
.It Ic environ Ar arguments... 
The
.Ic environ
command is used to manipulate the
the variables that my be sent through the
.Dv TELNET ENVIRON
option.
The initial set of variables is taken from the users
environment, with only the
.Ev DISPLAY
and
.Ev PRINTER
variables being exported by default.
The
.Ev USER
variable is also exported if the
.Fl a
or
.Fl l
options are used.
.br
Valid arguments for the
.Ic environ
command are:
.Bl -tag -width Fl
.It Ic define Ar variable value 
Define the variable
.Ar variable
to have a value of
.Ar value.
Any variables defined by this command are automatically exported.
The
.Ar value
may be enclosed in single or double quotes so
that tabs and spaces may be included.
.It Ic undefine Ar variable 
Remove
.Ar variable
from the list of environment variables.
.It Ic export Ar variable 
Mark the variable
.Ar variable
to be exported to the remote side.
.It Ic unexport Ar variable 
Mark the variable
.Ar variable
to not be exported unless
explicitly asked for by the remote side.
.It Ic list
List the current set of environment variables.
Those marked with a
.Cm *
will be sent automatically,
other variables will only be sent if explicitly requested.
.It Ic \&?
Prints out help information for the
.Ic environ
command.
.El
.It Ic logout
Sends the
.Dv TELNET LOGOUT
option to the remote side.
This command is similar to a
.Ic close
command; however, if the remote side does not support the
.Dv LOGOUT
option, nothing happens.
If, however, the remote side does support the
.Dv LOGOUT
option, this command should cause the remote side to close the
.Tn TELNET
connection.
If the remote side also supports the concept of
suspending a user's session for later reattachment,
the logout argument indicates that you
should terminate the session immediately.
E 23
E 9
E 3
D 11
.TP
D 9
.B z
I 4
.br
E 4
Suspend
.IR telnet .
This command only works when the user is using the 
.IR csh (1).
.TP
E 9
D 4
\fBescape\fP [ \fIescape-char\fP ]
Set the 
.I telnet
\*(lqescape character\*(rq.  Control characters may
be specified as \*(lq^\*(rq followed by a single
letter; e.g. \*(lqcontrol-X\*(rq is \*(lq^X\*(rq.
E 4
I 4
.B mode \fItype\fP
.br
.I Type
E 11
I 11
D 19
.Tp Cx Ic mode
.Cx \&\ \&
.Ar type
.Cx
E 19
I 19
.It Ic mode Ar type 
E 19
.Ar Type
E 11
D 9
is either
.I line
(for \*(lqline by line\*(rq mode)
or
.I character
(for \*(lqcharacter at a time\*(rq mode).
E 9
I 9
is one of several options, depending on the state of the
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
session.
E 9
The remote host is asked for permission to go into the requested mode.
If the remote host is capable of entering that mode, the requested
mode will be entered.
I 9
D 11
.RS 10
E 9
E 4
.TP
D 9
.B status
E 9
I 9
.B character
E 9
I 4
.br
E 11
I 11
D 19
.Tw Ar
.Tp Ic character
E 19
I 19
.Bl -tag -width Ar
.It Ic character
E 19
E 11
E 4
D 9
Show the current status of 
.IR telnet .
This includes the peer one is connected to, as well
D 4
as the state of debugging.
E 4
I 4
as the current mode.
E 9
I 9
Disable the
D 11
\s-1TELNET LINEMODE\s+1
E 11
I 11
D 19
.Li TELNET LINEMODE
E 19
I 19
.Dv TELNET LINEMODE
E 19
E 11
option, or, if the remote side does not understand the
D 11
\s-1LINEMODE\s+1
option, then enter \*(lqcharacter at a time\*(lq mode.
E 9
E 4
.TP
D 4
.B options
Toggle viewing of TELNET options processing.  When
options viewing is enabled, all TELNET option negotiations
will be displayed.  Options sent by 
.I telnet
are displayed as \*(lqSENT\*(rq, while options
received from the TELNET server are displayed as
\*(lqRCVD\*(rq.
E 4
I 4
D 9
.B display \fR[\fP \fIargument...\fP \fR]\fP
E 9
I 9
.B line
E 9
.br
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option, then enter \*(Lqcharacter at a time\*(Lq mode.
D 19
.Tp Ic line
E 19
I 19
.It Ic line
E 19
E 11
D 9
Displays all, or some, of the
.B set
and
.B toggle
values (see below).
E 9
I 9
Enable the
D 11
\s-1TELNET LINEMODE\s+1
E 11
I 11
D 19
.Li TELNET LINEMODE
E 19
I 19
.Dv TELNET LINEMODE
E 19
E 11
option, or, if the remote side does not understand the
D 11
\s-1LINEMODE\s+1
option, then attempt to enter \*(lqold-line-by-line\*(lq mode.
E 9
E 4
.TP
D 4
.B crmod
Toggle carriage return mode.  When this mode is enabled
any carriage return characters received from the remote
host will be mapped into a carriage return and a line
feed.  This mode does not affect those characters typed
by the user, only those received.  This mode is not very
useful, but is required for some hosts that like to ask
the user to do local echoing.
.TP
\fB?\fP [ \fIcommand\fP ]
E 4
I 4
D 9
.B ? \fR[\fP \fIcommand\fP \fR]\fP
E 9
I 9
.B isig (-isig)
E 9
.br
E 4
D 9
Get help.  With no arguments,
.I telnet
prints a help summary.
If a command is specified, 
.I telnet
D 4
will print the help information available about the command only.
E 4
I 4
will print the help information for just that command.
E 9
I 9
Attempt to enable (disable) the \s-1TRAPSIG\s+1 mode of the \s-1LINEMODE\s+1 option.
This requires that the \s-1LINEMODE\s+1 option be enabled.
E 9
.TP
I 9
.B edit (-edit)
.br
Attempt to enable (disable) the \s-1EDIT\s+1 mode of the \s-1LINEMODE\s+1 option.
This requires that the \s-1LINEMODE\s+1 option be enabled.
.TP
.B ?
.br
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option, then attempt to enter \*(Lqold-line-by-line\*(Lq mode.
D 19
.Tp Cx Ic isig
.Cx \&\ \&
.Pq Ic \-isig
.Cx
E 19
I 19
.It Ic isig Pq Ic \-isig 
E 19
Attempt to enable (disable) the 
D 19
.Li TRAPSIG
E 19
I 19
.Dv TRAPSIG
E 19
mode of the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option.
This requires that the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option be enabled.
D 19
.Tp Cx Ic edit
.Cx \&\ \&
.Pq Ic \-edit
.Cx
E 19
I 19
.It Ic edit Pq Ic \-edit 
E 19
Attempt to enable (disable) the 
D 19
.Li EDIT
E 19
I 19
.Dv EDIT
E 19
mode of the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option.
This requires that the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option be enabled.
I 12
D 13
D 19
.Tp Cx Ic softtabs
.Cx \&\ \&
.Pq Ic \-softtabs
.Cx
E 19
I 19
.It Ic softtabs Pq Ic \-softtabs 
E 19
Attempt to enable (disable) the 
D 19
.Li SOFT_TAB
E 19
I 19
.Dv SOFT_TAB
E 19
mode of the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option.
This requires that the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option be enabled.
I 25
.ne 1i
E 25
D 19
.Tp Cx Ic litecho
.Cx \&\ \&
.Pq Ic \-litecho
.Cx
E 19
I 19
.It Ic litecho Pq Ic \-litecho 
E 19
Attempt to enable (disable) the 
D 19
.Li LIT_ECHO
E 19
I 19
.Dv LIT_ECHO
E 19
mode of the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option.
This requires that the 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
option be enabled.
E 13
E 12
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
E 11
Prints out help information for the
D 11
.B mode
E 11
I 11
.Ic mode
E 11
command.
D 11
.RE
.TP
.B open \fIhost\fP \fR[\fP [\fI-\fP]\fIport\fP \fR]\fP
.br
E 11
I 11
D 19
.Tp
.Tp Cx Ic open
.Cx \&\ \&
.Ar host
.Cx \&\ \&
.Cx [
I 12
D 13
.Op Fl l
.Cx \&\ \&
E 19
I 19
.El
.It Xo
.Ic open Ar host
.Oo Op Fl l
E 19
.Ar user
D 19
.Cx ]
.Cx [
E 13
E 12
.Op Fl
.Cx \&\ \&
.Ar port
.Cx ]
.Cx
E 19
I 19
.Oc Ns Oo Fl
.Ar port Oc
.Xc
E 19
E 11
Open a connection to the named host.
If no port number
D 11
is specified, 
\fBtelnet\fR
E 11
I 11
is specified,
.Nm telnet
E 11
will attempt to contact a
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
server at the default port.
D 11
The host specification may be either a host name (see 
.BR hosts (5))
or an Internet address specified in the \*(lqdot notation\*(rq (see
.BR inet (3N)).
E 11
I 11
The host specification may be either a host name (see
.Xr hosts  5  )
or an Internet address specified in the \*(Lqdot notation\*(Rq (see
.Xr inet 3 ) .
I 12
D 13
The
.Op Fl l
option may be used to specify the user name
to be passed to the remote system via the
D 19
.Li ENVIRON
E 19
I 19
.Ev ENVIRON
E 19
option.
E 13
E 12
E 11
When connecting to a non-standard port,
D 11
\fBtelnet\fR
E 11
I 11
.Nm telnet
E 11
omits any automatic initiation of
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
D 23
options.  When the port number is preceeded by a minus sign,
the inital option negotiation is done.
E 23
I 23
options.  When the port number is preceded by a minus sign,
the initial option negotiation is done.
E 23
D 11
After establishing a connection, the \fB.telnetrc\fP in the
E 11
I 11
After establishing a connection, the file
.Pa \&.telnetrc
in the
E 11
D 23
users home directory is opened.  Lines begining with a # are
E 23
I 23
users home directory is opened.  Lines beginning with a # are
E 23
comment lines.  Blank lines are ignored.  Lines that begin
D 23
without whitespace are the start of a machine entry.  The
E 23
I 23
without white space are the start of a machine entry.  The
E 23
first thing on the line is the name of the machine that is
being connected to.  The rest of the line, and successive
D 23
lines that begin with whitespace are assumed to be
E 23
I 23
lines that begin with white space are assumed to be
E 23
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
commands and are processed as if they had been typed
in manually to the
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
command prompt.
D 11
.TP
.B quit
.br
E 11
I 11
D 19
.Tp Ic quit
E 19
I 19
.It Ic quit
E 19
E 11
Close any open
D 11
\s-1TELNET\s+1
session and exit 
.BR telnet .
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
session and exit
.Nm telnet  .
E 11
An end of file (in command mode) will also close a session and exit.
D 11
.TP
E 9
.B send \fIarguments\fP
.br
E 11
I 11
D 19
.Tp Cx Ic send
.Cx \&\ \&
.Ar arguments
.Cx
E 19
I 19
.It Ic send Ar arguments 
E 19
E 11
Sends one or more special character sequences to the remote host.
The following are the arguments which may be specified
(more than one argument may be specified at a time):
D 11
.RS
.TP
D 9
.I escape
E 9
I 9
.B abort
E 9
.br
E 11
I 11
.Pp
D 19
.Tw Ds
.Tp Ic abort
E 19
I 19
.Bl -tag -width escape
.It Ic abort
E 19
E 11
D 9
Sends the current
.I telnet
escape character (initially \*(lq^]\*(rq).
.TP
.I synch
.br
E 9
Sends the
D 9
.B TELNET SYNCH
E 9
I 9
D 11
\s-1TELNET ABORT\s+1
E 11
I 11
D 19
.Li TELNET ABORT
E 11
(ABORT processes)
E 19
I 19
.Dv TELNET ABORT
(Abort
processes)
E 19
E 9
sequence.
D 9
This sequence causes the remote system to discard all previously typed
(but not yet read) input.
This sequence is sent as TCP urgent
data (and may not work if the remote system is a 4.2 BSD system -- if
it doesn't work, a lower case \*(lqr\*(rq may be echoed on the terminal).
E 9
D 11
.TP
D 9
.I brk
E 9
I 9
.B ao
E 9
.br
E 11
I 11
D 19
.Tp Ic ao
E 19
I 19
.It Ic ao
E 19
E 11
Sends the
D 9
.B TELNET BRK
(Break) sequence, which may have significance to the remote
system.
.TP
.I ip
.br
Sends the
.B TELNET IP
D 5
(Interrupt Process) sequence, which hopefully will cause the remote
E 5
I 5
(Interrupt Process) sequence, which should cause the remote
E 5
system to abort the currently running process.
.TP
.I ao
.br
Sends the
.B TELNET AO
E 9
I 9
D 11
\s-1TELNET AO\s+1
E 11
I 11
D 19
.Li TELNET AO
E 19
I 19
.Dv TELNET AO
E 19
E 11
E 9
(Abort Output) sequence, which should cause the remote system to flush
all output
D 11
.B from
E 11
I 11
.Em from
E 11
the remote system
D 11
.B to
E 11
I 11
.Em to
E 11
the user's terminal.
D 11
.TP
D 9
.I ayt
E 9
I 9
.B ayt
E 9
.br
E 11
I 11
D 19
.Tp Ic ayt
E 19
I 19
.It Ic ayt
E 19
E 11
Sends the
D 9
.B TELNET AYT
E 9
I 9
D 11
\s-1TELNET AYT\s+1
E 11
I 11
D 19
.Li TELNET AYT
E 19
I 19
.Dv TELNET AYT
E 19
E 11
E 9
(Are You There)
D 5
sequence, which the remote system may or may not choose to respond to.
E 5
I 5
sequence, to which the remote system may or may not choose to respond.
E 5
D 11
.TP
D 9
.I ec
E 9
I 9
.B brk
E 9
.br
E 11
I 11
D 19
.Tp Ic brk
E 19
I 19
.It Ic brk
E 19
E 11
Sends the
D 9
.B TELNET EC
E 9
I 9
D 11
\s-1TELNET BRK\s+1
E 11
I 11
D 19
.Li TELNET BRK
E 19
I 19
.Dv TELNET BRK
E 19
E 11
(Break) sequence, which may have significance to the remote
system.
D 11
.TP
.B ec
.br
E 11
I 11
D 19
.Tp Ic ec
E 19
I 19
.It Ic ec
E 19
E 11
Sends the
D 11
\s-1TELNET EC\s+1
E 11
I 11
D 19
.Li TELNET EC
E 19
I 19
.Dv TELNET EC
E 19
E 11
E 9
(Erase Character)
sequence, which should cause the remote system to erase the last character
entered.
D 11
.TP
D 9
.I el
E 9
I 9
.B el
E 9
.br
E 11
I 11
D 19
.Tp Ic el
E 19
I 19
.It Ic el
E 19
E 11
Sends the
D 9
.B TELNET EL
E 9
I 9
D 11
\s-1TELNET EL\s+1
E 11
I 11
D 19
.Li TELNET EL
E 19
I 19
.Dv TELNET EL
E 19
E 11
E 9
(Erase Line)
sequence, which should cause the remote system to erase the line currently
being entered.
D 11
.TP
D 9
.I ga
E 9
I 9
.B eof
E 9
.br
E 11
I 11
D 19
.Tp Ic eof
E 19
I 19
.It Ic eof
E 19
E 11
Sends the
D 9
.B TELNET GA
E 9
I 9
D 11
\s-1TELNET EOF\s+1
E 11
I 11
D 19
.Li TELNET EOF
E 19
I 19
.Dv TELNET EOF
E 19
E 11
(End Of File)
sequence.
D 11
.TP
.B eor
.br
E 11
I 11
D 19
.Tp Ic eor
E 19
I 19
.It Ic eor
E 19
E 11
Sends the
D 11
\s-1TELNET EOR\s+1
E 11
I 11
D 19
.Li TELNET EOR
E 19
I 19
.Dv TELNET EOR
E 19
E 11
(End of Record)
sequence.
D 11
.TP
.B escape
.br
E 11
I 11
D 19
.Tp Ic escape
E 19
I 19
.It Ic escape
E 19
E 11
Sends the current
D 11
.B telnet
escape character (initially \*(lq^]\*(rq).
.TP
.B ga
.br
E 11
I 11
.Nm telnet
escape character (initially \*(Lq^\*(Rq).
D 19
.Tp Ic ga
E 19
I 19
.It Ic ga
E 19
E 11
Sends the
D 11
\s-1TELNET GA\s+1
E 11
I 11
D 19
.Li TELNET GA
E 19
I 19
.Dv TELNET GA
E 19
E 11
E 9
(Go Ahead)
sequence, which likely has no significance to the remote system.
D 11
.TP
I 10
.B getstatus
.br
E 11
I 11
D 19
.Tp Ic getstatus
E 19
I 19
.It Ic getstatus
E 19
E 11
If the remote side supports the
D 11
\s-1TELNET STATUS\s+1
E 11
I 11
D 19
.Li TELNET STATUS
E 19
I 19
.Dv TELNET STATUS
E 19
E 11
command,
D 11
.B getstatus
E 11
I 11
.Ic getstatus
E 11
will send the subnegotiation to request that the server send
its current option status.
I 25
.ne 1i
E 25
D 11
.TP
E 10
D 9
.I nop
E 9
I 9
.B ip
E 9
.br
E 11
I 11
D 19
.Tp Ic ip
E 19
I 19
.It Ic ip
E 19
E 11
Sends the
D 9
.B TELNET NOP
E 9
I 9
D 11
\s-1TELNET IP\s+1
E 11
I 11
D 19
.Li TELNET IP
E 19
I 19
.Dv TELNET IP
E 19
E 11
(Interrupt Process) sequence, which should cause the remote
system to abort the currently running process.
D 11
.TP
.B nop
.br
E 11
I 11
D 19
.Tp Ic nop
E 19
I 19
.It Ic nop
E 19
E 11
Sends the
D 11
\s-1TELNET NOP\s+1
E 11
I 11
D 19
.Li TELNET NOP
E 19
I 19
.Dv TELNET NOP
E 19
E 11
E 9
(No OPeration)
sequence.
D 11
.TP
D 9
.I ?
E 9
I 9
.B susp
E 9
.br
E 11
I 11
D 19
.Tp Ic susp
E 19
I 19
.It Ic susp
E 19
E 11
I 9
Sends the
D 11
\s-1TELNET SUSP\s+1
E 11
I 11
D 19
.Li TELNET SUSP
E 19
I 19
.Dv TELNET SUSP
E 19
E 11
(SUSPend process)
sequence.
D 11
.TP
.B synch
.br
E 11
I 11
D 19
.Tp Ic synch
E 19
I 19
.It Ic synch
E 19
E 11
Sends the
D 11
\s-1TELNET SYNCH\s+1
E 11
I 11
D 19
.Li TELNET SYNCH
E 19
I 19
.Dv TELNET SYNCH
E 19
E 11
sequence.
This sequence causes the remote system to discard all previously typed
(but not yet read) input.
D 19
This sequence is sent as TCP urgent
data (and may not work if the remote system is a 4.2 BSD system -- if
E 19
I 19
This sequence is sent as
.Tn TCP
urgent
data (and may not work if the remote system is a
.Bx 4.2
system -- if
E 19
D 11
it doesn't work, a lower case \*(lqr\*(rq may be echoed on the terminal).
.TP
.B ?
.br
E 11
I 11
it doesn't work, a lower case \*(Lqr\*(Rq may be echoed on the terminal).
I 23
.It Ic do Ar cmd
.It Ic dont Ar cmd
.It Ic will Ar cmd
.It Ic wont Ar cmd
Sends the
.Dv TELNET DO
.Ar cmd
sequence.
.Ar Cmd
can be either a decimal number between 0 and 255,
or a symbolic name for a specific
.Dv TELNET
command.
.Ar Cmd
can also be either
.Ic help
or
.Ic \&?
to print out help information, including
a list of known symbolic names.
E 23
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
E 11
E 9
Prints out help information for the
D 11
.B send
E 11
I 11
.Ic send
E 11
command.
D 11
.RE
.TP
.B set \fIargument value\fP
I 9
.TP
.B unset \fIarguments...\fP
E 9
.br
E 11
I 11
D 19
.Tp
.Tp Cx Ic set
.Cx \&\ \&
.Ar argument value
.Cx
.Tp Cx Ic unset
.Cx \&\ \&
.Ar argument value
.Cx
E 19
I 19
.El
.It Ic set Ar argument value 
.It Ic unset Ar argument value 
E 19
E 11
D 9
Set any one of a number of
.I telnet
variables to a specific value.
The special value \*(lqoff\*(rq turns off the function associated with
the variable.
E 9
I 9
The
D 11
.B set
E 11
I 11
.Ic set
E 11
command will set any one of a number of
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
D 19
variables to a specific value or to TRUE.
E 19
I 19
variables to a specific value or to
.Dv TRUE .
E 19
D 11
The special value \fBoff\fP turns off the function associated with
E 11
I 11
The special value
.Ic off
turns off the function associated with
E 11
the variable, this is equivalent to using the
D 11
.B unset
E 11
I 11
.Ic unset
E 11
command.
The
D 11
.B unset
E 11
I 11
.Ic unset
E 11
D 19
command will disable or set to FALSE any of the specified functions.
E 19
I 19
command will disable or set to
.Dv FALSE
any of the specified functions.
E 19
E 9
I 5
The values of variables may be interrogated with the
D 11
.B display
E 11
I 11
.Ic display
E 11
command.
E 5
D 9
The variables which may be specified are:
E 9
I 9
The variables which may be set or unset, but not toggled, are
listed here.  In addition, any of the variables for the
D 11
\fBtoggle\fP command may be explicitly set or unset using
the \fBset\fP and \fBunset\fP commands.
E 9
.RS
.TP
D 9
.I echo
E 9
I 9
.B echo
E 9
.br
This is the value (initially \*(lq^E\*(rq) which, when in
\*(lqline by line\*(rq mode, toggles between doing local echoing
E 11
I 11
.Ic toggle
command may be explicitly set or unset using
the
.Ic set
and
.Ic unset
commands.
D 19
.Tw Fl
.Tp Ic echo
E 19
I 19
.Bl -tag -width escape
I 23
.It Ic ayt
If
.Tn TELNET
is in localchars mode, or
.Dv LINEMODE
is enabled, and the status character is typed, a
.Dv TELNET AYT
sequence (see
.Ic send ayt
preceding) is sent to the
remote host.  The initial value for the "Are You There"
character is the terminal's status character.
E 23
.It Ic echo
E 19
This is the value (initially \*(Lq^E\*(Rq) which, when in
\*(Lqline by line\*(Rq mode, toggles between doing local echoing
E 11
of entered characters (for normal processing), and suppressing
echoing of entered characters (for entering, say, a password).
D 11
.TP
D 9
.I escape
E 9
I 9
.B eof
E 9
.br
E 11
I 11
D 19
.Tp Ic eof
E 19
I 19
.It Ic eof
E 19
E 11
D 9
This is the
.I telnet
escape character (initially \*(lq^[\*(rq) which causes entry
into
.I telnet
command mode (when connected to a remote system).
E 9
I 9
If
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
is operating in
D 11
\s-1LINEMODE\s+1
or \*(lqold line by line\*(rq mode, entering this character
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
or \*(Lqold line by line\*(Rq mode, entering this character
E 11
as the first character on a line will cause this character to be
sent to the remote system.
The initial value of the eof character is taken to be the terminal's
D 11
.B eof
E 11
I 11
.Ic eof
E 11
character.
E 9
D 11
.TP
D 9
.I interrupt
E 9
I 9
.B erase
E 9
.br
E 11
I 11
D 19
.Tp Ic erase
E 19
I 19
.It Ic erase
E 19
E 11
If
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
is in
D 11
.I localchars
E 11
I 11
.Ic localchars
E 11
mode (see
D 11
.B toggle
D 9
.I localchars
below)
and the
.I interrupt
E 9
I 9
.B localchars
E 11
I 11
.Ic toggle
.Ic localchars
E 11
below),
D 11
.B and
E 11
I 11
.Sy and
E 11
if
D 11
.B telnet
is operating in \*(lqcharacter at a time\*(rq mode, then when this
E 11
I 11
.Nm telnet
is operating in \*(Lqcharacter at a time\*(Rq mode, then when this
E 11
E 9
character is typed, a
D 9
.B TELNET IP
E 9
I 9
D 11
\s-1TELNET EC\s+1
E 11
I 11
D 19
.Li TELNET EC
E 19
I 19
.Dv TELNET EC
E 19
E 11
E 9
sequence (see
D 11
.B send
D 9
.I ip
E 9
I 9
.B ec
E 11
I 11
.Ic send
.Ic ec
E 11
E 9
above)
D 9
is sent to the remote host.
The initial value for the interrupt character is taken to be
E 9
I 9
is sent to the remote system.
The initial value for the erase character is taken to be
E 9
the terminal's
D 9
.B intr
E 9
I 9
D 11
.B erase
E 11
I 11
.Ic erase
E 11
E 9
character.
D 11
.TP
D 9
.I quit
E 9
I 9
.B escape
E 9
.br
E 11
I 11
D 19
.Tp Ic escape
E 19
I 19
.It Ic escape
E 19
E 11
I 9
This is the
D 11
.B telnet
escape character (initially \*(lq^[\*(rq) which causes entry
E 11
I 11
.Nm telnet
escape character (initially \*(Lq^[\*(Rq) which causes entry
E 11
into
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
command mode (when connected to a remote system).
D 11
.TP
.B flushoutput
.br
E 11
I 11
D 19
.Tp Ic flushoutput
E 19
I 19
.It Ic flushoutput
E 19
E 11
E 9
If
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
is in
D 11
.I localchars
E 11
I 11
.Ic localchars
E 11
mode (see
D 11
.B toggle
D 9
.I localchars
E 9
I 9
.B localchars
E 11
I 11
.Ic toggle
.Ic localchars
E 11
E 9
below)
and the
D 9
.I quit
E 9
I 9
D 11
.B flushoutput
E 11
I 11
.Ic flushoutput
E 11
E 9
character is typed, a
D 9
.B TELNET BRK
E 9
I 9
D 11
\s-1TELNET AO\s+1
E 11
I 11
D 19
.Li TELNET AO
E 19
I 19
.Dv TELNET AO
E 19
E 11
E 9
sequence (see
D 11
.B send
D 9
.I brk
E 9
I 9
.B ao
E 11
I 11
.Ic send
.Ic ao
E 11
E 9
above)
is sent to the remote host.
D 9
The initial value for the quit character is taken to be
E 9
I 9
The initial value for the flush character is taken to be
E 9
the terminal's
D 9
.B quit
E 9
I 9
D 11
.B flush
E 11
I 11
.Ic flush
E 11
E 9
character.
I 23
.It Ic forw1
.It Ic forw2
If
.Tn TELNET
is operating in
.Dv LINEMODE ,
these are the
characters that, when typed, cause partial lines to be
forwarded to the remote system.  The initial value for
the forwarding characters are taken from the terminal's
eol and eol2 characters.
E 23
D 11
.TP
D 9
.I flushoutput
E 9
I 9
.B interrupt
E 9
.br
E 11
I 11
D 19
.Tp Ic interrupt
E 19
I 19
.It Ic interrupt
E 19
E 11
If
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
is in
D 11
.I localchars
E 11
I 11
.Ic localchars
E 11
mode (see
D 11
.B toggle
D 9
.I localchars
E 9
I 9
.B localchars
E 11
I 11
.Ic toggle
.Ic localchars
E 11
E 9
below)
and the
D 9
.I flushoutput
E 9
I 9
D 11
.B interrupt
E 11
I 11
.Ic interrupt
E 11
E 9
character is typed, a
D 9
.B TELNET AO
E 9
I 9
D 11
\s-1TELNET IP\s+1
E 11
I 11
D 19
.Li TELNET IP
E 19
I 19
.Dv TELNET IP
E 19
E 11
E 9
sequence (see
D 11
.B send
D 9
.I ao
E 9
I 9
.B ip
E 11
I 11
.Ic send
.Ic ip
E 11
E 9
above)
is sent to the remote host.
D 9
The initial value for the flush character is taken to be
E 9
I 9
The initial value for the interrupt character is taken to be
E 9
the terminal's
D 9
.B flush
E 9
I 9
D 11
.B intr
E 11
I 11
.Ic intr
E 11
E 9
character.
D 11
.TP
D 9
.I erase
E 9
I 9
.B kill
E 9
.br
E 11
I 11
D 19
.Tp Ic kill
E 19
I 19
.It Ic kill
E 19
E 11
If
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
is in
D 11
.I localchars
E 11
I 11
.Ic localchars
E 11
mode (see
D 11
.B toggle
D 9
.I localchars
E 9
I 9
.B localchars
E 11
I 11
.Ic toggle
.Ic localchars
E 11
E 9
below),
D 11
.B and
E 11
I 11
.Ic and
E 11
if
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 9
is operating in \*(lqcharacter at a time\*(rq mode, then when this
E 11
I 11
.Nm telnet
is operating in \*(Lqcharacter at a time\*(Rq mode, then when this
E 11
character is typed, a
D 9
.B TELNET EC
E 9
I 9
D 11
\s-1TELNET EL\s+1
E 11
I 11
D 19
.Li TELNET EL
E 19
I 19
.Dv TELNET EL
E 19
E 11
E 9
sequence (see
D 11
.B send
D 9
.I ec
E 9
I 9
.B el
E 11
I 11
.Ic send
.Ic el
E 11
E 9
above)
is sent to the remote system.
D 9
The initial value for the erase character is taken to be
E 9
I 9
The initial value for the kill character is taken to be
E 9
the terminal's
D 9
.B erase
E 9
I 9
D 11
.B kill
E 11
I 11
.Ic kill
E 11
E 9
character.
D 11
.TP
D 9
.I kill
E 9
.br
I 9
.B lnext
E 11
I 11
D 19
.Tp Ic lnext
E 19
I 19
.It Ic lnext
E 19
E 11
E 9
If
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
is operating in
D 11
\s-1LINEMODE\s+1
or \*(lqold line by line\*(lq mode, then this character is taken to
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
or \*(Lqold line by line\*(Lq mode, then this character is taken to
E 11
be the terminal's
D 11
.B lnext
E 11
I 11
.Ic lnext
E 11
character.
The initial value for the lnext character is taken to be
the terminal's
D 11
.B lnext
E 11
I 11
.Ic lnext
E 11
character.
D 11
.TP
.B quit
.br
E 11
I 11
D 19
.Tp Ic quit
E 19
I 19
.It Ic quit
E 19
E 11
If
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
is in
D 11
.I localchars
E 11
I 11
.Ic localchars
E 11
mode (see
D 11
.B toggle
D 9
.I localchars
below),
.B and
if
.I telnet
is operating in \*(lqcharacter at a time\*(rq mode, then when this
E 9
I 9
.B localchars
E 11
I 11
.Ic toggle
.Ic localchars
E 11
below)
and the
D 11
.B quit
E 11
I 11
.Ic quit
E 11
E 9
character is typed, a
D 9
.B TELNET EL
E 9
I 9
D 11
\s-1TELNET BRK\s+1
E 11
I 11
D 19
.Li TELNET BRK
E 19
I 19
.Dv TELNET BRK
E 19
E 11
E 9
sequence (see
D 11
.B send
D 9
.I el
E 9
I 9
.B brk
E 11
I 11
.Ic send
.Ic brk
E 11
E 9
above)
D 9
is sent to the remote system.
E 9
I 9
is sent to the remote host.
The initial value for the quit character is taken to be
the terminal's
D 11
.B quit
E 11
I 11
.Ic quit
E 11
character.
D 11
.TP
.B reprint
.br
E 11
I 11
D 19
.Tp Ic reprint
E 19
I 19
.It Ic reprint
E 19
E 11
If
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
is operating in
D 11
\s-1LINEMODE\s+1
or \*(lqold line by line\*(lq mode, then this character is taken to
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
or \*(Lqold line by line\*(Lq mode, then this character is taken to
E 11
be the terminal's
D 11
.B reprint
E 11
I 11
.Ic reprint
E 11
character.
The initial value for the reprint character is taken to be
the terminal's
D 11
.B reprint
E 11
I 11
.Ic reprint
E 11
character.
I 23
.It Ic rlogin
This is the rlogin escape character.
If set, the normal
.Tn TELNET
escape character is ignored unless it is
preceded by this character at the beginning of a line.
This character, at the beginning of a line followed by
a "."  closes the connection; when followed by a ^Z it
suspends the telnet command.  The initial state is to
disable the rlogin escape character.
E 23
D 11
.TP
.B start
.br
E 11
I 11
D 19
.Tp Ic start
E 19
I 19
.It Ic start
E 19
E 11
If the
D 11
\s-1TELNET TOGGLE-FLOW-CONTROL\s+1
E 11
I 11
D 19
.Li TELNET TOGGLE-FLOW-CONTROL
E 19
I 19
.Dv TELNET TOGGLE-FLOW-CONTROL
E 19
E 11
option has been enabled,
then this character is taken to
be the terminal's
D 11
.B start
E 11
I 11
.Ic start
E 11
character.
E 9
The initial value for the kill character is taken to be
the terminal's
D 9
.B kill
E 9
I 9
D 11
.B start
E 11
I 11
.Ic start
E 11
E 9
character.
D 11
.TP
D 9
.I eof
E 9
I 9
.B stop
E 9
.br
E 11
I 11
D 19
.Tp Ic stop
E 19
I 19
.It Ic stop
E 19
E 11
I 9
If the
D 11
\s-1TELNET TOGGLE-FLOW-CONTROL\s+1
E 11
I 11
D 19
.Li TELNET TOGGLE-FLOW-CONTROL
E 19
I 19
.Dv TELNET TOGGLE-FLOW-CONTROL
E 19
E 11
option has been enabled,
then this character is taken to
be the terminal's
D 11
.B stop
E 11
I 11
.Ic stop
E 11
character.
The initial value for the kill character is taken to be
the terminal's
D 11
.B stop
E 11
I 11
.Ic stop
E 11
character.
D 11
.TP
.B susp
.br
E 11
I 11
D 19
.Tp Ic susp
E 19
I 19
.It Ic susp
E 19
E 11
E 9
If
D 9
.I telnet
is operating in \*(lqline by line\*(rq mode, entering this character
as the first character on a line will cause this character to be
sent to the remote system.
The initial value of the eof character is taken to be the terminal's
.B eof
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
is in
D 11
.B localchars
E 11
I 11
.Ic localchars
E 11
mode, or
D 11
\s-1LINEMODE\s+1
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
E 11
is enabled, and the
D 11
.B suspend
E 11
I 11
.Ic suspend
E 11
character is typed, a
D 11
\s-1TELNET SUSP\s+1
E 11
I 11
D 19
.Li TELNET SUSP
E 19
I 19
.Dv TELNET SUSP
E 19
E 11
sequence (see
D 11
.B send
.B susp
E 11
I 11
.Ic send
.Ic susp
E 11
above)
is sent to the remote host.
The initial value for the suspend character is taken to be
the terminal's
D 11
.B suspend
E 11
I 11
.Ic suspend
E 11
E 9
character.
I 25
.ne 1i
E 25
I 9
D 11
.TP
.B tracefile
This is the file to which the output, caused by \fBnetdata\fR or
\fBoption\fR tracing being TRUE, will be written.  If it is set to '-',
E 11
I 11
D 19
.Tp Ic tracefile
E 19
I 19
.It Ic tracefile
E 19
D 21
Thi is the file to which the output, caused by
E 21
I 21
This is the file to which the output, caused by
E 21
.Ic netdata
or
.Ic option
D 19
tracing being TRUE, will be written.  If it is set to
E 19
I 19
tracing being
.Dv TRUE ,
will be written.  If it is set to
E 19
.Dq Fl ,
E 11
then tracing information will be written to standard output (the default).
D 11
.br
.TP
.B worderase
.br
E 11
I 11
D 19
.Tp Ic worderase
E 19
I 19
.It Ic worderase
E 19
E 11
If
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
is operating in
D 11
\s-1LINEMODE\s+1
or \*(lqold line by line\*(lq mode, then this character is taken to
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
or \*(Lqold line by line\*(Lq mode, then this character is taken to
E 11
be the terminal's
D 11
.I worderase
E 11
I 11
.Ic worderase
E 11
character.
The initial value for the worderase character is taken to be
the terminal's
D 11
.I worderase
E 11
I 11
.Ic worderase
E 11
character.
I 12
D 13
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
Displays the legal
.Ic set
.Pq Ic unset
commands.
E 13
E 12
D 11
.TP
.B slc \fIstate\fP
.br
E 11
I 11
D 19
.Tp
.Tp Cx Ic slc
.Cx \&\ \&
.Ar state
.Cx
E 19
I 19
.El
.It Ic slc Ar state 
E 19
E 11
The
D 11
.B slc
E 11
I 11
.Ic slc
E 11
command (Set Local Characters) is used to set
D 21
or change the state of the the special
E 21
I 21
D 23
or change the state of the special
E 23
I 23
or change the state of the the special
E 23
E 21
D 11
characters when the \s-1TELNET LINEMODE\s+1 option has
E 11
I 11
characters when the 
D 19
.Li TELNET LINEMODE
E 19
I 19
.Dv TELNET LINEMODE
E 19
option has
E 11
been enabled.  Special characters are characters that get
D 11
mapped to \s-1TELNET\s+1 commands sequences (like
.B ip
E 11
I 11
mapped to 
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
commands sequences (like
.Ic ip
E 11
or
D 11
.BR quit )
E 11
I 11
.Ic quit  )
E 11
or line editing characters (like
D 11
.B erase
E 11
I 11
.Ic erase
E 11
and
D 11
.BR kill ).
E 11
I 11
.Ic kill  ) .
E 11
By default, the local special characters are exported.
D 11
.RS
.TP
.B export
.br
E 11
I 11
D 19
.Tw Fl
.Tp Ic export
E 19
I 19
.Bl -tag -width Fl
I 23
.It Ic check
Verify the current settings for the current special characters.
The remote side is requested to send all the current special
character settings, and if there are any discrepancies with
the local side, the local side will switch to the remote value.
E 23
.It Ic export
E 19
E 11
Switch to the local defaults for the special characters.  The
local default characters are those of the local terminal at
the time when
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
was started.
D 11
.br
.TP
.B import
.br
E 11
I 11
D 19
.Tp Ic import
E 19
I 19
.It Ic import
E 19
E 11
Switch to the remote defaults for the special characters.
The remote default characters are those of the remote system
D 11
at the time when the \s-1TELNET\s+1 connection was established.
.br
.TP
.B check
.br
E 11
I 11
at the time when the 
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
connection was established.
D 19
.Tp Ic check
E 19
I 19
D 23
.It Ic check
E 19
E 11
Verify the current settings for the current special characters.
The remote side is requested to send all the current special
D 21
character settings, and if there are any discrepencies with
E 21
I 21
character settings, and if there are any discrepancies with
E 21
the local side, the local side will switch to the remote value.
E 23
D 11
.TP
.B ?
.br
E 11
I 11
D 12
.Ic Ic \&?
E 12
I 12
D 13
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
E 13
I 13
.Ic Ic \&?
E 13
E 12
E 11
Prints out help information for the
D 11
.B slc
E 11
I 11
.Ic slc
E 11
command.
E 9
D 11
.RE
.TP
I 9
.B ?
.br
E 11
I 11
D 19
.Tp
I 12
D 13
.Tp Cx Ic environ
.Cx \&\ \&
.Ar arguments...
.Cx
E 19
I 19
.El
D 23
.It Ic environ Ar arguments... 
E 19
The
.Ic environ
D 21
command is used to manipulate the
the variables that my be sent through the
E 21
I 21
command is used to manipulate 
the variables that may be sent through the
E 21
D 19
.Li TELNET ENVIRON
E 19
I 19
.Dv TELNET ENVIRON
E 19
option.
D 21
The initial set of variables is taken from the users
E 21
I 21
The initial set of variables is taken from the user's
E 21
D 14
environment; with only the
.Ev USER
E 14
I 14
environment, with only the
.Ev DISPLAY
E 14
and
D 14
.Ev DISPLAY variables
being exported.
E 14
I 14
.Ev PRINTER
variables being exported by default.
The
.Ev USER
variable is also exported if the
.Fl a
or
.Fl l
options are used.
E 14
.br
D 19
Valid arguments for the \fBenviron\fP command are:
.Tw Fl
.Tp Cx Ic define
.Cx \&\ \&
.Ar variable value
.Cx
E 19
I 19
Valid arguments for the
.Ic environ
command are:
.Bl -tag -width Fl
.It Ic define Ar variable value 
E 19
Define the variable
.Ar variable
to have a value of
.Ar value.
Any variables defined by this command are automatically exported.
The
.Ar value
may be enclosed in single or double quotes so
that tabs and spaces may be included.
D 19
.Tp Cx Ic undefine
.Cx \&\ \&
.Ar variable
.Cx
E 19
I 19
.It Ic undefine Ar variable 
E 19
Remove
.Ar variable
from the list of environment variables.
D 19
.Tp Cx Ic export
.Cx \&\ \&
.Ar variable
.Cx
E 19
I 19
.It Ic export Ar variable 
E 19
Mark the variable
.Ar variable
to be exported to the remote side.
D 19
.Tp Cx Ic unexport
.Cx \&\ \&
.Ar variable
.Cx
E 19
I 19
.It Ic unexport Ar variable 
E 19
Mark the variable
.Ar variable
to not be exported unless
explicitly asked for by the remote side.
D 19
.Tp Ic list
E 19
I 19
.It Ic list
E 19
List the current set of environment variables.
D 19
Those marked with a \fB*\fR will be sent automatically,
E 19
I 19
Those marked with a
.Cm *
will be sent automatically,
E 19
other variables will only be sent if explicitly requested.
E 13
E 12
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
E 11
D 12
Displays the legal
D 11
\fBset\fR (\fBunset\fR)
E 11
I 11
.Ic set
.Pq Ic unset
E 11
commands.
E 12
I 12
D 13
Prints out help information for the
.Ic environ
command.
D 19
.Tp
E 13
I 13
Displays the legal
.Ic set
.Pq Ic unset
commands.
E 13
E 12
D 11
.RE
.TP
E 9
.B toggle \fIarguments...\fP
.br
E 11
I 11
.Tp Cx Ic toggle
.Cx \&\ \&
.Ar arguments ...
.Cx
E 19
I 19
.El
E 23
I 23
.It Ic status
Show the current status of
.Nm telnet  .
This includes the peer one is connected to, as well
as the current mode.
E 23
.It Ic toggle Ar arguments ... 
E 19
E 11
Toggle (between
D 19
TRUE
E 19
I 19
.Dv TRUE
E 19
and
D 19
FALSE)
E 19
I 19
.Dv FALSE )
E 19
various flags that control how
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
responds to events.
I 9
D 19
These flags may be set explicitly to TRUE or FALSE
E 19
I 19
These flags may be set explicitly to
.Dv TRUE
or
.Dv FALSE
E 19
using the
D 11
.B set
E 11
I 11
.Ic set
E 11
and
D 11
.B unset
E 11
I 11
.Ic unset
E 11
commands listed above.
E 9
More than one argument may be specified.
I 5
The state of these flags may be interrogated with the
D 11
.B display
E 11
I 11
.Ic display
E 11
command.
E 5
Valid arguments are:
D 11
.RS
.TP
D 9
.I localchars
E 9
I 9
.B autoflush
E 9
.br
E 11
I 11
D 19
.Tw Ar
.Tp Ic autoflush
E 19
I 19
.Bl -tag -width Ar
I 23
.It Ic authdebug
Turns on debugging information for the authentication code.
E 23
.It Ic autoflush
E 19
E 11
D 9
If this is
TRUE,
then the
.IR flush ,
.IR interrupt ,
.IR quit ,
.IR erase ,
and
.I kill
characters (see
.B set
above) are recognized locally, and transformed into (hopefully) appropriate
.B TELNET
control sequences
(respectively
.IR ao ,
.IR ip ,
.IR brk ,
.IR ec ,
and
.IR el ;
see
.B send
above).
The initial value for this toggle is TRUE in \*(lqline by line\*(rq mode,
and FALSE in \*(lqcharacter at a time\*(rq mode.
.TP
D 5
.I autosynch
If
.I autosynch
and
.I localsigs
are both
TRUE,
then when either the
.I intr
or
.I quit
characters is typed (see
.B set
above for descriptions of the
.I intr
and
.I quit
characters), the resulting
.B TELNET
sequence sent is followed by the
.B TELNET SYNCH
sequence.
This procedure
.B should
cause the remote system to begin throwing away all previously
typed input until both of the
.B TELNET
sequences have been read and acted upon.
The initial value of this toggle is FALSE.
.TP
E 5
.I autoflush
.br
E 9
If
D 9
.I autoflush
E 9
I 9
D 11
.B autoflush
E 11
I 11
.Ic autoflush
E 11
E 9
and
D 9
.I localchars
E 9
I 9
D 11
.B localchars
E 11
I 11
.Ic localchars
E 11
E 9
are both
D 19
TRUE,
E 19
I 19
.Dv TRUE ,
E 19
then when the
D 9
.IR ao ,
.IR intr ,
E 9
I 9
D 11
.BR ao ,
.BR intr ,
E 11
I 11
.Ic ao  ,
E 11
E 9
or
D 9
.I quit
E 9
I 9
D 11
.B quit
E 11
I 11
.Ic quit
E 11
E 9
characters are recognized (and transformed into
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
sequences; see
D 11
.B set
E 11
I 11
.Ic set
E 11
above for details),
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
refuses to display any data on the user's terminal
until the remote system acknowledges (via a
D 9
.B TELNET
.I Timing Mark
E 9
I 9
D 11
\s-1TELNET TIMING MARK\s+1
E 11
I 11
D 19
.Li TELNET TIMING MARK
E 19
I 19
.Dv TELNET TIMING MARK
E 19
E 11
E 9
option)
that it has processed those
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
sequences.
D 19
The initial value for this toggle is TRUE if the terminal user had not
done an "stty noflsh", otherwise FALSE (see
E 19
I 19
The initial value for this toggle is
.Dv TRUE
if the terminal user had not
done an "stty noflsh", otherwise
.Dv FALSE
(see
E 19
D 9
.IR stty(1)).
E 9
I 9
D 11
.BR stty (1)).
E 9
I 5
.TP
D 9
.I autosynch
E 9
I 9
.B autosynch
E 11
I 11
.Xr stty  1  ) .
I 23
.It Ic autodecrypt
When the
.Dv TELNET ENCRYPT
option is negotiated, by
default the actual encryption (decryption) of the data
stream does not start automatically.  The autoencrypt
(autodecrypt) command states that encryption of the
output (input) stream should be enabled as soon as
possible.
I 25
.sp
E 25
.Pp
Note:  Because of export controls, the
.Dv TELNET ENCRYPT
option is not supported outside the United States and Canada.
.It Ic autologin
If the remote side supports the
.Dv TELNET AUTHENTICATION
option
.Tn TELNET
attempts to use it to perform automatic authentication.  If the
.Dv AUTHENTICATION
option is not supported, the user's login
name are propagated through the
.Dv TELNET ENVIRON
option.
This command is the same as specifying
.Ar a
option on the
.Ic open
command.
E 23
D 19
.Tp Ic autosynch
E 19
I 19
.It Ic autosynch
E 19
E 11
E 9
If
D 9
.I autosynch
E 9
I 9
D 11
.B autosynch
E 11
I 11
.Ic autosynch
E 11
E 9
and
D 9
.I localchars
E 9
I 9
D 11
.B localchars
E 11
I 11
.Ic localchars
E 11
E 9
are both
D 19
TRUE,
E 19
I 19
.Dv TRUE ,
E 19
then when either the
D 9
.I intr
E 9
I 9
D 11
.B intr
E 11
I 11
.Ic intr
E 11
E 9
or
D 9
.I quit
E 9
I 9
D 11
.B quit
E 11
I 11
.Ic quit
E 11
E 9
characters is typed (see
D 11
.B set
E 11
I 11
.Ic set
E 11
above for descriptions of the
D 9
.I intr
E 9
I 9
D 11
.B intr
E 11
I 11
.Ic intr
E 11
E 9
and
D 9
.I quit
E 9
I 9
D 11
.B quit
E 11
I 11
.Ic quit
E 11
E 9
characters), the resulting
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
sequence sent is followed by the
D 9
.B TELNET SYNCH
E 9
I 9
D 11
\s-1TELNET SYNCH\s+1
E 11
I 11
D 19
.Li TELNET SYNCH
E 19
I 19
.Dv TELNET SYNCH
E 19
E 11
E 9
sequence.
This procedure
D 11
.B should
E 11
I 11
.Ic should
E 11
cause the remote system to begin throwing away all previously
typed input until both of the
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
sequences have been read and acted upon.
D 19
The initial value of this toggle is FALSE.
E 5
D 11
.TP
D 9
.I crmod
E 9
I 9
.B binary
E 9
.br
E 11
I 11
.Tp Ic binary
E 19
I 19
The initial value of this toggle is
.Dv FALSE .
.It Ic binary
E 19
E 11
I 9
Enable or disable the
D 11
\s-1TELNET BINARY\s+1
E 11
I 11
D 19
.Li TELNET BINARY
E 19
I 19
.Dv TELNET BINARY
E 19
E 11
D 10
option.
E 10
I 10
option on both input and output.
D 11
.TP
.B inbinary
.br
E 11
I 11
D 19
.Tp Ic inbinary
E 19
I 19
.It Ic inbinary
E 19
E 11
Enable or disable the
D 11
\s-1TELNET BINARY\s+1
E 11
I 11
D 19
.Li TELNET BINARY
E 19
I 19
.Dv TELNET BINARY
E 19
E 11
option on input.
D 11
.TP
.B outbinary
.br
E 11
I 11
D 19
.Tp Ic outbinary
E 19
I 19
.It Ic outbinary
E 19
E 11
Enable or disable the
D 11
\s-1TELNET BINARY\s+1
E 11
I 11
D 19
.Li TELNET BINARY
E 19
I 19
.Dv TELNET BINARY
E 19
E 11
option on output.
E 10
D 11
.TP
.B crlf
.br
E 11
I 11
D 19
.Tp Ic crlf
E 11
If this is TRUE, then carriage returns will be sent as <CR><LF>.
If this is FALSE, then carriage returns will be send as <CR><NUL>.
The initial value for this toggle is FALSE.
D 11
.TP
.B crmod
.br
E 11
I 11
.Tp Ic crmod
E 19
I 19
.It Ic crlf
If this is
.Dv TRUE ,
then carriage returns will be sent as
.Li <CR><LF> .
If this is
.Dv FALSE ,
then carriage returns will be send as
.Li <CR><NUL> .
The initial value for this toggle is
.Dv FALSE .
.It Ic crmod
E 19
E 11
E 9
Toggle carriage return mode.
When this mode is enabled, most carriage return characters received from
the remote host will be mapped into a carriage return followed by
a line feed.
This mode does not affect those characters typed by the user, only
those received from the remote host.
This mode is not very useful unless the remote host
only sends carriage return, but never line feed.
D 19
The initial value for this toggle is FALSE.
D 11
.TP
D 9
.I debug
E 9
I 9
.B debug
E 9
.br
E 11
I 11
.Tp Ic debug
E 19
I 19
The initial value for this toggle is
.Dv FALSE .
.It Ic debug
E 19
E 11
Toggles socket level debugging (useful only to the
D 11
.IR super user ).
E 11
I 11
.Ic super user  ) .
E 11
D 19
The initial value for this toggle is FALSE.
D 11
.TP
D 9
.I options
E 9
I 9
.B localchars
E 9
.br
E 11
I 11
.Tp Ic localchars
E 19
I 19
The initial value for this toggle is
.Dv FALSE .
I 23
.It Ic encdebug
Turns on debugging information for the encryption code.
E 23
.It Ic localchars
E 19
E 11
I 9
If this is
D 19
TRUE,
E 19
I 19
.Dv TRUE ,
E 19
then the
D 11
.BR flush ,
.BR interrupt ,
.BR quit ,
.BR erase ,
E 11
I 11
.Ic flush  ,
I 12
D 13
.Ic interrupt ,
E 13
E 12
.Ic quit  ,
I 12
D 13
.Ic erase ,
E 13
E 12
E 11
and
D 11
.B kill
E 11
I 11
.Ic kill
E 11
characters (see
D 11
.B set
E 11
I 11
.Ic set
E 11
above) are recognized locally, and transformed into (hopefully) appropriate
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
control sequences
(respectively
D 11
.BR ao ,
.BR ip ,
.BR brk ,
.BR ec ,
E 11
I 11
.Ic ao  ,
I 12
D 13
.Ic ip ,
E 13
E 12
.Ic brk  ,
I 12
D 13
.Ic ec ,
E 13
E 12
E 11
and
D 11
.BR el ;
E 11
I 11
.Ic el  ;
E 11
see
D 11
.B send
E 11
I 11
.Ic send
E 11
above).
D 11
The initial value for this toggle is TRUE in \*(lqold line by line\*(rq mode,
and FALSE in \*(lqcharacter at a time\*(rq mode.
E 11
I 11
D 19
The initial value for this toggle is TRUE in \*(Lqold line by line\*(Rq mode,
and FALSE in \*(Lqcharacter at a time\*(Rq mode.
E 19
I 19
The initial value for this toggle is
.Dv TRUE
in \*(Lqold line by line\*(Rq mode,
and
.Dv FALSE
in \*(Lqcharacter at a time\*(Rq mode.
E 19
E 11
When the
D 11
\s-1LINEMODE\s+1
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
E 11
option is enabled, the value of
D 11
.B localchars
E 11
I 11
.Ic localchars
E 11
D 19
is ignored, and assumed to always be TRUE.
E 19
I 19
is ignored, and assumed to always be
.Dv TRUE .
E 19
If
D 11
\s-1LINEMODE\s+1
E 11
I 11
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
E 11
has ever been enabled, then
D 11
.B quit
E 11
I 11
.Ic quit
E 11
is sent as
D 11
.BR abort ,
E 11
I 11
.Ic abort  ,
E 11
and
D 11
.BR eof and
E 11
I 11
.Ic eof and
E 11
.B suspend
are sent as
D 11
.BR eof and
.BR susp ,
E 11
I 11
.Ic eof and
I 12
D 13
.Ic susp ,
E 13
E 12
E 11
see
D 11
.B send
E 11
I 11
.Ic send
E 11
above).
D 11
.TP
.B netdata
.br
E 11
I 11
D 19
.Tp Ic netdata
E 19
I 19
.It Ic netdata
E 19
E 11
Toggles the display of all network data (in hexadecimal format).
D 19
The initial value for this toggle is FALSE.
D 11
.TP
.B options
.br
E 11
I 11
.Tp Ic options
E 19
I 19
The initial value for this toggle is
.Dv FALSE .
.It Ic options
E 19
E 11
E 9
Toggles the display of some internal
D 9
.I telnet
E 9
I 9
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
E 9
protocol processing (having to do with
D 9
.B TELNET
E 9
I 9
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
E 9
options).
D 19
The initial value for this toggle is FALSE.
D 11
.TP
D 9
.I netdata
E 9
I 9
.B prettydump
E 9
.br
E 11
I 11
.Tp Ic prettydump
E 19
I 19
The initial value for this toggle is
.Dv FALSE .
I 25
.ne 1i
E 25
.It Ic prettydump
E 19
E 11
D 9
Toggles the display of all network data (in hexadecimal format).
The initial value for this toggle is FALSE.
E 9
I 9
When the
D 11
.B netdata
E 11
I 11
.Ic netdata
E 11
toggle is enabled, if
D 11
.B prettydump
E 11
I 11
.Ic prettydump
E 11
is enabled the output from the
D 11
.B netdata
E 11
I 11
.Ic netdata
E 11
D 23
command will be formated in a more user readable format.
E 23
I 23
command will be formatted in a more user readable format.
E 23
Spaces are put between each character in the output, and the
D 23
begining of any
E 23
I 23
beginning of any
E 23
D 11
\s-1TELNET\s+1
E 11
I 11
D 19
.Li TELNET
E 19
I 19
.Tn TELNET
E 19
E 11
D 23
escape sequence is preceeded by a '*' to aid in locating them.
E 23
I 23
escape sequence is preceded by a '*' to aid in locating them.
.It Ic skiprc
When the skiprc toggle is
.Dv TRUE ,
.Tn TELNET
skips the reading of the
.Pa \&.telnetrc
file in the users home
directory when connections are opened.  The initial
value for this toggle is
.Dv FALSE.
.It Ic termdata
Toggles the display of all terminal data (in hexadecimal format).
The initial value for this toggle is
.Dv FALSE .
.It Ic verbose_encrypt
When the
.Ic verbose_encrypt
toggle is
.Dv TRUE ,
.Tn TELNET
prints out a message each time encryption is enabled or
disabled.  The initial value for this toggle is
.Dv FALSE.
Note:  Because of export controls, data encryption
is not supported outside of the United States and Canada.
E 23
E 9
D 11
.TP
D 9
.I ?
E 9
I 9
.B ?
E 9
.br
E 11
I 11
D 19
.Tp Ic \&?
E 19
I 19
.It Ic \&?
E 19
E 11
Displays the legal
D 11
.B toggle
E 11
I 11
.Ic toggle
E 11
commands.
D 11
.RE
E 4
D 9
.SH BUGS
E 9
I 9
.TP
.B z
.br
E 11
I 11
D 19
.Tp
.Tp Ic z
E 19
I 19
.El
.It Ic z
E 19
E 11
Suspend
D 11
.BR telnet .
This command only works when the user is using the 
.BR csh (1).
.TP
.B ! \fR[\fP \fIcommand\fP \fR]\fP
.br
E 11
I 11
.Nm telnet  .
This command only works when the user is using the
.Xr csh  1  .
D 19
.Tp Cx Ic \&!
.Cx \&\ \&
.Op Ar command
.Cx
E 19
I 19
.It Ic \&! Op Ar command 
E 19
E 11
Execute a single command in a subshell on the local
D 11
system.  If \fIcommand\fP is ommitted, then an interactive
E 11
I 11
system.  If
.Ic command
D 23
is ommitted, then an interactive
E 23
I 23
is omitted, then an interactive
E 23
E 11
subshell is invoked.
D 11
.TP
.B status
.br
Show the current status of 
.BR telnet .
E 11
I 11
D 19
.Tp Ic status
E 19
I 19
D 23
.It Ic status
E 19
Show the current status of
.Nm telnet  .
E 11
This includes the peer one is connected to, as well
as the current mode.
E 23
D 11
.TP
.B ? \fR[\fP \fIcommand\fP \fR]\fP
.br
E 11
I 11
D 19
.Tp Cx Ic \&?
.Cx \&\ \&
.Op Ar command
.Cx
E 19
I 19
.It Ic \&? Op Ar command 
E 19
E 11
Get help.  With no arguments,
D 11
.B telnet
E 11
I 11
.Nm telnet
E 11
prints a help summary.
D 11
If a command is specified, 
.B telnet
E 11
I 11
If a command is specified,
.Nm telnet
E 11
will print the help information for just that command.
I 19
.El
E 19
D 11
.SH FILES
.nf
~/.telnetrc
.fi
.SH NOTES
E 9
D 4
This implementation is very simple because
.IR rlogin (1C)
is the standard mechanism used to communicate locally 
with hosts.
E 4
I 4
.PP
E 11
I 11
.Sh ENVIRONMENT
.Nm Telnet
D 12
uses the
E 12
I 12
D 13
uses at least the
E 13
I 13
uses the
E 13
E 12
.Ev HOME ,
D 12
.Ev SHELL
E 12
I 12
D 13
.Ev SHELL ,
D 14
.Ev USER ,
E 14
.Ev DISPLAY ,
E 13
I 13
.Ev SHELL
E 13
E 12
and
.Ev TERM
D 21
environent variables.
I 12
D 13
Other envirnoment variables may be propogated
E 21
I 21
environment variables.
Other environment variables may be propagated
E 21
to the other side via the
D 19
.Li TELNET ENVIRON
E 19
I 19
.Dv TELNET ENVIRON
E 19
option.
E 13
E 12
.Sh FILES
D 19
.Dw ~/.telnetrc
.Di L
.Dp Pa ~/.telnetrc
E 19
I 19
.Bl -tag -width ~/.telnetrc -compact
.It Pa ~/.telnetrc
E 19
user customized telnet startup values
D 19
.Dp
E 19
I 19
.El
E 19
.Sh HISTORY
I 19
The
E 19
.Nm Telnet
D 19
appeared in 4.2 BSD.
E 19
I 19
command appeared in
.Bx 4.2 .
E 19
.Sh NOTES
.Pp
E 11
D 9
There is no adequate way for dealing with flow control.
.PP
E 9
On some remote systems, echo has to be turned off manually when in
D 9
\*(lqline by line\*(rq mode.
E 9
I 9
D 11
\*(lqold line by line\*(rq mode.
E 9
.PP
D 9
There is enough settable state to justify a
.RI . telnetrc
file.
E 9
.PP
D 9
No capability for a
.RI . telnetrc
file is provided.
.PP
In \*(lqline by line\*(rq mode, the terminal's
E 9
I 9
In \*(lqold line by line\*(rq mode or \s-1LINEMODE\s+1 the terminal's
E 9
.I eof
E 11
I 11
\*(Lqold line by line\*(Rq mode.
.Pp
In \*(Lqold line by line\*(Rq mode or 
D 19
.Li LINEMODE
E 19
I 19
.Dv LINEMODE
E 19
the terminal's
.Ic eof
E 11
character is only recognized (and sent to the remote system)
when it is the first character on a line.
E 4
E 1
