h24650
s 00002/00002/00065
d D 8.1 93/06/06 14:12:15 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00061/00049/00006
d D 6.7 91/03/16 18:14:13 cael 9 8
c macro and text revision (-mdoc version 3)
e
s 00036/00024/00019
d D 6.6 91/02/12 21:35:40 bostic 8 7
c rework the password subsystem
e
s 00001/00011/00042
d D 6.5 90/06/24 21:57:02 trent 7 6
c new copyright notice
e
s 00010/00005/00043
d D 6.4 89/03/11 16:36:22 bostic 6 5
c reenter editor if corrupted password file
e
s 00024/00006/00024
d D 6.3 89/02/22 11:15:54 bostic 5 4
c shadow passwords
e
s 00001/00001/00029
d D 6.2 86/05/19 20:35:48 karels 4 3
c update
e
s 00001/00001/00029
d D 6.1 85/04/27 13:54:55 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00012/00011/00018
d D 5.1 85/04/27 13:54:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00029/00000/00000
d D 4.1 85/04/27 13:54:17 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 9
.\" Copyright (c) 1983 The Regents of the University of California.
E 9
I 9
D 10
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 9
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
E 5
.\"
I 5
D 7
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
.\"
E 5
D 9
.\"	%W% (Berkeley) %G%
E 9
I 9
.\"     %W% (Berkeley) %G%
E 9
.\"
D 2
.TH VIPW 8 "4/1/81"
E 2
I 2
D 3
.TH VIPW 8 "4 July 1983"
E 3
I 3
D 9
.TH VIPW 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
vipw \- edit the password file with vi
E 2
I 2
vipw \- edit the password file
E 2
.SH SYNOPSIS
.B vipw
.SH DESCRIPTION
.I Vipw
D 8
edits the password file while setting the appropriate locks,
and does any necessary processing after the password file is unlocked.
If the password file is already being edited, then you will be told
D 2
to try again later
E 2
I 2
D 6
to try again later.  The 
E 6
I 6
to try again later.
The 
E 6
.I vi
editor will be used unless the environment variable EDITOR indicates
an alternate editor.  
E 8
I 8
locks the password file and makes a temporary copy of it for editing.
The user's editor (or by default, 
.IR vi (1))
is run on the copied file.
E 8
I 6
.PP
E 6
D 8
.I Vipw
D 6
performs a number of consistency checks on the password entry for
.IR root ,
and will not allow a password file with a ``mangled'' root entry
to be installed.
E 6
I 6
performs a number of consistency checks on the password entries,
and will not allow a password file with a ``mangled'' entry to be
installed.
If
E 8
I 8
Once the file has been edited,
E 8
.I vipw
D 8
rejects the new password file, the user is prompted to re-enter
the edit session.
E 8
I 8
runs the program
.IR pwd_mkdb (8).
.I Pwd_mkdb
performs a number of consistency checks on the password entries, and will
not allow a password file with a ``mangled'' entry to be installed.
E 9
I 9
.Dd %Q%
.Dt VIPW 8
.Os BSD 4
.Sh NAME
.Nm vipw
.Nd edit the password file
.Sh SYNOPSIS
.Nm vipw
.Sh DESCRIPTION
.Nm Vipw
edits the password file after setting the appropriate locks,
and does any necessary processing after the password file is unlocked.
If the password file is already locked for editing by another user,
.Nm vipw
will ask you
to try again later. The default editor for
.Nm vipw
is
.Xr vi 1 .
.Pp
.Nm Vipw
performs a number of consistency checks on the password entries,
and will not allow a password file with a
.Dq mangled
entry to be
installed.
E 9
If
D 9
.I pwd_mkdb
rejects the new file, the user is prompted to re-enter the edit session.
Once the file is found to be satisfactory,
.I pwd_mkdb
installs it as the new password file.
E 8
E 6
I 5
.PP
D 8
Once the information has been verified,
.I vipw
uses
.IR mkpasswd (8)
to update the user database.  This is run in the background, and,
at very large sites could take several minutes.  Until this update
is completed, the password file is unavailable for other updates
and the new information will not be available to programs.
E 8
I 8
If the password file is already locked, you will be told to try again
later.
.SH FILES
/var/db/pwd.db			Insecure password database file
.br
/var/db/spwd.db		The secure password database file
.br
/etc/master.passwd		The current password file
.br
/etc/passwd			A Version 7 format password file
.br
/etc/vipw.XXXXXX		Temporary copy of the password file
.SH ENVIRONMENT
.TP
EDITOR
The editor used; the default is
.IR vi (1).
Any user specified editor is expected to take the file name it will
edit as its first argument.
E 8
E 5
E 2
.SH SEE ALSO
D 4
chfn(1), chsh(1), passwd(1), passwd(5), adduser(8)
E 4
I 4
D 5
passwd(1), passwd(5), adduser(8), mkpasswd(8)
E 4
.SH FILES
D 2
/etc/vipw.lock
.SH BUGS
.I Vipw
does not remove the vipw.lock file; this is not a bug, but people tend
to think it is.
.PP
No one deals with left-over /etc/ptmp (the real lock) files after a system
crash.
E 2
I 2
/etc/ptmp
E 5
I 5
D 8
chpass(1), passwd(1), passwd(5), adduser(8), mkpasswd(8)
E 8
I 8
chpass(1), passwd(1), passwd(5), adduser(8), pwd_mkdb(8)
E 9
I 9
.Nm vipw
rejects the new password file, the user is prompted to re-enter
the edit session.
.Pp
Once the information has been verified,
.Nm vipw
uses
.Xr pwd_mkdb 8
to update the user database.  This is run in the background, and,
at very large sites could take several minutes.  Until this update
is completed, the password file is unavailable for other updates
and the new information is not available to programs.
.Sh ENVIRONMENT
If the following environment variable exists it will be utilized by
.Nm vipw :
.Bl -tag -width EDITOR
.It Ev EDITOR
The editor specified by the string
.Ev EDITOR
will be invoked instead of the default editor
.Xr vi 1 .
.El
.Sh SEE ALSO
.Xr chpass 1 ,
.Xr passwd 1 ,
.Xr passwd 5 ,
.Xr adduser 8 ,
.Xr pwd_mkdb 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
E 9
E 8
E 5
E 2
E 1
