h08995
s 00006/00000/00269
d D 8.4 95/05/09 16:13:53 mckusick 17 16
c update for checking the clean flag
e
s 00005/00001/00264
d D 8.3 94/11/29 21:01:27 mckusick 16 15
c define -c 3
e
s 00001/00000/00264
d D 8.2 93/12/11 23:43:06 mckusick 15 14
c copyediting for Usenix manuals
e
s 00002/00002/00262
d D 8.1 93/06/05 10:56:15 bostic 14 13
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00052/00036/00212
d D 6.11 93/05/14 18:10:50 mckusick 13 12
c update -c option, misc cleanups
e
s 00124/00176/00124
d D 6.10 92/07/12 13:08:14 cael 12 11
c mdoc version three
e
s 00003/00002/00297
d D 6.9 91/04/20 12:01:08 cael 11 10
c added redist.man
e
s 00006/00008/00293
d D 6.8 90/02/01 17:39:47 mckusick 10 9
c update for current program
e
s 00017/00008/00284
d D 6.7 89/03/19 13:21:09 karels 9 8
c check one filesystem per disk until done, ignoring pass numbers > 1
e
s 00008/00009/00284
d D 6.6 89/03/19 12:57:35 karels 8 7
c update and correct nits
e
s 00014/00000/00279
d D 6.5 89/02/17 17:02:22 mckusick 7 6
c add -m flag to override default creation mode for lost+found
e
s 00001/00000/00278
d D 6.4 88/05/05 10:35:57 mckusick 6 5
c add xref to fsdb(8)
e
s 00031/00007/00247
d D 6.3 88/05/02 22:52:15 mckusick 5 4
c add -c flag to convert between file system formats
e
s 00024/00031/00230
d D 6.2 86/05/21 22:48:09 mckusick 4 3
c update for 4.3BSD version
e
s 00001/00001/00260
d D 6.1 85/04/27 13:27:03 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00016/00078/00245
d D 5.1 85/04/27 13:26:31 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00323/00000/00000
d D 4.1 85/04/27 13:25:31 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 8
.\" Copyright (c) 1980 Regents of the University of California.
E 8
I 8
D 12
.\" Copyright (c) 1980, 1989 Regents of the University of California.
E 12
I 12
D 14
.\" Copyright (c) 1980, 1989, 1991 Regents of the University of California.
E 12
E 8
D 11
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 11
I 11
.\" All rights reserved.
E 14
I 14
.\" Copyright (c) 1980, 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 14
.\"
D 12
.\" %sccs.include.redist.man%
E 12
I 12
.\" %sccs.include.redist.roff%
E 12
E 11
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH FSCK 8 "4/1/81"
E 2
I 2
D 3
.TH FSCK 8 "4 February 1983"
E 3
I 3
D 12
.TH FSCK 8 "%Q%"
E 3
E 2
.UC 4
.de us
\\$1\l'|0\(ul'
..
.SH NAME
fsck \- file system consistency check and interactive repair
.SH SYNOPSIS
D 8
.B /etc/fsck
E 8
I 8
.B fsck
E 8
.B \-p
[
I 7
.B \-m
mode
D 8
] [
E 7
filesystem ...
E 8
]
.br
D 8
.B /etc/fsck
E 8
I 8
.B fsck
E 8
[
I 2
.B \-b
block#
] [
I 5
.B \-c
] [
E 5
E 2
.B \-y
] [
.B \-n
] [
I 7
.B \-m
mode
] [
E 7
D 2
.BR \-s X
] [
.BR \-S X
] [
.B \-t
filename
] [
E 2
filesystem 
] ...
.SH DESCRIPTION
E 12
I 12
.Dd %Q%
.Dt FSCK 8
.Os BSD 4
.Sh NAME
.Nm fsck
D 13
.Nd file system consistency check and interactive repair
E 13
I 13
.Nd filesystem consistency check and interactive repair
E 13
.Sh SYNOPSIS
.Nm fsck
.Fl p
.Op Fl m Ar mode
.Nm fsck
.Op Fl b Ar block#
D 13
.Op Fl c
E 13
I 13
.Op Fl c Ar level
I 15
.Op Fl l Ar maxparallel
E 15
E 13
.Op Fl y
.Op Fl n
.Op Fl m Ar mode
.Op Ar filesystem
.Ar ...
.Sh DESCRIPTION
E 12
The first form of
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 13
preens a standard set of filesystems or the specified file systems.
E 13
I 13
preens a standard set of filesystems or the specified filesystems.
E 13
It is normally used in the script
D 12
.B /etc/rc
E 12
I 12
.Pa /etc/rc
E 12
during automatic reboot.
D 10
In this case
E 10
I 10
Here
E 10
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
reads the table
D 12
.B /etc/fstab
E 12
I 12
.Pa /etc/fstab
E 12
D 13
to determine which file systems to check.
E 13
I 13
to determine which filesystems to check.
E 13
D 8
It uses the information there to inspect groups of disks in parallel taking
E 8
I 8
D 10
It uses the information there to inspect groups of disks in parallel, taking
E 8
maximum advantage of i/o overlap to check the file systems
as quickly as possible.
E 10
D 9
Normally, the root file system will be checked on pass 1, other
``root'' (``a'' partition) file systems on pass 2, other
small file systems on separate passes (e.g. the ``d'' file systems
on pass 3 and the ``e'' file systems on pass 4), and finally
the large user file systems on the last pass, e.g. pass 5.
E 9
D 4
A pass number of 0 in fstab causes a disk to not be checked; similarly
partitions which are not shown as to be mounted ``rw'' or ``ro''
are not checked.
E 4
I 4
D 8
Only partitions in fstab that are mounted ``rw'' or ``rq''
E 8
I 8
Only partitions in fstab that are mounted ``rw,'' ``rq'' or ``ro''
E 8
and that have non-zero pass number are checked.
I 9
Filesystems with pass number 1 (normally just the root filesystem)
are checked one at a time.
When pass 1 completes, all remaining filesystems are checked,
running one process per disk drive.
The disk drive containing each filesystem is inferred from the longest prefix
of the device name that ends in a digit; the remaining characters are assumed
to be the partition designator.
I 17
In preening mode,
filesystems that are marked clean are skipped.
Filesystems are marked clean when they are unmounted,
when they have been mounted read-only, or when
.Nm fsck
runs on them successfully.
E 17
E 9
E 4
D 12
.PP
E 12
I 12
.Pp
E 12
D 13
The system takes care that only a restricted class of innocuous
E 13
I 13
The kernel takes care that only a restricted class of innocuous filesystem
E 13
inconsistencies can happen unless hardware or software failures intervene.
These are limited to the following:
D 12
.IP
Unreferenced inodes
.ns
.IP
Link counts in inodes too large
.ns
.IP
D 5
Missing blocks in the free list
E 5
I 5
Missing blocks in the free map
E 5
.ns
.IP
D 5
Blocks in the free list also in files
E 5
I 5
Blocks in the free map also in files
E 5
.ns
.IP
Counts in the super-block wrong
.PP
E 12
I 12
D 13
.Bl -item -compact -indent indent
.It Unreferenced inodes
.It Link counts in inodes too large
.It Missing blocks in the free map
.It Blocks in the free map also in files
.It Counts in the super-block wrong
E 13
I 13
.Bl -item -compact
.It
Unreferenced inodes
.It
Link counts in inodes too large
.It
Missing blocks in the free map
.It
Blocks in the free map also in files
.It
Counts in the super-block wrong
E 13
.El
.Pp
E 12
D 4
These are the only inconsistencies which
E 4
I 4
These are the only inconsistencies that
E 4
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
with the
D 12
.B \-p
E 12
I 12
.Fl p
E 12
option will correct; if it encounters other inconsistencies, it exits
with an abnormal return status and an automatic reboot will then fail.
For each corrected inconsistency one or more lines will be printed
D 13
identifying the file system on which the correction will take place,
and the nature of the correction.  After successfully correcting a file
system,
E 13
I 13
identifying the filesystem on which the correction will take place,
and the nature of the correction.  After successfully correcting a filesystem,
E 13
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 4
will print the number of files on that file system and the number of
used and free blocks.
E 4
I 4
D 13
will print the number of files on that file system,
E 13
I 13
will print the number of files on that filesystem,
E 13
the number of used and free blocks,
and the percentage of fragmentation.
E 4
D 12
.PP
I 4
If sent a QUIT signal,
.I fsck
E 12
I 12
.Pp
If sent a
.Dv QUIT
signal,
.Nm fsck
E 12
D 13
will finish the file system checks, then exit with an abnormal
E 13
I 13
will finish the filesystem checks, then exit with an abnormal
E 13
D 9
return status that causes the automatic reboot to fail.
This is useful when you wish to finish the file system checks,
but do not want the machine to come up multiuser.
E 9
I 9
return status that causes an automatic reboot to fail.
D 13
This is useful when to finish the file system checks during an automatic reboot,
E 13
I 13
This is useful when you want to finish the filesystem checks during an
automatic reboot,
E 13
but do not want the machine to come up multiuser after the checks complete.
E 9
D 12
.PP
E 12
I 12
.Pp
E 12
E 4
Without the
D 12
.B \-p
E 12
I 12
.Fl p
E 12
option,
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 13
audits and interactively repairs inconsistent conditions for file systems. 
If the file system is inconsistent the operator is prompted for concurrence
E 13
I 13
audits and interactively repairs inconsistent conditions for filesystems. 
If the filesystem is inconsistent the operator is prompted for concurrence
E 13
before each correction is attempted.
D 4
It should be noted that a number of the corrective actions which are not
fixable under the
E 4
I 4
It should be noted that some of the corrective actions which are not
correctable under the
E 4
D 12
.B \-p
E 12
I 12
.Fl p
E 12
D 4
option will result in some loss
of data.
E 4
I 4
option will result in some loss of data.
E 4
The amount and severity of data lost may be determined from the diagnostic
output.
The default action for each consistency correction
D 12
is to wait for the operator to respond \fByes\fP or \fBno\fP.
E 12
I 12
is to wait for the operator to respond
.Li yes
or
.Li no .
E 12
D 4
If the operator does not have write permission 
E 4
I 4
D 13
If the operator does not have write permission on the file system
E 13
I 13
If the operator does not have write permission on the filesystem
E 13
E 4
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
will default to a 
D 12
.BR "\-n " action.
.PP
.I Fsck
E 12
I 12
.Fl n
action.
.Pp
.Nm Fsck
E 12
has more consistency checks than
its predecessors
D 12
.IR "check, dcheck, fcheck, " "and" " icheck"
E 12
I 12
.Em check , dcheck , fcheck ,
and
.Em icheck
E 12
combined.
D 12
.PP
E 12
I 12
.Pp
E 12
The following flags are interpreted by
D 12
.I fsck.
.TP 6
I 2
.B \-b
E 12
I 12
.Nm fsck .
.Bl -tag -width indent
.It Fl b
E 12
Use the block specified immediately after the flag as
D 5
the super block for the file system.  Block 32 is always
E 5
I 5
D 13
the super block for the file system.  Block 32 is usually
E 13
I 13
the super block for the filesystem.  Block 32 is usually
E 13
E 5
an alternate super block.
I 9
D 12
.TP 6
.B \-l
E 12
I 12
.It Fl l
E 12
Limit the number of parallel checks to the number specified in the following
argument.
By default, the limit is the number of disks, running one process per disk.
If a smaller limit is given, the disks are checked round-robin, one filesystem
at a time.
E 9
I 7
D 12
.TP 6
.B \-m
E 12
I 12
.It Fl m
E 12
Use the mode specified in octal immediately after the flag as the
D 12
permission bits to use when creating the lost+found directory
rather than the default 1777.
E 12
I 12
permission bits to use when creating the
.Pa lost+found
directory rather than the default 1777.
E 12
In particular, systems that do not wish to have lost files accessible
by all users on the system should use a more restrictive
set of permissions such as 700.
E 7
D 12
.TP 6
E 2
.B  \-y
E 12
I 12
.It Fl y
E 12
Assume a yes response to all questions asked by 
D 8
.I fsck;
E 8
I 8
D 12
.IR fsck ;
E 12
I 12
.Nm fsck ;
E 12
E 8
this should be used with great caution as this is a free license
to continue after essentially unlimited trouble has been encountered.
D 12
.TP 6
.B  \-n
E 12
I 12
.It Fl n
E 12
Assume a no response to all questions asked by 
D 8
.I fsck;
E 8
I 8
D 12
.I fsck
except for ``CONTINUE?'', which is assumed to be affirmative;
E 12
I 12
.Nm fsck
except for
.Ql CONTINUE? ,
which is assumed to be affirmative;
E 12
E 8
D 13
do not open the file system for writing.
E 13
I 13
do not open the filesystem for writing.
E 13
I 5
D 12
.TP 6
.B  \-c
E 12
I 12
.It Fl c
E 12
D 13
If the file system is in the old (static table) format,
convert it to the new (dynamic table) format.
If the file system is in the new format,
convert it to the old format provided the old format
can support the filesystem configuration.
E 13
I 13
Convert the filesystem to the specified level.
Note that the level of a filesystem can only be raised.
.Bl -tag -width indent
D 16
There are currently three levels defined:
E 16
I 16
There are currently four levels defined:
E 16
.It 0
The filesystem is in the old (static table) format.
.It 1
The filesystem is in the new (dynamic table) format.
.It 2
The filesystem supports 32-bit uid's and gid's,
short symbolic links are stored in the inode, 
and directories have an added field showing the file type.
I 16
.It 3
If maxcontig is greater than one,
build the free segment maps to aid in finding contiguous sets of blocks.
If maxcontig is equal to one, delete any existing segment maps.
E 16
.El
.Pp
E 13
In interactive mode,
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 13
will list the direction the conversion is to be made
E 13
I 13
will list the conversion to be made
E 13
and ask whether the conversion should be done.
If a negative answer is given,
no further operations are done on the filesystem.
In preen mode,
D 13
the direction of the conversion is listed and done if
E 13
I 13
the conversion is listed and done if
E 13
possible without user interaction.
D 13
Conversion in preen mode is best used when all the file systems
E 13
I 13
Conversion in preen mode is best used when all the filesystems
E 13
are being converted at once.
D 13
The format of a file system can be determined from the
E 13
I 13
The format of a filesystem can be determined from the
E 13
first line of output from 
D 12
.IR dumpfs (8).
E 5
D 2
.TP 6
.BR \-s \fIX
Ignore the actual free list and (unconditionally) reconstruct a new
one by rewriting the super-block of the file system.  
The file system should be unmounted while this is done; if this
is not possible, care should be taken that the system is quiescent
and that it is rebooted immediately afterwards.
This precaution is necessary so that the old, bad, in-core copy
of the superblock will not continue to be used, or written on the file system.
.IP
The
.BR \-s \fIX
option allows for creating an optimal free-list organization.
The following forms of
.I X
are supported for the following devices:
.sp
.nf
	\-s3 (RP03)
	\-s4 (RP04, RP05, RP06)
	\-sBlocks-per-cylinder\fB:\fRBlocks-to-skip (for anything else)
.fi
.IP "" 6
If 
.I X
is not given,
the values used when the filesystem was created
are used.
If these values were not specified, then the value
.I 400:9
is used.
.TP 6
.BR \-S \fIX
Conditionally reconstruct the free list. This option
is like
.BR \-s \fIX
above except that the free list is rebuilt only
if there were no discrepancies discovered in the
file system. Using
.B \-S
will force a no response to all questions asked
by
.I fsck.
This option is useful for forcing free list reorganization
on uncontaminated file systems.
.TP 6
.B \-t
If
.I fsck
cannot obtain enough memory to keep its tables,
it uses a scratch file. If the \f3\-t\fP option is
specified, the file named in the next argument
is used as the scratch file, if needed. Without the
.BR "\-t " flag,
.I fsck
will prompt the operator for the name of the
scratch file. The file chosen should not be on the
filesystem being checked, and if it is not
a special file or did not already exist, it is
removed when
.I fsck
completes.
E 2
.PP
E 12
I 12
.Xr dumpfs 8 .
.El
.Pp
E 12
If no filesystems are given to 
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 13
then a default list of file systems is read from
E 13
I 13
then a default list of filesystems is read from
E 13
the file
D 12
.BR /etc/fstab .
.PP
.ne 10
E 12
I 12
.Pa /etc/fstab .
.Pp
.Bl -enum -indent indent -compact
E 12
Inconsistencies checked are as follows:
D 12
.TP 6
1.
E 12
I 12
.It
E 12
D 5
Blocks claimed by more than one inode or the free list.
E 5
I 5
Blocks claimed by more than one inode or the free map.
E 5
D 12
.br
.br
.ns
.TP 6
2.
E 12
I 12
.It
E 12
D 5
Blocks claimed by an inode or the free list outside the range of the file system.
E 5
I 5
D 13
Blocks claimed by an inode outside the range of the file system.
E 13
I 13
Blocks claimed by an inode outside the range of the filesystem.
E 13
E 5
D 12
.br
.br
.ns
.TP 6
3.
E 12
I 12
.It
E 12
Incorrect link counts.
D 12
.br
.br
.ns
.TP 6
4.
E 12
I 12
.It
E 12
Size checks:
D 12
.br
.ns
.IP "" 12
E 12
I 12
.Bl -item -indent indent -compact
.It 
E 12
D 2
Directory size not 16-byte aligned.
E 2
I 2
D 13
Directory size not of proper format.
E 13
I 13
Directory size not a multiple of DIRBLKSIZ.
E 13
E 2
D 12
.br
E 12
I 12
.It
E 12
I 5
Partially truncated file.
E 5
D 12
.br
I 5
.br
E 5
.ns
.TP 6
5.
E 12
I 12
.El
.It
E 12
Bad inode format.
D 12
.br
.br
.ns
.TP 6
6.
E 12
I 12
.It
E 12
Blocks not accounted for anywhere.
D 12
.br
.br
.ns
.TP 6
7.
E 12
I 12
.It
E 12
Directory checks:
D 12
.br
.br
.ns
.IP "" 12
E 12
I 12
.Bl -item -indent indent -compact
.It 
E 12
File pointing to unallocated inode.
D 12
.br
E 12
I 12
.It
E 12
Inode number out of range.
D 12
.br
E 12
I 12
.It
E 12
I 10
Dot or dot-dot not the first two entries of a directory
or having the wrong inode number.
E 10
D 12
.br
I 10
.br
E 10
.ns
.TP 6
8.
E 12
I 12
.El
.It
E 12
Super Block checks:
I 13
.Bl -item -indent indent -compact
E 13
D 12
.br
.br
.ns
.IP "" 12
E 12
I 12
.It 
E 12
D 2
More than 65536 inodes.
E 2
D 5
.br
E 5
D 13
More blocks for inodes than there are in the file system.
E 13
I 13
More blocks for inodes than there are in the filesystem.
E 13
D 12
.br
.br
.ns
.TP 6
9.
E 12
I 12
.It
E 12
D 5
Bad free block list format.
E 5
I 5
Bad free block map format.
E 5
D 12
.br
.br
.ns
.TP 6
10.
E 12
I 12
.It
E 12
Total free block and/or free inode count incorrect.
D 12
.PP
E 12
I 12
.El
I 13
.El
E 13
.Pp
E 12
Orphaned files and directories (allocated but unreferenced) are,
with the operator's concurrence, reconnected by
placing them in the 
D 12
.B lost+found
E 12
I 12
.Pa lost+found
E 12
directory.
D 4
The name assigned is the inode number. The only restriction
is that the directory 
.B lost+found
must preexist
in the root of the filesystem being checked and
must have empty slots in which entries can be made.
This is accomplished by making 
.BR lost+found ,
copying a number of files to the directory, and then removing them
(before
.I
fsck
is executed).
E 4
I 4
The name assigned is the inode number.
If the
D 12
.I lost+found
E 12
I 12
.Pa lost+found
E 12
directory does not exist, it is created.
If there is insufficient space its size is increased.
E 4
D 12
.PP
E 12
I 12
.Pp
E 12
D 10
Checking the raw device is almost always faster.
E 10
I 10
Because of inconsistencies between the block device and the buffer cache,
the raw device should always be used.
E 10
D 12
.SH FILES
.br
.ns
.TP 21
/etc/fstab
E 12
I 12
.Sh FILES
.Bl -tag -width /etc/fstab -compact
.It Pa /etc/fstab
E 12
D 13
contains default list of file systems to check.
E 13
I 13
contains default list of filesystems to check.
E 13
D 12
.SH DIAGNOSTICS
E 12
I 12
.El
.Sh DIAGNOSTICS
E 12
The diagnostics produced by 
D 12
.I fsck
E 12
I 12
.Nm fsck
E 12
D 4
are intended to be self-explanatory.
E 4
I 4
are fully enumerated and explained in Appendix A of
D 12
``Fsck \- The UNIX File System Check Program'' (SMM:5).
E 4
.SH "SEE ALSO"
D 2
fstab(5), fs(5), crash(8), reboot(8)
E 2
I 2
fstab(5),
fs(5),
I 6
fsdb(8),
E 6
newfs(8),
mkfs(8),
D 10
crash(8V),
E 10
reboot(8)
E 12
I 12
.Rs
.%T "Fsck \- The UNIX File System Check Program"
.Re
.Sh SEE ALSO
.Xr fstab 5 ,
.Xr fs 5 ,
.Xr fsdb 8 ,
.Xr newfs 8 ,
.Xr mkfs 8 ,
.Xr reboot 8
E 12
E 2
D 10
.SH BUGS
D 4
Inode numbers for
.BR . ""
and
.BR .. ""
in each directory should be checked for validity.
D 2
.PP
\f3\-g\fP and \f3\-b\fP options from 
.I check
should be available in
.I fsck.
E 2
.PP
E 4
There should be some way to start a \fBfsck \-p\fR at pass \fIn\fR.
E 10
E 1
