#! /bin/sh
#
# an aggressive little script for sorting the summary files
# depends on '\002' and '\003' not being anywhere in the files.

TEMP=/tmp/sum_$$
DL="bin doc etc games ideas include lib local man misc new sys ucb usr.bin usr.lib"

if [ $# -ne 1 ]
then
	echo "usage: $0 summary_file"  1>&2
	exit 1
fi

# make sure summary file has an empty last line so that first sed match
# works on every entry; gets stripped at end if more than one blank line
echo "" >> $1

trap '/bin/rm -f $TEMP ; exit 1' 1 2 3 13 15

# turn each five-line entry into a single line with record separator of ^C's
sed 's/^[ 	]*$//' < $1 | tr '\012' '\003' | tr '\002' '\012' > $TEMP

for i in $DL; do
# grep out each topic
	egrep "^[^/]*/$i/" < $TEMP |
# take line VERSION/TOPIC/## and put ## first with white space separator
	sed 's;\([^/]*/[^/]*/\)\([0-9]*\)\(.*\);\2 \1 \3;' |
# sort based on that number
	sort -n | sed 's;\([^ ]*\) \([^ ]*\) \(.*\);\2\1\3;' |
# put back into normal five-line format
	sed 'a\
	' | sed -e 's/^//' -e 's/$//' | tr '\003' '\012'
done
/bin/rm -f $TEMP
exit 0
