h03464
s 00003/00002/00088
d D 6.8 91/08/07 00:03:47 cael 11 10
c fix .Os and history
e
s 00025/00029/00065
d D 6.7 91/05/09 23:14:39 cael 10 9
c mdoc version three/deleted AUTHOR section
e
s 00001/00002/00093
d D 6.6 91/04/16 15:49:07 bostic 9 8
c new copyright; att/bsd/shared
e
s 00002/00000/00093
d D 6.5 91/03/14 00:15:17 cael 8 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00093
d R 6.5 91/03/13 20:32:11 cael 7 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00000/00001/00093
d D 6.4 90/06/26 01:00:43 cael 6 5
c converted man page
e
s 00056/00055/00038
d D 6.3 90/06/11 05:59:33 cael 5 4
c converted man page
e
s 00001/00001/00092
d D 6.2 86/05/12 08:54:34 anne 4 3
c grammar
e
s 00001/00001/00092
d D 6.1 85/04/29 14:58:02 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00092
d D 5.1 85/04/29 14:57:44 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00093/00000/00000
d D 4.1 85/04/29 14:57:28 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
.\" All rights reserved.
E 5
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 5
.\"
D 2
.TH PX 1 4/8/79
E 2
I 2
D 3
.TH PX 1 "8 April 1979"
E 3
I 3
D 5
.TH PX 1 "%Q%"
E 5
I 5
D 9
.\"     %W% (Berkeley) %G%
E 9
I 9
.\"	%W% (Berkeley) %G%
E 9
.\"
I 8
D 9
.Vx
E 9
D 10
.Vx
E 10
E 8
.Dd %Q%
.Dt PX 1
I 10
D 11
.Os BSD 3.0
E 11
I 11
.Os BSD 3
E 11
E 10
E 5
E 3
E 2
D 6
.UC
E 6
D 5
.SH NAME
px \- Pascal interpreter
.SH SYNOPSIS
.B px
[ obj [ argument ... ] ]
.SH DESCRIPTION
.I Px
E 5
I 5
.Sh NAME
D 10
.Nm px
E 10
I 10
.Nm \&px
E 10
.Nd Pascal interpreter
.Sh SYNOPSIS
D 10
.Nm px
E 10
I 10
.Nm \&px
E 10
.Op  Ar obj Op Ar argument ...
.Sh DESCRIPTION
D 10
.Nm Px
E 10
I 10
.Nm \&Px
E 10
E 5
interprets the abstract machine code generated by
D 5
.I pi.
E 5
I 5
.Xr pi 1 .
E 5
The first argument is the file to be interpreted, and defaults
to
D 5
.IR obj \|;
E 5
I 5
.Ar obj ;
E 5
remaining arguments are available to the Pascal program using the
built-ins
D 5
.I argv
E 5
I 5
.Ar argv
E 5
and
D 5
.I argc.
.I Px
E 5
I 5
.Ar argc .
D 10
.Nm Px
E 10
I 10
.Nm \&Px
E 10
E 5
is also invoked by
D 5
.I pix
E 5
I 5
.Nm pix
E 5
when running `load and go'.
D 5
.PP
If the program terminates abnormally an error message and a 
E 5
I 5
.Pp
If the program terminates abnormally an error message and a
E 5
control flow backtrace are printed.
The number of statements executed and total execution time
are printed after normal termination.
The
D 5
.B p
E 5
I 5
.Cm p
E 5
option of
D 5
.I pi
E 5
I 5
D 10
.Nm pi
E 10
I 10
.Nm \&pi
E 10
E 5
suppresses all of this except the message indicating the cause
of abnormal termination.
D 5
.SH FILES
.DT
obj		default object file
E 5
I 5
.Sh FILES
D 10
.Dw pmon.out
.Di L
.Dp Pa obj
E 10
I 10
.Bl -tag -width pmon.out -compact
.It Pa obj
E 10
default object file
D 10
.Dp Pa pmon.out
E 10
I 10
.It Pa pmon.out
E 10
profile data file
D 10
.Dp
E 10
I 10
.El
E 10
.Sh SEE ALSO
D 10
.Em Berkeley Pascal User's Manual
E 5
.br
E 10
D 5
pmon.out	profile data file
.SH "SEE ALSO"
Berkeley Pascal User's Manual
.br
pi(1), pix(1)
.SH DIAGNOSTICS
E 5
I 5
.Xr pi 1 ,
.Xr pix 1
I 10
.Rs
.%T "Berkeley Pascal User's Manual"
.Re
E 10
.Sh DIAGNOSTICS
E 5
Most run-time error messages are self-explanatory.
Some of the more unusual ones are:
D 5
.HP 6
Reference to an inactive file
.br
E 5
I 5
D 10
.Tw Ds
.Tp Reference to an inactive file
E 10
I 10
.Bl -tag -width indent
.It Reference to an inactive file
E 10
E 5
A file other than
D 5
.I input
E 5
I 5
.Ar input
E 5
or
D 5
.I output
E 5
I 5
.Ar output
E 5
was used before a call to
D 5
.I reset
E 5
I 5
.Ar reset
E 5
or
D 5
.I rewrite.
.HP 6
Statement count limit exceeded
.br
E 5
I 5
.Ar rewrite .
D 10
.Tp Statement count limit exceeded
E 10
I 10
.It Statement count limit exceeded
E 10
E 5
The limit of 500,000 executed statements
(which prevents excessive looping or recursion)
has been exceeded.
D 5
.HP 6
Bad data found on integer read
.br
.ns
.HP 6
Bad data found on real read
.br
E 5
I 5
D 10
.Tp Bad data found on integer read
.Tp Bad data found on real read
E 10
I 10
.It Bad data found on integer read
.It Bad data found on real read
E 10
E 5
Usually, non-numeric input was found for a number.
For reals, Pascal requires digits before and after the decimal
point so that numbers like `.1' or `21.' evoke the second diagnostic.
D 5
.HP 6
panic:
.I  "Some message"
.br
E 5
I 5
D 10
.Tp panic:
.Em Some message
E 10
I 10
.It panic: Em Some message
E 10
E 5
D 4
Indicates a internal inconsistency detected in
E 4
I 4
Indicates an internal inconsistency detected in
E 4
D 5
.I px
E 5
I 5
D 10
.Nm px
E 10
I 10
.Nm \&px
E 10
E 5
probably due to a Pascal system bug.
D 5
.SH AUTHORS
E 5
I 5
D 10
.Tp
.Sh AUTHORS
E 5
Charles B. Haley, William Joy, and Ken Thompson
.br
VAX-11 version by Kirk McKusick
E 10
I 10
.El
E 10
D 5
.SH BUGS
E 5
I 5
.Sh HISTORY
I 11
The
E 11
D 10
.Nm Px
appeared in 3 BSD.
E 10
I 10
.Nm \&Px
D 11
appeared in
E 11
I 11
comman appeared in
E 11
.Bx 3.0 .
E 10
.Sh BUGS
E 5
Post-mortem traceback is not limited;
infinite recursion leads to almost infinite traceback.
E 1
