h31114
s 00017/00005/00128
d D 8.2 94/03/27 08:59:53 bostic 7 6
c Jan-Simon Pendry's and my new mount code
e
s 00002/00002/00131
d D 8.1 93/06/09 19:07:11 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00004/00131
d D 5.4 93/06/09 19:07:07 bostic 5 3
c fixed the under development line
e
s 00002/00002/00133
d R 8.1 93/06/05 11:02:05 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00032/00007/00103
d D 5.3 93/05/28 02:53:44 pendry 3 2
c update for new kernel filesystem
e
s 00003/00001/00107
d D 5.2 92/07/05 14:27:51 bostic 2 1
c integrate into the source tree, minor cleanups, bug fixes
e
s 00108/00000/00000
d D 5.1 92/07/05 14:15:13 bostic 1 0
c date and time created 92/07/05 14:15:13 by bostic
e
u
U
t
T
I 1
.\"
D 6
.\" Copyright (c) 1992 The Regents of the University of California
.\" Copyright (c) 1990, 1992 Jan-Simon Pendry
E 6
I 6
D 7
.\" Copyright (c) 1992, 1993
E 7
I 7
.\" Copyright (c) 1992, 1993, 1994
E 7
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\" All rights reserved.
.\"
.\" This code is derived from software donated to Berkeley by
.\" Jan-Simon Pendry.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	%W% (Berkeley) %G%
.\"
.\"
.Dd %Q%
.Dt MOUNT_FDESC 8
.Os BSD 4.4
.Sh NAME
.Nm mount_fdesc
D 3
.Nd mount the /dev/fd file system
E 3
I 3
.Nd mount the file-descriptor file system
E 3
.Sh SYNOPSIS
.Nm mount_fdesc
D 2
.Pa /dev/fd /dev/fd
E 2
I 2
D 7
.Op Fl F Ar fsoptions
D 3
.Pa /dev/fd
E 3
I 3
.Pa fdesc
E 3
.Pa mount_point
E 7
I 7
.Op Fl o Ar options
.Ar fdesc
.Ar mount_point
E 7
E 2
.Sh DESCRIPTION
The
.Nm mount_fdesc
command attaches an instance of the per-process file descriptor
namespace to the global filesystem namespace.
The conventional mount point is
D 3
.Pa /dev/fd .
E 3
I 3
.Pa /dev
and the filesystem should be union mounted in order to augment,
rather than replace, the existing entries in
.Pa /dev .
E 3
This command is normally executed by
.Xr mount 8
at boot time.
.Pp
I 7
The options are as follows:
.Bl -tag -width indent
.It Fl o
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
.El
.Pp
E 7
D 3
The contents of the mount point appear as a list of numbered files
E 3
I 3
The contents of the mount point are
.Pa fd ,
.Pa stderr ,
.Pa stdin ,
.Pa stdout 
and
.Pa tty .
.Pp
.Pa fd
is a directory whose contents
appear as a list of numbered files
E 3
which correspond to the open files of the process reading the
directory.
The files
.Pa /dev/fd/0
through
.Pa /dev/fd/#
refer to file descriptors which can be accessed through the file
system.
If the file descriptor is open and the mode the file is being opened
with is a subset of the mode of the existing descriptor, the call:
.Bd -literal -offset indent
fd = open("/dev/fd/0", mode);
.Ed
.Pp
and the call:
.Bd -literal -offset indent
fd = fcntl(0, F_DUPFD, 0);
.Ed
.Pp
are equivalent.
.Pp
D 3
Opening the files
E 3
I 3
The files
E 3
.Pa /dev/stdin ,
.Pa /dev/stdout
and
.Pa /dev/stderr
D 3
is equivalent to the following calls:
E 3
I 3
appear as symlinks to the relevant entry in the
.Pa /dev/fd
sub-directory.
Opening them is equivalent to the following calls:
E 3
.Bd -literal -offset indent
fd = fcntl(STDIN_FILENO,  F_DUPFD, 0);
fd = fcntl(STDOUT_FILENO, F_DUPFD, 0);
fd = fcntl(STDERR_FILENO, F_DUPFD, 0);
.Ed
.Pp
Flags to the
.Xr open 2
call other than
.Dv O_RDONLY , 
.Dv O_WRONLY
and
.Dv O_RDWR
are ignored.
I 3
.Pp
The
.Pa /dev/tty
entry is an indirect reference to the current process's controlling terminal.
It appears as a named pipe (FIFO) but behaves in exactly the same way as
the real controlling terminal device.
E 3
.Sh FILES
.Bl -tag -width /dev/stderr -compact
.It Pa /dev/fd/#
.It Pa /dev/stdin
.It Pa /dev/stdout
.It Pa /dev/stderr
I 3
.It Pa /dev/tty
E 3
.El
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
.Xr tty 4 ,
D 7
.Xr fstab 5
E 7
I 7
.Xr fstab 5 ,
.Xr mount 8
E 7
.Sh CAVEATS
No
.Pa .
and
.Pa ..
D 3
entries appear when listing the contents of the mount point.
E 3
I 3
entries appear when listing the contents of the
.Pa /dev/fd
directory.
E 3
This makes sense in the context of this filesystem, but is inconsistent
with usual filesystem conventions.
However, it is still possible to refer to both
.Pa .
and 
.Pa ..
in a pathname.
.Pp
This filesystem may not be NFS-exported.
.Sh HISTORY
The
D 5
.Nm
descriptor filesystem
is
.Ud
E 5
I 5
.Nm mount_fdesc
utility first appeared in 4.4BSD.
E 5
E 1
