h54481
s 00047/00037/00020
d D 5.3 91/09/08 17:55:21 cael 3 2
c mdoc version three
e
s 00003/00002/00054
d D 5.2 91/04/20 11:37:08 cael 2 1
c added redist.man
e
s 00056/00000/00000
d D 5.1 91/01/20 16:16:55 bostic 1 0
c break out of arff(8) and clean up
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1980 Regents of the University of California.
E 3
I 3
.\" Copyright (c) 1980, 1991 Regents of the University of California.
E 3
D 2
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 2
I 2
.\" All rights reserved.
.\"
D 3
.\" %sccs.include.redist.man%
E 3
I 3
.\" %sccs.include.redist.roff%
E 3
E 2
.\"
.\"	%W% (Berkeley) %G%
.\"
D 3
.TH FLCOPY 8 "%Q%"
.UC 4
.SH NAME
flcopy \- floppy copy
.SH SYNOPSIS
.nf
.ft B
flcopy [ \-hr ] [ \-f file ] [ \-t ntracks ]
.ft R
.fi
.SH DESCRIPTION
.I Flcopy
copies the console floppy disk (``/dev/floppy'') to a file in the
current directory, named ``floppy''.
E 3
I 3
.Dd %Q%
.Dt FLCOPY 8
.Os BSD 4
.Sh NAME
.Nm flcopy
.Nd floppy copy
.Sh SYNOPSIS
.Nm flcopy
.Op Fl hr
.Op Fl f Ar file
.Op Fl t Ar ntracks
.Sh DESCRIPTION
.Nm Flcopy
copies the console floppy disk
.Dq Pa /dev/floppy
to a file in the
current directory, named
.Dq Pa floppy .
E 3
The user is then prompted to change the floppy, and enter a carriage
return when done.
When a carriage return is entered,
D 3
.I flcopy
E 3
I 3
.Nm flcopy
E 3
copies the file out to the floppy disk.
D 3
.PP
E 3
I 3
.Pp
E 3
The options are as follows:
D 3
.TP
\-f
E 3
I 3
.Bl -tag -width indent
.It Fl f
E 3
Use 
D 3
.I file
E 3
I 3
.Ar file
E 3
instead of ``/dev/floppy''.
D 3
.TP
-h
E 3
I 3
.It Fl h
E 3
Cause
D 3
.I flcopy
E 3
I 3
.Nm flcopy
E 3
to copy a file named ``floppy'' in the current directory to
the console floppy disk.
D 3
.TP
\-r
E 3
I 3
.It Fl r
E 3
Cause
D 3
.I flcopy
E 3
I 3
.Nm flcopy
E 3
to copy the floppy to the current directory and then quit.
D 3
.TP
\-t
E 3
I 3
.It Fl t
E 3
Copy only the first 
D 3
.I ntracks
E 3
I 3
.Ar ntracks
E 3
tracks.
D 3
.SH FILES
floppy			temporary file name
.br
/dev/floppy		default floppy device
.SH SEE ALSO
crl(4), fl(4), rx(4), tu(4), arff(8), rxformat(8)
.SH BUGS
E 3
I 3
.El
.Sh FILES
.Bl -tag -width /dev/floppy  -compact
.It Pa floppy
Temporary file name.
.It Pa /dev/floppy
Default floppy device.
.El
.Sh SEE ALSO
.Xr crl 4 ,
.Xr fl 4 ,
.Xr rx 4 ,
.Xr tu 4 ,
.Xr arff 8 ,
.Xr rxformat 8
.Sh BUGS
E 3
Device errors are handled ungracefully.
E 1
