
/* $XConsortium: pexapi.m,v 5.4 92/02/24 15:57:23 mor Exp $ */

/*****************************************************************
Copyright (c) 1989, 1990, 1991,1990 by Sun Microsystems, Inc. and the X Consortium.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in 
supporting documentation, and that the names of Sun Microsystems,
the X Consortium, and MIT not be used in advertising or publicity 
pertaining to distribution of the software without specific, written 
prior permission.  

SUN MICROSYSTEMS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, 
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT 
SHALL SUN MICROSYSTEMS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/

void
popen_ar_file(Pint,char*)
void
pclose_ar_file(Pint)
void
par_structs(Pint,Pint_list*)
void
par_struct_nets(Pint,Pint_list*)
void
par_all_structs(Pint)
void
pset_conf_res(Pconf_res,Pconf_res)
void
pret_struct_ids(Pint,Pint,Pint,Pint_list*,Pint*)
void
pret_structs(Pint,Pint_list*)
void
pret_struct_nets(Pint,Pint_list*)
void
pret_all_structs(Pint)
void
pdel_structs_ar(Pint,Pint_list*)
void
pdel_struct_nets_ar(Pint,Pint_list*)
void
pdel_all_structs_ar(Pint)
void
pinq_ar_st(Par_st*)
void
pinq_ar_files(Pstore,Pint*,Par_file_list**)
void
pinq_conf_res(Pint*,Pconf_res*,Pconf_res*)
void
pinq_all_conf_structs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_conf_structs_net(Pint,Pint,Pstruct_net_source,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pret_paths_descs(Pint,Pint,Ppath_order,Pint,Pstore,Pelem_ref_list_list**,Pint*)
void
pret_paths_ances(Pint,Pint,Ppath_order,Pint,Pstore,Pelem_ref_list_list**,Pint*)
void
pcell_array3(Pparal*,Ppat_rep)
void
pcell_array(Prect*,Ppat_rep)
void
pcell_array3_plus(Pparal*,Pint_size*,Pint,Pcoval*)
void
pset_colr_rep(Pint,Pint,Pcolr_rep*)
void
pset_colr_model(Pint,Pint)
void
popen_xphigs(char*,size_t,long,Pxphigs_info*)
void
popen_phigs(char*,size_t)
void
pclose_phigs()
void
pinq_sys_st(Psys_st*)
void
pinq_phigs_facs(Pint,Pint,Pint*,Pint*,Pint*,Pint*,Pint_list*,Pint*,Pint*,Pint*)
void
pinq_gse_facs(Pint,Pint,Pint*,Pgse_id_dep_list*,Pint*)
void
pinq_model_clip_facs(Pint,Pint,Pint*,Pint*,Pint_list*,Pint*)
void
pemergency_close_phigs()
void
pset_dcue_ind(Pint)
void
pset_dcue_rep(Pint,Pint,Pdcue_bundle*)
void
pinq_dcue_rep(Pint,Pint,Pinq_type,Pint*,Pdcue_bundle*)
void
perr_hand(Pint,Pint,char*)
void
pset_err_hand_mode(Perr_mode)
void
pinq_err_hand_mode(Pint*,Perr_mode*)
void
perr_log(Pint,Pint,char*)
void
phg_cb_format_err_msg(int,int,int,char*)
void
pescape(Pint,Pescape_in_data*,Pstore,Pescape_out_data**)
void
pfill_area3(Ppoint_list3*)
void
pfill_area(Ppoint_list*)
void
pfill_area_set3(Ppoint_list_list3*)
void
pfill_area_set3_data(Pint,Pint,Pint,Pint,Pfacet_data3*,Pint,Pedge_data_list*,Pfacet_vdata_list3*)
void
pfill_area_set(Ppoint_list_list*)
void
ptri_strip3_data(Pint,Pint,Pint,Pint,Pfacet_data_arr3*,Pfacet_vdata_arr3*)
void
pquad_mesh3_data(Pint,Pint,Pint,Pint_size*,Pfacet_data_arr3*,Pfacet_vdata_arr3*)
void
pset_of_fill_area_set3_data(Pint,Pint,Pint,Pint,Pint,Pfacet_data_arr3*,Pedge_data_list_list*,Pint_list_list*,Pfacet_vdata_list3*)
void
pset_int_ind(Pint)
void
pset_edge_ind(Pint)
void
pset_int_style(Pint_style)
void
pset_back_int_style(Pint_style)
void
pset_int_style_ind(Pint)
void
pset_back_int_style_ind(Pint)
void
pset_int_colr_ind(Pint)
void
pset_int_colr(Pgcolr*)
void
pset_back_int_colr(Pgcolr*)
void
pset_edge_flag(Pedge_flag)
void
pset_edgetype(Pint)
void
pset_edgewidth(Pfloat)
void
pset_edge_colr_ind(Pint)
void
pset_edge_colr(Pgcolr*)
void
pset_pat_size(Pfloat,Pfloat)
void
pset_pat_ref_point_vecs(Ppoint3*,Pvec3*)
void
pset_pat_ref_point(Ppoint*)
void
pset_int_rep(Pint,Pint,Pint_bundle*)
void
pset_edge_rep(Pint,Pint,Pedge_bundle*)
void
pset_edge_rep_plus(Pint,Pint,Pedge_bundle_plus*)
void
pset_pat_rep(Pint,Pint,Ppat_rep*)
void
pset_pat_rep_plus(Pint,Pint,Ppat_rep_plus*)
void
pset_int_shad_meth(Pint)
void
pset_back_int_shad_meth(Pint)
void
pset_int_rep_plus(Pint,Pint,Pint_bundle_plus*)
void
pset_hlhsr_id(Pint)
void
pset_loc_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pset_stroke_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pset_val_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pset_choice_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pset_pick_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pset_string_mode(Pint,Pint,Pop_mode,Pecho_switch)
void
pawait_event(Pfloat,Pint*,Pin_class*,Pint*)
void
pflush_events(Pint,Pin_class,Pint)
void
pget_loc3(Pint*,Ppoint3*)
void
pget_loc(Pint*,Ppoint*)
void
pget_stroke3(Pint*,Ppoint_list3*)
void
pget_stroke(Pint*,Ppoint_list*)
void
pget_val(Pfloat*)
void
pget_choice(Pin_status*,Pint*)
void
pget_pick(Pint,Pin_status*,Ppick_path*)
void
pget_string(char*)
void
psample_loc(Pint,Pint,Pint*,Ppoint*)
void
psample_loc3(Pint,Pint,Pint*,Ppoint3*)
void
psample_stroke(Pint,Pint,Pint*,Ppoint_list*)
void
psample_stroke3(Pint,Pint,Pint*,Ppoint_list3*)
void
psample_val(Pint,Pint,Pfloat*)
void
psample_choice(Pint,Pint,Pin_status*,Pint*)
void
psample_pick(Pint,Pint,Pint,Pin_status*,Ppick_path*)
void
psample_string(Pint,Pint,char*)
void
preq_loc3(Pint,Pint,Pin_status*,Pint*,Ppoint3*)
void
preq_loc(Pint,Pint,Pin_status*,Pint*,Ppoint*)
void
preq_stroke3(Pint,Pint,Pin_status*,Pint*,Ppoint_list3*)
void
preq_stroke(Pint,Pint,Pin_status*,Pint*,Ppoint_list*)
void
preq_val(Pint,Pint,Pin_status*,Pfloat*)
void
preq_choice(Pint,Pint,Pin_status*,Pint*)
void
preq_pick(Pint,Pint,Pint,Pin_status*,Ppick_path*)
void
preq_string(Pint,Pint,Pin_status*,char*)
void
pinit_loc3(Pint,Pint,Pint,Ppoint3*,Pint,Plimit3*,Ploc_data3*)
void
pinit_loc(Pint,Pint,Pint,Ppoint*,Pint,Plimit*,Ploc_data*)
void
pinit_stroke3(Pint,Pint,Pint,Ppoint_list3*,Pint,Plimit3*,Pstroke_data3*)
void
pinit_stroke(Pint,Pint,Pint,Ppoint_list*,Pint,Plimit*,Pstroke_data*)
void
pinit_val3(Pint,Pint,Pfloat,Pint,Plimit3*,Pval_data3*)
void
pinit_val(Pint,Pint,Pfloat,Pint,Plimit*,Pval_data*)
void
pinit_choice3(Pint,Pint,Pin_status,Pint,Pint,Plimit3*,Pchoice_data3*)
void
pinit_choice(Pint,Pint,Pin_status,Pint,Pint,Plimit*,Pchoice_data*)
void
pinit_pick3(Pint,Pint,Pin_status,Ppick_path*,Pint,Plimit3*,Ppick_data3*,Ppath_order)
void
pinit_pick(Pint,Pint,Pin_status,Ppick_path*,Pint,Plimit*,Ppick_data*,Ppath_order)
void
pinit_string3(Pint,Pint,char*,Pint,Plimit3*,Pstring_data3*)
void
pinit_string(Pint,Pint,char*,Pint,Plimit*,Pstring_data*)
void
pset_pick_filter(Pint,Pint,Pfilter*)
void
pinq_loc_st3(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pint*,Ppoint3*,Pint*,Plimit3*,Ploc_data3**)
void
pinq_loc_st(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pint*,Ppoint*,Pint*,Plimit*,Ploc_data**)
void
pinq_stroke_st3(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pint*,Ppoint_list3**,Pint*,Plimit3*,Pstroke_data3**)
void
pinq_stroke_st(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pint*,Ppoint_list**,Pint*,Plimit*,Pstroke_data**)
void
pinq_val_st3(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pfloat*,Pint*,Plimit3*,Pval_data3**)
void
pinq_val_st(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pfloat*,Pint*,Plimit*,Pval_data**)
void
pinq_choice_st3(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pin_status*,Pint*,Pint*,Plimit3*,Pchoice_data3**)
void
pinq_choice_st(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pin_status*,Pint*,Pint*,Plimit*,Pchoice_data**)
void
pinq_pick_st3(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pfilter**,Pin_status*,Ppick_path**,Pint*,Plimit3*,Ppick_data3**,Ppath_order*)
void
pinq_pick_st(Pint,Pint,Pinq_type,Pstore,Pint*,Pop_mode*,Pecho_switch*,Pfilter**,Pin_status*,Ppick_path**,Pint*,Plimit*,Ppick_data**,Ppath_order*)
void
pinq_string_st3(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,char**,Pint*,Plimit3*,Pstring_data3**)
void
pinq_string_st(Pint,Pint,Pstore,Pint*,Pop_mode*,Pecho_switch*,char**,Pint*,Plimit*,Pstring_data**)
void
pinq_more_simult_events(Pint*,Pmore_simult_events*)
void
pinq_in_overf(Pint*,Pint*,Pin_class*,Pint*)
void
pcomp_fill_area_set_gnorm(Pint,Pint,Pfacet_vdata_list3*,Pint*,Pvec3*)
void
pset_refl_props(Prefl_props*)
void
pset_back_refl_props(Prefl_props*)
void
pset_refl_eqn(Pint)
void
pset_back_refl_eqn(Pint)
void
pset_face_disting_mode(Pdisting_mode)
void
pset_face_cull_mode(Pcull_mode)
void
pset_light_src_state(Pint_list*,Pint_list*)
void
pset_light_src_rep(Pint,Pint,Plight_src_bundle*)
void
pinq_light_src_rep(Pint,Pint,Pinq_type,Pint*,Plight_src_bundle*)
void
pwrite_item(Pint,Pint,Pint,Pitem_data*)
void
pget_item_type(Pint,Pint*,Pint*)
void
pread_item(Pint,Pint,Pitem_data*)
void
pinterpret_item(Pint,Pint,Pitem_data*)
void
padd_names_set(Pint_list*)
void
premove_names_set(Pint_list*)
void
pnuni_bsp_curv(Pint,Pfloat_list*,Prational,Ppoint_list34*,Pfloat,Pfloat)
void
pset_curve_approx(Pint,Pfloat)
void
/*
pnuni_bsp_surf(Pint,Pint,Pfloat_list*,Pfloat_list*,Prational,Ppoint_grid34*,Ppcs_limit*,Pint,Ptrimcurve_list*)
*/
pnuni_bsp_surf(Pint,Pint,Pfloat_list*,Pfloat_list*,Prational,Ppoint_grid34*,Pint,Ptrimcurve_list*)
void
pset_surf_approx(Pint,Pfloat,Pfloat)
void
ppolyline3(Ppoint_list3*)
void
ppolyline_set3_data(Pint,Pint,Pint,Pline_vdata_list3*)
void
ppolyline(Ppoint_list*)
void
pset_linetype(Pint)
void
pset_linewidth(Pfloat)
void
pset_line_colr_ind(Pint)
void
pset_line_colr(Pgcolr*)
void
pset_line_ind(Pint)
void
pset_line_rep(Pint,Pint,Pline_bundle*)
void
pset_line_rep_plus(Pint,Pint,Pline_bundle_plus*)
void
pset_line_shad_meth(Pint)
void
pinq_line_rep(Pint,Pint,Pinq_type,Pint*,Pline_bundle*)
void
pinq_line_rep_plus(Pint,Pint,Pinq_type,Pint*,Pline_bundle_plus*)
void
ppolymarker3(Ppoint_list3*)
void
ppolymarker(Ppoint_list*)
void
pset_marker_type(Pint)
void
pset_marker_size(Pfloat)
void
pset_marker_colr_ind(Pint)
void
pset_marker_colr(Pgcolr*)
void
pset_marker_ind(Pint)
void
pset_marker_rep(Pint,Pint,Pmarker_bundle*)
void
pset_marker_rep_plus(Pint,Pint,Pmarker_bundle_plus*)
void
pinq_marker_rep(Pint,Pint,Pinq_type,Pint*,Pmarker_bundle*)
void
pinq_marker_rep_plus(Pint,Pint,Pinq_type,Pint*,Pmarker_bundle_plus*)
void
popen_struct(Pint)
void
pclose_struct()
void
pcopy_all_elems_struct(Pint)
void
pdel_elem()
void
pdel_elem_range(Pint,Pint)
void
pdel_elems_labels(Pint,Pint)
void
pempty_struct(Pint)
void
pdel_struct(Pint)
void
pdel_struct_net(Pint,Pref_flag)
void
pdel_all_structs()
void
pchange_struct_id(Pint,Pint)
void
pchange_struct_refs(Pint,Pint)
void
pchange_struct_id_refs(Pint,Pint)
void
pset_elem_ptr(Pint)
void
poffset_elem_ptr(Pint)
void
pset_elem_ptr_label(Pint)
void
pset_edit_mode(Pedit_mode)
void
pinq_elem_ptr(Pint*,Pint*)
void
pinq_edit_mode(Pint*,Pedit_mode*)
void
pset_indiv_asf(Paspect,Pasf)
void
pset_local_tran3(Pmatrix3,Pcompose_type)
void
pset_local_tran(Pmatrix,Pcompose_type)
void
pset_global_tran3(Pmatrix3)
void
pset_global_tran(Pmatrix)
void
pset_view_ind(Pint)
void
pexec_struct(Pint)
void
plabel(Pint)
void
pappl_data(Pdata*)
void
pset_pick_id(Pint)
void
pset_model_clip_vol3(Pint,Phalf_space_list3*)
void
pset_model_clip_vol(Pint,Phalf_space_list*)
void
pset_model_clip_ind(Pclip_ind)
void
prestore_model_clip_vol()
void
pgdp3(Ppoint_list3*,Pint,Pgdp_data3*)
void
pgdp(Ppoint_list*,Pint,Pgdp_data*)
void
pgse(Pint,Pgse_data*)
void
ppost_struct(Pint,Pint,Pfloat)
void
punpost_struct(Pint,Pint)
void
punpost_all_structs(Pint)
void
pinq_struct_st(Pstruct_st*)
void
pinq_open_struct(Pint*,Popen_struct_status*,Pint*)
void
pinq_struct_status(Pint,Pint*,Pstruct_status*)
void
pinq_cur_elem_type_size(Pint*,Pelem_type*,size_t*)
void
pinq_elem_type_size(Pint,Pint,Pint*,Pelem_type*,size_t*)
void
pinq_cur_elem_content(Pstore,Pint*,Pelem_data**)
void
pinq_elem_content(Pint,Pint,Pstore,Pint*,Pelem_data**)
void
pinq_struct_ids(Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_paths_ances(Pint,Ppath_order,Pint,Pstore,Pint*,Pelem_ref_list_list**)
void
pinq_paths_descs(Pint,Ppath_order,Pint,Pstore,Pint*,Pelem_ref_list_list**)
void
pinq_wss_posted(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pelem_search(Pint,Pint,Psearch_dir,Pelem_type_list*,Pelem_type_list*,Pint*,Psearch_status*,Pint*)
void
pincr_spa_search3(Ppoint3*,Pfloat,Pelem_ref_list*,Pclip_ind,Pint,Pfilter_list*,Pfilter_list*,Pint,Pint,Pint*,Pelem_ref_list*,Pint*)
void
pincr_spa_search(Ppoint*,Pfloat,Pelem_ref_list*,Pclip_ind,Pint,Pfilter_list*,Pfilter_list*,Pint,Pint,Pint*,Pelem_ref_list*,Pint*)
void
ptext3(Ppoint3*,Pvec3*,char*)
void
ptext(Ppoint*,char*)
void
pset_text_font(Pint)
void
pset_text_prec(Ptext_prec)
void
pset_char_expan(Pfloat)
void
pset_char_space(Pfloat)
void
pset_text_colr_ind(Pint)
void
pset_text_colr(Pgcolr*)
void
pset_char_ht(Pfloat)
void
pset_char_up_vec(Pvec*)
void
pset_text_path(Ptext_path)
void
pset_text_align(Ptext_align*)
void
pset_text_ind(Pint)
void
pset_text_rep(Pint,Pint,Ptext_bundle*)
void
pset_text_rep_plus(Pint,Pint,Ptext_bundle_plus*)
void
pinq_text_extent(Pint,Pint,Pfloat,Pfloat,Pfloat,Ptext_path,Phor_text_align,Pvert_text_align,char*,Pint*,Prect*,Ppoint*)
void
panno_text_rel3(Ppoint3*,Pvec3*,char*)
void
panno_text_rel(Ppoint*,Pvec3*,char*)
void
pset_anno_char_ht(Pfloat)
void
pset_anno_char_up_vec(Pvec*)
void
pset_anno_path(Ptext_path)
void
pset_anno_align(Ptext_align*)
void
pset_anno_style(Pint)
void
pcreate_store(Pint*,Pstore*)
void
pdel_store(Pstore)
void
popen_ws(Pint,char*,Pint)
void
pclose_ws(Pint)
void
pmessage(Pint,char*)
void
predraw_all_structs(Pint,Pctrl_flag)
void
pupd_ws(Pint,Pregen_flag)
void
pset_disp_upd_st(Pint,Pdefer_mode,Pmod_mode)
void
pset_view_rep3(Pint,Pint,Pview_rep3*)
void
pset_view_rep(Pint,Pint,Pview_rep*)
void
pset_view_tran_in_pri(Pint,Pint,Pint,Prel_pri)
void
pset_ws_win3(Pint,Plimit3*)
void
pset_ws_win(Pint,Plimit*)
void
pset_ws_vp3(Pint,Plimit3*)
void
pset_ws_vp(Pint,Plimit*)
void
pset_highl_filter(Pint,Pfilter*)
void
pset_invis_filter(Pint,Pfilter*)
void
pset_hlhsr_mode(Pint,Pint)
void
pinq_ws_st(Pws_st*)
void
pinq_ws_conn_type(Pint,Pint,Pint*,char**,Pint*)
void
pinq_open_wss(Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_view_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_posted_structs(Pint,Pint,Pint,Pint*,Pposted_struct_list*,Pint*)
void
pinq_view_rep(Pint,Pint,Pint*,Pupd_st*,Pview_rep3*,Pview_rep3*)
void
pinq_ws_tran3(Pint,Pint*,Pupd_st*,Plimit3*,Plimit3*,Plimit3*,Plimit3*)
void
pinq_ws_tran(Pint,Pint*,Pupd_st*,Plimit*,Plimit*,Plimit*,Plimit*)
void
pinq_disp_upd_st(Pint,Pint*,Pdefer_mode*,Pmod_mode*,Pdisp_surf_empty*,Pvisual_st*)
void
pinq_list_line_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_light_src_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_dcue_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_marker_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_text_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_int_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_edge_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_pat_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_colr_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_text_rep(Pint,Pint,Pinq_type,Pint*,Ptext_bundle*)
void
pinq_text_rep_plus(Pint,Pint,Pinq_type,Pint*,Ptext_bundle_plus*)
void
pinq_int_rep(Pint,Pint,Pinq_type,Pint*,Pint_bundle*)
void
pinq_int_rep_plus(Pint,Pint,Pinq_type,Pint*,Pint_bundle_plus*)
void
pinq_edge_rep(Pint,Pint,Pinq_type,Pint*,Pedge_bundle*)
void
pinq_edge_rep_plus(Pint,Pint,Pinq_type,Pint*,Pedge_bundle_plus*)
void
pinq_colr_rep(Pint,Pint,Pinq_type,Pint*,Pcolr_rep*)
void
pinq_pat_rep(Pint,Pint,Pinq_type,Pstore,Pint*,Ppat_rep**)
void
pinq_pat_rep_plus(Pint,Pint,Pinq_type,Pstore,Pint*,Ppat_rep_plus**)
void
pinq_highl_filter(Pint,Pstore,Pint*,Pfilter**)
void
pinq_invis_filter(Pint,Pstore,Pint*,Pfilter**)
void
pinq_colr_model(Pint,Pint*,Pint*)
void
pinq_hlhsr_mode(Pint,Pint*,Pupd_st*,Pint*,Pint*)
caddr_t
phigs_ws_type_set(Pint,caddr_t*)
caddr_t
phigs_ws_type_get(Pint,Phigs_ws_type_attr,char*)
Pint
phigs_ws_type_create(Pint,caddr_t*)
void
phigs_ws_type_destroy(Pint)
void
pinq_list_avail_ws_types(Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_num_disp_pris(Pint,Pint*,Pint*)
void
pinq_ws_cat(Pint,Pint*,Pws_cat*)
void
pinq_disp_space_size3(Pint,Pint*,Pdisp_space_size3*)
void
pinq_disp_space_size(Pint,Pint*,Pdisp_space_size*)
void
pinq_hlhsr_id_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_hlhsr_mode_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_view_facs(Pint,Pint*,Pint*)
void
pinq_pred_view_rep(Pint,Pint,Pint*,Pview_rep3*)
void
pinq_ws_class(Pint,Pint*,Pws_class*)
void
pinq_dyns_ws_attrs(Pint,Pint*,Pdyns_ws_attrs*)
void
pinq_def_disp_upd_st(Pint,Pint*,Pdefer_mode*,Pmod_mode*)
void
pinq_line_facs(Pint,Pint,Pint,Pint*,Pline_facs*,Pint*)
void
pinq_line_facs_plus(Pint,Pint,Pint,Pint,Pint,Pint*,Pint*,Pint*,Pline_facs_plus*)
void
pinq_pred_line_rep(Pint,Pint,Pint*,Pline_bundle*)
void
pinq_pred_line_rep_plus(Pint,Pint,Pint*,Pline_bundle_plus*)
void
pinq_marker_facs(Pint,Pint,Pint,Pint*,Pmarker_facs*,Pint*)
void
pinq_pred_marker_rep(Pint,Pint,Pint*,Pmarker_bundle*)
void
pinq_pred_marker_rep_plus(Pint,Pint,Pint*,Pmarker_bundle_plus*)
void
pinq_text_facs(Pint,Pint,Pint,Pint*,Ptext_facs*,Pint*)
void
pinq_pred_text_rep(Pint,Pint,Pint*,Ptext_bundle*)
void
pinq_pred_text_rep_plus(Pint,Pint,Pint*,Ptext_bundle_plus*)
void
pinq_anno_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*,Pint*,Pfloat*,Pfloat*)
void
pinq_int_facs(Pint,Pint,Pint,Pint*,Pint_facs*,Pint*)
void
pinq_int_facs_plus(Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint*,Pint_facs_plus*,Pint*,Pint*,Pint*,Pint*)
void
pinq_pred_int_rep(Pint,Pint,Pint*,Pint_bundle*)
void
pinq_pred_int_rep_plus(Pint,Pint,Pint*,Pint_bundle_plus*)
void
pinq_edge_facs(Pint,Pint,Pint,Pint*,Pedge_facs*,Pint*)
void
pinq_pred_edge_rep(Pint,Pint,Pint*,Pedge_bundle*)
void
pinq_pred_edge_rep_plus(Pint,Pint,Pint*,Pedge_bundle_plus*)
void
pinq_pat_facs(Pint,Pint*,Pint*)
void
pinq_pred_pat_rep(Pint,Pint,Pstore,Pint*,Ppat_rep**)
void
pinq_pred_pat_rep_plus(Pint,Pint,Pstore,Pint*,Ppat_rep_plus**)
void
pinq_colr_model_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*,Pint*)
void
pinq_direct_colr_model_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_colr_facs(Pint,Pint*,Pcolr_facs*)
void
pinq_pred_colr_rep(Pint,Pint,Pint*,Pcolr_rep*)
void
pinq_list_avail_gdp3(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_list_avail_gdp(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_gdp3(Pint,Pint,Pint*,Pint*,Pattrs*)
void
pinq_gdp(Pint,Pint,Pint*,Pint*,Pattrs*)
void
pinq_list_avail_gse(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_ws_st_table(Pint,Pint*,Pws_st_tables*)
void
pinq_ws_st_table_plus(Pint,Pint*,Pws_tables_plus*)
void
pinq_dyns_structs(Pint,Pint*,Pdyns_structs*)
void
pinq_num_avail_in(Pint,Pint*,Pnum_in*)
void
pinq_def_loc_data3(Pint,Pint,Pstore,Pint,Ppoint3*,Pint_list**,Plimit3*,Ploc_data3**)
void
pinq_def_loc_data(Pint,Pint,Pstore,Pint*,Ppoint*,Pint_list*,Pint*,Plimit*,Ploc_data**)
void
pinq_def_stroke_data3(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Pint*,Plimit3*,Pstroke_data3**)
void
pinq_def_stroke_data(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Plimit*,Pstroke_data**)
void
pinq_def_val_data3(Pint,Pint,Pint,Pint,Pstore,Pint*,Pfloat*,Pint_list*,Pint*,Plimit3*,Pval_data3**)
void
pinq_def_val_data(Pint,Pint,Pint,Pint,Pstore,Pint*,Pfloat*,Pint_list*,Pint*,Plimit*,Pval_data**)
void
pinq_def_choice_data3(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Plimit3*,Pchoice_data3**)
void
pinq_def_choice_data(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Plimit*,Pchoice_data**)
void
pinq_def_pick_data3(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint_list*,Pint*,Plimit3*,Ppick_data3**,Ppath_order*)
void
pinq_def_pick_data(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint_list*,Pint*,Plimit*,Ppick_data**,Ppath_order*)
void
pinq_def_string_data3(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Plimit3*,Pstring_data3**)
void
pinq_def_string_data(Pint,Pint,Pint,Pint,Pstore,Pint*,Pint*,Pint_list*,Pint*,Plimit*,Pstring_data**)
void
pinq_curv_surf_facs(Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint,Pint*,Pcurvsurf_facs*,Pint*,Pint*,Pint*,Pint*)
void
pinq_dcue_facs(Pint,Pint*,Pint*)
void
pinq_pred_dcue_rep(Pint,Pint,Pint*,Pdcue_bundle*)
void
pinq_light_src_facs(Pint,Pint,Pint,Pint*,Pint*,Plight_src_facs*)
void
pinq_pred_light_src_rep(Pint,Pint,Pint*,Plight_src_bundle*)
void
ptranslate3(Pvec3*,Pint*,Pmatrix3)
void
ptranslate(Pvec*,Pint*,Pmatrix)
void
pscale3(Pvec3*,Pint*,Pmatrix3)
void
pscale(Pvec*,Pint*,Pmatrix)
void
protate_x(Pfloat,Pint*,Pmatrix3)
void
protate_y(Pfloat,Pint*,Pmatrix3)
void
protate_z(Pfloat,Pint*,Pmatrix3)
void
protate(Pfloat,Pint*,Pmatrix)
void
pcompose_matrix3(Pmatrix3,Pmatrix3,Pint*,Pmatrix3)
void
pcompose_matrix(Pmatrix,Pmatrix,Pint*,Pmatrix)
void
ptran_point3(Ppoint3*,Pmatrix3,Pint*,Ppoint3*)
void
ptran_point(Ppoint*,Pmatrix,Pint*,Ppoint*)
void
pbuild_tran_matrix3(Ppoint3*,Pvec3*,Pfloat,Pfloat,Pfloat,Pvec3*,Pint*,Pmatrix3)
void
pbuild_tran_matrix(Ppoint*,Pvec*,Pfloat,Pvec*,Pint*,Pmatrix)
void
pcompose_tran_matrix3(Pmatrix3,Ppoint3*,Pvec3*,Pfloat,Pfloat,Pfloat,Pvec3*,Pint*,Pmatrix3)
void
pcompose_tran_matrix(Pmatrix,Ppoint*,Pvec*,Pfloat,Pvec*,Pint*,Pmatrix)
void
peval_view_ori_matrix3(Ppoint3*,Pvec3*,Pvec3*,Pint*,Pmatrix3)
void
peval_view_ori_matrix(Ppoint*,Pvec*,Pint*,Pmatrix)
void
peval_view_map_matrix(Pview_map*,Pint*,Pmatrix)
void
peval_view_map_matrix3(Pview_map3*,Pint*,Pmatrix3)
void
pset_rendering_colr_model(Pint)
void
pset_para_surf_characs(Pint,Ppara_surf_characs*)
void
pinq_rendering_colr_model_facs(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_dyns_ws_attrs_plus(Pint,Pint*,Pdyns_ws_attrs_plus*)
void
pset_colr_map_ind(Pint)
void
pset_colr_map_rep(Pint,Pint,Pint,Pcolr_map_data*)
void
pinq_list_colr_map_inds(Pint,Pint,Pint,Pint*,Pint_list*,Pint*)
void
pinq_colr_map_rep(Pint,Pint,Pinq_type,Pstore,Pint*,Pint*,Pcolr_map_data**)
void
pinq_colr_map_facs(Pint,Pint,Pint,Pint*,Pcolr_map_facs*,Pint*)
void
pinq_pred_colr_map_rep(Pint,Pint,Pstore,Pint*,Pint*,Pcolr_map_data**)
