h27936
s 00001/00001/00050
d D 8.2 93/12/11 23:42:57 mckusick 3 2
c copyediting for Usenix manuals
e
s 00002/00002/00049
d D 8.1 93/06/05 13:50:54 bostic 2 1
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00051/00000/00000
d D 5.1 93/06/05 13:50:17 bostic 1 0
c date and time created 93/06/05 13:50:17 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1993 The Regents of the University of California.
.\" All rights reserved.
E 2
I 2
.\" Copyright (c) 1993
.\"	The Regents of the University of California.  All rights reserved.
E 2
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	%W% (Berkeley) %G%
.\"
.Dd "%Q%"
.Dt LFS_CLEANERD 8
.Os BSD 4.4
.Sh NAME
.Nm lfs_cleanerd
.Nd garbage collect a log-structured file system
.Sh SYNOPSIS
.Nm lfs_cleanerd
.Op Fl ds
.Pa node
.Sh DESCRIPTION
The
.Nm lfs_cleanerd
command starts a daemon process which garbage-collects
D 3
the log-structed file system residing at the point named by
E 3
I 3
the log-structured file system residing at the point named by
E 3
.Ar node
in the global file system namespace.
This command is normally executed by
.Xr mount_lfs 8
when the log-structured file system is mounted.
The daemon will exit within a few minutes
of when the file system it was cleaning is unmounted.
.Pp
Garbage collection on a log-structured file system is done by scanning
the file system's segments for active, i.e. referenced, data and copying
it to new segments.
When all of the active data in a given segment has been copied to a new
segment that segment can be marked as empty, thus reclaiming the space
taken by the inactive data which was in it.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl d
Run in debug mode.
Do not become a daemon process, and print debugging information.
.It Fl s
When cleaning the file system, read data in small chunks.
.El
.Sh SEE ALSO
.Xr mount_lfs 8
.Sh HISTORY
The
.Nm lfs_cleanerd
utility first appeared in 4.4BSD.
E 1
