h10358
s 00002/00002/00038
d D 8.1 93/06/04 17:01:45 bostic 2 1
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00040/00000/00000
d D 5.1 91/05/02 04:59:02 cael 1 0
c date and time created 91/05/02 04:59:02 by cael
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 2
I 2
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 2
.\"
.\"	%W% (Berkeley) %G%
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt FABS 3
.Os
.Sh NAME
.Nm fabs
.Nd floating-point absolute value function
.Sh SYNOPSIS
.Fd #include <math.h>
.Ft double
.Fn fabs "double x"
.Sh DESCRIPTION
The
.Fn fabs
function computes the absolute value of a floating-point number
.Fa x .
.Sh RETURN VALUES
The
.Fn fabs
function returns the absolute value of
.Fa x .
.Sh SEE ALSO
.Xr abs 3 ,
.Xr ceil 3 ,
.Xr floor 3 ,
.Xr rint 3 ,
.Xr ieee 3 ,
.Xr math.3
.Sh STANDARDS
The
.Fn fabs
function conforms to
.St -ansiC .
E 1
