h20275
s 00002/00002/00045
d D 8.1 93/06/04 17:04:46 bostic 2 1
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00047/00000/00000
d D 5.1 91/05/02 04:59:03 cael 1 0
c date and time created 91/05/02 04:59:03 by cael
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 2
I 2
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 2
.\"
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt TAN 3
.Os
.Sh NAME
.Nm tan
.Nd tangent function
.Sh SYNOPSIS
.Fd #include <math.h>
.Ft double
.Fn tan "double x"
.Sh DESCRIPTION
The
.Fn tan
function computes the tangent of
.Fa x
(measured in radians).
A large magnitude argument may yield a result
with little or no significance.
For a discussion of error due to roundoff, see
.Xr math 3 .
.Sh RETURN VALUES
The
.Fn tan
function returns the tangent value.
.Sh SEE ALSO
.Xr acos 3 ,
.Xr asin 3 ,
.Xr atan 3 ,
.Xr atan2 3 ,
.Xr cos 3 ,
.Xr cosh 3 ,
.Xr sin 3 ,
.Xr sinh 3 ,
.Xr tanh 3 ,
.Xr math 3 ,
.Sh STANDARDS
The
.Fn tan
function conforms to
.St -ansiC .
E 1
