h03974
s 00002/00002/00059
d D 8.1 93/06/05 13:43:27 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00048/00028/00013
d D 6.2 91/03/27 23:51:22 cael 3 2
c  macro and text revision (-mdoc version 3)
e
s 00001/00001/00040
d D 6.1 85/05/15 17:41:33 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00041/00000/00000
d D 5.1 85/05/15 17:41:27 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 4
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
E 3
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\" %sccs.include.redist.man%
E 3
.\"
D 2
.TH AD 4 "27 July 1983"
E 2
I 2
D 3
.TH AD 4 "%Q%"
E 2
.UC 5
.SH NAME
ad \- Data Translation A/D converter
.SH SYNOPSIS
.B "device ad0 at uba0 csr 0170400 vector adintr"
.SH DESCRIPTION
.I Ad
provides the interface to the Data Translation A/D converter.
E 3
I 3
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt AD 4 vax
.Os BSD 4.2
.Sh NAME
.Nm ad
.Nd Data Translation A/D converter
.Sh SYNOPSIS
.Cd "device ad0 at uba0 csr 0170400 vector adintr"
.Sh DESCRIPTION
The
.Nm \&ad
driver
provides an interface to the Data Translation A/D converter.
E 3
This is
D 3
.B not
E 3
I 3
.Em not
E 3
a real-time driver, but merely allows
the user process to sample the board's channels one at a time.
D 3
Each minor device selects a different A/D board.
.PP
The driver communicates to a user process by means of ioctls.
The AD_CHAN ioctl selects which channel of the board to read.
E 3
I 3
Each minor device selects a different
.Tn A/D
board.
.Pp
The driver communicates to a user process by means of
.Xr ioctl 2 Ns s.
The
.Dv AD_CHAN
.Xr ioctl
selects which channel of the board to read.
E 3
For example,
D 3
.br
.in +.5i
E 3
I 3
.Bd -literal -offset indent
E 3
chan = 5;
ioctl(fd, AD_CHAN, &chan);
D 3
.in -.5i
E 3
I 3
.Ed
.Pp
E 3
selects channel 5.
D 3
The AD_READ ioctl actually reads the data and returns it to the user
E 3
I 3
The
.Dv AD_READ
.Xr ioctl 2
actually reads the data and returns it to the user
E 3
process.
An example is
D 3
.br
.in +.5i
E 3
I 3
.Bd -literal -offset indent
E 3
ioctl(fd, AD_READ, &data);
D 3
.in -.5i
.SH FILES
/dev/ad
.SH DIAGNOSTICS
E 3
I 3
.Ed
.Sh FILES
.Bl -tag -width /dev/adx -compact
.It Pa /dev/ad
.El
.Sh DIAGNOSTICS
E 3
None.
I 3
.Sh HISTORY
The
.Nm
driver appeared in
.Bx 4.1 .
E 3
E 1
