h13533
s 00002/00002/00084
d D 8.1 93/06/05 13:46:29 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00073/00038/00013
d D 6.3 91/03/27 23:51:44 cael 5 4
c  macro and text revision (-mdoc version 3)
e
s 00001/00001/00050
d D 6.2 86/06/01 00:46:38 mis 4 3
c corrected a printf.
e
s 00001/00001/00050
d D 6.1 85/05/15 17:21:50 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00012/00008/00039
d D 5.1 85/05/15 17:21:41 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00047/00000/00000
d D 4.1 85/05/15 17:21:34 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1980, 1991 Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
E 5
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
D 2
.TH HT 4 4/1/81
E 2
I 2
D 3
.TH HT 4 "27 July 1983"
E 3
I 3
D 5
.TH HT 4 "%Q%"
E 3
E 2
.UC 4
.SH NAME
ht \- TM-03/TE-16,TU-45,TU-77 MASSBUS magtape interface
.SH SYNOPSIS
D 2
formatter ht0 at mba? drive ?
E 2
I 2
.B "master ht0 at mba? drive ?"
E 2
.br
D 2
tape tu0 at ht0 slave 0
E 2
I 2
.B "tape tu0 at ht0 slave 0"
E 2
.SH DESCRIPTION
The tm-03/transport combination provides a standard tape drive
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt HT 4 vax
.Os BSD 4
.Sh NAME
.Nm ht
.Nd
.Tn TM-03 Ns / Tn TE-16 ,
.Tn TU-45 ,
.Tn TU-77
.Tn MASSBUS
magtape device interface:
.Sh SYNOPSIS
.Cd "master ht0 at mba? drive ?"
.Cd "tape tu0 at ht0 slave 0"
.Sh DESCRIPTION
The
.Tn TM-03
transport combination provides a standard tape drive
E 5
interface as described in
D 2
.IR mt (4).
E 2
I 2
D 5
.IR mtio (4).
E 2
All drives provide both 800 and 1600 bpi; the TE-16 runs at 45 ips,
the TU-45 at 75 ips, while the TU-77 runs at 125 ips and autoloads tapes.
.SH "SEE ALSO"
D 2
mt(1), tar(1), tp(1), mtop(4), mt(4), tm(4), ts(4)
E 2
I 2
mt(1),
tar(1),
tp(1),
mtio(4),
tm(4),
ts(4),
mt(4),
ut(4)
E 2
.SH DIAGNOSTICS
\fBtu%d: no write ring\fR.  An attempt was made to write on the tape drive
E 5
I 5
.Xr mtio 4 .
All drives provide both 800 and 1600
.Tn BPI ;
the
.Tn TE-16
runs at 45
.Tn IPS ,
the
.Tn TU-45
at 75
.Tn IPS ,
while the
.Tn TU-77
runs at 125
.Tn IPS
and autoloads tapes.
.Sh DIAGNOSTICS
.Bl -diag
.It tu%d: no write ring.
An attempt was made to write on the tape drive
E 5
when no write ring was present; this message is written on the terminal of
the user who tried to access the tape.
D 5
.PP
\fBtu%d: not online\fR.  An attempt was made to access the tape while it
E 5
I 5
.Pp
.It tu%d: not online.
An attempt was made to access the tape while it
E 5
was offline; this message is written on the terminal of the user
who tried to access the tape.
D 5
.PP
D 4
\fBtu%d: can't switch density in mid-tape\fR.  An attempt was made to write
E 4
I 4
\fBtu%d: can't change density in mid-tape\fR.  An attempt was made to write
E 5
I 5
.Pp
.It tu%d: can't change density in mid-tape.
An attempt was made to write
E 5
E 4
on a tape at a different density than is already recorded on the tape.
This message is written on the terminal of the user who tried to switch
the density.
D 5
.PP
\fBtu%d: hard error bn%d mbsr=%b er=%b ds=%b\fR.   A tape error occurred
at block \fIbn\fR; the ht error register and drive status register are
E 5
I 5
.Pp
.It "tu%d: hard error bn%d mbsr=%b er=%b ds=%b."
A tape error occurred
at block
.Em bn ;
the ht error register and drive status register are
E 5
printed in octal with the bits symbolically decoded.  Any error is
fatal on non-raw tape; when possible the driver will have retried
the operation which failed several times before reporting the error.
D 5
.SH BUGS
If any non-data error is encountered on non-raw tape, it refuses to do anything
more until closed.
E 5
I 5
.El
.Sh SEE ALSO
.Xr mt 1 ,
.Xr tar 1 ,
.Xr tp 1 ,
.Xr mtio 4 ,
.Xr mt 4 ,
.Xr physio 4 ,
.Xr tm 4 ,
.Xr ts 4 ,
.Xr ut 4
.Sh HISTORY
An
.Nm
driver appeared in
.At v6 .
.Sh BUGS
May hang if physical (non-data) errors occur.
E 5
D 2
.PP
The system should remember which controlling terminal has the tape drive
open and write error messages to that terminal rather than on the console.
E 2
E 1
