h40180
s 00002/00002/00068
d D 8.1 93/06/05 13:54:25 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00069
d D 6.4 91/07/01 13:59:44 bostic 6 5
c proprietary code, add correct copyright
e
s 00004/00003/00066
d D 6.3 91/04/20 15:11:34 bostic 5 4
c new copyright; att/bsd/shared
e
s 00057/00055/00012
d D 6.2 90/06/24 19:20:22 cael 4 3
c converted man page
e
s 00001/00001/00066
d D 6.1 85/05/20 20:33:23 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00024/00018/00043
d D 5.1 85/05/20 20:33:08 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00061/00000/00000
d D 4.1 85/05/20 20:32:56 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
E 4
I 4
D 7
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
E 4
D 5
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 5
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\"     %W% (Berkeley) %G%
E 5
I 5
D 6
.\" %sccs.include.redist.roff%
E 6
I 6
.\" %sccs.include.proprietary.roff%
E 6
.\"
.\"	%W% (Berkeley) %G%
E 5
E 4
.\"
D 2
.TH TERM 7 
E 2
I 2
D 3
.TH TERM 7 "1 February 1983"
E 3
I 3
D 4
.TH TERM 7 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
terminals \- conventional names
E 2
I 2
term \- conventional names for terminals
E 2
.SH DESCRIPTION
D 2
These names
are used by certain commands and are maintained 
as part of the shell environment
(see
.IR sh (1), environ (5)).
E 2
I 2
Certain commands use these terminal names. They are maintained 
E 4
I 4
.Dd %Q%
.Dt TERM 7
.Os ATT 32v
.Sh NAME
.Nm term
.Nd conventional names for terminals
.Sh DESCRIPTION
Certain commands use these terminal names. They are maintained
E 4
as part of the shell environment (see
D 4
.IR sh (1), environ (7)).
E 2
.LP
.nf
.ta \w'450\-12\-8  'u
adm3a	Lear Seigler Adm-3a
2621	Hewlett-Packard HP262? series terminals
hp	Hewlett-Packard HP264? series terminals
c100	Human Designed Systems Concept 100
h19	Heathkit H19
mime	Microterm mime in enhanced ACT IV mode
1620	DIABLO 1620 (and others using HyType II)
300	DASI/DTC/GSI 300 (and others using HyType I)
33	TELETYPE\*R Model 33
37	TELETYPE Model 37
43	TELETYPE Model 43
735	Texas Instruments TI735 (and TI725)
745	Texas Instruments TI745
dumb	terminals with no special features
I 2
dialup	a terminal on a phone line with no known characteristics
network	a terminal on a network connection with no known characteristics
E 2
4014	Tektronix 4014
vt52	Digital Equipment Corp. VT52
.fi
.PP
E 4
I 4
.Xr sh  1  ,
.Xr environ  7  ) .
.Pp
.Ds I
.Cw network
.Cl adm3a	Lear Seigler Adm-3a
.Cl 2621	Hewlett-Packard HP262? series terminals
.Cl hp	Hewlett-Packard HP264? series terminals
.Cl c100	Human Designed Systems Concept 100
.Cl h19	Heathkit H19
.Cl mime	Microterm mime in enhanced ACT IV mode
.Cl 735	Texas Instruments TI735 (and TI725)
.Cl 745	Texas Instruments TI745
.Cl dumb	terminals with no special features
.Cl dialup	a terminal on a phone line with no known characteristics
.Cl network	a terminal on a network connection with no known characteristics
.Cl xterm	a workstation running X
.Cl 4014	Tektronix 4014
.Cl vt100	Digital Equipment Corp. VT100
.Cw
.De
.Pp
E 4
The list goes on and on.
D 2
Consult /etc/termcap
(see
E 2
I 2
D 4
Consult /etc/termcap (see
E 2
.IR termcap (5))
E 4
I 4
Consult
.Pa /usr/share/misc/termcap (see
.Xr termcap  5  )
E 4
for an up-to-date and locally correct list.
D 4
.PP
E 4
I 4
.Pp
E 4
D 2
Commands whose behavior may depend on the terminal
either consult TERM in the environment,
or accept arguments of the form
E 2
I 2
Commands whose behavior may depend on the terminal either consult TERM in
the environment, or accept arguments of the form
E 2
D 4
.BR \-Tterm,
E 4
I 4
.Fl Tterm ,
E 4
where
D 4
.I term
E 4
I 4
.Nm term
E 4
is one of the names given above.
D 4
.SH SEE ALSO
D 2
stty(1), tabs(1), plot(1),
sh(1), environ(5)
ex(1), clear(1), more(1), ul(1), tset(1),
termcap(5), termlib(3), ttytype(5)
E 2
I 2
stty(1),
tabs(1),
plot(1G),
sh(1),
environ(7)
ex(1),
clear(1),
more(1),
ul(1),
tset(1),
termcap(5),
termcap(3X),
ttytype(5)
E 2
.br
troff(1) for
.I nroff
.SH BUGS
E 4
I 4
.Sh SEE ALSO
.Xr stty 1 ,
.Xr tabs 1 ,
.Xr plot 1
.Xr sh 1 ,
.Xr environ 7
.Xr ex 1 ,
.Xr clear 1 ,
.Xr more 1 ,
.Xr ul 1 ,
.Xr tset 1 ,
.Xr termcap 5 ,
.Xr termcap 3 ,
.Xr ttys 5
.Xr troff 1
.Sh BUGS
E 4
D 2
The programs that ought to adhere to this nomenclature
do so only fitfully.
E 2
I 2
The programs that ought to adhere to this nomenclature do so only fitfully.
I 4
.Sh HISTORY
.Nm Term
appeared in Version 32 AT&T UNIX.
E 4
E 2
E 1
