h08426
s 00005/00004/00011
d D 5.2 89/07/05 10:42:05 mckusick 2 1
c update for process groups and vnodes
e
s 00015/00000/00000
d D 5.1 88/03/30 15:58:46 bostic 1 0
c date and time created 88/03/30 15:58:46 by bostic
e
u
U
t
T
I 1
./"link"16t"rlink"16t"next"16t"prev"n4Xn
+/"addr"16t"upri"8t"pri"8t"cpu"8t"stat"8t"time"nX5b
+/"nice"8t"slp"8t"cursig"16t"sig"n3b16tX
+/"mask"16t"ignore"16t"catch"n3X
D 2
+/"flag"16t"uid"8t"pgrp"8t"pid"8t"ppid"nX4d
+/"xstat"16t"ru"16t"poip"8t"szpt"8t"tsize"nx2+16tX2xX
E 2
I 2
+/"flag"16t"uid"8t"pid"8t"ppid"nX3d
+/"xstat"16t"ru"16t"poip"8t"szpt"8t"tsize"nx16tX2xX
E 2
+/"dsize"16t"ssize"16t"rssize"16t"maxrss"n4X
+/"swrss"16t"swaddr"16t"wchan"16t"textp"n4X
+/"p0br"16t"xlink"16t"ticks"n2Xd2+
D 2
+/"%cpu"16t" "16t"ndx"8t"idhash"8t"pptr"nf16t2xX
E 2
I 2
+/"%cpu"16t"ndx"8t"idhash"8t"pptr"nX2xX
E 2
+/"cptr"16t"osptr"16t"ysptr"n3X
I 2
+/"pgrp"16t"pgrpnxt"n2X
E 2
+/"real itimer"n4D
D 2
+/"quota"16tX
E 2
I 2
+/"quota"16t"traceflag"n2X
E 2
+/"ckey"16t"dkey"n2Dn
+,<9-1$<proc
E 1
