h26019
s 00002/00002/00091
d D 8.1 93/06/06 15:50:06 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00019/00019/00074
d D 5.6 91/07/27 16:24:19 cael 7 6
c mdoc version three
e
s 00004/00005/00089
d D 5.5 91/06/27 17:22:16 bostic 6 5
c add POSIX/IEEE contribution notice
e
s 00003/00001/00091
d D 5.4 91/03/14 00:24:31 cael 5 3
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00092
d R 5.4 91/03/13 20:36:26 cael 4 3
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00002/00001/00090
d D 5.3 90/07/24 22:49:57 cael 3 2
c .Xr botch fix
e
s 00044/00058/00048
d D 5.2 90/06/11 05:58:22 cael 2 1
c converted man page
e
s 00106/00000/00000
d D 5.1 89/12/31 16:42:48 bostic 1 0
c date and time created 89/12/31 16:42:48 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1989 The Regents of the University of California.
E 2
I 2
D 8
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 2
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
I 2
.\"
I 3
D 6
.\"
E 6
E 3
E 2
.\" This code is derived from software contributed to Berkeley by
D 3
.\" Adam S. Moskowitz of Menlo Consulting.
E 3
I 3
D 6
.\" Adam S. Moskowitz.
E 6
I 6
.\" Adam S. Moskowitz and the Institute of Electrical and Electronics
.\" Engineers, Inc.
E 6
E 3
.\"
D 2
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 2
I 2
D 6
.\" %sccs.include.redist.man%
E 6
I 6
.\" %sccs.include.redist.roff%
E 6
E 2
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
D 6
.\"     %W% (Berkeley) %G%
E 6
I 6
.\"	%W% (Berkeley) %G%
E 6
E 2
.\"
I 5
D 6
.Vx
E 6
D 7
.Vx
E 7
E 5
D 2
.TH PASTE 1 "%Q%"
.UC 7
.SH NAME
paste - merge corresponding or subsequent lines of files
.SH SYNOPSIS
.ft B
.nf
paste [-s] [-d list] file ...
.fi
.ft R
.SH DESCRIPTION
E 2
I 2
.Dd %Q%
.Dt PASTE 1
D 5
.Os BSD 4.4
E 5
I 5
.Os
E 5
.Sh NAME
.Nm paste
.Nd merge corresponding or subsequent lines of files
.Sh SYNOPSIS
.Nm paste
.Op Fl s
.Op Fl d Ar list
.Ar file ...
.Sh DESCRIPTION
E 2
The
D 2
.I paste
E 2
I 2
.Nm paste
E 2
utility concatenates the corresponding lines of the given input files,
replacing all but the last file's newline characters with a single tab
character, and writes the resulting lines to standard output.
If end-of-file is reached on an input file while other input files
still contain data, the file is treated as if it were an endless source
of empty lines.
D 2
.PP
E 2
I 2
.Pp
E 2
The options are as follows:
D 2
.TP
-d list
E 2
I 2
D 7
.Tw Fl
.Tp Cx Fl d 
.Ar list
.Cx
E 7
I 7
.Bl -tag -width Fl
.It Fl d  Ar list 
E 7
E 2
Use one or more of the provided characters to replace the newline
characters instead of the default tab.
The characters in
D 2
.I list
E 2
I 2
.Ar list
E 2
are used circularly, i.e., when
D 2
.I list
E 2
I 2
.Ar list
E 2
is exhausted the first character from
D 2
.I list
E 2
I 2
.Ar list
E 2
is reused.
This continues until a line from the last input file (in default operation)
or the last line in each file (using the -s option) is displayed, at which
time
D 2
.I paste
E 2
I 2
.Nm paste
E 2
begins selecting characters from the beginning of
D 2
.I list
E 2
I 2
.Ar list
E 2
again.
D 2
.PP
.RS
E 2
I 2
.Pp
E 2
The following special characters can also be used in list:
D 2
.TP
\en
E 2
I 2
D 7
.Tw Ds
.Tp Li \en
E 7
I 7
.Pp
.Bl -tag -width flag -compact
.It Li \en
E 7
E 2
newline character
D 7
.br
D 2
.ns
.TP
\et
E 2
I 2
.Tp Li \et
E 7
I 7
.It Li \et
E 7
E 2
tab character
D 7
.br
D 2
.ns
.TP
\e\e
E 2
I 2
.Tp Li \e\e
E 7
I 7
.It Li \e\e
E 7
E 2
backslash character
D 7
.br
D 2
.ns
.TP
\e0
E 2
I 2
.Tp Li \e0
E 7
I 7
.It Li \e0
E 7
E 2
Empty string (not a null character).
I 7
.El
E 7
D 2
.PP
E 2
I 2
.Pp
E 2
Any other character preceded by a backslash is equivalent to the
character itself.
D 2
.RE
.TP
-s
E 2
I 2
D 7
.Tp
.Tp Fl s
E 7
I 7
.It Fl s
E 7
E 2
Concatenate all of the lines of each separate input file in command line
order.
The newline character of every line except the last line in each input
file is replaced with the tab character, unless otherwise specified by
the -d option.
D 2
.PP
E 2
I 2
D 7
.Tp
E 7
I 7
.El
E 7
.Pp
E 2
D 7
If ``-'' is specified for one or more of the input files, the standard
E 7
I 7
If
.Ql Fl
is specified for one or more of the input files, the standard
E 7
input is used; standard input is read one line at a time, circularly,
D 7
for each instance of ``-''.
E 7
I 7
for each instance of
.Ql Fl .
E 7
D 2
.PP
E 2
I 2
.Pp
E 2
The
D 2
.I paste
E 2
I 2
.Nm paste
E 2
utility exits 0 on success, and >0 if an error occurs.
D 2
.SH ENVIRONMENT
.SH "SEE ALSO"
cut(1)
.SH STANDARDS
E 2
I 2
.Sh SEE ALSO
.Xr cut 1
.Sh STANDARDS
E 2
The
D 2
.I paste
E 2
I 2
.Nm paste
E 2
D 7
function is expected to be POSIX 1003.2 compatible.
E 7
I 7
utility is expected to be
.St -p1003.2
compatible.
E 7
E 1
