.TH PEOPLEDBM 1 "6/6/87"
.SH NAME
peopledbm \- Create dbm index for a private user name database
.SH SYNOPIS
.B peopledbm
[
.B \-f
file ]
.SH DESCRIPTION
The programs defined in the
.I Peopledbm
is used to create a token index in a dbm file pair for use with
the programs defined in the
.IR people (1)
command.
.LP
The source datafile is usually stored in a file `.people' on the users home
directory.
The
.B \-f
switch can be used to access other databases, alternatively
another location may be selected by supplying an environment variable
.IP
PEOPLE=
.LP
where the value of the variable gives the name of the file
containing the people database.
This stem is also used to generate the dbm files, say: ~/.people.dir
and ~/.people.pag.
.LP
The basic idea of this program is to create dbm key/content pairs
(containing standard UNIX strings) where the key is a token
(see
.IR people (1))
and the content is a comma separated list of decimal numbers
each giving the offset on the file where the start of the record
containing the token is to be found.
The access programs then use this information to reduce searching
of the first token to only the records which are found in this database.
This can cause a considerable speedup in searching operations.
The access programs all fail safe, and will work properly without these
files, they also ignore the dbm database if it seems to be out of date.
.SH "SEE ALSO"
people(1), peoplesort(1)
.SH BUGS
The people command and it's links will print:
.IP
Run peopledbm to update your dbm index files
.LP
if the change time of the source database is less than that of the
dbm data pair.
The dbm files are ignored in this case.
.SH AUTHOR
Peter Collinson, UKC. From an idea from David Tilbrook.
