h42491
s 00002/00002/00099
d D 8.1 93/06/04 18:50:12 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00072/00069/00029
d D 6.6 91/04/25 12:53:19 cael 8 7
c mdoc version three/bsd copyright
e
s 00001/00001/00097
d D 6.5 87/11/17 09:42:42 bostic 7 6
c typo
e
s 00010/00002/00088
d D 6.4 86/05/22 20:52:49 karels 6 5
c update
e
s 00003/00004/00087
d D 6.3 86/05/19 19:27:41 karels 5 4
c typos
e
s 00001/00001/00090
d D 6.2 86/04/20 05:17:23 lepreau 4 3
c typo
e
s 00018/00022/00073
d D 6.1 85/04/27 13:28:03 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00047/00017/00048
d D 5.1 85/04/27 13:27:42 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00065/00000/00000
d D 4.1 85/04/27 13:27:25 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 8
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 8
I 8
D 9
.\" Copyright (c) 1980, 1991 Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 8
.\"
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
.\"
D 2
.TH GETTY 8 "4/1/81"
E 2
I 2
D 3
.TH GETTY 8  "18 July 1983"
E 3
I 3
D 8
.TH GETTY 8  "%Q%"
E 3
E 2
.UC 4
.SH NAME
getty  \- set terminal mode
.SH SYNOPSIS
.B /etc/getty
D 2
[ char ]
E 2
I 2
D 3
[ type ]
E 3
I 3
D 5
[ type ] [ tty ]
E 5
I 5
[ type [ tty ] ]
E 5
E 3
E 2
.SH DESCRIPTION
.I Getty
D 3
is invoked by
E 3
I 3
is usually invoked by
E 3
.IR  init (8)
E 8
I 8
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt GETTY 8
.Os BSD 4
.Sh NAME
.Nm getty
.Nd set terminal mode
.Sh SYNOPSIS
.Nm getty
.Oo 
.Ar type
.Op Ar tty
.Oc
.Sh DESCRIPTION
The
.Nm getty
program
is called by
.Xr init 8
E 8
D 3
immediately after a terminal is opened,
following the making of a connection.
While reading the name
E 3
I 3
D 5
to intialize the tty line, read a login name, and invoke
E 5
I 5
to open and initialize the tty line, read a login name, and invoke
E 5
D 8
.IR login (1).
E 3
.I getty
attempts to adapt the system to the speed and type of terminal
being used.
.PP
E 8
I 8
.Xr login 1 .
.Pp
E 8
D 3
.I Init
calls
E 3
I 3
The argument
D 8
.I tty
D 6
is the special device file in /dev to open for the terminal (e.g., 'ttyh0').
E 6
I 6
is the special device file in /dev to open for the terminal (e.g., ``ttyh0'').
E 8
I 8
.Ar tty
is the special device file in
.Pa /dev
to open for the terminal (for example, ``ttyh0'').
E 8
E 6
If there is no argument or the argument is
D 6
"\-", the tty line is assumed to be open as file descriptor 0.
E 6
I 6
D 8
``\-'', the tty line is assumed to be open as file descriptor 0.
E 6
.PP
E 8
I 8
.Ql Fl ,
the tty line is assumed to be open as file descriptor 0.
.Pp
E 8
The
D 8
.I type
E 8
I 8
.Ar type
E 8
argument can be used to make
E 3
D 8
.I getty
E 8
I 8
.Nm getty
E 8
D 3
with an argument specified by the
.I ttys
file entry for the terminal line.
D 2
Arguments other than `0' can be used to make
E 2
I 2
The argument can be used to make
E 2
.I getty
treat the line specially.
E 3
I 3
treat the terminal line specially.
E 3
D 2
Normally, it
sets the speed of the interface to 300 baud,
specifies that raw mode is to be used (break on every character),
that echo is to be suppressed, and either parity
allowed.
It types a banner identifying the system (from
/usr/include/ident.h and the `login:' message.
E 2
I 2
This argument is used as an index into the
D 8
.IR gettytab (5)
E 8
I 8
.Nm gettytab 5
E 8
database, to determine the characteristics of the line.
If there is no argument, or there is no such table, the
D 8
.B default
E 8
I 8
.Em default
E 8
table is used.
If there is no
D 8
.B /etc/gettytab
E 8
I 8
.Pa /etc/gettytab
E 8
a set of system defaults is used.
If indicated by the table located,
D 8
.I getty
E 8
I 8
.Nm getty
E 8
will clear the terminal screen,
print a banner heading,
and prompt for a login name.
D 7
Usually either the banner of the login prompt will include
E 7
I 7
Usually either the banner or the login prompt will include
E 7
the system hostname.
E 2
D 8
Then the user's name is read, a character at a time.
If a null character is received, it is assumed to be the result
of the user pushing the `break' (`interrupt') key.
D 2
The speed is then
changed to 1200 baud and the `login:' is typed again;
a second `break' changes the speed to 150 baud and the `login:'
is typed again.  Successive `break' characters cycle through the
speeds 300, 1200, and 150 baud.
E 2
I 2
The speed is usually then
changed and the `login:' is typed again;
a second `break' changes the speed again and the `login:'
is typed once more.
Successive `break' characters cycle through the
D 4
some standard set of speeds.
E 4
I 4
same standard set of speeds.
E 4
E 2
.PP
The user's name is terminated by a new-line or
carriage-return character.
The latter results in the system being set to
treat carriage returns appropriately (see
D 2
.IR  stty (2)).
E 2
I 2
.IR  tty (4)).
E 2
.PP
The user's name is scanned to see if
it contains any lower-case alphabetic characters; if not,
and if the name is nonempty, the
system is told to map any future upper-case characters
into the corresponding lower-case characters.
.PP
D 3
Finally, login is called with the user's name as argument.
E 3
I 3
Finally,
.I login
is called with the user's name as an argument.
E 3
I 2
.PP
E 8
I 8
.Pp
E 8
Most of the default actions of
D 8
.I getty
E 8
I 8
.Nm getty
E 8
can be circumvented, or modified, by a suitable
D 8
.I gettytab
E 8
I 8
.Nm gettytab
E 8
table.
D 8
.PP
.I Getty
E 8
I 8
.Pp
The
.Nm getty
program
E 8
can be set to timeout after some interval,
which will cause dial up lines to hang up
if the login name is not entered reasonably quickly.
I 6
D 8
.SH DIAGNOSTICS
\fIttyxx\fR\|\fB: No such device or address\fR.
\fIttyxx\fR\|\fB: No such file or address\fR.
E 8
I 8
.Sh DIAGNOSTICS
.Bl -diag
.It "ttyxx: No such device or address."
.It "ttyxx: No such file or address."
E 8
A terminal which is turned
D 8
on in the \fIttys\fR file cannot be opened, likely because the requisite
E 8
I 8
on in the
.Xr ttys
file cannot be opened, likely because the requisite
E 8
lines are either not configured into the system, the associated device
was not attached during boot-time system configuration,
D 8
or the special file in /dev does not exist.
E 6
.SH FILES
/etc/gettytab
E 2
.SH "SEE ALSO"
D 2
init(8), login(1), stty(2), ttys(5)
E 2
I 2
D 5
gettytab(5), init(8), login(1), ioctl(2), tty(4), ttys(5).
E 2
.SH BUGS
E 5
I 5
gettytab(5), init(8), login(1), ioctl(2), tty(4), ttys(5)
E 8
I 8
or the special file in
.Pa /dev
does not exist.
.El
.Sh FILES
.Bl -tag -width /etc/gettytab -compact
.It Pa /etc/gettytab
.El
.Sh SEE ALSO
.Xr gettytab 5 ,
.Xr init 8 ,
.Xr login 1 ,
.Xr ioctl 2 ,
.Xr tty 4 ,
.Xr ttys 5
.Sh HISTORY
A
.Nm getty
program appeared in
.At v6 .
E 8
E 5
I 2
D 3
Currently, the format of
.B /etc/ttys
limits the permitted table names to a single character,
this should be expanded.
.PP
.B /etc/ttys
should be replaced completely.
E 3
E 2
E 1
