h28413
s 00001/00000/00109
d D 8.4 94/06/01 21:01:39 ah 9 8
c page breaks for 4.4BSD manuals
e
s 00001/00001/00108
d D 8.3 94/05/06 17:40:34 mckusick 8 7
c get the right section
e
s 00008/00008/00101
d D 8.2 94/01/12 17:34:28 mckusick 7 5
c copyediting by Usenix
e
s 00001/00001/00108
d R 5.2.1.1 94/01/05 17:24:51 bostic 6 4
c typo
e
s 00002/00002/00107
d D 8.1 93/06/09 19:23:57 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00002/00109
d D 5.2 93/06/09 19:23:54 bostic 4 2
c fixed the under development line
e
s 00002/00002/00109
d R 8.1 93/06/06 13:55:44 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00000/00111
d D 5.1 91/05/10 13:26:14 cael 2 1
c change SID
e
s 00111/00000/00000
d D 1.1 91/05/10 13:17:08 cael 1 0
c date and time created 91/05/10 13:17:08 by cael
e
u
U
t
T
I 1
D 5
.\" Copyright 1991 The Regents of the University of California.
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" %sccs.include.redist.roff%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
D 8
.Dt CRONTAB 8
E 8
I 8
.Dt CRONTAB 5
E 8
.Os
.Sh NAME
.Nm crontab
.Nd chronological services schedule file
.Sh SYNOPSIS
.Nm crontab
.Sh DESCRIPTION
The
.Nm crontab
D 7
file contain the schedules used by the
E 7
I 7
file contains the schedules used by the
E 7
.Xr cron 8
daemon.
Each line in the schedule gives a time of execution
and the command to be executed.
.Pp
A line consists of
two fields giving the time,
three fields giving the day,
a user name field,
and lastly the command to be
executed.
The first five fields are space
or tab
separated and may
consist of a number,
a comma separated list of numbers,
or an asterisk meaning any or all possible values.
The last field (the command field) may contain spaces.
A field containing two hyphen separated numbers is treated as
an inclusive range.
.Pp
The fields are:
.Bl -enum -offset indent
.It
The minute of the hour, a number from 0 to 59.
.It
The hour, a number from 0 to 23.
.It
The day in terms of the month, a number from 1 to 31.
.It
D 7
The day in terms of the year, a number from 1 to 12.
E 7
I 7
The month in terms of the year, a number from 1 to 12.
E 7
.It
The day in terms of the week, a number from 1 to 7.
Monday is considered day one, Sunday is day seven.
.It
The name of a user: the command will be run with the
user's uid and permissions.
.It
The command to execute.  This field may be terminated with a
D 7
newline of the
E 7
I 7
newline or the
E 7
.Ql %
character.
.El
.Pp
An optional file
.Nm crontab.local
D 7
may be created and used for addtional scheduling.
E 7
I 7
may be created and used for additional scheduling.
E 7
.Sh EXAMPLES
In the example below,
the first field indicates the command should be executed at the hour,
a quarter past the hour, on the half hour and at a quarter to the hour.
The next four fields indicate the command should be run every hour,
every day. The sixth field indicates the command is to be run with
root privileges.
.Bd -literal -offset indent
0,15,30,45 * * * *      root /usr/libexec/atrun
.Ed
.Pp
D 7
In this next exmaple,
the first field indicates this command should be exectuted on the half hour.
The second field constrains the hour to 3 A.M. The third and second
fields indicate any day of the month and any day of the year, but are
E 7
I 7
In this next example,
the first field indicates this command should be executed on the half hour.
The second field constrains the hour to 3 A.M. The third and fourth
fields indicate any day of the month and any month of the year, but are
E 7
constrained by the fifth field to the sixth day of the week (Saturday).
The command is to be executed with root privileges. The example shown here
has been folded (spread across two lines) to make it readable.
It must not be folded in the the
.Nm crontab
file.
.Bd -literal -offset indent
30 3 * * 6      root    /bin/sh /etc/weekly 2>&1 | tee
	/var/log/weekly.out | mail -s "weekly output" root
.Ed
.Sh SEE ALSO
.Xr cron 8
.Xr rc 8
I 9
.ne 1i
E 9
.Sh FILES
.Bl -tag -width /etc/crontab.local -compact
.It Pa /etc/crontab
General system tasks.
.It Pa /etc/crontab.local
Optional local tasks.
.It Pa /etc/rc
System initialization script (normally,
.Nm cron
is executed from this script.)
.Sh HISTORY
A
.Nm crontab
file appeared in
.At v6 .
D 4
This manual page is
.Ud .
E 4
E 1
