h02203
s 00002/00002/00055
d D 8.3 94/04/01 06:46:29 bostic 10 9
c clarificatoin
e
s 00010/00001/00047
d D 8.2 94/03/30 14:19:08 bostic 9 8
c change tsort to not look for the longest cycle (add a -l flag for
c users that actually want the longest cycle).  This is backward compatible
c with historic tsort, it didn't find the longest cycle either.
c This provides a major speedup for some tsort runs.
c From: christos@deshaw.com (Christos Zoulas)
e
s 00002/00002/00046
d D 8.1 93/06/09 22:54:18 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00030/00019/00018
d D 6.3 91/04/23 16:33:44 cael 7 4
c mdoc version three
e
s 00000/00000/00037
d R 6.4 90/06/24 19:21:13 cael 6 5
c converted man page
e
s 00002/00002/00035
d R 6.3 90/06/24 19:16:45 cael 5 4
c converted man page
e
s 00029/00023/00008
d D 6.2 90/05/22 11:32:18 bostic 4 3
c AT&T free version, from Michael Rendell (michael@stretch.cs.mun.ca)
e
s 00001/00001/00030
d D 6.1 85/04/29 18:06:48 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00030
d D 5.1 85/04/29 18:06:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00031/00000/00000
d D 4.1 85/04/29 18:06:22 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 8
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 8
I 8
D 9
.\" Copyright (c) 1990, 1993
E 9
I 9
.\" Copyright (c) 1990, 1993, 1994
E 9
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
.\" This manual is derived from one contributed to Berkeley by
.\" Michael Rendell of Memorial University of Newfoundland.
I 9
.\"
E 9
I 7
.\" %sccs.include.redist.roff%
E 7
.\"
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
E 4
I 1
D 7
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH TSORT 1 
E 2
I 2
D 3
.TH TSORT 1  "18 January 1983"
E 3
I 3
D 4
.TH TSORT 1 "%Q%"
E 4
I 4
.TH tsort 1 "%Q%"
E 4
E 3
E 2
.AT 3
.SH NAME
D 4
tsort \- topological sort
E 4
I 4
tsort \- topological sort of a directed graph
E 4
.SH SYNOPSIS
D 4
.B tsort
[ file ]
E 4
I 4
.nf
.ft B
tsort [ file ]
.ft R
.fi
E 4
.SH DESCRIPTION
.I Tsort
E 7
I 7
.Dd %Q%
.Dt TSORT 1
.Os
.Sh NAME
.Nm tsort
.Nd topological sort of a directed graph
.Sh SYNOPSIS
.Nm tsort
I 9
.Op Fl l
E 9
.Op Ar file
.Sh DESCRIPTION
.Nm Tsort
E 7
D 4
produces on the standard output a totally ordered list of items
consistent with a partial ordering of items
mentioned in the input
.IR file .
If no
.I file
is specified, the standard input is understood.
E 4
I 4
takes a list of pairs of node names representing directed arcs in
a graph and prints the nodes in topological order on standard output.
D 7
Input is taken from the named file, or from standard input if no file
E 7
I 7
Input is taken from the named
.Ar file ,
or from standard input if no file
E 7
is given.
E 4
D 7
.PP
E 7
I 7
.Pp
E 7
D 4
The input consists of pairs of items (nonempty strings)
separated by blanks.
Pairs of different items indicate ordering.
Pairs of identical items indicate presence, but not ordering.
.SH "SEE ALSO"
lorder(1)
.SH DIAGNOSTICS
Odd data: there is an odd number of fields in the input file.
.SH BUGS
Uses a quadratic algorithm;
not worth fixing for the typical use of ordering
a library archive file.
E 4
I 4
D 10
Node names in the input are separated by white space and there must be an
even number of nodes.
E 10
I 10
Node names in the input are separated by white space and there must
be an even number of node pairs.
E 10
D 7
.PP
E 7
I 7
.Pp
E 7
Presence of a node in a graph can be represented by an arc from the node
to itself.
This is useful when a node is not connected to any other nodes.
D 7
.PP
E 7
I 7
.Pp
E 7
If the graph contains a cycle (and therefore cannot be properly sorted),
one of the arcs in the cycle is ignored and the sort continues.
Cycles are reported on standard error.
I 9
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl l 
Search for and display the longest cycle.
Can take a very long time.
.El
E 9
I 7
.Sh SEE ALSO
.Xr ar 1
.Sh HISTORY
A
.Nm
command appeared in
.At v7 .
This
.Nm tsort
command and manual page are derived from sources contributed to Berkeley by
Michael Rendell of Memorial University of Newfoundland.
E 7
E 4
E 1
