h23013
s 00000/00000/00249
d D 8.1 93/08/14 11:05:21 mckusick 8 7
c 4.4BSD snapshot (revision 8.1)
e
s 00018/00018/00231
d D 6.4 93/08/14 09:19:33 elan 7 5
c add spacing between commands and arguments
e
s 00000/00000/00249
d R 8.1 93/06/08 13:07:54 bostic 6 5
c 4.4BSD snapshot (revision 8.1)
e
s 00002/00002/00247
d D 6.3 93/06/05 17:11:16 bostic 5 4
c new doc.mk; document numbering changes for 4.4BSD
e
s 00002/00000/00247
d D 6.2 91/04/17 12:49:47 bostic 4 3
c new copyright; att/bsd/shared
e
s 00012/00007/00235
d D 6.1 86/04/17 13:04:05 mckusick 3 2
c Mark Seiden edits for 4.3BSD release
e
s 00000/00000/00242
d D 5.1 86/04/17 13:03:53 mckusick 2 1
c document distributed with 4.2BSD
e
s 00242/00000/00000
d D 4.1 86/04/17 13:03:42 mckusick 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 4
.\" %sccs.include.proprietary.roff%
.\"
E 4
I 1
.\"	%W% (Berkeley) %G%
.\"
.if \n(mo=1 .ds mo January
.if \n(mo=2 .ds mo February
.if \n(mo=3 .ds mo March
.if \n(mo=4 .ds mo April
.if \n(mo=5 .ds mo May
.if \n(mo=6 .ds mo June
.if \n(mo=7 .ds mo July
.if \n(mo=8 .ds mo August
.if \n(mo=9 .ds mo September
.if \n(mo=10 .ds mo October
.if \n(mo=11 .ds mo November
.if \n(mo=12 .ds mo December
.if \n(dw=1 .ds dw Sunday
.if \n(dw=2 .ds dw Monday
.if \n(dw=3 .ds dw Tuesday
.if \n(dw=4 .ds dw Wednesday
.if \n(dw=5 .ds dw Thursday
.if \n(dw=6 .ds dw Friday
.if \n(dw=7 .ds dw Saturday
.\"
.bd S B 3
.ds NR "\s-1NROFF\s+1
.ds TR "\s-1TROFF\s+1
.ds Nr "N\s-2ROFF\s+2
.ds Tr "T\s-2ROFF\s+2
.nr PS 10
D 7
.hy14
E 7
I 7
.hy 14
E 7
.ds u \v'-0.3m'\s-2
.ds d \s0\v'0.3m'
.nr a .8i
.nr b 1.6i
.nr c 2.4i
.nr d 2.9i
.nr e 0.25i
.nr p 0 1
.nr s 0 1
.af p 1
.af s 1
.nr m -1i
.nr x 0 1
.nr y 0+\nmu
D 7
.ev1
E 7
I 7
.ev 1
E 7
.ps \n(PS-2
.vs \n(PS
D 7
.ll6.5i
E 7
I 7
.ll 6.5i
E 7
'in 0
.ev
.tr &.
.de xx
.sp 0.4
..
.de ht
D 3
.tl `\*(Nr/\*(Tr User's Manual```
.tl 'October 11, 1976'''\".tl 'Version \n(mo/\n(dy/\n(yr'''
E 3
I 3
D 5
.tl `\*(Nr/\*(Tr User's Manual``USD:24-%`
E 5
I 5
.tl `\*(Nr/\*(Tr User's Manual``USD:21-%`
E 5
.\" .tl 'updated to May 15, 1977'''\".tl 'Version \n(mo/\n(dy/\n(yr'''
E 3
..
I 3
.de he
D 5
.tl `USD:24-%``\*(Nr/\*(Tr User's Manual`
E 5
I 5
.tl `USD:21-%``\*(Nr/\*(Tr User's Manual`
E 5
.\" .tl 'updated to May 15, 1977'''\".tl 'Version \n(mo/\n(dy/\n(yr'''
..
E 3
.de hd
D 3
.tl '\(rn'''
.if \\n%>1 \{'sp |.33i
.ht
E 3
I 3
.\".tl '\(rn'''
.if \\n%>1 \{'sp |.30i
.if e .he
.if o .ht
E 3
.ps \\n(S2
.ps \\n(S1
.ft
D 3
'sp |1i\}
E 3
I 3
'sp |.9i\}
E 3
.nr x 0 1
.nr y 0+\\nmu
.ch fo \\nmu
.if \\n(dn .fz
.ns
.mx
.nr cl 0 1
.mk
..
.de fz
.fn
.nf
.fy
.fi
.ef
..
.de fx
.if \\nx .di fy
..
.de fo
.cx
.nr dn 0
.if \\nx .xf
.nr x 0 \"disable fx
.ie \\n(2C&(\\n+(cl<2) \{\
.po +3.4i
.rt
.nr y 0+\\nmu
.ch fo \\nmu
.if \\n(dn .fz
.ns \}
.el \{\
.po 26i/27u
.nr S1 \\n(.s
.ps
.nr S2 \\n(.s
.ps 10
'bp \}
..
.de 2C
.br
.mk
.nr 2C 1
.ll 3.1i
.ev 1
.ll 3.1i
.ev
..
.de 1C
.br
.nr 2C 0
.ll 6.5i
D 7
.ev1
E 7
I 7
.ev 1
E 7
.ll 6.5i
.ev
..
.de co
.de cx
.br
\fI(Continued next page.)\fP
.br
.rm cx
\\..
..
.de pp
'ps \\n(PS
D 7
.ftR
E 7
I 7
.ft R
E 7
D 3
'tl ''- % -''
E 3
I 3
.\"'tl ''- % -''
E 3
'bp
..
.wh 0 hd
.wh 12i fo
.wh \nmu fx
.ch fo \nmu
.de fn
.da FN
D 7
.ev1
E 7
I 7
.ev 1
E 7
.if \\n+x=1 .fs
.fi
D 7
.ti0
E 7
I 7
.ti 0
E 7
..
.de xf
D 7
.ev1
E 7
I 7
.ev 1
E 7
.nf
.FN
.rm FN
.di
.ev
..
.de fs
D 7
.ti0
E 7
I 7
.ti 0
E 7
\l'1i'
.br
..
.de ef
.br
.ev
.di
.nr y -\\n(dn
.if \\nx=1 .nr y -2p
.ch fo \\nyu
.if \\n(nl+\\n(.v-\\n(.p-\\ny .ch fo \\n(nlu+\\n(.vu
..
.wh -.6i pp
.de h1
.xx
.ne 5
.nf
.ta \\nau \\nbu \\ncu \\ndu +\\neu
.ft I
.bd I 3
Request	Initial	If No
Form	Value\\$2	Argument	Notes\\$1	Explanation
.bd I
.ft R
.ft
.fi
.in \\ndu
..
.de bt
D 7
.ftR
E 7
I 7
.ft R
E 7
.xx
.ne 1.1
D 7
.ti0
E 7
I 7
.ti 0
E 7
..
.de b1
.br
D 7
.ti0
E 7
I 7
.ti 0
E 7
..
.de pg
.ft R
.fi
D 7
.in0
E 7
I 7
.in 0
E 7
.xx
.ne 1.1
..
.de sc
.pg
\fI\\*H\\np.\\n+s.\|\\c
D 7
.ftR
E 7
I 7
.ft R
E 7
.ul
..
.de mh
.nr s 0
D 7
.in0
E 7
I 7
.in 0
E 7
.xx
.ne 2.5
.ft B
\\*H\\n+p.
..
.de x1
.xx
D 7
.in.5i
E 7
I 7
.in .5i
E 7
.nf
..
.de x2
.xx
D 7
.in0
E 7
I 7
.in 0
E 7
.fi
..
.de EM
.br
\&\c
'bp
D 7
.pl2i
E 7
I 7
.pl 2i
E 7
..
.em EM
.de TS
.sp
..
.de TE
.sp
.ce 0
.ft R
.ps \n(PS
.ta \\nau \\nbu \\ncu \\ndu +\\neu
..
E 1
