h14771
s 00002/00002/00061
d D 8.1 93/06/06 22:13:53 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00002/00062
d D 6.7 91/09/13 17:15:46 cael 8 7
c fix typo
e
s 00052/00045/00012
d D 6.6 91/03/16 18:11:07 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00001/00001/00056
d D 6.5 90/06/24 22:09:25 trent 6 5
c new pathnames
e
s 00002/00002/00055
d D 6.4 88/10/24 12:00:00 bostic 5 4
c remove refs to [18]C, add copyright if needed
e
s 00014/00014/00043
d D 6.3 86/04/24 22:21:52 mckusick 4 3
c update from rfg
e
s 00001/00001/00056
d D 6.2 85/06/23 15:59:20 bloom 3 2
c correct spool directory
e
s 00001/00001/00056
d D 6.1 85/04/27 16:01:04 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00057/00000/00000
d D 5.1 85/04/27 16:00:54 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 7
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 9
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 7
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\" %sccs.include.redist.man%
E 7
.\"
D 2
.TH UUCLEAN 8C "18 January 1983"
E 2
I 2
D 5
.TH UUCLEAN 8C "%Q%"
E 5
I 5
D 7
.TH UUCLEAN 8 "%Q%"
E 5
E 2
.UC 5
.SH NAME
uuclean \- uucp spool directory clean-up
.SH SYNOPSIS
D 4
.B uuclean
[ option ] ...
E 4
I 4
.B /usr/lib/uucp/uuclean
[
.B -m
] [
.BI -n time
] [
.BI -p pre
]
E 4
.SH DESCRIPTION
.I Uuclean
E 7
I 7
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt UUCLEAN 8
.Os BSD 4.2
.Sh NAME
.Nm uuclean
D 8
.Nd uucp spool directory clean
.Ndup
E 8
I 8
.Nd uucp spool directory clean-up
E 8
.Sh SYNOPSIS
.Nm uuclean
.Op Fl d Ns Ar subdirectory
.Op Fl m
.Op Fl n Ns Ar time
.Op Fl p Ns Ar pre
.Sh DESCRIPTION
.Xr Uuclean
E 7
will scan the spool directory for files with the
specified prefix and delete all those which are
older than the specified number of hours.
D 7
.PP
E 7
I 7
.Pp
E 7
The following options are available.
D 7
.TP 8
.BI \-p pre
Scan for files with
.I pre
as the file prefix.
Up to 10
.B \-p
arguments may be specified.
D 4
A
.B \-p
without any
.I pre
following will cause all files older than the
specified time to be deleted.
E 4
.TP
.BI \-n time
E 7
I 7
.Bl -tag -width Ds
.It Fl d Ns Ar subdirectory
Only the specified subdirectory will be cleaned.
.It Fl m
Send mail to the owner of the file
when it is deleted.
.It Fl n Ns Ar time
E 7
Files whose age is more than
D 7
.I time
E 7
I 7
.Ar time
E 7
hours will be deleted if the prefix
test is satisfied.
(default time is 72 hours)
D 7
.TP 8
.B \-m
Send mail to the owner of the file
when it is deleted.
I 4
.TP
.BI \-d subdirectory
Only the specified subdirectory will be cleaned.
E 4
.PP
E 7
I 7
.It Fl p Ns Ar pre
Scan for files with
.Ar pre
as the file prefix.
Up to 10
.Fl p
arguments may be specified.
.El
.Pp
E 7
D 4
This program will typically be started by
E 4
I 4
This program will typically be run daily by
E 4
D 7
.IR cron (8).
.SH FILES
.TP 22
D 4
/usr/lib/uucp
directory with commands used by uuclean internally
.TP
E 4
D 3
/usr/lib/uucp/spool
E 3
I 3
D 6
/usr/spool/uucp
E 6
I 6
/var/spool/uucp
E 7
I 7
.Xr cron 8 .
.Sh FILES
.Bl -tag -width /var/spool/uucp
.It Pa /var/spool/uucp
E 7
E 6
E 3
D 4
spool directory
E 4
I 4
Spool directory
E 4
D 7
.SH SEE ALSO
D 4
uucp(1C), uux(1C)
E 4
I 4
D 5
uucp(1C), uux(1C), uucico(8C)
E 5
I 5
uucp(1), uux(1), uucico(8)
E 7
I 7
.El
.Sh SEE ALSO
.Xr uucp 1 ,
.Xr uux 1 ,
.Xr uucico 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 7
E 5
E 4
E 1
