h59697
s 00044/00048/00009
d D 8.2 94/04/19 23:27:34 mckusick 6 5
c rewrite to decontaminate
e
s 00002/00002/00055
d D 8.1 93/06/05 10:50:21 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00002/00054
d D 6.2 91/05/04 15:49:45 cael 4 3
c proprietary copyright
e
s 00001/00001/00055
d D 6.1 85/04/27 13:09:10 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00002/00054
d D 5.1 85/04/27 13:07:41 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00056/00000/00000
d D 4.1 85/04/27 13:07:24 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
D 4
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1980, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
D 6
.\"	%sccs.include.proprietary.roff%
E 6
I 6
.\"	%sccs.include.redist.man%
E 6
E 4
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH CLRI 8 "4/3/81"
E 2
I 2
D 3
.TH CLRI 8  "4 February 1983"
E 3
I 3
D 6
.TH CLRI 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
clri \- clear i-node
.SH SYNOPSIS
.B /etc/clri
filesystem i-number ...
.SH DESCRIPTION
.B N.B.:
.I Clri
E 6
I 6
.Dd %Q%
.Dt CLRI 8
.Os BSD 4
.Sh NAME
.Nm clri
.Nd clear an inode
.Sh SYNOPSIS
.Nm clri
.Ar special_device inode_number ...
.Sh DESCRIPTION
.Bf -symbolic
.Nm Clri
E 6
is obsoleted for normal file system repair work by
D 6
.IR fsck (8).
.PP
.I Clri
writes zeros on the i-nodes
with the decimal
.I i-numbers
on the
.I filesystem.
After
.I clri,
any blocks
in the affected file
will show up as `missing' in an
D 2
.IR icheck (1)
E 2
I 2
.IR icheck (8)
E 2
of the
.I filesystem.
.PP
Read and write permission is required on the specified
file system device.
The i-node becomes allocatable.
.PP
E 6
I 6
.Xr fsck 8 .
.Ef
.Pp
.Nm Clri
zeros out the inodes with the specified inode number(s)
on the filesystem residing on the given
.Ar special_device .
The
.Xr fsck 8
utility is usually run after
.Nm clri
to reclaim the zero'ed inode(s) and the
blocks previously claimed by those inode(s).
Both read and write permission are required on the specified
.Ar special_device .
.Pp
E 6
The primary purpose of this routine
is to remove a file which
D 6
for some reason appears in no
directory.
If it is used to zap an i-node
which does appear in a directory, care should be taken to track down
the entry and remove it.
Otherwise, when the i-node is reallocated to some new file,
the old entry will still point to that file.
At that point removing the old entry will destroy the new file.
The new entry will again point to an unallocated i-node,
so the whole cycle is likely to be repeated again and again.
.SH "SEE ALSO"
icheck(8)
.SH BUGS
If the file is open,
.I clri
is likely to be ineffective.
E 6
I 6
for some reason is not being properly handled by
.Xr fsck 8 .
Once removed,
it is anticipated that
.Xr fsck 8
will be able to clean up the resulting mess.
.Sh "SEE ALSO"
.Xr fsck 8 ,
.Xr fsdb 8 ,
.Xr icheck 8 ,
.Xr ncheck 8
.Sh BUGS
If the file is open, the work of
.Nm clri
will be lost when the inode is written back to disk from the inode cache.
E 6
E 1
