h48903
s 00002/00002/00041
d D 8.1 93/06/06 16:25:49 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00011/00006/00032
d D 6.6 91/05/26 11:07:13 bostic 10 9
c add -d option to strip debugging and empty symbols
e
s 00002/00002/00036
d D 6.5 91/05/09 17:01:40 cael 9 8
c delete references to 4.4
e
s 00032/00031/00006
d D 6.4 91/04/22 15:31:13 cael 8 5
c mdoc conversion
e
s 00031/00031/00006
d R 6.4 91/04/22 15:29:41 cael 7 5
c mdoc conversion
e
s 00004/00014/00023
d R 6.4 90/06/24 19:17:59 cael 6 5
c converted man page
e
s 00004/00000/00033
d D 6.3 89/12/09 13:55:07 bostic 5 4
c document exit values
e
s 00024/00019/00009
d D 6.2 89/12/09 13:51:38 bostic 4 3
c from scratch, remove any mention of temporary files
e
s 00001/00001/00027
d D 6.1 85/04/29 17:58:54 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00027
d D 5.1 85/04/29 17:58:47 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00028/00000/00000
d D 4.1 85/04/29 17:58:40 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 8
.\" Copyright (c) 1989 The Regents of the University of California.
E 8
I 8
D 11
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 8
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
.\"
D 8
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 8
I 8
D 9
.\" %sccs.include.redist.man%
E 9
I 9
.\" %sccs.include.redist.roff%
E 9
E 8
.\"
E 4
I 1
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 2
.TH STRIP 1 
E 2
I 2
D 3
.TH STRIP 1  "18 January 1983"
E 3
I 3
D 8
.TH STRIP 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
D 4
strip \- remove symbols and relocation bits
E 4
I 4
strip \- remove unnecessary information from executable files
E 4
.SH SYNOPSIS
D 4
.B strip
name ...
E 4
I 4
.ft B
strip file ...
.ft R
E 4
.SH DESCRIPTION
.I Strip
D 4
removes the symbol
table and relocation bits ordinarily attached to the output
of the assembler and loader.
This is useful to save space after a program has been
debugged.
.PP
The effect of
.I strip
is the same as use of the
.B \-s
option
of
.IR ld .
.SH FILES
/tmp/stm?	temporary file
E 4
I 4
removes the relocation information and symbol table used by
assemblers and loaders.
This save disk space by decreasing the size of the installed binaries.
It also significantly decreases the usefulness of debuggers.
I 5
.PP
.I Strip
E 8
I 8
.Dd %Q%
.Dt STRIP 1
D 9
.Os BSD 4.4
E 9
I 9
.Os
E 9
.Sh NAME
.Nm strip
.Nd remove unnecessary information from executable files
.Sh SYNOPSIS
.Nm strip
D 10
.Ar
E 10
I 10
.Op Fl d
.Ar file ...
E 10
.Sh DESCRIPTION
The
.Nm strip
utility
deletes the relocation information and symbol table used by
assemblers, loaders and debuggers.
This significantly
decreases the size of the installed binaries and saves disk space.
.Pp
I 10
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Delete only debugging and empty symbols.
.El
.Pp
E 10
.Nm Strip
E 8
D 10
exits 0 on success (or if the file had already been stripped), 1 if
an error occurred.
E 10
I 10
exits 0 on success and 1 if an error occurred.
E 10
E 5
E 4
D 8
.SH "SEE ALSO"
D 4
ld(1)
E 4
I 4
as(1), cc(1), install(1), ld(1)
E 8
I 8
.Sh SEE ALSO
D 10
.Xr as 1 ,
E 10
.Xr cc 1 ,
D 10
.Xr install 1 ,
.Xr ld 1
E 10
I 10
.Xr ld 1 ,
.Xr stab 5
E 10
.Sh HISTORY
A
.Nm
command appeared in
.At v6 .
E 8
E 4
E 1
