h26553
s 00002/00002/00117
d D 8.1 93/06/29 17:27:12 bostic 18 17
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00006/00006/00113
d D 6.14 93/06/29 17:26:00 mckusick 17 15
c typesetting nits
e
s 00002/00002/00117
d R 8.1 93/06/06 14:26:15 bostic 16 15
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00006/00117
d D 6.13 91/06/17 12:32:53 bostic 15 14
c minor cleanups
e
s 00001/00001/00122
d D 6.12 91/05/14 21:50:17 cael 14 13
c fix display (was -ragged needed to be -unfilled)
e
s 00026/00027/00097
d D 6.11 91/03/14 01:39:21 cael 13 12
c updated to -mdoc version 3
e
s 00001/00001/00123
d D 6.10 90/08/31 13:28:09 cael 12 11
c fix botched parenthetic expression
e
s 00002/00004/00122
d D 6.9 90/07/24 22:41:40 cael 11 10
c .Xr botch fix
e
s 00070/00068/00056
d D 6.8 90/06/11 05:53:38 cael 10 9
c converted man page
e
s 00007/00000/00117
d D 6.7 90/05/03 21:34:44 bostic 9 8
c document that dates are only matched if they occur first on the line
e
s 00001/00001/00116
d D 6.6 90/02/21 14:15:16 bostic 8 7
c not any space, just tabs; people used " 2/1" because it formatted
c with "10/1" so it broke things
e
s 00001/00001/00116
d D 6.5 89/12/11 11:07:36 bostic 7 6
c this date isn't ambiguous, make explanation clearer
e
s 00003/00000/00114
d D 6.4 89/11/27 14:11:12 bostic 6 5
c add calendar.computer
e
s 00018/00004/00096
d D 6.3 89/10/27 18:49:48 bostic 5 4
c add new default calendars
e
s 00086/00039/00014
d D 6.2 89/10/13 14:12:32 bostic 4 3
c redone from scratch as a C program to fix cpp security problem
e
s 00001/00001/00052
d D 6.1 85/04/29 20:00:21 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00011/00006/00042
d D 5.1 85/04/29 19:59:58 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00048/00000/00000
d D 4.1 85/04/29 19:59:34 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 10
.\" Copyright (c) 1989 The Regents of the University of California.
E 10
I 10
D 18
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 10
.\" All rights reserved.
E 18
I 18
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 18
.\"
D 10
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 10
I 10
.\" %sccs.include.redist.man%
E 10
.\"
E 4
I 1
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
.\"     %W% (Berkeley) %G%
E 10
.\"
D 2
.TH CALENDAR 1 4/1/81
E 2
I 2
D 3
.TH CALENDAR 1  "29 March 1982"
E 3
I 3
D 10
.TH CALENDAR 1 "%Q%"
E 3
E 2
D 4
.AT 3
E 4
I 4
.UC 7
E 4
.SH NAME
calendar \- reminder service
.SH SYNOPSIS
.B calendar
D 4
[ \- ]
E 4
I 4
[ \-a ]
E 4
.SH DESCRIPTION
.I Calendar 
D 4
consults the file `calendar' in the current directory
and prints out lines that contain today's or
tomorrow's date anywhere in the line.
Most reasonable month-day dates such as `Dec. 7,'
`december 7,' `12/7,' etc., are recognized, but not
`7 December' or `7/12'.
D 2
If you give just a date, i.e. ``1'', that day in any month will do.
E 2
I 2
If you give the month as ``*''
with a date, i.e. ``* 1'', that day in any month will do.
E 2
On weekends `tomorrow' extends through Monday.
E 4
I 4
reads the file ``calendar'' in the current directory and displays lines
that begin with either today's or tomorrow's date.
E 10
I 10
.Dd %Q%
D 13
.\"
E 13
.Dt CALENDAR 1
D 13
.Os BSD 4.4
E 13
I 13
.Os
E 13
.Sh NAME
.Nm calendar
.Nd reminder service
.Sh SYNOPSIS
.Nm calendar
D 13
.Op  \-a
E 13
I 13
.Op Fl a
E 13
.Sh DESCRIPTION
.Nm Calendar
D 17
checks the current directory for a file named named
E 17
I 17
checks the current directory for a file named
E 17
D 13
.Li calendar
E 13
I 13
.Pa calendar
E 13
and displays lines that begin with either today's date
or tomorrow's.
E 10
On Fridays, events on Friday through Monday are displayed.
E 4
D 10
.PP
E 10
I 10
.Pp
E 10
D 4
When 
an argument is present,
.I calendar
does its job for every user
who has a file `calendar' in his login directory
and sends him any positive results by
.IR mail (1).
Normally this is done daily in the wee hours under control of
.IR cron (8).
E 4
I 4
The following options are available:
D 10
.TP
\-a
E 10
I 10
D 13
.Tp Fl a
E 13
I 13
.Bl -tag -width Ds
.It Fl a
E 13
E 10
Process the ``calendar'' files of all users and mail the results
to them.
This requires super-user privileges.
E 4
I 2
D 10
.PP
E 10
I 10
D 13
.Tp
E 13
I 13
.El
E 13
.Pp
E 10
D 4
The file `calendar' is first run through the ``C'' preprocessor,
.IR /lib/cpp ,
to include any other calendar files
specified with the usual ``#include'' syntax.
Included calendars will usually be shared by all users,
maintained and documented by the local administration.
E 4
I 4
D 17
A month and day should begin lines.
E 17
I 17
Lines should begin with a month and day.
E 17
They may be entered in almost any format, either numeric or as character
strings.
A single asterisk (``*'') matches every month.
A day without a month matches that day of every week.
A month without a day matches the first of that month.
Two numbers default to the month followed by the day.
D 8
Lines with leading whitespace default to the last entered date, allowing
E 8
I 8
Lines with leading tabs default to the last entered date, allowing
E 8
multiple line specifications for a single date.
D 17
By convention, dates followed by an asterisk are not fixed, i.e. change
E 17
I 17
By convention, dates followed by an asterisk are not fixed, i.e., change
E 17
from year to year.
D 10
.PP
E 10
I 10
.Pp
E 10
The ``calendar'' file is preprocessed by
D 10
.IR cpp (1),
E 10
I 10
.Xr cpp 1 ,
E 10
allowing the inclusion of shared files such as company holidays or
meetings.
If the shared file is not referenced by a full pathname,
D 10
.I cpp
E 10
I 10
.Xr cpp 1
E 10
searches in the current (or home) directory first, and then in the
directory
D 10
.IR /usr/share/calendar .
E 10
I 10
.Pa /usr/share/calendar .
E 10
D 13
Empty lines and lines protected by the C commenting syntax (/* ... */)
E 13
I 13
Empty lines and lines protected by the C commenting syntax
.Pq Li /* ... */
E 13
are ignored.
D 10
.PP
E 10
I 10
.Pp
E 10
Some possible calendar entries:
D 10
.in +5
.sp
.nf
E 10
I 10
D 13
.Pp
.Ds I
E 13
I 13
D 14
.Bd -ragged -offset indent
E 14
I 14
.Bd -unfilled -offset indent
E 14
E 13
E 10
#include	<calendar.usholiday>
#include	<calendar.birthday>
D 10
.sp
E 10
I 10

E 10
D 7
6/15		... June 15 (ambiguous, default to month/day).
E 7
I 7
6/15		... June 15 (if ambiguous, will default to month/day).
E 7
D 13
Jun. 15	... June 15.
15 June	... June 15.
E 13
I 13
D 15
Jun. 15		... June 15.
15 June		... June 15.
E 15
I 15
D 17
Jun. 15	... June 15.
15 June	... June 15.
E 17
I 17
Jun. 15		... June 15.
15 June		... June 15.
E 17
E 15
E 13
Thursday	... Every Thursday.
June		... Every June 1st.
15 *		... 15th of every month.
D 10
.fi
.PP
E 4
E 2
.SH FILES
E 10
I 10
D 13
.De
.Pp
E 13
I 13
.Ed
E 13
.Sh FILES
E 10
D 4
calendar
.br
/usr/lib/calendar to figure out today's and tomorrow's dates
.br
/etc/passwd
.br
/tmp/cal*
.br
D 2
egrep, sed, mail subprocesses
E 2
I 2
/lib/cpp, egrep, sed, mail as subprocesses
E 4
I 4
The following default calendar files are provided:
D 10
.TP
calendar.birthday
Births and deaths of famous (and not-so-famous) people.
.TP
D 5
calendar.usholiday
U.S. holidays and Judeo-Christian holidays.
E 5
I 5
calendar.christian
E 10
I 10
D 13
.Dw calendar.christian
D 11
.Ds L
E 11
I 11
.Di L
E 11
.Dp Pa calendar.birthday
E 13
I 13
.Pp
.Bl -tag -width calendar.christian -compact
.It Pa calendar.birthday
E 13
D 12
Births  and  deaths  of  famous ( and  not- so- famous) people.
E 12
I 12
Births and deaths of famous (and not-so-famous) people.
E 12
D 13
.Dp Pa calendar.christian
E 13
I 13
.It Pa calendar.christian
E 13
E 10
Christian holidays.
E 5
This calendar should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year.
D 10
.TP
I 6
calendar.computer
E 10
I 10
D 13
.Dp Pa calendar.computer
E 13
I 13
.It Pa calendar.computer
E 13
E 10
Days of special significance to computer people.
D 10
.TP
E 6
I 5
calendar.history
Everything else, mostly U.S. historical events.
.TP
E 5
calendar.holiday
Other holidays, including the not-well-known, obscure, and
.B really
E 10
I 10
D 13
.Dp Pa calendar.history
E 13
I 13
.It Pa calendar.history
E 13
Everything  else,  mostly  U. S. historical events.
D 13
.Dp Pa calendar.holiday
E 13
I 13
.It Pa calendar.holiday
E 13
Other  holidays,  including  the  not-well-known,  obscure, and
.Em really
E 10
obscure.
D 10
.TP
D 5
calendar.history
Everything else, mostly U.S. historical events.
E 5
I 5
calendar.judaic
E 10
I 10
D 13
.Dp Pa calendar.judaic
E 13
I 13
.It Pa calendar.judaic
E 13
E 10
Jewish holidays.
This calendar should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year.
D 10
.TP
calendar.music
Musical events, births, and deaths.
Strongly oriented toward rock 'n' roll.
.TP
calendar.usholiday
E 10
I 10
D 13
.Dp Pa calendar.music
E 13
I 13
.It Pa calendar.music
E 13
Musical  events,  births, and deaths.
D 13
Strongly  oriented  toward  rock ' n' roll.
.Dp Pa calendar.usholiday
E 13
I 13
Strongly  oriented  toward  rock 'n' roll.
.It Pa calendar.usholiday
E 13
E 10
U.S. holidays.
This calendar should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year.
E 5
E 4
E 2
D 10
.SH "SEE ALSO"
D 4
at(1), cron(8), mail(1)
E 4
I 4
at(1), cpp(1), mail(1), cron(8)
I 9
.SH COMPATIBILITY
E 10
I 10
D 13
.Dp
E 13
I 13
.El
E 13
.Sh SEE ALSO
.Xr at 1 ,
.Xr cpp 1 ,
.Xr cron 8
.Xr mail 1 ,
.Sh COMPATIBILITY
E 10
The
D 10
.I calendar
E 10
I 10
.Nm calendar
E 10
program previously selected lines which had the correct date anywhere
in the line.
This is no longer true, the date is only recognized when it occurs
first on the line.
E 9
E 4
D 10
.SH BUGS
D 2
Your calendar must be public information for you
to get reminder service.
.br
E 2
D 4
.I Calendar's
extended idea of `tomorrow' doesn't account for
holidays.
E 4
I 4
.I Calendar
E 10
I 10
.Sh HISTORY
A
.Nm
command appeared in Version 7 AT&T UNIX.
D 15
The version of
.Nm calendar
D 13
released with this man page
D 11
is not derived from the AT&T version.
.\" what is status of code?? are phrases like today's date a problem?
.\" todays's and tomorrow' are only AT&T similarities
E 11
I 11
is unrelated.
E 13
I 13
released with this manual
is new and unrelated to the former.
E 15
E 13
E 11
.Sh BUGS
.Nm Calendar
E 10
D 17
doesn't handle events that move around from year to year, i.e.
E 17
I 17
doesn't handle events that move around from year to year, i.e.,
E 17
``the last Monday in April''.
E 4
E 1
