h00221
s 00012/00007/00079
d D 8.2 94/03/19 11:27:53 bostic 10 9
c tput patch to support 'tput cm 10 20'
c From: Christos-Zoulas@deshaw.com (Christos Zoulas)
e
s 00002/00002/00084
d D 8.1 93/06/06 16:37:19 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00003/00083
d D 6.5 93/03/23 18:58:01 cael 8 7
c update .Os and history from .Ud to .Bx 4.4
e
s 00052/00057/00034
d D 6.4 91/04/23 16:25:29 cael 7 5
c mdoc version three
e
s 00004/00014/00077
d R 6.4 90/06/24 19:21:03 cael 6 5
c converted man page
e
s 00028/00004/00063
d D 6.3 89/10/31 10:12:36 bostic 5 4
c add boolean and numeric capabilities, key word longname; specify exit values
e
s 00061/00014/00006
d D 6.2 89/10/30 17:07:37 bostic 4 3
c replace clear with simple version of tput
e
s 00001/00001/00019
d D 6.1 85/04/29 14:19:13 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00002/00019
d D 5.1 85/04/29 14:19:06 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00021/00000/00000
d D 4.1 85/04/29 14:18:59 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 7
.\" Copyright (c) 1989 The Regents of the University of California.
E 7
I 7
D 9
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 7
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 4
.\"
I 4
D 7
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
.\"
E 4
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH CLEAR 1 2/24/79
E 2
I 2
D 3
.TH CLEAR 1 "24 February 1979"
E 3
I 3
D 4
.TH CLEAR 1 "%Q%"
E 3
E 2
.UC
E 4
I 4
D 7
.TH TPUT 1 "%Q%"
.UC 7
E 4
.SH NAME
D 4
clear \- clear terminal screen
E 4
I 4
tput \- terminal capability interface
E 4
.SH SYNOPSIS
D 4
.B clear
E 4
I 4
.ft B
tput [ -T term ] attribute
.ft R
E 4
.SH DESCRIPTION
D 4
.I Clear
clears your screen if this is possible.
It looks in the environment for the terminal type and then in
.I /etc/termcap
to figure out how to clear the screen.
.SH FILES
/etc/termcap	terminal capability data base
E 4
I 4
.I Tput
E 7
I 7
.Dd %Q%
.Dt TPUT 1
D 8
.Os
E 8
I 8
.Os BSD 4.4
E 8
.Sh NAME
.Nm tput
.Nd terminal capability interface
.Sh SYNOPSIS
.Nm tput
.Op Fl T Ar term
.Ar attribute
.Sh DESCRIPTION
.Nm Tput
E 7
makes terminal-dependent information available to users or shell
applications.
The options are as follows:
D 7
.TP
\-T
E 7
I 7
.Bl -tag -width Ds
.It Fl T
E 7
The terminal name as specified in the
D 7
.I termcap
E 7
I 7
.Xr termcap
E 7
database, for example, ``vt100'' or ``xterm''.
If not specified,
D 7
.I tput
retrieves the ``TERM'' variable from the environment.
.PP
I 5
.I Tput
E 7
I 7
.Nm tput
retrieves the
.Dq Ev TERM
variable from the environment.
.El
.Pp
.Nm Tput
E 7
outputs a string if the
D 7
.I attribute
E 7
I 7
.Ar attribute
E 7
is of type string; a number if it is of type integer.
Otherwise,
D 7
.I tput
E 7
I 7
.Nm tput
E 7
exits 0 if the terminal has the capability and 1 if it does not,
without further action.
D 7
.PP
E 7
I 7
.Pp
I 10
If the
.Ar attribute
is of type string, and takes arguments (e.g. cursor movement,
the termcap
.Dq cm
sequence) the arguments are taken from the command line immediately
following the attribute.
.Pp
E 10
E 7
E 5
The following special attributes are available:
D 7
.TP
clear
.br
E 7
I 7
.Bl -tag -width Ar
D 10
.It Ar clear
E 10
I 10
.It clear
E 10
E 7
Clear the screen (the
D 7
.I termcap
E 7
I 7
.Xr termcap
E 7
``cl'' sequence).
D 7
.TP
init
.br
E 7
I 7
D 10
.It Ar init
E 10
I 10
.It init
E 10
E 7
Initialize the terminal (the
D 7
.I termcap
E 7
I 7
.Xr termcap
E 7
``is'' sequence).
D 7
.TP
I 5
longname
E 7
I 7
D 10
.It Ar longname
E 10
I 10
.It longname
E 10
E 7
Print the descriptive name of the user's terminal type.
D 7
.TP
E 5
reset
.br
E 7
I 7
D 10
.It Ar reset
E 10
I 10
.It reset
E 10
E 7
Reset the terminal (the
D 7
.I termcap
E 7
I 7
.Xr termcap
E 7
``rs'' sequence).
I 5
D 7
.SH DIAGNOSTICS
E 7
I 7
.Sh DIAGNOSTICS
E 7
The exit value of
D 7
.I tput
E 7
I 7
.Nm tput
E 7
is based on the last attribute specified.
If the attribute is of type string or of type integer,
D 7
.I tput
E 7
I 7
.Nm tput
E 7
exits 0 if the attribute is defined for this terminal type and 1
if it is not.
If the attribute is of type boolean,
D 7
.I tput
E 7
I 7
.Nm tput
E 7
exits 0 if the terminal has this attribute, and 1 if it does not.
D 7
.I Tput
E 7
I 7
.Nm Tput
E 7
exits 2 if any error occurred.
E 5
D 7
.SH "SEE ALSO"
termcap(3), termcap(5)
.SH BUGS
.I Tput
E 7
I 7
.Sh SEE ALSO
.Xr termcap 3 ,
.Xr termcap 5
.Sh BUGS
.Nm Tput
E 7
D 5
doesn't have the power available in the System V version of the
program.
E 5
I 5
can't really distinguish between different types of attributes.
E 5
D 10
This is due to the limited interface in the current version of
D 5
.IR termcap (3).
This will be fixed in the near future.
E 5
I 5
D 7
.IR termcap (3),
E 7
I 7
.Xr termcap 3 ,
E 7
and will be fixed in the near future.
E 10
I 7
.Sh HISTORY
The
.Nm
D 8
command is
.Ud .
E 8
I 8
command appears in
.Bx 4.4 .
E 8
E 7
E 5
E 4
D 2
.SH BUGS
E 2
E 1
