h27507
s 00002/00002/00103
d D 8.1 93/06/06 16:03:11 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00019/00021/00086
d D 6.8 91/07/27 17:42:37 cael 10 9
c mdoc version three
e
s 00002/00000/00105
d D 6.7 91/03/14 00:25:39 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00105
d R 6.7 91/03/13 20:36:59 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00026/00025/00079
d D 6.6 90/07/24 22:50:29 cael 7 6
c .Xr botch fix
e
s 00081/00076/00023
d D 6.5 90/06/11 05:59:48 cael 6 5
c converted man page
e
s 00061/00020/00038
d D 6.4 90/05/06 14:34:26 mckusick 5 4
c update for new quota system
e
s 00010/00005/00048
d D 6.3 88/07/09 11:45:05 bostic 4 3
c install approved copyright notice
e
s 00009/00003/00044
d D 6.2 88/05/20 12:19:23 bostic 3 2
c add Berkeley specific header
e
s 00001/00001/00046
d D 6.1 85/04/29 21:13:59 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00047/00000/00000
d D 5.1 85/04/29 21:13:47 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 5
.\" Copyright (c) 1983 Regents of the University of California.
E 5
I 5
D 6
.\" Copyright (c) 1983, 1990 Regents of the University of California.
E 6
I 6
D 11
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
E 6
E 5
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
.\"
I 6
D 10
.\"
E 10
E 6
I 5
.\" This code is derived from software contributed to Berkeley by
.\" Robert Elz at The University of Melbourne.
.\"
E 5
D 6
.\" Redistribution and use in source and binary forms are permitted
D 4
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
E 4
I 4
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 6
E 4
E 3
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
D 10
.\"     %W% (Berkeley) %G%
E 10
I 10
.\"	%W% (Berkeley) %G%
E 10
E 6
.\"
I 9
D 10
.Vx
.Vx
E 10
E 9
D 2
.TH QUOTA 1  "28 July 1983"
E 2
I 2
D 6
.TH QUOTA 1 "%Q%"
E 2
.UC 5
.SH NAME
D 5
quota \- display disc usage and limits
E 5
I 5
quota \- display disk usage and limits
E 5
.SH SYNOPSIS
.B quota
[
D 5
.B \-qv
E 5
I 5
.B \-g
E 5
] [
I 5
.B \-u
] [
.B "\-v | \-q"
]
.br
.B quota
[
.B \-u
] [
.B "\-v | \-q"
]
E 5
user
I 5
.br
.B quota
.B \-g
[
.B "\-v | \-q"
E 5
]
I 5
group
.br
E 5
.SH DESCRIPTION
.I Quota
D 5
displays users' disc usage and limits. 
Only the super-user may use the optional
E 5
I 5
displays users' disk usage and limits. 
E 6
I 6
.Dd %Q%
.Dt QUOTA 1
.Os BSD 4.2
.Sh NAME
.Nm quota
.Nd display disk usage and limits
.Sh SYNOPSIS
.Nm quota
.Op Fl g
.Op Fl u
D 10
.Op Fl v Li \&| Fl q
E 10
I 10
.Op Fl v | Fl q
E 10
.Nm quota
.Op Fl u
D 10
.Op Fl v Li \&| Fl q
E 10
I 10
.Op Fl v | Fl q
E 10
.Ar user
.Nm quota
.Op Fl g
D 10
.Op Fl v Li \&| Fl q
E 10
I 10
.Op Fl v | Fl q
E 10
.Ar group
.Sh DESCRIPTION
.Nm Quota
displays users' disk usage and limits.
E 6
By default only the user quotas are printed.
I 7
.Pp
Options:
.Pp
D 10
.Tw Ds
.Tp Fl g
E 10
I 10
.Bl -tag -width Ds
.It Fl g
E 10
Print group quotas for the group 
of which the user is a member.
E 7
D 6
The optional \fI-g\fP flag specifies that group quotas
E 6
I 6
The optional
D 7
.Fl g
flag specifies that group quotas
E 6
for the groups of which the user is a member should be printed.
E 7
I 7
.Fl u
flag is equivalent to the default.
D 10
.Tp Fl v
E 10
I 10
.It Fl v
E 10
.Nm quota
will display quotas on filesystems
where no storage is allocated.
D 10
.Tp Fl q
E 10
I 10
.It Fl q
E 10
Print a more terse message,
containing only information
on filesystems where usage is over quota.
D 10
.Tp
E 10
I 10
.El
E 10
.Pp
E 7
D 6
Specifying both \fI-g\fP and \fI-u\fP
E 6
I 6
Specifying both
.Fl g
and
.Fl u
E 6
D 7
specifies that both the user quotas and the group quotas for
the groups of which the user is a member should be printed.
D 6
The optional \fI-u\fP flag is equivalent to the default.
.PP
Only the super-user may use the \fI-u\fP flag and the optional
E 5
.I user
E 6
I 6
The optional
.Fl u
flag is equivalent to the default.
E 7
I 7
displays both the user quotas and the group quotas (for
the user).
E 7
.Pp
Only the super-user may use the
.Fl u
flag and the optional
.Ar user
E 6
D 5
argument to view the limits of users other than
himself.
E 5
I 5
argument to view the limits of other users.
D 6
Non-super-users can use the the \fI-g\fP flag and optional
.I group
E 6
I 6
Non-super-users can use the the
.Fl g
flag and optional
.Ar group
E 6
argument to view only the limits of groups of which they are members.
E 5
D 6
.PP
E 6
I 6
.Pp
E 6
D 5
The
.B \-q
flag prints a more terse message,
containing only information
on file systems where usage is over quota.
.PP
E 5
D 7
If a
D 6
.B \-v
flag is supplied, 
.I quota
E 6
I 6
.Fl v
flag is supplied,
.Nm quota
E 6
D 5
will also display user's quotas on file systems
E 5
I 5
will also display quotas on filesystems
E 5
where no storage is allocated.
D 6
.PP
E 6
I 6
.Pp
E 7
E 6
I 5
The
D 6
.B \-q
E 6
I 6
.Fl q
E 6
D 7
flag prints a more terse message,
containing only information
on filesystems where usage is over quota.
D 6
The \fI-q\fP flag takes precedence over the \fI-v\fP flag.
.PP
E 5
.I Quota
E 6
I 6
The
.Fl q
E 7
flag takes precedence over the
.Fl v
flag.
.Pp
.Nm Quota
E 6
D 5
reports only on file systems which have
disc quotas. 
E 5
I 5
reports the quotas of all the filesystems listed in
D 6
.IR /etc/fstab .
E 5
If 
.I quota
E 6
I 6
D 7
.Nm /etc/fstab .
E 7
I 7
.Pa /etc/fstab .
E 7
If
.Nm quota
E 6
D 5
exits with a non-zero status, one or more file
systems are over quota.
.SH "SEE ALSO"
quota(2), quotaon(8)
E 5
I 5
exits with a non-zero status, one or more filesystems
are over quota.
D 6
.SH FILES
.DT
\fIquota.user\fP	at the filesystem root with user quotas
.br
\fIquota.group\fP	at the filesystem root with group quotas
.br
/etc/fstab	to find filesystem names and locations
.SH SEE ALSO
quotactl(2),
fstab(5),
edquota(8), quotacheck(8), quotaon(8), repquota(8)
E 6
I 6
.Sh FILES
D 10
.Dw quota.group
.Di L
D 7
.Nm quota.user
at the filesystem root with user quotas
.Nm quota.group
at the filesystem root with group quotas
E 7
I 7
.Dp Pa quota.user
E 10
I 10
.Bl -tag -width quota.group -compact
.It Pa quota.user
E 10
located at the filesystem root with user quotas
D 10
.Dp Pa quota.group
E 10
I 10
.It Pa quota.group
E 10
located at the filesystem root with group quotas
E 7
D 10
.Dp Pa /etc/fstab
E 10
I 10
.It Pa /etc/fstab
E 10
to find filesystem names and locations
D 10
.Dp
E 10
I 10
.El
E 10
.Sh HISTORY
D 10
.Nm Quota
appeared in 4.2 BSD.
E 10
I 10
The
.Nm quota
command appeared in
.Bx 4.2 .
E 10
.Sh SEE ALSO
.Xr quotactl 2 ,
.Xr fstab 5 ,
.Xr edquota 8 ,
.Xr quotacheck 8 ,
.Xr quotaon 8 ,
.Xr repquota 8
E 6
E 5
E 1
