h30386
s 00002/00002/00060
d D 8.1 93/06/04 16:53:55 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00000/00058
d D 5.5 92/05/26 14:37:35 bostic 5 4
c add LBL credit line
e
s 00014/00004/00044
d D 5.4 92/04/29 11:49:42 bostic 4 3
c update from LBL (Chris, Craig and Steve)
e
s 00002/00003/00046
d D 5.3 92/04/24 19:10:11 bostic 3 2
c fix file names
e
s 00012/00008/00037
d D 5.2 92/04/01 19:14:26 mckusick 2 1
c format fixes
e
s 00045/00000/00000
d D 5.1 92/04/01 18:29:01 mckusick 1 0
c from Steve McCanne
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1992 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
I 5
.\" This code is derived from software developed by the Computer Systems
.\" Engineering group at Lawrence Berkeley Laboratory under DARPA contract
.\" BG 91-66 and contributed to Berkeley.
.\"
E 5
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt KVM_NLIST 3
.Os
.Sh NAME
D 2
.Nm kvm_nlist 
E 2
I 2
.Nm kvm_nlist
E 2
.Nd retrieve symbol table names from a kernel image
.Sh SYNOPSIS
.Fd #include <kvm.h>
.Fd #include <nlist.h>
D 2
.br
E 2
.Ft int
.Fn kvm_nlist "kvm_t *kd" "struct nlist *nl"
.Sh DESCRIPTION
.Fn kvm_nlist
retrieves the symbol table entries indicated by the name list argument
D 2
.Fa nl .
E 2
I 2
.Fa \&nl .
E 2
This argument points to an array of nlist structures, terminated by
D 2
an entry whose n_name field is NULL (see 
.Xr nlist 3 ).
E 2
I 2
an entry whose n_name field is
.Dv NULL
(see
.Xr nlist 3 ) .
E 2
D 4
For each symbol is looked up using the n_name field, and if found, the
E 4
I 4
Each symbol is looked up using the n_name field, and if found, the
E 4
corresponding n_type and n_value fields are filled in.  These fields are set
to 0 if the symbol is not found.
.Pp
D 2
The program 
E 2
I 2
The program
E 2
D 4
.Fn kvm_mkdb
E 4
I 4
.Xr kvm_mkdb 8
E 4
builds a database from the running kernel's namelist.
If the database matches the opened kernel,
.Fn kvm_nlist
D 4
uses it to speed name to value calculations.
E 4
I 4
uses it to speed lookups.
E 4
.Sh RETURN VALUES
I 4
The
E 4
.Fn kvm_nlist
D 4
returns the number of invalid entries found.
E 4
I 4
function returns the number of invalid entries found.
E 4
If the kernel symbol table was unreadable, -1 is returned.
.Sh FILES
D 2
/var/run/kvm_vmunix.{dir,pag}
E 2
I 2
D 3
.Bl -tag -width /var/run/kvm_vmunix.{dir,pag} -compact
.It Pa /var/run/kvm_vmunix.dir
.It Pa /var/run/kvm_vmunix.pag
E 3
I 3
.Bl -tag -width /var/db/kvm_vmunix.db -compact
.It Pa /var/db/kvm_vmunix.db
E 3
.El
E 2
.Sh SEE ALSO
D 2
.Xr kvm 3
E 2
I 2
.Xr kvm 3 ,
I 4
.Xr kvm_close 3 ,
.Xr kvm_getargv 3 ,
.Xr kvm_getenvv 3 ,
.Xr kvm_geterr 3 ,
.Xr kvm_getprocs 3 ,
.Xr kvm_open 3 ,
.Xr kvm_openfiles 3 ,
.Xr kvm_read 3 ,
.Xr kvm_write 3 ,
E 4
E 2
.Xr kvm_mkdb 8
E 1
