h51911
s 00002/00002/00080
d D 8.1 93/06/06 22:27:43 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00046/00037/00036
d D 6.5 91/04/24 00:09:43 cael 7 6
c mdoc version three
e
s 00001/00011/00072
d D 6.4 91/04/18 18:58:57 bostic 6 5
c new copyright; att/bsd/shared
e
s 00065/00046/00018
d D 6.3 89/11/21 11:46:33 bostic 5 4
c new version from Jef Poskanzer and Craig Leres
e
s 00001/00001/00063
d D 6.2 86/05/05 15:59:57 bloom 4 3
c fix message string to correspond to reality
e
s 00001/00001/00063
d D 6.1 85/04/29 18:09:27 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00002/00062
d D 5.1 85/04/29 18:09:18 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00064/00000/00000
d D 4.1 85/04/29 18:09:07 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 5
D 8
.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1989, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Jef Poskanzer and Craig Leres of the Lawrence Berkeley Laboratory.
.\"
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 7
.\" %sccs.include.redist.roff%
E 7
I 7
.\" %sccs.include.redist.man%
E 7
E 6
.\"
E 5
I 1
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH WRITE 1 
E 2
I 2
D 3
.TH WRITE 1  "18 January 1983"
E 3
I 3
D 7
.TH WRITE 1 "%Q%"
E 3
E 2
D 5
.AT 3
E 5
I 5
.UC 4
E 5
.SH NAME
D 5
write \- write to another user
E 5
I 5
write - send a message to another user
E 5
.SH SYNOPSIS
D 5
.B write
user [ ttyname ]
E 5
I 5
.B write user
[
.B ttyname
]
.ft R
E 5
.SH DESCRIPTION
.I Write
E 7
I 7
.Dd %Q%
.Dt WRITE 1
.Os
.Sh NAME
.Nm write
.Nd send a message to another user
.Sh SYNOPSIS
.Nm write
.Ar user
.Op Ar ttyname
.Sh DESCRIPTION
.Nm Write
E 7
D 5
copies lines from your terminal to that of
another user.
When first called,
it sends the message
E 5
I 5
allows you to communicate with other users, by copying lines from
your terminal to theirs.
E 5
D 7
.PP
E 7
I 7
.Pp
E 7
D 2
     Message from yourname yourttyname...
E 2
I 2
D 4
     Message from yoursystem!yourname yourttyname...
E 4
I 4
D 5
     Message from yourname@yoursystem on yourttyname at time...
E 4
E 2
.PP
The recipient of the message should write back at this point.
Communication continues until an end of file is
read from the terminal or an interrupt is sent.
At that point
E 5
I 5
When you run the
E 5
D 7
.I write
E 7
I 7
.Nm write
E 7
D 5
writes `EOT' on the other terminal and exits.
E 5
I 5
command, the user you are writing to gets a message of the form:
D 7
.sp
.nf
.ti +5
Message from yourname@yourhost on yourtty at hh:mm ...
.fi
.sp
E 7
I 7
.Pp
.Dl Message from yourname@yourhost on yourtty at hh:mm ...
.Pp
E 7
Any further lines you enter will be copied to the specified user's
terminal.
If the other user wants to reply, they must run
D 7
.I write
E 7
I 7
.Nm write
E 7
as well.
E 5
D 7
.PP
E 7
I 7
.Pp
E 7
D 5
If you want to write to a user who is logged in more than once,
the
.I ttyname
argument may be used to indicate the
appropriate terminal name.
E 5
I 5
When you are done, type an end-of-file or interrupt character.
D 7
The other user will see the message ``EOF'' indicating that the
E 7
I 7
The other user will see the message
.Ql EOF
indicating that the
E 7
conversation is over.
E 5
D 7
.PP
E 7
I 7
.Pp
E 7
D 5
Permission to write may be denied or granted by use of the
.I mesg
E 5
I 5
You can prevent people (other than the super-user) from writing to you
with the
D 7
.IR mesg (1)
E 7
I 7
.Xr mesg 1
E 7
E 5
command.
D 5
At the outset writing is allowed.
Certain commands, in particular
E 5
I 5
Some commands, for example
E 5
D 7
.I nroff
E 7
I 7
.Xr nroff 1
E 7
and
D 5
.IR  pr (1)
disallow
messages in order to prevent messy output.
E 5
I 5
D 7
.IR pr ,
E 7
I 7
.Xr pr 1 ,
E 7
disallow writing automatically, so that your output isn't overwritten.
E 5
D 7
.PP
E 7
I 7
.Pp
E 7
D 5
If the character `!' is found at the beginning of a line,
E 5
I 5
If the user you want to write to is logged in on more than one terminal,
you can specify which terminal to write to by specifying the terminal
name as the second operand to the
E 5
D 7
.I write
E 7
I 7
.Nm write
E 7
D 5
calls the shell
to execute the rest of the
line as a command.
E 5
I 5
command.
Alternatively, you can let
D 7
.I write
E 7
I 7
.Nm write
E 7
select one of the terminals \- it will pick the one with the shortest
idle time.
This is so that if the user is logged in at work and also dialed up from
home, the message will go to the right place.
E 5
D 7
.PP
D 5
The following protocol is suggested for using
.IR write :
when you first write to another user, wait for him to
write back before starting to send.
Each party should end each message with a distinctive
signal\(em\fB(o)\fR
for `over' is conventional\(emthat the other may reply.
.B (oo)
for `over and out' is suggested when conversation
is about to be terminated.
.SH FILES
/etc/utmp	to find user
.br
/bin/sh		to execute `!'
E 5
I 5
The traditional protocol for writing to someone is that the string ``-o'',
E 7
I 7
.Pp
The traditional protocol for writing to someone is that the string
.Ql \-o ,
E 7
either at the end of a line or on a line by itself, means that it's the
other person's turn to talk.
D 7
The string ``o-o'' means that the person believes the conversation to be
E 7
I 7
The string
.Ql oo
means that the person believes the conversation to be
E 7
over.
E 5
D 7
.SH "SEE ALSO"
D 5
mesg(1), who(1), mail(1)
E 5
I 5
mesg(1), talk(1), who(1)
E 7
I 7
.Sh SEE ALSO
.Xr mesg 1 ,
.Xr talk 1 ,
.Xr who 1
.Sh HISTORY
A
.Nm
command appeared in
.At v6 .
E 7
E 5
E 1
