h36647
s 00013/00010/00004
d D 5.2 90/08/22 11:06:02 torek 2 1
c update for dupfd, saved ids, SysV shm, POSIX pgrps, tracing, etc
e
s 00014/00000/00000
d D 5.1 88/03/30 15:59:46 bostic 1 0
c date and time created 88/03/30 15:59:46 by bostic
e
u
U
t
T
I 1
D 2
./"link"16t"rlink"16t"next"16t"prev"n4Xn
E 2
I 2
./"link"16t"rlink"16t"next"16t"prev"n4X
E 2
+/"addr"16t"upri"8t"pri"8t"cpu"8t"stat"8t"time"nX5b
D 2
+/"nice"8t"slp"8t"cursig"16t"sig"n3b16tX
E 2
I 2
+/"nice"8t"slp"8t"dupfd"16t"sig"n3b16tX
E 2
+/"mask"16t"ignore"16t"catch"n3X
D 2
+/"flag"16t"uid"8t"pgrp"8t"pid"8t"ppid"nX4d
+/"xstat"16t"ru"16t"poip"8t"szpt"8t"tsize"nx2+16tX2xX
+/"dsize"16t"ssize"16t"rssize"16t"maxrss"n4X
+/"swrss"16t"swaddr"16t"wchan"16t"textp"n4X
+/"p0br"16t"xlink"16t"ticks"n2Xd2+
+/"%cpu"16t" "16t"ndx"8t"idhash"8t"pptr"nf16t2xX
+/"cptr"16t"osptr"16t"ysptr"n3X
E 2
I 2
+/"flag"16t"uid"8t"ruid"8t"svuid"8t"rgid"8t"svgid"nX5d
+/"pid"8t"ppid"8t"xstat"8t"ru"56t"poip"8t"szpt"n3dXdd
+/"tsize"16t"dsize"16t"mmsize"16t"ssize"n4D
+/"rssize"16t"maxrss"16t"swrss"16t"swaddr"n4D
+/"wchan"16t"textp"16t"p0br"16t"xlink"n4X
+/"ticks"16t"%cpu"16t"ndx"8t"hash"nd++16tXd++X
+/"pptr"16t"cptr"16t"osptr"16t"ysptr"n4X
+/"pgrp"16t"pgrpnxt"nXX
E 2
+/"real itimer"n4D
D 2
+/"quota"16tX
E 2
I 2
+/"traceflag"16t"tracep"16t"comm"nXX8C12+
+/"logname"48t"wmesg"n8C4+48tX
+/"utime"32t"stime"n4D
E 2
+,<9-1$<proc
E 1
