h26282
s 00008/00021/00113
d D 1.2 89/05/18 15:08:46 kfall 2 1
c attempt to De-Athenify
e
s 00134/00000/00000
d D 1.1 89/02/04 14:17:28 kfall 1 0
c date and time created 89/02/04 14:17:28 by kfall
e
u
U
t
T
I 1
.\" $Source: /mit/kerberos/src/man/RCS/kinit.1,v $
.\" $Author: jtkohl $
.\" $Header: kinit.1,v 4.6 89/01/23 11:39:11 jtkohl Exp $
.\" Copyright 1989 by the Massachusetts Institute of Technology.
.\"
.\" For copying and distribution information,
.\" please see the file <mit-copyright.h>.
.\"
.TH KINIT 1 "Kerberos Version 4.0" "MIT Project Athena"
.SH NAME
kinit \- Kerberos login utility
.SH SYNOPSIS
.B kinit
[
.B \-irvl
]
.SH DESCRIPTION
The
.I kinit
command is used to login to the
Kerberos
authentication and authorization system.
Note that only registered
Kerberos
users can use the
Kerberos
system.
For information about registering as a
Kerberos
user,
see the
.I kerberos(1)
manual page.
.PP
D 2
If you are logged in to a workstation that is running the
.I toehold
service,
E 2
I 2
If you system is configured so that
.IR login (1)
automatically provides your initial tickets,
E 2
you do not have to use
.I kinit.
D 2
The
.I toehold
login procedure will log you into
Kerberos
automatically.
E 2
You will need to use
.I kinit
only in those situations in which
your original tickets have expired.
(Tickets expire in about a day.)
D 2
Note as well that
.I toehold
will automatically destroy your tickets when you logout from the workstation.
E 2
.PP
When you use
.I kinit
without options,
the utility
D 2
prompts for your username and Kerberos password,
and tries to authenticate your login with the local
E 2
I 2
prompts for your Kerberos principal name and password,
and tries to authenticate your login with the local realm's
E 2
Kerberos
server.
.PP
If
Kerberos
authenticates the login attempt,
.I kinit
retrieves your initial ticket and puts it in the ticket file specified by
your KRBTKFILE environment variable.
If this variable is undefined,
your ticket will be stored in the
.IR /tmp
directory,
in the file
.I tktuid ,
where
.I uid
specifies your user identification number.
.PP
D 2
If you have logged in to
Kerberos
without the benefit of the workstation
.I toehold
system,
make sure you use the
E 2
I 2
Make sure you use the
E 2
.I kdestroy
command to destroy any active tickets before you end your login session.
You may want to put the
.I kdestroy
command in your
.I \.logout
file so that your tickets will be destroyed automatically when you logout.
.PP
The options to
.I kinit
are as follows:
.TP 7
.B \-i
.I kinit
prompts you for a
Kerberos
instance.
.TP
.B \-r
.I kinit
prompts you for a
Kerberos
realm.
This option lets you authenticate yourself with a remote
Kerberos
server.
.TP
.B \-v
Verbose mode.
.I kinit
D 2
prints the name of the ticket file used, and
E 2
I 2
prints the location of your tickets, and
E 2
a status message indicating the success or failure of
your login attempt.
.TP
.B \-l
.I kinit
prompts you for a ticket lifetime in minutes.  Due to protocol
restrictions in Kerberos Version 4, this value must be between 5 and
1275 minutes.
.SH SEE ALSO
.PP
D 2
kerberos(1), kdestroy(1), klist(1), toehold(1)
E 2
I 2
kerberos(1), kdestroy(1), klist(1)
E 2
.SH BUGS
The
.B \-r
option has not been fully implemented.
.SH AUTHORS
Steve Miller, MIT Project Athena/Digital Equipment Corporation
.br
Clifford Neuman, MIT Project Athena
E 1
