h13259
s 00002/00002/00060
d D 8.1 93/06/06 16:31:31 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00002/00059
d D 6.5 91/07/29 16:48:13 cael 9 8
c fix .Os, .St -p1003.2
e
s 00001/00003/00060
d D 6.4 91/07/22 18:01:51 bostic 8 7
c file is an output file, not an input file
e
s 00003/00000/00060
d D 6.3 91/06/27 17:25:04 bostic 7 6
c add POSIX/IEEE contribution notice
e
s 00059/00026/00001
d D 6.2 91/04/22 19:57:53 cael 6 3
c mdoc conversion/bsd copyright
e
s 00004/00002/00025
d R 6.3 91/04/18 18:19:46 bostic 5 4
c new copyright; att/bsd/shared
e
s 00002/00002/00025
d R 6.2 90/06/24 19:20:12 cael 4 3
c converted man page
e
s 00001/00001/00026
d D 6.1 85/04/29 18:01:56 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00026
d D 5.1 85/04/29 18:01:49 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00027/00000/00000
d D 4.1 85/04/29 18:01:41 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
D 10
.\" Copyright (c) 1991 Regents of the University of California.
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
E 6
.\"
I 7
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 7
D 2
.TH TEE 1 
E 2
I 2
D 3
.TH TEE 1  "18 January 1983"
E 3
I 3
D 6
.TH TEE 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
tee \- pipe fitting
.SH SYNOPSIS
.B tee
[
.B \-i
] [
.B \-a
]
[ file ] ...
.SH DESCRIPTION
.I Tee
transcribes the standard input to the standard
output and makes copies in the 
.I files.
Option
.B \-i
ignores interrupts;
option
.B \-a
causes the output to be appended to the
.I files
rather than overwriting them.
E 6
I 6
.\" %sccs.include.redist.roff%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt TEE 1
D 9
.Os BSD 4.4
E 9
I 9
.Os
E 9
.Sh NAME
.Nm tee
.Nd pipe fitting
.Sh SYNOPSIS
.Nm tee
.Op Fl ai
.Op Ar file ...
.Sh DESCRIPTION
The
.Nm tee
utility copies standard input to standard output,
making a copy in zero or more files.
The output is unbuffered.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl a
Append the output to the files rather than
overwriting them.
.It Fl i
Ignore the
.Dv SIGINT
signal.
.El
.Pp
The following operands are available:
.Bl -tag -width file
.It file
D 8
A pathname of an input
E 8
I 8
A pathname of an output
E 8
.Ar file .
D 8
If no file operands
are specified, the standard input is used.
E 8
.El
.Pp
The
.Nm tee
utility takes the default action for all signals,
except in the event of the
.Fl i
option.
.Pp
The
.Nm tee
utility exits 0 on success, and >0 if an error occurs.
.Sh STANDARDS
The
.Nm tee
function is expected to be
.Tn POSIX
D 9
1003.2 compatible.
E 9
I 9
.St -p1003.2
compatible.
E 9
E 6
E 1
