h19512
s 00033/00038/00107
d D 6.6 91/08/08 17:34:56 cael 8 7
c mdoc version three
e
s 00003/00004/00142
d D 6.5 91/04/18 16:36:26 bostic 7 6
c new copyright; att/bsd/shared
e
s 00002/00000/00144
d D 6.4 91/03/14 00:25:59 cael 6 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00144
d R 6.4 91/03/13 20:37:10 cael 5 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00113/00085/00031
d D 6.3 90/07/24 22:51:13 cael 4 3
c .Xr botch fix
e
s 00000/00002/00116
d D 6.2 86/05/07 13:27:12 mckusick 3 2
c delete authors
e
s 00001/00001/00117
d D 6.1 85/04/29 21:15:23 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00118/00000/00000
d D 5.1 85/04/29 21:15:10 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 7
.\" Copyright (c) 1983, 1990 Regents of the University of California.
E 7
I 7
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
E 7
.\" All rights reserved.
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
E 4
.\"
D 2
.TH ROFFBIB 1 "18 July 1983"
E 2
I 2
D 4
.TH ROFFBIB 1 "%Q%"
E 2
.UC 5
.SH NAME
roffbib \- run off bibliographic database
.SH SYNOPSIS
.B roffbib
[
.B \-e
] [
.B \-h
] [
.B \-n
] [
.B \-o
] [
.B \-r
] [
.B \-s
] [
.BI \-T term
] [
.B \-x
] [
.B \-m
.I mac
] [
.B \-V
] [
.B \-Q
] [ file ... ]
.SH DESCRIPTION
.I Roffbib
prints out all records in a bibliographic database,
E 4
I 4
D 7
.\"     %W% (Berkeley) %G%
E 7
I 7
.\"	%W% (Berkeley) %G%
E 7
.\"
I 6
D 7
.Vx
E 7
D 8
.Vx
E 8
E 6
.Dd %Q%
.Dt ROFFBIB 1
.Os BSD 4.2
.Sh NAME
.Nm roffbib
.Nd run off bibliographic database
.Sh SYNOPSIS
.Nm roffbib
.Op Fl e
.Op Fl h
.Op Fl n
.Op Fl o
.Op Fl r
.Op Fl s
D 8
.Oo
.Op Fl T Ar term
.Oo
E 8
I 8
.Op Fl T Ns Ar term
E 8
.Op Fl x
D 8
.Op Fl m Ar mac
E 8
I 8
.Op Fl m Ns Ar mac
E 8
.Op Fl V
.Op Fl Q
.Ar
.Sh DESCRIPTION
.Nm Roffbib
is a shell script which prints out all records in a bibliographic database,
E 4
in bibliography format rather than as footnotes or endnotes.
Generally it is used in conjunction with
D 4
.IR sortbib :
.LP
.RS
sortbib  database | roffbib
.RE
.LP
.I Roffbib
E 4
I 4
.Xr sortbib  :
.Pp
.Dl sortbib  database \&| roffbib
.Pp
.Nm Roffbib
E 4
accepts most of the options understood by
D 4
.IR nroff (1),
most importantly the
.B \-T
E 4
I 4
.Xr nroff  1  ,
such as the
.Fl T
E 4
flag to specify terminal type.
D 4
.PP
If abstracts or comments are entered following the %X field key,
.I roffbib
E 4
I 4
.Pp
D 8
If abstracts or comments are entered in the database following the %X field key,
E 8
I 8
If abstracts or comments are entered in the database following the
.Cm %X
field key,
E 8
.Nm roffbib
E 4
will format them into paragraphs for an annotated bibliography.
D 8
Several %X fields may be given if several
E 8
I 8
Several
.Cm %X
fields may be given if several
E 8
annotation paragraphs are desired.
D 4
The
.B \-x
flag will suppress the printing of these abstracts.
.PP
A user-defined set of macros
may be specified after the
.B \-m
E 4
I 4
.Pp
Options exclusive to
.Nm roffbib :
D 8
.Tp Fl x
Suppresses the printing of %X abstracts.
.Tp Fl V
E 8
I 8
.Bl -tag -width Fl x
.It Fl x
Suppresses the printing of
.Cm %X
abstracts.
.It Fl V
E 8
Send output to the Versatec (use vtroff).
D 8
.Tp Fl Q
E 8
I 8
.It Fl Q
E 8
Queue the output to the default troff device.
D 8
.Tp
E 8
I 8
.El
E 8
.Pp
If neither the
.Fl Q
or
.Fl V
flags are given,
.Nm
sends the output to the standard output.
The default macros for
.Nm
are in 
.Pa /usr/share/tmac/tmac.bib .
These can be over ridden by
specifying a user-defined set with the
.Fl m
E 4
option.
D 4
There should be a space between the
.B \-m
and the macro filename.
This set of macros will replace the ones
defined in /usr/lib/tmac/tmac.bib.
The
.B \-V
flag will send output to the Versatec; the
.B \-Q
flag will queue output for the phototypesetter.
.PP
E 4
I 4
.Pp
E 4
Four command-line registers control formatting style
of the bibliography, much like the number registers of
D 4
.IR ms (7).
E 4
I 4
.Xr ms  7  .
E 4
The command-line argument
D 4
.BR \-r N1
E 4
I 4
D 8
.Cx Fl r
.Ar N1
.Cx
E 8
I 8
.Fl r Ns Ar N1 
E 8
E 4
will number
D 4
the references starting at one (1).
E 4
I 4
the references starting at one  1 .
E 4
The flag
D 4
.BR \-r V2
E 4
I 4
D 8
.Cx Fl r
.Ar V2
.Cx
E 4
will double space the biblio\%graphy,
E 8
I 8
.Fl r Ns Ar V2 
will double space the bibliography,
E 8
while
D 4
.BR \-r V1
E 4
I 4
D 8
.Cx Fl r
.Ar V1
.Cx
E 8
I 8
.Fl r Ns Ar V1 
E 8
E 4
will double space references
but single space annotation paragraphs.
The line length can be changed from the default 6.5 inches
to 6 inches with the
D 4
.BR \-r L6i
E 4
I 4
D 8
.Cx Fl r
.Ar L6i
.Cx
E 8
I 8
.Fl r Ns Ar L6i 
E 8
E 4
argument,
and the page offset can be set from the default of 0
to one inch by specifying
D 4
.BR \-r O1i
E 4
I 4
D 8
.Cx Fl r
.Ar O1i
.Cx
E 8
I 8
.Fl r Ns Ar O1i 
E 8
E 4
(capital O, not zero).
Note: with the
D 4
.B \-V
E 4
I 4
.Fl V
E 4
and
D 4
.B \-Q
E 4
I 4
.Fl Q
E 4
flags
the default page offset is already one inch.
D 4
.SH FILES
.ta \w'/usr/lib/tmac/tmac.bib\0\0'u
.nf
/usr/lib/tmac/tmac.bib	file of macros used by \fInroff/troff\fP
.fi
.SH SEE ALSO
refer(1), addbib(1), sortbib(1), indxbib(1), lookbib(1)
D 3
.SH AUTHORS
Greg Shenaut, Bill Tuthill
E 3
.SH BUGS
E 4
I 4
.Pp
.Nm Roffbib
is limited, but it is a good script to copy and adopt
for one's own needs, as it does demonstrate usage of
.Xr refer 1 .
.Sh FILES
D 8
.Dw /usr/share/tmac/tmac.bib
.Di L
.Dp Pa /usr/bin/roffbib
.Nm
E 8
I 8
.Bl -tag -width /usr/share/tmac/tmac.bib -compact
.It Pa /usr/bin/roffbib
.Nm Roffbib
E 8
script.
D 8
.Dp Pa /usr/share/tmac/tmac.bib
file of macros used by
E 8
I 8
.It Pa /usr/share/tmac/tmac.bib
File of macros used by
E 8
.Xr nroff 1
and
D 8
.Xr troff 1
.Dp
E 8
I 8
.Xr troff 1 .
.El
E 8
.Sh SEE ALSO
.Xr refer 1 ,
.Xr addbib 1 ,
.Xr sortbib 1 ,
.Xr indxbib 1 ,
.Xr lookbib 1
.Sh HISTORY
D 8
.Nm Roffbib
appeared in 4.2 BSD.
E 8
I 8
The
.Nm roffbib
command appeared in
.Bx 4.2 .
E 8
.Sh BUGS
E 4
Users have to rewrite macros
to create customized formats.
E 1
