h58948
s 00002/00002/00034
d D 8.1 93/06/09 22:53:26 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00000/00033
d D 6.4 91/06/27 17:25:52 bostic 6 5
c add POSIX/IEEE contribution notice
e
s 00028/00031/00005
d D 6.3 91/04/23 16:28:08 cael 5 4
c mdoc version three/bsd copyright
e
s 00005/00000/00031
d D 6.2 91/04/18 18:29:09 bostic 4 3
c new copyright; att/bsd/shared
e
s 00001/00001/00030
d D 6.1 85/04/29 18:06:10 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00018/00020/00013
d D 5.1 85/04/29 18:06:01 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00033/00000/00000
d D 4.1 85/04/29 18:05:53 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 5
.\" Copyright (c) 1985 The Regents of the University of California.
E 5
I 5
D 7
.\" Copyright (c) 1983, 1985, 1990 The Regents of the University of California.
E 5
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1985, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
I 6
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 6
D 5
.\" %sccs.include.proprietary.roff%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH TRUE 1 
E 2
I 2
D 3
.TH TRUE 1 "11 January 1982"
E 3
I 3
D 5
.TH TRUE 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
true, false \- provide truth values
.SH SYNOPSIS
.B true
.PP
.B false
.SH DESCRIPTION
.I True
D 2
does nothing, successfully.
.I False
does nothing, unsuccessfully.
They are typically used in input to
.IR  sh (1)
such as:
.PP
	while true
.br
	do
.br
		command
.br
	done
E 2
I 2
and
.I false
are usually used in a Bourne shell script.
They test for the appropriate status "true" or "false" before running 
E 5
I 5
.Dd %Q%
.Dt TRUE 1
.Os
.Sh NAME
.Nm true
.Nd return true value
.Sh SYNOPSIS
.Nm true
.Sh DESCRIPTION
.Nm True
is normally used in a Bourne shell script.
.Nm True
tests for the appropriate status "false" before running 
E 5
(or failing to run) a list of commands.  
D 5
.SH EXAMPLE
.IP
.nf
     while true 
     do
          command list 
     done
E 2
.SH "SEE ALSO"
D 2
sh(1)
E 2
I 2
csh(1),
sh(1),
false(1)
E 2
.SH DIAGNOSTICS
D 2
.I True
has exit status zero,
.I false
nonzero.
E 2
I 2
.I True 
has exit status zero.
E 5
I 5
.Sh SEE ALSO
.Xr csh 1 ,
.Xr sh 1 ,
.Xr false 1
.Sh DIAGNOSTICS
The
.Nm true
utility always returns with exit code zero.
.Sh STANDARDS
The
.Nm true
function is expected to be POSIX 1003.2 compatible.
E 5
E 2
E 1
