h31045
s 00002/00002/00271
d D 8.1 93/06/06 22:13:48 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00219/00174/00054
d D 6.6 91/03/16 18:11:01 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00020/00020/00208
d D 6.5 90/06/24 22:09:23 trent 5 4
c new pathnames
e
s 00009/00005/00219
d D 6.4 88/10/24 11:59:58 bostic 4 3
c remove refs to [18]C, add copyright if needed
e
s 00013/00002/00211
d D 6.3 86/05/15 14:16:22 bloom 3 2
c add uucpd to man page
e
s 00125/00052/00088
d D 6.2 86/04/24 22:18:11 mckusick 2 1
c update from rfg
e
s 00140/00000/00000
d D 6.1 85/06/24 13:17:05 bloom 1 0
c manual page first distributed with 4.3BSD
e
u
U
t
T
I 4
D 6
.\" Copyright (c) 1988 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 7
.\" Copyright (c) 1988, 1991 Regents of the University of California.
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 6
.\"
E 4
I 1
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
D 4
.TH UUCICO 8C "%Q%"
E 4
I 4
D 6
.TH UUCICO 8 "%Q%"
E 4
.UC 6
.SH NAME
D 2
uucicio \- uupoll transfer files queued by uucp or uux
E 2
I 2
D 3
uucico \- transfer files queued by uucp or uux
E 3
I 3
uucico, uucpd \- transfer files queued by uucp or uux
E 3
E 2
.SH SYNOPSIS
D 2
.B uucico
E 2
I 2
.B /usr/lib/uucp/uucico
E 2
[
.BI \-d spooldir
] [
.BI \-g grade
] [
.BI \-r role
] [
.B \-R
] [
.BI \-s system
] [
.BI \-x debug
] [
.B \-L
] [
.BI \-t turnaround
]
I 3
.PP
D 5
.B /etc/uucpd
E 5
I 5
.B uucpd
E 5
E 3
D 2
.PP
.B uupoll 
[
.BI \-g grade
] [
.B -n
]
system [ system1 ... ]
E 2
.SH DESCRIPTION
D 2
.I uucico
E 2
I 2
.I Uucico
E 6
I 6
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt UUCICO 8
.Os BSD 4.3
.Sh NAME
.Nm uucico ,
.Nm uucpd
.Nd transfer files queued by uucp or uux
.Sh SYNOPSIS
.Nm uucico
.Op Fl L
.Op Fl R
.Op Fl d Ns Ar spooldir
.Op Fl g Ns Ar grade
.Op Fl r Ns Ar role
.Op Fl s Ns Ar system
.Op Fl x Ns Ar debug
.Op Fl t Ns Ar turnaround
.Nm uucpd
.Sh DESCRIPTION
.Nm Uucico
E 6
E 2
performs the actual work involved in transferring files between
D 6
systems. 
D 2
.I uucp
E 2
I 2
D 4
.IR Uucp (1C)
E 4
I 4
.IR Uucp (1)
E 6
I 6
systems.
.Xr Uucp 1
E 6
E 4
E 2
and
D 2
.I uux
merely queue requests for data transfer which uucico processes.
E 2
I 2
D 4
.IR uux (1C)
E 4
I 4
D 6
.IR uux (1)
E 6
I 6
.Xr uux 1
E 6
E 4
merely queue requests for data transfer which
D 6
.I uucico
E 6
I 6
.Nm uucico
E 6
processes.
E 2
D 6
.PP
E 6
I 6
.Pp
E 6
The following options are available.
D 6
.TP 8
.BI \-d spooldir
E 6
I 6
.Bl -tag -width Ds
.It Fl L
Only call
.Dq local
sites. A site is considered local if the device-type field in
.Xr L.sys 5
is one of
.Tn LOCAL , DIR
or
.Tn TCP .
.It Fl R
Reverse roles.  When used with the
.Fl r Ns Ar 1
option, this tells the remote system to begin sending its
jobs first, instead of waiting for the local machine to finish.
.It Fl d Ns Ar spooldir
E 6
Use
D 6
.I spooldir
D 2
as the spool directory.
E 2
I 2
D 5
as the spool directory. The default is /usr/spool/uucp.
E 5
I 5
as the spool directory. The default is /var/spool/uucp.
E 5
E 2
.TP 8
.BI \-g grade
E 6
I 6
.Ar spooldir
as the spool directory. The default is
.Pa /var/spool/uucp.
.It Fl g Ns Ar grade
E 6
Only send jobs of grade
D 6
.I grade
E 6
I 6
.Ar grade
E 6
or higher this transfer.
I 2
The grade of a job is specified when the job is queued by
D 6
.I uucp
E 6
I 6
.Xr uucp 1
E 6
or
D 6
.IR uux .
E 2
.TP 8
D 2
.B \-R
Reverse roles. This tells the remote system to begin sending its
jobs first, instead of waiting for the local machine to finish.
.TP 8
E 2
.BI \-r role
.I role
E 6
I 6
.Xr uux 1 .
.It Fl r Ns Ar role
.Ar role
E 6
D 2
is either 1 or 0. It signifies whether uucico is to run in 
master or slave mode. 1 is used when starting 
E 2
I 2
is either 1 or 0; it indicates whether
E 2
D 6
.I uucico
D 2
by hand. 0 is used when another system calls the local system.
E 2
I 2
is to start up in 
master or slave role, respectively. 1 is used when running 
.I uucico
E 6
I 6
.Nm uucico
is to start up in
master or slave role, respectively. 1 is used when running
.Nm uucico
E 6
by hand or from
D 6
.IR cron (8).
E 6
I 6
.Xr cron 8 .
E 6
0 is used when another system calls the local system.
Slave role is the default.
E 2
D 6
.TP 8
I 2
.B \-R
Reverse roles.  When used with the
.B \-r1
option, this tells the remote system to begin sending its
jobs first, instead of waiting for the local machine to finish.
.TP 8
E 2
.BI \-s system
E 6
I 6
.It Fl s Ns Ar system
E 6
Call only system
D 6
.IR system .
If 
.B \-s
D 2
is not specified, and \-r1 is specifed,
E 2
I 2
is not specified, and \-r1 is specified,
E 2
.I uucico
E 6
I 6
.Ar system .
If
.Fl s
is not specified, and
.Fl r Ns Ar 1
is specified,
.Nm uucico
E 6
will attempt to call all systems for which there is work.
If
D 6
.B \-s
E 6
I 6
.Fl s
E 6
is specified, a call will be made even if there is
D 2
no work for that system. This is useful for polling
systems.
E 2
I 2
no work for that system. This is useful for polling.
E 2
D 6
.TP 8
.BI \-x debug
Turn on debugging at level
.IR debug .
Level 5 is a good start when trying to find out why a call
failed. Level 9 is very detailed. Level 99 is absurdly verbose.
I 2
If
.I role
is 1 (master), output is normally written to the standard message
output
.IR stderr .
If
.I stderr
is unavailable, output is written to
D 5
.RI /usr/spool/uucp/AUDIT/ system.
E 5
I 5
.RI /var/spool/uucp/AUDIT/ system.
E 5
When
.I role
is 0 (slave), debugging output is always written to the AUDIT
file.
E 2
.TP 8
.B \-L
Only call ``local'' sites. A site is considered local if
the device-type field in 
.I L.sys
is one of LOCAL, DIR or TCP.
.TP 8
.BI \-t turnaround
E 6
I 6
.It Fl t Ns Ar turnaround
E 6
Use
D 6
.I turnaround
as the line turnaround time (in minutes) instead of the default 30.  If 
.I turnaround
E 6
I 6
.Ar turnaround
as the line turnaround time (in minutes) instead of the default 30.  If
.Ar turnaround
E 6
is missing or 0, line turnaround will be disabled.
D 2
After uucico has been running in Slave mode for
E 2
I 2
After
D 6
.I uucico
E 6
I 6
.Nm uucico
E 6
has been running in slave role for
E 2
D 6
.I turnaround 
E 6
I 6
.Ar turnaround
E 6
D 2
minutes, it will attempt to run in master mode by negotiating with the
remote machine.  In the past, a large transfer of news in
one direction would hold up mail going in the other direction.
E 2
I 2
minutes, it will attempt to run in master role by negotiating with the
remote machine.
In earlier versions of
D 6
.IR uucico ,
E 6
I 6
.Nm uucico ,
E 6
a transfer of many large files in one direction would hold up mail
going in the other direction.
E 2
With the turnaround code working, the message flow will be more
bidirectional in the short term.
D 2
This option only works with newer uucicos and is ignored by older ones.
E 2
I 2
This option only works with newer
D 6
.IR uucico 's
E 6
I 6
.Nm uucico Ns 's
E 6
and is ignored by older ones.
E 2
D 6
.PP
E 6
I 6
.It Fl x Ns Ar debug
Turn on debugging at level
.Ar debug .
Level 5 is a good start when trying to find out why a call
failed. Level 9 is very detailed. Level 99 is absurdly verbose.
E 6
If
D 6
.I uucico
E 6
I 6
.Ar role
is 1 (master), output is written to the standard error
.Em stderr .
If
.Em stderr
is unavailable, output is written to
.Pa /var/spool/uucp/AUDIT/ Ns Ar system .
When
.Ar role
is 0 (slave), debugging output is always written to the
AUDIT
file.
.El
.Pp
If
.Nm uucico
E 6
receives a
D 6
.B SIGFPE
E 6
I 6
.Dv SIGFPE
E 6
(see
D 2
.IR kill (1))
E 2
I 2
D 6
.IR kill (1)),
E 6
I 6
.Xr kill 1 ) ,
E 6
E 2
it will toggle the debugging on or off.
D 6
.PP
I 3
.I Uucpd
E 6
I 6
.Pp
.Nm Uucpd
E 6
is the server for supporting uucp connections over networks.
D 6
.I Uucpd
E 6
I 6
.Nm Uucpd
E 6
listens for service requests at the port indicated in the ``uucp''
D 6
service specification; see \fIservices\fP\|(5).
E 6
I 6
service specification; see
.Xr services 5 .
E 6
The server provides login name and password authentication before starting up
D 6
.I uucico
E 6
I 6
.Nm uucico
E 6
for the rest of the transaction.
D 6
.PP
E 3
D 2
This program will typically be started by
.IR cron (8).
E 2
I 2
.I Uucico
E 6
I 6
.Pp
.Nm Uucico
E 6
is commonly used either of two ways: as a daemon run periodically by
D 6
.IR cron (8)
E 6
I 6
.Xr cron 8
E 6
to call out to remote systems, and as a ``shell'' for remote systems
who call in.
For calling out periodically, a typical line in
D 6
.I crontab
E 6
I 6
.Xr crontab
E 6
would be:
E 2
D 6
.PP
D 2
.B uupoll
is used to force a poll of a remote system. It queues a null job
for the remote system and invokes 
.I uucico.
If the
.I \-g
flag is specified, the null job will be queued with grade 
.IR grade .
If
.I \-n
is specified, the null job will be queued, but an immediate
E 2
I 2
.nf
	0	*	*	*	*	/usr/lib/uucp/uucico -r1
.fi
.PP
E 6
I 6
.Bd -literal
0    *    *    *    *    /usr/lib/uucp/uucico -r1
.Ed
.Pp
E 6
This will run
E 2
D 6
.I uucico
D 2
will not be invoked.
E 2
I 2
every hour in master role. 
For each system that has transfer requests queued, 
.I uucico
E 6
I 6
.Nm uucico
every hour in master role.
For each system that has transfer requests queued,
.Nm uucico
E 6
calls the system, logs in, and executes the transfers. The file
D 6
.IR L.sys (5)
E 6
I 6
.Xr L.sys 5
E 6
is consulted for information about how to log in, while
D 6
.IR L-devices (5)
E 6
I 6
.Xr L-devices 5
E 6
specifies available lines and modems for calling.
D 6
.PP
E 6
I 6
.Pp
E 6
For remote systems to dial in, an entry in the
D 6
.IR passwd (5)
E 6
I 6
.Xr passwd 5
E 6
file must be created, with a login ``shell'' of
D 6
.IR uucico .
E 6
I 6
.Nm uucico .
E 6
For example:
D 6
.PP
.nf
D 5
	nuucp:Password:6:1::/usr/spool/uucppublic:/usr/lib/uucp/uucico
E 5
I 5
	nuucp:Password:6:1::/var/spool/uucppublic:/usr/lib/uucp/uucico
E 5
.fi
.PP
The UID for UUCP remote logins is not critical, so long as it differs from
D 3
the UUCP Administrative login (usually UID 5).
E 3
I 3
the UUCP Administrative login.
E 3
The latter owns the UUCP files, and assigning
this UID to a remote login would be an extreme security hazard. 
E 2
.SH FILES
D 2
.TP 22
/usr/lib/uucp
directory with commands used by uucico internally
.TP
/usr/spoool/uucp
spool directory
E 2
I 2
D 5
.ta \w'/usr/spool/uucp/D.hostnameX/  'u
E 5
I 5
.ta \w'/var/spool/uucp/D.hostnameX/  'u
E 5
.nf
/usr/lib/uucp/	UUCP internal files/utilities
/usr/lib/uucp/L-devices	Local device descriptions
/usr/lib/uucp/L-dialcodes	Phone numbers and prefixes
/usr/lib/uucp/L.aliases	Hostname aliases
/usr/lib/uucp/L.cmds	Remote command permissions list
/usr/lib/uucp/L.sys	Host connection specifications
/usr/lib/uucp/USERFILE	Remote directory tree permissions list
.PP
D 5
/usr/spool/uucp/	Spool directory
/usr/spool/uucp/AUDIT/*	Debugging audit trails
/usr/spool/uucp/C./	Control files directory
/usr/spool/uucp/D./	Incoming data file directory
/usr/spool/uucp/D.hostname/	Outgoing data file directory
/usr/spool/uucp/D.hostnameX/	Outgoing execution file directory
/usr/spool/uucp/CORRUPT/	Place for corrupted C. and D. files
/usr/spool/uucp/ERRLOG	UUCP internal error log
/usr/spool/uucp/LOGFILE	UUCP system activity log
/usr/spool/uucp/LCK/LCK..*	Device lock files
/usr/spool/uucp/SYSLOG	File transfer statistics log
/usr/spool/uucp/STST/*	System status files
/usr/spool/uucp/TM./	File transfer temp directory
/usr/spool/uucp/X./	Incoming execution file directory
E 5
I 5
/var/spool/uucp/	Spool directory
/var/spool/uucp/AUDIT/*	Debugging audit trails
/var/spool/uucp/C./	Control files directory
/var/spool/uucp/D./	Incoming data file directory
/var/spool/uucp/D.hostname/	Outgoing data file directory
/var/spool/uucp/D.hostnameX/	Outgoing execution file directory
/var/spool/uucp/CORRUPT/	Place for corrupted C. and D. files
/var/spool/uucp/ERRLOG	UUCP internal error log
/var/spool/uucp/LOGFILE	UUCP system activity log
/var/spool/uucp/LCK/LCK..*	Device lock files
/var/spool/uucp/SYSLOG	File transfer statistics log
/var/spool/uucp/STST/*	System status files
/var/spool/uucp/TM./	File transfer temp directory
/var/spool/uucp/X./	Incoming execution file directory
E 5
.PP
D 5
/usr/spool/uucppublic	Public access directory
E 5
I 5
/var/spool/uucppublic	Public access directory
E 5
.fi
E 2
.SH SEE ALSO
I 2
D 4
uucp(1C), uuq(1C), uux(1C), L-devices(5), L-dialcodes(5), L.aliases(5),
L.cmds(5), L.sys(5), uuclean(8C), uupoll(8C), uusnap(8C), uuxqt(8C)
E 4
I 4
uucp(1), uuq(1), uux(1), L-devices(5), L-dialcodes(5), L.aliases(5),
L.cmds(5), L.sys(5), uuclean(8), uupoll(8), uusnap(8), uuxqt(8)
E 4
.PP
D. A. Nowitz and M. E. Lesk,
.IR "A Dial-Up Network of UNIX Systems" .
.PP
E 2
D. A. Nowitz,
D 2
Uucp Implementation Description
E 2
I 2
.IR "Uucp Implementation Description" .
E 6
I 6
.Bd -literal
nuucp:Password:6:1::/var/spool/uucppublic:/usr/lib/uucp/uucico
.Ed
.Pp
The
.Tn UID
for
.Tn UUCP
remote logins is not critical, so long as it differs from
the
.Tn UUCP
Administrative login.
The latter owns the
.Tn UUCP
files, and assigning
this
.Tn UID
to a remote login would be an extreme security hazard.
.Sh FILES
.Bl -tag -width /var/spool/uucp/D.hostnameX/ -compact
.It Pa /usr/lib/uucp/
.Tn UUCP
internal files/utilities
.It Pa /usr/lib/uucp/L-devices
Local device descriptions
.It Pa /usr/lib/uucp/L-dialcodes
Phone numbers and prefixes
.It Pa /usr/lib/uucp/L.aliases
Hostname aliases
.It Pa /usr/lib/uucp/L.cmds
Remote command permissions list
.It Pa /usr/lib/uucp/L.sys
Host connection specifications
.It Pa /usr/lib/uucp/USERFILE
Remote directory tree permissions list
.It Pa /var/spool/uucp/
Spool directory
.It Pa /var/spool/uucp/AUDIT/*
Debugging audit trails
.It Pa /var/spool/uucp/C./
Control files directory
.It Pa /var/spool/uucp/D./
Incoming data file directory
.It Pa /var/spool/uucp/D.hostname/
Outgoing data file directory
.It Pa /var/spool/uucp/D.hostnameX/
Outgoing execution file directory
.It Pa /var/spool/uucp/CORRUPT/
Place for corrupted C. and D. files
.It Pa /var/spool/uucp/ERRLOG
.Tn UUCP
internal error log
.It Pa /var/spool/uucp/LOGFILE
.Tn UUCP
system activity log
.It Pa /var/spool/uucp/LCK/LCK..*
Device lock files
.It Pa /var/spool/uucp/
.Tn SYSLOG
File transfer statistics log
.It Pa /var/spool/uucp/STST/*
System status files
.It Pa /var/spool/uucp/TM./
File transfer temp directory
.It Pa /var/spool/uucp/X./
Incoming execution file directory
.It Pa /var/spool/uucppublic
Public access directory
.El
.Sh SEE ALSO
.Xr uucp 1 ,
.Xr uuq 1 ,
.Xr uux 1 ,
.Xr L-devices 5 ,
.Xr L-dialcodes 5 ,
.Xr L.aliases 5 ,
.Xr L.cmds 5 ,
.Xr L.sys 5 ,
.Xr uuclean 8 ,
.Xr uupoll 8 ,
.Xr uusnap 8 ,
.Xr uuxqt 8
.Rs
.%A D. A. Nowitz
.%A M. E. Lesk
.%T "A Dial-Up Network of UNIX Systems"
.Re
.Rs
.%A D. A. Nowitz
.%T "Uucp Implementation Description"
.Re
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.3 .
E 6
E 2
E 1
