h32226
s 00001/00001/00153
d D 8.4 94/03/20 14:35:07 bostic 8 7
c delete UofT; requested change from Henry Spencer <henry@zoo.toronto.edu>
e
s 00001/00001/00153
d D 8.3 94/03/19 08:21:59 bostic 7 6
c make prototypes __P style
e
s 00015/00006/00139
d D 8.2 94/03/16 12:43:00 bostic 6 5
c alpha3.3
e
s 00002/00002/00143
d D 8.1 93/06/04 12:58:02 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00077/00046/00068
d D 5.4 93/05/21 16:06:53 bostic 4 3
c Henry Spencer's Alpha 3.0 regex release
e
s 00000/00019/00114
d D 5.3 92/09/30 14:30:47 bostic 3 2
c convert to 4BSD style prototypes, includes
e
s 00021/00004/00112
d D 5.2 92/09/30 12:58:06 bostic 2 1
c alpha2.1 release from Henry Spencer
e
s 00116/00000/00000
d D 5.1 92/08/06 11:58:07 bostic 1 0
c date and time created 92/08/06 11:58:07 by bostic
e
u
U
t
T
I 1
/*-
D 6
 * Copyright (c) 1992 Henry Spencer.
D 5
 * Copyright (c) 1992 The Regents of the University of California.
 * All rights reserved.
E 5
I 5
 * Copyright (c) 1992, 1993
E 6
I 6
 * Copyright (c) 1992, 1993, 1994 Henry Spencer.
 * Copyright (c) 1992, 1993, 1994
E 6
 *	The Regents of the University of California.  All rights reserved.
E 5
 *
 * This code is derived from software contributed to Berkeley by
D 8
 * Henry Spencer of the University of Toronto.
E 8
I 8
 * Henry Spencer.
E 8
 *
 * %sccs.include.redist.c%
 *
 *	%W% (Berkeley) %G%
 */

#if defined(LIBC_SCCS) && !defined(lint)
static char sccsid[] = "%W% (Berkeley) %G%";
#endif /* LIBC_SCCS and not lint */

#include <sys/types.h>
D 2

E 2
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
D 2
#include <assert.h>
E 2
#include <regex.h>

#include "utils.h"

I 4
D 6
static char *regatoi __P((const regex_t *, char *));
E 6
I 6
/* ========= begin header generated by ./mkh ========= */
#ifdef __cplusplus
extern "C" {
#endif
E 6

I 6
/* === regerror.c === */
D 7
static char *regatoi(const regex_t *preg, char *localbuf);
E 7
I 7
static char *regatoi __P((const regex_t *preg, char *localbuf));
E 7

#ifdef __cplusplus
}
#endif
/* ========= end header generated by ./mkh ========= */
E 6
/*
 = #define	REG_NOMATCH	 1
 = #define	REG_BADPAT	 2
 = #define	REG_ECOLLATE	 3
 = #define	REG_ECTYPE	 4
 = #define	REG_EESCAPE	 5
 = #define	REG_ESUBREG	 6
 = #define	REG_EBRACK	 7
 = #define	REG_EPAREN	 8
 = #define	REG_EBRACE	 9
 = #define	REG_BADBR	10
 = #define	REG_ERANGE	11
 = #define	REG_ESPACE	12
 = #define	REG_BADRPT	13
 = #define	REG_EMPTY	14
 = #define	REG_ASSERT	15
 = #define	REG_INVARG	16
 = #define	REG_ATOI	255	// convert name to number (!)
 = #define	REG_ITOA	0400	// convert number to name (!)
 */
E 4
I 2
D 3
/*
 = #define	REG_NOMATCH	 1
 = #define	REG_BADPAT	 2
 = #define	REG_ECOLLATE	 3
 = #define	REG_ECTYPE	 4
 = #define	REG_EESCAPE	 5
 = #define	REG_ESUBREG	 6
 = #define	REG_EBRACK	 7
 = #define	REG_EPAREN	 8
 = #define	REG_EBRACE	 9
 = #define	REG_BADBR	10
 = #define	REG_ERANGE	11
 = #define	REG_ESPACE	12
 = #define	REG_BADRPT	13
 = #define	REG_EMPTY	14
 = #define	REG_ASSERT	15
 */
E 3
E 2
static struct rerr {
	int code;
	char *name;
	char *explain;
} rerrs[] = {
D 4
	REG_NOMATCH,	"NOMATCH",	"regexec() failed to match",
	REG_BADPAT,	"BADPAT",	"invalid regular expression",
	REG_ECOLLATE,	"ECOLLATE",	"invalid collating element",
	REG_ECTYPE,	"ECTYPE",	"invalid character class",
D 2
	REG_EESCAPE,	"EESCAPE",	"\\ applied to unescapable character",
E 2
I 2
	REG_EESCAPE,	"EESCAPE",	"trailing backslash (\\)",
E 2
	REG_ESUBREG,	"ESUBREG",	"invalid backreference number",
	REG_EBRACK,	"EBRACK",	"brackets ([ ]) not balanced",
	REG_EPAREN,	"EPAREN",	"parentheses not balanced",
	REG_EBRACE,	"EBRACE",	"braces not balanced",
	REG_BADBR,	"BADBR",	"invalid repetition count(s)",
	REG_ERANGE,	"ERANGE",	"invalid character range",
	REG_ESPACE,	"ESPACE",	"out of memory",
	REG_BADRPT,	"BADRPT",	"repetition-operator operand invalid",
	REG_EMPTY,	"EMPTY",	"empty (sub)expression",
	REG_ASSERT,	"ASSERT",	"\"can't happen\" -- you found a bug",
E 4
I 4
	REG_NOMATCH,	"REG_NOMATCH",	"regexec() failed to match",
	REG_BADPAT,	"REG_BADPAT",	"invalid regular expression",
	REG_ECOLLATE,	"REG_ECOLLATE",	"invalid collating element",
	REG_ECTYPE,	"REG_ECTYPE",	"invalid character class",
	REG_EESCAPE,	"REG_EESCAPE",	"trailing backslash (\\)",
	REG_ESUBREG,	"REG_ESUBREG",	"invalid backreference number",
	REG_EBRACK,	"REG_EBRACK",	"brackets ([ ]) not balanced",
	REG_EPAREN,	"REG_EPAREN",	"parentheses not balanced",
	REG_EBRACE,	"REG_EBRACE",	"braces not balanced",
	REG_BADBR,	"REG_BADBR",	"invalid repetition count(s)",
	REG_ERANGE,	"REG_ERANGE",	"invalid character range",
	REG_ESPACE,	"REG_ESPACE",	"out of memory",
	REG_BADRPT,	"REG_BADRPT",	"repetition-operator operand invalid",
	REG_EMPTY,	"REG_EMPTY",	"empty (sub)expression",
	REG_ASSERT,	"REG_ASSERT",	"\"can't happen\" -- you found a bug",
	REG_INVARG,	"REG_INVARG",	"invalid argument to regex routine",
E 4
	0,		"",		"*** unknown regexp error code ***",
};

/*
 - regerror - the interface to error numbers
I 4
D 6
 = extern size_t regerror(int errcode, const regex_t *preg, char *errbuf, \
 =							size_t errbuf_size);
E 6
I 6
 = extern size_t regerror(int, const regex_t *, char *, size_t);
E 6
E 4
I 2
D 3
 = extern size_t regerror(int errcode, const regex_t *preg, char *errbuf, \
 =							size_t errbuf_size);
E 3
E 2
 */
/* ARGSUSED */
size_t
regerror(errcode, preg, errbuf, errbuf_size)
int errcode;
const regex_t *preg;
char *errbuf;
size_t errbuf_size;
{
	register struct rerr *r;
	register size_t len;
I 4
	register int target = errcode &~ REG_ITOA;
	register char *s;
	char convbuf[50];
E 4

D 4
	for (r = rerrs; r->code != 0; r++)
		if (r->code == errcode)
			break;
E 4
I 4
	if (errcode == REG_ATOI)
		s = regatoi(preg, convbuf);
	else {
		for (r = rerrs; r->code != 0; r++)
			if (r->code == target)
				break;
	
		if (errcode&REG_ITOA) {
			if (r->code != 0)
				(void) strcpy(convbuf, r->name);
			else
				sprintf(convbuf, "REG_0x%x", target);
			assert(strlen(convbuf) < sizeof(convbuf));
			s = convbuf;
		} else
			s = r->explain;
	}
E 4

D 4
	len = strlen(r->explain) + 1;
E 4
I 4
	len = strlen(s) + 1;
E 4
	if (errbuf_size > 0) {
		if (errbuf_size > len)
D 4
			(void) strcpy(errbuf, r->explain);
E 4
I 4
			(void) strcpy(errbuf, s);
E 4
		else {
D 4
			(void) strncpy(errbuf, r->explain, errbuf_size-1);
E 4
I 4
			(void) strncpy(errbuf, s, errbuf_size-1);
E 4
			errbuf[errbuf_size-1] = '\0';
		}
	}

	return(len);
}

D 2
#ifndef NDEBUG
E 2
I 2
D 4
#ifdef REDEBUG
E 4
E 2
/*
D 4
 - eprint - express an error number as a string
E 4
I 4
 - regatoi - internal routine to implement REG_ATOI
D 6
 = static char *regatoi(const regex_t *preg, char *localbuf);
E 6
I 6
 == static char *regatoi(const regex_t *preg, char *localbuf);
E 6
E 4
 */
D 4
char *
eprint(eno)
int eno;
E 4
I 4
static char *
regatoi(preg, localbuf)
const regex_t *preg;
char *localbuf;
E 4
{
	register struct rerr *r;
D 4
	static char eval[10];
E 4
I 4
	register size_t siz;
	register char *p;
E 4

	for (r = rerrs; r->code != 0; r++)
D 4
		if (r->code == eno)
			return(r->name);
	sprintf(eval, "#%d", r->code);
	return(eval);
}
E 4
I 4
		if (strcmp(r->name, preg->re_endp) == 0)
			break;
	if (r->code == 0)
		return("0");
E 4

D 4
/*
 - efind - find an error name
 */
int
efind(ename)
char *ename;
{
	register struct rerr *r;

	for (r = rerrs; r->code != 0; r++)
		if (strcmp(r->name, ename) == 0)
			return(r->code);
	return(0);		/* it'll do */
E 4
I 4
	sprintf(localbuf, "%d", r->code);
	return(localbuf);
E 4
}
D 4
#endif
E 4
E 1
