h20632
s 00002/00002/00116
d D 8.1 93/06/04 12:49:54 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00086/00073/00032
d D 6.6 91/04/19 14:50:20 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00104
d D 6.5 90/06/23 17:59:08 trent 6 5
c new copyright notice
e
s 00017/00005/00098
d D 6.4 89/02/14 16:57:24 bostic 5 4
c add Berkeley specific copyright
e
s 00003/00003/00100
d D 6.3 86/05/19 03:19:05 lepreau 4 3
c correct meaning of stayopen flag
e
s 00001/00001/00102
d D 6.2 86/05/09 21:57:38 lepreau 3 2
c p_proto and s_port are int, not long.
e
s 00001/00001/00102
d D 6.1 85/05/15 16:20:57 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00103/00000/00000
d D 5.1 85/05/15 16:20:50 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1983 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
E 5
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH GETPROTOENT 3N "9 February 1983"
E 2
I 2
D 5
.TH GETPROTOENT 3N "%Q%"
E 5
I 5
D 7
.TH GETPROTOENT 3 "%Q%"
E 5
E 2
.UC 5
.SH NAME
D 5
getprotoent, getprotobynumber, getprotobyname, setprotoent, endprotoent \- get protocol entry
E 5
I 5
getprotoent, getprotobynumber, getprotobyname, setprotoent,
endprotoent \- get protocol entry
E 5
.SH SYNOPSIS
.nf
.ft B
.B #include <netdb.h>
.PP
.ft B
struct protoent *getprotoent()
.PP
.ft B
struct protoent *getprotobyname(name)
char *name;
.PP
.ft B
struct protoent *getprotobynumber(proto)
int proto;
.PP
.ft B
setprotoent(stayopen)
int stayopen
.PP
.ft B
endprotoent()
.fi
.SH DESCRIPTION
.IR Getprotoent ,
.IR getprotobyname ,
E 7
I 7
.Dd %Q%
.Dt GETPROTOENT 3
.Os BSD 4.2
.Sh NAME
.Nm getprotoent ,
.Nm getprotobynumber ,
.Nm getprotobyname ,
.Nm setprotoent ,
.Nm endprotoent
.Nd get protocol entry
.Sh SYNOPSIS
.Fd #include <netdb.h>
.Ft struct protoent *
.Fn getprotoent 
.Ft struct protoent *
.Fn getprotobyname "char *name"
.Ft struct protoent *
.Fn getprotobynumber "int proto"
.Fn setprotoent "int stayopen"
.Fn endprotoent 
.Sh DESCRIPTION
The
.Fn getprotoent ,
.Fn getprotobyname ,
E 7
and
D 7
.I getprotobynumber
E 7
I 7
.Fn getprotobynumber
functions
E 7
each return a pointer to an object with the
following structure
containing the broken-out
fields of a line in the network protocol data base,
D 7
.IR /etc/protocols .
.RS
.PP
.nf
E 7
I 7
.Pa /etc/protocols .
.Bd -literal -offset indent
.Pp
E 7
struct	protoent {
	char	*p_name;	/* official name of protocol */
	char	**p_aliases;	/* alias list */
D 3
	long	p_proto;	/* protocol number */
E 3
I 3
	int	p_proto;	/* protocol number */
E 3
};
D 7
.ft R
.ad
.fi
.RE
.PP
E 7
I 7
.Ed
.Pp
E 7
The members of this structure are:
D 7
.TP \w'p_aliases'u+2n
p_name
E 7
I 7
.Bl -tag -width p_aliases
.It Fa p_name
E 7
The official name of the protocol.
D 7
.TP \w'p_aliases'u+2n
p_aliases
E 7
I 7
.It Fa p_aliases
E 7
A zero terminated list of alternate names for the protocol.
D 7
.TP \w'p_aliases'u+2n
p_proto
E 7
I 7
.It Fa p_proto
E 7
The protocol number.
D 7
.PP
.I Getprotoent
E 7
I 7
.El
.Pp
The
.Fn getprotoent
function
E 7
reads the next line of the file, opening the file if necessary.
D 7
.PP
.I Setprotoent
E 7
I 7
.Pp
The
.Fn setprotoent
function
E 7
opens and rewinds the file.  If the
D 7
.I stayopen
E 7
I 7
.Fa stayopen
E 7
flag is non-zero,
the net data base will not be closed after each call to 
D 4
.I getprotoent
(either directly, or indirectly through one of
the other \*(lqgetproto\*(rq calls).
E 4
I 4
D 7
.I getprotobyname
E 7
I 7
.Fn getprotobyname
E 7
or
D 7
.IR getprotobynumber .
E 4
.PP
.I Endprotoent
E 7
I 7
.Fn getprotobynumber .
.Pp
The
.Fn endprotoent
function
E 7
closes the file.
D 7
.PP
.I Getprotobyname
E 7
I 7
.Pp
The
.Fn getprotobyname
function
E 7
and
D 7
.I getprotobynumber
E 7
I 7
.Fn getprotobynumber
E 7
sequentially search from the beginning
of the file until a matching
protocol name or
protocol number is found,
D 7
or until EOF is encountered.
.SH FILES
/etc/protocols
.SH "SEE ALSO"
protocols(5)
.SH DIAGNOSTICS
E 7
I 7
or until
.Dv EOF
is encountered.
.Sh RETURN VALUES
E 7
Null pointer
D 7
(0) returned on EOF or error.
.SH BUGS
All information
is contained in a static area
so it must be copied if it is
to be saved.  Only the Internet
E 7
I 7
(0) returned on
.Dv EOF
or error.
.Sh FILES
.Bl -tag -width /etc/protocols -compact
.It Pa /etc/protocols
.El
.Sh SEE ALSO
.Xr protocols 5
.Sh HISTORY
The
.Fn getprotoent ,
.Fn getprotobynumber ,
.Fn getprotobyname ,
.Fn setprotoent ,
and
.Fn endprotoent
functions appeared in 
.Bx 4.2 .
.Sh BUGS
These functions use a static data space;
if the data is needed for future use, it should be
copied before any subsequent calls overwrite it.
Only the Internet
E 7
protocols are currently understood.
E 1
