h22145
s 00001/00001/00071
d D 8.3 94/05/20 14:50:03 mckusick 7 6
c cleanups to make run through groff
e
s 00004/00004/00068
d D 8.2 94/05/20 14:39:57 mckusick 6 5
c add comments
e
s 00000/00000/00072
d D 8.1 93/06/08 13:17:50 bostic 5 4
c 4.4BSD snapshot (revision 8.1)
e
s 00002/00000/00070
d D 6.2 91/04/17 12:51:12 bostic 4 3
c new copyright; att/bsd/shared
e
s 00000/00000/00070
d D 6.1 86/05/23 09:34:11 kjd 3 2
c document for 4.3BSD release
e
s 00000/00000/00070
d D 5.1 86/05/23 09:34:06 kjd 2 1
c document distributed with 4.2BSD
e
s 00070/00000/00000
d D 4.1 86/05/23 09:34:02 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 4
.\" %sccs.include.proprietary.roff%
.\"
E 4
I 1
.\"	%W% (Berkeley) %G%
.\"
.tr _\(em
.tr *\(**
.de UL
.if n .ul
.if n \\$3\\$1\\$2
.if t \\$3\f3\\$1\fP\\$2
..
.de UC
\\$3\s-1\\$1\s+1\\$2
..
.de C
.if n .ul
.if n \\$3\\$1\\$2
.if t \\$3\f3\\$1\fP\\$2
..
.de IT
.if t \\$3\f2\\$1\fP\\$2
.if n .ul
.if n \\$3\\$1\\$2
..
.de UI
\f3\\$1\fI\\$2\fR\\$3
..
.de P1
.if n .ls 1
.nf
D 7
.		use first argument as indent if present
E 7
I 7
.\"		use first argument as indent if present
E 7
.if \\n(.$ .DS I \\$1
.if !\\n(.$ .DS I 5
.ta .75i 1.5i 2.25i 3i 3.75i
.tr '\'
..
.de P2
.tr ''
.DE
.if n .ls 2
.lg
..
.if t .ds m \(mi
.if n .ds m -
.if t .ds n \(no
.if n .ds n -
.if t .ds s \v'.41m'\s+4*\s-4\v'-.41m'
.if n .ds s *
.if t .ds S \(sl
.if n .ds S /
.if t .ds d \s+4\&.\&\s-4
.if n .ds d \&.\&
.if t .ds a \z@@
.if n .ds a @
.hy 14
D 6
.	2=not last lines; 4= no -xx; 8=no xx-
E 6
I 6
.\"	2=not last lines; 4= no -xx; 8=no xx-
E 6
.de WS
.sp \\$1
..
D 6
.   ACCENTS  say \*'e or \*`e to get e acute or e grave
E 6
I 6
.\"   ACCENTS  say \*'e or \*`e to get e acute or e grave
E 6
.ds ' \h'\w'e'u*4/10'\z\(aa\h'-\w'e'u*4/10'
.ds e \o"e\'"
.ds ` \h'\w'e'u*4/10'\z\(ga\h'-\w'e'u*4/10'
D 6
.   UMLAUT  \*:u, etc.
E 6
I 6
.\"   UMLAUT  \*:u, etc.
E 6
.ds : \v'-0.6m'\h'(1u-(\\n(.fu%2u))*0.13m+0.06m'\z.\h'0.2m'\z.\h'-((1u-(\\n(.fu%2u))*0.13m+0.26m)'\v'0.6m'
D 6
.  TILDE and CIRCUMFLEX
E 6
I 6
.\"  TILDE and CIRCUMFLEX
E 6
.ds ^ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z^\h'|\\n:u'
.ds ~ \\k:\h'-\\n(.fu+1u/2u*2u+\\n(.fu-1u*0.13m+0.06m'\z~\h'|\\n:u'
.de BD
\&\\$3\f1\\$1\h\(ts-\w\(ts\\$1\(tsu+1u\(ts\\$1\fP\\$2\&
..
.hw semi-colon
E 1
