h07238
s 00002/00002/00117
d D 8.1 93/06/06 14:01:33 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00032/00039/00087
d D 6.7 91/05/09 16:54:11 cael 9 8
c mdoc version three
e
s 00002/00000/00124
d D 6.6 91/03/14 00:30:03 cael 8 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00124
d R 6.6 91/03/13 20:39:28 cael 7 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00097/00074/00027
d D 6.5 90/07/24 22:47:58 cael 6 5
c .Xr botch fix
e
s 00004/00014/00097
d D 6.4 90/06/24 19:10:33 cael 5 4
c converted man page
e
s 00000/00000/00111
d D 6.3 90/06/11 05:56:39 cael 4 3
c converted man page
e
s 00014/00003/00097
d D 6.2 88/09/29 09:32:24 bostic 3 2
c add Berkeley copyright notice
e
s 00001/00001/00099
d D 6.1 85/04/29 21:12:13 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00100/00000/00000
d D 5.1 85/04/29 21:11:57 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 5
.\" Copyright (c) 1983 The Regents of the University of California.
E 5
I 5
D 10
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
E 5
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
D 9
.\" %sccs.include.redist.man%
E 9
I 9
.\" %sccs.include.redist.roff%
E 9
E 5
E 3
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
I 8
D 9
.Vx
.Vx
E 9
E 8
D 2
.TH LPRM 1 "28 July 1983"
E 2
I 2
D 5
.TH LPRM 1 "%Q%"
E 5
I 5
D 6
.TH LPRM 1 "%Q"
E 5
E 2
.UC 5
.SH NAME
lprm \- remove jobs from the line printer spooling queue
.SH SYNOPSIS
.B lprm
[
.BI \-P printer
] [
.B \-
] [
job # ...
] [
user ...
]
.SH DESCRIPTION
.I Lprm
E 6
I 6
.Dd %Q%
.Dt LPRM 1
.Os BSD 4.2
.Sh NAME
.Nm lprm
.Nd remove jobs from the line printer spooling queue
.Sh SYNOPSIS
.Nm lprm
D 9
.Oo
.Op Fl P Ar printer
.Oo
E 9
I 9
.Op Fl P Ns Ar printer
E 9
.Op Fl
.Op job # ...
.Op Ar user ...
.Sh DESCRIPTION
.Nm Lprm
E 6
will remove a job, or jobs, from a printer's spool queue.
Since the spooling directory is protected from users, using
D 6
.I lprm
E 6
I 6
.Nm lprm
E 6
is normally the only method by which a user may remove a job.
D 6
.PP
.I Lprm
without any arguments will delete the currently active job if it is
owned by the user who invoked
.IR lprm .
.PP
If the
.B \-
flag is specified, 
.I lprm
will remove all jobs which a user
owns.  If the super-user employs this flag, the spool queue will
be emptied entirely. The owner is determined by the user's login name
E 6
I 6
The owner of a job is determined by the user's login name
E 6
and host name on the machine where the
D 6
.I lpr
E 6
I 6
.Xr lpr 1
E 6
command was invoked.
D 6
.PP
Specifying a user's name, or list of user names, will cause
.I lprm
E 6
I 6
.Pp
Options and arguments:
D 9
.Tw Fl
.Tc Fl P
.Ar printer
.Cx
E 9
I 9
.Bl -tag -width indent
.It Fl P Ns Ar printer
E 9
Specify the queue associated with a specific
.Ar printer
(otherwise the default printer is used).
D 9
.Tp Fl
E 9
I 9
.It Fl
E 9
If a single
.Sq Fl
is given,
.Nm lprm
will remove all jobs which a user
owns.  If the super-user employs this flag, the spool queue will
be emptied entirely.
D 9
.Tp Ar user
E 9
I 9
.It Ar user
E 9
Causes
.Nm lprm
E 6
to attempt to remove any jobs queued belonging to that user
(or users).  This form of invoking
D 6
.I lprm
E 6
I 6
.Nm lprm
E 6
is useful only to the super-user.
D 6
.PP
E 6
I 6
D 9
.Tp Ar job\ \&#
E 9
I 9
.It Ar job\ \&#
E 9
E 6
A user may dequeue an individual job by specifying its job number.
This number may be obtained from the
D 6
.IR lpq (1)
E 6
I 6
D 9
.Ar lpq  1
E 9
I 9
.Xr lpq  1
E 9
E 6
program, e.g.
D 6
.PP
.nf
.in +0.5i
.ta \w'k0-k9  'u +\w'Type  'u +\w'"/usr/lib/lpd"  'u
.ta \w'1st: 'u +\w'(standard input)      		'u
% lpq \-l
E 6
I 6
.Pp
D 9
.Ds I
.Cw \&a 1st:standard_input)
.Cl \&% lpq \-l
E 9
I 9
.Bd -literal -offset indent
\&% lpq \-l
E 9
E 6

D 6
1st: ken	[job #013ucbarpa]
	(standard input)	100 bytes
% lprm 13
.in -0.5i
.fi
.PP
.I Lprm
will announce the names of any files it removes and is silent if
E 6
I 6
D 9
.Cl 1st:ken\t\t[job #013ucbarpa]
.Cl \t(standard input)	100 bytes
.Cl % lprm 13
.Cw
.De
.Tp
E 9
I 9
1st:ken				[job #013ucbarpa]
	(standard input)	100 bytes
% lprm 13
.Ed
.El
E 9
.Pp
If neither arguments or options are given,
.Nm Lprm
will delete the currently active job if it is
owned by the user who invoked
.Nm lprm  .
.Pp
.Nm Lprm
announces the names of any files it removes and is silent if
E 6
there are no jobs in the queue which match the request list.
D 6
.PP
.I Lprm
E 6
I 6
.Pp
.Nm Lprm
E 6
will kill off an active daemon, if necessary, before removing
any spooling files.  If a daemon is killed, a new one is
automatically restarted upon completion of file removals.
D 6
.PP
The
.B \-P
option may be usd to specify the queue associated with a specific
printer (otherwise the default printer, or the value of the PRINTER
variable in the environment is used).
.SH FILES
.nf
.ta \w'/usr/spool/*/lock   'u
/etc/printcap	printer characteristics file
/usr/spool/*	spooling directories
/usr/spool/*/lock	lock file used to obtain the pid of the current
	daemon and the job number of the currently active job
.fi
.SH "SEE ALSO"
lpr(1),
lpq(1),
lpd(8)
.SH DIAGNOSTICS
E 6
I 6
.Sh ENVIRONMENT
D 9
The following environment variable exists, it is utilized by
E 9
I 9
If the following environment variable exists, it is utilized by
E 9
.Nm lprm .
D 9
.Tw Fl
.Tp Ev PRINTER
E 9
I 9
.Bl -tag -width PRINTER
.It Ev PRINTER
E 9
If the environment variable
.Ev PRINTER
exists,
and a printer has not been specified with the
.Fl P
option,
the default printer is assumed from 
.Ev PRINTER .
D 9
.Tp
E 9
I 9
.El
E 9
.Sh FILES
D 9
.Dw /var/spool/*/lock/
.Di L
.Dp Pa /etc/printcap
printer characteristics file
.Dp Pa /var/spool/*
spooling directories
.Dp Pa /var/spool/*/lock
lock file used to obtain the pid of the current
daemon and the job number of the currently active job
.Dp
E 9
I 9
.Bl -tag -width /var/spool/*/lock/ -compact
.It Pa /etc/printcap
Printer characteristics file.
.It Pa /var/spool/*
Spooling directories.
.It Pa /var/spool/*/lock
Lock file used to obtain the pid of the current
daemon and the job number of the currently active job.
.El
E 9
.Sh SEE ALSO
.Xr lpr 1 ,
.Xr lpq 1 ,
.Xr lpd 8
.Sh DIAGNOSTICS
E 6
``Permission denied" if the user tries to remove files other than his
own.
D 6
.SH BUGS
E 6
I 6
.Sh BUGS
E 6
Since there are race conditions possible in the update of the lock file,
the currently active job may be incorrectly identified.
I 6
.Sh HISTORY
D 9
.Nm Lprm
appeared in 3 BSD.
E 9
I 9
The
.Nm lprm
command appeared in
.Bx 3.0 .
E 9
E 6
E 1
