h22764
s 00001/00001/00062
d D 8.2 94/04/19 15:22:56 mckusick 3 2
c add architecture to Dt field
e
s 00002/00002/00061
d D 8.1 93/06/05 11:10:56 bostic 2 1
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00063/00000/00000
d D 5.1 92/07/09 18:25:34 torek 1 0
c date and time created 92/07/09 18:25:34 by torek
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1992 The Regents of the University of California.
.\" All rights reserved.
E 2
I 2
.\" Copyright (c) 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 2
.\"
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
D 3
.Dt REBOOT 8
E 3
I 3
.Dt REBOOT 8 sparc
E 3
.Os
.Sh NAME
.Nm reboot
.Nd
.Tn UNIX
bootstrapping procedures
.Sh SYNOPSIS
.Nm reboot
.Op Fl n
.Op Fl q
.Sh DESCRIPTION
.Sy Power fail and crash recovery.
Normally, the system will reboot itself at power-up or after crashes.
An automatic consistency check of the file systems will be performed
as described in
.Xr fsck 8 .
and unless this fails, the system will resume multi-user operations.
.Pp
.Sy Cold starts
The SPARC system currently uses the SunOS bootstrap loaders.
This will be changed in a future version of the system.
The SunOS boot will attempt to load
.Pa vmunix
from partition A of the boot device,
which must currently be an ``sd'' disk.
.Pp
The
.Op Fl s
flag to the SunOS boot loader will being the system up in single-user mode.
The
.Op Fl d
flag to the SunOS boot loader will bring the system up in debug mode.
Here it waits for a kernel debugger connect; see
.Xr kgdb 8 .
Other flags are currently ignored.
.Sh FILES
.Bl -tag -width /vmunixxx -compact
.It Pa /vmunix
system code
.It Pa /boot
system bootstrap
.El
.Sh SEE ALSO
.Xr crash 8 ,
.Xr disklabel 8 ,
.Xr fsck 8 ,
.Xr halt 8 ,
.Xr init 8 ,
.Xr rc 8 ,
.Xr shutdown 8 ,
.Xr syslogd 8
.Sh BUGS
The use of Sun disk labels, without the ability to write them,
is problematic.
E 1
