h26378
s 00045/00038/00014
d D 6.5 91/03/16 17:06:15 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00003/00013/00049
d D 6.4 90/06/24 21:36:21 trent 6 5
c new copyright & pathnames (halt & wtmp)
e
s 00015/00003/00047
d D 6.3 88/09/20 12:04:43 bostic 5 4
c Berkeley copyright
e
s 00012/00001/00038
d D 6.2 86/05/24 22:58:41 karels 4 3
c new logging
e
s 00001/00001/00038
d D 6.1 85/04/27 13:28:53 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00038
d D 5.1 85/04/27 13:28:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00039/00000/00000
d D 4.1 85/04/27 13:28:21 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1980 The Regents of the University of California.
E 7
I 7
.\" Copyright (c) 1980, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
E 5
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
I 5
D 7
.TH <PROGNAME> <SECTION> "%Q%"
E 5
D 2
.TH HALT 8 5/11/81
E 2
I 2
D 3
.TH HALT 8 "11 May 1981"
E 3
I 3
.TH HALT 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
halt \- stop the processor
.SH SYNOPSIS
D 6
.B /etc/halt
E 6
I 6
.B halt
E 6
[
.B \-n
]
[
.B \-q
]
[
.B \-y
]
.SH DESCRIPTION
.I Halt
E 7
I 7
.Dd %Q%
.Dt HALT 8
.Os BSD 4
.Sh NAME
.Nm halt
.Nd stop the processor
.Sh SYNOPSIS
.Nm halt
.Op Fl n
.Op Fl q
.Op Fl y
.Sh DESCRIPTION
.Nm Halt
E 7
writes out sandbagged information to the disks and then stops
the processor.  The machine does not reboot, even if the auto-reboot
switch is set on the console.
D 7
.PP
The
.B \-n
option prevents the sync before stopping.  The
.B \-q
option causes a quick halt, no graceful shutdown is attempted.  The
.B \-y
option is needed if you are trying to halt the system from a dialup.
I 4
.PP
.I Halt
E 7
I 7
.Pp
Available options for
.Nm halt :
.Bl -tag -width Ds
.It Fl n
No sync before stopping.
.It Fl q
Quick halt, no graceful shutdown is attempted.
.It Fl y
This option is needed if you are trying to halt the system from a dialup.
.El
.Pp
.Nm Halt
E 7
normally logs the shutdown using
D 7
.IR syslog (8)
E 7
I 7
.Xr syslog 8
E 7
and places a shutdown record in the login accounting file
D 6
/usr/adm/wtmp.
E 6
I 6
D 7
/var/log/wtmp.
E 7
I 7
.Pa /var/log/wtmp.
E 7
E 6
These actions are inhibited if the
D 7
.B \-n
E 7
I 7
.Fl n
E 7
or
D 7
.B \-q
E 7
I 7
.Fl q
E 7
options are present.
E 4
D 7
.SH SEE ALSO
D 4
reboot(8), shutdown(8)
E 4
I 4
reboot(8), shutdown(8), syslogd(8)
E 4
.SH BUGS
It is very difficult to halt a VAX, as the machine wants to then
E 7
I 7
.Sh SEE ALSO
.Xr reboot 8 ,
.Xr shutdown 8 ,
.Xr syslogd 8
.Sh BUGS
It is very difficult to halt a
.Tn VAX ,
as the machine wants to then
E 7
reboot itself.  A rather tight loop suffices.
I 7
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
E 7
E 1
