#! /bin/sh
#	MAKEDEV	1.2	86/07/29
#
# $Log:	MAKEDEV,v $
# Revision 1.3  90/04/09  16:46:16  kupfer
# Get permissions right for hd.
# 
# Revision 1.2  90/04/09  13:46:04  kupfer
# Fix up for i386s at ORC.
# 
#
# Device "make" file.  Valid arguments:
#	std	standard devices
#	local	configuration specific devices
# Tapes:
#	st*	1/4" streamer
#
# Disks:
#	hd*	esdi disk
#	sd*	scsi disk
#	fd*	5-1/4" floppy disk
#	f5*	5-1/4" floppy disk
#	fh*	3" floppy disk
#	f3*	3" floppy disk
#
# Terminal:
#	com
# Pseudo terminals:
#	pty*	set of 16 master and slave pseudo terminals
# Printers:
#	lpr
# Graphics/windows:
#
# Misc:
#	iopl	enable/disable '386 I/O privileges
######################################################################
umask 77
for i
do
case $i in

std)
        /etc/mknod console      c 1 0   ; chmod 622 console
        /etc/mknod tty          c 2 0   ; chmod 666 tty
        /etc/mknod mem          c 3 0   ; chmod 640 mem ; chgrp kmem mem
        /etc/mknod kmem         c 3 1   ; chmod 640 kmem ; chgrp kmem kmem
        /etc/mknod null         c 3 2   ; chmod 666 null
        /etc/mknod kbd          c 11 0  ; chmod 666 kbd
        /etc/mknod mouse        c 12 0  ; chmod 666 mouse
	/etc/mknod lpr0		c 20 0  ; chmod 666 lpr0
	/etc/mknod klog		c 22 0	; chmod 666 klog
        ;;


st*)
        umask 0 ; unit=`expr $i : '..\(.*\)'`
        case $i in
        st*) chr=6; blk=2 ;;
        esac
        case $unit in
        0|1|2|3)
		rew=$unit
		norew=`expr $rew + 4`
		eight=`expr $rew + 8`
                twelve=`expr $rew + 12`
                /etc/mknod rst$unit    c $chr $rew
		/etc/mknod rst$eight   c $chr $eight
                /etc/mknod nrst$unit   c $chr $norew
                /etc/mknod nrst$eight  c $chr $twelve
		/etc/mknod qt$unit     b $blk 0
                umask 77
                ;;
        *)
                echo "bad unit number in: $i; use qt0 thru qt3"
                ;;
        esac
        ;;

hd*)
        unit=`expr $i : '..\(.*\)'`
        case $i in
	hd*) name=hd; blk=0; chr=4;;
        esac
	/etc/mknod ${name}${unit}a      b $blk `expr $unit '*' 16 + 0`
	/etc/mknod ${name}${unit}b      b $blk `expr $unit '*' 16 + 1`
	/etc/mknod ${name}${unit}c      b $blk `expr $unit '*' 16 + 2`
	/etc/mknod ${name}${unit}d      b $blk `expr $unit '*' 16 + 3`
	/etc/mknod ${name}${unit}e      b $blk `expr $unit '*' 16 + 4`
	/etc/mknod ${name}${unit}f      b $blk `expr $unit '*' 16 + 5`
	/etc/mknod ${name}${unit}g      b $blk `expr $unit '*' 16 + 6`
	/etc/mknod ${name}${unit}h      b $blk `expr $unit '*' 16 + 7`

	/etc/mknod r${name}${unit}a     c $chr `expr $unit '*' 16 + 0`
	/etc/mknod r${name}${unit}b     c $chr `expr $unit '*' 16 + 1`
	/etc/mknod r${name}${unit}c     c $chr `expr $unit '*' 16 + 2`
	/etc/mknod r${name}${unit}d     c $chr `expr $unit '*' 16 + 3`
	/etc/mknod r${name}${unit}e     c $chr `expr $unit '*' 16 + 4`
	/etc/mknod r${name}${unit}f     c $chr `expr $unit '*' 16 + 5`
	/etc/mknod r${name}${unit}g     c $chr `expr $unit '*' 16 + 6`
	/etc/mknod r${name}${unit}h     c $chr `expr $unit '*' 16 + 7`
	chgrp operator ${name}${unit}[a-h] r${name}${unit}[a-h]
	chmod 640 ${name}${unit}[a-h] r${name}${unit}[a-h]
        ;;

sd*)
        unit=`expr $i : '..\(.*\)'`
        case $i in
	sd*) name=sd; blk=3; chr=23;;
        esac
	/etc/mknod ${name}${unit}a      b $blk `expr $unit '*' 16 + 0`
	/etc/mknod ${name}${unit}b      b $blk `expr $unit '*' 16 + 1`
	/etc/mknod ${name}${unit}c      b $blk `expr $unit '*' 16 + 2`
	/etc/mknod ${name}${unit}d      b $blk `expr $unit '*' 16 + 3`
	/etc/mknod ${name}${unit}e      b $blk `expr $unit '*' 16 + 4`
	/etc/mknod ${name}${unit}f      b $blk `expr $unit '*' 16 + 5`
	/etc/mknod ${name}${unit}g      b $blk `expr $unit '*' 16 + 6`
	/etc/mknod ${name}${unit}h      b $blk `expr $unit '*' 16 + 7`

	/etc/mknod r${name}${unit}a     c $chr `expr $unit '*' 16 + 0`
	/etc/mknod r${name}${unit}b     c $chr `expr $unit '*' 16 + 1`
	/etc/mknod r${name}${unit}c     c $chr `expr $unit '*' 16 + 2`
	/etc/mknod r${name}${unit}d     c $chr `expr $unit '*' 16 + 3`
	/etc/mknod r${name}${unit}e     c $chr `expr $unit '*' 16 + 4`
	/etc/mknod r${name}${unit}f     c $chr `expr $unit '*' 16 + 5`
	/etc/mknod r${name}${unit}g     c $chr `expr $unit '*' 16 + 6`
	/etc/mknod r${name}${unit}h     c $chr `expr $unit '*' 16 + 7`
	chgrp operator ${name}${unit}[a-h] r${name}${unit}[a-h]
	chmod 640 ${name}${unit}[a-h] r${name}${unit}[a-h]
        ;;

fd*|fh*|f5*|f3*)
        unit=`expr $i : '..\(.*\)'`
        case $i in
		fd*|f5*) name=fd; blk=1; chr=5; minor=3;;
		fh*|f3*) name=fd; blk=1; chr=5; minor=1;;
        esac
	/etc/mknod ${name}${unit} b $blk  `expr $unit '*' 64 + $minor`
	/etc/mknod r${name}${unit} c $chr `expr $unit '*' 64 + $minor`
	chmod 666 ${name}${unit} r${name}${unit}
	case $unit in
		0)
		  /etc/mknod floppy b $blk  `expr $unit '*' 64 + $minor`
		  /etc/mknod rfloppy c $chr `expr $unit '*' 64 + $minor` 
		  chmod 666 floppy rfloppy;;
		1)
		  /etc/mknod floppyb b $blk  `expr $unit '*' 64 + $minor`
		  /etc/mknod rfloppyb c $chr `expr $unit '*' 64 + $minor`
		  chmod 666 floppyb rfloppyb;;
	esac
	;;

ttys)
	/etc/mknod ttys0 c 13 0
	/etc/mknod ttys1 c 13 1
	;;


iopl)
	/etc/mknod iopl c 16 0
	;;

com*)	/etc/mknod com0 c 0 0
	/etc/mknod com1 c 0 1
	/etc/mknod com2 c 0 2
	;;

lpr*)	/etc/mknod lpr0 c 20 0
	;;

log)
	/etc/mknod klog	c 22 0
	chmod 600 klog
	;;

pty*)
        class=`expr $i : 'pty\(.*\)'`
        case $class in
        0) offset=0 name=p;;
        1) offset=16 name=q;;
        2) offset=32 name=r;;
        *) echo "bad unit for pty in: $i; use pty0 thru pty2";;
        esac
        case $class in
        0|1|2)
                umask 0
                eval `echo $offset $name | awk ' { b=$1; n=$2 } END {
                        for (i = 0; i < 16; i++)
                                printf("/etc/mknod tty%s%x c 9 %d; \
                                        /etc/mknod pty%s%x c 10 %d; ", \
                                        n, i, b+i, n, i, b+i); }'`
                umask 77
                ;;
        esac
        ;;

local)
	sh MAKEDEV.local
	;;

*)
	echo "I don't know how to MAKEDEV $i."
	;;
esac
done
