.TH Dhar 1 local
.SH NAME
dhar, d202, daps, dcan \- phototypesetter filters
.SH SYNOPSIS
.BR dhar
[ option ] ... [ file ] ...
.SH DESCRIPTION
.I dhar
and its companions
print
.I files
created by
.IR ditroff (1)
on a Harris 7400 phototypesetter
a Mergenthaler Linotron 202 phototypesetter,
an Autologic APS-5 phototypesetter,
and an Imagen Canon LBP-10 laser printer respectively.
If no
.I file
is mentioned, the standard input is printed.
Dhar will on the moment write to a file called
.I har.in
in the current directory.
This file should be processed by
.IR harprot (1)
The following options are understood.
.TP
.B \-b
Report whether the typesetter is busy; do not print.
(Not for
.IR dhar ) 
.TP
.BI \-o list
Print pages whose numbers are given in the comma-separated
.IR list .
The list contains single numbers
.I N
and ranges
.IB N1 \- N2.
A missing 
.I N1
means the lowest-numbered page, a missing
.I N2
means the highest.
.TP
.BI \-s n
Stop after every 
.I n
pages of output.
Proceed when the RUN button is pushed on the typesetter.
(For
.I d202
only.)
.TP
.B \-t
Direct output to the standard output instead of the typesetter.
.TP
.B \-w
Wait for typesetter to become free, then print.
(Not for
.IR dhar )
.TP
directory
.BI \-f " dir"
Take font information from
.I dir
instead of the default.
.PP
The
.I files
for
.I dhar
.I d202
and
.I daps
should be prepared under the corresponding
.B \-Thar
.B \-T202
or
.B \-Taps
option of
.IR troff ;
.B dcan
is intended as a typesetter simulator, and can cope with anything.
.SH FILES
/usr/lib/font/devhar/*	Harris description
/usr/lib/font/dev202/*	202 description files
/usr/lib/font/devAPS/*	aps-5 description files
/usr/lib/font/devcan/*	Canon description and raster character files
.SH SEE ALSO
troff(1), tc(1),
harprot(1)
.SH REMARKS
The current version of dhar is highly experimental.
.br
D202, daps and dcan are not supported, the output devices are not available.
.br
Dver, (for the versatec) is under construction.
