h19724
s 00173/00198/00007
d D 8.2 94/05/20 15:42:53 mckusick 5 4
c format for typesetting
e
s 00002/00002/00203
d D 8.1 93/06/08 13:22:17 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00003/00201
d D 6.2 91/04/17 13:14:56 bostic 3 2
c new copyright; att/bsd/shared
e
s 00000/00000/00204
d D 6.1 86/06/02 16:28:19 mckusick 2 1
c 4.3BSD beta release document
e
s 00204/00000/00000
d D 5.1 86/06/02 16:28:04 mckusick 1 0
c document distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 4
.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1983, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" %sccs.include.redist.roff%
E 3
.\"
.\"	%W% (Berkeley) %G%
.\"
D 5






			COMMENTED REFER MACROS




.	\" refer macros for citations
.de []
.][ \\$1				# mysterious synonym for .][
..
.de ][					# changes .][ according to argument
.if \\$1>4 .tm %M undefined (Bell Labs) # no macros defined above [4
.[\\$1					# call one of the macros below
..
.if \n(.V>19 .ds [. \f1[		# open bracket for nroff
.if \n(.V<20 .ds [. \f1\s-2\v'-0.4m'	# superscripting for troff/daisy-wheel
.if \n(.V>19 .ds .] ]\fP		# close bracket for nroff
.if \n(.V<20 .ds .] \v'0.4m'\s+2\fP	# end troff/daisy-wheel superscripting
.if n .ds [o \&"			# open quote for nroff
.if n .ds [c \&"			# close quote for nroff
.if t .ds [o ``				# open quote for troff
.if t .ds [c ''				# close quote for troff
.ds <. .				# period before citation number
.ds <, ,				# comma before citation number
.	\" [0 - other type of citation
.de [0
.FS					# start -ms footnote
.nr [: 0				# has anything been printed?
.if !"\\*([F"" .FP \\*([F		# number for footnote paragraph
.if !"\\*([Q"" \{\
.nr [: 1				# if there's a corporate author,
\\*([Q\c				# set [: to 1 and print [Q
.\}
.if !"\\*([A"" \{\			# if there's an author,
.nr [: 1				# set [: to 1,
\\*([A\c				# print the author and continue 
.\}
.if !"\\*([T"" \{\			# if there's a title,
.if \\n([:>0 ,				# print comma if there was author,
.nr [: 1				# set [: to 1,
\f2\\*([T\f1\c				# and print the title in italics
.\}
.if !"\\*([S"" , \\*([S\c		# series title, not in italics
.if !"\\*([V"" , \\*([V\c		# if there's a volume, print it
.if !"\\*([P"" \{\
.ie \\n([P>0 , pp. \\*([P\c		# if multiple pages, use pp.
.el , p. \\*([P\c			# if only one page, use p.
.\}
.if !"\\*([C"" , \\*([C\c		# if there's a city, print it
.if !"\\*([D"" , \\*([D\c		# if there's a date, print it
.if \\n([:>0 \&.			# if [Q [A or [T, print period
.if !"\\*([O"" \\*([O			# print the other field if present
.FE					# end -ms footnote
..










.de [1	\" [1 - journal article
.FS					# start -ms footnote
.if !"\\*([F"" .FP \\*([F		# number for footnote paragraph
.if !"\\*([Q"" \\*([Q,			# if corporate author, print it
.if !"\\*([A"" \\*([A,			# if author, print with comma
.if !"\\*([T"" \\*([o\\*([T,\\*([c	# if title, print with quotes
\f2\\*([J\f1\c				# always a journal, in italics
.if !"\\*([V"" , vol. \\*([V\c		# if volume, print after "vol."
.if !"\\*([N"" , no. \\*([N\c		# if number, print after "no."
.if !"\\*([P"" \{\
.ie \\n([P>0 , pp. \\*([P\c		# if multiple pages, use pp.
.el , p. \\*([P\c			# if only one page, use p.
.\}
.if !"\\*([I"" , \\*([I\c		# if there's a publisher, print it
.if !"\\*([C"" , \\*([C\c		# if there's a city, print it
.if !"\\*([D"" , \\*([D\c		# if there's a date, print it
\&.					# end reference with period
.if !"\\*([O"" \\*([O			# if other information, print it
.FE					# end -ms footnote
..
.de [2	\" [2 - book
.FS					# start -ms footnote
.if !"\\*([F"" .FP \\*([F		# number for footnote paragraph
.if !"\\*([Q"" \\*([Q,			# if corporate author, print it
.if !"\\*([A"" \\*([A,			# if author, print with comma
.if !"\\*([T"" \f2\\*([T,\f1		# title and comma in italics
.if !"\\*([S"" \\*([S,			# series title, not in italics
.if !"\\*([V"" \\*([V,			# perhaps [V says "4 vols."
.if !"\\*([P"" \{\
.ie \\n([P>0 pp. \\*([P,		# if multiple pages, use pp.
.el p. \\*([P,				# if only one page, use p.
.\}
\\*([I\c				# always a publisher with book
.if !"\\*([C"" , \\*([C\c		# if there's a city, print it
.if !"\\*([D"" , \\*([D\c		# if there's a date, print it
\&.					# end reference with period
.if !"\\*([O"" \\*([O			# if other information, print it
.FE					# end -ms footnote
..
.de [3	\" [3 - article in book
.FS					# start -ms footnote
.if !"\\*([F"" .FP \\*([F		# number for footnote paragraph
.if !"\\*([Q"" \\*([Q,			# if corporate author, print it
.if !"\\*([A"" \\*([A,			# if author, print with comma
.if !"\\*([T"" \\*([o\\*([T,\\*([c	# title and comma in quotes
in \f2\\*([B\f1\c			# always "in" book, italicized
.if !"\\*([E"" , ed. \\*([E\c		# if an editor, should follow book
.if !"\\*([S"" , \\*([S\c		# series title, not in italics
.if !"\\*([V"" , vol. \\*([V\c		# if volume, print after "vol."
.if !"\\*([P"" \{\
.ie \\n([P>0 , pp. \\*([P\c		# if multiple pages, use pp.
.el , p. \\*([P\c			# if only one page, use p.
.\}
.if !"\\*([I"" , \\*([I\c		# if there's a publisher, print it
.if !"\\*([C"" , \\*([C\c		# if there's a city, print it
.if !"\\*([D"" , \\*([D\c		# if there's a date, print it
\&.					# end reference with period
.if !"\\*([O"" \\*([O			# if other information, print it
.FE					# end -ms footnote
..








.	\" [4 - report
.de [4
.FS					# start -ms footnote
.if !"\\*([F"" .FP \\*([F		# number for footnote paragraph
.if !"\\*([Q"" \\*([Q,			# if corporate author, print it
.if !"\\*([A"" \\*([A,			# if author, print with comma
.if !"\\*([T"" \\*([o\\*([T,\\*([c	# title and comma in quotes
.if !"\\*([R"" \\*([R\c			# if a report number, print it
.if !"\\*([G"" \& (\\*([G)\c		# put [G string in parentheses
.if !"\\*([P"" \{\
.ie \\n([P>0 , pp. \\*([P\c		# if multiple pages, use pp.
.el , p. \\*([P\c			# if only one page, use p.
.\}
.if !"\\*([I"" , \\*([I\c		# if there's a publisher, print it
.if !"\\*([C"" , \\*([C\c		# if there's a city, print it
.if !"\\*([D"" , \\*([D\c		# if there's a date, print it
\&.					# end reference with period
.if !"\\*([O"" \\*([O			# if other information, print it
.FE					# end -ms footnote
..
.de ]<					# mysterious synonym for [<
.[<
..
.de [<					# For footnotes at end of text,
.SH					# with the -e or -s $LIST$ options.
References				# Print References section heading.
.LP					# Initialize; IP references printed,
.rn IP FP				# because FP is replaced by IP,
.rm FS FE				# and footnote macros are removed.
..
.de [>					# mysterious synonym for ]>
.]>
..
.de ]>					# with the -e or -s $LIST$ options,
.sp					# put a space between references
..
.de ]-					# mysterious synonym for [-
.[-
..
.de [-					# Appears at start of references,
.rm [Q [A [T [J [B [E [S [V		# to remove old string definitions--
.rm [N [P [I [C [D [O [R [G		# if you add new field strings,
..					# they should be removed as well.
.de ]]
.\" circumvent EOF bug in troff		# mysterious fix for .MC output
..






Note:	the double quotes in string comparisons are in fact control-g
	characters; this allows fields to contain double quotes.







E 5
I 5
.SH
Commented Refer Macros
.XS
Commented Refer Macros
.XE
.nf
\f(CW
.TS
l l.
\&.\e" refer macros for citations
\&.de []
\&.][ \e\e$1	# mysterious synonym for .][
\&..
\&.de ][	# changes .][ according to argument
\&.if \e\e$1>4 .tm %M undefined (Bell Labs)	# no macros defined above [4
\&.[\e\e$1	# call one of the macros below
\&..
\&.if \en(.V>19 .ds [. \ef1[	# open bracket for nroff
\&.if \en(.V<20 .ds [. \ef1\es-2\ev'-0.4m'	# superscripting for troff/daisy-wheel
\&.if \en(.V>19 .ds .] ]\efP	# close bracket for nroff
\&.if \en(.V<20 .ds .] \ev'0.4m'\es+2\efP	# end troff/daisy-wheel superscripting
\&.if n .ds [o \e&"	# open quote for nroff
\&.if n .ds [c \e&"	# close quote for nroff
\&.if t .ds [o ``	# open quote for troff
\&.if t .ds [c ''	# close quote for troff
\&.ds <. .	# period before citation number
\&.ds <, ,	# comma before citation number
\&.\e" [0 - other type of citation
\&.de [0
\&.FS	# start -ms footnote
\&.nr [: 0	# has anything been printed?
\&.if !"\e\e*([F"" .FP \e\e*([F	# number for footnote paragraph
\&.if !"\e\e*([Q"" \e{\e
\&.nr [: 1	# if there's a corporate author,
\&\e\e*([Q\ec	# set [: to 1 and print [Q
\&.\e}
\&.if !"\e\e*([A"" \e{\e	# if there's an author,
\&.nr [: 1	# set [: to 1,
\&\e\e*([A\ec	# print the author and continue 
\&.\e}
\&.if !"\e\e*([T"" \e{\e	# if there's a title,
\&.if \e\en([:>0 ,	# print comma if there was author,
\&.nr [: 1	# set [: to 1,
\&\ef2\e\e*([T\ef1\ec	# and print the title in italics
\&.\e}
\&.if !"\e\e*([S"" , \e\e*([S\ec	# series title, not in italics
\&.if !"\e\e*([V"" , \e\e*([V\ec	# if there's a volume, print it
\&.if !"\e\e*([P"" \e{\e
\&.ie \e\en([P>0 , pp. \e\e*([P\ec	# if multiple pages, use pp.
\&.el , p. \e\e*([P\ec	# if only one page, use p.
\&.\e}
\&.if !"\e\e*([C"" , \e\e*([C\ec	# if there's a city, print it
\&.if !"\e\e*([D"" , \e\e*([D\ec	# if there's a date, print it
\&.if \e\en([:>0 \e&.	# if [Q [A or [T, print period
\&.if !"\e\e*([O"" \e\e*([O	# print the other field if present
\&.FE	# end -ms footnote
\&..
\&.\e" [1 - journal article
\&.de [1
\&.FS	# start -ms footnote
\&.if !"\e\e*([F"" .FP \e\e*([F	# number for footnote paragraph
\&.if !"\e\e*([Q"" \e\e*([Q,	# if corporate author, print it
\&.if !"\e\e*([A"" \e\e*([A,	# if author, print with comma
\&.if !"\e\e*([T"" \e\e*([o\e\e*([T,\e\e*([c	# if title, print with quotes
\&\ef2\e\e*([J\ef1\ec	# always a journal, in italics
\&.if !"\e\e*([V"" , vol. \e\e*([V\ec	# if volume, print after "vol."
\&.if !"\e\e*([N"" , no. \e\e*([N\ec	# if number, print after "no."
\&.if !"\e\e*([P"" \e{\e
\&.ie \e\en([P>0 , pp. \e\e*([P\ec	# if multiple pages, use pp.
\&.el , p. \e\e*([P\ec	# if only one page, use p.
\&.\e}
\&.if !"\e\e*([I"" , \e\e*([I\ec	# if there's a publisher, print it
\&.if !"\e\e*([C"" , \e\e*([C\ec	# if there's a city, print it
\&.if !"\e\e*([D"" , \e\e*([D\ec	# if there's a date, print it
\&\e&.	# end reference with period
\&.if !"\e\e*([O"" \e\e*([O	# if other information, print it
\&.FE	# end -ms footnote
\&..
\&.\e" [2 - book
\&.de [2
\&.FS	# start -ms footnote
\&.if !"\e\e*([F"" .FP \e\e*([F	# number for footnote paragraph
\&.if !"\e\e*([Q"" \e\e*([Q,	# if corporate author, print it
\&.if !"\e\e*([A"" \e\e*([A,	# if author, print with comma
\&.if !"\e\e*([T"" \ef2\e\e*([T,\ef1	# title and comma in italics
\&.if !"\e\e*([S"" \e\e*([S,	# series title, not in italics
\&.if !"\e\e*([V"" \e\e*([V,	# perhaps [V says "4 vols."
\&.if !"\e\e*([P"" \e{\e
\&.ie \e\en([P>0 pp. \e\e*([P,	# if multiple pages, use pp.
\&.el p. \e\e*([P,	# if only one page, use p.
\&.\e}
\&\e\e*([I\ec	# always a publisher with book
\&.if !"\e\e*([C"" , \e\e*([C\ec	# if there's a city, print it
\&.if !"\e\e*([D"" , \e\e*([D\ec	# if there's a date, print it
\&\e&.	# end reference with period
\&.if !"\e\e*([O"" \e\e*([O	# if other information, print it
\&.FE	# end -ms footnote
\&..
\&.\e" [3 - article in book
\&.de [3
\&.FS	# start -ms footnote
\&.if !"\e\e*([F"" .FP \e\e*([F	# number for footnote paragraph
\&.if !"\e\e*([Q"" \e\e*([Q,	# if corporate author, print it
\&.if !"\e\e*([A"" \e\e*([A,	# if author, print with comma
\&.if !"\e\e*([T"" \e\e*([o\e\e*([T,\e\e*([c	# title and comma in quotes
\&in \ef2\e\e*([B\ef1\ec	# always "in" book, italicized
\&.if !"\e\e*([E"" , ed. \e\e*([E\ec	# if an editor, should follow book
\&.if !"\e\e*([S"" , \e\e*([S\ec	# series title, not in italics
\&.if !"\e\e*([V"" , vol. \e\e*([V\ec	# if volume, print after "vol."
\&.if !"\e\e*([P"" \e{\e
\&.ie \e\en([P>0 , pp. \e\e*([P\ec	# if multiple pages, use pp.
\&.el , p. \e\e*([P\ec	# if only one page, use p.
\&.\e}
\&.if !"\e\e*([I"" , \e\e*([I\ec	# if there's a publisher, print it
\&.if !"\e\e*([C"" , \e\e*([C\ec	# if there's a city, print it
\&.if !"\e\e*([D"" , \e\e*([D\ec	# if there's a date, print it
\&\e&.	# end reference with period
\&.if !"\e\e*([O"" \e\e*([O	# if other information, print it
\&.FE	# end -ms footnote
\&..
\&.\e" [4 - report
\&.de [4
\&.FS	# start -ms footnote
\&.if !"\e\e*([F"" .FP \e\e*([F	# number for footnote paragraph
\&.if !"\e\e*([Q"" \e\e*([Q,	# if corporate author, print it
\&.if !"\e\e*([A"" \e\e*([A,	# if author, print with comma
\&.if !"\e\e*([T"" \e\e*([o\e\e*([T,\e\e*([c	# title and comma in quotes
\&.if !"\e\e*([R"" \e\e*([R\ec	# if a report number, print it
\&.if !"\e\e*([G"" \e& (\e\e*([G)\ec	# put [G string in parentheses
\&.if !"\e\e*([P"" \e{\e
\&.ie \e\en([P>0 , pp. \e\e*([P\ec	# if multiple pages, use pp.
\&.el , p. \e\e*([P\ec	# if only one page, use p.
\&.\e}
\&.if !"\e\e*([I"" , \e\e*([I\ec	# if there's a publisher, print it
\&.if !"\e\e*([C"" , \e\e*([C\ec	# if there's a city, print it
\&.if !"\e\e*([D"" , \e\e*([D\ec	# if there's a date, print it
\&\e&.	# end reference with period
\&.if !"\e\e*([O"" \e\e*([O	# if other information, print it
\&.FE	# end -ms footnote
\&..
\&.de ]<	# mysterious synonym for [<
\&.[<
\&..
\&.de [<	# For footnotes at end of text,
\&.SH	# with the -e or -s $LIST$ options.
\&References	# Print References section heading.
\&.LP	# Initialize; IP references printed,
\&.rn IP FP	# because FP is replaced by IP,
\&.rm FS FE	# and footnote macros are removed.
\&..
\&.de [>	# mysterious synonym for ]>
\&.]>
\&..
\&.de ]>	# with the -e or -s $LIST$ options,
\&.sp	# put a space between references
\&..
\&.de ]-	# mysterious synonym for [-
\&.[-
\&..
\&.de [-	# Appears at start of references,
\&.rm [Q [A [T [J [B [E [S [V	# to remove old string definitions--
\&.rm [N [P [I [C [D [O [R [G	# if you add new field strings,
\&..	# they should be removed as well.
\&.de ]]
\&.\e" circumvent EOF bug in troff	# mysterious fix for .MC output
\&..
.TE
.sp -1
.LP
Note that the double quotes in string comparisons are in fact control-g
characters; this allows fields to contain double quotes.
.nr LL 6i
.TC
E 5
E 1
