h23140
s 00002/00002/00133
d D 8.1 93/06/06 22:28:17 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00074/00061/00061
d D 5.7 92/07/23 10:22:22 bostic 8 7
c update from Cael
e
s 00014/00027/00108
d D 5.6 92/07/20 14:37:46 bostic 7 6
c mostly fix exit status, plus vfork(2) doesn't currently share
c the address space.  Probably still not quite right
e
s 00002/00001/00133
d D 5.5 91/06/27 17:26:56 bostic 6 5
c add POSIX/IEEE contribution notice
e
s 00066/00032/00068
d D 5.4 91/04/27 13:11:58 bostic 5 4
c increase default -n to 5000; add SVID/POSIX -x flag; redo allocation
c and -s flag to be POSIX compliant; bug fix to make "noinvoke" volatile;
c add err() routine for error messages
e
s 00014/00012/00086
d D 5.3 91/04/27 09:57:54 bostic 4 3
c minor consistency changes for -f flag
e
s 00010/00001/00088
d D 5.2 91/03/05 16:41:44 donn 3 1
c Document the -f flag (force xargs to ignore status).
e
s 00010/00001/00088
d R 5.2 91/03/05 16:41:04 donn 2 1
c 
e
s 00089/00000/00000
d D 5.1 90/04/17 21:22:11 bostic 1 0
c date and time created 90/04/17 21:22:11 by bostic
e
u
U
t
T
I 1
D 8
.\" Copyright (c) 1990 The Regents of the University of California.
E 8
I 8
D 9
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 8
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
.\" This code is derived from software contributed to Berkeley by
D 6
.\" John B. Roll Jr.
E 6
I 6
.\" John B. Roll Jr. and the Institute of Electrical and Electronics
.\" Engineers, Inc.
E 6
.\"
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
.\"
.\"	%W% (Berkeley) %G%
.\"
D 8
.TH XARGS 1 "%Q%"
.UC 7
.SH NAME
xargs \- construct argument list(s) and execute utility.
.SH SYNOPSIS
.ft B
D 3
xargs [\-t] [\-n number] [\-s size] [utility [argument ...]]
E 3
I 3
D 4
xargs [\-t] [\-f] [\-n number] [\-s size] [utility [argument ...]]
E 4
I 4
D 5
xargs [\-ft] [\-n number] [\-s size] [utility [argument ...]]
E 5
I 5
D 7
xargs [\-ft] [[\-x] \-n number] [\-s size] [utility [argument ...]]
E 7
I 7
xargs [\-t] [[\-x] \-n number] [\-s size] [utility [arg ...]]
E 7
E 5
E 4
E 3
.ft R
.SH DESCRIPTION
E 8
I 8
.Dd %Q%
.Dt XARGS 1
.Os
.Sh NAME
.Nm xargs
.Nd "construct argument list(s) and execute utility"
.Sh SYNOPSIS
.Nm xargs
.Op Fl t
.Oo Op Fl x
.Fl n Ar number
.Oc
.Op Fl s Ar size
.Op Ar utility Op Ar arguments ...
.Sh DESCRIPTION
E 8
The
D 5
.I xargs utility
reads space, tab, and newline delimited arguments from the standard
input and executes the specified
E 5
I 5
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
utility reads space, tab, newline and end-of-file delimited arguments
from the standard input and executes the specified
E 5
D 8
.I utility
with them as arguments.
D 4
Any arguments specified on the command line are given to the
E 4
I 4
.PP
E 8
I 8
.Ar utility
with them as
arguments.
.Pp
E 8
The utility and any arguments specified on the command line are given
to the
E 4
D 8
.I utility
E 8
I 8
.Ar utility
E 8
upon each invocation, followed by some number of the arguments read
from standard input.
The
D 8
.I utility
E 8
I 8
.Ar utility
E 8
is repeatedly executed until standard input is exhausted.
D 8
.PP
D 5
Spaces and tabs may be embedded in arguments using single (`` ' '') or
double (``"'') quotes or backslashes (``\e'').
Single or double quotes escape all characters to the next matching quote
character, backslashes escape the next character.
Newlines may not be escaped.
E 5
I 5
Spaces, tabs and newlines may be embedded in arguments using single (`` ' '')
E 8
I 8
.Pp
Spaces, tabs and newlines may be embedded in arguments using single
(``\ '\ '')
.Ek
E 8
or double (``"'') quotes or backslashes (``\e'').
Single quotes escape all non-single quote characters, excluding newlines,
up to the matching single quote.
Double quotes escape all non-double quote characters, excluding newlines,
up to the matching double quote.
Any single character, including newlines, may be escaped by a backslash.
E 5
D 8
.PP
E 8
I 8
.Pp
E 8
D 4
The following options are available:
E 4
I 4
The options are as follows:
E 4
D 8
.TP
I 4
D 5
-f
E 5
I 5
D 7
\-f
E 5
Force
.I xargs
to ignore the exit status returned by
.IR utility .
D 5
Normally a nonzero exit status will cause
E 5
I 5
By default,
E 5
.I xargs
D 5
to exit immediately with an error status.
E 5
I 5
will exit immediately if
.I utility
exits with a non-zero exit status.
This does not include ignoring
.I utility
exiting due to a signal or without calling
.IR exit (2).
E 5
.TP
E 7
E 4
D 5
-n number
Set the maximum number of arguments used from standard input for
each invocation of the utility.
E 5
I 5
\-n number
E 8
I 8
.Bl -tag -width indent
.It Fl n Ar number
E 8
Set the maximum number of arguments taken from standard input for each
invocation of the utility.
E 5
An invocation of
D 8
.I utility
E 8
I 8
.Ar utility
E 8
will use less than
D 8
.I number
E 8
I 8
.Ar number
E 8
standard input arguments if the number of bytes accumulated (see the
D 8
.I \-s
E 8
I 8
.Fl s
E 8
D 5
option) exceeds the specified size or the last invocation of
.I utility
has fewer than
E 5
I 5
option) exceeds the specified
D 8
.I size
E 8
I 8
.Ar size
E 8
or there are fewer than
E 5
D 8
.I number
E 8
I 8
.Ar number
E 8
D 5
arguments remaining.
The default value for
E 5
I 5
arguments remaining for the last invocation of
D 8
.IR utility .
E 8
I 8
.Ar utility .
E 8
The current default value for
E 5
D 8
.I number
E 8
I 8
.Ar number
E 8
D 5
is 255.
E 5
I 5
is 5000.
E 5
D 8
.TP
D 5
-s size
Set the maximum number of bytes to which the last component of the
E 5
I 5
\-s size
E 8
I 8
.It Fl s Ar size
E 8
Set the maximum number of bytes for the command line length provided to
D 8
.IR utility .
E 8
I 8
.Ar utility .
E 8
The sum of the length of the utility name and the arguments passed to
E 5
D 8
.I utility
D 5
name, the command-line arguments, and the arguments read in from
standard input may sum.
The default value for
E 5
I 5
(including NULL terminators) will be less than or equal to this number.
E 8
I 8
.Ar utility
(including
.Dv NULL
terminators) will be less than or equal to this number.
E 8
The current default value for
E 5
D 8
.I size
D 5
is 2048.
E 5
I 5
is ARG_MAX - 2048.
E 5
.TP
D 5
-t
E 5
I 5
\-t
E 8
I 8
.Ar size
is
.Dv ARG_MAX
- 2048.
.It Fl t
E 8
E 5
Echo the command to be executed to standard error immediately before it
is executed.
I 5
D 8
.TP
\-x
E 8
I 8
.It Fl x
E 8
Force
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
to terminate immediately if a command line containing
D 8
.I number
E 8
I 8
.Ar number
E 8
arguments will not fit in the specified (or default) command line length.
E 5
I 3
D 4
.TP
-f
Force
.I xargs
to ignore the exit status returned by
.IR utility .
Normally a nonzero exit status will cause
.I xargs
to exit with status 1.
E 4
E 3
D 8
.PP
E 8
I 8
.El
.Pp
E 8
If no
D 8
.I utility
E 8
I 8
.Ar utility
E 8
is specified,
D 8
.IR echo (1)
E 8
I 8
.Xr echo 1
E 8
is used.
D 8
.PP
E 8
I 8
.Pp
E 8
D 5
.I Utility
should never read from the standard input.
E 5
I 5
Undefined behavior may occur if
D 8
.I utility
E 8
I 8
.Ar utility
E 8
reads from the standard input.
E 5
D 8
.PP
E 8
I 8
.Pp
E 8
D 7
.I Xargs
D 5
exits with 0 if no error occurred, and 1 otherwise.
E 5
I 5
exits with an exit status of 0 if no error occurs.
If
E 7
I 7
The
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
utility exits immediately (without processing any further input) if a
command line cannot be assembled,
E 7
D 8
.I utility
E 8
I 8
.Ar utility
E 8
D 7
cannot be invoked, is terminated by a signal or terminates without
calling
.IR exit (2),
E 7
I 7
cannot be invoked, an invocation of the utility is terminated by a signal
or an invocation of the utility exits with a value of 255.
D 8
.PP
E 8
I 8
.Pp
E 8
The
E 7
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
D 7
exits with an exit status of 127.
E 7
I 7
utility exits with a value of 0 if no error occurs.
E 7
If
D 8
.I utility
E 8
I 8
.Ar utility
E 8
D 7
exits with an exit status other than 0,
E 7
I 7
cannot be invoked,
E 7
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
D 7
exits with that exit status.
Otherwise,
E 7
I 7
exits with a value of 127.
If any other error occurs,
E 7
D 8
.I xargs
E 8
I 8
.Nm xargs
E 8
D 7
exits with an exit status of 1.
E 7
I 7
exits with a value of 1.
E 7
E 5
D 8
.SH "SEE ALSO"
D 5
echo(1)
E 5
I 5
.IR echo (1),
.IR find (1)
E 5
.SH STANDARDS
E 8
I 8
.Sh SEE ALSO
.Xr echo 1 ,
.Xr find 1
.Sh STANDARDS
E 8
The
D 8
.I xargs
utility is expected to be POSIX 1003.2 compliant.
E 8
I 8
.Nm xargs
utility is expected to be
.St -p1003.2
compliant.
E 8
E 1
