h39201
s 00002/00002/00079
d D 8.1 93/06/06 15:49:24 bostic 15 14
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00020/00017/00061
d D 6.11 91/07/24 22:48:11 cael 14 13
c mdoc version three
e
s 00002/00000/00076
d D 6.10 91/03/14 00:24:20 cael 13 11
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00076
d R 6.10 91/03/13 20:36:20 cael 12 11
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00009/00008/00067
d D 6.9 91/02/12 22:16:27 bostic 11 10
c rework the password subsystem
e
s 00000/00000/00075
d D 6.8 90/07/24 22:49:54 cael 10 9
c .Xr botch fix
e
s 00030/00010/00045
d D 6.7 90/06/22 16:26:55 kfall 9 8
c add Kerberos info
e
s 00042/00035/00013
d D 6.6 90/06/11 05:58:19 cael 8 7
c converted man page
e
s 00032/00088/00016
d D 6.5 89/02/22 17:22:29 bostic 7 6
c shadow passwords
e
s 00001/00000/00103
d D 6.4 86/06/05 16:51:20 bloom 6 5
c break needed
e
s 00001/00001/00102
d D 6.3 86/05/09 08:42:42 anne 5 4
c grammar
e
s 00011/00020/00092
d D 6.2 85/10/30 18:56:30 bloom 4 3
c add /etc/shells, more forgiving about entering GCOS info
e
s 00080/00010/00032
d D 6.1 85/04/29 14:41:16 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00002/00040
d D 5.1 85/04/29 14:41:04 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00042/00000/00000
d D 4.1 85/04/29 14:40:54 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
f b 
t
T
I 1
D 7
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 8
.\" Copyright (c) 1988 The Regents of the University of California.
E 8
I 8
D 15
.\" Copyright (c) 1990 The Regents of the University of California.
E 8
.\" All rights reserved.
E 15
I 15
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 15
E 7
.\"
I 7
D 8
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 8
I 8
D 14
.\" %sccs.include.redist.man%
E 14
I 14
.\" %sccs.include.redist.roff%
E 14
E 8
.\"
E 7
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
D 14
.\"     %W% (Berkeley) %G%
E 14
I 14
.\"	%W% (Berkeley) %G%
E 14
E 8
.\"
I 13
D 14
.Vx
.Vx
E 14
E 13
D 2
.TH PASSWD 1 
E 2
I 2
D 3
.TH PASSWD 1 "18 January 1983"
E 3
I 3
D 8
.TH PASSWD 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 3
passwd \- change login password
E 3
I 3
D 7
chfn, chsh, passwd \- change password file information
E 7
I 7
passwd \- change password file information
E 7
E 3
.SH SYNOPSIS
.B passwd
D 3
[ name ]
E 3
I 3
D 7
[
.B \-f
] [
.B \-s
] [ name ]
E 7
I 7
[ user ]
E 7
E 3
.SH DESCRIPTION
D 3
This command changes (or installs) a password
E 3
I 3
D 7
This command changes (or installs)
a password, login shell
.RB ( \-s
option), or GECOS information field
.RB ( \-f
option)
E 3
associated with the user
.IR name
(your own name by default).
.PP
D 3
The program prompts for the old password and then for the new one.
E 3
I 3
When altering a password,
the program prompts for the current password and then for the new one.
E 3
The caller must supply both.
D 5
The new password must be typed twice, to forestall mistakes.
E 5
I 5
The new password must be typed twice to forestall mistakes.
E 5
.PP
New passwords must be at least four characters long if they use
a sufficiently rich alphabet and at least six characters long
if monocase.
These rules are relaxed if you are insistent enough.
.PP
Only the owner of the name or the super-user may change a password;
the owner must prove he knows the old password.
I 3
.PP
When altering a login shell,
.I passwd
displays the current login shell and then prompts
for the new one.
D 4
The new login shell must be one of the approved shells:
.IR /bin/sh ,
.IR /bin/csh ,
.IR /bin/oldcsh ,
or
.I /usr/new/csh
E 4
I 4
The new login shell must be one of the approved shells
listed in
.I /etc/shells
E 4
unless you are the super-user.
I 4
If
.I /etc/shells
does not exist, the only shells that may be specified are
.I /bin/sh
and
.IR /bin/csh .
E 4
.PP
The super-user may change anyone's login shell; normal users
may only change their own login shell.
.PP
When altering the GECOS information field,
.I passwd
displays the current information, broken into
fields, as interpreted by the
.IR finger (1)
program, among others, and prompts for new values.
These fields include a user's
``real life'' name, office room number,
office phone number, and home phone number.
Included in each prompt is a default value,
which is enclosed between brackets.
The default value is accepted simply by typing a carriage
return.  To enter a blank field, the word ``none'' may
be typed.  Below is a sample run:
.IP
.B "Name [Biff Studsworth II]:"
.br
.B "Room number (Exs: 597E or 197C) []:"
521E
.br
.B "Office Phone (Ex: 1632) []:"
1863
.br
.B "Home Phone (Ex: 987532) [5771546]:"
none
.sp
.PP
E 7
.I Passwd
D 7
allows phone numbers to be entered with or without hyphens.
D 4
Because 
.I finger
only knows about UCB extensions,
.I passwd
will insist upon a four digit number (after the hyphens are removed) 
for office phone numbers.
Also, room numbers must be in Evans or Cory;
again, this is also because of 
.IR finger .
.PP
E 4
It is a good idea to run
.I finger
after changing the GECOS information
to make sure everything is setup properly.
E 7
I 7
changes the user's password.  First, the user is prompted for their old
password, and then, if that is correct, for the new password.  The new
password must be entered twice to forestall any typing errors.  The
E 8
I 8
.Dd %Q%
.Dt PASSWD 1
.Os BSD 4
.Sh NAME
.Nm passwd
D 9
.Nd modify password file information
E 9
I 9
.Nd modify a user's password
E 9
.Sh SYNOPSIS
.Nm passwd
I 9
.Op Fl l
E 9
.Op Ar user
.Sh DESCRIPTION
.Nm Passwd
D 9
changes the user's password.  First, the user is prompted for their
current
password, and, if that is correct typed, for a new password.  The new
password must be entered two times to verify any typing errors.  The
E 8
super-user is not prompted for the old password.
E 9
I 9
changes the user's Kerberos password.  First, the user is prompted for their
current password.
If the current password is correctly typed, a new password is
requested.
D 11
The new password must be entered two times to verify any typing errors.
E 11
I 11
The new password must be entered twice to avoid typing errors.
E 11
E 9
E 7
D 8
.PP
E 8
I 8
.Pp
D 9
The new password must be at least six characters long and cannot be
purely alphabetic.  Numbers, upper case letters and meta characters
E 9
I 9
The new password should be at least six characters long and not
purely alphabetic.
D 14
Its total length must be less than _PASSWORD_LEN (currently 128 characters).
E 14
I 14
Its total length must be less than
.Dv _PASSWORD_LEN
(currently 128 characters).
E 14
Numbers, upper case letters and meta characters
E 9
are encouraged.
.Pp
E 8
D 7
The super-user may change anyone's GECOS information; normal
users may only change their own.
E 7
I 7
Once the password has been verified,
D 8
.I passwd
E 8
I 8
.Nm passwd
E 8
D 9
uses
E 9
I 9
communicates the new password information to
the Kerberos authenticating host.
D 14
.Tp Fl l
E 14
I 14
.Bl -tag -width flag
.It Fl l
E 14
This option causes the password to be updated only in the local
password file, and not with the Kerberos database.
When changing only the local password,
E 9
D 8
.IR mkpasswd (8)
E 8
I 8
D 11
.Xr mkpasswd  8
E 8
D 9
to update the user database.  This is run in the background, and,
E 9
I 9
is used to update the user database.  This is run in the background, and,
E 9
at very large sites could take several minutes.  Until this update
is completed, the password file is unavailable for other updates
and the new password will not be available to programs.
E 11
I 11
.Xr pwd_mkdb  8
is used to update the password databases.
E 11
I 9
D 14
.Tp
E 14
I 14
.El
E 14
.Pp
To change another user's Kerberos password, one must first
run
.Xr kinit 1
followed by
.Xr passwd 1 .
The super-user is not required to provide a user's current password
if only the local password is modified.
E 9
E 7
E 3
D 8
.SH FILES
D 4
/etc/passwd
E 4
I 4
D 7
/etc/passwd	The file containing all of this information
I 6
.br
E 6
/etc/shells	The list of approved shells
E 7
I 7
.DT
/etc/master.passwd		the user database
.RE
E 7
E 4
.SH "SEE ALSO"
D 3
login(1), passwd(5), crypt(3)
E 3
I 3
D 7
login(1), finger(1), passwd(5), crypt(3)
E 7
I 7
chpass(1), login(1), passwd(5), mkpasswd(8), vipw(8)
E 8
I 8
.Sh FILES
D 14
.Dw /etc/master.passwd
.Di L
.Dp Pa /etc/master.passwd
E 14
I 14
.Bl -tag -width /etc/master.passwd -compact
.It Pa /etc/master.passwd
E 14
D 11
the user database
E 11
I 11
The user database
D 14
.Dp Pa /etc/passwd 
E 14
I 14
.It Pa /etc/passwd 
E 14
A Version 7 format password file
D 14
.Dp Pa /etc/passwd.XXXXXX
E 14
I 14
.It Pa /etc/passwd.XXXXXX
E 14
Temporary copy of the password file
E 11
D 14
.Dp
E 14
I 14
.El
E 14
.Sh SEE ALSO
.Xr chpass 1 ,
I 9
.Xr kerberos 1 ,
.Xr kinit 1 ,
E 9
.Xr login 1 ,
.Xr passwd 5 ,
I 9
.Xr kpasswdd 8 ,
E 9
D 11
.Xr mkpasswd 8 ,
E 11
I 11
.Xr pwd_mkdb 8 ,
E 11
.Xr vipw 8
E 8
E 7
E 3
D 14
.br
Robert Morris and Ken Thompson,
D 8
.I UNIX password security
E 8
I 8
.Em UNIX password security
E 14
I 14
.Rs
.%A Robert Morris
.%A Ken Thompson
.%T "UNIX password security"
.Re
E 14
.Sh HISTORY
A
.Nm passwd
D 14
command appeared in Version 6 AT&T UNIX.
E 14
I 14
command appeared in
.At v6 .
E 14
E 8
D 4
.SH BUGS
D 3
The password file information should be kept in a different data structure
allowing indexed access;
D 2
.IR dbm (3)
E 2
I 2
.IR dbm (3X)
E 2
would probably be suitable.
E 3
I 3
The encoding of the office and extension information
is installation dependent.
E 4
E 3
E 1
