h14462
s 00002/00002/00031
d D 8.1 93/06/06 16:46:36 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00025/00013/00008
d D 6.6 91/04/23 18:33:38 cael 10 9
c mdoc version three
e
s 00003/00003/00018
d D 6.5 90/08/21 10:34:48 bostic 9 8
c state the format for clarity
e
s 00000/00012/00021
d D 6.4 90/08/21 10:31:12 bostic 8 7
c somebody picked and dropped a little too fast
e
s 00018/00005/00015
d D 6.3 90/06/24 19:22:12 cael 7 6
c converted man page
e
s 00001/00001/00019
d D 6.2 87/01/28 14:33:01 bostic 6 4
c add entries to see also
e
s 00005/00003/00017
d R 6.2 86/12/10 07:04:24 bostic 5 4
c document the argument file
e
s 00001/00001/00019
d D 6.1 85/04/29 17:29:13 mckusick 4 2
c 4.3BSD beta release manual page
e
s 00000/00000/00020
d R 6.1 85/04/29 15:06:55 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00003/00018
d D 5.1 85/04/29 15:06:46 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00021/00000/00000
d D 4.1 85/04/29 15:06:37 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 7
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 10
.\" Copyright (c) 1980, 1990 Regents of the University of California.
E 10
I 10
D 11
.\" Copyright (c) 1980, 1990, 1991 Regents of the University of California.
E 10
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1980, 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 7
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\" %sccs.include.redist.man%
E 7
.\"
D 2
.TH USERS 1
E 2
I 2
D 4
.TH USERS 1 January 1983"
E 4
I 4
D 7
.TH USERS 1 "%Q%"
E 7
I 7
.\"     %W% (Berkeley) %G%
.\"
D 10
.TH USERS 1 "%Q"
E 7
E 4
E 2
.UC
I 7
.SH NAME
D 9
users \- compact list of users who are on the system
E 9
I 9
users \- list of current users
E 9
.SH SYNOPSIS
.B users
.SH DESCRIPTION
.I Users
E 10
I 10
.Dd %Q%
.Dt USERS 1
.Os BSD 3
.Sh NAME
.Nm users
.Nd list current users
.Sh SYNOPSIS
.Nm users
.Sh DESCRIPTION
.Nm Users
E 10
D 9
lists the login names of the users currently on the system in a compact,
one-line format.
E 9
I 9
lists the login names of the users currently on the system,
in sorted order, space separated, on a single line.
E 9
D 10
.SH FILES
/etc/utmp
.SH SEE ALSO
finger(1), last(1), who(1), utmp(5)
E 10
I 10
.Sh FILES
.Bl -tag -width /etc/utmp
.It Pa /etc/utmp
.El
.Sh SEE ALSO
.Xr finger 1 ,
.Xr last 1 ,
.Xr who 1 ,
.Xr utmp 5
.Sh HISTORY
The
.Nm
command appeared in
.Bx 3.0 .
E 10
E 7
D 8
.SH NAME
users \- compact list of users who are on the system
.SH SYNOPSIS
.B users
.SH DESCRIPTION
.I Users
lists the login names of the users currently on the system in a compact,
one-line format.
.SH FILES
/etc/utmp
.SH SEE ALSO
D 2
finger(1), who(1)
.SH BUGS
E 2
I 2
D 6
who(1)
E 6
I 6
finger(1), last(1), who(1), utmp(5)
E 8
E 6
E 2
E 1
