h48590
s 00036/00026/00014
d D 6.5 91/03/16 17:08:34 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00003/00013/00037
d D 6.4 90/06/24 21:52:09 trent 5 4
c new copyright & pathnames
e
s 00015/00004/00035
d D 6.3 89/02/17 09:01:04 bostic 4 3
c Berkeley copyright notice
e
s 00000/00001/00039
d D 6.2 86/06/03 15:22:14 cuccia 3 2
c removed hanging BUGS:
e
s 00001/00001/00039
d D 6.1 85/04/27 15:57:38 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00040/00000/00000
d D 5.1 85/04/27 15:57:21 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 4
.\"
I 4
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH RRESTORE 8C "18 January 1983"
E 2
I 2
D 4
.TH RRESTORE 8C "%Q%"
E 4
I 4
D 6
.TH RRESTORE 8 "%Q%"
E 4
E 2
.UC 5
.SH NAME
rrestore \- restore a file system dump across the network
.SH SYNOPSIS
D 5
.B /etc/rrestore
E 5
I 5
.B rrestore
E 5
[ key [
name ... ]
.SH DESCRIPTION
.I Rrestore
obtains from magnetic tape files
saved by a previous
.IR dump (8).
E 6
I 6
.Dd %Q%
.Dt RRESTORE 8
.Os BSD 4.2
.Sh NAME
.Nm rrestore
.Nd "restore a file system dump across the network"
.Sh SYNOPSIS
.Nm rrestore
.Oo
.Ar key
.Op Ar name ...
.Oc
.Sh DESCRIPTION
.Nm Rrestore
remotely restores files across a network in the same manner as
.Xr restore 8
locally restores files.
.Xr dump 8 .
E 6
The command is identical in operation to
D 6
.IR restore (8)
E 6
I 6
.Xr restore 8
E 6
except the 
D 6
.I f
E 6
I 6
.Cm f
E 6
key should be specified and the file
supplied should be of the form
D 6
.IR machine:device .
.PP
.I Rrestore
E 6
I 6
.Ar machine:device .
.Pp
.Nm Rrestore
E 6
creates a remote server,
D 5
.IR /etc/rmt ,
E 5
I 5
D 6
.IR rmt ,
E 6
I 6
rmt,
E 6
E 5
on the client machine to access the tape
device.
D 6
.SH "SEE ALSO"
restore(8),
rmt(8C)
.SH DIAGNOSTICS
E 6
I 6
.Sh SEE ALSO
.Xr restore 8 ,
.Xr rmt 8
.Sh DIAGNOSTICS
E 6
Same as 
D 6
.IR restore (8)
E 6
I 6
.Xr restore 8
E 6
with a few extra related to the network.
I 6
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 6
D 3
.SH BUGS
E 3
E 1
