h51156
s 00002/00002/00191
d D 8.1 93/06/06 14:09:58 bostic 12 11
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00063/00002/00130
d D 6.7 93/05/11 11:51:18 bostic 11 10
c new version from Vernon Schryver (vjs@sgi.com); see ../timed/CHANGES for details
e
s 00076/00052/00056
d D 6.6 91/04/27 21:58:32 cael 10 8
c mdoc version three
e
s 00075/00051/00057
d R 6.6 91/04/20 11:51:43 cael 9 8
c mdoc'd
e
s 00006/00016/00102
d D 6.5 90/06/24 22:45:38 trent 8 7
c new copyright & pathnames
e
s 00001/00001/00117
d D 6.4 88/09/20 10:16:00 bostic 7 6
c (4P) -> (4)
e
s 00010/00005/00108
d D 6.3 88/07/09 11:32:08 bostic 6 5
c install approved copyright notice
e
s 00008/00002/00105
d D 6.2 87/12/23 14:31:44 bostic 5 4
c add Berkeley header; NASA wants it
e
s 00000/00000/00107
d D 6.1 86/05/28 11:42:38 karels 4 3
c out
e
s 00021/00006/00086
d D 1.3 86/05/28 10:30:57 karels 3 2
c updates and cleanups
e
s 00020/00002/00072
d D 1.2 86/05/15 19:25:22 bloom 2 1
c add -i flag (from ks@purdue)
e
s 00074/00000/00000
d D 1.1 85/06/24 13:27:25 gusella 1 0
c date and time created 85/06/24 13:27:25 by gusella
e
u
U
t
T
I 1
D 10
.\" Copyright (c) 1980 Regents of the University of California.
E 10
I 10
D 12
.\" Copyright (c) 1980, 1991 Regents of the University of California.
E 10
D 5
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
.\" All rights reserved.
E 12
I 12
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 12
.\"
D 8
.\" Redistribution and use in source and binary forms are permitted
D 6
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
E 6
I 6
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 8
I 8
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 8
E 6
E 5
.\"
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
.\"     %W% (Berkeley) %G%
E 10
.\"
D 10
.TH TIMED 8 "%Q%"
.UC 6
.ad
.SH NAME
timed \- time server daemon
.SH SYNOPSIS
D 8
.B /etc/timed
E 8
I 8
.B timed
E 8
D 2
[ -t ] [ -M ] [ -n network ]
E 2
I 2
[ -t ] [ -M ] [ -n network ] [ -i network ]
E 2
.SH DESCRIPTION
.I Timed
E 10
I 10
.Dd %Q%
.Dt TIMED 8
.Os BSD 4.3
.Sh NAME
.Nm timed
.Nd time server daemon
.Sh SYNOPSIS
.Nm timed
.Op Fl M
.Op Fl t
I 11
.Op Fl d
E 11
.Op Fl i Ar network
.Op Fl n Ar network
I 11
.Op Fl F Ar host1 host2 ...
E 11
.Sh DESCRIPTION
This
E 10
D 11
is the time server daemon and is normally invoked
E 11
I 11
is a time server daemon and is normally invoked
E 11
at boot time from the
D 10
.IR rc (8)
E 10
I 10
.Xr rc 8
E 10
file.  
It synchronizes the host's time with the time of other
machines in a local area network running 
D 10
.IR timed (8).
E 10
I 10
.Nm timed 8 .
E 10
These time servers will slow down the clocks of some machines
and speed up the clocks of others to bring them to the average network time.
I 3
The average network time is computed from measurements of clock differences
D 10
using the ICMP timestamp request message.
E 3
.PP
The service provided by \fItimed\fP is based  on a master-slave
E 10
I 10
using the
.Tn ICMP
timestamp request message.
.Pp
The service provided by
.Nm timed
is based  on a master-slave
E 10
scheme.
When
D 10
.IR timed (8)
E 10
I 10
.Nm timed 8
E 10
is started on a machine, it asks the master for the network time
and sets the host's clock to that time.
After that, it accepts synchronization messages periodically sent by
the master and calls 
D 10
.IR adjtime (2)
E 10
I 10
.Xr adjtime 2
E 10
to perform the needed corrections on the host's clock.
D 10
.PP
E 10
I 10
.Pp
E 10
It also communicates with
D 10
.IR date (1)
E 10
I 10
.Xr date 1
E 10
in order to set the date globally,
and with 
D 10
.IR timedc (8),
E 10
I 10
.Xr timedc 8 ,
E 10
a timed control program.
If the machine running the master crashes, then the slaves will elect
a new master from among slaves running with the 
D 10
.B \-M
E 10
I 10
.Fl M
E 10
flag.
A
D 10
.IR timed
E 10
I 10
.Nm timed
E 10
running without the
D 10
.B \-M
E 10
I 10
.Fl M
E 10
D 11
flag will remain a slave.
E 11
I 11
or
.Fl F
flags will remain a slave.
E 11
The 
D 10
.B \-t 
flag enables \fItimed\fP to trace the messages it receives in the
D 8
file /usr/adm/timed.log.
E 8
I 8
file /var/log/timed.log.
E 10
I 10
.Fl t
flag enables
.Nm timed
to trace the messages it receives in the
file
.Pa /var/log/timed.log .
E 10
E 8
Tracing can be turned on or off by the program
D 10
.IR timedc (8).
I 3
.I Timed
normally checks for a master time server on each network to which
E 10
I 10
.Xr timedc 8 .
I 11
The
.Fl d
flag is for debugging the daemon.
It causes the program to not put itself into the background.
E 11
Normally
.Nm timed
checks for a master time server on each network to which
E 10
it is connected, except as modified by the options described below.
It will request synchronization service from the first master server
located.
If permitted by the
D 10
.B \-M
E 10
I 10
.Fl M
E 10
flag, it will provide synchronization service on any attached networks
on which no current master server was detected.
Such a server propagates the time computed by the top-level master.
E 3
The 
D 10
.B \-n 
E 10
I 10
.Fl n
E 10
flag, followed by the name of a network which the host is connected to
D 3
(see: /etc/networks), overrides the default choice of the
E 3
I 3
(see
D 10
.IR networks (5)),
E 10
I 10
.Xr networks 5 ) ,
E 10
overrides the default choice of the
E 3
D 2
network address made by the program.
E 2
I 2
network addresses made by the program.
Each time the
D 10
.B \-n
E 10
I 10
.Fl n
E 10
flag appears, that network name is added to a list of valid networks.
All other networks are ignored.
The 
D 10
.B \-i 
E 10
I 10
.Fl i
E 10
D 3
flag, followed by the name of a network which the host is connected to
(see: /etc/networks), overrides the default choice of the
network addresses made by the program.
E 3
I 3
flag, followed by the name of a network to which the host is connected
(see
D 10
.IR networks (5)),
E 10
I 10
.Xr networks 5 ) ,
E 10
overrides the default choice of the network addresses made by the program.
E 3
Each time the
D 10
.B \-i
E 10
I 10
.Fl i
E 10
flag appears, that network name is added to a list of networks to ignore.
All other networks are used by the time daemon.
The
D 10
.B \-n
E 10
I 10
.Fl n
E 10
and 
D 10
.B \-i
E 10
I 10
.Fl i
E 10
flags are meaningless if used together.
I 11
.Pp
.Nm Timed
checks for a master time server on each network to which
it is connected, except as modified by the
.Fl n
and
.Fl i
options described above.
If it finds masters on more than one network, it chooses one network
on which to be a "slave," and then periodically checks the other
networks to see if the masters there have disappeared.
.Pp
One way to synchronize a group of machines is to use an NTP daemon to 
synchronize the clock of one machine to a distant standard or a radio
receiver and 
.Fl F Ar hostname
to tell its timed daemon to trust only itself.
.Pp
Messages printed by the kernel on the system console occur with
interrupts disabled. 
This means that the clock stops while they are printing.
A machine with many disk or network hardware problems and consequent
messages cannot keep good time by itself.  Each message typically causes
the clock to lose a dozen milliseconds.  A time daemon can
correct the result.
.Pp
Messages in the system log about machines that failed to respond
usually indicate machines that crashed or were turned off.
Complaints about machines that failed to respond to initial time
settings are often associated with "multi-homed" machines
that looked for time masters on more than one network and eventually
chose to become a slave on the other network.
.SH WARNING
If two or more time daemons, whether 
.Nm timed ,
.Xr NTP ,
try to adjust the same clock, temporal chaos will result.
If both 
.Nm
and another time daemon are run on the same machine,
ensure that the 
.Fl F
flag is used, so that 
.Nm timed
never attempts to adjust the local clock.
.Pp 
The protocol is based on UDP/IP broadcasts.  All machines within
the range of a broadcast that are using the TSP protocol must cooperate.
There cannot be more than a single administrative domain using the
.Fl F
flag among all machines reached by a broadcast packet.
Failure to follow this rule is usually indicated by complaints concerning
"untrusted" machines in the system log.
E 11
E 2
D 10
.SH FILES
.nf
D 3
.ta \w'/usr/adm/masterlog       'u
E 3
I 3
D 8
.ta \w'/usr/adm/timed.masterlog     'u
E 3
/usr/adm/timed.log		tracing file for timed
/usr/adm/timed.masterlog	log file for master timed 
E 8
I 8
.ta \w'/var/log/timed.masterlog     'u
/var/log/timed.log		tracing file for timed
/var/log/timed.masterlog	log file for master timed 
E 8
.fi
.SH "SEE ALSO"
D 3
date(1), adjtime(2), gettimeofday(2), timedc(8),
E 3
I 3
D 7
date(1), adjtime(2), gettimeofday(2), icmp(4P), timedc(8),
E 7
I 7
date(1), adjtime(2), gettimeofday(2), icmp(4), timedc(8),
E 7
E 3
.br
\fITSP: The Time Synchronization Protocol for UNIX 4.3BSD\fP, 
R. Gusella and S. Zatti
E 10
I 10
.Sh FILES
.Bl -tag -width /var/log/timed.masterlog -compact
.It Pa /var/log/timed.log
tracing file for timed
.It Pa /var/log/timed.masterlog
log file for master timed 
.El
.Sh SEE ALSO
.Xr date 1 ,
.Xr adjtime 2 ,
.Xr gettimeofday 2 ,
.Xr icmp 4 ,
.Xr timedc 8 ,
.Rs
.%T "TSP: The Time Synchronization Protocol for UNIX 4.3BSD"
.%A R. Gusella
.%A S. Zatti
.Re
.Sh HISTORY
The
.Nm
daemon appeared in
.Bx 4.3 .
E 10
E 1
