h35417
s 00002/00002/00041
d D 8.1 93/06/05 10:55:30 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00033/00029/00010
d D 6.3 91/03/16 17:06:12 cael 4 3
c macro and text revision (-mdoc version 3)
e
s 00002/00002/00037
d D 6.2 90/06/24 21:33:48 trent 3 2
c new pathnames (fastboot & fasthalt)
e
s 00001/00001/00038
d D 6.1 85/04/27 14:56:20 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00039/00000/00000
d D 5.1 85/04/27 14:56:00 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 5
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\" %sccs.include.redist.man%
E 4
.\"
D 2
.TH FASTBOOT 8 "4 March 1983"
E 2
I 2
D 4
.TH FASTBOOT 8 "%Q%"
E 2
.UC 5
.SH NAME
fastboot, fasthalt \- reboot/halt the system without checking the disks
.SH SYNOPSIS
D 3
.B /etc/fastboot
E 3
I 3
.B fastboot
E 3
[
.I boot-options
]
.br
D 3
.B /etc/fasthalt
E 3
I 3
.B fasthalt
E 3
[
.I halt-options
]
.SH DESCRIPTION
.I Fastboot
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt FASTBOOT 8
.Os BSD 4.2
.Sh NAME
.Nm fastboot ,
.Nm fasthalt
.Nd "reboot/halt the system without checking the disks"
.Sh SYNOPSIS
.Nm fastboot
.Op Ar boot-options
.Nm fasthalt
.Op Ar halt-options
.Sh DESCRIPTION
.Nm Fastboot
E 4
and
D 4
.I fasthalt
E 4
I 4
.Nm fasthalt
E 4
are shell scripts which reboot and halt the system without
checking the file systems.  This is done by creating a
file 
D 4
.IR /fastboot ,
E 4
I 4
.Pa /fastboot ,
E 4
then invoking the 
D 4
.I reboot
E 4
I 4
.Xr reboot
E 4
program.  The system startup script,
D 4
.IR /etc/rc ,
E 4
I 4
.Pa /etc/rc ,
E 4
looks for this file and, if present, skips the normal
invocation of
D 4
.IR fsck (8).
.SH "SEE ALSO"
halt(8),
reboot(8),
rc(8)
E 4
I 4
.Xr fsck 8 .
.Sh SEE ALSO
.Xr halt 8 ,
.Xr reboot 8 ,
.Xr rc 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 4
E 1
