h34107
s 00000/00000/00026
d D 8.1 93/05/31 17:03:11 bostic 2 1
c 4.4BSD snapshot (revision 8.1)
e
s 00026/00000/00000
d D 1.1 89/05/04 19:24:37 bostic 1 0
c date and time created 89/05/04 19:24:37 by bostic
e
u
U
t
T
I 1
.nr tp 8
.nr hm 3v
.nr fm 2v
.nr tm 5v
.nr bm 4v
.cs R
.sc
.sz 6
.ll +10n
.lt \n(.l
.de $h
.tl 'Fortune Database'\\*(Se'\*(td'
..
.de $f
.tl ''- % -''
..
.2c
.nf
.ta
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 80n
.de %%
.sp .3
.ce
\(sq\|\(sq\|\(sq\|\(sq\|\(sq\|\(sq\|\(sq\|\(sq\|\(sq
.sp .2
..
E 1
