h19116
s 00046/00021/00001
d D 6.2 92/07/15 11:59:47 cael 5 3
c mdoc version three
e
s 00006/00002/00020
d R 6.2 90/06/24 19:18:56 cael 4 3
c converted man page
e
s 00001/00001/00021
d D 6.1 85/04/29 18:00:11 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00002/00020
d D 5.1 85/04/29 18:00:01 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00022/00000/00000
d D 4.1 85/04/29 17:59:54 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\" Copyright (c) 1991 Regents of the University of California.
.\" All rights reserved.
E 5
.\"
D 2
.TH SUM 1 
E 2
I 2
D 3
.TH SUM 1  "18 January 1983"
E 3
I 3
D 5
.TH SUM 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
sum \- sum and count blocks in a file
.SH SYNOPSIS
.B sum
file
.SH DESCRIPTION
.I Sum
calculates and prints a 16-bit checksum for the named file,
and also prints the number of blocks in the file.
It is typically used to look for bad spots, or
to validate a file communicated over
some transmission line.
.SH "SEE ALSO"
wc(1)
.SH DIAGNOSTICS
`Read error'
D 2
is indistinuishable from end of file on
E 2
I 2
is indistinguishable from end of file on
E 2
most devices; check the block count.
E 5
I 5
.\" %sccs.include.redist.roff%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt SUM 1
.Os
.Sh NAME
.Nm sum
.Nd calculate file checksums and block counts
.Sh SYNOPSIS
.Nm sum
.Ar file
.Sh DESCRIPTION
The
.Nm sum
utility calculates and writes to standard output a
checksum (16 bit CRC) for each input file,
and also writes to the standard output the number of blocks
in each file.
.Pp
The following operand is available:
.Bl -tag -width file
.It Ar file
The pathname of the
.Ar file
to checksum.
If no file operands are specified, the
standard input is used.
.El
.Sh SEE ALSO
.Xr wc 1
.Sh DIAGNOSTICS
The
.Nm sum
utility exits zero on success,
and >0 if an error occurs.
.Pp
End-of-file may return a read-error.
.Sh HISTORY
A
.Nm
command appeared in
.At v7 .
E 5
E 1
