h63465
s 00026/00044/00106
d D 6.5 91/07/29 23:39:48 cael 7 6
c mdoc version three
e
s 00002/00000/00148
d D 6.4 91/03/14 00:26:09 cael 6 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00148
d R 6.4 91/03/13 20:37:15 cael 5 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00120/00072/00028
d D 6.3 90/07/24 22:47:40 cael 4 3
c .Xr botch fix
e
s 00002/00002/00098
d D 6.2 90/06/24 19:09:45 cael 3 2
c converted man page
e
s 00008/00002/00092
d D 6.1 85/04/29 21:11:20 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00094/00000/00000
d D 5.1 85/04/29 21:11:11 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" Copyright (c) 1983, 1990 Regents of the University of California.
.\" All rights reserved.
E 4
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
D 4
.\"		%W% (Berkeley) %G%
E 4
I 4
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
E 4
E 3
.\"
D 2
.TH LOOKBIB 1 "18 July 1983"
E 2
I 2
D 3
.TH LOOKBIB 1 "%Q%"
E 3
I 3
D 4
.TH LOOKBIB 1 "April 29, 1985"
E 3
E 2
.UC 5
.SH NAME
indxbib, lookbib \- build inverted index for a bibliography, find references in a bibliography
.SH SYNOPSIS
.B indxbib
database  ...
.br
.B lookbib
D 2
database
E 2
I 2
[
.B \-n
] database
E 2
.SH DESCRIPTION
.I Indxbib
makes an inverted index to the named
.I databases
(or files) for use by
.IR lookbib (1)
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
I 6
D 7
.Vx
.Vx
E 7
E 6
.Dd %Q%
.Dt LOOKBIB 1
.Os BSD 4.2
.Sh NAME
.Nm indxbib , lookbib
.Nd build inverted index for a bibliography,
find references in a bibliography
.Sh SYNOPSIS
.Nm indxbib
.Ar database ...
.Nm lookbib
.Op Fl n
.Ar database
.Sh DESCRIPTION
.Nm Indxbib
builds an inverted index to the named
.Ar databases
(or files), which can then be
used by
.Nm lookbib
E 4
and
D 4
.IR refer (1).
These files contain bibliographic references
(or other kinds of information) separated by blank lines.
.PP
A bibliographic reference is a set of lines,
constituting fields of bibliographic information.
Each field starts on a line beginning with a ``%'',
followed by a key-letter, then a blank,
and finally the contents of the field,
which may continue until the next line starting with ``%''.
.PP
.I Indxbib 
is a shell script that calls
/usr/lib/refer/mkey and /usr/lib/refer/inv.
E 4
I 4
.Xr refer  1  .
The files are assumed to be
.Xr refer
style bibliographic databases
(see
.Xr addbib 1 ) .
.Pp
.Nm Indxbib
is a shell script which calls
.Nm mkey
and
.Nm inv .
E 4
The first program,
D 4
.I mkey,
E 4
I 4
.Nm mkey ,
E 4
truncates words to 6 characters,
and maps upper case to lower case.
It also discards words shorter than 3 characters,
words among the 100 most common English words,
and numbers (dates) < 1900 or > 2000.
D 4
These parameters can be changed; see page 4 of the
.I Refer
document by Mike Lesk.
E 4
I 4
These parameters can be changed; see page 4 of a
.Em Refer
document by Mike Lesk (See the SEE ALSO section below).
E 4
The second program,
D 4
.I inv,
creates an entry file (.ia),
a posting file (.ib), and a tag file (.ic),
E 4
I 4
.Nm inv ,
creates an entry file
D 7
.Cx \&(
.Ar file
.Cx .ia),
.Cx
E 7
I 7
.Pq Ar file Ns .ia ,
E 7
a posting file
D 7
.Cx \&(
.Ar file
.Cx .ib),
.Cx
E 7
I 7
.Pq Ar file Ns .ib ,
E 7
and a tag file
D 7
.Cx \&(
.Ar file
.Cx .ic),
.Cx
E 7
I 7
.Pq Ar file Ns .ic ,
E 7
E 4
all in the working directory.
D 4
.PP
.I Lookbib
E 4
I 4
.Pp
.Nm Lookbib
E 4
uses an inverted index made by
D 4
.I indxbib
E 4
I 4
.Nm indxbib
E 4
to find sets of bibliographic references.
It reads keywords typed after the ``>'' prompt on the terminal,
and retrieves records containing all these keywords.
If nothing matches, nothing is returned except another ``>'' prompt.
I 2
D 4
.PP
.I Lookbib
E 4
I 4
.Pp
.Nm Lookbib
E 4
will ask if you need instructions, and will print some brief information if
D 4
you reply ``y''.  The ``\-n'' flag turns off the prompt for instructions.
E 2
.PP
E 4
I 4
you reply ``y''.  The
.Fl n
flag turns off the prompt for instructions.
.Pp
E 4
It is possible to search multiple databases,
as long as they have a common index made by
D 4
.I indxbib.
E 4
I 4
.Nm indxbib .
E 4
In that case, only the first argument given to
D 4
.I indxbib
E 4
I 4
.Nm indxbib
E 4
is specified to
D 4
.I lookbib.
.PP
E 4
I 4
.Nm lookbib .
.Pp
E 4
If
D 4
.I lookbib
does not find the index files (the .i[abc] files),
E 4
I 4
.Nm lookbib
D 7
does not find the index files (the 
.Cx \&(
.Ar file
.Cx .i[abc]
.Cx
E 7
I 7
does not find the index files (the
.Ar file Ns .i[abc]
E 7
files),
E 4
it looks for a reference file with the same name as the argument,
without the suffixes.
D 4
It creates a file with a '.ig' suffix, suitable for use with
.I fgrep.
E 4
I 4
It creates a file with a
`.ig' suffix, suitable for use with
.Xr fgrep 1 .
E 4
It then uses this fgrep file to find references.
D 4
This method is simpler to use, but the .ig file is slower to use
than the .i[abc] files, and does not allow the use of multiple reference files.
.SH FILES
.IR x .ia,
.IR x .ib,
.IR x .ic,
where 
.I x
is the first argument, or if these are not present, then
.IR x .ig,
.IR x
.SH SEE ALSO
refer(1), addbib(1), sortbib(1), roffbib(1), lookbib(1)
.SH BUGS
E 4
I 4
D 7
This method is simpler to use, but the 
.Cx Ar file
.Cx .ig
.Cx
E 7
I 7
This method is simpler to use, but the
.Ar file Ns ig
E 7
is slower to use
D 7
than the 
.Cx Ar file
.Cx .i[abc]
.Cx
E 7
I 7
than the
.Ar file Ns .i[abc]
E 7
files, and does not allow the use of multiple reference files.
.Sh FILES
D 7
.Dw /usr/libexec/mkey
.Di L
.Dp Pa \&*.ia
entry file
.Dp Pa \&*.ib
posting file
.Dp Pa \&*.ic
tag file
.Dp Pa \&*.ig
ascii file created if index files not found.
.Dp Pa /usr/libexec/mkey
make keys program
.Dp Pa /usr/libexec/inv
hash and invert program
.Dp
E 7
I 7
.Bl -tag -width /usr/libexec/mkey -compact
.It Pa \&*.ia
Entry file.
.It Pa \&*.ib
Posting file.
.It Pa \&*.ic
Tag file.
.It Pa \&*.ig
Ascii file created if index files not found.
.It Pa /usr/libexec/mkey
Make keys program.
.It Pa /usr/libexec/inv
Hash and invert program.
.El
E 7
.Sh SEE ALSO
.Xr refer 1 ,
.Xr addbib 1 ,
.Xr sortbib 1 ,
.Xr roffbib 1 ,
.Xr lookbib 1
.Sh BUGS
More than one blank line in between citations
can wreak havoc.
.Pp
E 4
Probably all dates should be indexed,
since many disciplines refer to literature
written in the 1800s or earlier.
I 4
.Sh HISTORY
A
.Nm lookbib
D 7
appeared in Version 32 AT&T Unix.
E 7
I 7
command appeared in
.At 32v .
E 7
E 4
E 1
