#
# Mach Operating System
# Copyright (c) 1989 Carnegie-Mellon University
# All rights reserved.  The CMU software License Agreement specifies
# the terms and conditions for use and redistribution.
#
#
# HISTORY
# $Log:	Makefile,v $
# Revision 2.2  89/07/12  00:23:42  jjc
# 	      Modified for CMU CS make.
# 	[88/11/14            jjc]
# 
#

#
# @(#)Makefile 1.3 88/02/08 SMI
#
# Makefile for Standalone Library

#if	CMU
ARCH=	sun3
#endif	CMU

all: $$(LIBSA)

include ../m68k/Makefile.arch
include ../common/Makefile.com
