h05189
s 00002/00002/00065
d D 8.1 93/06/04 13:04:02 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00001/00064
d D 6.7 91/06/29 14:23:11 bostic 9 8
c add ANSI contribution notice
e
s 00048/00040/00017
d D 6.6 91/04/19 14:48:33 cael 8 7
c macro and text revision (-mdoc version 3)
e
s 00002/00002/00055
d D 6.5 91/03/05 13:47:27 bostic 7 6
c go to template
e
s 00001/00003/00056
d D 6.4 91/03/05 11:23:00 bostic 6 5
c no reason to mention malloc/free
e
s 00050/00050/00009
d D 6.3 91/01/20 21:08:30 bostic 5 4
c new stdio
e
s 00012/00003/00047
d D 6.2 88/12/16 11:22:38 bostic 4 3
c add fpurge()
e
s 00001/00001/00049
d D 6.1 85/05/15 14:56:29 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00004/00004/00046
d D 5.1 85/05/15 14:56:19 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00050/00000/00000
d D 4.1 85/05/15 14:56:08 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 5
D 8
.\" Copyright (c) 1990 The Regents of the University of California.
E 8
I 8
D 10
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 8
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
.\" This code is derived from software contributed to Berkeley by
D 9
.\" Chris Torek.
E 9
I 9
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
E 9
D 8
.\"
E 8
.\" %sccs.include.redist.man%
.\"
E 5
I 1
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 2
.TH FCLOSE 3S 
E 2
I 2
D 3
.TH FCLOSE 3S  "19 January 1983"
E 3
I 3
D 5
.TH FCLOSE 3S  "%Q%"
E 3
E 2
.AT 3
E 5
I 5
D 8
.TH FCLOSE 3 "%Q%"
.UC 7
E 5
.SH NAME
D 5
fclose, fflush \- close or flush a stream
E 5
I 5
fclose \- close a stream
E 5
.SH SYNOPSIS
D 5
.B #include <stdio.h>
.PP
.B fclose(stream)
.br
.SM
.B FILE
.B *stream;
.PP
.B fflush(stream)
.br
.SM
.B FILE
.B *stream;
I 4
.PP
.B fpurge(stream)
.br
.SM
.B FILE
.B *stream;
E 5
I 5
.nf
.ft B
#include <stdio.h>

int
fclose(FILE *stream);
.ft R
.fi
E 5
E 4
.SH DESCRIPTION
.I Fclose
E 8
I 8
.Dd %Q%
.Dt FCLOSE 3
.Os
.Sh NAME
.Nm fclose
.Nd close a stream
.Sh SYNOPSIS
.Fd #include <stdio.h>
.Ft int
.Fn fclose "FILE *stream"
.Sh DESCRIPTION
The
.Fn fclose
function
E 8
D 5
causes any buffers for the named
E 5
I 5
dissociates the named
E 5
D 8
.I stream
E 8
I 8
.Fa stream
E 8
D 5
to be emptied, and the file to be closed.
Buffers allocated by the standard input/output system
are freed.
.PP
.I Fclose
is performed automatically upon
calling
D 2
.IR  exit (2).
E 2
I 2
.IR  exit (3).
E 2
.PP
.I Fflush
causes any buffered data for the named output
.I stream
to be written to that file.
The stream remains open.
I 4
.PP
.I Fpurge
causes any buffered data for the named
.I stream
to be lost.  The stream remains open.
E 5
I 5
from its underlying file or set of functions.
If the stream was being used for output, any buffered data is written
first, using
D 8
.IR fflush (3).
D 6
Any allocated memory is 
.IR free 'd.
E 6
E 5
E 4
D 7
.SH "SEE ALSO"
D 4
close(2),
D 2
fopen(3),
setbuf(3)
E 2
I 2
fopen(3S),
setbuf(3S)
E 4
I 4
D 5
close(2), fopen(3), setbuf(3)
E 4
E 2
.SH DIAGNOSTICS
These routines return
.SM
E 5
I 5
D 6
close(2), fflush(3), fopen(3), free(3), setbuf(3)
E 6
I 6
close(2), fflush(3), fopen(3), setbuf(3)
E 7
E 6
.SH "RETURN VALUE"
E 8
I 8
.Xr fflush 3 .
.Sh RETURN VALUES
E 8
Upon successful completion 0 is returned.
Otherwise,
E 5
D 8
.B EOF
E 8
I 8
.Dv EOF
E 8
D 5
if
.I stream
is not associated with an output file, or
if buffered data cannot be transferred to that file.
E 5
I 5
is returned and the global variable
D 8
.I errno
E 8
I 8
.Va errno
E 8
is set to indicate the error.
D 8
In either case no further access to the stream is possible. 
.SH ERRORS
.TP 15
[EBADF]
.I Stream
E 8
I 8
In either case no further access to the stream is possible.
.Sh ERRORS
.Bl -tag -width [EBADF]
.It Bq Er EBADF
The argument
.Fa stream
E 8
is not an open stream.
D 8
.PP
.I Fclose
may also fail and set 
.I errno
E 8
I 8
.El
.Pp
The
.Fn fclose
function
may also fail and set
.Va errno
E 8
for any of the errors specified for the routines
D 8
.IR close (2)
or 
.IR fflush (3).
.SH STANDARDS
.I Fclose
conforms to ANSI X3.159-1989 (``ANSI C'').
I 7
.SH "SEE ALSO"
close(2), fflush(3), fopen(3), setbuf(3)
E 8
I 8
.Xr close 2
or
.Xr fflush 3 .
.Sh SEE ALSO
.Xr close 2 ,
.Xr fflush 3 ,
.Xr fopen 3 ,
.Xr setbuf 3
.Sh STANDARDS
The
.Fn fclose
function
conforms to
.St -ansiC .
E 8
E 7
E 5
E 1
