h58616
s 00002/00002/00082
d D 8.1 93/06/04 13:04:28 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00001/00081
d D 5.4 91/06/29 14:23:51 bostic 4 3
c add ANSI contribution notice
e
s 00058/00051/00024
d D 5.3 91/04/19 14:46:37 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00075
d D 5.2 91/04/19 14:41:32 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00075/00000/00000
d D 5.1 91/03/05 13:47:04 bostic 1 0
c date and time created 91/03/05 13:47:04 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" This code is derived from software contributed to Berkeley by
D 4
.\" Chris Torek.
E 4
I 4
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
E 4
D 3
.\"
E 3
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH FFLUSH 3 "%Q%"
.UC 7
.SH NAME
fflush, fpurge \- flush a stream
.SH SYNOPSIS
.nf
.ft B
#include <stdio.h>

int
fflush(FILE *stream);

int
fpurge(FILE *stream);
.ft R
.fi
.SH DESCRIPTION
.I Fflush
writes any buffered data for the given output
.I stream
E 3
I 3
.Dd %Q%
.Dt FFLUSH 3
.Os
.Sh NAME
.Nm fflush ,
.Nm fpurge
.Nd flush a stream
.Sh SYNOPSIS
.Fd #include <stdio.h>
.Ft int
.Fn fflush "FILE *stream"
.Ft int
.Fn fpurge "FILE *stream"
.Sh DESCRIPTION
The function
.Fn fflush
forces a write of all buffered data for the given output or update
.Fa stream
E 3
via the stream's underlying write function.
D 3
The stream remains open.
.PP
E 3
I 3
The open status of the stream is unaffected.
.Pp
E 3
If the
D 3
.I stream
argument is NULL,
.I fflush
E 3
I 3
.Fa stream
argument is
.Dv NULL ,
.Fn fflush
E 3
flushes
D 3
.I all
E 3
I 3
.Em all
E 3
open output streams.
D 3
.PP
.I Fpurge
E 3
I 3
.Pp
The function
.Fn fpurge
E 3
erases any input or output buffered in the given
D 3
.IR stream .
E 3
I 3
.Fa stream .
E 3
For output streams this discards any unwritten output.
For input streams this discards any input read from the underlying object
but not yet obtained via
D 3
.IR getc ;
E 3
I 3
.Xr getc 3 ;
E 3
this includes any text pushed back via
D 3
.IR ungetc .
.SH "RETURN VALUE"
E 3
I 3
.Xr ungetc .
.Sh RETURN VALUES
E 3
Upon successful completion 0 is returned.
Otherwise,
D 3
.B EOF
E 3
I 3
.Dv EOF
E 3
is returned and the global variable
D 3
.I errno
E 3
I 3
.Va errno
E 3
is set to indicate the error.
D 3
.SH ERRORS
.TP 15
[EBADF]
.I Stream
E 3
I 3
.Sh ERRORS
.Bl -tag -width [EBADF]
.It Bq Er EBADF
.Fa Stream
E 3
is not an open stream, or, in the case of
D 3
.IR fflush ,
E 3
I 3
.Fn fflush ,
E 3
not a stream open for writing.
D 3
.PP
.I Fflush
E 3
I 3
.El
.Pp
The function
.Fn fflush
E 3
may also fail and set
D 3
.I errno
E 3
I 3
.Va errno
E 3
for any of the errors specified for the routine
D 3
.IR write (2).
.SH "SEE ALSO"
write(2), fopen(3), fclose(3), setbuf(3)
.SH STANDARDS
.I Fflush
conforms to ANSI X3.159-1989 (``ANSI C'').
E 3
I 3
.Xr write 2 .
.Sh SEE ALSO
.Xr write 2 ,
.Xr fopen 3 ,
.Xr fclose 3 ,
.Xr setbuf 3
.Sh STANDARDS
The
.Fn fflush
function
conforms to
.St -ansiC .
E 3
E 1
