h39267
s 00002/00002/00102
d D 8.1 93/06/06 15:39:31 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00033/00034/00071
d D 6.7 91/07/28 12:31:52 cael 10 9
c mdoc version three
e
s 00003/00001/00102
d D 6.6 91/03/14 00:23:15 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00103
d R 6.6 91/03/13 20:35:48 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00004/00001/00099
d D 6.5 90/07/24 22:49:03 cael 7 6
c .Xr botch fix
e
s 00072/00072/00028
d D 6.4 90/06/11 05:57:27 cael 6 5
c converted man page
e
s 00015/00003/00085
d D 6.3 89/08/17 13:33:37 bostic 5 4
c add Berkeley specific copyright notice
e
s 00002/00002/00086
d D 6.2 86/05/09 08:41:22 anne 4 3
c grammar
e
s 00001/00001/00087
d D 6.1 85/04/29 14:38:25 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00059/00029/00029
d D 5.1 85/04/29 14:38:14 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00058/00000/00000
d D 4.1 85/04/29 14:38:05 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1981 The Regents of the University of California.
E 6
I 6
D 11
.\" Copyright (c) 1981, 1990 The Regents of the University of California.
E 6
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1981, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 10
.\" %sccs.include.redist.man%
E 10
E 6
.\"
E 5
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
D 10
.\"     %W% (Berkeley) %G%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 6
.\"
I 9
D 10
.Vx
.Vx
E 10
I 10
.\"	%W% (Berkeley) %G%
.\"
E 10
E 9
I 5
D 6
.UC 7
E 5
D 2
.TH MT 1 5/11/81
E 2
I 2
D 3
.TH MT 1 "1 April 1983"
E 3
I 3
.TH MT 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
mt \- magnetic tape manipulating program
.SH SYNOPSIS
.B mt
[
D 2
.B \-t
E 2
I 2
.B \-f
E 2
.I tapename
]
.I command
[
.I count
]
.SH DESCRIPTION
D 2
.PP
E 2
.I Mt
E 6
I 6
.Dd %Q%
D 9
.Os BSD 4.4
E 9
I 9
D 10
.Os
E 10
E 9
.Dt MT 1
.Os BSD 4
.Sh NAME
.Nm mt
.Nd magnetic tape manipulating program
.Sh SYNOPSIS
.Nm mt
.Op Fl f Ar tapename
.Ar command
.Op Ar count
.Sh DESCRIPTION
.Nm Mt
E 6
D 2
is used to give commands to the tape drive.  If a tape name is not
specified, /dev/rmt12 is used.  If a count is not specified, 1 is assumed.
E 2
I 2
is used to give commands to a magnetic tape drive.
D 10
If a tape name is not specified, the environment variable
D 6
TAPE is used;  if TAPE does not exist,
.I mt
E 6
I 6
.Ev TAPE
is used;  if
.Ev TAPE
does not exist,
.Nm mt
E 6
uses the device
D 6
.IR /dev/rmt12 .
E 6
I 6
.Pa /dev/rmt12 .
E 6
Note
that
D 6
.I tapename
E 6
I 6
.Ar tapename
E 6
must reference a raw (not block) tape device.
E 10
By default
D 6
.I mt
E 6
I 6
.Nm mt
E 6
performs the requested operation once.  Operations
may be performed multiple times by specifying
D 6
.IR count .
E 2
.PP
E 6
I 6
.Ar count  .
I 10
Note
that
.Ar tapename
must reference a raw (not block) tape device.
E 10
.Pp
E 6
D 2
Here are the commands:
.in +.5i
.BR eof "	write"
E 2
I 2
The available commands are listed below.  Only as many
characters as are required to uniquely identify a command
need be specified.
D 6
.TP
.BR eof , " weof"
Write 
E 2
.I count
E 6
I 6
D 10
.Tp Cm eof , weof
E 10
I 10
.Bl -tag -width "eof, weof"
.It Cm eof , weof
E 10
Write
.Ar count
E 6
D 2
end-of-file marks
.br
.BR fsf "	space forward"
E 2
I 2
end-of-file marks at the current position on the tape.
D 6
.TP
.B fsf
E 6
I 6
D 10
.Tp Cm fsf
E 10
I 10
.It Cm fsf
E 10
E 6
Forward space
E 2
D 6
.I count
E 6
I 6
.Ar count
E 6
D 2
files
.br
.BR fsr "	space forward"
E 2
I 2
files.
D 6
.TP
.B fsr
Forward space 
E 2
.I count
E 6
I 6
D 10
.Tp Cm fsr
E 10
I 10
.It Cm fsr
E 10
Forward space
.Ar count
E 6
D 2
records
.br
.BR bsf "	space backward"
E 2
I 2
records.
D 6
.TP
.B bsf
Back space 
E 2
.I count
E 6
I 6
D 10
.Tp Cm bsf
E 10
I 10
.It Cm bsf
E 10
Back space
.Ar count
E 6
D 2
files
.br
.BR bsr "	space backward"
E 2
I 2
files.
D 6
.TP 
.B bsr
E 6
I 6
D 10
.Tp Cm bsr
E 10
I 10
.It Cm bsr
E 10
E 6
Back space
E 2
D 6
.I count
E 6
I 6
.Ar count
E 6
D 2
records
.br
.BR rew "	rewind tape"
.br
.BR offl "	rewind tape and go offline:
.in -.5i
E 2
I 2
records.
D 6
.TP
.B rewind
E 6
I 6
D 10
.Tp Cm rewind
E 10
I 10
.It Cm rewind
E 10
E 6
Rewind the tape
D 6
.RI ( Count
D 4
is ignored.)
E 4
I 4
is ignored). 
E 4
.TP
.BR offline , " rewoffl"
E 6
I 6
(Count is ignored).
D 10
.Tp Cm offline , rewoffl
E 10
I 10
.It Cm offline , rewoffl
E 10
E 6
Rewind the tape and place the tape unit off-line
D 6
.RI ( Count
D 4
is ignored.)
E 4
I 4
is ignored).
E 4
.TP
.B status
E 6
I 6
(Count is ignored).
D 10
.Tp Cm status
E 10
I 10
.It Cm status
E 10
E 6
Print status information about the tape unit.
D 6
.PP
.I Mt
E 6
I 6
D 10
.Tp
E 10
I 10
.El
E 10
.Pp
I 10
If a tape name is not specified, and the environment variable
.Ev TAPE
does not exist;
.Nm mt
uses the device
.Pa /dev/rmt12 .
.Pp
E 10
.Nm Mt
E 6
returns a 0 exit status when the operation(s) were successful,
1 if the command was unrecognized, and 2 if an operation failed.
E 2
D 6
.SH FILES
.DT
/dev/rmt*	Raw magnetic tape interface
D 2
.SH SEE ALSO
mt(4), dd(1)
.SH BUGS
E 2
I 2
.SH "SEE ALSO"
mtio(4), dd(1), ioctl(2), environ(7)
E 6
I 6
.Sh ENVIRONMENT
I 7
If the following environment variable exists, it is utilized by
.Nm mt .
E 7
D 10
.Tw Fl
.Tp Ev TAPE
E 10
I 10
.Bl -tag -width Fl
.It Ev TAPE
E 10
.Nm Mt
checks the
.Ev TAPE
environment variable if the
argument
D 7
.Ar tapename is not given.
E 7
I 7
.Ar tapename
is not given.
E 7
.Sh FILES
D 10
.Dw /dev/rmt*
.Di L
.Dp Pa /dev/rmt*
E 10
I 10
.Bl -tag -width /dev/rmt* -compact
.It Pa /dev/rmt*
E 10
Raw magnetic tape interface
D 10
.Dp
E 10
I 10
.El
E 10
.Sh SEE ALSO
.\".Xr mtio 4 ,
.Xr dd 1 ,
.Xr ioctl 2 ,
.Xr environ 7
.Sh HISTORY
D 10
.Nm Mt
appeared in 4.3 BSD.
E 10
I 10
The
.Nm mt
command appeared in
.Bx 4.3 .
E 10
.\" mt.1: mtio(4) missing
E 6
E 2
E 1
