h16591
s 00001/00000/00119
d D 8.2 94/06/01 21:00:18 ah 9 8
c page breaks for 4.4BSD manuals
e
s 00002/00002/00117
d D 8.1 93/06/09 19:21:18 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00002/00118
d D 6.4 93/06/09 19:21:15 bostic 7 5
c fixed the under development line
e
s 00002/00002/00118
d R 8.1 93/06/06 14:18:59 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00060/00037/00060
d D 6.3 91/05/10 13:11:15 cael 5 4
c mdoc version three
e
s 00078/00038/00019
d D 6.2 91/01/17 18:21:09 bostic 4 3
c new versionl; document all known BSD formats
e
s 00001/00001/00056
d D 6.1 85/05/15 18:22:19 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00007/00020/00050
d D 5.1 85/05/15 18:21:55 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00070/00000/00000
d D 4.1 85/05/15 18:21:18 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 5
.\" Copyright (c) 1990 The Regents of the University of California.
E 5
I 5
D 8
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 5
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
D 5
.\" %sccs.include.redist.man%
E 5
I 5
.\" %sccs.include.redist.roff%
E 5
.\"
E 4
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH AR 5 
E 2
I 2
D 3
.TH AR 5  "15 January 1983"
E 3
I 3
D 5
.TH AR 5  "%Q%"
E 3
E 2
.AT 3
.SH NAME
ar \- archive (library) file format
.SH SYNOPSIS
.B #include <ar.h>
.SH DESCRIPTION
D 2
.IR N.B. :
This archive format is new to this distribution.
See
.IR old (8)
and
.IR arcv (1)
for programs to deal with the old format.
E 2
.PP
E 5
I 5
.Dd %Q%
.Dt AR 5
.Os
.Sh NAME
.Nm ar
.Nd archive (library) file format
.Sh SYNOPSIS
.Fd #include <ar.h>
.Sh DESCRIPTION
E 5
The archive command
D 4
.I ar
E 4
I 4
D 5
.IR ar
E 5
I 5
.Nm ar
E 5
E 4
D 2
is used to combine several files into
one.
Archives are used mainly as libraries to be searched
by the link-editor
E 2
I 2
combines several files into one.
D 4
Archives are used mainly as libraries to be searched by the link-editor
E 2
.I ld.
E 4
I 4
Archives are mainly used as libraries of object files intended to be
loaded using the link-editor
D 5
.IR ld (1).
E 4
.PP
E 5
I 5
.Xr ld 1 .
.Pp
E 5
D 4
A file produced by
E 4
I 4
A file created with
E 4
D 5
.I ar
E 5
I 5
.Nm ar
E 5
D 4
has a magic string at the start,
followed by the constituent files, each preceded by a file header.
D 2
The magic number and header layout as described in the
include file are:
E 2
I 2
The magic number and header layout as described in the include file are:
E 2
.RS
E 4
I 4
begins with the ``magic'' string "!<arch>\en".
The rest of the archive is made up of objects, each of which is composed
of a header for a file, a possible file name, and the file contents.
The header is portable between machine architectures, and, if the file
contents are printable, the archive is itself printable.
E 4
D 5
.PP
D 4
.nf
.ta \w'#define 'u +\w'SARMAG 'u
.ec %
.so /usr/include/ar.h
.ec \
.fi
.RE
.LP
The name is a blank-padded string.
The
.I ar_fmag
D 2
field contains ARFMAG
to help verify the presence of a header.
E 2
I 2
field contains ARFMAG to help verify the presence of a header.
E 2
The other fields are left-adjusted, blank-padded numbers.
They are decimal except for
.IR ar_mode ,
which is octal.
The date is the modification date of the file
at the time of its insertion into the archive.
E 4
I 4
The header is made up of six variable length ASCII fields, followed by a
E 5
I 5
.Pp
The header is made up of six variable length
.Tn ASCII
fields, followed by a
E 5
two character trailer.
The fields are the object name (16 characters), the file last modification
time (12 characters), the user and group id's (each 6 characters), the file
mode (8 characters) and the file size (10 characters).
All numeric fields are in decimal, except for the file mode which is in
octal.
E 4
D 5
.PP
D 4
Each file begins on a even (0 mod 2) boundary;
a new-line is inserted between files if necessary.
Nevertheless the size given reflects the
actual size of the file exclusive of padding.
E 4
I 4
The modification time is the file st_mtime field, i.e., CUT seconds since
E 5
I 5
.Pp
The modification time is the file
.Fa st_mtime
field, i.e.,
.Dv CUT
seconds since
E 5
the epoch.
D 5
The user and group id's are the file st_uid and st_gid fields.
The file mode is the file st_mode field.
The file size is the file st_size field.
E 5
I 5
The user and group id's are the file
.Fa st_uid
and
.Fa st_gid
fields.
The file mode is the file
.Fa st_mode
field.
The file size is the file
.Fa st_size
field.
E 5
The two-byte trailer is the string "\`\en".
E 4
D 5
.PP
E 5
I 5
.Pp
E 5
D 2
There is no provision for empty areas in an archive
file.
E 2
I 2
D 4
There is no provision for empty areas in an archive file.
E 4
I 4
Only the name field has any provision for overflow.
If any file name is more than 16 characters in length or contains an
D 5
embedded space, the string "#1/" followed by the ASCII length of the
E 5
I 5
embedded space, the string "#1/" followed by the
.Tn ASCII
length of the
E 5
name is written in the name field.
The file size (stored in the archive header) is incremented by the length
of the name.
The name is then written immediately following the archive header.
E 4
E 2
D 5
.PP
E 5
I 5
.Pp
E 5
D 4
The encoding of the header is portable across machines.
D 2
If an archive contains printable files, the archive itself
is printable.
E 2
I 2
If an archive contains printable files, the archive itself is printable.
E 4
I 4
Any unused characters in any of these fields are written as space
characters.
If any fields are their particular maximum number of characters in
length, there will be no separation between the fields.
D 5
.PP
E 5
I 5
.Pp
E 5
Objects in the archive are always an even number of bytes long; files
which are an odd number of bytes long are padded with a newline (``\en'')
character, although the size in the header does not reflect this.
E 4
E 2
D 5
.SH "SEE ALSO"
D 4
ar(1), ld(1), nm(1)
.SH BUGS
File names lose trailing blanks.
Most software dealing with archives takes even
an included blank as a name terminator.
E 4
I 4
ar(1), stat(2)
.SH HISTORY
E 5
I 5
.Sh SEE ALSO
.Xr ar 1 ,
.Xr stat 2
.Sh HISTORY
E 5
There have been at least four
D 5
.I ar
E 5
I 5
.Nm ar
E 5
formats.
The first was denoted by the leading ``magic'' number 0177555 (stored as
type int).
These archives were almost certainly created on a 16-bit machine, and
contain headers made up of five fields.
The fields are the object name (8 characters), the file last modification
time (type long), the user id (type char), the file mode (type char) and
the file size (type unsigned int).
Files were padded to an even number of bytes.
D 5
.PP
E 5
I 5
.Pp
E 5
The second was denoted by the leading ``magic'' number 0177545 (stored as
type int).
These archives may have been created on either 16 or 32-bit machines, and
contain headers made up of six fields.
The fields are the object name (14 characters), the file last modification
time (type long), the user and group id's (each type char), the file mode
(type int) and the file size (type long).
Files were padded to an even number of bytes.
For more information on converting from this format see
D 5
.IR arcv (8).
.PP
E 5
I 5
.Xr arcv 8 .
I 9
.ne 1i
E 9
.Pp
E 5
The current archive format (without support for long character names and
D 5
names with embedded spaces) was introduced in 4.0BSD.
E 5
I 5
names with embedded spaces) was introduced in
.Bx 4.0 .
E 5
The headers were the same as the current format, with the exception that
names longer than 16 characters were truncated, and names with embedded
spaces (and often trailing spaces) were not supported.
D 5
It was extended for these reasons in 4.4BSD, as described above.
.SH COMPATIBILITY
E 5
I 5
It has been extended for these reasons,
as described above.
D 7
This format is
.Ud .
E 7
I 7
This format first appeared in 4.4BSD.
E 7
.Sh COMPATIBILITY
E 5
No archive format is currently specified by any standard.
D 5
System V has historically distributed archives in a different format from
E 5
I 5
.At V
has historically distributed archives in a different format from
E 5
all of the above.
E 4
E 1
