h41349
s 00001/00001/00293
d D 8.4 95/04/28 09:30:08 bostic 18 17
c formatting error in NetBSD's version
c From: Charles Hannum <mycroft@NetBSD.ORG>
e
s 00010/00008/00284
d D 8.3 95/04/28 09:29:18 bostic 17 16
c reapply Kirk's 6.11 revision to the new page
e
s 00177/00116/00115
d D 8.2 95/04/28 09:26:20 bostic 16 15
c convert to mandoc (starting with version 6.10)
c From: Charles Hannum <mycroft@NetBSD.ORG>
e
s 00002/00002/00229
d D 8.1 93/06/29 16:16:24 bostic 15 14
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00010/00008/00221
d D 6.11 93/06/29 16:16:05 mckusick 14 12
c grammer nits
e
s 00002/00002/00227
d R 8.1 93/06/06 14:18:51 bostic 13 12
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00012/00012/00217
d D 6.10 91/03/21 12:15:59 bostic 12 11
c rename -s option to -T (Sys V. compatibility)
e
s 00009/00009/00220
d D 6.9 91/03/12 10:07:37 bostic 11 10
c minor cleanups, describe the -p option correctly
e
s 00030/00009/00199
d D 6.8 91/03/11 14:31:50 bostic 10 9
c document POSIX and more compatibility stuff for -s
c change so that the command line file name is used for error/info messages
e
s 00006/00003/00202
d D 6.7 91/03/11 10:27:43 bostic 9 8
c get truncated names right -- it's 15 chars, not 16
e
s 00020/00009/00185
d D 6.6 91/03/10 16:26:05 bostic 8 7
c add -s option which inserts/matches truncated member names
e
s 00190/00160/00004
d D 6.5 91/01/17 18:17:17 bostic 7 6
c new version; approximate POSIX compliance
e
s 00004/00003/00160
d D 6.4 90/07/24 22:40:39 cael 6 5
c .Xr botch fix
e
s 00003/00004/00160
d D 6.3 90/06/26 00:58:34 cael 5 4
c converted man page
e
s 00086/00069/00078
d D 6.2 90/06/11 05:52:47 cael 4 3
c converted man page
e
s 00001/00001/00146
d D 6.1 85/04/29 19:59:11 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00014/00007/00133
d D 5.1 85/04/29 19:58:38 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00140/00000/00000
d D 4.1 85/04/29 19:58:15 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 4
.\"
D 2
.TH AR 1 
E 2
I 2
D 3
.TH AR 1 "24 February 1979"
E 3
I 3
D 4
.TH AR 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
ar \- archive and library maintainer
.SH SYNOPSIS
.B ar
key [ posname ] afile name ...
.SH DESCRIPTION
.I Ar
E 4
I 4
.\" %sccs.include.redist.man%
E 5
I 5
D 7
.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 15
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 15
I 15
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 15
E 7
E 5
.\"
D 7
.\"     %W% (Berkeley) %G%
E 7
I 7
.\" This code is derived from software contributed to Berkeley by
.\" Hugh Smith at The University of Guelph.
E 7
.\"
D 7
.Dd %Q%
.Dt AR 1
.Os ATT 7th
.Sh NAME
.Nm ar
.Nd archive and library maintainer
.Sh SYNOPSIS
.Nm ar
.Cm key
.Op Ar posname
.Ar afile name ...
.Sh DESCRIPTION
.Nm Ar
E 4
maintains groups of files
combined into a single archive file.
Its main use
is to create and update library files as used by the loader.
It can be used, though, for any similar purpose.
D 4
.B N.B:
E 4
I 4
.Sy N.B.:
E 4
This version of
D 4
.I ar
E 4
I 4
.Nm ar
E 4
uses a ASCII-format archive which is portable among the various
D 4
machines running \s-2UNIX\s0.
E 4
I 4
machines running UNIX.
E 4
Programs for dealing with older formats are available: see
D 2
.IR old (8).
E 2
I 2
D 4
.IR arcv (8).
E 2
.PP
.I Key
E 4
I 4
.Xr arcv 8 .
.Pp
.Cm Key
E 4
is one character from the set
D 4
.B drqtpmx,
E 4
I 4
.Fl drqtpmx
E 4
optionally concatenated with
one or more of
D 2
.B vuaibcl.
E 2
I 2
D 4
.B vuaibclo.
E 2
.I Afile
E 4
I 4
.Fl vuaibclo .
.Ar Afile
E 4
is the archive file.
E 7
I 7
.\" %sccs.include.redist.man%
.\"
.\"	%W% (Berkeley) %G%
.\"
D 16
.TH AR 1 "%Q%"
.AT 3
.SH NAME
ar \- create and maintain library archives
.SH SYNOPSIS
.nf
.ft B
D 8
ar -d [-v] archive file ...
ar -m [-v] archive file ...
ar -m [-abiv] position archive file ...
ar -p [-v] archive [file ...]
ar -q [-cv] archive file ...
ar -r [-cuv] archive file ...
ar -r [-abciuv] position archive file ...
ar -t [-v] archive [file ...]
ar -x [-ouv] archive [file ...]
E 8
I 8
D 12
ar -d [-sv] archive file ...
ar -m [-sv] archive file ...
ar -m [-abisv] position archive file ...
ar -p [-sv] archive [file ...]
ar -q [-csv] archive file ...
ar -r [-cusv] archive file ...
ar -r [-abciusv] position archive file ...
ar -t [-sv] archive [file ...]
ar -x [-ousv] archive [file ...]
E 12
I 12
ar -d [-Tv] archive file ...
ar -m [-Tv] archive file ...
ar -m [-abiTv] position archive file ...
ar -p [-Tv] archive [file ...]
ar -q [-cTv] archive file ...
ar -r [-cuTv] archive file ...
ar -r [-abciuTv] position archive file ...
ar -t [-Tv] archive [file ...]
ar -x [-ouTv] archive [file ...]
E 12
E 8
.fi
.ft R
.SH DESCRIPTION
E 16
I 16
.Dd "%Q%"
.Dt AR 1 
.Os
.Sh NAME
.Nm ar 
.Nd create and maintain library archives
.Sh SYNOPSIS
.Nm ar
.Fl d 
.Op Fl \Tv 
.Ar archive file ...
.Nm ar
.Fl m
.Op Fl \Tv 
.Ar archive file ...
.Nm ar
.Fl m
.Op Fl abiTv 
.Ar position archive file ...
.Nm ar
.Fl p
.Op Fl \Tv
.Ar archive
.Op Ar file ...
.Nm ar
.Fl q
.Op Fl cTv
.Ar archive file ...
.Nm ar
.Fl r
.Op Fl cuTv
.Ar archive file ...
.Nm ar
.Fl r
.Op Fl abciuTv
.Ar position archive file ...
.Nm ar
.Fl t
.Op Fl \Tv
.Ar archive
.Op Ar file ...
.Nm ar
.Fl x
.Op Fl ouTv
.Ar archive
.Op Ar file ...
.Sh DESCRIPTION
E 16
E 7
The
D 4
.I names
E 4
I 4
D 7
.Ar names
E 4
are constituent files in the archive file.
The meanings of the
D 4
.I key
E 4
I 4
.Fl key
E 4
characters are:
D 4
.TP
.B d
E 4
I 4
.Tp Fl d
E 4
Delete the named files from the archive file.
D 4
.TP
.B r
E 4
I 4
.Tp Fl r
E 4
Replace the named files in the archive file.
If the optional character
D 4
.B u
E 4
I 4
.Fl u
E 4
is used with
D 4
.B r,
D 2
then only those files with
modified dates later than
E 2
I 2
then only those files with `last-modified' dates later than
E 4
I 4
.Fl r
then only those files with
.Li last-modified
dates later than
E 4
E 2
the archive files are replaced.
If an optional positioning character from the set
D 4
.B abi
E 4
I 4
.Fl abi
E 4
is used, then the
D 4
.I posname
E 4
I 4
.Ar posname
E 4
argument must be present
and specifies that new files are to be placed
after
D 4
.RB ( a )
E 4
I 4
.Fl a
E 4
or before
D 4
.RB ( b
E 4
I 4
.Fl b
E 4
or
D 4
.BR i )
.IR posname .
E 4
I 4
.Fl i
.Ar posname .
E 4
Otherwise
new files are placed at the end.
D 4
.TP
.B q
E 4
I 4
.Tp Fl q
E 4
Quickly append the named files to the end of the archive file.
Optional positioning characters are invalid.
The command does not check whether the added members
are already in the archive.
Useful only to avoid quadratic behavior when creating a large
archive piece-by-piece.
D 4
.TP
.B t
E 4
I 4
.Tp Fl t
E 4
Print a table of contents of the archive file.
If no names are given, all files in the archive are tabled.
If names are given, only those files are tabled.
D 4
.TP
.B p
E 4
I 4
.Tp Fl p
E 4
Print the named files in the archive.
D 4
.TP
.B m
E 4
I 4
.Tp Fl m
E 4
Move the named files to the end of the archive.
If a positioning character is present,
then the
D 4
.I posname
E 4
I 4
.Ar posname
E 4
argument must be present and,
as in
D 4
.B r,
E 4
I 4
.Fl r
E 4
specifies where the files are to be moved.
D 4
.TP
.B x
E 4
I 4
.Tp Fl x
E 4
Extract the named files.
If no names are given, all files in the archive are
extracted.
In neither case does
D 4
.B x
E 4
I 4
.Fl x
E 4
D 2
alter the archive file.
E 2
I 2
alter the archive file. Normally the `last-modified' date of each
extracted file is the date when it is extracted. However, if
D 4
.B o
E 4
I 4
.Fl o
E 4
is used, the `last-modified' date is reset to the date recorded in the
archive.
E 2
D 4
.TP
.B v
E 4
I 4
.Tp Fl v
E 4
Verbose.
Under the verbose option,
D 4
.I ar
E 4
I 4
.Nm ar
E 4
gives a file-by-file
description of the making of a
new archive file from the old archive and the constituent files.
When used with
D 4
.B t,
E 4
I 4
.Fl t
E 4
it gives a long listing of all information about the files.
When used with
D 4
.BR p ,
E 4
I 4
.Fl p ,
E 4
it precedes each file with a name.
D 4
.TP
.B c
E 4
I 4
.Tp Fl c
E 4
Create.
Normally
D 4
.I ar
E 4
I 4
.Nm ar
E 4
will create
D 4
.I afile
E 4
I 4
.Ar afile
E 4
when it needs to.
The create option suppresses the
normal message that is produced when
D 4
.I afile
E 4
I 4
.Ar afile
E 4
is created.
D 4
.TP
.B l
E 4
I 4
.Tp Fl l
E 4
Local.
Normally
D 4
.I ar
E 4
I 4
.Nm ar
E 4
places its temporary files in the directory /tmp.
This option causes them to be placed in the local directory.
D 4
.SH FILES
/tmp/v*	temporaries
.SH "SEE ALSO"
D 2
lorder(1), ld(1), ranlib(1), ar(5), arcv(8), old(8)
E 2
I 2
lorder(1), ld(1), ranlib(1), ar(5), arcv(8)
E 2
.SH BUGS
E 4
I 4
.Tp
.Sh FILES
D 6
.Tw /tmp/v*
.Tp Pa tmp/v*
E 6
I 6
.Dw /tmp/v*
.Di L
.Dp Pa tmp/v*
E 6
temporaries
D 6
.Tp
E 6
I 6
.Dp
E 6
.Sh SEE ALSO
.Xr lorder 1 ,
.Xr ld 1 ,
.Xr ranlib 1 ,
.Xr ar 5 ,
.Xr arcv 8
.Sh HISTORY
.Nm Ar
appeared in vanilla Version 6 AT&T UNIX.  The Version 7
.Nm ar
appeared
in 2.0 BSD.
.Sh BUGS
E 4
If the same file is mentioned twice in an argument list,
it may be put in the archive twice.
I 2
D 4
.LP
The `last-modified' date of a file will not be altered by the
.B o
E 4
I 4
.Pp
E 7
I 7
D 16
.I ar
E 16
I 16
.Nm ar
E 16
utility creates and maintains groups of files combined into an archive.
Once an archive has been created, new files can be added and existing
files can be extracted, deleted, or replaced.
D 16
.PP
E 16
I 16
.Pp
E 16
Files are named in the archive by a single component, i.e., if a file
referenced by a path containing a slash (``/'') is archived it will be
named by the last component of that path.
When matching paths listed on the command line against file names stored
in the archive, only the last component of the path will be compared.
D 10
All informational and error messages use the file name as found in the
archive, not the path listed on the command line.
E 10
I 10
D 16
.PP
E 16
I 16
.Pp
E 16
All informational and error messages use the path listed on the command
D 11
archive, not the name entered in the archive unless no name was supplied
on the command line.
E 11
I 11
D 14
line, if any was specified, otherwise the name in the archive is used.
E 14
I 14
D 16
line, if any was specified; otherwise the name in the archive is used.
E 16
I 16
D 17
line, if any was specified, otherwise the name in the archive is used.
E 17
I 17
line, if any was specified; otherwise the name in the archive is used.
E 17
E 16
E 14
E 11
E 10
If multiple files in the archive have the same name, and paths are listed
on the command line to ``select'' archive files for an operation, only the
D 16
.B first
E 16
I 16
.Em first
E 16
file with a matching name will be selected.
D 16
.PP
E 16
I 16
.Pp
E 16
The normal use of
D 16
.I ar
E 16
I 16
.Nm ar
E 16
is for the creation and maintenance of libraries suitable for use with
the loader (see
D 14
.IR ld (1))
E 14
I 14
D 16
.IR ld (1)),
E 16
I 16
D 17
.Xr ld 1 )
E 17
I 17
.Xr ld 1 ),
E 17
E 16
E 14
although it is not restricted to this purpose.
The options are as follows:
D 16
.TP
\-a
A positioning modifier used with the options \-r and \-m.
E 16
I 16
.Bl -tag -width indent
D 18
It Fl a
E 18
I 18
.It Fl a
E 18
A positioning modifier used with the options 
.Fl r 
and 
.Fl m .
E 16
The files are entered or moved
D 16
.B after
E 16
I 16
.Em after
E 16
the archive member
D 16
.IR position ,
E 16
I 16
.Ar position ,
E 16
which must be specified.
D 16
.TP
\-b
A positioning modifier used with the options \-r and \-m.
E 16
I 16
.It Fl b
A positioning modifier used with the options
.Fl r 
and 
.Fl m .
E 16
The files are entered or moved
D 16
.B before
E 16
I 16
.Em before
E 16
the archive member
D 16
.IR position ,
E 16
I 16
.Ar position ,
E 16
which must be specified.
D 16
.TP
\-c
E 16
I 16
.It Fl c
E 16
Whenever an archive is created, an informational message to that effect
is written to standard error.
D 16
If the \-c option is specified,
.I ar
E 16
I 16
If the 
.Fl c
option is specified,
.Nm ar
E 16
creates the archive silently.
D 16
.TP
\-d
E 16
I 16
.It Fl d
E 16
Delete the specified archive files.
D 16
.TP
\-i
Identical to the \-b option.
.TP
\-m
E 16
I 16
.It Fl i
Identical to the 
.Fl b
option.
.It Fl m
E 16
Move the specified archive files within the archive.
D 14
If one of the options \-a, \-b or \-i are specified, the files are moved
E 14
I 14
D 16
If one of the options \-a, \-b or \-i is specified, the files are moved
E 14
before or after the
.I position
E 16
I 16
If one of the options 
.Fl a , 
.Fl b 
or 
.Fl i
D 17
are specified, the files are moved before or after the
E 17
I 17
is specified, the files are moved before or after the
E 17
.Ar position
E 16
file in the archive.
If none of those options are specified, the files are moved
to the end of the archive.
D 16
.TP
\-o
E 16
I 16
.It Fl o
E 16
Set the access and modification times of extracted files to the
modification time of the file when it was entered into the archive.
This will fail if the user is not the owner of the extracted file
or the super-user.
D 16
.TP
\-p
E 16
I 16
.It Fl p
E 16
Write the contents of the specified archive files to the standard output.
If no files are specified, the contents of all the files in the archive
are written in the order they appear in the archive.
D 16
.TP
\-q
E 16
I 16
.It Fl q
E 16
(Quickly) append the specified files to the archive.
If the archive does not exist a new archive file is created.
D 16
Much faster than the \-r option, when creating a large archive
E 16
I 16
Much faster than the 
.Fl r
option, when creating a large archive
E 16
piece-by-piece, as no checking is done to see if the files already
exist in the archive.
D 16
.TP
\-r
E 16
I 16
.It Fl r
E 16
Replace or add the specified files to the archive.
If the archive does not exist a new archive file is created.
Files that replace existing files do not change the order of the files
within the archive.
D 16
New files are appended to the archive unless one of the options \-a, \-b
or \-i is specified.
I 8
.TP
D 12
\-s
E 12
I 12
\-T
E 16
I 16
New files are appended to the archive unless one of the options 
.Fl a ,
.Fl b
or 
.Fl i
is specified.
.It Fl T
E 16
E 12
D 9
Truncate file names as necessary to fit in the standard archive file
format (which has only sixteen bytes for the name).
This means that file names that are not unique in their first sixteen
E 9
I 9
D 10
Truncate file names to fit in the historical archive file format.
The historic format had sixteen bytes for the name, but historic
implementations couldn't handle names that used the entire space,
so this option causes file names longer than fifteen characters to
be truncated.
E 10
I 10
Select and/or name archive members using only the first fifteen characters
of the archive member or command line file name.
The historic archive format had sixteen bytes for the name, but some
historic archiver and loader implementations were unable to handle names
that used the entire space.
E 10
This means that file names that are not unique in their first fifteen
E 9
characters can subsequently be confused.
A warning message is printed to the standard error output if any file
names are truncated.
(See
D 16
.IR ar (5)
E 16
I 16
.Xr ar 5
E 16
for more information.)
E 8
D 16
.TP
\-t
E 16
I 16
.It Fl t
E 16
List the specified files in the order in which they appear in the archive,
each on a separate line.
If no files are specified, all files in the archive are listed.
D 16
.TP
\-u
E 16
I 16
.It Fl u
E 16
Update files.
D 16
When used with the \-r option, files in the archive will be replaced
E 16
I 16
When used with the 
.Fl r
option, files in the archive will be replaced
E 16
only if the disk file has a newer modification time than the file in
the archive.
D 16
When used with the \-x option, files in the archive will be extracted
E 16
I 16
When used with the 
.Fl x
option, files in the archive will be extracted
E 16
only if the archive file has a newer modification time than the file
on disk.
D 16
.TP
\-v
E 16
I 16
.It Fl v
E 16
Provide verbose output.
D 16
When used with the \-d, \-m, \-q or \-x options,
.I ar
E 16
I 16
When used with the 
.Fl d , 
.Fl m , 
.Fl q 
or 
.Fl x
options,
.Nm ar
E 16
gives a file-by-file description of the archive modification.
This description consists of three, white-space separated fields: the
option letter, a dash (``-'') and the file name.
D 16
When used with the \-r option,
.I ar
E 16
I 16
When used with the 
.Fl r
option,
.Nm ar
E 16
displays the description as above, but the initial letter is an ``a'' if
the file is added to the archive and an ``r'' if the file replaces a file
already in the archive.
D 16
.IP
When used with the \-p option,
D 14
the name of each printed file is written to the standard output before
D 11
the contents of the file, on a line by itself, enclosed in less-than
(``<'') and greater-than (``>'') characters.
E 11
I 11
the contents of the file, preceded by a single newline character, and
followed by two newline characters, enclosed in less-than (``<'') and
greater-than (``>'') characters.
E 14
I 14
the name of each printed file,
enclosed in less-than (``<'') and greater-than (``>'') characters,
is written to the standard output before
the contents of the file;
it is preceded by a single newline character, and
followed by two newline characters.
E 14
E 11
.IP
When used with the \-t option,
.I ar
E 16
I 16
.Pp
When used with the 
.Fl p 
option,
D 17
the name of each printed file is written to the standard output before
the contents of the file, preceded by a single newline character, and
followed by two newline characters, enclosed in less-than (``<'') and
greater-than (``>'') characters.
E 17
I 17
the name of each printed file,
enclosed in less-than (``<'') and greater-than (``>'') characters,
is written to the standard output before
the contents of the file;
it is preceded by a single newline character, and
followed by two newline characters.
E 17
.Pp
When used with the 
.Fl t
option,
.Nm ar
E 16
D 11
displays an ``ls -l'' style listing of information about the files in
E 11
I 11
displays an ``ls -l'' style listing of information about the members of
E 11
the archive.
This listing consists of eight, white-space separated fields:
the file permissions (see
D 16
.IR strmode (3)),
D 14
the decimal user and group ID's, separated by a single slash (``/''),
E 14
I 14
the decimal user and group ID's separated by a single slash (``/''),
E 16
I 16
.Xr strmode 3 ),
D 17
the decimal user and group ID's, separated by a single slash (``/''),
E 17
I 17
the decimal user and group ID's separated by a single slash (``/''),
E 17
E 16
E 14
the file size (in bytes), the file modification time (in the
D 16
.IR date (1)
E 16
I 16
.Xr date 1
E 16
format ``%b %e %H:%M %Y''), and the name of the file.
D 16
.TP
\-x
E 16
I 16
.It Fl x
E 16
D 11
Extract the specified files into the files named by the command line
arguments.
If no files are specified, all the files in the archive are extracted into
E 11
I 11
Extract the specified archive members into the files named by the command
line arguments.
If no members are specified, all the members of the archive are extracted into
E 11
the current directory.
D 16
.IP
E 16
I 16
.Pp
E 16
If the file does not exist, it is created; if it does exist, the owner
and group will be unchanged.
The file access and modification times are the time of the extraction
D 16
(but see the \-o option).
E 16
I 16
(but see the 
.Fl o
option).
E 16
The file permissions will be set to those of the file when it was entered
into the archive; this will fail if the user is not the owner of the
extracted file or the super-user.
D 16
.PP
E 16
I 16
.El
.Pp
E 16
E 7
The
D 7
.Li last-modified
date of a file will not be altered by the
.Fl o
E 4
option if the user is not the owner of the extracted file, or the super-user.
E 7
I 7
D 16
.I ar
E 16
I 16
.Nm ar
E 16
utility exits 0 on success, and >0 if an error occurs.
D 16
.SH ENVIRONMENT
.TP
TMPDIR
E 16
I 16
.Sh ENVIRONMENT
.Bl -tag -width indent -compact
.It Ev TMPDIR
E 16
The pathname of the directory to use when creating temporary files.
D 10
.PP
E 10
D 16
.SH FILES
.TP 14
/tmp
E 16
I 16
.El
.Sh FILES
.Bl -tag -width indent -compact
.It Pa /tmp
E 16
default temporary file directory
D 16
.TP 14
ar.XXXXXX
E 16
I 16
.It Pa ar.XXXXXX
E 16
temporary file names
I 10
D 16
.SH COMPATIBILITY
E 16
I 16
.El
.Sh COMPATIBILITY
E 16
By default,
D 16
.I ar
E 16
I 16
.Nm ar
E 16
writes archives that may be incompatible with historic archives, as
the format used for storing archive members with names longer than
fifteen characters has changed.
This implementation of
D 16
.I ar
E 16
I 16
.Nm ar
E 16
is backward compatible with previous versions of
D 16
.I ar
D 12
in that it can read and write (using the \-s option) historic archives.
The \-s option is provided for compatibility only, and will be deleted
E 12
I 12
in that it can read and write (using the \-T option) historic archives.
The \-T option is provided for compatibility only, and will be deleted
E 16
I 16
.Nm ar
in that it can read and write (using the 
.Fl T
option) historic archives.
The 
.Fl T
option is provided for compatibility only, and will be deleted
E 16
E 12
in a future release.
See
D 16
.IR ar (5)
E 16
I 16
.Xr ar 5
E 16
for more information.
.SH STANDARDS
The
D 16
.I ar
utility is expected to offer a superset of the POSIX 1003.2 functionality.
E 10
.SH "SEE ALSO"
D 10
date(1), ld(1), ranlib(1), strmode(3), ar(5)
E 10
I 10
D 11
ld(1), ranlib(1), ar(5)
E 11
I 11
ld(1), ranlib(1), strmode(3), ar(5)
E 16
I 16
.Nm ar
utility is expected to offer a superset of the 
.St -p1003.2
functionality.
.Sh SEE ALSO
.Xr ld 1 , 
.Xr ranlib 1 ,
.Xr strmode 3 ,
.Xr ar 5
E 16
E 11
E 10
E 7
E 2
E 1
