h00877
s 00001/00000/00349
d D 8.4 94/06/01 20:38:44 ah 12 11
c page breaks for 4.4BSD manuals
e
s 00057/00026/00292
d D 8.3 94/04/13 13:04:36 karels 11 10
c restore my 1985 change to pass the listening socket to "stream wait" servers;
c document this, and correct the description of wait vs. nowait for datagram,
c plus other man page cleanups
e
s 00001/00001/00317
d D 8.2 93/12/11 23:44:38 mckusick 10 9
c copyediting for Usenix manuals
e
s 00002/00002/00316
d D 8.1 93/06/06 13:57:13 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00125/00003/00193
d D 6.8 93/02/01 22:50:29 andrew 8 7
c document tcpmux stuff; add examples and errors sections
e
s 00136/00077/00060
d D 6.7 91/03/16 18:12:28 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00002/00012/00135
d D 6.6 90/06/24 22:19:41 trent 6 5
c new copyright & pathname (inetd)
e
s 00016/00005/00131
d D 6.5 88/09/19 21:35:27 bostic 5 4
c Berkeley copyright
e
s 00005/00000/00131
d D 6.4 86/05/26 13:23:13 karels 4 3
c sighup restarts
e
s 00010/00003/00121
d D 6.3 86/05/22 20:42:22 karels 3 2
c update
e
s 00000/00003/00124
d D 6.2 86/05/13 19:35:51 karels 2 1
c I disagree
e
s 00127/00000/00000
d D 6.1 85/04/27 16:15:03 mckusick 1 0
c manual page first distributed with 4.3BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1985 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1985, 1991 The Regents of the University of California.
E 8
I 8
D 9
.\" Copyright (c) 1985, 1991, 1993 The Regents of the University of California.
E 8
E 7
.\" All rights reserved.
E 9
I 9
D 11
.\" Copyright (c) 1985, 1991, 1993
E 11
I 11
.\" Copyright (c) 1985, 1991, 1993, 1994
E 11
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
E 5
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 7
.TH INETD 8 "%Q%"
.UC 6
.SH NAME
inetd \- internet ``super\-server''
.SH SYNOPSIS
D 6
.B /etc/inetd
E 6
I 6
.B inetd
E 6
[
.B \-d
] [ configuration file ]
.SH DESCRIPTION
.I Inetd
E 7
I 7
.Dd %Q%
.Dt INETD 8
D 8
.Os BSD 4.3
E 8
I 8
.Os BSD 4.4
E 8
.Sh NAME
.Nm inetd
.Nd internet
.Dq super-server
.Sh SYNOPSIS
.Nm inetd
.Op Fl d
I 8
.Op Fl R Ar rate
E 8
.Op Ar configuration file
.Sh DESCRIPTION
D 11
.Nm Inetd
E 11
I 11
The
.Nm inetd
program
E 11
E 7
should be run at boot time by
D 7
.IR /etc/rc.local .
E 7
I 7
D 11
.Pa /etc/rc.local
E 11
I 11
.Pa /etc/rc
E 11
(see
.Xr rc 8 ) .
E 7
It then listens for connections on certain
internet sockets.  When a connection is found on one
of its sockets, it decides what service the socket
corresponds to, and invokes a program to service the request.
I 11
The server program is invoked with the service socket
as its standard input, output and error descriptors.
E 11
After the program is
D 11
finished, it continues to listen on the socket (except in some cases which
E 11
I 11
finished,
.Nm inetd
continues to listen on the socket (except in some cases which
E 11
will be described below).  Essentially,
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
allows running one daemon to invoke several others,
reducing load on the system.
D 7
.PP
E 7
I 7
.Pp
D 8
The option available for
E 8
I 8
The options available for
E 8
.Nm inetd:
.Bl -tag -width Ds
.It Fl d
Turns on debugging.
I 8
.It Fl R Ar rate
Specifies the maximum number of times a service can be invoked
in one minute; the default is 1000.
E 8
.El
.Pp
E 7
Upon execution,
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
reads its configuration information from a configuration
file which, by default, is
D 7
.IR /etc/inetd.conf .
E 7
I 7
.Pa /etc/inetd.conf .
E 7
There must be an entry for each field of the configuration
file, with entries for each field separated by a tab or
a space.  Comments are denoted by a ``#'' at the beginning
of a line.  There must be an entry for each field.  The
fields of the configuration file are as follows:
D 7
.br
	service name
.br
	socket type
.br
	protocol
.br
	wait/nowait
.br
	user
.br
	server program
.br
	server program arguments
.PP
E 7
I 7
.Pp
.Bd -unfilled -offset indent -compact
service name
socket type
protocol
wait/nowait
user
server program
server program arguments
.Ed
.Pp
I 8
There are two types of services that 
.Nm inetd
can start: standard and TCPMUX.
A standard service has a well-known port assigned to it;
it may be a service that implements an official Internet standard or is a
BSD-specific service.
As described in 
.Tn RFC 1078 ,
TCPMUX services are nonstandard services that do not have a 
well-known port assigned to them.
They are invoked from
.Nm inetd 
when a program connects to the
.Dq tcpmux
well-known port and specifies
the service name.  
This feature is useful for adding locally-developed servers.
.Pp
E 8
E 7
The
D 7
.I service name
E 7
I 7
.Em service-name
E 7
entry is the name of a valid service in
the file
D 7
.IR /etc/services/ .
For ``internal'' services (discussed below), the service
E 7
I 7
.Pa /etc/services .
For
.Dq internal
services (discussed below), the service
E 7
name
D 7
.I must
E 7
I 7
.Em must
E 7
D 3
be the official name of the service (that is, the left-most entry in
E 3
I 3
be the official name of the service (that is, the first entry in
E 3
D 7
.IR /etc/services ).
.PP
E 7
I 7
.Pa /etc/services ) .
I 8
For TCPMUX services, the value of the
.Em service-name
field consists of the string
.Dq tcpmux
followed by a slash and the
locally-chosen service name. 
The service names listed in 
.Pa /etc/services
and the name 
.Dq help
are reserved.
Try to choose unique names for your TCPMUX services by prefixing them with
your organization's name and suffixing them with a version number.
E 8
.Pp
E 7
The
D 7
.I socket type
should be one of ``stream'', ``dgram'', ``raw'', ``rdm'', or ``seqpacket'',
E 7
I 7
.Em socket-type
should be one of
.Dq stream ,
.Dq dgram ,
.Dq raw ,
.Dq rdm ,
or
.Dq seqpacket ,
E 7
depending on whether the socket is a stream, datagram, raw,
reliably delivered message, or sequenced packet socket.
I 8
TCPMUX services must use 
.Dq stream .
E 8
D 7
.PP
E 7
I 7
.Pp
E 7
The
D 7
.I protocol
E 7
I 7
.Em protocol
E 7
must be a valid protocol as given in
D 7
.IR /etc/protocols .
Examples might be ``tcp'' or ``udp''.
.PP
E 7
I 7
.Pa /etc/protocols .
Examples might be
.Dq tcp
or
.Dq udp .
I 8
TCPMUX services must use 
.Dq tcp .
E 8
.Pp
E 7
The
D 7
.I wait/nowait
E 7
I 7
.Em wait/nowait
E 7
D 11
entry is applicable to datagram sockets only (other sockets should
D 7
have a ``nowait'' entry in this space).  If a datagram server connects
E 7
I 7
have a
.Dq nowait
entry in this space).  If a datagram server connects
E 11
I 11
entry specifies whether the server that is invoked by inetd will take over
the socket associated with the service access point, and thus whether
.Nm inetd
should wait for the server to exit before listening for new service
requests.
Datagram servers must use
.Dq wait ,
as they are always invoked with the original datagram socket bound
to the specified service address.
These servers must read at least one datagram from the socket
before exiting.
If a datagram server connects
E 11
E 7
to its peer, freeing the socket so
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
can received further messages on the socket, it is said to be
D 7
a ``multi-threaded'' server, and should use the ``nowait''
E 7
I 7
a
.Dq multi-threaded
D 11
server, and should use the
.Dq nowait
E 7
entry.  For datagram servers which process all incoming datagrams
on a socket and eventually time out, the server is said to be
D 3
``single-threaded'' and should use a ``wait'' entry.  ``Rwho''
E 3
I 3
D 7
``single-threaded'' and should use a ``wait'' entry.  ``Comsat'' (``biff'')
E 3
and ``talk'' are both examples of the latter type of
E 7
I 7
.Dq single-threaded
and should use a
.Dq wait
entry.
E 11
I 11
server;
it should read one datagram from the socket and create a new socket
connected to the peer.
It should fork, and the parent should then exit
to allow
.Nm inetd
to check for new service requests to spawn new servers.
Datagram servers which process all incoming datagrams
on a socket and eventually time out are said to be
.Dq single-threaded .
E 11
D 10
.Xr Comsat 8
E 10
I 10
.Xr Comsat 8 ,
E 10
.Pq Xr biff 1
and
.Xr talkd 8
are both examples of the latter type of
E 7
datagram server.
I 3
D 7
.I Tftpd
E 7
I 7
.Xr Tftpd 8
E 7
D 11
is an exception; it is a datagram server that establishes pseudo-connections.
D 7
It must be listed as ``wait'' in order to avoid a race;
E 7
I 7
It must be listed as
E 11
I 11
is an example of a multi-threaded datagram server.
.Pp
Servers using stream sockets generally are multi-threaded and
use the
.Dq nowait
entry.
Connection requests for these services are accepted by
.Nm inetd ,
and the server is given only the newly-accepted socket connected
to a client of the service.
Most stream-based services operate in this manner.
Stream-based servers that use
E 11
.Dq wait
D 11
in order to avoid a race;
E 7
the server reads the first packet, creates a new socket,
and then forks and exits to allow
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
to check for new service requests to spawn new servers.
E 11
I 11
are started with the listening service socket, and must accept
at least one connection request before exiting.
Such a server would normally accept and process incoming connection
requests until a timeout.
E 11
I 8
TCPMUX services must use 
.Dq nowait .
E 8
E 3
D 7
.PP
E 7
I 7
.Pp
E 7
The
D 7
.I user
E 7
I 7
.Em user
E 7
entry should contain the user name of the user as whom the server
should run.  This allows for servers to be given less permission
than root.
I 7
.Pp
E 7
The
D 7
.I server program
E 7
I 7
.Em server-program
E 7
entry should contain the pathname of the program which is to be
executed by
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
when a request is found on its socket.  If
D 7
.I inetd
E 7
I 7
.Nm inetd
E 7
provides this service internally, this entry should
D 7
be ``internal''.
.PP
The arguments to the server program should be just as they
E 7
I 7
be
.Dq internal .
.Pp
The
.Em server program arguments
should be just as arguments
E 7
normally are, starting with argv[0], which is the name of
the program.  If the service is provided internally, the
D 7
word ``internal'' should take the place of this entry.
.PP
.I Inetd
provides several ``trivial'' services internally by use of
routines within itself.  These services are ``echo'',
``discard'', ``chargen'' (character generator), ``daytime''
(human readable time), and ``time'' (machine readable time,
E 7
I 7
word
.Dq internal
should take the place of this entry.
.Pp
D 11
.Nm Inetd
E 11
I 11
The
.Nm inetd
program
E 11
provides several
.Dq trivial
services internally by use of
routines within itself.  These services are
.Dq echo ,
.Dq discard ,
.Dq chargen
(character generator),
.Dq daytime
(human readable time), and
.Dq time
(machine readable time,
E 7
in the form of the number of seconds since midnight, January
1, 1900).  All of these services are tcp based.  For
D 7
details of these services, consult the appropriate RFC
E 7
I 7
details of these services, consult the appropriate
.Tn RFC
E 7
from the Network Information Center.
I 4
D 7
.PP
.I Inetd
rereads its configuration file when it receives a hangup signal, SIGHUP.
E 7
I 7
.Pp
D 11
.Nm Inetd
E 11
I 11
The
.Nm inetd
program
E 11
rereads its configuration file when it receives a hangup signal,
.Dv SIGHUP .
E 7
Services may be added, deleted or modified when the configuration file
is reread.
I 8
.Sh TCPMUX
.Pp
.Tn RFC 1078 
describes the TCPMUX protocol:
``A TCP client connects to a foreign host on TCP port 1.  It sends the
service name followed by a carriage-return line-feed <CRLF>.  The
service name is never case sensitive.  The server replies with a
single character indicating positive (+) or negative (\-)
acknowledgment, immediately followed by an optional message of
explanation, terminated with a <CRLF>.  If the reply was positive,
the selected protocol begins; otherwise the connection is closed.''
The program is passed the TCP connection as file descriptors 0 and 1.
.Pp
If the TCPMUX service name begins with a ``+'',
.Nm inetd
returns the positive reply for the program.
This allows you to invoke programs that use stdin/stdout
without putting any special server code in them.
.Pp
The special service name
.Dq help
causes
.Nm inetd
to list TCPMUX services in
.Pa inetd.conf .
I 12
.ne 1i
E 12
.Sh "EXAMPLES"
.Pp
Here are several example service entries for the various types of services:
.Bd -literal
ftp           stream  tcp   nowait root  /usr/libexec/ftpd       ftpd -l
ntalk         dgram   udp   wait   root  /usr/libexec/ntalkd     ntalkd
tcpmux/+date  stream  tcp   nowait guest /bin/date               date
tcpmux/phonebook stream tcp nowait guest /usr/local/bin/phonebook phonebook
.Ed
.Sh "ERROR MESSAGES"
D 11
.Nm Inetd
E 11
I 11
The
.Nm inetd
server
E 11
logs error messages using
.Xr syslog 3 .
Important error messages and their explanations are:
.Bd -literal
\fIservice\fP/\fIprotocol\fP server failing (looping), service terminated.
.Ed
The number of requests for the specified service in the past minute
exceeded the limit. The limit exists to prevent a broken program
or a malicious user from swamping the system.
This message may occur for several reasons:
1) there are lots of hosts requesting the service within a short time period,
2) a 'broken' client program is requesting the service too frequently,
3) a malicious user is running a program to invoke the service in
a 'denial of service' attack, or
4) the invoked service program has an error that causes clients
to retry quickly.
Use the
.Op Fl R 
option,
as described above, to change the rate limit.
Once the limit is reached, the service will be
reenabled automatically in 10 minutes.
.sp
.Bd -literal
\fIservice\fP/\fIprotocol\fP: No such user '\fIuser\fP', service ignored
\fIservice\fP/\fIprotocol\fP: getpwnam: \fIuser\fP: No such user
.Ed
No entry for 
.Em user
exists in the 
.Pa passwd
file. The first message
occurs when
.Nm inetd
(re)reads the configuration file. The second message occurs when the
service is invoked.
.sp
.Bd -literal
\fIservice\fP: can't set uid \fInumber\fP
\fIservice\fP: can't set gid \fInumber\fP
.Ed
The user or group ID for the entry's 
.Em user
is invalid.
E 8
E 4
D 7
.SH "SEE ALSO"
D 5
comsat(8C), ftpd(8C), rexecd(8C), rlogind(8C), rshd(8C),
D 3
rwhod(8C), telnetd(8C), tftpd(8C)
E 3
I 3
telnetd(8C), tftpd(8C)
E 5
I 5
comsat(8), fingerd(8), ftpd(8), rexecd(8), rlogind(8), rshd(8),
telnetd(8), tftpd(8)
E 7
I 7
.Sh SEE ALSO
.Xr comsat 8 ,
.Xr fingerd 8 ,
.Xr ftpd 8 ,
.Xr rexecd 8 ,
.Xr rlogind 8 ,
.Xr rshd 8 ,
.Xr telnetd 8 ,
.Xr tftpd 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.3 .
I 8
TCPMUX is based on code and documentation by Mark Lottor.
E 8
E 7
E 5
E 3
D 2
.SH BUGS
Internal services should not have to have their official
name in the configuration file.
E 2
E 1
