h47944
s 00002/00002/00049
d D 8.1 93/06/04 13:04:41 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00001/00048
d D 5.3 91/06/29 14:19:25 bostic 3 2
c add ANSI contribution notice
e
s 00033/00027/00016
d D 5.2 91/04/19 14:40:29 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00043/00000/00000
d D 5.1 90/05/15 22:32:18 bostic 1 0
c date and time created 90/05/15 22:32:18 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 4
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" This code is derived from software contributed to Berkeley by
D 3
.\" Chris Torek.
E 3
I 3
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
E 3
D 2
.\"
E 2
.\" %sccs.include.redist.man%
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH ATEXIT 3 "%Q%"
.UC 7
.SH NAME
atexit \- register a function to be called on exit
.SH SYNOPSIS
.B #include <stdlib.h>
.PP
.B "atexit(void (*function)())
.SH DESCRIPTION
.B Atexit
E 2
I 2
.Dd %Q%
.Dt ATEXIT 3
.Os
.Sh NAME
.Nm atexit
.Nd register a function to be called on exit
.Sh SYNOPSIS
.Fd #include <stdlib.h>
.Ft int
.Fn atexit "void (*function)(void)"
.Sh DESCRIPTION
The
.Fn atexit
function
E 2
registers the given
D 2
.I function
E 2
I 2
.Ar function
E 2
to be called at program exit, whether via
D 2
.IR exit (3)
E 2
I 2
.Xr exit 3
E 2
or via return from the program's
D 2
.BR main .
E 2
I 2
.Em main .
E 2
Functions so registered are called in reverse order;
no arguments are passed.
At least 32 functions can always be registered,
and more are allowed as long as sufficient memory can be allocated.
D 2
.SH RETURN VALUE
.B Atexit
returns 0 on success, \-1 on error.
.SH ERRORS
.TP
[ENOMEM]
E 2
I 2
.Sh RETURN VALUES
.Rv -std atexit
.Sh ERRORS
.Bl -tag -width [ENOMEM]
.It Bq Er ENOMEM
E 2
No memory was available to add the function to the list.
The existing list of functions is unmodified.
D 2
.SH SEE ALSO
exit(3)
.SH STANDARDS
.B Atexit
conforms to ANSI X3.159-1989 (``ANSI C'').
E 2
I 2
.El
.Sh SEE ALSO
.Xr exit 3
.Sh STANDARDS
The
.Fn atexit
function
conforms to
.St -ansiC .
E 2
E 1
