h61201
s 00002/00002/00030
d D 8.1 93/06/05 13:25:45 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00003/00028
d D 6.2 91/04/30 18:13:21 bostic 3 2
c new copyright; att/bsd/shared
e
s 00001/00001/00030
d D 6.1 85/05/15 16:26:54 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00031/00000/00000
d D 5.1 85/05/15 16:26:48 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 4
.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1983, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" %sccs.include.proprietary.roff%
E 3
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH PUTC 3F "13 June 1983"
E 2
I 2
.TH PUTC 3F "%Q%"
E 2
.UC 5
.SH NAME
putc, fputc \- write a character to a fortran logical unit
.SH SYNOPSIS
.B integer function putc (char)
.br
.B character char
.sp 1
.B integer function fputc (lunit, char)
.br
.B character char
.SH DESCRIPTION
These funtions write a character to the file associated with a fortran logical
unit bypassing normal fortran I/O.
.I Putc
writes to logical unit 6, normally connected to the control terminal output.
.PP
The value of each function will be zero unless some error occurred;
a system error code otherwise. See perror(3F).
.SH FILES
.ie \nM /usr/ucb/lib/libU77.a
.el /usr/lib/libU77.a
.SH "SEE ALSO"
putc(3S), intro(2), perror(3F)
E 1
