h21658
s 00008/00018/00028
d D 6.6 91/08/05 12:33:51 bostic 8 7
c minor cleanups, don't mention specific files, they're going away
e
s 00011/00011/00035
d D 6.5 91/07/24 22:57:18 cael 7 6
c mdoc version three
e
s 00002/00000/00044
d D 6.4 91/03/14 00:18:34 cael 6 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00044
d R 6.4 91/03/13 20:33:43 cael 5 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00000/00000/00044
d D 6.3 90/07/24 22:46:01 cael 4 3
c .Xr botch fix
e
s 00032/00021/00012
d D 6.2 90/06/24 19:05:07 cael 3 2
c converted man page
e
s 00001/00001/00032
d D 6.1 85/04/29 21:09:19 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00033/00000/00000
d D 5.1 85/04/29 21:09:12 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
.\" Copyright (c) 1983 1990 The Regents of the University of California.
.\" All rights reserved.
E 3
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
E 3
.\"
D 2
.TH GROUPS 1 "30 May 1983"
E 2
I 2
D 3
.TH GROUPS 1 "%Q%"
E 2
.UC 5
.SH NAME
groups \- show group memberships
.SH SYNOPSIS
.B
groups [user]
.SH DESCRIPTION
E 3
I 3
D 7
.\"     %W% (Berkeley) %G%
E 7
I 7
.\"	%W% (Berkeley) %G%
E 7
.\"
I 6
D 7
.Vx
.Vx
E 7
E 6
.Dd %Q%
.Dt GROUPS 1
.Os BSD 4.2
.Sh NAME
.Nm groups
.Nd show group memberships
.Sh SYNOPSIS
.Nm groups
.Op Ar user
.Sh DESCRIPTION
E 3
The
D 3
.I groups
E 3
I 3
.Nm groups
E 3
command shows the groups to which you or the optionally specified
user belong.
Each user belongs to a group specified in the password file
D 3
.I /etc/passwd
E 3
I 3
D 8
.Pa /etc/passwd
E 3
and possibly to other groups as specified in the file
D 3
.IR /etc/group .
E 3
I 3
.Pa /etc/group .
E 3
If you do not own a file but belong to the group which it is owned
by then you are granted group access to the file.
E 8
I 8
and possibly to other groups.
If you do not own a file but belong to the group by which it is owned,
then you are granted group access to the file.
E 8
D 3
.PP
E 3
I 3
.Pp
E 3
D 8
When a new file is created it is given
the group of the containing directory.
E 8
I 8
When a new file is created it is given the group of the containing
directory.
E 8
D 3
.SH "SEE ALSO"
setgroups(2)
.SH FILES
/etc/passwd, /etc/group
.SH BUGS
E 3
I 3
.Sh SEE ALSO
I 8
.Xr id 1 ,
E 8
.Xr group 5 ,
D 8
.Xr setgroups 2
.Sh FILES
D 7
.Dw /etc/passwd
.Di L
.Dp Pa /etc/passwd
.Dp Pa /etc/group
.Dp
E 7
I 7
.Bl -tag -width /etc/passwd -compact
.It Pa /etc/passwd
.It Pa /etc/group
.El
E 8
E 7
.Sh HISTORY
D 7
.Nm Group
appeared in 4.2 BSD.
E 7
I 7
The
D 8
.Nm group
command
appeared in
E 8
I 8
.Nm groups
command appeared in
E 8
.Bx 4.2 .
E 7
D 8
.Sh BUGS
E 3
More groups should be allowed.
E 8
E 1
