h63174
s 00002/00002/00070
d D 8.1 93/06/06 22:14:19 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00065/00050/00007
d D 6.5 91/04/23 21:23:33 cael 5 4
c mdoc version three/bsd copyright
e
s 00001/00001/00056
d D 6.4 90/06/29 21:05:54 trent 4 3
c /usr/spool -> /var/spool
e
s 00004/00004/00053
d D 6.3 90/06/24 19:22:32 cael 3 2
c converted man page
e
s 00004/00004/00053
d D 6.2 88/10/24 12:00:04 bostic 2 1
c remove refs to [18]C, add copyright if needed
e
s 00057/00000/00000
d D 6.1 86/04/24 19:30:40 mckusick 1 0
c from rfg
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1986 Regents of the University of California.
E 3
I 3
D 5
.\" Copyright (c) 1986,1990 Regents of the University of California.
E 3
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1986,1990, 1991 Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1991, 1993, 19861990
.\"	The Regents of the University of California.  All rights reserved.
E 6
E 5
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
D 5
.\"		%W% (Berkeley) %G%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
E 3
.\"
D 2
.TH UULOG 1C "%Q%"
E 2
I 2
D 3
.TH UULOG 1 "%Q%"
E 3
I 3
D 5
.TH UULOG 1 "%Q"
E 3
E 2
.UC 6
.SH NAME
uulog \- display \s-1UUCP\s0 log files
.SH SYNOPSIS
.B uulog
[
.B \-s
.I sys
] [
.B \-u
.I user
]
.SH DESCRIPTION
.I Uulog
queries a log
of 
D 2
.IR uucp (1C)
E 2
I 2
.IR uucp (1)
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt UULOG 1
.Os BSD 4.3
.Sh NAME
.Nm uulog
.Nd display
.Tn UUCP
log entries
.Sh SYNOPSIS
.Nm uulog
.Op Fl s Ar sys
.Op Fl u Ar user
.Sh DESCRIPTION
The
.Nm uulog
program displays
.Xr uucp 1
E 5
E 2
and
D 2
.IR uux (1C)
E 2
I 2
D 5
.IR uux (1)
E 2
transactions in the file
D 3
.B /usr/spool/uucp/\s-1LOGFILE.\s0
E 3
I 3
.B /var/spool/uucp/\s-1LOGFILE.\s0
E 3
.PP
The options command 
.I uulog
to print logging information:
.TP 8
.BI \-s sys\^
Print information about work involving system
.IR sys .
.TP 8
.BI \-u user\^
Print information about work done for the specified
.IR user .
.SH FILES
D 4
/usr/spool/uucp/\s-1LOGFILE\s0
E 4
I 4
/var/spool/uucp/\s-1LOGFILE\s0
E 4
.SH SEE ALSO
D 2
uucp(1C), uux(1C).
E 2
I 2
uucp(1), uux(1).
E 2
.SH NOTES
Very early releases of \s-1UUCP\s0 used separate log files
for each of the \s-1UUCP\s0 utilities;
.I uulog
E 5
I 5
.Xr uux 1
log entries from the file
.Pa /var/spool/uucp/LOGFILE .
.Pp
Options supported by
.Nm uulog :
.Bl -tag -width Ar
.It Fl s Ar sys
Display all entries logged which include the system named
.Ar sys .
.It Fl u Ar user
Display only entries which include the user name
.Ar user .
.El
.Sh FILES
.Bl -tag -width /usr/spool/uucp/LOGFILEXx
.It Pa /usr/spool/uucp/LOGFILE
Logfile of all uucp events.
.El
.Sh SEE ALSO
.Xr uucp 1 ,
.Xr uux 1 .
.Sh NOTES
Very early releases of
.Tn UUCP
used separate log files
for each of the
.Tn UUCP
utilities;
.Nm uulog
E 5
was used to merge the individual logs into a master file.
This capability has not been necessary for some time and is
no longer supported.
D 5
.SH BUGS
\s-1UUCP\s0's recording of which user issued a request is unreliable.
.PP
.I Uulog
E 5
I 5
.Sh BUGS
.Tn UUCP Ns 's
recording of which user issued a request is unreliable.
.Pp
The
.Nm uulog
program
E 5
is little more than an overspecialized version of
D 5
.IR grep (1).
E 5
I 5
.Xr grep 1 .
.Sh HISTORY
A
.Nm
command appeared in
.At 32v .
E 5
E 1
