h04076
s 00002/00002/00092
d D 8.1 93/06/29 16:09:06 bostic 16 15
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00002/00092
d D 6.12 93/06/29 16:08:45 mckusick 15 13
c typesetting nits
e
s 00002/00002/00092
d R 8.1 93/06/06 15:21:28 bostic 14 13
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00005/00004/00089
d D 6.11 91/07/22 15:42:16 cael 13 12
c Os fix
e
s 00031/00022/00062
d D 6.10 91/03/14 01:38:37 cael 12 11
c updated to -mdoc version 3
e
s 00005/00004/00079
d D 6.9 90/07/24 22:40:35 cael 11 10
c .Xr botch fix
e
s 00060/00058/00023
d D 6.8 90/06/11 05:52:41 cael 10 9
c converted man page
e
s 00002/00002/00079
d D 6.7 90/05/27 15:25:37 bostic 9 8
c new apropos version, using new man.conf file
e
s 00068/00025/00013
d D 6.6 90/03/11 15:08:35 bostic 8 7
c add -m flag, configurable search directories
e
s 00022/00027/00016
d D 6.5 87/06/30 20:49:57 bostic 7 6
c added -M flag, no longer part of man(1)
e
s 00001/00001/00042
d D 6.4 86/06/05 17:00:35 bloom 6 5
c font fix
e
s 00002/00002/00041
d D 6.3 86/05/08 15:22:27 anne 5 4
c grammar
e
s 00001/00001/00042
d D 6.2 86/01/08 14:14:19 mckusick 4 3
c /usr/lib/whatis moves to /usr/man/whatis
e
s 00001/00001/00042
d D 6.1 85/04/29 19:57:51 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00002/00041
d D 5.1 85/04/29 19:57:31 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00043/00000/00000
d D 4.1 85/04/29 19:57:09 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 7
D 8
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 8
I 8
D 10
.\" Copyright (c) 1989 The Regents of the University of California.
E 10
I 10
D 16
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 10
.\" All rights reserved.
E 16
I 16
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 16
E 8
.\"
I 8
D 10
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 10
I 10
D 13
.\" %sccs.include.redist.man%
E 13
I 13
.\" %sccs.include.redist.roff%
E 13
E 10
.\"
E 8
E 7
I 1
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
D 13
.\"     %W% (Berkeley) %G%
E 13
I 13
.\"	%W% (Berkeley) %G%
E 13
E 10
.\"
D 2
.TH APROPOS 1 2/24/79
E 2
I 2
D 3
.TH APROPOS 1 "24 February 1979"
E 3
I 3
D 10
.TH APROPOS 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
apropos \- locate commands by keyword lookup
.SH SYNOPSIS
D 8
.B apropos
I 7
[
.B -M
.I path
]
E 7
keyword ...
E 8
I 8
.nf
.ft B
apropos [-M path] [-m path] keyword ...
.ft R
.fi
E 8
.SH DESCRIPTION
D 7
.I Apropos
shows which manual sections contain instances of any of the given
keywords in their title.
Each word is considered separately and case of letters is ignored.
D 5
Words which are part of other words are considered thus looking for
compile will hit all instances of `compiler' also.
E 5
I 5
Words which are part of other words are considered; thus, when looking for
D 6
compile, \fIapropos\fB will find all instances of `compiler' also.
E 6
I 6
compile, \fIapropos\fP will find all instances of `compiler' also.
E 6
E 5
Try
.IP
apropos password
E 7
I 7
D 8
\fIApropos\fP shows which manual pages contain instances of any of the given
\fIkeyword\fP(s) in their title line.  Each word is considered separately
and case of letters is ignored.  Words which are part of other words are
considered; when looking for compile, \fIapropos\fP will also find all
instances of ``compiler''.
E 8
I 8
.I Apropos
E 10
I 10
.Dd %Q%
.Dt APROPOS 1
I 13
.Os
E 13
.Sh NAME
.Nm apropos
.Nd locate commands by keyword lookup
.Sh SYNOPSIS
.Nm apropos
.Op Fl M Ar path
.Op Fl m Ar path
.Ar keyword ...
.Sh DESCRIPTION
.Nm Apropos
E 10
shows which manual pages contain instances of any of the given
D 10
.I keyword(s)
E 10
I 10
.Ar keyword(s)
E 10
in their title line.
Each word is considered separately and case of letters is ignored.
Words which are part of other words are considered; when looking for
D 10
``compile'',
.I apropos
will also list all instances of ``compiler''.
E 8
E 7
.PP
E 10
I 10
D 12
\*(Lqcompile\*(Rq,
E 12
I 12
.Dq compile ,
E 12
.Nm apropos
D 12
will also list all instances of \*(Lqcompiler\*(Rq.
E 12
I 12
will also list all instances of
.Dq compiler .
E 12
.Pp
E 10
D 7
and
.IP
apropos editor
E 7
I 7
D 8
If the line output by \fIapropos\fP starts ``name(section) ...'' you can
enter ``man section name'' to get its documentation.
E 8
I 8
If the line output by
D 10
.I apropos
starts ``name(section) ...'' you can enter ``man section name'' to get
E 10
I 10
.Nm apropos
starts
D 12
.Li \*(Lqname(section) ...\*(Rq
E 12
I 12
.Dq Li name(section) ...
E 12
you can enter
D 12
.Li \*(Lqman section name\*(Rq
E 12
I 12
.Dq Li man section name
E 12
to get
E 10
its documentation.
E 8
E 7
D 10
.PP
E 10
I 10
.Pp
E 10
D 7
If the line starts `name(section) ...' you can do
`man section name' to get the documentation for it.
Try `apropos format' and then `man 3s printf' to get the manual
on the subroutine
.I printf.
.PP
.I Apropos
is actually just the
.B \-k
option to the
D 2
.IR man (2)
E 2
I 2
.IR man (1)
E 2
command.
E 7
I 7
D 8
Normally \fIapropos\fP checks in a standard location (/usr/man) for its
database ``whatis''.  This can be changed by supplying a \fIpath\fP (a
la the Bourne shell) with the \fB-M\fP flag.  This search path must be
a colon (``:'') separated list of directories which \fIapropos\fP will
search for files named ``whatis''.  The path can also be set with the
environmental variable \fIMANPATH\fP.
E 8
I 8
The options are as follows:
D 10
.TP
.I M
E 10
I 10
D 12
.Tp Fl M
E 10
Override the list of standard directories where
E 12
I 12
D 13
.Bl -tag -width Ds
E 13
I 13
.Bl -tag -width flag
E 13
.It Fl M
Override the list of standard directories
E 12
D 10
.I apropos
D 9
searches for its database.
E 9
I 9
searches for a database named ``whatis.db''.
E 10
I 10
.Nm apropos
searches for a database named
.Pa whatis.db .
E 10
E 9
The supplied
D 10
.I path
must be a colon (``:'') separated list of directories.
E 10
I 10
.Ar path
D 12
must be a colon (\*(Lq:\*(Rq) separated list of directories.
E 12
I 12
must be a colon
.Dq \&:
separated list of directories.
E 12
E 10
D 11
This search path may also be set using the environmental variable
E 11
I 11
This search path may also be set using the environment variable
E 11
D 10
.IR MANPATH .
.TP
.I m
E 10
I 10
.Ev MANPATH .
D 12
.Tp Fl m
E 10
Augment the list of standard directories where
E 12
I 12
.It Fl m
Augment the list of standard directories
E 12
D 10
.I apropos
D 9
searches for its database.
E 9
I 9
searches for a database named ``whatis.db''.
E 10
I 10
.Nm apropos
searches for its database.
E 10
E 9
The supplied
D 10
.I path
must be a colon (``:'') separated list of directories.
E 10
I 10
.Ar path
D 12
must be a colon (\*(Lq:\*(Rq) separated list of directories.
E 12
I 12
must be a colon
.Dq \&:
separated list of directories.
E 12
E 10
D 15
These directories will be searched before the standard directories
E 15
I 15
These directories will be searched before the standard directories,
E 15
or the directories supplied with the
D 10
.I M
E 10
I 10
.Fl M
E 10
option or the
D 10
.I MANPATH
E 10
I 10
.Ev MANPATH
E 10
D 12
environmental variable are searched.
E 12
I 12
D 15
environment variable are searched.
E 15
I 15
environment variable.
E 15
E 12
D 10
.SH "ENVIRONMENTAL VARIABLES"
.TP
.I MANPATH
E 10
I 10
.Sh ENVIRONMENT
D 12
.Tw MANPATH
.Tp Ev MANPATH
E 12
I 12
.Bl -tag -width MANPATH
.It Ev MANPATH
E 12
E 10
The standard search path used by
D 10
.I man
E 10
I 10
.Xr man 1
E 10
may be overridden by specifying a path in the
D 10
.I MANPATH
E 10
I 10
.Ev MANPATH
E 10
D 12
environmental variable.
D 10
The format of the path is a colon (``:'') separated list of directories.
E 8
E 7
.SH FILES
D 8
.DT
D 4
/usr/lib/whatis		data base
E 4
I 4
/usr/man/whatis		data base
E 8
I 8
whatis.db		name of the apropos database
E 8
E 4
.SH "SEE ALSO"
D 7
man(1), whatis(1), catman(8)
.SH AUTHOR
William Joy
E 7
I 7
D 8
man(1), whatis(1)
E 8
I 8
man(1), whatis(1), whereis(1)
E 10
I 10
The format of the path is a colon (\*(Lq:\*(Rq) separated list of directories.
.Tp
E 12
I 12
environment variable.
The format of the path is a colon
.Dq \&:
separated list of directories.
.El
E 12
.Sh FILES
D 11
.Tw whatis.db
.Tp Pa whatis.db
E 11
I 11
D 12
.Dw whatis.db
.Di L
.Dp Pa whatis.db
E 12
I 12
.Bl -tag -width whatis.db -compact
.It Pa whatis.db
E 12
E 11
name of the apropos database
D 11
.Tp
E 11
I 11
D 12
.Dp
E 12
I 12
.El
E 12
E 11
.Sh SEE ALSO
.Xr man 1 ,
.Xr whatis 1 ,
.Xr whereis 1
.Sh HISTORY
D 12
.Nm apropos
appeared in 3 BSD.
E 12
I 12
The
D 13
.Nm
E 13
I 13
.Nm apropos
E 13
command appeared in
.Bx 3.0 .
E 12
E 10
E 8
E 7
E 1
