h17384
s 00002/00002/00048
d D 8.1 93/06/05 13:53:18 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00035/00020/00015
d D 6.3 91/05/02 06:57:21 cael 4 3
c mdoc version three/bsd copyright
e
s 00003/00002/00032
d D 6.2 86/05/16 11:31:56 mckusick 3 2
c note that only ``,'' and \n are terminators
e
s 00001/00001/00033
d D 6.1 85/05/15 18:59:08 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00034/00000/00000
d D 5.1 85/05/15 18:59:00 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 5
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\" %sccs.include.redist.roff%
E 4
.\"
D 2
.TH PHONES 5 "15 January 1983"
E 2
I 2
D 4
.TH PHONES 5 "%Q%"
E 2
.UC 5
.SH NAME
phones \- remote host phone number data base
.SH DESCRIPTION
The file /etc/phones contains the system-wide
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt PHONES 5
.Os BSD 4.2
.Sh NAME
.Nm phones
.Nd remote host phone number data base
.Sh DESCRIPTION
The file
.Pa /etc/phones
contains the system-wide
E 4
private phone numbers for the
D 4
.IR tip (1C)
E 4
I 4
.Xr tip 1
E 4
program.  This file is normally unreadable, and so may contain
privileged information.  The format of the file is a series of lines
of the form: <system-name>[\ \et]*<phone-number>.  The system name is
one of those defined in the
D 4
.IR remote (5)
E 4
I 4
.Xr remote 5
E 4
D 3
file and the phone number is
constructed from [0123456789-=*%].  The ``='' and ``*'' characters are
E 3
I 3
file and the phone number is constructed from any sequence of
characters terminated only by ``,'' or the end of the line.
The ``='' and ``*'' characters are
E 3
indicators to the auto call units to pause and wait for a second dial
tone (when going through an exchange).  The ``='' is required by the
D 4
DF02-AC and the ``*'' is required by the BIZCOMP 1030.
.PP
E 4
I 4
.Tn DF02-AC
and the ``*'' is required by the
.Tn BIZCOMP
1030.
.Pp
E 4
Only one phone number per line is permitted.  However, if more than
one line in the file contains the same system name
D 4
.IR tip (1C)
E 4
I 4
.Xr tip 1
E 4
will attempt to dial each one in turn, until it establishes a connection.
D 4
.SH FILES
/etc/phones
.SH "SEE ALSO"
tip(1C),
remote(5)
E 4
I 4
.Sh FILES
.Bl -tag -width /etc/phones -compact
.It Pa /etc/phones
.El
.Sh SEE ALSO
.Xr tip 1 ,
.Xr remote 5
.Sh HISTORY
The
.Nm
file appeared in
.Bx 4.2 .
E 4
E 1
