h62291
s 00001/00000/00191
d D 8.3 94/06/01 20:45:13 ah 9 8
c page breaks for 4.4BSD manuals
e
s 00002/00002/00189
d D 8.2 93/12/11 23:44:46 mckusick 8 7
c copyediting for Usenix manuals
e
s 00002/00002/00189
d D 8.1 93/06/06 14:05:18 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00120/00080/00071
d D 6.5 91/03/16 18:13:18 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00150
d D 6.4 90/06/24 22:30:38 trent 5 4
c new copyright notice
e
s 00016/00013/00145
d D 6.3 89/03/28 10:54:51 mckusick 4 3
c correct description of syntax (4.3BSD-tahoe/man/4, Guy Harris)
e
s 00016/00009/00142
d D 6.2 88/09/19 21:46:16 bostic 3 2
c Berkeley specific header
e
s 00001/00001/00150
d D 6.1 85/04/27 15:42:33 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00151/00000/00000
d D 5.1 85/04/27 15:42:16 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 3
.\"
I 3
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 3
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH RMT 8C "4 March 1983"
E 2
I 2
D 3
.TH RMT 8C "%Q%"
E 3
I 3
D 6
.TH RMT 8 "%Q%"
E 3
E 2
.UC 5
.SH NAME
rmt \- remote magtape protocol module
.SH SYNOPSIS
.B /etc/rmt
.SH DESCRIPTION
.I Rmt
E 6
I 6
.Dd %Q%
.Dt RMT 8
.Os BSD 4.2
.Sh NAME
.Nm rmt
.Nd remote magtape protocol module
.Sh SYNOPSIS
.Nm rmt
.Sh DESCRIPTION
.Nm Rmt
E 6
is a program used by the remote dump and restore programs
in manipulating a magnetic tape drive through an interprocess
communication connection.
D 6
.I Rmt
E 6
I 6
.Nm Rmt
E 6
is normally started up with an
D 6
.IR rexec (3X)
E 6
I 6
.Xr rexec 3
E 6
or
D 6
.IR rcmd (3X)
E 6
I 6
.Xr rcmd 3
E 6
call.
D 6
.PP
E 6
I 6
.Pp
E 6
The 
D 6
.I rmt
E 6
I 6
.Nm rmt
E 6
program accepts requests specific to the manipulation of
magnetic tapes, performs the commands, then responds with
D 6
a status indication.  All responses are in ASCII and in
E 6
I 6
a status indication.  All responses are in
.Tn ASCII
and in
E 6
one of two forms. 
D 6
Successful commands have responses of
I 4
.IP
.BI A number \en
E 4
.PP
D 4
.ti +0.5i
\fBA\fInumber\fR\en
.PP
E 4
where 
.I number
is an ASCII representation of a decimal number.
Unsuccessful commands are responded to with
.PP
D 4
.ti +0.5i
\fBE\fIerror-number\fR\en\fIerror-message\fR\en,
E 4
I 4
.IP
.BI E error-number \en error-message \en
E 4
.PP
where
.I error-number
E 6
I 6
Successful commands have responses of:
.Bd -filled -offset indent
.Sm off
.Sy A Ar number No \en
.Sm on
.Ed
.Pp
.Ar Number
is an
.Tn ASCII
representation of a decimal number.
Unsuccessful commands are responded to with:
.Bd -filled -offset indent
.Sm off
.Xo Sy E Ar error-number
.No \en Ar error-message
.No \en
.Xc
.Sm on
.Ed
.Pp
.Ar Error-number
E 6
is one of the possible error
numbers described in
D 6
.IR intro (2)
E 6
I 6
.Xr intro 2
E 6
and
D 6
.I error-message
E 6
I 6
.Ar error-message
E 6
is the corresponding error string as printed
from a call to
D 6
.IR perror (3).
E 6
I 6
.Xr perror 3 .
E 6
The protocol is comprised of the
D 4
following commands (a space is present between each token).
E 4
I 4
following commands, which are sent as indicated - no spaces are supplied
between the command and its arguments, or between its arguments, and
D 6
.B \en
E 6
I 6
.Ql \en
E 6
indicates that a newline should be supplied:
E 4
D 6
.TP 15
D 4
.B O device mode
E 4
I 4
.BI O device \en mode \en
E 6
I 6
.Bl -tag -width Ds
.Sm off
.It Xo Sy \&O Ar device
.No \en Ar mode No \en
.Xc
E 6
E 4
Open the specified 
D 6
.I device
E 6
I 6
.Ar device
E 6
using the indicated
D 6
.IR mode .
.I Device
E 6
I 6
.Ar mode .
.Ar Device
E 6
is a full pathname and
D 6
.I mode
is an ASCII representation of a decimal
E 6
I 6
.Ar mode
is an
.Tn ASCII
representation of a decimal
E 6
number suitable for passing to
D 6
.IR open (2).
E 6
I 6
.Xr open 2 .
E 6
If a device had already been opened, it is
closed before a new open is performed.
D 6
.TP 15
D 4
.B C device
E 4
I 4
.BI C device \en
E 6
I 6
.It Xo Sy C Ar device No \en
.Xc
E 6
E 4
Close the currently open device.  The
D 6
.I device
E 6
I 6
.Ar device
E 6
specified is ignored.
D 6
.TP 15
D 4
.B L whence offset
E 4
I 4
.BI L whence \en offset \en
E 6
I 6
.It Xo Sy L
.Ar whence No \en
.Ar offset No \en
.Xc
.Sm on
E 6
E 4
Perform an
D 6
.IR lseek (2)
E 6
I 6
.Xr lseek 2
E 6
operation using the specified parameters.
The response value is that returned from the
D 6
.I lseek
E 6
I 6
.Xr lseek
E 6
call.
D 6
.TP 15
D 4
.B W count
E 4
I 4
.BI W count \en
E 6
I 6
.Sm off
.It Sy W Ar count No \en
.Sm on
E 6
E 4
Write data onto the open device.
D 6
.I Rmt
E 6
I 6
.Nm Rmt
E 6
reads
D 6
.I count
E 6
I 6
.Ar count
E 6
bytes from the connection, aborting if
a premature end-of-file is encountered.
The response value is that returned from
the
D 6
.IR write (2)
E 6
I 6
.Xr write 2
E 6
call.
D 6
.TP 15
D 4
.B R count
E 4
I 4
.BI R count \en
E 6
I 6
.Sm off
.It Sy R Ar count No \en
.Sm on
E 6
E 4
Read
D 6
.I count
E 6
I 6
.Ar count
E 6
bytes of data from the open device.
If
D 6
.I count
E 6
I 6
.Ar count
E 6
exceeds the size of the data buffer (10 kilobytes), it is
truncated to the data buffer size.
D 6
.I Rmt
E 6
I 6
.Nm rmt
E 6
then performs the requested 
D 6
.IR read (2)
E 6
I 6
.Xr read 2
E 6
and responds with 
D 4
\fBA\fIcount-read\fR\en if the read was
E 4
I 4
D 6
.BI A count-read \en
E 6
I 6
.Sm off
.Sy A Ar count-read No \en
.Sm on
E 6
if the read was
E 4
successful; otherwise an error in the
standard format is returned.  If the read
was successful, the data read is then sent.
D 6
.TP 15
D 4
.B I operation count 
E 4
I 4
.BI I operation \en count \en
E 4
Perform a MTIOCOP 
.IR ioctl (2)
E 6
I 6
.Sm off
.It Xo Sy I Ar operation
.No \en Ar count No \en
.Xc
.Sm on
Perform a
.Dv MTIOCOP
.Xr ioctl 2
E 6
command using the specified parameters.
The parameters are interpreted as the
D 6
ASCII representations of the decimal values
E 6
I 6
.Tn ASCII
representations of the decimal values
E 6
to place in the 
D 6
.I mt_op
E 6
I 6
.Ar mt_op
E 6
and
D 6
.I mt_count
E 6
I 6
.Ar mt_count
E 6
fields of the structure used in the
D 6
.I ioctl
E 6
I 6
.Xr ioctl
E 6
call.  The return value is the
D 6
.I count
E 6
I 6
.Ar count
E 6
parameter when the operation is successful.
I 9
.ne 1i
E 9
D 6
.TP 15
.B S
E 6
I 6
.It Sy S
E 6
Return the status of the open device, as
D 6
obtained with a MTIOCGET 
.I ioctl
E 6
I 6
obtained with a
.Dv MTIOCGET
.Xr ioctl
E 6
call.  If the operation was successful,
an ``ack'' is sent with the size of the
status buffer, then the status buffer is
sent (in binary).
D 6
.PP
E 6
I 6
.El
.Sm on
.Pp
E 6
Any other command causes 
D 6
.I rmt
E 6
I 6
.Nm rmt
E 6
to exit.
D 6
.SH DIAGNOSTICS
E 6
I 6
.Sh DIAGNOSTICS
E 6
All responses are of the form described above.
D 6
.SH "SEE ALSO"
D 3
rcmd(3X),
rexec(3X),
mtio(4),
rdump(8C),
rrestore(8C)
E 3
I 3
rcmd(3), rexec(3), mtio(4), rdump(8), rrestore(8)
E 3
.SH BUGS
E 6
I 6
.Sh SEE ALSO
.Xr rcmd 3 ,
.Xr rexec 3 ,
.Xr mtio 4 ,
.Xr rdump 8 ,
.Xr rrestore 8
.Sh BUGS
E 6
D 8
People tempted to use this for a remote file access protocol
are discouraged.
E 8
I 8
People should be discouraged from using this for a remote
file access protocol.
E 8
I 6
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 6
E 1
