h28998
s 00001/00001/00312
d D 8.2 94/04/18 21:14:38 bostic 13 12
c spell
e
s 00002/00002/00311
d D 8.1 93/06/06 16:53:58 bostic 12 11
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00112/00066/00201
d D 4.6 91/07/27 17:26:56 cael 11 10
c mdoc version three
e
s 00002/00003/00265
d D 4.5 91/04/26 16:09:08 bostic 10 9
c new copyright; att/bsd/shared
e
s 00002/00000/00266
d D 4.4 91/03/14 00:28:48 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00266
d R 4.4 91/03/13 20:38:46 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00146/00113/00120
d D 4.3 90/06/11 06:01:08 cael 7 6
c converted man page
e
s 00126/00032/00107
d D 4.2 88/12/21 22:42:20 minshall 6 5
c These are the current versions (actually already 2 years old).
e
s 00000/00000/00139
d D 4.1 88/12/04 15:10:52 minshall 5 4
c Release 4.1
e
s 00014/00003/00125
d D 1.4 88/10/25 15:52:26 bostic 4 3
c Berkeley copyright notice
e
s 00008/00003/00120
d D 1.3 86/01/11 16:11:07 mckusick 3 2
c convert to standard format
e
s 00002/00002/00121
d D 1.2 85/12/16 10:38:44 minshall 2 1
c Add SCCS id.
e
s 00123/00000/00000
d D 1.1 85/12/16 10:34:05 minshall 1 0
c date and time created 85/12/16 10:34:05 by minshall
e
u
U
t
T
I 1
D 2
.\" @(#)tn3270.1	1.3
.TH TN3270 1 "22 March 1985"
E 2
I 2
D 3
.\" %W% %G%
.TH TN3270 1 "%G%"
E 2
.ds ]W UCB Computer Center
E 3
I 3
D 4
.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 7
.\" Copyright (c) 1986 The Regents of the University of California.
E 7
I 7
D 12
.\" Copyright (c) 1986, 1990 The Regents of the University of California.
E 7
.\" All rights reserved.
E 12
I 12
.\" Copyright (c) 1986, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 12
.\"
D 7
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 7
E 4
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
D 10
.\"     %W% (Berkeley) %G%
E 10
I 10
.\"	%W% (Berkeley) %G%
E 10
E 7
.\"
I 9
D 10
.Vx
E 10
D 11
.Vx
E 11
E 9
D 7
.TH TN3270 1 "%Q%"
.UC 6
E 3
.SH NAME
tn3270 \- full-screen remote login to IBM VM/CMS
.SH SYNOPSIS
.B tn3270
D 6
sysname
E 6
I 6
[-d] [-n filename] [-t commandname] [sysname [port]]
E 6
.SH DESCRIPTION
.I Tn3270
E 7
I 7
.Dd %Q%
.Dt TN3270 1
.Os BSD 4.3
.Sh NAME
.Nm tn3270
D 11
.Nd full-screen remote login to IBM VM/CMS
E 11
I 11
.Nd full-screen remote login to
.Tn IBM VM/CMS
E 11
.Sh SYNOPSIS
.Nm tn3270
.Op Fl d
.Op Fl n Ar filename
.Op Fl t Ar commandname
.Op Ar sysname Op port
.Sh DESCRIPTION
.Nm Tn3270
E 7
permits a full-screen, full-duplex connection
D 6
from a VAX UNIX machine
to an IBM machine running VM/CMS
giving the appearance of being logged in
directly to the remote machine
on an IBM 3270 terminal.
Of course you must have an account on the machine
to which you wish to connect in order to log in.
E 6
I 6
D 7
from a \s-UNIX\s0 machine
E 7
I 7
D 11
from a UNIX
E 11
I 11
from a
.Tn UNIX
E 11
machine
E 7
D 11
to an IBM (or compatible) machine.
E 11
I 11
to an
.Tn IBM
(or compatible) machine.
E 11
E 6
D 7
.I Tn3270
E 7
I 7
.Nm Tn3270
E 7
I 6
gives the appearance of being logged in
to the remote machine
D 11
from an IBM 3270 terminal.
E 11
I 11
from an
.Tn IBM
3270 terminal.
E 11
Of course, you must have an account on the machine
to which you connect in order to log in.
D 7
.I Tn3270
E 7
I 7
.Nm Tn3270
E 7
E 6
looks to the user in many respects
D 11
like the Yale ASCII Terminal Communication System II.
E 11
I 11
like the Yale
.Tn ASCII
Terminal Communication System II.
E 11
D 7
.I Tn3270
E 7
I 7
.Nm Tn3270
E 7
D 11
is actually a modification of the Arpanet TELNET user interface (see
E 11
I 11
is actually a modification of the Arpanet
.Tn TELNET
user interface (see
E 11
D 7
.IR telnet (1))
E 7
I 7
.Xr telnet  1  )
E 7
D 6
that interprets and generates raw 3270 control streams.
E 6
I 6
which will, in certain circumstances, interpret and generate
raw 3270 control streams.
E 6
D 7
.PP
E 7
I 7
.Pp
E 7
D 6
Emulation of the 3270 terminal is done in the Unix process.
E 6
I 6
The flags to
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
are as follows:
D 7
.TP +2
-d
E 7
I 7
D 11
.Tw Fl
.Tp Fl d
E 11
I 11
.Bl -tag -width Fl
.It Fl d
E 11
E 7
Turn on socket-level tracing (for super-user only)
D 7
.TP
-n filename
E 7
I 7
D 11
.Ct Fl n
.Ar filename
.Cx
E 11
I 11
.Fl n Ns Ar filename
E 11
E 7
Specify a file to receive network trace data
output (from commands "toggle netdata" and
"toggle options", see
D 7
.IR telnet (1c));
E 7
I 7
.Xr telnet 1 ) ;
E 7
the default is for output
to be directed to the standard error file.
D 7
.TP
-t commandname
Specify a \s-UNIX\s0 command to process IBM 4994 style transparent mode
E 7
I 7
D 11
.Ct Fl t
.Ar commandname
.Cx
Specify a UNIX
command to process IBM 4994 style transparent mode
E 7
data received from the remote IBM machine.
D 7
.TP
sysname
E 7
I 7
.Tp Ar sysname
E 11
I 11
.Fl t Ns Ar commandname
Specify a
.Tn UNIX
command to process
.Tn IBM
4994 style transparent mode
data received from the remote
.Tn IBM
machine.
.It Ar sysname
E 11
E 7
The name of the remote system.  If the remote name
is NOT specified, the user will be prompted for a
command (see below).
D 7
.TP
port
E 7
I 7
D 11
.Tp Ar port
E 11
I 11
.It Ar port
E 11
E 7
The port to connect to on the remote system.
Normally,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
attempts to connect to the
D 11
standard TELNET port (port
E 11
I 11
standard
.Tn TELNET
port (port
E 11
23) on the remote machine.
D 7
.sp 
.PP
E 7
I 7
D 11
.Tp
E 11
I 11
.El
E 11
.Pp
E 7
When
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
first connects to the remote system, it will negotiate to go into
3270 mode.
Part of this negotiation involves telling the remote system what model
3270 it is emulating.
In all cases,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
emulates a 3278 terminal.
To decide which specific model,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
looks at the number of lines and columns on the actual terminal (as
defined in the
D 7
.B TERM
E 7
I 7
.Ev TERM
E 7
environment variable; see
D 7
.IR termcap (5)).
The terminal (or window in which tn3270 is running, on multiple
E 7
I 7
.Xr termcap  5  ) .
The terminal (or window in which
.Nm tn3270
is running, on multiple
E 7
window systems) must have at least 80 columns and 24 lines, or
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
will not go into emulation mode.
If the terminal does have at least 80 columns and at least 24 lines,
the following table describes the emulation:
D 7
.sp 
E 7
I 7
.Pp
E 7
.ne 7v
D 7
.nf
.ta 0.5i 1.5i
         minimum size             emulated
        (rows*columns)            terminal
        --------------          ------------
            27*132              3278 model 5
            43*80               3278 model 4
            32*80               3278 model 3
            24*80               3278 model 2.
.fi
.sp
.PP
Emulation of the 3270 terminal is done in the \s-UNIX\s0 process.
E 7
I 7
D 11
.Ds C
.Cw (rows*columns)
.Cl minimum_size	emulated
.Cl (rows*columns)	terminal
.Cl --------------	------------
.Cl 27*132	3278 model 5
.Cl 43*80	3278 model 4
.Cl 32*80	3278 model 3
.Cl 24*80	3278 model 2.
.Cw
.De
E 11
I 11
.Bd -filled -offset center
.Bl -column (rows*columns)
.It minimum_size	emulated
.It (rows*columns)	terminal
.It --------------	------------
.It 27*132	3278 model 5
.It 43*80	3278 model 4
.It 32*80	3278 model 3
.It 24*80	3278 model 2.
.El
.Ed
E 11
.Pp
D 11
.Pp
Emulation of the 3270 terminal is done in the UNIX
E 11
I 11
Emulation of the 3270 terminal is done in the
.Tn UNIX
E 11
process.
E 7
E 6
This emulation involves mapping
3270-style commands from the host
into appropriate sequences to control the user's terminal screen.
D 7
.I Tn3270
E 7
I 7
.Nm Tn3270
E 7
uses
D 7
.IR curses (3x)
E 7
I 7
.Xr curses 3
E 7
and the
D 7
.I /etc/termcap
E 7
I 7
.Pa /usr/share/misc/termcap
E 7
file to do this.
The emulation also involves simulating the special 3270 keyboard keys
(program function keys, etc.)
by mapping sequences of keystrokes
D 11
from the ASCII keyboard into appropriate 3270 control strings.
E 11
I 11
from the
.Tn ASCII
keyboard into appropriate 3270 control strings.
E 11
This mapping is terminal dependent and is specified
in a description file,
D 7
.IR /etc/map3270 ,
E 7
I 7
.Pa /usr/share/misc/map3270 ,
E 7
(see
D 7
.IR map3270 (5))
E 7
I 7
.Xr map3270  5  )
E 7
or in an environment variable
D 7
.I MAP3270
E 7
I 7
.Ev MAP3270
E 7
D 6
(see
E 6
I 6
(and, if necessary,
D 7
.IR MAP3270A ,
.IR MAP3270B ,
E 7
I 7
.Ev MAP3270A  ,
.Ev MAP3270B ,
E 7
and so on - see
E 6
D 7
.IR mset (1)).
E 7
I 7
.Xr mset  1  ) .
E 7
D 11
Any special function keys on the ASCII keyboard are used whenever possible.
E 11
I 11
Any special function keys on the
.Tn ASCII
keyboard are used whenever possible.
E 11
If an entry for the user's terminal
is not found,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
looks for an entry for the terminal type
D 7
.B unknown.
E 7
I 7
.Em unknown .
E 7
If this is not found,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
uses a default keyboard mapping
(see
D 7
.IR map3270 (5)).
.PP
The first character of each special keyboard mapping sequence 
E 7
I 7
.Xr map3270  5  ) .
.Pp
The first character of each special keyboard mapping sequence
E 7
D 11
is either an ASCII escape (ESC),
a control character, or an ASCII delete (DEL).
E 11
I 11
is either an
.Tn ASCII
escape
.Pq Tn ESC ,
a control character, or an
.Tn ASCII
delete
.Pq Tn DEL .
E 11
If the user types an unrecognized function key sequence,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
D 11
sends an ASCII bell (BEL), or a visual bell if
E 11
I 11
sends an
.Tn ASCII
bell
.Pq Tn BEL ,
or a visual bell if
E 11
defined in the user's termcap entry, to the user's terminal
D 11
and nothing is sent to the IBM host.
E 11
I 11
and nothing is sent to the
.Tn IBM
host.
E 11
D 7
.PP
E 7
I 7
.Pp
E 7
If
D 7
.I tn3270 
E 7
I 7
.Nm tn3270
E 7
is invoked without specifying a remote host system name,
it enters local command mode,
D 7
indicated by the prompt ``tn3270>''.
E 7
I 7
indicated by the prompt
.Dq Li tn3270>\  .
E 7
In this mode,
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
accepts and executes
D 6
the following
commands:
.sp 
.nf
.ta 0.5i 1.5i
	open	connect to a remote host
	close	close the current connection
	quit	exit tn3270
	z	suspend tn3270
	status	print connection status
	?	print help information
.fi
.sp
Other common
.I telnet
commands are not available in
.I tn3270.
E 6
I 6
all the commands of
D 7
.IR telnet (1),
E 7
I 7
.Xr telnet  1  ,
E 7
plus one additional command:
D 7
.TP +2
transcom
Specify \s-UNIX\s0 command for IBM 4994 style transparent mode processing.
.PP
E 6
.I Tn3270
E 7
I 7
.Pp
D 11
.Tw Ar
.Tp Ic transcom
Specify UNIX
command for IBM 4994 style transparent mode processing.
.Tp
E 11
I 11
.Bl -tag -width Ar
.It Ic transcom
Specify
.Tn UNIX
command for
.Tn IBM
4994 style transparent mode processing.
.El
E 11
.Pp
.Nm Tn3270
E 7
command mode may also be entered, after connecting to a host, by typing
D 6
a special escape character
(typically control-C).
E 6
I 6
a special escape sequence.
If
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
has succeeded in negotiating 3270 mode with the remote host, the
escape sequence will be as defined by the map3270 (see
D 7
.IR map3270 (5))
E 7
I 7
.Xr map3270  5  )
E 7
entry for the user's terminal type
(typically control-C);
otherwise the escape sequence will initially be set to the
D 7
single character '^]'
E 7
I 7
single character
.Sq Li \&^]
E 7
(control right square bracket).
E 6
D 7
.PP
E 7
I 7
.Pp
E 7
While in command mode, any host login session is still alive
but temporarily suspended.
The host login session may be resumed by entering an empty line
D 7
(press the RETURN key)
E 7
I 7
(press the
D 11
.Li RETURN
E 11
I 11
.Tn RETURN
E 11
key)
E 7
in response to the command prompt.
A session may be terminated by logging off the foreign host,
or by typing ``quit'' or ``close'' while in local command mode.
D 7
.SH FILES
/etc/termcap
E 7
I 7
.Sh FILES
D 11
.Dw /usr/share/misc/termcap
.Di L
.Dp Pa /usr/share/misc/termcap
E 7
.br
D 7
/etc/map3270
.SH AUTHOR
E 7
I 7
.Dp Pa /usr/share/misc/map3270
.Dp
.Sh AUTHOR
E 7
Greg Minshall
E 11
I 11
.Bl -tag -width /usr/share/misc/termcap -compact
.It Pa /usr/share/misc/termcap
.It Pa /usr/share/misc/map3270
.El
.\" .Sh AUTHOR
.\" Greg Minshall
E 11
I 6
D 7
.SH NOTES
.PP
E 7
I 7
.Sh NOTES
E 7
D 11
The IBM 4994 style transparent mode command is invoked when
E 11
I 11
The
.Tn IBM
4994 style transparent mode command is invoked when
E 11
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
D 11
receives IBM 4994 style transparent output from the remote host.
E 11
I 11
receives
.Tn IBM
4994 style transparent output from the remote host.
E 11
Output and input pipes are created for communication between the two
processes.
The pipes are closed when a 3270 clear command is received from the remote
D 13
hosts, signalling the end of transparent mode output.
E 13
I 13
hosts, signaling the end of transparent mode output.
E 13
D 11
Transparent mode is necessary for sending ASCII control characters over the
3270 terminal connection; ASCII graphics terminal support is accomplished this
E 11
I 11
Transparent mode is necessary for sending
.Tn ASCII
control characters over the
3270 terminal connection;
.Tn ASCII
graphics terminal support is accomplished this
E 11
way.
Developers of
D 7
.I transcom
E 7
I 7
.Ic transcom
E 7
commands should note that the
D 7
.I transcom
E 7
I 7
.Ic transcom
E 7
D 11
stdin pipe end will be in CBREAK mode, with ECHO and CRMOD turned off.
E 11
I 11
stdin pipe end will be in
.Dv CBREAK
mode, with
.Dv ECHO
and
.Dv CRMOD
turned off.
E 11
E 6
D 7
.SH SEE ALSO
D 6
mset(1), telnet(1), termcap(3x), termcap(5), map3270(5),
E 6
I 6
mset(1), telnet(1), curses(3x), termcap(3x), termcap(5), map3270(5),
E 6
\fIYale ASCII Terminal Communication
System II Program Description/Operator's Manual\fR
(IBM SB30-1911)
.SH BUGS
E 7
I 7
.Sh ENVIRONMENT
.Nm Tn3270
checks the following environment variables:
.Ev TERM ,
.Ev MAP3270 ,
.Ev MAP3270[A...] .
Information on these can be found in
.Xr mset 1 .
.Nm Tn3270
also checks
.Ev SHELL ,
.Ev KEYBD
and 
.Ev API3270 .
.Sh SEE ALSO
.Xr mset 1 ,
.Xr telnet 1 ,
.Xr curses 3 ,
.Xr termcap 3 ,
.Xr termcap 5 ,
.Xr map3270 5 ,
D 11
.br
.Em Yale ASCII Terminal Communication
.Em System II Program Description/Operator's Manual
.Pq IBM SB30-1911
E 11
I 11
.Rs
.%T "Yale ASCII Terminal Communication"
.%B "System II Program Description/Operator's Manual"
.%R IBM SB30-1911
.Re
E 11
.Sh HISTORY
D 11
.Nm
appeared in 4.3 BSD.
E 11
I 11
The
.Nm tn3270
command appeared in
.Bx 4.3 .
E 11
.Sh BUGS
E 7
D 6
Performance is slow and uses system resources prodigiously.
E 6
I 6
Tn3270 is slow and uses system resources prodigiously.
E 6
D 7
.PP
E 7
I 7
.Pp
E 7
Not all 3270 functions are supported,
nor all Yale enhancements.
I 6
D 7
.PP
E 7
I 7
.Pp
E 7
Error conditions (attempting to enter data in a protected field, for
example) should cause a message to be sent to the user's terminal
instead of just ringing a bell.
E 6
E 1
