#!/bin/csh -f
mv /nbsd/sys/tahoe/tags /nbsd/sys/tahoe/tags.tmp
mv /nbsd/sys/vax/tags /nbsd/sys/vax/tags.tmp
mv /nbsd/sys/GENERIC /nbsd/sys/GENERIC.tmp

echo '::::::::' conf '::::::::' 
foreach f (GENERIC LINT files files.vax)
	diff /nbsd/usr/src/sys/conf/$f conf
end
diff /nbsd/usr/src/sys/conf/makefile.vax conf/Makefile.vax

foreach d (dist cassette/Makefile consolerl/Makefile floppy/Makefile h mdec stand net* sys vax*)
	echo '::::::::' $d '::::::::' 
	diff /nbsd/usr/src/sys/$d $d
end

diff -r /nbsd/sys .

mv /nbsd/sys/tahoe/tags.tmp /nbsd/sys/tahoe/tags
mv /nbsd/sys/vax/tags.tmp /nbsd/sys/vax/tags
mv /nbsd/sys/GENERIC.tmp /nbsd/sys/GENERIC
