h62405
s 00002/00002/00103
d D 8.1 93/06/09 22:51:57 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00074/00046/00031
d D 6.5 91/03/16 18:10:52 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00003/00013/00074
d D 6.4 90/06/24 22:02:12 trent 6 5
c new copyright & pathname (renice)
e
s 00015/00003/00072
d D 6.3 89/08/17 13:29:58 bostic 5 4
c add Berkeley specific copyright notice
e
s 00004/00007/00071
d D 6.2 86/05/19 20:05:50 karels 4 3
c realieyt
e
s 00001/00001/00077
d D 6.1 85/04/27 13:44:51 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00062/00018/00016
d D 5.1 85/04/27 13:44:21 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00034/00000/00000
d D 4.1 85/04/27 13:43:58 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1983 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
E 5
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
I 5
D 7
.UC 7
E 5
D 2
.TH RENICE 8 "4/1/81"
E 2
I 2
D 3
.TH RENICE 8 "24 July 1983"
E 3
I 3
.TH RENICE 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
renice \- alter priority of running process by changing nice
E 2
I 2
renice \- alter priority of running processes
E 2
.SH SYNOPSIS
D 6
.B /etc/renice
E 6
I 6
.B renice
E 6
D 2
pid
[ priority ]
E 2
I 2
priority [ [
.B \-p
] pid ... ] [ [
.B \-g
] pgrp ... ] [ [
.B \-u
] user ... ]
E 2
.SH DESCRIPTION
.I Renice
E 7
I 7
.Dd %Q%
.Dt RENICE 8
.Os BSD 4
.Sh NAME
.Nm renice
.Nd alter priority of running processes
.Sh SYNOPSIS
.Nm renice
.Ar priority
.Oo
.Op Fl p
.Ar pid ...
.Oc
.Oo
.Op Fl g
.Ar pgrp ...
.Oc
.Oo
.Op Fl u
.Ar user ...
.Oc
.Sh DESCRIPTION
.Nm Renice
E 7
D 2
can be used by the super-user to alter the 
priority of a running process.
By default, the nice of the process is made \*(lq19\*(rq which means that it
will run only when nothing else in the system wants to.  This can be used
to nail long running processes which are interfering with interactive work.
E 2
I 2
alters the 
scheduling priority of one or more running processes.
D 7
The
.I who
E 7
I 7
The following
.Ar who
E 7
parameters are interpreted as process ID's, process group
ID's, or user names.
D 7
.IR Renice 'ing
E 7
I 7
.Nm Renice Ns 'ing
E 7
a process group causes all processes in the process group
to have their scheduling priority altered.  
D 7
.IR Renice 'ing
E 7
I 7
.Nm Renice Ns 'ing
E 7
a user causes all processes owned by the user to have
their scheduling priority altered.
By default, the processes to be affected are specified by
D 7
their process ID's.  To force 
.I who
parameters to be interpreted as process group ID's, a
.B \-g 
may be specified.  To force the
.I who
parameters to be interpreted as user names, a
.B \-u
may be given.  Supplying
.B \-p
will reset 
.I who
E 7
I 7
their process ID's.
.Pp
Options supported by
.Nm renice :
.Bl -tag -width Ds
.It Fl g
Force 
.Ar who
parameters to be interpreted as process group ID's.
.It Fl u
Force the
.Ar who
parameters to be interpreted as user names.
.It Fl p
Resets the
.Ar who
E 7
interpretation to be (the default) process ID's.
I 7
.El
.Pp
E 7
For example,
D 7
.sp
D 6
	/etc/renice +1 987 -u daemon root -p 32 
E 6
I 6
	renice +1 987 -u daemon root -p 32 
E 6
.sp
E 7
I 7
.Bd -literal -offset
renice +1 987 -u daemon root -p 32
.Ed
.Pp
E 7
would change the priority of process ID's 987 and 32, and
all processes owned by users daemon and root.
E 2
D 7
.PP
E 7
I 7
.Pp
E 7
D 2
.I Renice
can be given a second argument to choose a nice other than the default.
Negative nices can be used to make things go very fast.
E 2
I 2
Users other than the super-user may only alter the priority of
processes they own,
and can only monotonically increase their ``nice value''
D 4
within the range 0 to PRIO_MIN (20).
E 4
I 4
D 7
within the range 0 to PRIO_MAX (20).
E 7
I 7
within the range 0 to
.Dv PRIO_MAX
(20).
E 7
E 4
(This prevents overriding administrative fiats.)
The super-user
may alter the priority of any process
D 4
and set the priority to any value in the range PRIO_MAX (\-20)
to PRIO_MIN.
E 4
I 4
D 7
and set the priority to any value in the range PRIO_MIN (\-20)
to PRIO_MAX.
E 7
I 7
and set the priority to any value in the range
.Dv PRIO_MIN
(\-20)
to
.Dv PRIO_MAX .
E 7
E 4
Useful priorities are:
D 4
19 (the affected processes will run only when nothing else
E 4
I 4
20 (the affected processes will run only when nothing else
E 4
in the system wants to),
0 (the ``base'' scheduling priority),
anything negative (to make things go very fast).
E 2
D 7
.SH FILES
D 2
/vmunix
.br
/dev/kmem
E 2
I 2
/etc/passwd	to map user names to user ID's
E 2
.SH SEE ALSO
D 2
nice(1)
E 2
I 2
getpriority(2), setpriority(2)
E 2
.SH BUGS
E 7
I 7
.Sh FILES
.Bl -tag -width /etc/passwd -compact
.It Pa /etc/passwd
to map user names to user ID's
.El
.Sh SEE ALSO
.Xr getpriority 2 ,
.Xr setpriority 2
.Sh BUGS
E 7
D 2
If you make the nice very negative, then the process cannot be interrupted.
To regain control you must put the nice back (e.g. to 0.)
E 2
I 2
D 4
If you make the priority very negative,
then the process cannot be interrupted.
To regain control you make the priority greater than zero.
E 4
Non super-users can not increase scheduling priorities of their own processes,
even if they were the ones that decreased the priorities in the first place.
I 7
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
E 7
E 2
E 1
