h40281
s 00024/00083/00030
d D 5.7 90/05/12 15:36:30 bostic 7 6
c update for new make
e
s 00003/00013/00110
d D 5.6 89/08/20 17:38:54 karels 6 5
c /sys/h is no more; sys becomes general case
e
s 00014/00003/00109
d D 5.5 89/04/11 14:11:24 bostic 5 4
c add Berkeley specific copyright
e
s 00061/00012/00051
d D 5.4 88/01/17 21:32:08 karels 4 3
c vax, tahoe self-configuration
e
s 00006/00002/00057
d D 5.3 86/10/13 17:03:48 sam 3 2
c add tahoe
e
s 00003/00007/00056
d D 5.2 86/05/11 15:55:01 karels 2 1
c fix up for distribution (let's keep it)
e
s 00063/00000/00000
d D 5.1 86/05/11 15:35:41 karels 1 0
c date and time created 86/05/11 15:35:41 by karels
e
u
U
t
T
I 1
D 7
#
D 5
# Copyright (c) 1983,1986 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
E 5
I 5
D 6
# Copyright (c) 1983, 1986 The Regents of the University of California.
E 6
I 6
# Copyright (c) 1983, 1986, 1989 The Regents of the University of California.
E 6
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
#
E 7
#	%W% (Berkeley) %G%
#
D 2
# Doing a make install builds /usr/include
#
# Define SHARED to indicate whether you want
# symbolic links to the system source (``symlinks''),
# or a separate copy (``copies'').
# (latter useful in environments where it's
# not possible to keep /sys publicly readable)
E 2
I 2
# Makefile for /usr/include, used to convert system include subdirectories
D 7
# between symbolic links and copies of kernel headers.
# May also be used to update copies from kernel header files.
E 7
I 7
# between symbolic links and copies of kernel headers.  May also be used to
# update copies from kernel header files.
E 7
E 2
#
D 7
# The ``rm -rf''s used below are safe because rm doesn't
# follow symbolic links.
E 7
I 7
# The ``rm -rf''s used below are safe because rm doesn't follow symbolic
# links.
E 7
#
D 7
DESTDIR=
D 3
MACHINE=vax
MACHDEP=${MACHINE} vaxif vaxmba vaxuba
E 3
I 3
D 4
#ifdef vax
#MACHINE=vax
#MACHDEP=${MACHINE} vaxif vaxmba vaxuba
#endif
MACHINE=tahoe
MACHDEP=${MACHINE} tahoeif tahoevba
E 3
NETDIRS=net netimp netinet netns
SYSDIRS=${NETDIRS} stand ${MACHDEP}
E 4
I 4
MACHDEP.vax=	vaxif vaxmba vaxuba
MACHDEP.tahoe=	tahoeif tahoevba
NETDIRS=	net netimp netinet netns
D 6
SYSDIRS=	${NETDIRS} ${MACHINE}
E 6
I 6
SYSDIRS=	sys ${NETDIRS} ${MACHINE}
E 7
I 7

E 7
E 6
E 4
SYS=/sys
I 7
DIRS=	sys net netimp netinet netns ${MACHINE}
.if (${MACHINE} == "tahoe")
DIRS+=	tahoeif tahoevba
.elif (${MACHINE} == "vax")
DIRS+=	vaxif vaxmba vaxuba
.endif
E 7

all:
	@echo "\"make symlinks\", \"make copies\", or \"make update\" only"
	@false

D 4
symlinks:
E 4
I 4
D 7
symlinks: symlinks.${MACHINE}
E 4
	for i in ${SYSDIRS}; do \
		rm -rf $$i; \
		ln -s ${SYS}/$$i $$i; \
	done
E 7
I 7
copies:
E 7
D 4
	rm -rf sys
E 4
I 4
D 6
	rm -rf sys machine
E 4
	ln -s ${SYS}/h sys
E 6
I 6
	rm -rf machine
E 6
I 4
	ln -s ${MACHINE} machine
E 4
D 7

D 4
copies:
E 4
I 4
symlinks.vax:
	for i in ${MACHDEP.vax}; do \
E 7
I 7
	-for i in ${DIRS}; do \
E 7
		rm -rf $$i; \
D 7
		ln -s ${SYS}/$$i $$i; \
E 7
I 7
		(cd ${SYS}; tar cf - $$i/*.h) | tar xpfB -; \
E 7
	done

D 7
symlinks.tahoe:
	for i in ${MACHDEP.tahoe}; do \
E 7
I 7
symlinks:
	rm -rf machine
	ln -s ${MACHINE} machine
	for i in ${DIRS}; do \
E 7
		rm -rf $$i; \
		ln -s ${SYS}/$$i $$i; \
	done

D 7
copies: copies.${MACHINE}
E 4
	-for i in ${SYSDIRS}; do \
		rm -rf $$i; \
		(cd ${SYS}; tar cf - $$i/*.h) | tar xpfB -; \
	done
D 6
	rm -rf sys;
	mkdir sys; 
	chmod 775 sys;
	-(cd ${SYS}/h; tar cf - *.h) | (cd sys; tar xpfB -)
E 6
I 4
	rm -f machine
E 7
I 7
update:
	rm -rf machine
E 7
	ln -s ${MACHINE} machine
E 4
D 7

D 4
update:
E 4
I 4
copies.vax:
	-for i in ${MACHDEP.vax}; do \
		rm -rf $$i; \
		(cd ${SYS}; tar cf - $$i/*.h) | tar xpfB -; \
	done

copies.tahoe:
	-for i in ${MACHDEP.tahoe}; do \
		rm -rf $$i; \
		(cd ${SYS}; tar cf - $$i/*.h) | tar xpfB -; \
	done

update: update.${MACHINE}
E 4
	-for i in ${SYSDIRS}; do \
E 7
I 7
	-for i in ${DIRS}; do \
E 7
		if [ ! -d $$i ]; \
		then \
			mkdir $$i; \
		fi; \
		for j in `cd ${SYS}/$$i; echo *.[ih]`; do \
			cmp -s ${SYS}/$$i/$$j $$i/$$j || \
D 7
			install -c -m 444 ${SYS}/$$i/$$j $$i/$$j; \
E 7
I 7
			install -c -o ${BINOWN} -g ${BINGRP} -m 444 \
			    ${SYS}/$$i/$$j $$i/$$j; \
E 7
		done; \
	done
D 6
	for j in `cd ${SYS}/h; echo *.[ih]`; do \
		cmp -s ${SYS}/h/$$j sys/$$j || \
		{ echo "install -c -m 444 ${SYS}/h/$$j sys/$$j"; \
		install -c -m 444 ${SYS}/h/$$j sys/$$j; } \
	done;
E 6
I 4
D 7
	rm -f machine
	ln -s ${MACHINE} machine
E 7

D 7
update.vax:
	-for i in ${MACHDEP.vax}; do \
		if [ ! -d $$i ]; \
		then \
			mkdir $$i; \
		fi; \
		for j in `cd ${SYS}/$$i; echo *.[ih]`; do \
			cmp -s ${SYS}/$$i/$$j $$i/$$j || \
			install -c -m 444 ${SYS}/$$i/$$j $$i/$$j; \
		done; \
	done

update.tahoe:
	-for i in ${MACHDEP.tahoe}; do \
		if [ ! -d $$i ]; \
		then \
			mkdir $$i; \
		fi; \
		for j in `cd ${SYS}/$$i; echo *.[ih]`; do \
			cmp -s ${SYS}/$$i/$$j $$i/$$j || \
			install -c -m 444 ${SYS}/$$i/$$j $$i/$$j; \
		done; \
	done
E 7
I 7
clean cleandir depend lint tags:
E 7
E 4
E 1
