h30857
s 00041/00031/00010
d D 6.3 91/03/16 17:06:01 cael 4 3
c macro and text revision (-mdoc version 3)
e
s 00002/00002/00039
d D 6.2 90/06/24 21:30:59 trent 3 2
c new pathnames (rdump & rmt)
e
s 00001/00001/00040
d D 6.1 85/04/27 15:39:44 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00041/00000/00000
d D 5.1 85/04/27 15:39:26 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\" %sccs.include.redist.man%
E 4
.\"
D 2
.TH RDUMP 8C "19 January 1983"
E 2
I 2
D 4
.TH RDUMP 8C "%Q%"
E 2
.UC 5
.SH NAME
rdump \- file system dump across the network
.SH SYNOPSIS
D 3
.B /etc/rdump
E 3
I 3
.B rdump
E 3
[ key [
.I argument
\&... ] filesystem ]
.SH DESCRIPTION
.I Rdump
copies to magnetic tape all files
changed after a certain date
in the
.I filesystem.
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt RDUMP 8
.Os BSD 4.2
.Sh NAME
.Nm rdump
.Nd file system dump across the network
.Sh SYNOPSIS
.Nm rdump
.Oo
.Ar flags
.Op Ar argument ...
.Ar filesystem
.Oc
.Sh DESCRIPTION
.Nm Rdump
remotely backs up files across a network in the same manner as
.Xr dump 8
locally backs up files.
E 4
The command is identical in operation to
D 4
.IR dump (8)
E 4
I 4
.Xr dump 8
E 4
except the 
D 4
.I f
key should be specified and the file
E 4
I 4
.Cm f
key must be specified and the file
.Ar argument
E 4
supplied should be of the form
D 4
.IR machine:device .
.PP
.I Rdump
E 4
I 4
.Pa machine:device .
.Pp
.Nm Rdump
E 4
creates a remote server,
D 3
.IR /etc/rmt ,
E 3
I 3
D 4
.IR rmt ,
E 4
I 4
.Xr rmt ,
E 4
E 3
on the client machine to access the tape
device.
D 4
.SH "SEE ALSO"
dump(8),
rmt(8C)
.SH DIAGNOSTICS
E 4
I 4
.Sh SEE ALSO
.Xr dump 8 ,
.Xr rmt 8
.Sh DIAGNOSTICS
E 4
Same as 
D 4
.IR dump (8)
E 4
I 4
.Xr dump 8
E 4
with a few extra related to the network.
I 4
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 4
E 1
