h43293
s 00001/00001/00078
d D 8.2 93/12/30 15:39:37 mckusick 9 8
c copyediting for Usenix manuals
e
s 00002/00002/00077
d D 8.1 93/06/06 22:25:12 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00073/00035/00006
d D 6.5 91/04/23 23:50:32 cael 7 6
c mdoc version three/bsd copyright
e
s 00005/00004/00036
d D 6.4 91/04/18 18:53:57 bostic 6 5
c new copyright; att/bsd/shared
e
s 00012/00008/00028
d D 6.3 90/06/24 19:24:08 cael 5 4
c converted man page
e
s 00019/00030/00017
d D 6.2 86/12/10 17:00:20 bostic 4 3
c general cleanup
e
s 00001/00001/00046
d D 6.1 85/04/29 18:08:58 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00002/00044
d D 5.1 85/04/29 18:08:49 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00046/00000/00000
d D 4.1 85/04/29 18:08:41 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
D 6
.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 7
.\" Copyright (c) 1986 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1986, 1991 Regents of the University of California.
E 7
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1986, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
E 6
E 5
.\"
D 2
.TH WHO 1 
E 2
I 2
D 3
.TH WHO 1  "18 January 1983"
E 3
I 3
D 5
.TH WHO 1 "%Q%"
E 5
I 5
D 6
.\"     %W% (Berkeley) %G%
E 6
I 6
D 7
.\" %sccs.include.proprietary.roff%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
E 6
.\"
D 7
.TH WHO 1 "%Q"
E 5
E 3
E 2
.AT 3
.SH NAME
who \- who is on the system
.SH SYNOPSIS
.B who
[ who-file ] [
.B "am I"
]
.SH DESCRIPTION
D 4
.I Who,
without an argument,
lists the login name, terminal name, and login time
for each current UNIX user.
E 4
I 4
D 5
\fIWho,\fP without any argument, reads the /etc/utmp file,
E 5
I 5
\fIWho,\fP without any argument, reads the /var/run/utmp file,
E 5
and lists the login name, terminal name, and login time for each
user currently logged into the system.  If a single argument is
D 5
given, \fIwho\fP uses that file instead of /etc/utmp.  Typically,
that file will be /usr/adm/wtmp, which contains a record of all
E 5
I 5
given, \fIwho\fP uses that file instead of /var/run/utmp.  Typically,
that file will be /var/log/wtmp, which contains a record of all
E 5
the logins, logouts, crashes, shutdowns and time changes since it
was created.  In either case, each login will be listed with the
user name, the terminal name (with "/dev/" suppressed), login date
and time, and, if applicable, the host logged in from.
E 4
.PP
D 4
Without an argument,
.I who
D 2
examines the /etc/utmp
E 2
I 2
examines the
.I /etc/utmp
E 2
file to obtain its information.
If a file is given, that file is examined.
Typically the given file will be /usr/adm/wtmp,
which contains a record of all the logins since it
was created.
Then
.I who
lists
logins, logouts, and crashes since the creation of
the wtmp file.
Each login is listed with user name,
terminal name (with `/dev/'
suppressed),
and date and time.
When an argument is given, logouts produce a similar line without a user name.
Reboots produce a line with `x' in the place of the device name,
and a fossil time indicative of when the system went down.
E 4
I 4
D 5
If /usr/adm/wtmp is being used as the file, the user name may be empty
E 5
I 5
If /var/log/wtmp is being used as the file, the user name may be empty
E 7
I 7
.Dd %Q%
.Dt WHO 1
.Os
.Sh NAME
.Nm who
.Nd display who is logged in
.Sh SYNOPSIS
.Nm who
.Op Ar am I
.Op Ar file 
.Sh DESCRIPTION
The utility
.Nm who
displays
a list of all users currently logged on, showing for each user
the login name,
tty name, the date and time of login, and hostname if not local.
.Pp
Available options:
.Pp
.Bl -tag -width file
.It Ar \&am I
Returns the invoker's real user name. 
.It Ar file
By default,
.Nm who
gathers information from the file
.Pa /var/run/utmp .
An alternate
.Ar file
may be specified which is usually
.Pa /var/run/wtmp
(or
.Pa /var/run/wtmp.[0-6]
depending on site policy as
.Pa wtmp
can grow quite large and daily versions may or may not
D 9
kept around after compression by
E 9
I 9
be kept around after compression by
E 9
.Xr ac 8 ) .
The
.Pa wtmp
file contains a record of every login, logout,
crash, shutdown and date change
since
.Pa wtmp
was last truncated or
created.
.El
.Pp
If
.Pa /var/log/wtmp
is being used as the file, the user name may be empty
E 7
E 5
or one of the special characters '|', '}' and '~'.  Logouts produce
an output line without any user name.  For more information on the
D 7
special characters, see utmp(5).
E 4
.PP
D 4
With two arguments,
as in `who am I' (and also `who are you'),
.I who
tells who you are logged in as.
E 4
I 4
With two arguments, as in `who am I' (and also `who are you'),
\fIwho\fP tells you who you are logged in as.
E 4
.SH FILES
I 4
.DT
E 4
D 5
/etc/utmp
E 5
I 5
/var/run/utmp
E 5
I 4
.br
D 5
/usr/adm/wtmp
E 5
I 5
/var/log/wtmp
E 5
E 4
.SH "SEE ALSO"
D 4
getuid(2), utmp(5)
E 4
I 4
last(1), users(1), getuid(2), utmp(5)
E 7
I 7
special characters, see
.Xr utmp 5 .
.Sh FILES
.Bl -tag -width /var/log/wtmp.[0-6] -compact
.It Pa /var/run/utmp
.It Pa /var/log/wtmp
.It Pa /var/log/wtmp.[0-6]
.El
.Sh SEE ALSO
.Xr last 1 ,
.Xr users 1 ,
.Xr getuid 2 ,
.Xr utmp 5
.Sh HISTORY
A
.Nm
command appeared in
.At v6 .
E 7
E 4
E 1
