h40396
s 00002/00002/00046
d D 8.1 93/06/02 00:04:34 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00047
d D 6.7 92/07/28 09:47:57 bostic 9 8
c include <signal.h>, not <sys/signal.h>
e
s 00038/00035/00010
d D 6.6 91/03/10 23:49:55 cael 8 7
c man page macro and text revisions (-mdoc version 3)
e
s 00003/00000/00042
d D 6.5 90/07/01 16:41:43 karels 7 6
c deprecate, point to new POSIX calls
e
s 00001/00011/00041
d D 6.4 90/06/23 17:52:50 trent 6 5
c new copyright notice
e
s 00014/00003/00038
d D 6.3 89/05/18 14:15:57 bostic 5 4
c add Berkeley specific copyright notice
e
s 00001/00001/00040
d D 6.2 86/05/15 15:24:21 anne 4 3
c spelling
e
s 00004/00002/00037
d D 6.1 85/05/09 17:43:04 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00028/00020/00011
d D 5.1 85/05/09 17:42:38 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00031/00000/00000
d D 4.1 85/05/09 17:42:00 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 8
.\" Copyright (c) 1983 The Regents of the University of California.
E 8
I 8
D 10
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 8
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
E 5
.\"
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 2
.TH PAUSE 2 
E 2
I 2
D 3
.TH SIGPAUSE 2 "7 July 1983"
E 3
I 3
D 8
.TH SIGPAUSE 2 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
pause \- stop until signal
E 2
I 2
sigpause \- atomically release blocked signals and wait for interrupt
E 2
.SH SYNOPSIS
D 2
.B pause()
E 2
I 2
.ft B
sigpause(sigmask)
.br
int sigmask;
.ft R
E 2
.SH DESCRIPTION
I 7
.B "This interface is made obsolete by sigsuspend(2).
.LP
E 7
D 2
.I Pause
never returns normally.
It is used to give up control while waiting for
a signal from
.IR kill (2)
or
.IR alarm (2).
Upon termination of a signal handler started during a
.I pause,
the
.I pause
call will return.
E 2
I 2
.I Sigpause
E 8
I 8
.Dd %Q%
.Dt SIGPAUSE 2
.Os BSD 4
.Sh NAME
.Nm sigpause
.Nd atomically release blocked signals and wait for interrupt
.Sh SYNOPSIS
D 9
.Fd #include <sys/signal.h>
E 9
I 9
.Fd #include <signal.h>
E 9
.Ft int
.Fn sigpause "int sigmask"
.Sh DESCRIPTION
.Sy This interface is made obsolete by
.Xr sigsuspend 2 .
.Pp
.Fn Sigpause
E 8
assigns 
D 8
.I sigmask
E 8
I 8
.Fa sigmask
E 8
to the set of masked signals
and then waits for a signal to arrive;
on return the set of masked signals is restored.
D 8
.I Sigmask
E 8
I 8
.Fa Sigmask
E 8
is usually 0 to indicate that no
D 8
signals are now to be blocked.
.I Sigpause
D 3
always terminates by being interrupted, returning EINTR.
E 3
I 3
always terminates by being interrupted, returning \-1 with
.I errno
set to EINTR.
E 3
.PP
In normal usage, a signal is blocked using
.IR sigblock (2),
D 4
to begin a critical section, variables modified on the occurance
E 4
I 4
to begin a critical section, variables modified on the occurrence
E 4
of the signal are examined to determine that there is no work
to be done, and the process pauses awaiting work by using
.I sigpause
with the mask returned by
.IR sigblock .
E 2
.SH SEE ALSO
I 7
sigsuspend(2), kill(2), sigaction(2), sigprocmask(2),
E 7
D 2
kill(1), kill(2), alarm(2), sigsys(2), signal(2), sigset(3), setjmp(3)
.SH "ASSEMBLER (PDP-11)"
(pause = 29.)
.br
.B sys pause
E 2
I 2
sigblock(2), sigvec(2)
E 8
I 8
signals are to be blocked.
.Fn Sigpause
always terminates by being interrupted, returning -1 with
.Va errno
set to
.Dv EINTR
.Sh SEE ALSO
.Xr sigsuspend 2 ,
.Xr kill 2 ,
.Xr sigaction 2 ,
.Xr sigprocmask 2 ,
.Xr sigblock 2 ,
.Xr sigvec 2
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2
and has been deprecated.
E 8
E 2
E 1
