#!/bin/sh
# Sample start servers file
/etc/atis
# allow atis to startup first
sleep 5
# Example servers - you don't need to atis if you don't plan on using
# anything that doesn't register names
/usr/local/cap/lsrv -P xx -t 'LaserWriter Plus'
/usr/local/cap/efsd
