/* A lexical scanner generated by flex */

/* scanner skeleton version:
 *
 * $Header: flex/RCS/flex.skel,v 2.13 90/05/26 17:24:13 vern Exp $
 *
 *	@(#)lex.skel	5.2 (Berkeley) 6/18/90
 */

#define FLEX_SCANNER

#include <stdio.h>

#ifdef __STDC__

#ifndef DONT_HAVE_STDLIB_H
#include <stdlib.h>
#else
void *malloc( unsigned );
void free( void* );
#endif

#define YY_USE_PROTOS
#define YY_USE_CONST
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#ifndef __STDC__
#include <stdlib.h>
#endif

#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#endif


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* there's no standard place to get these definitions */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "grapl.l"
#define INITIAL 0
#define A 1
#define str 2
#define def 3
#define thru 4
#define sh 5
# line 4 "grapl.l"
#undef	input
#undef	unput
#include <stdio.h>
#include <ctype.h>
#include "grap.h"
#include "y.tab.h"

extern	struct	symtab	symtab[];

#define	CADD	cbuf[clen++]=yytext[0]; if(clen>=CBUFLEN-1) {yyerror("string too long", cbuf); BEGIN A;}
#define	CBUFLEN	1500
char	cbuf[CBUFLEN];
int	clen, cflag;
int	c, delim;
# line 25 "grapl.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 96
typedef int yy_state_type;
static const short int yy_accept[299] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   96,   95,   89,    1,    3,   86,   87,   88,
       89,   89,   75,    4,   83,   89,   82,   77,   89,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   41,   42,
       89,   89,   77,   94,   91,   90,   94,   74,   31,   30,
       31,   72,   71,   81,   88,   84,   75,   75,   75,    0,
       75,   80,   78,   79,   77,    2,   77,   77,   77,   65,
       77,   77,   64,   77,   77,   77,   77,   27,   77,   77,
       77,   77,   77,   77,   77,   50,   33,   67,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   63,   77,   47,   77,   85,   76,   75,   77,   92,
       93,   74,   30,   31,   71,   75,    0,   75,   77,   77,
       77,   77,   77,   44,   77,   77,   77,   15,   77,   77,
       77,   77,   77,   77,   13,   25,   77,   77,   77,   77,
       77,   77,   21,   77,   77,   77,   77,   77,   12,   19,
       20,   38,   77,   69,   68,   77,   77,   77,   52,   77,
       77,   77,   70,   14,   77,   77,   77,   77,   77,   77,
       77,   43,   77,   51,   77,   76,   75,   76,   75,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   28,   77,
       77,   77,   48,   37,   35,   77,   62,   77,   10,   77,
       77,   77,   77,   45,    5,   77,   36,   23,   39,   77,
       77,   18,   77,   77,   61,   77,   17,   34,   77,   29,
        9,   77,   77,   66,   76,   75,   77,   59,   77,    6,
       16,   60,   77,   77,   11,   77,   77,   77,    8,   77,
       77,   10,   77,   77,   53,   40,   57,   23,   22,   77,
       46,   58,   56,   77,    9,   32,   51,   77,   49,   44,
        7,   11,   55,   77,   54,   24,   77,   77,   40,   52,
       77,   77,   73,   24,   77,   26,   10,    0

    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    1,    1,
        1,    1,    8,    1,    9,   10,    1,   11,   11,   12,
       11,   11,   11,   11,   11,   11,   11,    1,   13,   14,
       15,   16,    1,    1,   17,   17,   17,   18,   19,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,   20,    1,    1,   17,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   47,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    1,    1,    1,    1,    3,    4,    3,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    1
    } ;

static const short int yy_base[313] =
    {   0,
        0,    0,    0,   39,   47,   48,   68,  116,  164,  212,
      260,  308,  501,  502,  502,  502,  502,  485,  502,    0,
      492,   43,   75,  502,  483,  482,  481,    0,  492,   67,
       66,   27,   71,   66,   22,  456,   68,   69,  112,  114,
      468,   71,  116,  123,  121,  111,   25,  463,    0,    0,
      443,   52,  456,  502,  502,  502,   94,    0,  502,  487,
        0,  502,    0,  502,    0,  502,  170,  175,  219,  194,
      502,  502,  502,  502,    0,  502,  453,  449,  448,  464,
      452,  443,    0,  444,  157,  442,  454,  117,  458,  439,
      441,  438,  162,  130,  446,    0,    0,  167,  452,  447,

      438,  430,  443,  425,  434,   22,  441,  426,  442,  429,
      434,  164,  435,  420,  458,  199,  427,  420,  432,  209,
      433,  419,  414,    0,  161,  502,    0,  224,  429,  502,
      502,    0,  450,    0,    0,  266,  228,  270,  409,  415,
      414,  414,  412,  406,  422,  406,  398,    0,  414,  412,
      400,  405,  395,  412,    0,    0,  403,  402,  398,  409,
      405,  399,    0,  401,  404,  388,  402,  387,    0,    0,
        0,    0,  385,    0,    0,  422,  383,  388,  392,  396,
      391,  379,  415,    0,  391,  386,  374,  377,  375,  211,
      373,    0,  370,  343,  326,    0,  275,  246,    0,  327,

      327,  312,  307,  337,  305,  312,  314,  321,    0,  319,
      309,  317,    0,    0,    0,  316,    0,  312,  123,  311,
      297,  298,  304,    0,    0,  295,    0,    0,    0,  294,
      292,    0,  292,  291,    0,  306,    0,    0,  288,    0,
      288,  294,  297,    0,  230,  272,  271,    0,  266,    0,
        0,    0,  270,  277,  259,  273,  271,  269,    0,  290,
      261,    0,  249,  264,    0,  240,    0,    0,    0,  217,
        0,    0,    0,  224,    0,    0,    0,  212,    0,    0,
        0,    0,    0,  235,    0,    0,  176,  183,    0,    0,
      163,  135,  132,    0,   88,  502,   63,  502,  356,  361,

      366,  371,  376,  381,  384,  388,  389,  391,  393,  397,
      402,  407
    } ;

static const short int yy_def[313] =
    {   0,
      299,  299,  298,    3,  300,  300,  301,  301,  302,  302,
      303,  303,  298,  298,  298,  298,  298,  298,  298,  304,
      298,  298,  298,  298,  298,  298,  298,  305,  298,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      298,  306,  305,  298,  298,  298,  298,  307,  298,  298,
      308,  298,  309,  298,  304,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  305,  298,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  298,  310,  310,  305,  298,
      298,  307,  298,  308,  309,  298,  298,  298,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  298,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  310,  310,  310,  310,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  311,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  310,  310,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  311,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  312,  305,  305,  305,  305,
      305,  305,  298,  312,  305,  298,  305,    0,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298
    } ;

static const short int yy_nxt[551] =
    {   0,
       15,   16,   17,   18,   19,   20,   21,   15,   15,   22,
       23,   23,   24,   25,   26,   27,   28,   28,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   28,
       28,   39,   40,   41,   42,   43,   28,   44,   45,   46,
       47,   28,   48,   49,   50,   28,   15,   51,   52,   55,
       55,   56,   56,   67,   67,   84,   92,   53,  123,   93,
      124,   85,  128,  128,  172,  173,   57,   57,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   68,   69,   69,   14,   77,   78,
       81,   86,   95,   70,   97,   87,  107,   90,  130,   70,

       82,  262,   98,   71,   79,   88,   80,   96,   89,   91,
       83,  108,  297,  131,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   99,  293,  104,   14,  100,  296,  120,  121,
      101,  102,  105,  112,  109,  122,  103,  110,  115,  116,
      159,  113,  114,  111,  261,  117,  151,  118,  160,  152,
      119,  262,   14,   14,   59,   60,   14,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       67,   67,  157,   59,  194,  136,  136,  179,   70,  162,
      240,  146,  147,   70,   70,  148,  158,  180,   71,   70,

      195,  137,  137,   71,  138,  138,  163,  209,  164,  295,
       59,   59,   59,   60,   14,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   68,   69,
       69,   59,  184,  189,  197,  197,  293,   70,  138,  138,
      246,  246,  198,   70,  185,  239,  190,   71,  198,  292,
      291,  240,  199,  245,  245,  290,  246,  246,   59,   59,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,  136,  136,  289,   62,
      138,  138,  246,  246,   70,  197,  197,  288,   96,  287,
       70,  286,  285,  198,   71,  284,  283,  282,   71,  198,

      199,  281,  280,  199,  279,  278,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,  277,  276,  275,   62,  274,  273,
      272,  271,  270,  269,  267,  266,  265,  264,  263,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  244,   62,   62,   14,   14,   14,   14,
       14,   54,   54,   54,   54,   54,   58,   58,   58,   58,
       58,   61,   61,   61,   61,   61,   63,   63,   63,   63,
       63,   65,  243,   65,   65,   65,   75,   75,  127,  127,
      127,  132,  132,  134,  134,  135,  135,  196,  242,  196,

      196,  196,  268,  241,  268,  268,  268,  294,  238,  294,
      294,  294,   83,  237,  236,  235,  183,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  133,  200,  193,  192,  191,  188,  187,  186,  183,
      182,  181,  178,  177,  176,  175,  174,  171,  170,  169,
      168,  167,  166,  165,  161,  156,  155,  154,  153,  150,
      149,  145,  144,  143,  142,  141,  140,  139,  133,  129,
      126,  125,  106,   94,   76,   74,   73,   72,   66,   64,

      298,   13,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298
    } ;

static const short int yy_chk[551] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    5,
        6,    5,    6,   22,   22,   32,   35,    4,   47,   35,
       47,   32,   52,   52,  106,  106,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   23,   23,   23,    7,   30,   30,
       31,   33,   37,   23,   38,   33,   42,   34,   57,   23,

       31,  297,   38,   23,   30,   33,   30,   37,   33,   34,
       31,   42,  295,   57,    7,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,   39,  293,   40,    8,   39,  292,   46,   46,
       39,   39,   40,   44,   43,   46,   39,   43,   45,   45,
       94,   44,   44,   43,  219,   45,   88,   45,   94,   88,
       45,  219,    8,    8,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       67,   67,   93,    9,  125,   68,   68,  112,   67,   98,
      291,   85,   85,   68,   67,   85,   93,  112,   67,   68,

      125,   70,   70,   68,   70,   70,   98,  288,   98,  287,
        9,    9,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   69,   69,
       69,   10,  116,  120,  128,  128,  284,   69,  137,  137,
      245,  245,  128,   69,  116,  190,  120,   69,  128,  278,
      274,  190,  128,  198,  198,  270,  198,  198,   10,   10,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,  136,  136,  266,   11,
      138,  138,  246,  246,  136,  197,  197,  264,  263,  261,
      136,  260,  258,  197,  136,  257,  256,  255,  138,  197,

      246,  254,  253,  197,  249,  247,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,  243,  242,  241,   12,  239,  236,
      234,  233,  231,  230,  226,  223,  222,  221,  220,  218,
      216,  212,  211,  210,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  195,   12,   12,  299,  299,  299,  299,
      299,  300,  300,  300,  300,  300,  301,  301,  301,  301,
      301,  302,  302,  302,  302,  302,  303,  303,  303,  303,
      303,  304,  194,  304,  304,  304,  305,  305,  306,  306,
      306,  307,  307,  308,  308,  309,  309,  310,  193,  310,

      310,  310,  311,  191,  311,  311,  311,  312,  189,  312,
      312,  312,  188,  187,  186,  185,  183,  182,  181,  180,
      179,  178,  177,  176,  173,  168,  167,  166,  165,  164,
      162,  161,  160,  159,  158,  157,  154,  153,  152,  151,
      150,  149,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  133,  129,  123,  122,  121,  119,  118,  117,  115,
      114,  113,  111,  110,  109,  108,  107,  105,  104,  103,
      102,  101,  100,   99,   95,   92,   91,   90,   89,   87,
       86,   84,   82,   81,   80,   79,   78,   77,   60,   53,
       51,   48,   41,   36,   29,   27,   26,   25,   21,   18,

       13,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;


	if (yybgin-yysvec-1 == 0) {	/* witchcraft */
		BEGIN A;
	}


    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	if ( yy_bp[-1] == '\n' )
	    ++yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 299 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 298 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 30 "grapl.l"
;
	YY_BREAK
case 2:
# line 31 "grapl.l"
;
	YY_BREAK
case 3:
# line 32 "grapl.l"
return(ST);
	YY_BREAK
case 4:
# line 33 "grapl.l"
return(ST);
	YY_BREAK
case 5:
# line 35 "grapl.l"
return(yylval.i = LINE);
	YY_BREAK
case 6:
# line 36 "grapl.l"
{ yylval.i = ARROW; return(LINE); }
	YY_BREAK
case 7:
# line 37 "grapl.l"
return(yylval.i = CIRCLE);
	YY_BREAK
case 8:
# line 38 "grapl.l"
return(FRAME);
	YY_BREAK
case 9:
# line 39 "grapl.l"
return(TICKS);
	YY_BREAK
case 10:
# line 40 "grapl.l"
return(GRID);
	YY_BREAK
case 11:
# line 41 "grapl.l"
return(COORD);
	YY_BREAK
case 12:
# line 42 "grapl.l"
return(LOG);
	YY_BREAK
case 13:
# line 43 "grapl.l"
return(EXP);
	YY_BREAK
case 14:
# line 44 "grapl.l"
return(SIN);
	YY_BREAK
case 15:
# line 45 "grapl.l"
return(COS);
	YY_BREAK
case 16:
# line 46 "grapl.l"
return(ATAN2);
	YY_BREAK
case 17:
# line 47 "grapl.l"
return(SQRT);
	YY_BREAK
case 18:
# line 48 "grapl.l"
return(RAND);
	YY_BREAK
case 19:
# line 49 "grapl.l"
return(MAX);
	YY_BREAK
case 20:
# line 50 "grapl.l"
return(MIN);
	YY_BREAK
case 21:
# line 51 "grapl.l"
return(INT);
	YY_BREAK
case 22:
# line 52 "grapl.l"
return(PRINT);
	YY_BREAK
case 23:
# line 53 "grapl.l"
{ yylval.p = tostring(yytext+3); return(PIC); }
	YY_BREAK
case 24:
# line 54 "grapl.l"
{ yylval.p = tostring(yytext+5); return(GRAPH); }
	YY_BREAK
case 25:
# line 56 "grapl.l"
return(FOR);
	YY_BREAK
case 26:
# line 57 "grapl.l"
{ endfor(); }
	YY_BREAK
case 27:
# line 58 "grapl.l"
{ yylval.p = delimstr("loop body"); BEGIN A; return(DOSTR); }
	YY_BREAK
case 28:
# line 60 "grapl.l"
{ return(COPY); }
	YY_BREAK
case 29:
# line 61 "grapl.l"
{ BEGIN thru; return(THRU); }
	YY_BREAK
case 30:
# line 62 "grapl.l"
;
	YY_BREAK
case 31:
# line 63 "grapl.l"
{ yylval.op = copythru(yytext); BEGIN A; return(DEFNAME); }
	YY_BREAK
case 32:
# line 64 "grapl.l"
return(UNTIL);
	YY_BREAK
case 33:
# line 66 "grapl.l"
return(IF);
	YY_BREAK
case 34:
# line 67 "grapl.l"
{ yylval.p = delimstr("then part"); BEGIN A; return(THEN); }
	YY_BREAK
case 35:
# line 68 "grapl.l"
{ yylval.p = delimstr("else part"); BEGIN A; return(ELSE); }
	YY_BREAK
case 36:
# line 70 "grapl.l"
return(NEXT);
	YY_BREAK
case 37:
# line 71 "grapl.l"
return(yylval.i = DRAW);
	YY_BREAK
case 38:
# line 72 "grapl.l"
return(yylval.i = NEW);
	YY_BREAK
case 39:
# line 73 "grapl.l"
return(yylval.i = PLOT);
	YY_BREAK
case 40:
# line 74 "grapl.l"
return(LABEL);
	YY_BREAK
case 41:
# line 75 "grapl.l"
return(X);
	YY_BREAK
case 42:
# line 76 "grapl.l"
return(Y);
	YY_BREAK
case 43:
# line 78 "grapl.l"
{ yylval.i = TOP; return SIDE; }
	YY_BREAK
case 44:
# line 79 "grapl.l"
{ yylval.i = BOT; return SIDE; }
	YY_BREAK
case 45:
# line 80 "grapl.l"
{ yylval.i = LEFT; return SIDE; }
	YY_BREAK
case 46:
# line 81 "grapl.l"
{ yylval.i = RIGHT; return SIDE; }
	YY_BREAK
case 47:
# line 82 "grapl.l"
return(yylval.i = UP);
	YY_BREAK
case 48:
# line 83 "grapl.l"
return(yylval.i = DOWN);
	YY_BREAK
case 49:
# line 84 "grapl.l"
return(yylval.i = ACROSS);
	YY_BREAK
case 50:
# line 85 "grapl.l"
return(yylval.i = HEIGHT);
	YY_BREAK
case 51:
# line 86 "grapl.l"
return(yylval.i = WIDTH);
	YY_BREAK
case 52:
# line 87 "grapl.l"
return(yylval.i = RADIUS);
	YY_BREAK
case 53:
# line 88 "grapl.l"
return(yylval.i = INVIS);
	YY_BREAK
case 54:
# line 89 "grapl.l"
return(yylval.i = DOT);
	YY_BREAK
case 55:
# line 90 "grapl.l"
return(yylval.i = DASH);
	YY_BREAK
case 56:
# line 91 "grapl.l"
return(yylval.i = SOLID);
	YY_BREAK
case 57:
# line 93 "grapl.l"
{ yylval.i = LJUST; return JUST; }
	YY_BREAK
case 58:
# line 94 "grapl.l"
{ yylval.i = RJUST; return JUST; }
	YY_BREAK
case 59:
# line 95 "grapl.l"
{ yylval.i = ABOVE; return JUST; }
	YY_BREAK
case 60:
# line 96 "grapl.l"
{ yylval.i = BELOW; return JUST; }
	YY_BREAK
case 61:
# line 97 "grapl.l"
return(yylval.i = SIZE);
	YY_BREAK
case 62:
# line 99 "grapl.l"
return(yylval.i = FROM);
	YY_BREAK
case 63:
# line 100 "grapl.l"
return(yylval.i = TO);
	YY_BREAK
case 64:
# line 101 "grapl.l"
return(yylval.i = BY);
	YY_BREAK
case 65:
# line 102 "grapl.l"
return(yylval.i = AT);
	YY_BREAK
case 66:
# line 103 "grapl.l"
return(yylval.i = WITH);
	YY_BREAK
case 67:
# line 104 "grapl.l"
return(yylval.i = IN);
	YY_BREAK
case 68:
# line 105 "grapl.l"
return(yylval.i = OUT);
	YY_BREAK
case 69:
# line 106 "grapl.l"
return(yylval.i = OFF);
	YY_BREAK
case 70:
# line 108 "grapl.l"
{	BEGIN sh;
		if ((delim = input()) == '{') delim = '}';	/* no nested {} */
		shell_init(); }
	YY_BREAK
case 71:
# line 111 "grapl.l"
{
		int c;
		Obj *p;
		if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		} else {
			p = lookup(yytext, 0);
			if (p != NULL && p->type == DEFNAME) {
				c = input();
				unput(c);
				if (c == '(')
					dodef(p);
				else
					pbstr(p->val);
			} else
				shell_text(yytext);
		}
	}
	YY_BREAK
case 72:
# line 130 "grapl.l"
{ if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		  } else
			shell_text(yytext);
		}
	YY_BREAK
case 73:
# line 137 "grapl.l"
{ BEGIN def; }
	YY_BREAK
case 74:
# line 138 "grapl.l"
{ definition(yytext); BEGIN A; }
	YY_BREAK
case 75:
# line 140 "grapl.l"
{
		  yylval.f = atof(yytext); return(NUMBER); }
	YY_BREAK
case 76:
# line 143 "grapl.l"
{ if (yytext[1] == 'G' && yytext[2] == '2') {
			yylval.i = yytext[2];
			return(EOF);
		  } else {
			yylval.p = tostring(yytext);
			return(PIC);
		  }
		}
	YY_BREAK
case 77:
# line 152 "grapl.l"
{
		int c;
		Obj *p;
		p = lookup(yytext, 1);
		if (p->type == DEFNAME) {
			c = input();
			unput(c);
			if (c == '(')	/* it's name(...) */
				dodef(p);
			else	/* no argument list */
				pbstr(p->val);
		} else {
			yylval.op = p;
			return p->type;	/* NAME or VARNAME */
		}
	}
	YY_BREAK
case 78:
# line 169 "grapl.l"
return(EQ);
	YY_BREAK
case 79:
# line 170 "grapl.l"
return(GE);
	YY_BREAK
case 80:
# line 171 "grapl.l"
return(LE);
	YY_BREAK
case 81:
# line 172 "grapl.l"
return(NE);
	YY_BREAK
case 82:
# line 173 "grapl.l"
return(GT);
	YY_BREAK
case 83:
# line 174 "grapl.l"
return(LT);
	YY_BREAK
case 84:
# line 175 "grapl.l"
return(AND);
	YY_BREAK
case 85:
# line 176 "grapl.l"
return(OR);
	YY_BREAK
case 86:
# line 177 "grapl.l"
return(NOT);	
	YY_BREAK
case 87:
# line 179 "grapl.l"
{ BEGIN str; clen = 0; }
	YY_BREAK
case 88:
# line 181 "grapl.l"
;
	YY_BREAK
case 89:
# line 183 "grapl.l"
{ yylval.i = yytext[0]; return(yytext[0]); }
	YY_BREAK
case 90:
# line 185 "grapl.l"
{ BEGIN A; cbuf[clen] = 0;
		  yylval.p = tostring(cbuf); return(STRING); }
	YY_BREAK
case 91:
# line 187 "grapl.l"
{ yyerror("newline in string"); BEGIN A; return(ST); }
	YY_BREAK
case 92:
# line 188 "grapl.l"
{ cbuf[clen++] = '\\'; cbuf[clen++] = '"'; }
	YY_BREAK
case 93:
# line 189 "grapl.l"
{ cbuf[clen++] = '\\'; cbuf[clen++] = '\\'; }
	YY_BREAK
case 94:
# line 190 "grapl.l"
{ CADD; }
	YY_BREAK
case 95:
# line 192 "grapl.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(A):
case YY_STATE_EOF(str):
case YY_STATE_EOF(def):
case YY_STATE_EOF(thru):
case YY_STATE_EOF(sh):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    register YY_CHAR *yy_bp = yytext;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
	++yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 299 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 299 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 298);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 192 "grapl.l"

