h12894
s 00030/00000/00000
d D 5.1 88/10/20 18:35:41 bostic 1 0
c from UUNET; applied patches 1-3
e
u
U
t
T
I 1
C
C FLAGS
C
	LOGICAL TROLLF,CAGESF,BUCKTF,CAROFF,CAROZF,LWTIDF
	LOGICAL DOMEF,GLACRF,ECHOF,RIDDLF,LLDF,CYCLOF
	LOGICAL MAGICF,LITLDF,SAFEF,GNOMEF,GNODRF,MIRRMF
	LOGICAL EGYPTF,ONPOLF,BLABF,BRIEFF,SUPERF,BUOYF
	LOGICAL GRUNLF,GATEF,RAINBF,CAGETF,EMPTHF,DEFLAF
	LOGICAL GLACMF,FROBZF,ENDGMF,BADLKF,THFENF,SINGSF
	LOGICAL MRPSHF,MROPNF,WDOPNF,MR1F,MR2F,INQSTF
	LOGICAL FOLLWF,SPELLF,CPOUTF,CPUSHF
	COMMON /FINDEX/ TROLLF,CAGESF,BUCKTF,CAROFF,CAROZF,LWTIDF,
&		DOMEF,GLACRF,ECHOF,RIDDLF,LLDF,CYCLOF,
&		MAGICF,LITLDF,SAFEF,GNOMEF,GNODRF,MIRRMF,
&		EGYPTF,ONPOLF,BLABF,BRIEFF,SUPERF,BUOYF,
&		GRUNLF,GATEF,RAINBF,CAGETF,EMPTHF,DEFLAF,
&		GLACMF,FROBZF,ENDGMF,BADLKF,THFENF,SINGSF,
&		MRPSHF,MROPNF,WDOPNF,MR1F,MR2F,INQSTF,
&		FOLLWF,SPELLF,CPOUTF,CPUSHF
	COMMON /FINDEX/ BTIEF,BINFF
	COMMON /FINDEX/ RVMNT,RVCLR,RVCYC,RVSND,RVGUA
	COMMON /FINDEX/ ORRUG,ORCAND,ORMTCH,ORLAMP
	COMMON /FINDEX/ MDIR,MLOC,POLEUF
	COMMON /FINDEX/ QUESNO,NQATT,CORRCT
	COMMON /FINDEX/ LCELL,PNUMB,ACELL,DCELL,CPHERE

	LOGICAL FLAGS(46)
	EQUIVALENCE (FLAGS(1),TROLLF)
	INTEGER SWITCH(22)
	EQUIVALENCE (SWITCH(1), BTIEF)
E 1
