h49027
s 00002/00002/00057
d D 8.1 93/06/04 18:46:32 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00013/00013/00046
d D 6.8 91/05/09 16:27:33 cael 10 9
c mdoc version three
e
s 00002/00000/00057
d D 6.7 91/03/14 00:10:59 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00057
d R 6.7 91/03/13 20:30:04 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00043/00023/00014
d D 6.6 90/07/24 22:51:38 cael 7 6
c .Xr botch fix
e
s 00004/00014/00033
d D 6.5 90/06/24 19:15:43 cael 6 5
c converted man page
e
s 00014/00003/00033
d D 6.4 88/10/25 15:13:25 bostic 5 4
c add Berkeley copyright
e
s 00001/00003/00035
d D 6.3 87/07/26 14:37:11 bostic 4 3
c didn't mention bugfiler(8)
e
s 00007/00006/00031
d D 6.2 86/05/05 21:37:19 bloom 3 2
c add description of EDITOR environment variable
e
s 00001/00001/00036
d D 6.1 85/04/29 21:26:07 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00037/00000/00000
d D 5.1 85/04/29 21:25:48 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 11
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
E 6
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
.\"
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 6
E 5
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
I 9
D 10
.Vx
.Vx
E 10
E 9
D 2
.TH SENDBUG 1 "11 May 1983"
E 2
I 2
D 6
.TH SENDBUG 1 "%Q%"
E 6
I 6
D 7
.TH SENDBUG 1 "%Q"
E 6
E 2
.UC 5
.ad
.SH NAME
sendbug \- mail a system bug report to 4bsd-bugs
.SH SYNOPSIS
.B sendbug [ address ]
.SH DESCRIPTION
.PP
E 7
I 7
.Dd %Q%
.Dt SENDBUG 1
.Os BSD 4.2
.Sh NAME
.Nm sendbug
.Nd mail a system bug report to 4bsd-bugs
.Sh SYNOPSIS
.Nm sendbug
.Op Ar address
.Sh DESCRIPTION
E 7
D 3
Bug reports sent to `4bsd-bugs@BERKELEY' are intercepted
E 3
I 3
Bug reports sent to `4bsd-bugs@Berkeley.EDU' are intercepted
E 3
by a program which expects bug reports to conform to a standard format.
D 7
.I Sendbug
E 7
I 7
.Nm Sendbug
E 7
is a shell script to help the user compose and mail bug reports
in the correct format.
D 7
.I Sendbug
E 7
I 7
.Nm Sendbug
E 7
D 3
works by invoking
.IR vi (1)
E 3
I 3
works by invoking the editor specified by the environment variable
D 7
.I EDITOR
E 7
I 7
.Ev EDITOR
E 7
E 3
on a temporary copy of the bug report format outline. The user must fill in the
D 3
appropriate fields and exit
.IR vi .
E 3
I 3
D 7
appropriate fields and exit the editor.  The default editor is
.IR vi (1).
E 3
.I Sendbug
D 3
then mails the completed report to `4bsd-bugs@BERKELEY' or the address
E 3
I 3
then mails the completed report to `4bsd-bugs@Berkeley.EDU' or the address
E 7
I 7
appropriate fields and exit the editor.
.Nm Sendbug
then mails the completed report to `4bsd-bugs@Berkeley.EDU' or the
.Ar address
E 7
E 3
specified on the command line.
D 7
.SH FILES
.nf
.ta \w'/usr/ucb/bugformat       'u
/usr/ucb/bugformat	contains the bug report outline
.fi
.SH "SEE ALSO"
D 4
vi(1),
I 3
environ(7),
E 3
sendmail(8)
E 4
I 4
vi(1), environ(7), bugfiler(8), sendmail(8)
E 7
I 7
.Sh ENVIRONMENT
.Nm Sendbug
will utilize the following environment variable if it exists:
D 10
.Tw Fl
.Tp Ev EDITOR
E 10
I 10
.Bl -tag -width EDITOR
.It Ev EDITOR
E 10
Specifies the preferred editor. If
.Ev EDITOR
is not set,
.Nm
defaults to
.Xr vi 1 .
D 10
.Tp
E 10
I 10
.El
E 10
.Sh FILES
D 10
.Dw /usr/share/misc/bugformat
.Di L
.Dp Pa /usr/share/misc/bugformat
contains the bug report outline
.Dp
E 10
I 10
.Bl -tag -width /usr/share/misc/bugformat -compact
.It Pa /usr/share/misc/bugformat
Contains the bug report outline.
.El
E 10
.Sh SEE ALSO
.Xr vi 1 ,
.Xr environ 7 ,
.Xr bugfiler 8 ,
.Xr sendmail 8
.Sh HISTORY
D 10
.Nm Sendbug
appeared in 4.2 BSD.
E 10
I 10
The
.Nm sendbug
command
appeared in
.Bx 4.2 .
E 10
E 7
E 4
E 1
