h26235
s 00017/00005/00088
d D 8.2 94/03/27 09:04:41 bostic 6 5
c Jan-Simon Pendry's and my new mount code
e
s 00002/00002/00091
d D 8.1 93/06/09 19:08:36 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00004/00091
d D 5.3 93/06/09 19:08:33 bostic 4 2
c fixed the under development line
e
s 00002/00002/00093
d R 8.1 93/06/05 11:02:16 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00043/00021/00052
d D 5.2 92/07/19 08:50:22 pendry 2 1
c updated
e
s 00073/00000/00000
d D 5.1 92/07/18 16:13:26 pendry 1 0
c date and time created 92/07/18 16:13:26 by pendry
e
u
U
t
T
I 1
.\"
D 5
.\" Copyright (c) 1992 The Regents of the University of California
.\" Copyright (c) 1990, 1992 Jan-Simon Pendry
E 5
I 5
D 6
.\" Copyright (c) 1992, 1993
E 6
I 6
.\" Copyright (c) 1992, 1993, 1994
E 6
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\" All rights reserved.
.\"
.\" This code is derived from software donated to Berkeley by
.\" Jan-Simon Pendry.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	%W% (Berkeley) %G%
.\"
.\"
.Dd %Q%
.Dt MOUNT_KERNFS 8
.Os BSD 4.4
.Sh NAME
.Nm mount_kernfs
.Nd mount the /kern file system
.Sh SYNOPSIS
.Nm mount_kernfs
D 6
.Op Fl F Ar fsoptions
.Pa /kern
.Pa mount_point
E 6
I 6
.Op Fl o Ar options
.Ar /kern
.Ar mount_point
E 6
.Sh DESCRIPTION
The
.Nm mount_kern
command attaches an instance of the kernel parameter
namespace to the global filesystem namespace.
The conventional mount point is
.Pa /kern .
This command is normally executed by
.Xr mount 8
at boot time.
.Pp
I 2
The filesystem includes several regular files which can be read,
some of which can also be written.
The contents of the files is in a machine-independent format,
either a string, or an integer in decimal ASCII.
Where numbers are returned, a trailing newline character is also added.
I 6
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
.El
E 6
E 2
.Sh FILES
D 2
.Bl -tag -width copyright\ \- -compact
.It Pa copyright \-
E 2
I 2
.Bl -tag -width copyright -compact
.It Pa boottime
the time at which the system was last booted (decimal ASCII).
.It Pa copyright
E 2
kernel copyright message.
D 2
.It Pa hostname \-
the hostname.  The hostname can be changed by writing to this file.
.It Pa hz \-
the frequency of the system clock.
.It Pa loadavg \-
four integers in decimal ASCII representing the 1, 5 and 15 minute
load average in kern fix point format.  The final integer is the fix-point
scaling factor.
.It Pa pagesize \-
the machine pagesize, in decimal ASCII.
.It Pa physmem \-
the number of pages of physical memory in the machine, in decimal ASCII.
.It Pa root \-
the root directory.
.It Pa rootdev \-
E 2
I 2
.It Pa hostname
the hostname, with a trailing newline.
The hostname can be changed by writing to this file.
A trailing newline will be stripped from the hostname being written.
.It Pa hz
the frequency of the system clock (decimal ASCII).
.It Pa loadavg
the 1, 5 and 15 minute load average in kernel fixed-point format.
The final integer is the fix-point scaling factor.
All numbers are in decimal ASCII.
.It Pa pagesize
the machine pagesize (decimal ASCII).
.It Pa physmem
the number of pages of physical memory in the machine (decimal ASCII).
.It Pa root
the system root directory.
In a chroot'ed environment,
.Nm
can be used to create a new
.Pa /kern
mount point.
.Pa /kern/root
will then refer to the system global root, not the current process root.
.It Pa rootdev
E 2
the root device.
D 2
.It Pa time \-
two integers in decimal ASCII representing the second and microsecond
value of the system clock.
.It Pa version \-
E 2
I 2
.It Pa rrootdev
the raw root device.
.It Pa time
the second and microsecond value of the system clock.
Both numbers are in decimal ASCII.
.It Pa version
E 2
the kernel version string.
I 2
The head line for
.Pa /etc/motd
can be generated by running:
.Dq Ic "sed 1q /kern/version"
E 2
.El
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
D 6
.Xr fstab 5
E 6
I 6
.Xr fstab 5 ,
.Xr mount 8
E 6
.Sh CAVEATS
This filesystem may not be NFS-exported.
.Sh HISTORY
The
D 4
.Nm
filesystem
is
.Ud
E 4
I 4
.Nm mount_kernfs
utility first appeared in 4.4BSD.
E 4
E 1
