h39100
s 00002/00002/00051
d D 8.1 93/06/09 19:23:34 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00003/00051
d D 5.4 93/06/09 19:23:31 bostic 5 3
c fixed the under development line
e
s 00002/00002/00052
d R 8.1 93/06/06 13:52:02 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00044/00024/00010
d D 5.3 91/03/16 18:11:54 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00033
d D 5.2 90/06/24 22:12:08 trent 2 1
c new copyright notice
e
s 00044/00000/00000
d D 5.1 88/12/05 15:42:25 bostic 1 0
c date and time created 88/12/05 15:42:25 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1988 The Regents of the University of California.
E 3
I 3
D 6
.\" Copyright (c) 1988, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 2
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 2
I 2
.\" %sccs.include.redist.man%
E 2
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH CHROOT 8 "%Q%"
.UC 6
.SH NAME
chroot \- change root directory
.SH SYNOPSIS
.B chroot newroot [ command ]
.SH DESCRIPTION
E 3
I 3
.Dd %Q%
.Dt CHROOT 8
.Os BSD 4.3
.Sh NAME
.Nm chroot
.Nd change root directory
.Sh SYNOPSIS
.Nm chroot
.Ar newroot
.Op Ar command
.Sh DESCRIPTION
E 3
The
D 3
.I chroot
E 3
I 3
.Nm chroot
E 3
command changes its root directory to the supplied directory
D 3
.I newroot
E 3
I 3
.Ar newroot
E 3
and exec's
D 3
.IR command ,
if supplied, or an interactive copy of your shell (as specified
by the environmental variable
.IR SHELL )
if not.
.I /bin/sh
is used if
.I SHELL
is not specified.
.PP
E 3
I 3
.Ar command ,
if supplied, or an interactive copy of your shell.
.Pp
E 3
Note,
D 3
.I command
E 3
I 3
.Ar command
E 3
or the shell are run as your real-user-id.
D 3
.SH "SEE ALSO"
chdir(2), chroot(2), environ(7)
E 3
I 3
.Sh ENVIRONMENT
The following environment variable is referenced by
.Nm chroot :
.Bl -tag -width SHELL
.It Ev SHELL
If set,
the string specified by
.Ev SHELL
is interpreted as the name of
the shell to exec.
If the variable
.Ev SHELL
is not set,
.Pa /bin/sh
is used.
.El
.Sh SEE ALSO
.Xr chdir 2 ,
.Xr chroot 2 ,
.Xr environ 7
.Sh HISTORY
The
D 5
.Nm
command
.Ud
E 5
I 5
.Nm chroot
utility first appeared in 4.4BSD.
E 5
E 3
E 1
