#! /bin/sh
#
#	$Id: archtype,v 1.13 1993/03/25 02:30:42 jch Exp $
#
# %(Copyright.header)
#
#	Try to determine the type of machine we are running on by using 'arch'
#	or 'machine'.  If neither exist, use 'hostname'.
#

if [ ! -z "${GATED_ARCHTYPE}" ]; then
	echo ${GATED_ARCHTYPE} ;
	exit ;
fi

for comm in uname arch machine hostname; do
	if (${comm}) > /dev/null 2>&1; then
		case ${comm} in
		uname)
			mach=`uname -m` ;
			system=`uname -s` ;
			case ${system}"-"${mach} in
			SunOS*)		# We prefer the application arch on Suns
				mach=`uname -m | sed -e 's/[a-z]$//'`
				;;
			AIX-000*)	# AIX on an RS/6000 reports some sort of serial #
				mach="RS6K"
				;;
			esac
			case ${system} in
			HP-UX*)		# Remove leading zeros
				system="${system}-`uname -r | sed -e 's/\.0/./g'`"
				;;
			AIX*)		# IBM has their own way...
				system="${system}-`uname -v`.`uname -r`"
				;;
			4*BSD)
				system=`uname -r`;
				;;
			*)
				system="${system}-`uname -r`"
				;;
			esac
			mach="${system}-${mach}" ;
			;;

		hostname)
			mach=`hostname | sed -e 's/\..*//'` ;
			;;

		*)
			mach=`${comm}` ;
			;;
		esac
		echo ${mach} | sed -e 's%/%.%g' ;
		exit ;
	fi
done

echo "unknown" ;

exit ;

#
# %(Copyright)
#
