h35859
s 00001/00001/00191
d D 8.2 93/12/30 15:39:35 mckusick 11 10
c copyediting for Usenix manuals
e
s 00002/00002/00190
d D 8.1 93/06/18 15:09:09 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00006/00001/00186
d D 6.5 93/06/18 15:09:02 bostic 9 7
c describe "view" command
e
s 00002/00002/00185
d R 8.1 93/06/09 21:49:42 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00018/00018/00169
d D 6.4 92/07/19 17:54:51 cael 7 6
c missed two tag labels leftover from version one macros
e
s 00162/00060/00025
d D 6.3 91/04/23 21:52:38 cael 6 4
c mdoc version three/bsd copyright
e
s 00161/00059/00026
d R 6.3 91/04/23 21:46:43 cael 5 4
c mdoc version three (note no copyright change - still `shared')
e
s 00004/00003/00081
d D 6.2 91/04/17 17:39:31 bostic 4 3
c new copyright; att/bsd/shared
e
s 00001/00001/00083
d D 6.1 85/04/29 15:08:57 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00083
d D 5.1 85/04/29 15:08:49 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00084/00000/00000
d D 4.1 85/04/29 15:08:41 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1980 The Regents of the University of California.
E 6
I 6
D 10
.\" Copyright (c) 1980, 1991 Regents of the University of California.
E 6
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 6
.\" %sccs.include.proprietary.roff%
E 6
I 6
.\" %sccs.include.redist.roff%
E 6
E 4
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH VI 1 12/2/79
E 2
I 2
D 3
.TH VI 1 "2 December 1979"
E 3
I 3
D 6
.TH VI 1 "%Q%"
E 3
E 2
.UC
.SH NAME
vi \- screen oriented (visual) display editor based on ex
.SH SYNOPSIS
.B vi
[
.B \-t
tag
] [
.B \-r
] [
\fB+\fR\fIcommand\fR
] [
.B \-l
] [
\fB\-w\fIn\fR
]
name ...
.SH DESCRIPTION
.I Vi
E 6
I 6
.Dd %Q%
.Dt VI 1
.Os BSD 3
.Sh NAME
D 7
.Nm vi
E 7
I 7
D 9
.Nm \&vi
E 9
I 9
.Nm \&vi , view
E 9
E 7
.Nd screen oriented (visual) display editor based on ex
.Sh SYNOPSIS
D 7
.Nm vi
E 7
I 7
.Nm \&vi
E 7
.Op Fl R
.Op Fl l
.Op Fl r
.Op Fl t Ar tag
.Op Fl w Ar n
.Op Cm \&+ Ns Ar command
.Ar name ...
.Sh DESCRIPTION
D 7
.Nm Vi
E 7
I 7
.Nm \&Vi
E 7
E 6
(visual) is a display oriented text editor based on
D 6
.IR ex (1).
.I Ex
E 6
I 6
D 7
.Xr ex 1 .
E 7
I 7
.Xr \&ex 1 .
E 7
.Xr \&Ex
E 6
and
D 6
.I vi
E 6
I 6
D 7
.Nm vi
E 7
I 7
.Nm \&vi
E 7
E 6
run the same code; it is possible to get to
the command mode of
D 6
.I ex
E 6
I 6
D 7
.Xr ex
E 7
I 7
.Xr \&ex
E 7
E 6
from within
D 6
.I vi
E 6
I 6
D 7
.Nm vi
E 7
I 7
.Nm \&vi
E 7
E 6
and vice-versa.
I 9
.Pp
.Nm View
is the same as
.Dq "vi -R" ,
e.g. run in read-only mode.
E 9
D 6
.PP
E 6
I 6
.Pp
Available options:
.Bl -tag -width xcommandx
.It Fl R
Read only. Changes to the file may not be written out.
.It Fl l
Sets options for editing
.Tn LISP
source (options
.Ic showmatch
and
.Ic lisp ) .
.It Fl r
In the event of an editor or system crash, the
.Fl r
option will retrieve the last saved version of the
specified file, or if no file is specified,
a list of saved files is printed.
.It Fl t Ar tag
If tags are used (see
.Xr ctags 1 )
D 11
the editor is postioned at
E 11
I 11
the editor is positioned at
E 11
.Ar tag .
.It Fl w Ns Ar n
The default window size is set to
.Ar n .
.It Cm \&+ Ns Ar command
Enter the file with
.Ar command.
Useful for
positioning on a string or line number.
.El
.Pp
E 6
The
D 6
.I "Vi Quick Reference"
E 6
I 6
.%T "Vi Quick Reference"
E 6
card and the
D 6
.I "Introduction to Display Editing with Vi"
E 6
I 6
.%T "Introduction to Display Editing with Vi"
E 6
provide full details on using
D 6
.I vi.
.SH FILES
See
.IR ex (1).
.SH SEE ALSO
ex (1), edit (1), ``Vi Quick Reference'' card,
``An Introduction to Display Editing with Vi''.
.SH AUTHOR
William Joy
.br
Mark Horton added macros to \fIvisual\fR mode and is maintaining version 3
.SH BUGS
Software tabs using \fB^T\fR work only immediately after the
.I autoindent.
.PP
E 6
I 6
D 7
.Nm vi .
E 7
I 7
.Nm \&vi .
E 7
.Sh ENVIRONMENT
The
.Nm
command uses the following environment variables.
.Bl -tag -width Fl
.It Ev EXINIT
User specified startup values for
D 7
.Xr ex
E 7
I 7
.Xr \&ex
E 7
and
D 7
.Nm vi .
E 7
I 7
.Nm \&vi .
E 7
Usually specified in the file
.Pa ~/.exrc
.It Ev HOME
Default directory to search for
the file
.Pa ~/.exrc
.It Ev SHELL
Shell used for
.Em escaped
commands (with the
D 7
.Xr ex
E 7
I 7
.Xr \&ex
E 7
.Ic \&:!
command).
.It Ev TERM
Terminal type used to lookup terminal capabilities from the
file
.Pa /usr/share/misc/termcap .
.It Ev TERMCAP
If set, specifies an alternate termcap file.
.El
.Sh FILES
.Bl -tag -width /usr/libexec/ex?.?preserve -compact
.It Pa  /usr/libexec/ex?.?strings
error messages
.It Pa  /usr/libexec/ex?.?recover
recover command
.It Pa  /usr/libexec/ex?.?preserve
preserve command
.It Pa  /usr/share/misc/termcap
describes capabilities of terminals
.It Pa  ~/.exrc
editor startup file
D 7
.Dc Pa /tmp/Ex Ns Em nnnnn
E 7
I 7
.It Pa /tmp/Ex Ns Em nnnnn
E 7
editor temporary
D 7
.Dc Pa /tmp/Rx Ns Em nnnnn
E 7
I 7
.It Pa /tmp/Rx Ns Em nnnnn
E 7
named buffer temporary
.It Pa /var/preserve
preservation directory
.El
.Sh SEE ALSO
.Xr awk 1 ,
D 7
.Xr ed 1 ,
E 7
I 7
.Xr \&ed 1 ,
E 7
.Xr grep 1 ,
.Xr sed 1 ,
.Xr grep 1 ,
D 7
.Xr vi 1 ,
E 7
I 7
.Xr \&vi 1 ,
E 7
.Xr termcap 5 ,
.Xr environ 7
.Rs
.%T "Vi Quick Reference Card"
.Re
.Rs
.%T "An Introduction to Display Editing with Vi"
.Re
.Sh BUGS
Software tabs using
.Sy \&^T
work only immediately after the
.Ic autoindent .
.Pp
E 6
Left and right shifts on intelligent terminals don't make use of
insert and delete character operations in the terminal.
D 6
.PP
E 6
I 6
.Pp
E 6
The
D 6
.I wrapmargin
E 6
I 6
.Ic wrapmargin
E 6
option can be fooled since it looks at output columns when blanks are typed.
If a long word passes through the margin and onto the next line without a 
break, then the line won't be broken.
D 6
.PP
E 6
I 6
.Pp
E 6
Insert/delete within a line can be slow if tabs are present on intelligent
terminals, since the terminals need help in doing this correctly.
D 6
.PP
E 6
I 6
.Pp
E 6
Saving text on deletes in the named buffers is somewhat inefficient.
D 6
.PP
E 6
I 6
.Pp
E 6
The
D 6
.I source
command does not work when executed as \fB:source\fR;
there is no way to use the \fB:append\fR, \fB:change\fR,
and \fB:insert\fR commands, since it is not possible to give
more than one line of input to a \fB:\fR escape.  To use these
on a \fB:global\fR you must \fBQ\fR to \fIex\fR command mode,
E 6
I 6
.Ic source
command does not work when executed as
.Ic :source ;
there is no way to use the
.Ic :append ,
.Ic :change ,
and
.Ic :insert
commands, since it is not possible to give
more than one line of input to a
.Ic \&:
escape.  To use these
on a
.Ic :global
you must
.Ic Q
to
D 7
.Xr ex
E 7
I 7
.Xr \&ex
E 7
command mode,
E 6
execute them, and then reenter the screen editor with
D 6
.I vi
E 6
I 6
D 7
.Nm vi
E 7
I 7
.Nm \&vi
E 7
E 6
or
D 6
.I open.
E 6
I 6
.Ic open .
.Sh HISTORY
The
D 7
.Nm
E 7
I 7
.Nm \&vi
E 7
command appeared in
.Bx 3.0 .
E 6
E 1
