DIR = /usr/lib/font/devsun/

FILES = $(DIR)B.10 $(DIR)B.14 $(DIR)B.24 $(DIR)B.7 $(DIR)CW.10 $(DIR)CW.14 \
	$(DIR)CW.7 $(DIR)I.10 $(DIR)I.14 $(DIR)I.24 $(DIR)I.7 $(DIR)R.10 \
	$(DIR)R.14 $(DIR)R.24 $(DIR)R.7 $(DIR)S.10 $(DIR)S.14 $(DIR)S.24 \
	$(DIR)S.7 $(DIR)cb.10 $(DIR)ci.10 $(DIR)cr.10 $(DIR)tb.10 $(DIR)ti.10 \
	$(DIR)tr.10 $(DIR)ts.10 $(DIR)dr.12 $(DIR)di.12 $(DIR)db.12 $(DIR)sl.10

all: $(FILES)

$(DIR)R.7:	R.7
	ch2vft R.7 > $(DIR)R.7
$(DIR)R.10:	R.10
	ch2vft R.10 > $(DIR)R.10
$(DIR)R.14:	R.14
	ch2vft R.14 > $(DIR)R.14
$(DIR)R.24:	R.24
	ch2vft R.24 > $(DIR)R.24
$(DIR)I.7:	I.7
	ch2vft I.7 > $(DIR)I.7
$(DIR)I.10:	I.10
	ch2vft I.10 > $(DIR)I.10
$(DIR)I.14:	I.14
	ch2vft I.14 > $(DIR)I.14
$(DIR)I.24:	I.24
	ch2vft I.24 > $(DIR)I.24
$(DIR)B.7:	B.7
	ch2vft B.7 > $(DIR)B.7
$(DIR)B.10:	B.10
	ch2vft B.10 > $(DIR)B.10
$(DIR)B.14:	B.14
	ch2vft B.14 > $(DIR)B.14
$(DIR)B.24:	B.24
	ch2vft B.24 > $(DIR)B.24
$(DIR)S.7:	S.7
	ch2vft S.7 > $(DIR)S.7
$(DIR)S.10:	S.10
	ch2vft S.10 > $(DIR)S.10
$(DIR)S.14:	S.14
	ch2vft S.14 > $(DIR)S.14
$(DIR)S.24:	S.24
	ch2vft S.24 > $(DIR)S.24
$(DIR)CW.7:	CW.7
	ch2vft CW.7 > $(DIR)CW.7
$(DIR)CW.10:	CW.10
	ch2vft CW.10 > $(DIR)CW.10
$(DIR)CW.14:	CW.14
	ch2vft CW.14 > $(DIR)CW.14
$(DIR)CW.24:	CW.24
	ch2vft CW.24 > $(DIR)CW.24
$(DIR)tr.10:	tr.10
	ch2vft tr.10 > $(DIR)tr.10
$(DIR)ti.10:	ti.10
	ch2vft ti.10 > $(DIR)ti.10
$(DIR)tb.10:	tb.10
	ch2vft tb.10 > $(DIR)tb.10
$(DIR)ts.10:	ts.10
	ch2vft ts.10 > $(DIR)ts.10
$(DIR)cr.10:	cr.10
	ch2vft cr.10 > $(DIR)cr.10
$(DIR)ci.10:	ci.10
	ch2vft ci.10 > $(DIR)ci.10
$(DIR)cb.10:	cb.10
	ch2vft cb.10 > $(DIR)cb.10
$(DIR)dr.12:	dr.12
	ch2vft dr.12 > $(DIR)dr.12
$(DIR)di.12:	di.12
	ch2vft di.12 > $(DIR)di.12
$(DIR)db.12:	db.12
	ch2vft db.12 > $(DIR)db.12
$(DIR)sl.10:	sl.10
	ch2vft sl.10 > $(DIR)sl.10
