h43366
s 00002/00002/00032
d D 8.2 94/04/18 07:22:36 bostic 12 11
c typo
e
s 00002/00002/00032
d D 8.1 93/06/06 16:20:47 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00006/00006/00028
d D 6.7 92/03/02 14:25:18 bostic 10 9
c minor rewording, no fixes
e
s 00007/00007/00027
d D 6.6 91/07/01 15:19:52 cael 9 8
c fixed .Os
e
s 00000/00000/00034
d D 6.5 91/06/02 20:56:19 cael 8 7
c mdoc version three
e
s 00002/00000/00032
d D 6.4 91/03/14 00:16:04 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00032
d R 6.4 91/03/13 20:32:33 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00029/00019/00003
d D 6.3 90/07/24 22:51:50 cael 5 4
c .Xr botch fix
e
s 00006/00002/00016
d D 6.2 90/06/24 19:16:08 cael 4 3
c converted man page
e
s 00001/00001/00017
d D 6.1 85/04/29 17:56:04 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00006/00015
d D 5.1 85/04/29 17:55:53 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00021/00000/00000
d D 4.1 85/04/29 17:55:41 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 11
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 11
I 11
D 12
.\" Copyright (c) 1990, 1993
E 12
I 12
.\" Copyright (c) 1990, 1993, 1994
E 12
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 5
E 4
.\"
I 5
.\" %sccs.include.redist.man%
.\"
E 5
D 2
.TH SIZE 1 VAX-11
E 2
I 2
D 3
.TH SIZE 1 "18 January 1983"
E 3
I 3
D 4
.TH SIZE 1 "%Q%"
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
I 7
D 9
.Vx
.Vx
E 9
E 7
D 5
.TH SIZE 1 "%Q"
E 4
E 3
E 2
.AT 3
.SH NAME
size \- size of an object file
.SH SYNOPSIS
.B size
[ object ... ]
.SH DESCRIPTION
.I Size
D 2
prints the (decimal) number of bytes
required by the
text, data, and bss
portions, and their sum in hex and decimal,
of each object-file argument.
E 2
I 2
prints the (decimal) number of bytes required by the text, data, and
bss portions, and their sum in hex and decimal, of each object-file argument.
E 2
If no file is specified,
.B a.out
is used.
.SH "SEE ALSO"
a.out(5)
E 5
I 5
.Dd %Q%
.Dt SIZE 1
D 9
.Os ATT 7th
E 9
I 9
.Os
E 9
.Sh NAME
.Nm size
.Nd display object file segment sizes (text, data and bss)
.Sh SYNOPSIS
.Nm size
.Op Ar object_file ...
.Sh DESCRIPTION
.Nm Size
D 10
displays the text, data and bss segment sizes of the given
E 10
I 10
displays the text, data and bss segment sizes of the specified
E 10
.Ar object_file
D 10
in bytes (decimal), and the sum of the three segments (hexidecimal and 
D 9
decimal). If
E 9
I 9
decimal).
If
E 10
I 10
in bytes (in decimal), and the sum of the three segments (in
D 12
decimal and hexidecimal).
E 12
I 12
decimal and hexadecimal).
E 12
If no
E 10
E 9
.Ar object_file
D 10
is not given,
E 10
I 10
is specified
E 10
.Nm
D 9
will search for the file
E 9
I 9
D 10
automatically searches for the file
E 10
I 10
attempts to report on the file
E 10
E 9
.Pa a.out .
.Sh SEE ALSO
.Xr a.out 5
.Sh HISTORY
D 9
.Nm Size
appeared in Version 6 AT&T Unix.
E 9
I 9
A
.Nm size
command appeared in Version 6 AT&T Unix.
E 9
E 5
E 1
