h35805
s 00001/00001/00063
d D 8.2 94/04/01 06:10:34 bostic 8 7
c misspelling
e
s 00002/00002/00062
d D 8.1 93/06/05 11:21:45 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00051/00035/00013
d D 6.4 91/03/16 17:09:01 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00004/00014/00044
d D 6.3 90/06/24 21:56:19 trent 5 4
c new copyright & pathnames (slattach)
e
s 00018/00002/00040
d D 6.2 88/09/19 22:03:49 bostic 4 3
c Berkeley specific copyright
e
s 00000/00000/00042
d D 6.1 86/02/17 17:01:59 karels 3 2
c rev 6
e
s 00007/00010/00035
d D 1.2 86/02/17 17:01:37 karels 2 1
c rm address setting, let ifconfig deal with it
e
s 00045/00000/00000
d D 1.1 86/02/17 16:49:37 karels 1 0
c from Torek
e
u
U
t
T
I 4
D 6
.\" Copyright (c) 1986 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1986, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1986, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
I 1
D 2
.TH SLATTACH 8C "20 September 1984"
E 2
I 2
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
D 4
.TH SLATTACH 8C "%Q%"
E 4
I 4
.\"
D 6
.TH SLATTACH 8 "%Q%"
E 4
E 2
.UC 6
.SH NAME
slattach \- attach serial lines as network interfaces
.SH SYOPNSIS
D 5
.B /etc/slattach
E 5
I 5
.B slattach
E 5
D 2
ttyname source destination [
E 2
I 2
ttyname [
E 2
.I baudrate
]
.SH DESCRIPTION
.I Slattach
E 6
I 6
.Dd %Q%
.Dt SLATTACH 8
.Os BSD 4.3
.Sh NAME
.Nm slattach
.Nd attach serial lines as network interfaces
D 8
.Sh SYOPNSIS
E 8
I 8
.Sh SYNOPSIS
E 8
.Nm Slattach
.Ar ttyname Op Ar baudrate
.Sh DESCRIPTION
.Nm Slattach
E 6
is used to assign a tty line to a network interface,
D 6
and to define the network source and destination addresses. The
.I ttyname
D 2
parameter is a string of the form ``ttyXX'', or ``/dev/ttyXX'', while
the source and destination are either host names present
in the host name data base,
.IR hosts (5),
or DARPA Internet addresses expressed in the Internet standard
``dot notation''.  The optional
E 2
I 2
parameter is a string of the form ``ttyXX'', or ``/dev/ttyXX''.
The optional
E 2
.I baudrate
parameter is used to set the speed of the connection. If not specified, the
E 6
I 6
and to define the network source and destination addresses.
The following operands are supported by
.Nm slattach :
.Bl -tag -width Ar
.It Ar ttyname
Specifies the name of the tty device.
.Ar Ttyname
should be a string of the form
.Ql ttyXX ,
or
.Ql /dev/ttyXX .
.It Ar baudrate
Specifies the speed of the connection. If not specified, the
E 6
default of 9600 is used.
D 6
.PP
E 6
I 6
.El
.Pp
E 6
Only the super-user may attach a network interface.
D 6
.PP
To detach the interface, use `ifconfig
.I interface-name
down' after killing off the
.I slattach
E 6
I 6
.Pp
To detach the interface, use
.Dq Li ifconfig interface-name down
after killing off the
.Nm slattach
E 6
process.
D 6
.I interface-name
E 6
I 6
.Ar Interface-name
E 6
is the name that is shown by
D 6
.B netstat(1)
.SH EXAMPLES
.ta 8
D 2
	/etc/slattach ttyh8 seismo osg3
E 2
I 2
D 5
	/etc/slattach ttyh8
E 5
I 5
	slattach ttyh8
E 5
E 2
.br
D 2
	/etc/slattach /dev/tty01 hugo dahl 4800
E 2
I 2
D 5
	/etc/slattach /dev/tty01 4800
E 5
I 5
	slattach /dev/tty01 4800
E 5
E 2
.SH DIAGNOSTICS
E 6
I 6
.Xr netstat 1
.Sh EXAMPLES
.Bd -literal -offset indent -compact
slattach ttyh8
slattach /dev/tty01 4800
.Ed
.Sh DIAGNOSTICS
E 6
Messages indicating the specified interface does not exit, the
requested address is unknown, the user is not privileged and
tried to alter an interface's configuration.
D 6
.SH "SEE ALSO"
D 4
rc(8), intro(4N), netstat(1), ifconfig(8C)
E 4
I 4
netstat(1), netintro(4), ifconfig(8), rc(8)
E 6
I 6
.Sh SEE ALSO
.Xr netstat 1 ,
.Xr netintro 4 ,
.Xr ifconfig 8 ,
.Xr rc 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.3 .
E 6
E 4
E 1
