h57531
s 00002/00002/00050
d D 8.1 93/06/04 16:22:14 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00049/00033/00003
d D 6.4 91/04/19 14:30:53 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00003/00001/00033
d D 6.3 89/05/17 21:53:20 bostic 5 4
c move to compatibility library
e
s 00001/00001/00033
d D 6.2 86/05/27 10:34:24 kjd 4 3
c fix english
e
s 00001/00001/00033
d D 6.1 85/05/15 15:31:58 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00005/00001/00029
d D 5.1 85/05/15 15:31:29 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00030/00000/00000
d D 4.1 85/05/15 15:30:37 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
D 7
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 6
.\"
D 2
.TH GETPW 3  deprecated
E 2
I 2
D 3
.TH GETPW 3C  "19 January 1983"
E 3
I 3
D 5
.TH GETPW 3C  "%Q%"
E 5
I 5
D 6
.TH GETPW 3  "%Q%"
E 5
E 3
E 2
.AT 3
.SH NAME
getpw \- get name from uid
.SH SYNOPSIS
.nf
.B getpw(uid, buf)
.B char *buf;
.fi
.SH DESCRIPTION
I 2
.ft B
D 4
Getpw is obsoleted by getpwuid(3).
E 4
I 4
Getpw is made obsolete by getpwuid(3).
E 6
I 6
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt GETPW 3
.Os
.Sh NAME
.Nm getpw
.Nd get name from uid
.Sh SYNOPSIS
.Fn getpw uid "char *buf"
.Sh DESCRIPTION
.Bf -symbolic
The getpw function is made obsolete by getpwuid(3).
E 6
I 5
.br
It is available from the compatibility library, libcompat.
E 5
E 4
D 6
.ft R
.PP
E 2
.I Getpw
searches the password file for
the (numerical)
.IR uid ", and fills in " "buf"
with the corresponding line;
it returns non-zero if
.IR uid ""
could not
be found.
The line is null-terminated.
.SH FILES
/etc/passwd
.SH "SEE ALSO"
getpwent(3),
passwd(5)
.SH DIAGNOSTICS
Non-zero
return on error.
E 6
I 6
.Ef
.Pp
The
.Fn getpw
function reads the file
.Pa /etc/passwd ,
and if it finds
the specified
.Fa uid ,
copies the password entry line into the string pointed to by
.Fa buf .
the null terminated entry line from the password database,
and appends the
.Dv NUL
character.
.Sh RETURN VALUES
The
.Fn getpw
function returns the zero if successful, otherwise 
a non-zero if the entry does not exist.
.Sh FILES
.Bl -tag -width /etc/passwd - compact
.It Pa /etc/passwd
.El
.Sh SEE ALSO
.Xr getpwent 3 ,
.Xr passwd 5
.Sh HISTORY
A
.Fn getpw
function appeared in
.At v6 .
E 6
E 1
