h20780
s 00002/00002/00129
d D 8.1 93/06/05 11:10:12 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00088/00080/00043
d D 6.7 91/03/16 17:08:06 cael 8 7
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00122
d D 6.6 90/06/24 21:48:20 trent 7 6
c new copyright notice
e
s 00070/00037/00063
d D 6.5 90/05/06 14:35:07 mckusick 6 5
c update for new quota system
e
s 00010/00005/00090
d D 6.4 88/07/09 11:32:04 bostic 5 4
c install approved copyright notice
e
s 00008/00002/00087
d D 6.3 88/05/20 12:23:50 bostic 4 3
c add Berkeley specific header
e
s 00012/00001/00077
d D 6.2 85/09/15 16:29:50 serge 3 2
c added -p flag (from ulysses!amw)
e
s 00001/00001/00077
d D 6.1 85/04/27 15:38:22 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00078/00000/00000
d D 5.1 85/04/27 15:38:05 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1983 Regents of the University of California.
E 6
I 6
D 8
.\" Copyright (c) 1983, 1990 Regents of the University of California.
E 8
I 8
D 9
.\" Copyright (c) 1983, 1990, 1991 Regents of the University of California.
E 8
E 6
D 4
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1983, 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
I 6
.\" This code is derived from software contributed to Berkeley by
.\" Robert Elz at The University of Melbourne.
.\"
E 6
D 7
.\" Redistribution and use in source and binary forms are permitted
D 5
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
E 5
I 5
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
E 5
E 4
.\"
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 2
.TH QUOTACHECK 8  "18 July 1983"
E 2
I 2
D 8
.TH QUOTACHECK 8 "%Q%"
E 2
.UC 5
.SH NAME
D 6
quotacheck \- file system quota consistency checker
E 6
I 6
quotacheck \- filesystem quota consistency checker
E 6
.SH SYNOPSIS
D 6
.B /etc/quotacheck
E 6
I 6
.B quotacheck
E 6
[
D 6
.B \-v
E 6
I 6
.B \-g
E 6
I 3
] [
D 6
.B \-p
E 6
I 6
.B \-u
] [
.B \-v
E 6
E 3
]
D 6
filesystem...
E 6
I 6
filesystem ...
E 6
.br
D 6
.B /etc/quotacheck
E 6
I 6
.B quotacheck
E 6
[
D 6
.B \-v
E 6
I 6
.B \-g
E 6
I 3
] [
D 6
.B \-p
E 6
I 6
.B \-u
] [
.B \-v
E 6
E 3
]
.B \-a
I 6
.br
E 6
.SH DESCRIPTION
.I Quotacheck
E 8
I 8
.Dd %Q%
.Dt QUOTACHECK 8
.Os BSD 4.2
.Sh NAME
.Nm quotacheck
.Nd filesystem quota consistency checker
.Sh SYNOPSIS
.Nm quotacheck
.Op Fl g
.Op Fl u
.Op Fl v
.Ar filesystem Ar ...
.Nm quotacheck
.Op Fl g
.Op Fl u
.Op Fl v
.Fl a
.Sh DESCRIPTION
.Nm Quotacheck
E 8
D 6
examines each file system,
builds a table of current disc usage,
and compares this table against that stored
in the disc quota file for the file system.
E 6
I 6
examines each filesystem,
builds a table of current disk usage,
and compares this table against that recorded
in the disk quota file for the filesystem.
E 6
If any inconsistencies are detected, both the
quota file and the current system copy of the
incorrect quotas are updated (the latter only
D 6
occurs if an active file system is checked).
E 6
I 6
occurs if an active filesystem is checked).
By default both user and group quotas are checked.
D 8
The optional \fI-g\fP flag specifies that only group quotas should be checked.
The optional \fI-u\fP flag specifies that only user quotas should be checked.
Specifying both \fI-g\fP and \fI-u\fP is equivalent to the default.
E 6
.PP
E 8
I 8
.Pp
Available options:
.Bl -tag -width Ds
.It Fl a
E 8
If the
D 8
.B \-a
E 8
I 8
.Fl a
E 8
D 6
flag is supplied in place of any file system
names,
E 6
I 6
flag is supplied in place of any filesystem names,
E 6
D 8
.I quotacheck
E 8
I 8
.Nm quotacheck
E 8
D 6
will check all the file systems indicated in
E 6
I 6
will check all the filesystems indicated in
E 6
D 8
.I /etc/fstab
E 8
I 8
.Pa /etc/fstab
E 8
D 6
to be read-write with disc quotas.
E 6
I 6
to be read-write with disk quotas.
By default only the types of quotas listed in
D 8
.I /etc/fstab
E 8
I 8
.Pa /etc/fstab
E 8
are checked.
D 8
The optional \fI-g\fP flag specifies that only group quotas listed in
.I /etc/fstab
should be checked.
The optional \fI-u\fP flag specifies that only user quotas listed in
.I /etc/fstab
should be checked.
Specifying both \fI-g\fP and \fI-u\fP is equivalent to the default.
E 8
I 8
.It Fl g
Only group quotas listed in
.Pa /etc/fstab
are to be checked.
.It Fl u
Only user quotas listed in
.Pa /etc/fstab
are to be checked.
.It Fl v
.Nm quotacheck
reports discrepancies between the
calculated and recorded disk quotas.
.El
.Pp
Specifying both
.Fl g
and
.Fl u
is equivalent to the default.
E 8
Parallel passes are run on the filesystems required,
using the pass numbers in
D 8
.I /etc/fstab
E 8
I 8
.Pa /etc/fstab
E 8
in an identical fashion to
D 8
.IR fsck (8).
E 6
.PP
E 8
I 8
.Xr fsck 8 .
.Pp
E 8
Normally
D 8
.I quotacheck
E 8
I 8
.Nm quotacheck
E 8
D 6
reports only those quotas modified.  If the
E 6
I 6
operates silently.
D 8
If the
E 6
.B \-v
option is supplied,
.I quotacheck
D 6
will indicate the calculated disc quotas for each
user on a particular file system.
E 6
I 6
will report discrepancies between the
calculated and recorded disk quotas.
E 6
.PP
I 3
D 6
If the
.B \-p
flag is supplied then parallel passes will be run on
the filesystems required, using the pass numbers in
/etc/fstab in an identical fashion to
.IR fsck (8).
.PP
E 6
E 3
.I Quotacheck
E 8
I 8
.Pp
.Nm Quotacheck
E 8
D 6
expects each file system to be checked to have a
quota file named
.I quotas
in the root directory.  If none is present, 
E 6
I 6
expects each filesystem to be checked to have a
quota files named
D 8
.I quota.user
E 8
I 8
.Pa quota.user
E 8
and
D 8
.I quota.group
E 8
I 8
.Pa quota.group
E 8
which are located at the root of the associated file system.
These defaults may be overridden in
D 8
.I /etc/fstab .
E 8
I 8
.Pa /etc/fstab .
E 8
If a file is not present, 
E 6
D 8
.I quotacheck
E 8
I 8
.Nm quotacheck
E 8
D 6
will ignore the file system.
E 6
I 6
will create it.
E 6
D 8
.PP
.I Quotacheck 
E 8
I 8
.Pp
.Nm Quotacheck
E 8
is normally run at boot time from the
D 8
.I /etc/rc.local
E 8
I 8
.Pa /etc/rc.local
E 8
file, see
D 8
.IR rc (8),
E 8
I 8
.Xr rc 8 ,
E 8
D 6
before enabling disc quotas with
E 6
I 6
before enabling disk quotas with
E 6
D 8
.IR quotaon (8).
.PP
.I Quotacheck
E 8
I 8
.Xr quotaon 8 .
.Pp
.Nm Quotacheck
E 8
accesses the raw device in calculating the actual
D 6
disc usage for each user.  Thus, the file systems
E 6
I 6
disk usage for each user.
Thus, the filesystems
E 6
checked should be quiescent while
D 8
.I quotacheck
E 8
I 8
.Nm quotacheck
E 8
is running.
D 8
.SH FILES
.DT
D 6
/etc/fstab	default file systems
E 6
I 6
\fIquota.user\fP	at the filesystem root with user quotas
.br
\fIquota.group\fP	at the filesystem root with group quotas
.br
/etc/fstab	default filesystems
E 6
.SH "SEE ALSO"
D 3
quota(2), setquota(2), quotaon(8)
E 3
I 3
D 6
quota(2), setquota(2), quotaon(8), fsck(8)
E 6
I 6
quota(1),
quotactl(2),
fstab(5),
edquota(8), fsck(8), quotaon(8), repquota(8)
E 8
I 8
.Sh FILES
.Bl -tag -width quota.group -compact
.It Pa quota.user
at the filesystem root with user quotas
.It Pa quota.group
at the filesystem root with group quotas
.It Pa /etc/fstab
default filesystems
.El
.Sh SEE ALSO
.Xr quota 1 ,
.Xr quotactl 2 ,
.Xr fstab 5 ,
.Xr edquota 8 ,
.Xr fsck 8 ,
.Xr quotaon 8 ,
.Xr repquota 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 8
E 6
E 3
E 1
