h14431
s 00000/00001/00125
d D 8.2 93/12/11 23:44:50 mckusick 8 7
c copyediting for Usenix manuals
e
s 00002/00002/00124
d D 8.1 93/06/06 14:11:44 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00082/00069/00044
d D 6.5 91/03/16 18:14:00 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00112
d D 6.4 90/06/24 22:48:17 trent 5 4
c new copyright notice
e
s 00016/00005/00107
d D 6.3 88/09/20 10:25:07 bostic 4 3
c Berkeley copyright
e
s 00022/00011/00090
d D 6.2 86/05/26 20:41:55 karels 3 2
c add -f
e
s 00001/00001/00100
d D 6.1 85/04/27 16:00:26 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00101/00000/00000
d D 5.1 85/04/27 16:00:18 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 4
.\"
I 4
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH TRPT 8C "2 March 1983"
E 2
I 2
D 4
.TH TRPT 8C "%Q%"
E 4
I 4
D 6
.TH TRPT 8 "%Q%"
E 4
E 2
.UC 5
.SH NAME
trpt \- transliterate protocol trace
.SH SYNOPSIS
.B trpt
[
.B \-a
] [
.B \-s
]  [
.B \-t
] [
I 3
.B \-f
] [
E 3
.B \-j
] [
.B \-p
hex-address ]
[ system [ core ] ]
.SH DESCRIPTION
.I Trpt
interrogates the buffer of TCP trace records created
when a socket is marked for \*(lqdebugging\*(rq (see
.IR setsockopt (2)),
E 6
I 6
.Dd %Q%
.Dt TRPT 8
.Os BSD 4.2
.Sh NAME
.Nm trpt
.Nd transliterate protocol trace
.Sh SYNOPSIS
.Nm trpt
.Op Fl a
.Op Fl f
.Op Fl j
.Op Fl p Ar hex-address
.Op Fl s
.Op Fl t
.Oo
.Ar system Op Ar core
.Oc
.Sh DESCRIPTION
.Nm Trpt
interrogates the buffer of
.Tn TCP
trace records created
when a socket is marked for
.Dq debugging
(see
.Xr setsockopt 2 ) ,
E 6
and prints a readable description of these records.
When no options are supplied, 
D 6
.I trpt
E 6
I 6
.Nm trpt
E 6
prints all the trace records found in the system
D 6
grouped according to TCP connection protocol control
block (PCB).  The following options may be used to
E 6
I 6
grouped according to
.Tn TCP
connection protocol control
block
.Pq Tn PCB .
The following options may be used to
E 6
alter this behavior.
D 6
.TP
I 3
.B \-a
in addition to the normal output,
E 6
I 6
.Bl -tag -width Ds
.It Fl a
In addition to the normal output,
E 6
print the values of the source and destination
addresses for each packet recorded.
D 6
.TP
E 3
.B \-s
in addition to the normal output,
E 6
I 6
.It Fl f
Follow the trace as it occurs, waiting a short time for additional records
each time the end of the log is reached.
.It Fl j
Just give a list of the protocol control block
addresses for which there are trace records.
.It Fl p
Show only trace records associated with the protocol
control block at the given address
.Ar hex-address .
.It Fl s
In addition to the normal output,
E 6
print a detailed description of the packet
D 3
sequencing information,
E 3
I 3
sequencing information.
E 3
D 6
.TP
.B \-t
E 6
I 6
.It Fl t
E 6
in addition to the normal output,
print the values for all timers at each
D 3
point in the trace,
E 3
I 3
point in the trace.
E 3
D 6
.TP
I 3
.B \-f
follow the trace as it occurs, waiting a short time for additional records
each time the end of the log is reached.
.TP
E 3
.B \-j
just give a list of the protocol control block
D 3
addresses for which there are trace records,
E 3
I 3
addresses for which there are trace records.
E 3
.TP
.B \-p
show only trace records associated with the protocol
D 3
control block who's address follows,
.TP
.B \-a
in addition to the normal output,
print the values of the source and destination
addresses for each packet recorded.
E 3
I 3
control block, the address of which follows.
E 3
.PP
E 6
I 6
.El
.Pp
E 6
The recommended use of
D 6
.I trpt
E 6
I 6
.Nm trpt
E 6
is as follows.
Isolate the problem and enable debugging on the
socket(s) involved in the connection.
Find the address of the protocol control blocks
associated with the sockets using the 
D 6
.B \-A
E 6
I 6
.Fl A
E 6
option to 
D 6
.IR netstat (1).
E 6
I 6
.Xr netstat 1 .
E 6
Then run
D 6
.I trpt
E 6
I 6
.Nm trpt
E 6
with the
D 6
.B \-p
E 6
I 6
.Fl p
E 6
option, supplying the associated
D 3
protocol control block addresses.  If there are
E 3
I 3
protocol control block addresses.
The
D 6
.B \-f
E 6
I 6
.Fl f
E 6
option can be used to follow the trace log once the trace is located.
If there are
E 3
many sockets using the debugging option, the
D 6
.B \-j
E 6
I 6
.Fl j
E 6
option may be useful in checking to see if
any trace records are present for the socket in
question.
I 3
D 8
The
E 8
E 3
D 6
.PP
E 6
I 6
.Pp
E 6
If debugging is being performed on a system or
core file other than the default, the last two
arguments may be used to supplant the defaults.
D 6
.SH FILES
/vmunix
.br
/dev/kmem
.SH "SEE ALSO"
D 3
setsockopt(2), netstat(1)
E 3
I 3
D 4
setsockopt(2), netstat(1), trsp(8C)
E 4
I 4
netstat(1), setsockopt(2), trsp(8)
E 4
E 3
.SH DIAGNOSTICS
``no namelist'' when the system image doesn't
E 6
I 6
.Sh FILES
.Bl -tag -width /dev/kmem -compact
.It Pa /vmunix
.It Pa /dev/kmem
.El
.Sh SEE ALSO
.Xr netstat 1 ,
.Xr setsockopt 2 ,
.Xr trsp 8
.Sh DIAGNOSTICS
.Bl -tag -width Ds
.It Sy no namelist
When the system image doesn't
E 6
contain the proper symbols to find the trace buffer;
others which should be self explanatory.
D 6
.SH BUGS
E 6
I 6
.El
.Sh BUGS
E 6
Should also print the data for each input or output,
but this is not saved in the race record.
D 6
.PP
E 6
I 6
.Pp
E 6
The output format is inscrutable and should be described
here.
I 6
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 6
E 1
