h01718
s 00001/00001/00140
d D 8.3 95/04/28 12:51:41 bostic 10 9
c typo; From: Chris Torek <torek@BSDI.COM>
e
s 00001/00001/00140
d D 8.2 93/12/30 15:39:28 mckusick 9 8
c copyediting for Usenix manuals
e
s 00002/00002/00139
d D 8.1 93/06/06 16:36:50 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00109/00017/00032
d D 6.5 93/03/06 13:34:37 bostic 7 6
c implement from scratch, using utimes(2), for POSIX 1003.2
e
s 00003/00000/00046
d D 6.4 91/06/27 17:25:27 bostic 6 5
c add POSIX/IEEE contribution notice
e
s 00040/00036/00006
d D 6.3 91/04/23 16:22:09 cael 5 4
c mdoc version 3
e
s 00005/00000/00037
d D 6.2 91/04/18 18:25:00 bostic 4 3
c new copyright; att/bsd/shared
e
s 00001/00001/00036
d D 6.1 85/04/29 18:03:18 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00015/00005/00022
d D 5.1 85/04/29 18:03:09 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00027/00000/00000
d D 4.1 85/04/29 18:03:01 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 5
.\" Copyright (c) 1985 The Regents of the University of California.
E 5
I 5
D 8
.\" Copyright (c) 1991 Regents of the University of California.
E 5
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
I 6
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 6
D 5
.\" %sccs.include.proprietary.roff%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH TOUCH 1 
E 2
I 2
D 3
.TH TOUCH 1  "18 January 1983"
E 3
I 3
D 5
.TH TOUCH 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
touch \- update date last modified of a file
.SH SYNOPSIS
.B touch
[
.B \-c
]
I 2
[
.B \-f
]
E 2
file ...
.SH DESCRIPTION
.I Touch
attempts to set the modified date of each
D 2
.I file.
This is done by reading a character from the file
E 2
I 2
.IR file .
If a
.I file
exists,
this is done by reading a character from the file
E 2
and writing it back.
D 2
.PP
E 2
If a
.I file
does not exist,
an attempt will be made to create it unless the
.B \-c
option is specified.
E 5
I 5
.Dd %Q%
.Dt TOUCH 1
.Os
.Sh NAME
.Nm touch
D 7
.Nd update date last modified of a file
E 7
I 7
.Nd change file access and modification times
E 7
.Sh SYNOPSIS
.Nm touch
D 7
.Op Fl c
.Op Fl f
E 7
I 7
.Op Fl acfm
.Op Fl r Ar file
D 10
.Op Fl t [[CC]YY]MMDDhhmm[.SS]
E 10
I 10
.Op Fl t Ar [[CC]YY]MMDDhhmm[.SS]
E 10
E 7
.Ar file ...
.Sh DESCRIPTION
E 5
I 2
The
D 5
.B \-f
option will attempt to force the touch
E 5
I 5
.Nm touch
D 7
utility
changes the modification and or access times
of the given
.Ar file .
E 7
I 7
utility sets the modification and access times of files to the
current time of day.
If the file doesn't exist, it is created with default permissions.
E 7
.Pp
D 7
Available options:
E 7
I 7
The following options are available:
E 7
.Bl -tag -width Ds
I 7
.It Fl a
Change the access time of the file.
The modification time of the file is not changed unless the
.Fl m
flag is also specified.
E 7
.It Fl c
D 7
Do not create a specified file if it does not exist.
Do not write any diagnostic messages concerning this
condition.
E 7
I 7
Do not create the file if it does not exist.
The
.Nm touch
utility does not treat this as an error.
No error messages are displayed and the exit value is not affected.
E 7
.It Fl f
D 7
Attempt to force the
E 7
I 7
Attempt to force the update, even if the file permissions do not
currently permit it.
.It Fl m
Change the modification time of the file.
The access time of the file is not changed unless the
.Fl a
flag is also specified.
.It Fl r
Use the access and modifications times from the specified file
instead of the current time of day.
.It Fl t
Change the access and modification times to the specified time.
The argument should be in the form
.Dq [[CC]YY]MMDDhhmm[.SS]
where each pair of letters represents the following:
.Pp
.Bl -tag -width Ds -compact -offset indent
.It Ar CC
The first two digits of the year (the century).
.It Ar YY
The second two digits of the year.
If
.Dq YY
is specified, but
.Dq CC
is not, a value for
.Dq YY
between 69 and 99 results in a
.Dq YY
value of 19.
Otherwise, a
.Dq YY
value of 20 is used.
.It Ar MM
The month of the year, from 1 to 12.
.It Ar DD
the day of the month, from 1 to 31.
.It Ar hh
The hour of the day, from 0 to 23.
.It Ar mm
The minute of the hour, from 0 to 59.
.It Ar SS
The second of the minute, from 0 to 61.
.El
.Pp
If the
.Dq CC
and
.Dq YY
letter pairs are not specified, the values default to the current
year.
If the
.Dq SS
letter pair is not specified, the value defaults to 0.
.El
.Pp
The
E 7
.Nm touch
E 5
D 7
in spite of read and write permissions on a
D 5
.IR file .
E 2
.SH SEE\ ALSO
D 2
utime(2)
E 2
I 2
utimes(2)
E 5
I 5
.Ar file .
E 7
I 7
utility exits 0 on success, and >0 if an error occurs.
E 7
.Sh SEE ALSO
.Xr utimes 2
I 7
.Sh COMPATIBILITY
The obsolescent form of
.Nm touch ,
where a time format is specified as the first argument, is supported.
When no
.Fl r
or
.Fl t
option is specified, there are at least two arguments, and the first
argument is a string of digits either eight or ten characters in length,
D 9
the first argument is interprested as a time specification of the form
E 9
I 9
the first argument is interpreted as a time specification of the form
E 9
.Dq MMDDhhmm[YY] .
.Pp
The
.Dq MM ,
.Dq DD ,
.Dq hh
and
.Dq mm
letter pairs are treated as their counterparts specified to the
.Fl t
option.
If the
.Dq YY
letter pair is in the range 69 to 99, the year is set to 1969 to 1999,
otherwise, the year is set in the 21st century.
E 7
.Sh HISTORY
A
D 7
.Nm
E 7
I 7
.Nm touch
E 7
command appeared in
.At v7 .
D 7
This command is
.Ud .
E 7
I 7
.Sh STANDARDS
The
.Nm touch
function is expected to be a superset of the
.St -p1003.2
specification.
E 7
E 5
E 2
E 1
