h02203
s 00001/00000/00264
d D 8.3 94/06/01 20:37:19 ah 16 15
c page breaks for 4.4BSD manuals
e
s 00002/00002/00262
d D 8.2 94/04/19 08:29:03 bostic 15 14
c spell
e
s 00002/00002/00262
d D 8.1 93/06/04 18:48:26 bostic 14 13
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00064/00034/00200
d D 6.11 92/06/27 18:24:15 andrew 13 12
c document changes to logging, list files displayed during login
e
s 00017/00018/00217
d D 6.10 92/06/22 14:13:20 bostic 12 11
c spell out the rules for the anonymous directory
e
s 00179/00143/00056
d D 6.9 91/03/16 17:05:17 cael 11 10
c macro and text revision (-mdoc version 3)
e
s 00002/00012/00197
d D 6.8 90/06/24 21:20:24 trent 10 8
c new copyright & pathname (ftpd)
e
s 00000/00001/00208
d D 6.7.1.1 89/03/02 09:38:36 karels 9 8
c remove restart for network release
e
s 00049/00015/00160
d D 6.7 89/02/28 12:09:59 karels 8 7
c lots of changes, mostly from Rick Adams: implement restart, stat,
c site (from Dave Borman), size, mdtm; pointer fixes for cray; more cleanups;
c proctitle stuff
e
s 00003/00001/00172
d D 6.6 89/01/25 14:43:57 rick 7 6
c add support for REST (restart at arbitrary byte position) SYST (system
c type); fix chroot bug; add setproctitle (#ifdef'd); clean up 400/500
c return codes; make NLST/LIST RFC conformant
e
s 00016/00005/00157
d D 6.5 88/09/19 21:23:19 bostic 6 5
c Berkeley copyright
e
s 00004/00001/00158
d D 6.4 86/05/28 15:28:27 mckusick 5 4
c add restriction that user must have a standard shell
e
s 00004/00005/00155
d D 6.3 86/03/07 11:40:23 minshall 4 3
c minor changes from Steve Jacobson.
e
s 00018/00015/00142
d D 6.2 86/02/03 15:20:07 minshall 3 2
c Steve Jacoson's changes (from <csvsj@ucbopal>).
e
s 00001/00001/00156
d D 6.1 85/04/27 14:56:57 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00157/00000/00000
d D 5.1 85/04/27 14:56:40 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
f b 
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
E 3
I 3
D 6
.\" Copyright (c) 1985 Regents of the University of California.
E 3
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 8
.\" Copyright (c) 1985 The Regents of the University of California.
E 8
I 8
D 11
.\" Copyright (c) 1985, 1988 The Regents of the University of California.
E 11
I 11
D 14
.\" Copyright (c) 1985, 1988, 1991 The Regents of the University of California.
E 11
E 8
.\" All rights reserved.
E 14
I 14
.\" Copyright (c) 1985, 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 14
E 6
.\"
I 6
D 10
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 10
I 10
.\" %sccs.include.redist.man%
E 10
.\"
E 6
D 11
.\"	%W% (Berkeley) %G%
E 11
I 11
.\"     %W% (Berkeley) %G%
E 11
.\"
D 2
.TH FTPD 8C "4 March 1983"
E 2
I 2
D 3
.TH FTPD 8C "%Q%"
E 3
I 3
D 6
.TH FTPD 8C "April 27, 1985"
E 6
I 6
D 7
.TH FTPD 8 "%Q%"
E 7
I 7
D 8
.TH FTPD 8 "January 24, 1989"
E 8
I 8
D 11
.TH FTPD 8 "February 23, 1989"
E 8
E 7
E 6
E 3
E 2
.UC 5
.SH NAME
ftpd \- DARPA Internet File Transfer Protocol server
.SH SYNOPSIS
D 10
.B /etc/ftpd
E 10
I 10
.B ftpd
E 10
[
.B \-d
] [
.B \-l
] [
.BR \-t timeout
I 8
] [
.BR \-T maxtimeout
E 8
]
.SH DESCRIPTION
.I Ftpd
D 8
is the DARPA Internet File Transfer Prototocol
E 8
I 8
is the DARPA Internet File Transfer Protocol
E 8
server process.  The server uses the TCP protocol
and listens at the port specified in the ``ftp''
E 11
I 11
.Dd %Q%
.Dt FTPD 8
.Os BSD 4.2
.Sh NAME
.Nm ftpd
.Nd
D 13
.Tn DARPA
E 13
Internet File Transfer Protocol server
.Sh SYNOPSIS
.Nm ftpd
D 12
.Op Fl d
.Op Fl l
E 12
I 12
.Op Fl dl
E 12
D 13
.Op Fl t Ar timeout
E 13
.Op Fl T Ar maxtimeout
I 13
.Op Fl t Ar timeout
E 13
.Sh DESCRIPTION
.Nm Ftpd
is the
D 13
.Tn DARPA
E 13
Internet File Transfer Protocol
server process.  The server uses the
.Tn TCP
protocol
and listens at the port specified in the
.Dq ftp
E 11
service specification; see
D 11
.IR services (5).
.PP
If the 
.B \-d
option is specified,
D 3
each socket created will have debugging turned
on (SO_DEBUG).  With debugging enabled, the system
will trace all TCP packets sent and received on a
socket.  The program
.IR trpt (8C)
may then be used to interpret the packet traces.
E 3
I 3
D 4
debugging information is included in the "/tmp/ftplog" file when the -l
option is also specified.
E 4
I 4
debugging information is written to the syslog.
E 4
E 3
.PP
If the
.B \-l
option is specified,
D 3
each ftp session is logged on the standard output.
This allows a line of the form 
`/etc/ftpd -l > /tmp/ftplog''
to be used to conveniently maintain a log of ftp sessions.
E 3
I 3
D 4
each ftp session is logged in a file named "/tmp/ftplog".
E 4
I 4
each ftp session is logged in the syslog.
E 4
E 3
.PP
The ftp server
D 4
will timeout an inactive session after 60 seconds.
E 4
I 4
will timeout an inactive session after 15 minutes.
E 4
If the
.B \-t
option is specified,
the inactivity timeout period will be set to
D 8
.IR timeout .
E 8
I 8
.I timeout
seconds.
E 11
I 11
.Xr services 5 .
.Pp
Available options:
.Bl -tag -width Ds
.It Fl d
D 13
Debugging information is written to the syslog.
E 13
I 13
Debugging information is written to the syslog using LOG_FTP.
E 13
.It Fl l
D 13
Each
E 13
I 13
Each successful and failed 
E 13
.Xr ftp 1
D 13
session is logged in the syslog.
.It Fl t
The inactivity timeout period is set to
.Ar timeout
seconds (the default is 15 minutes).
E 13
I 13
session is logged using syslog with a facility of LOG_FTP.
If this option is specified twice, the retrieve (get), store (put), append,
delete, make directory, remove directory and rename operations and
their filename arguments are also logged.
E 13
.It Fl T
E 11
A client may also request a different timeout period;
the maximum period allowed may be set to
D 11
.I timeout
E 11
I 11
.Ar timeout
E 11
seconds with the
D 11
.B \-T
E 11
I 11
.Fl T
E 11
option.
The default limit is 2 hours.
I 13
.It Fl t
The inactivity timeout period is set to
.Ar timeout
seconds (the default is 15 minutes).
E 13
E 8
D 11
.PP
E 11
I 11
.El
.Pp
E 11
D 13
The ftp server currently supports the following ftp
D 8
requests;  case is not distinguished.
E 8
I 8
requests; case is not distinguished.
E 13
I 13
The file
.Pa /etc/nologin
can be used to disable ftp access.
If the file exists,
.Nm
displays it and exits.
If the file
.Pa /etc/ftpwelcome
exists,
.Nm
prints it before issuing the 
.Dq ready
message.
If the file
.Pa /etc/motd
exists,
.Nm
D 15
prints it after a successsful login.
E 15
I 15
prints it after a successful login.
E 15
.Pp
The ftp server currently supports the following ftp requests.
The case of the requests is ignored.
E 13
E 8
D 11
.PP
.nf
.ta \w'Request        'u
\fBRequest	Description\fP
I 3
ABOR	abort previous command
E 3
ACCT	specify account (ignored)
ALLO	allocate storage (vacuously)
APPE	append to a file
I 3
CDUP	change to parent of current working directory
E 3
CWD	change working directory
DELE	delete a file
HELP	give help information
D 8
LIST	give list files in a directory (``ls -lg'')
E 8
I 8
LIST	give list files in a directory (``ls -lgA'')
E 8
I 3
MKD	make a directory
I 8
MDTM	show last modification time of file
E 8
E 3
MODE	specify data transfer \fImode\fP
D 8
NLST	give name list of files in directory (``ls'')
E 8
I 8
NLST	give name list of files in directory 
E 8
NOOP	do nothing
PASS	specify password
I 3
PASV	prepare for server-to-server transfer
E 3
PORT	specify data connection port
I 3
PWD	print the current working directory
E 3
QUIT	terminate session
I 8
D 9
REST	restart incomplete transfer
E 9
E 8
RETR	retrieve a file
I 3
RMD	remove a directory
E 3
RNFR	specify rename-from file name
RNTO	specify rename-to file name
I 8
SITE	non-standard commands (see next section)
SIZE	return size of file
STAT	return status of server
E 8
STOR	store a file
I 3
STOU	store a file with a unique name
E 3
STRU	specify data transfer \fIstructure\fP
I 7
SYST	show operating system type of server system
E 7
TYPE	specify data transfer \fItype\fP
USER	specify user name
D 8
XCUP	change to parent of current working directory
XCWD	change working directory
XMKD	make a directory
XPWD	print the current working directory
XRMD	remove a directory
I 7
XUMA	set umask
E 8
I 8
XCUP	change to parent of current working directory (deprecated)
XCWD	change working directory (deprecated)
XMKD	make a directory (deprecated)
XPWD	print the current working directory (deprecated)
XRMD	remove a directory (deprecated)
E 8
E 7
.fi
.PP
I 8
The following non-standard or UNIX specific commands are supported
by the SITE request.
.PP
.nf
.ta \w'Request        'u
\fBRequest	Description\fP
UMASK	change umask. \fIE.g.\fP SITE UMASK 002
IDLE	set idle-timer. \fIE.g.\fP SITE IDLE 60
CHMOD	change mode of a file. \fIE.g.\fP SITE CHMOD 755 filename
HELP	give help information. \fIE.g.\fP SITE HELP
.fi
.PP
E 8
D 3
The remaining ftp requests specified in Internet RFC 765 are
E 3
I 3
The remaining ftp requests specified in Internet RFC 959 are
E 11
I 11
.Bl -column "Request" -offset indent
.It Request Ta "Description"
.It ABOR Ta "abort previous command"
.It ACCT Ta "specify account (ignored)"
.It ALLO Ta "allocate storage (vacuously)"
.It APPE Ta "append to a file"
.It CDUP Ta "change to parent of current working directory"
.It CWD Ta "change working directory"
.It DELE Ta "delete a file"
.It HELP Ta "give help information"
.It LIST Ta "give list files in a directory" Pq Dq Li "ls -lgA"
.It MKD Ta "make a directory"
.It MDTM Ta "show last modification time of file"
.It MODE Ta "specify data transfer" Em mode
.It NLST Ta "give name list of files in directory"
.It NOOP Ta "do nothing"
.It PASS Ta "specify password"
.It PASV Ta "prepare for server-to-server transfer"
.It PORT Ta "specify data connection port"
.It PWD Ta "print the current working directory"
.It QUIT Ta "terminate session"
.It REST Ta "restart incomplete transfer"
.It RETR Ta "retrieve a file"
.It RMD Ta "remove a directory"
.It RNFR Ta "specify rename-from file name"
.It RNTO Ta "specify rename-to file name"
.It SITE Ta "non-standard commands (see next section)"
.It SIZE Ta "return size of file"
.It STAT Ta "return status of server"
.It STOR Ta "store a file"
.It STOU Ta "store a file with a unique name"
.It STRU Ta "specify data transfer" Em structure
.It SYST Ta "show operating system type of server system"
.It TYPE Ta "specify data transfer" Em type
.It USER Ta "specify user name"
.It XCUP Ta "change to parent of current working directory (deprecated)"
.It XCWD Ta "change working directory (deprecated)"
.It XMKD Ta "make a directory (deprecated)"
.It XPWD Ta "print the current working directory (deprecated)"
.It XRMD Ta "remove a directory (deprecated)"
.El
.Pp
The following non-standard or
.Tn UNIX
specific commands are supported
by the
SITE request.
.Pp
.Bl -column Request -offset indent
.It Sy Request Ta Sy Description
D 13
.It UMASK Ta change umask. Em E.g. SITE UMASK 002
.It IDLE Ta set idle-timer. Em E.g. SITE IDLE 60
.It CHMOD Ta change mode of a file. Em E.g.
SITE CHMOD 755 filename
.It HELP Ta give help information. Em E.g. SITE HELP
E 13
I 13
.It UMASK Ta change umask, e.g. ``SITE UMASK 002''
.It IDLE Ta set idle-timer, e.g. ``SITE IDLE 60''
.It CHMOD Ta change mode of a file, e.g. ``SITE CHMOD 755 filename''
.It HELP Ta give help information.
E 13
.El
.Pp
D 13
The remaining ftp requests specified in Internet
.%T "RFC 959"
E 13
I 13
The remaining ftp requests specified in Internet RFC 959
E 13
are
E 11
E 3
recognized, but not implemented.
I 8
D 13
MDTM and SIZE are not specified in
D 11
RFC 959, but will appear in the next updated FTP RFC.
E 8
.PP
E 11
I 11
.%T "RFC 959" ,
but will appear in the next updated FTP RFC.
E 13
I 13
MDTM and SIZE are not specified in RFC 959, but will appear in the
next updated FTP RFC.
E 13
.Pp
E 11
I 3
The ftp server will abort an active file transfer only when the
D 11
ABOR command is preceded by a Telnet "Interrupt Process" (IP)
E 11
I 11
ABOR
command is preceded by a Telnet "Interrupt Process" (IP)
E 11
signal and a Telnet "Synch" signal in the command Telnet stream,
D 11
as described in Internet RFC 959.
I 8
If a STAT command is received during a data transfer, preceded by a Telnet IP
E 11
I 11
D 13
as described in Internet
.%T "RFC 959" .
E 13
I 13
as described in Internet RFC 959.
E 13
If a
STAT
command is received during a data transfer, preceded by a Telnet IP
E 11
and Synch, transfer status will be returned.
E 8
D 11
.PP
E 3
.I Ftpd
interprets file names according to the ``globbing''
E 11
I 11
.Pp
.Nm Ftpd
interprets file names according to the
.Dq globbing
E 11
conventions used by
D 11
.IR csh (1).
This allows users to utilize the metacharacters ``*?[]{}~''.
.PP
.I Ftpd
E 11
I 11
.Xr csh 1 .
This allows users to utilize the metacharacters
.Dq Li \&*?[]{}~ .
.Pp
.Nm Ftpd
E 11
authenticates users according to three rules. 
D 11
.IP 1)
E 11
I 11
.Pp
.Bl -enum -offset indent
.It
E 11
D 13
The user name must be in the password data base,
E 13
I 13
The login name must be in the password data base,
E 13
D 11
.IR /etc/passwd ,
E 11
I 11
.Pa /etc/passwd ,
E 11
D 13
and not have a null password.  In this case a password
must be provided by the client before any file operations
may be performed.
E 13
I 13
and not have a null password.
In this case a password must be provided by the client before any
file operations may be performed.
E 13
D 11
.IP 2)
E 11
I 11
.It
E 11
D 13
The user name must not appear in the file
E 13
I 13
The login name must not appear in the file
E 13
D 11
.IR /etc/ftpusers .
.IP 3)
E 11
I 11
.Pa /etc/ftpusers .
.It
E 11
I 5
The user must have a standard shell returned by 
D 11
.IR getusershell (3).
.IP 4)
E 5
If the user name is ``anonymous'' or ``ftp'', an
E 11
I 11
.Xr getusershell 3 .
.It
If the user name is
.Dq anonymous
or
.Dq ftp ,
an
E 11
anonymous ftp account must be present in the password
D 11
file (user ``ftp'').  In this case the user is allowed
E 11
I 11
file (user
.Dq ftp ) .
In this case the user is allowed
E 11
D 13
to log in by specifying any password (by convention this
is given as the client host's name).
E 13
I 13
to log in by specifying any password (by convention an email address for
the user should be used as the password).
E 13
D 11
.PP
E 11
I 11
.El
.Pp
E 11
In the last case, 
D 11
.I ftpd
E 11
I 11
.Nm ftpd
E 11
takes special measures to restrict the client's access privileges.
The server performs a 
D 11
.IR chroot (2)
command to the home directory of the ``ftp'' user.
E 11
I 11
.Xr chroot 2
D 13
command to the home directory of the
E 13
I 13
to the home directory of the
E 13
.Dq ftp
user.
E 11
In order that system security is not breached, it is recommended
D 11
that the ``ftp'' subtree be constructed with care;  the following
E 11
I 11
that the
.Dq ftp
D 12
subtree be constructed with care;  the following
E 11
rules are recommended.
E 12
I 12
subtree be constructed with care, following these rules:
E 12
D 11
.IP ~ftp)
Make the home directory owned by ``ftp'' and unwritable by anyone.
.IP ~ftp/bin)
E 11
I 11
.Bl -tag -width "~ftp/pub" -offset indent
.It Pa ~ftp
Make the home directory owned by
D 12
.Dq ftp
E 12
I 12
.Dq root
E 12
and unwritable by anyone.
I 16
.ne 1i
E 16
.It Pa ~ftp/bin
E 11
D 12
Make this directory owned by the super-user and unwritable by
anyone.  The program
E 12
I 12
Make this directory owned by
.Dq root
D 13
and unwritable by anyone.
E 13
I 13
and unwritable by anyone (mode 555).
E 13
The program
E 12
D 11
.IR ls (1)
E 11
I 11
.Xr ls 1
E 11
D 8
must be present to support the list commands.  This
E 8
I 8
D 12
must be present to support the list command.  This
E 8
program should have mode 111.
E 12
I 12
must be present to support the list command.
This program should be mode 111.
E 12
D 11
.IP ~ftp/etc)
E 11
I 11
.It Pa ~ftp/etc
E 11
D 12
Make this directory owned by the super-user and unwritable by
anyone.  The files
E 12
I 12
Make this directory owned by
.Dq root
D 13
and unwritable by anyone.
E 13
I 13
and unwritable by anyone (mode 555).
E 13
The files
E 12
D 11
.IR passwd (5)
E 11
I 11
.Xr passwd 5
E 11
and
D 11
.IR group (5)
E 11
I 11
.Xr group 5
E 11
must be present for the 
D 11
.I ls
E 11
I 11
.Xr ls
E 11
D 8
command to work properly.  These files should be mode 444.
E 8
I 8
command to be able to produce owner names rather than numbers.
The password field in
D 11
.I passwd
E 11
I 11
.Xr passwd
E 11
D 12
is not used, and should not contain real encrypted passwords.
E 12
I 12
is not used, and should not contain real passwords.
I 13
The file
.Pa motd ,
D 15
if present, will be printed after a sucessful login.
E 15
I 15
if present, will be printed after a successful login.
E 15
E 13
E 12
These files should be mode 444.
E 8
D 11
.IP ~ftp/pub)
Make this directory mode 777 and owned by ``ftp''.  Users
E 11
I 11
.It Pa ~ftp/pub
Make this directory mode 777 and owned by
.Dq ftp .
D 12
Users
E 11
should then place files which are to be accessible via the
anonymous account in this directory.
E 12
I 12
Guests
can then place files which are to be accessible via the anonymous
account in this directory.
I 13
.El
.Sh FILES
.Bl -tag -width /etc/ftpwelcome -compact
.It Pa /etc/ftpusers
List of unwelcome/restricted users.
.It Pa /etc/ftpwelcome
Welcome notice.
.It Pa /etc/motd
Welcome notice after login.
.It Pa /etc/nologin
Displayed and access refused.
E 13
E 12
D 11
.SH "SEE ALSO"
D 4
ftp(1C),
E 4
I 4
D 5
ftp(1C), syslogd(8)
E 5
I 5
D 6
ftp(1C), getusershell(3), syslogd(8)
E 6
I 6
ftp(1), getusershell(3), syslogd(8)
E 6
E 5
E 4
.SH BUGS
E 11
I 11
.El
.Sh SEE ALSO
.Xr ftp 1 ,
.Xr getusershell 3 ,
.Xr syslogd 8
.Sh BUGS
E 11
D 3
There is no support for aborting commands.
.PP
E 3
D 12
The anonymous account is inherently dangerous and should
avoided when possible.
D 11
.PP
E 11
I 11
.Pp
E 12
E 11
The server must run as the super-user
to create sockets with privileged port numbers.  It maintains
an effective user id of the logged in user, reverting to
the super-user only when binding addresses to sockets.  The
possible security holes have been extensively
scrutinized, but are possibly incomplete.
I 11
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 11
E 1
