h56238
s 00000/00004/00053
d D 7.5 90/12/16 16:47:23 bostic 7 6
c kernel reorg
e
s 00001/00011/00056
d D 7.4 90/06/28 22:27:52 bostic 6 5
c new copyright notice
e
s 00001/00001/00066
d D 7.3 89/05/09 20:54:57 mckusick 5 4
c eliminate ../h
e
s 00015/00000/00052
d D 7.2 88/09/16 09:37:30 bostic 4 3
c add appropriate copyright notices
e
s 00003/00001/00049
d D 7.1 88/05/21 18:33:10 karels 3 2
c bring up to revision 7 for tahoe release
e
s 00003/00003/00047
d D 1.2 87/12/22 12:33:58 bostic 2 1
c make ANSI C compatible
e
s 00050/00000/00000
d D 1.1 86/11/29 12:09:54 sam 1 0
c date and time created 86/11/29 12:09:54 by sam
e
u
U
t
T
I 1
D 3
/*	%M%	%I%	%E%	*/
E 3
I 3
/*
I 4
 * Copyright (c) 1986 The Regents of the University of California.
 * All rights reserved.
 *
D 6
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Berkeley.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
 * %sccs.include.redist.c%
E 6
 *
E 4
 *	%W% (Berkeley) %G%
 */
E 3

#ifndef _PSREG_
#define _PSREG_
/*
 * PS300 definitions.
 */
D 7
#ifndef KERNEL
E 7
#include <sys/ioctl.h>
D 7
#else
D 5
#include "../h/ioctl.h"
E 5
I 5
#include "ioctl.h"
E 5
#endif
E 7

struct  pslookup {
        int     pl_len;                 /* length of name string */
        char    *pl_name;               /* address of name string */
        u_long  pl_addr;                /* symbol's address */
};

/*
 * Maximum string which may be supplied for lookup.
 */
#define PS_MAXNAMELEN   256             /* must be <= PSMAXDMA */

/*
 * When doing physical i/o, one may specify the address
 * and whether or not refresh sync should is required with
 * a null iovec descriptor (iov_len = 0).
 */
#define PSIO_SYNC       1               /* do physical write w/ refresh sync */

/*
 * Ioctl requests.
 */
D 2
#define PSIOGETERROR    _IOR(p, 0, int)                 /* get last error */
#define PSIOLOOKUP      _IOWR(p, 1, struct pslookup)    /* do name lookup */
#define PSIORWLOGICAL   _IOWR(p, 2, int)                /* set i/o mode */
E 2
I 2
#define PSIOGETERROR    _IOR('p', 0, int)                 /* get last error */
#define PSIOLOOKUP      _IOWR('p', 1, struct pslookup)    /* do name lookup */
#define PSIORWLOGICAL   _IOWR('p', 2, int)                /* set i/o mode */
E 2

/*
 * Error codes returned by PSIOGETERROR are either
 * returned by the PS300 or, from the list below,
 * generated by the device driver.
 */
#define PSERROR_DIOTIMO         1       /* timeout during dioread/diowrite */
#define PSERROR_INVALBC         2       /* invalid byte count for read/write */
#define PSERROR_BADADDR         3       /* invalid address for read/write */
#define PSERROR_BADCMD          4       /* invalid command in ikstart */
#define PSERROR_NAMETIMO        5       /* timeout during nameaddr dioread */
#define PSERROR_CMDTIMO         6       /* operation timed out */
#endif
E 1
