h27401
s 00002/00002/00072
d D 8.1 93/06/06 14:53:07 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00003/00071
d D 5.5 93/03/23 18:57:38 cael 9 8
c update .Os and history from .Ud to .Bx 4.4
e
s 00029/00029/00045
d D 5.4 91/07/26 19:08:17 cael 8 7
c mdoc version three
e
s 00002/00000/00072
d D 5.3 91/03/14 00:19:30 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00072
d R 5.3 91/03/13 20:34:09 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00001/00071
d D 5.2 91/03/07 15:17:31 marc 5 4
c refer to strerror() instead of sys_errlist
e
s 00036/00044/00036
d D 5.1 90/12/28 19:17:31 bostic 4 3
c KNF, lint, document all options, make man page consistent
e
s 00071/00043/00009
d D 1.3 90/07/24 22:46:33 cael 3 2
c .Xr botch fix
e
s 00007/00004/00045
d D 1.2 90/06/29 00:33:02 marc 2 1
c output file is ktrace.out; add -R
e
s 00049/00000/00000
d D 1.1 89/03/24 14:01:47 marc 1 0
c date and time created 89/03/24 14:01:47 by marc
e
u
U
t
T
I 1
D 3
.TH KDUMP 1
.SH NAME
.I kdump
\- display kernel trace data
.SH SYNOPSIS
.B kdump
[
D 2
.B -dnlT
E 2
I 2
.B -dnlTR
E 2
]
.B -f 
trfile ]
[
.B -t 
trstr ]
.SH DESCRIPTION
.I Kdump
displays kernel trace files produced with ktrace(1) in a human readable format.
D 2
Without the -f flag, kdump reads the file "ktrace.data" in the current
E 2
I 2
Without the -f flag, kdump reads the file "ktrace.out" in the current
E 3
I 3
D 10
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
.\"
D 8
.\"     %W% (Berkeley) %G%
E 8
I 8
.\"	%W% (Berkeley) %G%
E 8
.\"
I 7
D 8
.Vx
.Vx
E 8
E 7
.Dd %Q%
.Dt KDUMP 1
I 8
D 9
.Os
E 9
I 9
.Os BSD 4.4
E 9
E 8
.Sh NAME
.Nm kdump
.Nd display kernel trace data
.Sh SYNOPSIS
.Nm kdump
D 4
.Op Fl dnlTR
.Op Fl f Ar trfile
.Op Fl t Ar trstr
E 4
I 4
.Op Fl dnlRT
.Op Fl f Ar file
.Op Fl m Ar maxdata
.Op Fl t Op cnis
E 4
.Sh DESCRIPTION
.Nm Kdump
D 4
displays kernel trace files produced with
E 4
I 4
displays the kernel trace files produced with
E 4
.Xr ktrace 1
D 4
in a human readable format.
Without the
.Fl f
flag,
.Nm kdump
reads the file
.Sq Pa ktrace.out
in the current
E 3
E 2
directory.
E 4
I 4
in human readable format.
D 8
By default, the file ``ktrace.out'' in the current directory is displayed.
E 8
I 8
By default, the file
.Pa ktrace.out
in the current directory is displayed.
E 8
E 4
D 3
Following is a description of the options:
.br
.TP
.B \-d
E 3
I 3
.Pp
D 4
Options:
E 4
I 4
The options are as follows:
E 4
D 8
.Tw Fl
.Tp Fl d
E 8
I 8
.Bl -tag -width Fl
.It Fl d
E 8
E 3
Display all numbers in decimal.
I 4
D 8
.Tc Fl f
.Ws
.Ar file
.Cx
Display the specified file instead of ``ktrace.out''.
.Tp Fl l
E 8
I 8
.It Fl f Ar file 
Display the specified file instead of
.Pa ktrace.out .
.It Fl l
E 8
Loop reading the trace file, once the end-of-file is reached, waiting for
more data.
D 8
.Tc Fl m
.Ws
.Ar maxdata
.Cx
E 8
I 8
.It Fl m Ar maxdata 
E 8
Display at most
.Ar maxdata
D 8
bytes when decoding I/O.
E 4
D 3
.TP
.B \-n
Suppress ad hoc translations.  Normally kdump tries to decode many
E 3
I 3
.Tp Fl n
E 8
I 8
bytes when decoding
.Tn I/O .
.It Fl n
E 8
D 4
Suppress ad hoc translations.  Normally
E 4
I 4
Suppress ad hoc translations.
Normally
E 4
.Nm kdump
D 4
tries to decode many
E 3
system calls into a more human readable format.  For example, ioctl
values are replaced with the macro name and errno values are replaced
D 3
with the sys_errlist string.  Suppressing this feature yields a more consistent
E 3
I 3
with the
E 4
I 4
tries to decode many system calls into a more human readable format.
D 8
For example, ioctl values are replaced with the macro name and errno
E 8
I 8
For example,
.Xr ioctl 2
values are replaced with the macro name and
.Va errno
E 8
values are replaced with the
E 4
D 5
.Li sys_errlist
E 5
I 5
D 8
.Li strerror()
E 8
I 8
.Xr strerror 3
E 8
E 5
D 4
string.  Suppressing this feature yields a more consistent
E 3
D 2
output format and is more amenable to further processing.
E 2
I 2
output format and is easily amenable to further processing.
E 2
D 3
.TP
.B \-l
E 3
I 3
.Tp Fl l
E 3
Loop reading end-of-file.
D 3
.TP
.B \-T
E 3
I 3
.Tp Fl T
E 3
D 2
Display timestamps.
E 2
I 2
Display absolute timestamps for each entry (seconds since epoch).
E 4
I 4
string.
Suppressing this feature yields a more consistent output format and is
easily amenable to further processing.
E 4
D 3
.TP
.B \-R
E 3
I 3
D 8
.Tp Fl R
E 8
I 8
.It Fl R
E 8
E 3
Display relative timestamps (time since previous entry).
I 4
D 8
.Tp Fl T
E 8
I 8
.It Fl T
E 8
Display absolute timestamps for each entry (seconds since epoch).
E 4
E 2
D 3
.TP
.B \-t trstr
See -t in ktrace(1).
.TP
.B \-f trfile
See -t in ktrace(1).
.TP
.B \-m maxdata
Display at most \fBmaxdata\fP bytes when decoding i/o.
.SH SEE ALSO
.IR ktrace(1)
E 3
I 3
D 8
.Tc Fl t
.Ws
D 4
.Ar trstr
E 4
I 4
.Ar cnis
E 4
.Cx
E 8
I 8
.It Fl t Ar cnis 
E 8
D 4
See
E 4
I 4
See the
E 4
.Fl t
D 4
in
E 4
I 4
option of
E 4
.Xr ktrace 1 .
D 4
.Tc Fl f
.Ws
.Ar trfile
.Cx
See
.Fl t
in
.Xr ktrace 1 .
.Tc Fl m
.Ws
.Ar maxdata
.Cx
Display at most
.Ar maxdata
bytes when decoding i/o.
E 4
D 8
.Tp
E 8
I 8
.El
E 8
.Sh SEE ALSO
.Xr ktrace 1
E 3
D 4
\- enable kernel process tracing.
E 4
I 3
.Sh HISTORY
D 8
4.4 BSD.
E 8
I 8
The
.Nm kdump
D 9
command is
.Ud .
E 9
I 9
command appears in
.Bx 4.4 .
E 9
E 8
E 3
E 1
