h61125
s 00001/00000/00122
d D 8.3 94/06/01 20:44:36 ah 9 8
c page breaks for 4.4BSD manuals
e
s 00001/00001/00121
d D 8.2 93/12/11 23:43:04 mckusick 8 7
c copyediting for Usenix manuals
e
s 00002/00002/00120
d D 8.1 93/06/04 18:58:35 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00062/00062/00060
d D 6.5 91/03/16 17:05:28 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00002/00012/00120
d D 6.4 90/06/24 21:22:26 trent 5 4
c new copyright & pathnames (rexecd)
e
s 00017/00006/00115
d D 6.3 88/09/27 22:17:38 bostic 4 3
c Berkeley copyright notice
e
s 00013/00010/00108
d D 6.2 86/05/09 03:30:24 lepreau 3 2
c reality treatment similar to rshd.8c delta 6.2
e
s 00001/00001/00117
d D 6.1 85/04/27 15:41:05 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00118/00000/00000
d D 5.1 85/04/27 15:40:45 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 4
.\"
I 4
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
E 4
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH REXECD 8C "4 March 1983"
E 2
I 2
D 4
.TH REXECD 8C "%Q%"
E 4
I 4
D 6
.TH REXECD 8 "%Q%"
E 4
E 2
.UC 5
.SH NAME
rexecd \- remote execution server
.SH SYNOPSIS
D 5
.B /etc/rexecd
E 5
I 5
.B rexecd
E 5
.SH DESCRIPTION
.I Rexecd
E 6
I 6
.Dd %Q%
.Dt REXECD 8
.Os BSD 4.2
.Sh NAME
.Nm rexecd
.Nd remote execution server
.Sh SYNOPSIS
.Nm rexecd
.Sh DESCRIPTION
.Nm Rexecd
E 6
is the server for the 
D 4
.IR rexec (3X)
E 4
I 4
D 6
.IR rexec (3)
E 6
I 6
.Xr rexec 3
E 6
E 4
routine.  The server provides remote execution facilities
D 3
with authentication based on user names and encrypted
E 3
I 3
with authentication based on user names and
E 3
passwords.
D 6
.PP
.I Rexecd
E 6
I 6
.Pp
.Nm Rexecd
E 6
listens for service requests at the port indicated in
the ``exec'' service specification; see
D 6
.IR services (5).
E 6
I 6
.Xr services 5 .
E 6
When a service request is received the following protocol
is initiated:
D 6
.IP 1)
E 6
I 6
.Bl -enum
.It
E 6
The server reads characters from the socket up
D 6
to a null (`\e0') byte.  The resultant string is
interpreted as an ASCII number, base 10.
.IP 2)
E 6
I 6
to a NUL
.Pq Ql \e0
byte.  The resultant string is
interpreted as an
.Tn ASCII
number, base 10.
.It 
E 6
If the number received in step 1 is non-zero,
it is interpreted as the port number of a secondary
stream to be used for the 
D 6
.BR stderr .
E 6
I 6
.Em stderr .
E 6
A second connection is then created to the specified
port on the client's machine.
D 6
.IP 3)
A null terminated user name of at most 16 characters
E 6
I 6
.It
A NUL terminated user name of at most 16 characters
E 6
is retrieved on the initial socket.
D 6
.IP 4)
D 3
A null terminated, encrypted, password of at most
E 3
I 3
A null terminated, unencrypted password of at most
E 6
I 6
.It
A NUL terminated, unencrypted password of at most
E 6
E 3
16 characters is retrieved on the initial socket.  
D 6
.IP 5)
A null terminated command to be passed to a
E 6
I 6
.It
A NUL terminated command to be passed to a
E 6
shell is retrieved on the initial socket.  The length of
the command is limited by the upper bound on the size of
the system's argument list.  
D 6
.IP 6)
.I Rexecd
E 6
I 6
.It
.Nm Rexecd
E 6
then validates the user as is done at login time
and, if the authentication was successful, changes
to the user's home directory, and establishes the user
and group protections of the user.
If any of these steps fail the connection is
aborted with a diagnostic message returned.
D 6
.IP 7)
D 3
A null byte is returned on the connection associated
with the
.B stderr 
E 3
I 3
A null byte is returned on the initial socket
E 6
I 6
.It
A NUL byte is returned on the initial socket
E 6
E 3
and the command line is passed to the normal login
shell of the user.  The
shell inherits the network connections established
by
D 6
.IR rexecd .
.SH DIAGNOSTICS
E 6
I 6
.Nm rexecd .
.El
.Sh DIAGNOSTICS
E 6
D 3
All diagnostic messages are returned on the connection
associated with the
.BR stderr ,
E 3
I 3
Except for the last one listed below,
all diagnostic messages are returned on the initial socket,
E 3
after which any network connections are closed.
An error is indicated by a leading byte with a value of
1 (0 is returned in step 7 above upon successful completion
of all the steps prior to the command execution).
D 6
.PP
.B ``username too long''
.br
E 6
I 6
.Pp
.Bl -tag -width Ds
.It Sy username too long
E 6
The name is
longer than 16 characters.
D 6
.PP
.B ``password too long''
.br
E 6
I 6
.It Sy password too long
E 6
The password is longer than 16 characters.
D 6
.PP
.B ``command too long ''
.br
E 6
I 6
.It Sy command too long
E 6
The command line passed exceeds the size of the argument
list (as configured into the system).
D 6
.PP
.B ``Login incorrect.''
.br
E 6
I 6
.It Sy Login incorrect.
E 6
No password file entry for the user name existed.
D 6
.PP
.B ``Password incorrect.''
.br
E 6
I 6
.It Sy Password incorrect.
E 6
D 8
The wrong was password supplied.
E 8
I 8
The wrong password was supplied.
I 9
.ne 1i
E 9
E 8
D 6
.PP
.B ``No remote directory.''
.br
E 6
I 6
.It Sy \&No remote directory.
E 6
The 
D 6
.I chdir
E 6
I 6
.Xr chdir
E 6
command to the home directory failed.
D 6
.PP
.B ``Try again.''
.br
E 6
I 6
.It Sy Try again.
E 6
A
D 6
.I fork
E 6
I 6
.Xr fork
E 6
by the server failed.
D 6
.PP
D 3
.B ``/bin/sh: ...''
E 3
I 3
.B ``<shellname>: ...''
E 3
.br
E 6
I 6
.It Sy <shellname>: ...
E 6
The user's login shell could not be started.
I 3
This message is returned
on the connection associated with the
D 6
.BR stderr ,
E 6
I 6
.Em stderr ,
E 6
and is not preceded by a flag byte.
D 6
.SH SEE ALSO
D 4
rexec(3X)
E 4
I 4
rexec(3)
E 4
E 3
.SH BUGS
E 6
I 6
.El
.Sh SEE ALSO
.Xr rexec 3
.Sh BUGS
E 6
Indicating ``Login incorrect'' as opposed to ``Password incorrect''
is a security breach which allows people to probe a system for users
with null passwords.
D 6
.PP
E 6
I 6
.Pp
E 6
D 3
A facility to allow all data exchanges to be encrypted should be
E 3
I 3
A facility to allow all data and password exchanges to be encrypted should be
E 3
present.
I 6
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 6
E 1
