h14457
s 00002/00002/00056
d D 8.1 93/06/06 14:04:47 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00055/00034/00003
d D 6.4 91/05/04 15:33:43 cael 6 5
c mdoc version three/bsd copyright
e
s 00001/00001/00036
d D 6.3 90/06/24 22:29:06 trent 5 4
c new pathname (quot)
e
s 00002/00007/00035
d D 6.2 88/04/18 21:41:38 bostic 4 3
c rip out mention of default file system, list options in synopsis
e
s 00001/00001/00041
d D 6.1 85/04/27 13:41:03 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00003/00041
d D 5.1 85/04/27 13:40:43 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00044/00000/00000
d D 4.1 85/04/27 13:40:26 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 7
.\" Copyright (c) 1980, 1991 Regents of the University of California.
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 6
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
D 2
.TH QUOT 8 "4/1/81"
E 2
I 2
D 3
.TH QUOT 8  "4 February 1983"
E 3
I 3
D 6
.TH QUOT 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
quot \- summarize file system ownership
.SH SYNOPSIS
D 5
.B /etc/quot
E 5
I 5
.B quot
E 5
D 4
[ option ] ...
[ filesystem ]
E 4
I 4
[ -ncf ] [ filesystem ... ]
E 4
.SH DESCRIPTION
.I Quot
prints the number of blocks in the named
.I filesystem
currently owned by each user.
If no 
.I filesystem
D 4
is named, a default name is assumed.
E 4
I 4
is named, the file systems listed in \fI/etc/fstab\fP are used.
E 6
I 6
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt QUOT 8
.Os BSD 4
.Sh NAME
.Nm quot
.Nd display total block usage per user for a file system
.Sh SYNOPSIS
.Nm quot
.Op Fl ncf
.Op Ar filesystem Ar ...
.Sh DESCRIPTION
The
.Nm quot
command
displays the total count of blocks owned by a user for the filesystem
.Ar filesystem .
If the filesystem option
.Ar filesystem
is not specified,
the file systems listed in
.Pa /etc/fstab
are used.
E 6
E 4
The following options are available:
D 6
.TP
.B \-n
Cause the pipeline
.B "ncheck filesystem | sort +0n | quot \-n filesystem
to produce a list of all files and their owners.
.TP
.B \-c
Print three columns giving file size in blocks, number of
files of that size, and cumulative total of blocks
in that size or smaller file.
.TP
.B \-f
Print count of number of files as well as space owned by each user.
D 4
.SH FILES
Default file system varies with system.
.br
/etc/passwd	to get user names
E 4
.SH "SEE ALSO"
ls(1), du(1)
E 6
I 6
.Bl -tag -width Ds
.It Fl c
Display information on file size and block usage. The file sizes
are listed in the first column, the second column contains a count
of how many files of that size were found and the third column
lists the cumulative block usage for the displayed size and all smaller
files.
.It Fl f
For each user,
the number of files (inodes) owned is displayed in addition
to the block usage.
.It Fl n
A list sorted by block usage is displayed.
This is the result of
.Nm quot
executing the following command:
.Bd -literal -offset indent
ncheck filesystem \&| sort +0n \&| quot \-n filesystem
.Ed
.El
.Sh SEE ALSO
.Xr ls 1 ,
.Xr du 1
.Sh HISTORY
The
.Nm
command appeared in
.At 32v .
E 6
D 2
.SH BUGS
Holes in files are counted as if they actually occupied space.
E 2
E 1
