h33005
s 00002/00002/00270
d D 8.2 94/04/18 21:01:12 bostic 18 17
c spell
e
s 00002/00002/00270
d D 8.1 93/06/06 15:36:48 bostic 17 16
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00072/00126/00200
d D 5.15 91/07/29 17:27:38 cael 16 15
c mdoc version three
e
s 00002/00000/00324
d D 5.14 91/03/14 00:22:49 cael 15 13
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00324
d R 5.14 91/03/13 20:35:37 cael 14 13
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00024/00014/00300
d D 5.13 90/07/24 22:48:54 cael 13 12
c .Xr botch fix
e
s 00205/00122/00109
d D 5.12 90/06/11 05:57:09 cael 12 11
c converted man page
e
s 00005/00002/00226
d D 5.11 88/12/28 17:08:07 bostic 11 10
c exit on end-of-file if file shorter than a screen, regardless
e
s 00002/00001/00226
d D 5.10 88/12/06 18:25:09 bostic 10 9
c make '' default to file beginning if no large movements yet
e
s 00001/00004/00226
d D 5.9 88/12/06 17:33:47 bostic 9 8
c remove -p (terse prompts)
e
s 00000/00001/00230
d D 5.8 88/11/27 17:57:23 bostic 8 7
c delete mention of ^Y; currently don't allow ^Y or ^E.
e
s 00009/00007/00222
d D 5.7 88/11/26 12:03:54 bostic 7 6
c compress CR-LF to LF by default; -u flag prints the CR as "^M"
e
s 00007/00003/00222
d D 5.6 88/11/22 17:41:29 bostic 6 5
c =/^G show total bytes now; document may not always work
e
s 00109/00455/00116
d D 5.5 88/11/22 16:51:33 bostic 5 4
c 
e
s 00000/00014/00571
d D 5.4 88/09/23 14:12:53 bostic 4 3
c remove mention of  lesskey
e
s 00005/00004/00580
d D 5.3 88/07/25 12:04:42 bostic 3 2
c update copyright notice
e
s 00001/00029/00583
d D 5.2 88/07/22 13:24:40 bostic 2 1
c rip out -lL options; no shell escapes, that was job control is for
e
s 00612/00000/00000
d D 5.1 88/07/21 18:52:47 bostic 1 0
c distribution by Mark Nudleman
e
u
U
t
T
I 1
D 12
.\"
E 12
I 12
D 17
.\" Copyright (c) 1988, 1990 The Regents of the University of California.
E 12
.\" Copyright (c) 1988 Mark Nudleman
E 17
I 17
.\" Copyright (c) 1988, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 17
D 12
.\" Copyright (c) 1988 Regents of the University of California.
E 12
.\" All rights reserved.
.\"
D 3
.\" This code is derived from software contributed to Berkeley by
.\" Mark Nudleman.
.\"
E 3
D 12
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
D 3
.\" by the University of California, Berkeley.  The name of the
E 3
I 3
.\" by Mark Nudleman and the University of California, Berkeley.  The
.\" name of Mark Nudleman or the
E 3
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 12
I 12
D 16
.\" %sccs.include.redist.man%
E 16
I 16
.\" %sccs.include.redist.roff%
E 16
E 12
.\"
D 12
.\"	%W% (Berkeley) %G%
E 12
I 12
D 16
.\"     %W% (Berkeley) %G%
E 16
I 16
.\"	%W% (Berkeley) %G%
E 16
E 12
.\"
I 15
D 16
.Vx
.Vx
E 16
E 15
D 5
.TH LESS 1
E 5
I 5
D 12
.TH MORE 1
E 5
.SH NAME
D 5
less \- opposite of more
E 5
I 5
more \- file perusal filter for crt viewing
E 5
.SH SYNOPSIS
D 5
.B "less [-[+]aABcCdeEimMnqQuUsw] [-b\fIN\fB] [-h\fIN\fB] [-x\fIN\fB] [-[z]\fIN\fB]"
.br
D 2
.B "     [-P[mM=]\fIstring\fB] [-[lL]\fIlogfile\fB] [+\fIcmd\fB]"
E 2
I 2
.B "     [-P[mM=]\fIstring\fB] [+\fIcmd\fB]"
E 2
.br
.B "     [-t\fItag\fB] [\fIfilename\fB]..."
E 5
I 5
D 9
.B "more [-ceinpus] [-t tag] [-x tabs] [-/ pattern] [-#] [file ...]"
E 9
I 9
.B "more [-ceinus] [-t tag] [-x tabs] [-/ pattern] [-#] [file ...]"
E 9
E 5
.SH DESCRIPTION
D 5
.I Less
is a program similar to 
E 5
I 5
.I More
E 12
I 12
.Dd %Q%
.Dt MORE 1
I 16
.Os
E 16
.Sh NAME
.Nm more
.Nd file perusal filter for crt viewing
.Sh SYNOPSIS
.Nm more
.Op Fl ceinus
.Op Fl t Ar tag
.Op Fl x Ar tabs
.Op Fl / Ar pattern
.Op Fl #
D 16
.Ar
E 16
I 16
.Op Ar
E 16
.Sh DESCRIPTION
.Nm More
E 12
is a filter for paging through text one screenful at a time.  It
uses
D 12
.IR termcap (3)
E 12
I 12
.Xr termcap  3
E 12
so it can run on a variety of terminals.  There is even limited support
for hardcopy terminals.  (On a hardcopy terminal, lines which should be
printed at the top of the screen are prefixed with an up-arrow.)
D 12
.I File
E 12
I 12
.Ar File
E 12
may be a single dash (``-''), implying stdin.
D 12
.SH OPTIONS
E 12
I 12
.Sh OPTIONS
E 12
Command line options are described below.
D 12
Options are also taken from the environment variable "MORE"
E 12
I 12
Options are also taken from the environment variable
.Ev MORE
E 12
(make sure to precede them with a dash (``-'')) but command
line options will override them.
D 12
.IP -c
Normally, 
E 5
.I more
E 12
I 12
D 16
.Tw Fl
.Tp Fl c
E 16
I 16
.Bl -tag -width flag
.It Fl c
E 16
Normally,
.Nm more
E 12
D 5
(1), but which allows backwards movement
in the file as well as forward movement.
Also,
.I less
does not have to read the entire input file before starting,
so with large input files it starts up faster than text editors like
.I vi
(1).
.I Less
uses termcap (or terminfo on some systems),
so it can run on a variety of terminals.
There is even limited support for hardcopy terminals.
(On a hardcopy terminal, lines which should be printed at the top
of the screen are prefixed with an up-arrow.)
.PP
Commands are based on both
E 5
I 5
will repaint the screen by scrolling from the bottom of the screen.
D 12
If the -c option is set, when
.I more 
E 12
I 12
If the
.Fl c
option is set, when
.Nm more
E 12
needs to change the entire display, it will paint from the top line down.
D 12
.IP -e
E 12
I 12
D 16
.Tp Fl e
E 16
I 16
.It Fl e
E 16
E 12
D 11
Normally
E 11
I 11
Normally, if displaying a single file,
E 11
E 5
D 12
.I more
D 5
and
.I vi.
Commands may be preceeded by a decimal number, 
called N in the descriptions below.
The number is used by some commands, as indicated.

E 5
I 5
exits as soon as it reaches end-of-file.  The -e option tells more to
E 12
I 12
.Nm more
exits as soon as it reaches end-of-file.  The
.Fl e
option tells more to
E 12
D 11
exit the second time it reaches end-of-file.
E 11
I 11
exit if it reaches end-of-file twice without an intervening operation.
If the file is shorter than a single screen
D 12
.I more
E 12
I 12
.Nm more
E 12
will exit at end-of-file regardless.
E 11
D 12
.IP -i
The -i option causes searches to ignore case; that is,
E 12
I 12
D 16
.Tp Fl i
E 16
I 16
.It Fl i
E 16
The
.Fl i
option causes searches to ignore case; that is,
E 12
uppercase and lowercase are considered identical.
D 12
.IP -n
The -n flag suppresses line numbers.
E 12
I 12
D 16
.Tp Fl n
E 16
I 16
.It Fl n
E 16
The
.Fl n
flag suppresses line numbers.
E 12
The default (to use line numbers) may cause
D 12
.I more
E 12
I 12
.Nm more
E 12
to run more slowly in some cases, especially with a very large input file.
D 12
Suppressing line numbers with the -n flag will avoid this problem.
Using line numbers means: the line number will be displayed in the 
E 12
I 12
Suppressing line numbers with the
.Fl n
flag will avoid this problem.
Using line numbers means: the line number will be displayed in the
E 12
D 13
= command, and the v command will pass the current line number to the editor.
E 13
I 13
.Cm =
command, and the
.Cm v
command will pass the current line number to the editor.
E 13
D 9
.IP -p
The -p option gives you a colon (``:'') for a prompt, rather than
the more verbose traditional prompt.
E 9
D 12
.IP -s
The -s option causes
E 12
I 12
D 16
.Tp Fl s
E 16
I 16
.It Fl s
E 16
The
.Fl s
option causes
E 12
consecutive blank lines to be squeezed into a single blank line.
D 12
.IP -t
The -t option, followed immediately by a tag, will edit the file
E 12
I 12
D 16
.Tp Fl t
E 16
I 16
.It Fl t
E 16
The
.Fl t
option, followed immediately by a tag, will edit the file
E 12
containing that tag.  For more information, see the
D 12
.IR ctags (1)
E 12
I 12
.Xr ctags  1
E 12
command.
D 12
.IP -u
E 12
I 12
D 16
.Tp Fl u
E 16
I 16
.It Fl u
E 16
E 12
D 7
If the -u option is given, backspaces are always printed as the two
character sequence ``^H''; otherwise, backspaces which appear adjacent
to an underscore character are treated specially: the underlined text
is displayed using the terminal's hardware underlining capability.
Also, backspaces which appear between two identical characters are
treated specially: the overstruck text is printed using the terminal's
hardware boldface capability.
E 7
I 7
By default,
D 12
.I more
E 12
I 12
.Nm more
E 12
D 16
treats backspaces and CR-LF sequences specially.  Backspaces which appear
E 16
I 16
treats backspaces and
.Dv CR-LF
sequences specially.  Backspaces which appear
E 16
adjacent to an underscore character are displayed as underlined text.
Backspaces which appear between two identical characters are displayed
D 16
as emboldened text.  CR-LF sequences are compressed to a single linefeed
E 16
I 16
as emboldened text.
.Dv CR-LF
sequences are compressed to a single linefeed
E 16
D 12
character.  The -u option causes backspaces to always be displayed as
E 12
I 12
character.  The
.Fl u
option causes backspaces to always be displayed as
E 12
D 16
control characters, i.e. as the two character sequence ``^H'', and CR-LF
E 16
I 16
control characters, i.e. as the two character sequence ``^H'', and
.Dv CR-LF
E 16
to be left alone.
E 7
D 12
.IP -x
The -x option sets tab stops every
.I N
E 12
I 12
D 16
.Tp Fl x
E 16
I 16
.It Fl x
E 16
The
.Fl x
option sets tab stops every
.Ar N
E 12
positions. The default for
D 12
.I N
E 12
I 12
.Ar N
E 12
is 8.
D 12
.IP -/
The -/ option specifies a string that will be searched for before
E 12
I 12
D 16
.Tp Fl \&/
E 16
I 16
.It Fl /
E 16
The
D 16
.Fl \&/
E 16
I 16
.Fl /
E 16
option specifies a string that will be searched for before
E 12
each file is displayed.
E 5
D 12
.SH COMMANDS
E 12
I 12
.Sh COMMANDS
E 12
I 5
Interactive commands for
D 12
.I more
E 12
I 12
.Nm more
E 12
are based on
D 12
.IR vi (1).
E 12
I 12
.Xr vi  1  .
E 12
D 18
Some commands may be preceeded by a decimal number, called N in the
E 18
I 18
Some commands may be preceded by a decimal number, called N in the
E 18
descriptions below.
E 5
In the following descriptions, ^X means control-X.
D 5
ESC stands for the ESCAPE key; for example ESC-v means the
two character sequence "ESCAPE", then "v".
.IP H
Help: display a summary of these commands.
E 5
I 5
D 12
.IP h
E 12
I 12
.Pp
D 16
.Tw Ic
.Tp Ic h
E 12
help: display a summary of these commands.
E 16
I 16
.Bl -tag -width Ic
.It Ic h
Help: display a summary of these commands.
E 16
E 5
If you forget all the other commands, remember this one.
D 12
.PP
D 5
.IP "SPACE or f or ^F or ^V"
Scroll forward N lines, default one window (see option -z below).
E 5
I 5
.IP "SPACE or f or ^F"
E 12
I 12
D 16
.Tp Cx Ic SPACE
.Ws
.Cx or
.Ws
E 16
I 16
.It Xo
.Ic SPACE
.No or
E 16
.Ic f
D 16
.Ws
.Cx or
.Ws
E 16
I 16
.No or
E 16
.Ic \&^F
D 16
.Cx
E 16
I 16
.Xc
E 16
E 12
Scroll forward N lines, default one window.
E 5
If N is more than the screen size, only the final screenful is displayed.
D 5
Warning: some systems use ^V as a special literalization character.
E 5
D 12
.PP
D 5
.IP "b or ^B or ESC-v"
E 5
I 5
.IP "b or ^B"
E 12
I 12
D 16
.Tp Cx Ic b
.Ws
.Cx or
.Ws
.Ic \&^B
.Cx
E 16
I 16
.It Ic b No or Ic \&^B
E 16
E 12
E 5
Scroll backward N lines, default one window (see option -z below).
If N is more than the screen size, only the final screenful is displayed.
D 12
.PP
D 5
.IP "RETURN or ^N or e or ^E or j or ^J"
E 5
I 5
.IP "j or RETURN"
E 12
I 12
D 16
.Tp Cx Ic j
.Ws
.Cx or
.Ws
.Ic RETURN
.Cx
E 16
I 16
.It Ic j No or Ic RETURN
E 16
E 12
E 5
Scroll forward N lines, default 1.
The entire N lines are displayed, even if N is more than the screen size.
D 12
.PP
D 5
.IP "y or ^Y or ^P or k or ^K"
E 5
I 5
.IP "k"
E 12
I 12
D 16
.Tp Ic k
E 16
I 16
.It Ic k
E 16
E 12
E 5
Scroll backward N lines, default 1.
The entire N lines are displayed, even if N is more than the screen size.
D 8
Warning: some systems use ^Y as a special job control character.
E 8
D 12
.PP
.IP "d or ^D"
E 12
I 12
D 13
.Tp Ic d
E 13
I 13
D 16
.Tp Cx Ic d
E 13
.Ws
.Cx or
.Ws
.Ic \&^D
.Cx
E 16
I 16
.It Ic d No or Ic \&^D
E 16
E 12
Scroll forward N lines, default one half of the screen size.
D 12
If N is specified, it becomes the new default for 
E 12
I 12
If N is specified, it becomes the new default for
E 12
subsequent d and u commands.
D 12
.PP
.IP "u or ^U"
E 12
I 12
D 13
.Tp Ic u
E 13
I 13
D 16
.Tp Cx Ic u
E 13
.Ws
.Cx or
.Ws
.Ic \&^U
.Cx
E 16
I 16
.It Ic u No or Ic \&^U
E 16
E 12
Scroll backward N lines, default one half of the screen size.
D 12
If N is specified, it becomes the new default for 
E 12
I 12
If N is specified, it becomes the new default for
E 12
subsequent d and u commands.
D 12
.PP
D 5
.IP "r or ^R or ^L"
Repaint the screen.
.PP
.IP R
Repaint the screen, discarding any buffered input.
Useful if the file is changing while it is being viewed.
.PP
.IP "g or < or ESC-<"
E 5
I 5
.IP "g"
E 12
I 12
D 16
.Tp Ic g
E 16
I 16
.It Ic g
E 16
E 12
E 5
Go to line N in the file, default 1 (beginning of file).
D 5
(Warning: this may be slow if N is large.)
E 5
D 12
.PP
D 5
.IP "G or > or ESC->"
E 5
I 5
.IP "G"
E 12
I 12
D 16
.Tp Ic G
E 16
I 16
.It Ic G
E 16
E 12
E 5
Go to line N in the file, default the end of the file.
D 5
(Warning: this may be slow if N is large,
or if N is not specified and
standard input, rather than a file, is being read.)
E 5
D 12
.PP
.IP "p or %"
E 12
I 12
D 13
.Tp Ic p
E 13
I 13
D 16
.Tp Cx Ic p
E 13
.Ws
.Cx or
.Ws
.Ic \&%
.Cx
E 16
I 16
.It Ic p No or Ic \&%
E 16
E 12
D 5
Go to a position N percent into the file.
N should be between 0 and 100.
(This works if standard input is being read, but only if
.I less
has already read to the end of the file.
It is always fast, but not always useful.)
E 5
I 5
Go to a position N percent into the file.  N should be between 0
and 100.  (This works if standard input is being read, but only if
D 12
.I more
E 12
I 12
.Nm more
E 12
has already read to the end of the file.  It is always fast, but
not always useful.)
E 5
D 12
.PP
I 5
.IP "r or ^L"
E 12
I 12
D 13
.Tp Ic r
E 13
I 13
D 16
.Tp Cx Ic r
E 13
.Ws
.Cx or
.Ws
.Ic \&^L
.Cx
E 16
I 16
.It Ic r No or Ic \&^L
E 16
E 12
Repaint the screen.
D 12
.PP
.IP "R"
E 12
I 12
D 16
.Tp Ic R
E 16
I 16
.It Ic R
E 16
E 12
Repaint the screen, discarding any buffered input.
Useful if the file is changing while it is being viewed.
D 12
.PP
E 5
.IP m
Followed by any lowercase letter, 
E 12
I 12
D 16
.Tp Ic m
E 16
I 16
.It Ic m
E 16
Followed by any lowercase letter,
E 12
marks the current position with that letter.
D 12
.PP
.IP "'"
E 12
I 12
D 16
.Tp Ic \&\'
E 16
I 16
.It Ic \&'
E 16
E 12
(Single quote.)
Followed by any lowercase letter, returns to the position which
was previously marked with that letter.
D 18
Followed by another single quote, returns to the postion at
E 18
I 18
Followed by another single quote, returns to the position at
E 18
D 10
which the last "large" movement command was executed.
E 10
I 10
which the last "large" movement command was executed, or the
beginning of the file if no such movements have occurred.
E 10
All marks are lost when a new file is examined.
D 12
.PP
D 5
.IP "^X^X"
Same as single quote.
.PP
E 5
.IP /pattern
E 12
I 12
D 16
.Tp Cx Ic \&/
.Ar pattern
.Cx
E 16
I 16
.It Ic \&/ Ns Ar pattern
E 16
E 12
Search forward in the file for the N-th line containing the pattern.
N defaults to 1.
The pattern is a regular expression, as recognized by
D 12
.I ed.
E 12
I 12
.Xr ed .
E 12
D 5
The search starts at the second line displayed
(but see the -a option, which changes this).
E 5
I 5
The search starts at the second line displayed.
E 5
D 12
.PP
.IP ?pattern
E 12
I 12
D 13
.Tp Cx Ic \&?
E 13
I 13
D 16
.Tp Cx Ic \&\?
E 13
.Ar pattern
.Cx
E 16
I 16
.It Ic \&? Ns Ar pattern
E 16
E 12
Search backward in the file for the N-th line containing the pattern.
The search starts at the line immediately before the top line displayed.
D 12
.PP
.IP /!pattern
E 12
I 12
D 13
.Tp Ic \&/!
E 13
I 13
D 16
.Tp Cx Ic \&/\&!
E 13
.Ar pattern
.Cx
E 16
I 16
.It Ic \&/\&! Ns Ar pattern
E 16
E 12
Like /, but the search is for the N-th line
which does NOT contain the pattern.
D 12
.PP
.IP ?!pattern
E 12
I 12
D 13
.Tp Ic \&?!
E 13
I 13
D 16
.Tp Cx Ic \&?\&!
E 13
.Ar pattern
.Cx
E 16
I 16
.It Ic \&?\&! Ns Ar pattern
E 16
E 12
Like ?, but the search is for the N-th line
which does NOT contain the pattern.
D 12
.PP
.IP n
E 12
I 12
D 16
.Tp Ic n
E 16
I 16
.It Ic n
E 16
E 12
Repeat previous search, for N-th line containing the last pattern
D 16
(or NOT containing the last pattern, if the previous search
E 16
I 16
(or
.Tn NOT
containing the last pattern, if the previous search
E 16
was /! or ?!).
D 12
.PP
.IP "E [filename]"
E 12
I 12
D 16
.Tp Cx Ic E
.Ws
.Op Ar filename
.Cx
E 16
I 16
.It Ic E Ns Op Ar filename
E 16
E 12
Examine a new file.
If the filename is missing, the "current" file (see the N and P commands
below) from the list of files in the command line is re-examined.
If the filename is a pound sign (#), the previously examined file is
re-examined.
D 12
.PP
D 5
.IP "^X^V or :e"
Same as E.
Warning: some systems use ^V as a special literalization character.
.PP
E 5
.IP "N or :n"
E 12
I 12
D 16
.Tp Cx Ic N
.Ws
.Cx or
.Ws
.Ic \&:n
.Cx
E 16
I 16
.It Ic N No or Ic \&:n
E 16
E 12
Examine the next file (from the list of files given in the command line).
If a number N is specified (not to be confused with the command N),
the N-th next file is examined.
D 12
.PP
.IP "P or :p"
E 12
I 12
D 16
.Tp Cx Ic P
.Ws
.Cx or
.Ws
.Ic \&:p
.Cx
E 16
I 16
.It Ic P No or Ic \&:p
E 16
E 12
Examine the previous file.
If a number N is specified, the N-th previous file is examined.
D 12
.PP
D 5
.IP "= or ^G"
Prints some information about the file being viewed,
including its name
and the line number and byte offset of the bottom line being displayed.
If possible, it also prints the length of the file
and the percent of the file above the last displayed line.
E 5
I 5
.IP ":t"
E 12
I 12
D 16
.Tp Ic \&:t
E 16
I 16
.It Ic \&:t
E 16
E 12
Go to supplied tag.
E 5
D 12
.PP
D 5
.IP \-
Followed by one of the command line option letters (see below),
this will change the setting of that option
and print a message describing the new setting.
If the option letter has a numeric value (such as -b or -h),
or a string value (such as -P or -t),
a new value may be entered after the option letter.
.PP
.IP \_
(Underscore.)
Followed by one of the command line option letters (see below),
this will print a message describing the current setting of that option.
The setting of the option is not changed.
.PP
.IP +cmd
Causes the specified cmd to be executed each time a new file is examined.
For example, +G causes 
.I less
to initially display each file starting at the end 
rather than the beginning.
.PP
.IP V
Prints the version number of 
.I less 
being run.
.PP
.IP "q or :q or ZZ"
Exits
.I less.
.PP
E 5
D 2
The following 
two 
commands may or may not be valid, depending on your particular installation.
.PP
E 2
.IP v
E 12
I 12
D 16
.Tp Ic v
E 16
I 16
.It Ic v
E 16
E 12
Invokes an editor to edit the current file being viewed.
D 12
The editor is taken from the environment variable EDITOR,
E 12
I 12
The editor is taken from the environment variable
.Ev EDITOR ,
E 12
D 5
or defaults to "vi".
E 5
I 5
or defaults to
D 12
.IR vi (1).
E 5
.PP
D 2
.IP "! shell-command"
Invokes a shell to run the shell-command given.
A percent sign in the command is replaced by the name of the
current file.  "!!" repeats the last shell command.
"!" with no shell command simply invokes a shell.
In all cases, the shell is taken from the environment variable SHELL,
or defaults to "sh".
.PP
E 2
D 5
.SH OPTIONS
Command line options are described below.
Most options may be changed while
.I less 
is running, via the "\-" command.
E 5
I 5
.IP "= or ^G"
E 12
I 12
.Xr vi  1  .
D 16
.Tp Cx Ic \&=
.Ws
.Cx or
.Ws
.Ic \&^G
.Cx
E 16
I 16
.It Ic \&= No or Ic \&^G
E 16
E 12
These options print out the number of the file currently being displayed
D 6
relative to the total number of files there are to display, the line
number, the byte number, and what percentage of the file has been displayed
if possible.  All of these are for the bottom line on the screen.
E 6
I 6
relative to the total number of files there are to display, the current
line number, the current byte number and the total bytes to display, and
what percentage of the file has been displayed.  If
D 12
.I more
E 12
I 12
.Nm more
E 12
is reading from stdin, or the file is shorter than a single screen, some
of these items may not be available.  Note, all of these items reference
the first byte of the last line displayed on the screen.
E 6
E 5
D 12
.PP
D 5
Options are also taken from the environment variable "LESS".
For example, 
to avoid typing "less -options ..." each time 
.I less 
is invoked, you might tell 
.I csh:
.sp
setenv LESS "-options"
.sp
or if you use 
.I sh:
.sp
LESS="-options"; export LESS
.sp
The environment variable is parsed before the command line,
so command line options override the LESS environment variable.
If an option appears in the LESS variable, it can be reset
to its default on the command line by beginning the command
line option with "-+".
.sp
A dollar sign ($) may be used to signal the end of an option string.
This is important only for options like -P which take a
following string.
.IP -a
Normally, forward searches start just after
the top displayed line (that is, at the second displayed line).
Thus, forward searches include the currently displayed screen.
The -a option causes forward searches to start 
just after the bottom line displayed,
thus skipping the currently displayed screen.
.IP -A
The -A option causes searches to start at the second SCREEN line
displayed, as opposed to the default which is to start at the second
REAL line displayed.
For example, suppose a long real line occupies the first three screen lines.
The default search will start at the second real line (the fourth
screen line), while the -A option
will cause the search to start at the second screen line (in the
midst of the first real line).
(This option is rarely useful.)
.IP -b
The -b\fIn\fR option tells
.I less
to use a non-standard number of buffers.
Buffers are 1K, and normally 10 buffers are used
(except if data in coming from standard input; see the -B option).
The number \fIn\fR specifies a different number of buffers to use.
.IP -B
Normally, when data is coming from standard input,
buffers are allocated automatically as needed, to avoid loss of data.
The -B option disables this feature, so that only the default number
of buffers are used.
If more data is read than will fit in the buffers, the oldest
data is discarded.
.IP -c
Normally, 
.I less 
will repaint the screen by scrolling from the bottom of the screen.
If the -c option is set, when
.I less 
needs to change the entire display, it will paint from the top line down.
.IP -C
The -C option is like -c, but the screen is cleared before it is repainted.
.IP -d
Normally,
.I less
will complain if the terminal is dumb; that is, lacks some important capability,
such as the ability to clear the screen or scroll backwards.
The -d option suppresses this complaint 
(but does not otherwise change the behavior of the program on a dumb terminal).
.IP -e
Normally the only way to exit less is via the "q" command.
The -e option tells less to automatically exit
the second time it reaches end-of-file.
.IP -E
The -E flag causes less to exit the first time it reaches end-of-file.
.IP -h
Normally,
.I less
will scroll backwards when backwards movement is necessary.
The -h option specifies a maximum number of lines to scroll backwards.
If it is necessary to move backwards more than this many lines,
the screen is repainted in a forward direction.
(If the terminal does not have the ability to scroll
backwards, -h0 is implied.)
.IP -i
The -i option causes searches to ignore case; that is,
uppercase and lowercase are considered identical.
Also, text which is overstruck or underlined can be searched for.
D 2
.IP -l
The -l option, followed immediately by a filename,
will cause 
.I less
to copy its input to the named file as it is being viewed.
This applies only when the input file is a pipe,
not an ordinary file.
If the file already exists, less will ask for confirmation before
overwriting it.
.IP -L
The -L option is like -l, but it will overwrite an existing
file without asking for confirmation.
.sp
If no log file has been specified,
the -l and -L options can be used from within less to specify a log file.
Without a file name, they will simply report the name of the log file.
E 2
.IP -m
Normally,
.I less
prompts with a colon.
The -m option causes 
.I less
to prompt verbosely (like 
.I more),
with the percent into the file.
.IP -M
The -M option causes 
.I less
to prompt even more verbosely than 
E 5
I 5
.IP "q or :q or ZZ"
E 12
I 12
D 16
.Tp Cx Ic q
.Ws
.Cx or
.Ws
E 16
I 16
.It Xo
.Ic q
.No or
E 16
.Ic \&:q
D 16
.Ws
.Cx or
.Ws
E 16
I 16
.No or
E 16
.Ic ZZ
D 16
.Cx
E 16
I 16
.Xc
E 16
E 12
Exits
E 5
D 12
.I more.
D 5
.IP -n
The -n flag suppresses line numbers.
The default (to use line numbers) may cause
.I less
to run more slowly in some cases, especially with a very large input file.
Suppressing line numbers with the -n flag will avoid this problem.
Using line numbers means: the line number will be displayed in the verbose
prompt and in the = command,
and the v command will pass the current line number to the editor.
.IP -P
The -P option provides a way to tailor the three prompt
styles to your own preference.
You would normally put this option in your LESS environment
variable, rather than type it in with each less command.
Such an option must either be the last option in the LESS variable,
or be terminated by a dollar sign.
-P followed by a string changes the default (short) prompt to that string.
-Pm changes the medium (-m) prompt to the string, and
-PM changes the long (-M) prompt.
Also, -P= changes the message printed by the = command to the given string.
All prompt strings consist of a sequence of 
letters and special escape sequences.
See the section on PROMPTS for more details.
.IP -q
Normally, if an attempt is made to scroll past the end of the file
or before the beginning of the file, the terminal bell is rung to
indicate this fact.
The -q option tells
.I less
not to ring the bell at such times.
If the terminal has a "visual bell", it is used instead.
.IP -Q
Even if -q is given, 
.I less 
will ring the bell on certain other errors,
such as typing an invalid character.
The -Q option tells
.I less
to be quiet all the time; that is, never ring the terminal bell.
If the terminal has a "visual bell", it is used instead.
.IP -s
The -s option causes
consecutive blank lines to be squeezed into a single blank line.
This is useful when viewing
.I nroff
output.
.IP -t
The -t option, followed immediately by a TAG,
will edit the file containing that tag.
For this to work, there must be a file called "tags" in the
current directory, which was previously built by the 
.I ctags
(1) command.
This option may also be specified from within less 
(using the \- command) as a way of examining a new file.
.IP -u
If the -u option is given, 
backspaces are treated as printable characters;
that is, they are sent to the terminal when they appear in the input.
.IP -U
If the -U option is given,
backspaces are printed as the two character sequence "^H".
.sp
If neither -u nor -U is given,
backspaces which appear adjacent to an underscore character
are treated specially:
the underlined text is displayed 
using the terminal's hardware underlining capability.
Also, backspaces which appear between two identical characters
are treated specially: 
the overstruck text is printed 
using the terminal's hardware boldface capability.
Other backspaces are deleted, along with the preceeding character.
.IP -w
Normally,
.I less
uses a tilde character to represent lines past the end of the file.
The -w option causes blank lines to be used instead.
.IP -x
The -x\fIn\fR option sets tab stops every \fIn\fR positions.
The default for \fIn\fR is 8.
.IP -[z]
When given a backwards or forwards window command,
.I less
will by
default scroll backwards or forwards one screenful of lines. 
The -z\fIn\fR option changes the default scrolling window size 
to \fIn\fR lines.
Note that the "z" is optional for compatibility with
.I more.
.IP +
If a command line option begins with \fB+\fR,
the remainder of that option is taken to be an initial command to
.I less.
For example, +G tells
.I less
to start at the end of the file rather than the beginning,
and +/xyz tells it to start at the first occurence of "xyz" in the file.
As a special case, +<number> acts like +<number>g; 
that is, it starts the display at the specified line number
(however, see the caveat under the "g" command above).
If the option starts with \fB++\fR, the initial command applies to
every file being viewed, not just the first one.
The + command described previously
may also be used to set (or change) an initial command for every file.

D 4
.SH "KEY BINDINGS"
You may define your own less commands by using the program 
.I lesskey
(1)
to create a file called ".less" in your home directory.
This file specifies a set of command keys and an action
associated with each key.
See the
.I lesskey
manual page for more details.

E 4
.SH "PROMPTS"
The -P option allows you to tailor the prompt to your preference.
The string given to the -P option replaces the specified prompt string.
Certain characters in the string are interpreted specially.
The prompt mechanism is rather complicated to provide flexibility,
but the ordinary user need not understand the details of constructing
personalized prompt strings.
.sp
A percent sign followed by a single character is expanded
according to what the following character is:
.IP "%bX"
Replaced by the byte offset into the current input file.
The b is followed by a single character (shown as X above)
which specifies the line whose byte offset is to be used.
If the character is a "t", the byte offset of the top line in the
display is used,
an "m" means use the middle line,
a "b" means use the bottom line,
and a "B" means use the line just after the bottom line.
.IP "%f"
Replaced by the name of the current input file.
.IP "%i"
Replaced by the index of the current file in the list of
input files.
.IP "%lX"
Replaced by the line number of a line in the input file.
The line to be used is determined by the X, as with the %b option.
.IP "%m"
Replaced by the total number of input files.
.IP "%pX"
Replaced by the percent into the current input file.
The line used is determined by the X as with the %b option.
.IP "%s"
Replaced by the size of the current input file.
.IP "%t"
Causes any trailing spaces to be removed.
Usually used at the end of the string, but may appear anywhere.
.IP "%x"
Replaced by the name of the next input file in the list.
.PP
If any item is unknown (for example, the file size if input
is a pipe), a question mark is printed instead.
.PP
The format of the prompt string can be changed
depending on certain conditions.
A question mark followed by a single character acts like an "IF":
depending on the following character, a condition is evaluated.
If the condition is true, any characters following the question mark
and condition character, up to a period, are included in the prompt.
If the condition is false, such characters are not included.
A colon appearing between the question mark and the
period can be used to establish an "ELSE": any characters between
the colon and the period are included in the string if and only if
the IF condition is false.
Condition characters (which follow a question mark) may be:
.IP "?a"
True if any characters have been included in the prompt so far.
.IP "?bX"
True if the byte offset of the specified line is known.
.IP "?e"
True if at end-of-file.
.IP "?f"
True if there is an input filename
(that is, if input is not a pipe).
.IP "?lX"
True if the line number of the specified line is known.
.IP "?m"
True if there is more than one input file.
.IP "?n"
True if this is the first prompt in a new input file.
.IP "?pX"
True if the percent into the current input file
of the specified line is known.
.IP "?s"
True if the size of current input file is known.
.IP "?x"
True if there is a next input file
(that is, if the current input file is not the last one).
.PP
Any characters other than the special ones
(question mark, colon, period, percent, and backslash)
become literally part of the prompt.
Any of the special characters may be included in the prompt literally
by preceeding it with a backslash.
.PP
Some examples:
.sp
?f%f:Standard input.
.sp
This prompt prints the filename, if known;
otherwise the string "Standard input".
.sp
?f%f .?ltLine %lt:?pt%pt\%:?btByte %bt:-...
.sp
This prompt would print the filename, if known.
The filename is followed by the line number, if known,
otherwise the percent if known, otherwise the byte offset if known.
Otherwise, a dash is printed.
Notice how each question mark has a matching period,
and how the % after the %pt
is included literally by escaping it with a backslash.
.sp
?n?f%f\ .?m(file\ %i\ of\ %m)\ ..?e(END)\ ?x-\ Next\\:\ %x..%t
.sp
This prints the filename if this is the first prompt in a file,
followed by the "file N of N" message if there is more
than one input file.
Then, if we are at end-of-file, the string "(END)" is printed
followed by the name of the next file, if there is one.
Finally, any trailing spaces are truncated.
This is the default prompt.
For reference, here are the defaults for
the other two prompts (-m and -M respectively).
Each is broken into two lines here for readability only.
.nf
.sp
?n?f%f\ .?m(file\ %i\ of\ %m)\ ..?e(END)\ ?x-\ Next\\:\ %x.:
	?pB%pB\\%:byte\ %bB?s/%s...%t
.sp
?f%f\ .?n?m(file\ %i\ of\ %m)\ ..?ltline\ %lt\ :byte\ %bB?s/%s\ ..
	?e(END)\ ?x-\ Next\\:\ %x.:?pB%pB\\%..%t
.sp
.fi
And here is the default message produced by the = command:
.nf
.sp
?f%f\ .?m(file\ %i\ of\ %m)\ .?ltline\ %lt\ .
	byte\ %bB?s/%s.\ ?e(END)\ :?pB%pB\\%..%t
.fi
I 3

E 5
I 5
.SH "SEE ALSO
ctags(1), vi(1)
E 5
.SH AUTHOR
E 12
I 12
.Nm more .
D 16
.Tp
E 16
I 16
.El
E 16
.Sh ENVIRONMENT
.Nm More
D 13
uses the following environment variables:
.Ev MORE ,
.Ev EDITOR ,
.Ev SHELL
and
.Ev TERM .
E 13
I 13
utilizes the following environment variables, if they exist:
D 16
.Tw Fl
.Tp Ev MORE
E 16
I 16
.Bl -tag -width Fl
.It Ev MORE
E 16
This variable may be set with favored options to
.Nm more .
D 16
.Tp Ev EDITOR
E 16
I 16
.It Ev EDITOR
E 16
Specify default editor.
D 16
.Tp Ev SHELL
E 16
I 16
.It Ev SHELL
E 16
Current shell in use (normally set by the shell at login time).
D 16
.Tp Ev TERM
E 16
I 16
.It Ev TERM
E 16
Specifies terminal type, used by more to get the terminal
characteristics necessary to manipulate the screen.
D 16
.Tp
E 16
I 16
.El
E 16
E 13
.Sh SEE ALSO
.Xr ctags 1 ,
.Xr vi 1
.Sh AUTHOR
E 12
D 5
This software is derived from software contributed by Mark Nudleman.
E 3
D 4

.SH "SEE ALSO"
lesskey(1)
E 4

.SH WARNINGS
The = command and prompts (unless changed by -P)
report the line number of the line at the top of the screen,
but the byte and percent of the line at the bottom of the screen.
E 5
I 5
This software is derived from software contributed to Berkeley
by Mark Nudleman.
I 12
.Sh HISTORY
I 16
The
E 16
.Nm more
D 16
appeared in 3 BSD.
E 16
I 16
command appeared in
.Bx 3.0 .
E 16
E 12
E 5
E 1
