FILE="$4/man/cache$2"
TFILE="$FILE/t#$$"
LASTCOMMAND=
LASTCOMMAND1=
if test -d $FILE -a -x $FILE -a -w $FILE
then COMMAND="tee $TFILE";LASTCOMMAND="chmod -f 444 $TFILE";LASTCOMMAND1="mv -f $TFILE $FILE/$3"
if test -f $FILE/$3
then rm -f $FILE/$3
fi
else COMMAND="cat"
fi
sed '/^\.[a-z]/!s/	/#GT@/g
s/\\(bu/+/g
s/\\(em/--/g' $1 | nroff -i $4/etc/moption.macros | sed 's/_//g
s/|/?/g
s/>/?/g
s/o+/+/g
s/.//g
s/#G@$//
s/#GN@/\
/g
s/#GT@/	/g
s/^  *$//
s/^     /	/
s/^	     /		/
s/^		   /			/
/#GC@/N
s/#GC@\n */\
		/' | $COMMAND
$LASTCOMMAND
$LASTCOMMAND1