h32960
s 00000/00000/00005
d D 8.1 93/06/04 12:41:16 bostic 2 1
c 4.4BSD snapshot (revision 8.1)
e
s 00005/00000/00000
d D 5.1 92/06/26 06:55:25 bostic 1 0
c date and time created 92/06/26 06:55:25 by bostic
e
u
U
t
T
I 1
#	%W% (Berkeley) %G%

SRCS+=	bcmp.c bcopy.c bzero.s ffs.c index.c memchr.c memcmp.c memset.c \
	rindex.c strcat.c strcmp.c strcpy.c strcspn.c strlen.c strncat.c \
	strncmp.c strncpy.c strpbrk.c strsep.c strspn.c strstr.c
E 1
