h50736
s 00012/00012/00182
d D 8.2 94/01/05 12:12:16 mckusick 6 5
c control files now live in /etc/sliphome (from Chris Demetriou)
e
s 00002/00002/00192
d D 8.1 93/06/06 14:05:49 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00006/00002/00188
d D 5.4 91/08/05 07:09:27 cael 4 3
c minor nits
e
s 00110/00095/00080
d D 5.3 91/03/16 18:13:38 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00125/00130/00050
d D 5.2 90/07/01 11:29:38 trent 2 1
c hybrid version of van's & old sliplogin (major cleanup)
e
s 00180/00000/00000
d D 5.1 90/06/25 18:08:49 bostic 1 0
c date and time created 90/06/25 18:08:49 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH SLIPLOGIN 8 "%Q%"
D 2
.UC 7
E 2
.SH NAME
sliplogin \- attach a serial line network interface
.SH SYNOPSIS
.B sliplogin
D 2
[ {
.I loginname
|
.I local
.I remote
E 2
[
D 2
.I mask
] } ]
E 2
I 2
.I loginname
]
E 2
.SH DESCRIPTION
.B sliplogin
E 3
I 3
.Dd %Q%
.Dt SLIPLOGIN 8
.Os
.Sh NAME
.Nm sliplogin
.Nd attach a serial line network interface
.Sh SYNOPSIS
.Nm sliplogin
.Op Ar loginname
.Sh DESCRIPTION
.Nm Sliplogin
E 3
D 2
is used to turn the terminal line on the standard input of the process into
a Serial Line IP link to a remote host.  In order to do this, the program
needs to know the local interface address of the link, the remote interface
address, and the applicable (sub)net mask.  There are three ways it may
determine this information:
.IP -
If run by a non-root user id, the program will ignore any arguments and
instead search a table (the
.B /etc/hosts.slip
file) for an entry matching that user id's login name, and set the parameters
it needs from the contents of the matching entry.  This would be the typical
usage when sliplogin is the shell for a remote site connecting via dialup
SLIP.
.IP -
If run by root with a single argument, the described search procedure will
be performed using the argument as a key.
.IP -
If run by root with two or three arguments, they are assumed to set the
needed parameters explicitly.  A missing
.I mask
will cause the default network mask for that class network to be used.
E 2
I 2
is used to turn the terminal line on standard input into
D 3
a Serial Line IP (SLIP) link to a remote host.  To do this, the program
E 3
I 3
a Serial Line IP
.Pq Tn SLIP
link to a remote host.  To do this, the program
E 3
searches the file
D 3
.B /etc/slip.hosts
E 3
I 3
D 6
.Pa /etc/slip.hosts
E 6
I 6
.Pa /etc/sliphome/slip.hosts
E 6
E 3
for an entry matching
D 3
.I loginname
E 3
I 3
.Ar loginname
E 3
(which defaults to the current login name if omitted).
If a matching entry is found, the line is configured appropriately
D 3
for slip (8-bit transparent i/o) and converted to SLIP line
E 3
I 3
for slip (8-bit transparent i/o) and converted to
.Tn SLIP
line
E 3
discipline.  Then a shell script is invoked to initialize the slip
D 3
interface with the appropriate local and remote IP address,
E 3
I 3
interface with the appropriate local and remote
.Tn IP
address,
E 3
netmask, etc.
E 2
D 3
.PP
E 3
I 3
.Pp
E 3
D 2
The parameters may be specified either by name (which will be looked up
using
.BR gethostbyname (3N)
and
.BR getnetbyname (3N)),
or as a dotted quad that the
.BR inet_addr (3N)
function can interpret.
E 2
I 2
The usual initialization script is
D 3
.B /etc/slip.login
E 3
I 3
D 6
.Pa /etc/slip.login
E 6
I 6
.Pa /etc/sliphome/slip.login
E 6
E 3
but, if particular hosts need special initialization, the file
D 3
.BI /etc/slip.login. loginname
E 3
I 3
D 6
.Pa /etc/slip.login. Ns Ar loginname
E 6
I 6
.Pa /etc/sliphome/slip.login. Ns Ar loginname
E 6
E 3
will be executed instead if it exists.
The script is invoked with the parameters
D 3
.TP
.I slipunit
E 3
I 3
.Bl -tag -width slipunit
.It Em slipunit
E 3
The unit number of the slip interface assigned to this line.  E.g.,
D 3
.B 0
E 3
I 3
.Sy 0
E 3
for
D 3
.BR sl0 .
.TP
.I speed
E 3
I 3
.Sy sl0 .
.It Em speed
E 3
The speed of the line.
D 3
.TP
.I args
E 3
I 3
.It Em args
E 3
The arguments from the
D 3
.B /etc/slip.hosts
E 3
I 3
D 6
.Pa /etc/slip.hosts
E 6
I 6
.Pa /etc/sliphome/slip.hosts
E 6
E 3
entry, in order starting with
D 3
.IR loginname .
E 2
.PP
E 3
I 3
.Ar loginname .
.El
.Pp
E 3
D 2
The line speed is unchanged, but other terminal line parameters are
initialized properly for the purpose.
.PP
E 2
Only the super-user may attach a network interface.  The interface is
D 2
automatically detached when the
E 2
I 2
automatically detached when the other end hangs up or the
E 2
D 3
.B sliplogin
E 3
I 3
.Nm sliplogin
E 3
D 2
process dies.  If the kernel
.B slip
E 2
I 2
process dies.  If the kernel slip
E 2
module has been configured for it, all routes through that interface will
D 2
also disappear at the same time.
.SH "TABLE FORMAT"
The format of the
.B /etc/hosts.slip
file is as follows:
.IP -
blank lines and lines with a leading # are ignored.
.IP -
all other lines should have the form:
.sp
.br
\fIname mode local-address remote-address netmask\fP
.br
.sp
The
.I name
is usually the login name of a remote host that wishes to connect by
dialup slip.  More generally it is any key you wish for the address
and mask parameters specified on that line.  The
.I mode
is currently unused but must be specified.  Use
.BR normal .
The remaining parameters have been discussed.
E 2
I 2
also disappear at the same time.  If there is other processing a site
would like done on hangup, the file
D 3
.B /etc/slip.logout
E 3
I 3
D 6
.Pa /etc/slip.logout
E 6
I 6
.Pa /etc/sliphome/slip.logout
E 6
E 3
or
D 3
.BI /etc/slip.logout. loginname
E 3
I 3
D 6
.Pa /etc/slip.logout. Ns Ar loginname
E 6
I 6
.Pa /etc/sliphome/slip.logout. Ns Ar loginname
E 6
E 3
is executed if it exists.  It is given the same arguments as the login script.
D 3
.SS Format of /etc/slip.hosts
E 3
I 3
D 6
.Ss Format of /etc/slip.hosts
E 6
I 6
.Ss Format of /etc/sliphome/slip.hosts
E 6
E 3
Comments (lines starting with a `#') and blank lines are ignored.
Other lines must start with a
D 3
.I loginname
E 3
I 3
.Ar loginname
E 3
but the remaining arguments can be whatever is appropriate for the
D 3
.B slip.login
E 3
I 3
.Pa  slip.login
E 3
file that will be executed for that name.
Arguments are separated by white space and follow normal
D 3
.BR sh (1)
E 3
I 3
.Xr sh 1
E 3
quoting conventions (however,
D 3
.I loginname
E 3
I 3
.Ar loginname
E 3
cannot be quoted).
Usually, lines have the form
D 3
.RS
.I
E 3
I 3
.Bd -literal -offset indent
E 3
loginname local-address remote-address netmask opt-args
D 3
.RE
E 3
I 3
.Ed
.Pp
E 3
where
D 3
.I local-address
E 3
I 3
.Em local-address
E 3
and
D 3
.I remote-address
E 3
I 3
.Em remote-address
E 3
are the IP host names or addresses of the local and remote ends of the
slip line and
D 3
.I netmask
E 3
I 3
.Em netmask
E 3
is the appropriate IP netmask.  These arguments are passed
directly to
D 3
.BR ifconfig (8).
.I Opt-args
E 3
I 3
.Xr ifconfig 8 .
.Em Opt-args
E 3
are optional arguments used to configure the line.
D 3
.SH EXAMPLE
E 3
I 3
.Sh EXAMPLE
E 3
The normal use of
D 3
.B sliplogin
E 3
I 3
.Nm sliplogin
E 3
is to create a
D 3
.B /etc/passwd
E 3
I 3
.Pa /etc/passwd
E 3
entry for each legal, remote slip site with
D 3
.B sliplogin
E 3
I 3
.Nm sliplogin
E 3
as the shell for that entry.  E.g.,
D 3
.RS
E 3
I 3
.Bd -literal
E 3
D 6
Sfoo:ikhuy6:2010:1:slip line to foo:/tmp:/etc/sliplogin
E 6
I 6
Sfoo:ikhuy6:2010:1:slip line to foo:/tmp:/usr/sbin/sliplogin
E 6
D 3
.RE
E 3
I 3
.Ed
.Pp
E 3
(Our convention is to name the account used by remote host
D 3
.I hostname
E 3
I 3
.Ar hostname
E 3
as
D 3
.IR Shostname .)
E 3
I 3
.Em Shostname . )
E 3
Then an entry is added to
D 3
.B slip.hosts
E 3
I 3
.Pa slip.hosts
E 3
that looks like:
D 3
.RS
E 3
I 3
.Pp
.Bd -literal -offset indent -compact
E 3
Sfoo	`hostname`	foo	netmask
D 3
.RE
E 3
I 3
.Ed
.Pp
E 3
where
D 3
.I `hostname`
E 3
I 3
.Em `hostname`
E 3
will be evaluated by
D 3
.B sh
E 3
I 3
.Xr sh
E 3
to the local host name and
D 3
.I netmask
E 3
I 3
.Em netmask
E 3
is the local host IP netmask.
D 3
.PP
E 3
I 3
.Pp
E 3
Note that
D 3
.B sliplogin
E 3
I 3
.Nm sliplogin
E 3
must be setuid to root and, while not a security hole, moral defectives
can use it to place terminal lines in an unusable state and/or deny
access to legitimate users of a remote slip line.  To prevent this,
a site can create a group, say
D 3
.IR slip ,
E 3
I 3
.Em slip ,
E 3
that only the slip login accounts are put in then make sure that
D 3
.B /etc/sliplogin
E 3
I 3
D 6
.Pa /etc/sliplogin
E 6
I 6
.Pa /usr/sbin/sliplogin
E 6
E 3
is in group
D 3
.I slip
E 3
I 3
.Em slip
E 3
and mode 4550 (setuid root, only group
D 3
.I slip
E 3
I 3
.Em slip
E 3
can execute binary).
E 2
D 3
.SH "DIAGNOSTICS"
.B sliplogin
E 3
I 3
.Sh DIAGNOSTICS
.Nm Sliplogin
E 3
logs various information to the system log daemon,
D 3
.BR syslogd (8),
E 3
I 3
.Xr syslogd 8 ,
E 3
with a facility code of
D 3
.BR daemon .
E 3
I 3
.Em daemon .
E 3
The messages are listed here, grouped by severity level.
I 4
.Pp
E 4
D 3
.SS Err Severity
.TP
.BI "ioctl (TCGETS): " reason
E 3
I 3
.Sy Error Severity
D 4
.Bl -tag -width Ds
E 4
I 4
.Bl -tag -width Ds -compact
E 4
.It Sy ioctl (TCGETS): Em reason
E 3
A
D 3
.SB TCGETS
.B ioctl
E 3
I 3
.Dv TCGETS
.Fn ioctl
E 3
to get the line parameters failed.
I 4
.Pp
E 4
D 3
.TP
.BI "ioctl (TCSETS): " reason
E 3
I 3
.It Sy ioctl (TCSETS): Em reason
E 3
A
D 3
.SB TCSETS
.B ioctl
E 3
I 3
.Dv TCSETS
.Fn ioctl
E 3
to set the line parameters failed.
I 4
.Pp
E 4
D 3
.TP
D 2
.BI "ioctl (I_PUSH): " reason
A
.SB I_PUSH
.B ioctl
to push the
.B slip
streams module onto the line failed.
.TP
.BI "ioctl (SLIOGUNIT): " reason
A
.SB SLIOGUNIT
.B ioctl
to get the interface unit number failed.
.TP
.BI "ioctl (SIOCSIFNETMASK): " reason
A
.SB SIOCSIFNETMASK
.B ioctl
to set the network mask for the SLIP interface failed.
.TP
.BI "ioctl (SIOCSIFDSTADDR): " reason
A
.SB SIOCSIFDSTADDR
.B ioctl
to set the destination address for the SLIP interface failed.
.TP
.BI "ioctl (SIOCSIFADDR): " reason
A
.SB SIOCSIFADDR
.B ioctl
to set the source address for the SLIP interface failed.
.TP
.BI "UID (" uid ") is unknown"
An attempt was made to run
.B sliplogin
with an effective user
.SM ID
not in the password file.
.TP
.BI "/etc/hosts.slip: " reason
E 2
I 2
.BI "/etc/slip.hosts: " reason
E 3
I 3
D 6
.It Sy /etc/slip.hosts: Em reason
E 6
I 6
.It Sy /etc/sliphome/slip.hosts: Em reason
E 6
E 3
E 2
The
D 2
.B /etc/hosts.slip
E 2
I 2
D 3
.B /etc/slip.hosts
E 3
I 3
D 6
.Pa /etc/slip.hosts
E 6
I 6
.Pa /etc/sliphome/slip.hosts
E 6
E 3
E 2
file could not be opened.
I 4
.Pp
E 4
D 3
.TP
D 2
.BI "SLIP access denied for " user
Access to SLIP logins was denied for the user
.IR user .
.TP
.IB addr ": bad value"
The address specification
.I addr
could not be converted to an Internet address.
E 2
I 2
.BI "access denied for " user
E 3
I 3
.It Sy access denied for Em user
E 3
No entry for
D 3
.I user
E 3
I 3
.Em user
E 3
was found in
D 3
.BR /etc/slip.hosts .
E 2
.SS Notice Severity
.TP
D 2
.BI "attaching slip" unit ": local " local " remote " remote " mask" mask
E 2
I 2
.BI "attaching slip unit " unit " for " loginname
E 2
SLIP unit
.I unit
E 3
I 3
D 6
.Pa /etc/slip.hosts .
E 6
I 6
.Pa /etc/sliphome/slip.hosts .
E 6
.El
.Pp
.Sy Notice Severity
D 4
.Bl -tag -width Ds
E 4
I 4
.Bl -tag -width Ds -compact
E 4
.It Sy "attaching slip unit" Em unit Sy for Ar loginname
.Tn SLIP
unit
.Em unit
E 3
D 2
was successfully attached, with a source address of
.IR local ,
a destination address of
.IR remote ,
and a netmask of
.IR mask .
.SH EXAMPLES
.ta 8
	sliplogin ip_utai < /dev/ttyb &
.sp
	sliplogin us-sl them-sl 255.255.255.0 < /dev/ttyb &
.sp
	sliplogin 192.12.174.1 192.12.174.2 < /dev/ttyb &
E 2
I 2
was successfully attached.
E 2
D 3
.SH "SEE ALSO"
D 2
.BR slip (4M),
E 2
I 2
.BR slattach (8),
E 2
.BR syslogd (8)
E 3
I 3
.El
.Sh SEE ALSO
.Xr slattach 8 ,
.Xr syslogd 8
.Sh HISTORY
The
.Nm
command
.Bt
E 3
E 1
