h18073
s 00002/00002/00077
d D 8.1 93/06/06 22:17:50 bostic 12 11
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00051/00034/00028
d D 6.9 91/04/23 18:37:18 cael 11 10
c mdoc version three
e
s 00004/00014/00058
d D 6.8 90/06/24 19:22:20 cael 10 9
c converted man page
e
s 00001/00001/00071
d D 6.7 90/04/03 20:01:24 bostic 9 8
c move uuencode.5 to uuencode.format.5
e
s 00002/00001/00070
d D 6.6 89/08/22 14:28:47 bostic 8 7
c document that setuid and execute bits are not retained
e
s 00036/00050/00035
d D 6.5 89/07/19 16:53:04 bostic 7 6
c remove mail bias; uudecode handles multiple files.
e
s 00014/00003/00071
d D 6.4 89/03/15 17:34:40 bostic 6 5
c add Berkeley specific copyright notice
e
s 00003/00003/00071
d D 6.3 88/10/24 12:00:02 bostic 5 4
c remove refs to [18]C, add copyright if needed
e
s 00010/00009/00064
d D 6.2 86/04/24 19:28:22 mckusick 4 3
c update from rfg
e
s 00001/00001/00072
d D 6.1 85/04/29 15:07:18 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00005/00005/00068
d D 5.1 85/04/29 15:07:08 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00073/00000/00000
d D 4.1 85/04/29 15:07:00 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 10
.\" Copyright (c) 1980 The Regents of the University of California.
E 10
I 10
D 12
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
E 10
.\" All rights reserved.
E 12
I 12
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 12
.\"
D 10
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 10
I 10
.\" %sccs.include.redist.man%
E 10
E 6
.\"
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
.\"     %W% (Berkeley) %G%
E 10
.\"
D 2
.TH UUENCODE 1C 6/1/80
E 2
I 2
D 3
.TH UUENCODE 1C "1 June 1980"
E 3
I 3
D 5
.TH UUENCODE 1C "%Q%"
E 5
I 5
D 10
.TH UUENCODE 1 "%Q%"
E 10
I 10
D 11
.TH UUENCODE 1 "%Q"
E 10
E 5
E 3
E 2
.UC 4
.SH NAME
D 2
uuencode,uudecode \- encode/decode a binary file for tranmission via mail
E 2
I 2
D 4
uuencode,uudecode \- encode/decode a binary file for transmission via mail
E 4
I 4
D 7
uuencode, uudecode \- encode/decode a binary file for transmission via mail
E 7
I 7
uuencode, uudecode \- encode/decode a binary file
E 7
E 4
E 2
.SH SYNOPSIS
.B uuencode
D 7
[ source ] remotedest |
.B mail
sys1!sys2!..!decode
E 7
I 7
[ file ] name
E 7
.br
.B uudecode
D 7
[ file ]
E 7
I 7
[ file ... ]
E 7
.SH DESCRIPTION
.I Uuencode
E 11
I 11
.Dd %Q%
.Dt UUENCODE 1
.Os BSD 4
.Sh NAME
.Nm uuencode ,
.Nm uudecode
.Nd encode/decode a binary file
.Sh SYNOPSIS
.Nm uuencode
.Op Ar file
.Ar name
.Nm uudecode
.Op Ar file ...
.Sh DESCRIPTION
.Nm Uuencode
E 11
and
D 11
.I uudecode
E 11
I 11
.Nm uudecode
E 11
D 7
are used to send a binary file via uucp (or other) mail.
This combination can be used over indirect mail links
even when
D 2
.I uusend(1)
E 2
I 2
D 5
.IR uusend (1C)
E 5
I 5
.IR uusend (1)
E 5
E 2
is not available.
E 7
I 7
are used to transmit binary files over transmission mediums
D 11
that do not support other than simple ASCII data.
E 7
.PP
.I Uuencode
E 11
I 11
that do not support other than simple
.Tn ASCII
data.
.Pp
.Nm Uuencode
E 11
D 7
takes the named source file (default standard input) and
produces an encoded version on the standard output.
The encoding uses only printing ASCII characters,
and includes the mode of the file and the
.I remotedest
for recreation on the remote system.
E 7
I 7
reads
D 11
.I file
E 11
I 11
.Ar file
E 11
(or by default the standard input) and writes an encoded version
to the standard output.
D 11
The encoding uses only printing ASCII characters and includes the
E 11
I 11
The encoding uses only printing
.Tn ASCII
characters and includes the
E 11
mode of the file and the operand
D 11
.I name
E 11
I 11
.Ar name
E 11
for use by
D 11
.IR uudecode .
E 7
.PP
.I Uudecode
E 11
I 11
.Nm uudecode .
.Pp
.Nm Uudecode
E 11
D 7
reads an encoded file,
strips off any leading and trailing lines added by mailers,
and recreates the original file with the specified mode and name.
.PP
The intent is that all mail to the user ``decode'' should be filtered
D 4
through the uudecode program.  This way the file is created automatically
E 4
I 4
through the
E 7
I 7
transforms
D 11
.I uuencoded
E 11
I 11
.Em uuencoded
E 11
files (or by default, the standard input) into the original form.
The resulting file is named
D 11
.IR name
E 11
I 11
.Ar name
E 11
D 8
and will have the mode of the original file.
E 8
I 8
and will have the mode of the original file except that setuid
and execute bits are not retained.
E 8
D 11
.I Uudecode
E 11
I 11
.Nm Uudecode
E 11
ignores any leading and trailing lines.
D 11
.SH EXAMPLES
E 11
I 11
.Sh EXAMPLES
E 11
The following example packages up a source tree, compresses it,
uuencodes it and mails it to a user on another system.
When
E 7
D 11
.I uudecode
E 11
I 11
.Nm uudecode
E 11
D 7
program.  This way the file is created automatically
E 4
without human intervention.
This is possible on the uucp network by either using
D 2
.I delivermail
E 2
I 2
.I sendmail
E 2
or by making
.I rmail
be a link to
.I Mail
instead of
D 4
.I mail.
E 4
I 4
.IR mail .
E 4
In each case, an alias must be created in a master file to get
D 4
the automatic invocation of uudecode.
E 4
I 4
the automatic invocation of
.IR uudecode .
E 4
.PP
If these facilities are not available, the file can be sent to a
user on the remote machine who can uudecode it manually.
.PP
The encode file has an ordinary text form and can be edited
by any text editor to change the mode or remote name.
E 7
I 7
is run on the target system, the file ``src_tree.tar.Z'' will be
created which may then be uncompressed and extracted into the original
tree.
D 11
.sp
.in +5
tar cf - src_tree | compress | uuencode src_tree.tar.Z | mail sys1!sys2!user
.sp
E 7
D 4
.SH SEE\ ALSO
D 2
uuencode(5), uusend(1), uucp(1), uux(1), mail(1)
E 2
I 2
uuencode(5), uusend(1C), uucp(1C), uux(1C), mail(1)
E 2
.SH AUTHOR
Mark Horton
E 4
I 4
.SH SEE ALSO
D 5
atob(n), uusend(1C), uucp(1C), uux(1C), mail(1), uuencode(5)
E 5
I 5
D 7
atob(n), uusend(1), uucp(1), uux(1), mail(1), uuencode(5)
E 7
I 7
D 9
compress(1), mail(1), uucp(1), uuencode(5)
E 9
I 9
compress(1), mail(1), uucp(1), uuencode.format(5)
E 9
E 7
E 5
E 4
.SH BUGS
E 11
I 11
.Pp
.Bd -literal -offset indent -compact
tar cf \- src_tree \&| compress \&|
uuencode src_tree.tar.Z \&| mail sys1!sys2!user
.Ed
.Sh SEE ALSO
.Xr compress 1 ,
.Xr mail 1 ,
.Xr uucp 1 ,
.Xr uuencode 5 ,
.Xr format 5
.Sh BUGS
E 11
D 7
The file is expanded by 35% (3 bytes become 4 plus control information)
causing it to take longer to transmit.
.PP
The user on the remote system who is invoking
.I uudecode
(often
D 4
.I uucp)
E 4
I 4
.IR uucp )
E 4
must have write permission on the specified file.
E 7
I 7
The encoded form of the file is expanded by 35% (3 bytes become 4 plus
control information).
I 11
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
E 11
E 7
E 1
