h32306
s 00012/00000/00476
d D 8.6 95/05/27 11:25:33 eric 28 27
c doc updates -- -q[IRS] not mentioned
e
s 00001/00000/00475
d D 8.5 94/06/01 20:46:42 ah 27 26
c page breaks for 4.4BSD manuals
e
s 00001/00000/00474
d D 8.4 93/12/11 23:44:49 mckusick 26 25
c copyediting for Usenix manuals
e
s 00000/00005/00474
d D 8.3 93/08/20 11:52:03 eric 25 24
c more on elimination of frozen config files
e
s 00005/00000/00474
d D 8.2 93/07/18 12:32:13 eric 24 23
c document -X flag
e
s 00002/00002/00472
d D 8.1 93/07/18 12:30:38 bostic 23 21
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00002/00472
d R 8.1 93/06/16 14:48:11 bostic 22 21
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00003/00472
d D 6.17 93/06/16 12:33:50 eric 21 20
c more tweaking
e
s 00026/00030/00449
d D 6.16 93/06/16 12:03:57 bostic 20 18
c update for current reality
e
s 00002/00002/00477
d R 8.1 93/06/07 10:32:02 bostic 19 18
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00007/00000/00472
d D 6.15 93/04/15 18:18:30 eric 18 17
c document the -B flag
e
s 00000/00000/00472
d D 6.14 92/12/21 16:08:37 eric 17 16
c Release 6
e
s 00004/00000/00468
d D 6.13 92/12/15 18:16:13 eric 16 15
c add -p flag
e
s 00010/00007/00458
d D 6.12 91/10/03 14:38:57 eric 15 14
c some changes to enhance compatibility with SunOS sendmail
e
s 00006/00006/00459
d D 6.11 91/10/02 12:59:36 eric 14 13
c reverse sense of w (wildcard MX) flag to default to the safest option,
c instead of the most desirable option.
e
s 00008/00003/00457
d D 6.10 91/08/05 07:06:13 cael 13 12
c .Dv CNAME...
e
s 00007/00000/00453
d D 6.9 91/07/26 09:34:33 eric 12 11
c hooks for distributed user database system
e
s 00019/00007/00434
d D 6.8 91/07/25 11:12:23 eric 11 10
c some compatibility with SunOS for future work here at Berkeley;
c change NO_WILDCARD_MX compilation flag to configuration option "w".
e
s 00007/00000/00434
d D 6.7 91/04/26 14:40:35 cael 10 8
c add -k flag for eric
e
s 00007/00000/00434
d R 6.7 91/04/26 14:37:19 cael 9 8
c add -k flag for eric
e
s 00003/00003/00431
d D 6.6 91/04/23 20:45:18 cael 8 7
c fixed unquoted title (%T)
e
s 00250/00240/00184
d D 6.5 91/03/16 18:13:31 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00013/00023/00411
d D 6.4 90/06/24 22:38:01 trent 6 5
c new copyright & pathnames
e
s 00016/00009/00418
d D 6.3 88/09/20 18:20:09 bostic 5 4
c Berkeley copyright
e
s 00078/00043/00349
d D 6.2 86/05/22 13:48:07 eric 4 3
c cleanup for 4.3bsd
e
s 00001/00001/00391
d D 6.1 85/04/27 13:18:32 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00300/00162/00092
d D 5.1 85/04/27 13:17:26 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00254/00000/00000
d D 4.1 85/04/27 13:15:52 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1988 The Regents of the University of California.
E 7
I 7
D 23
.\" Copyright (c) 1988, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 23
I 23
.\" Copyright (c) 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 23
E 5
.\"
I 5
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
E 5
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH DELIVERMAIL 8 "4/1/81"
E 2
I 2
D 5
.\"	@(#)sendmail.8	4.2		7/28/83
E 5
D 3
.TH SENDMAIL 8 "7/28/83"
E 3
I 3
D 7
.TH SENDMAIL 8 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
delivermail \- deliver mail to arbitrary people
E 2
I 2
sendmail \- send mail over the internet
E 2
.SH SYNOPSIS
D 2
.B /etc/delivermail
E 2
I 2
D 6
.B /usr/lib/sendmail
E 6
I 6
.B sendmail
E 6
E 2
[
D 2
.BR \- [ fr ]
.I address
E 2
I 2
flags
E 2
] [
D 2
.B \-a
] [
.BI \-e x
] [
.B \-n
] [
.B \-m
] [
.B \-s
] [
.B \-i
] [
.B \-h
.I N
] address ...
E 2
I 2
address ...
]
.PP
.B newaliases
.PP
.B mailq
I 4
[
.B \-v
]
E 4
E 2
.SH DESCRIPTION
D 2
.I Delivermail
delivers a letter to one or more people,
routing the letter over whatever networks
E 2
I 2
.I Sendmail
E 7
I 7
.Dd %Q%
.Dt SENDMAIL 8
.Os BSD 4
.Sh NAME
.Nm sendmail
.Nd send mail over the internet
.Sh SYNOPSIS
.Nm sendmail
.Op Ar flags
.Op Ar address ...
.Nm newaliases
.Nm mailq
.Op Fl v
.Sh DESCRIPTION
.Nm Sendmail
E 7
D 4
sends a message to one or more people,
E 4
I 4
sends a message to one or more
D 7
.IR recipients ,
E 7
I 7
.Em recipients ,
E 7
E 4
routing the message over whatever networks
E 2
are necessary.
D 2
.I Delivermail
will do inter-net forwarding as necessary
to deliver the mail to the correct place.
E 2
I 2
D 7
.I Sendmail
E 7
I 7
.Nm Sendmail
E 7
does internetwork forwarding as necessary
to deliver the message to the correct place.
E 2
D 7
.PP
D 2
.I Delivermail
E 2
I 2
.I Sendmail
E 7
I 7
.Pp
.Nm Sendmail
E 7
E 2
is not intended as a user interface routine;
D 2
it is expected that other programs will provide user-friendly
front ends,
and
.I delivermail
will be used only to deliver pre-formatted messages.
E 2
I 2
other programs provide user-friendly
front ends;
D 7
.I sendmail
E 7
I 7
.Nm sendmail
E 7
is used only to deliver pre-formatted messages.
E 2
D 7
.PP
E 7
I 7
.Pp
E 7
D 2
.I Delivermail
E 2
I 2
With no flags,
D 7
.I sendmail
E 7
I 7
.Nm sendmail
E 7
E 2
reads its standard input
D 4
up to a control-D
or a line with a single dot
and sends a copy of the letter found there
E 4
I 4
up to an end-of-file
or a line consisting only of a single dot
and sends a copy of the message found there
E 4
to all of the addresses listed.
D 2
If the
.B \-i
flag is given,
single dots are ignored.
E 2
D 4
It determines the network to use
E 4
I 4
It determines the network(s) to use
E 4
D 2
based on the syntax of the addresses.
Addresses containing the character `@'
or the word \*(lqat\*(rq
are sent to the
.SM ARPANET;
addresses containing `!'
are sent to the
.SM UUCP
net,
and addresses containing `:' or `.'
are sent to the Berkeley network.
Other addresses are assumed to be local.
E 2
I 2
based on the syntax and contents of the addresses.
E 2
D 7
.PP
E 7
I 7
.Pp
E 7
Local addresses are looked up in a file
D 2
constructed by
.IR newaliases (1)
from the data file
.I /usr/lib/aliases
E 2
and aliased appropriately.
Aliasing can be prevented by preceding the address
D 2
with a backslash or using the
.B \-n
flag.
E 2
I 2
with a backslash.
E 2
Normally the sender is not included in any alias
expansions, e.g.,
if `john' sends to `group',
and `group' includes `john' in the expansion,
then the letter will not be delivered to `john'.
D 2
The
.B \-m
flag disables this suppression.
E 2
D 7
.PP
E 7
I 7
D 21
.Pp
E 7
D 2
.I Delivermail
computes the person sending the mail
by looking at your login name.
The \*(lqfrom\*(rq person
can be explicitly specified by using the
E 2
I 2
Flags are:
E 21
I 21
.Ss Parameters
E 21
D 7
.TP 1.2i
.B \-ba
Go into \s-1ARPANET\s0 mode.
E 7
I 7
.Bl -tag -width Fl
I 18
.It Fl B Ns Ar type
Set the body type to
.Ar type .
Current legal values
.Li 7BIT
or
.Li 8BITMIME .
E 18
.It Fl ba
Go into
.Tn ARPANET
mode.
E 7
All input lines must end with a CR-LF,
and all messages will be generated with a CR-LF at the end.
Also,
the ``From:'' and ``Sender:''
fields are examined for the name of the sender.
D 7
.TP 1.2i
.B \-bd
Run as a daemon.  This requires Berkeley IPC.
I 4
.I Sendmail
E 7
I 7
.It Fl bd
Run as a daemon.  This requires Berkeley
.Tn IPC .
.Nm Sendmail
E 7
will fork and run in background
D 7
listening on socket 25 for incoming SMTP connections.
E 7
I 7
listening on socket 25 for incoming
.Tn SMTP
connections.
E 7
This is normally run from
D 7
.IR /etc/rc .
E 4
.TP 1.2i
.B \-bi
E 7
I 7
.Pa /etc/rc .
.It Fl bi
E 7
Initialize the alias database.
D 7
.TP 1.2i
.B \-bm
E 7
I 7
.It Fl bm
E 7
Deliver mail in the usual way (default).
D 7
.TP 1.2i
.B \-bp
E 7
I 7
.It Fl bp
E 7
Print a listing of the queue.
D 7
.TP 1.2i
.B \-bs
D 4
Use the \s-2SMTP\s0 protocol as described in RFC821.
E 4
I 4
Use the \s-2SMTP\s0 protocol as described in RFC821
E 7
I 7
.It Fl bs
Use the
.Tn SMTP
protocol as described in
.Tn RFC821
E 7
on standard input and output.
E 4
This flag implies all the operations of the
D 7
.B \-ba
flag that are compatible with \s-2SMTP\s0.
.TP 1.2i
.B \-bt
E 7
I 7
.Fl ba
flag that are compatible with
.Tn SMTP .
.It Fl bt
E 7
Run in address test mode.
This mode reads addresses and shows the steps in parsing;
it is used for debugging configuration tables.
D 7
.TP 1.2i
.B \-bv
E 7
I 7
.It Fl bv
E 7
Verify names only \- do not try to collect or deliver a message.
Verify mode is normally used for validating
users or mailing lists.
D 7
.TP 1.2i
.B \-bz
E 7
I 7
D 25
.It Fl bz
E 7
Create the configuration freeze file.
E 25
D 7
.TP 1.2i
.BI \-C file
E 7
I 7
.It Fl C Ns Ar file
E 7
Use alternate configuration file.
I 4
D 7
.I Sendmail
E 7
I 7
.Nm Sendmail
E 7
refuses to run as root if an alternate configuration file is specified.
D 25
The frozen configuration file is bypassed.
E 25
E 4
D 7
.TP 1.2i
.BI \-d X
E 7
I 7
.It Fl d Ns Ar X
E 7
Set debugging value to
D 7
.I X.
.TP 1.2i
.BI \-F fullname
E 7
I 7
.Ar X .
I 26
.ne 1i
E 26
.It Fl F Ns Ar fullname
E 7
Set the full name of the sender.
D 7
.TP 1.2i
.BI \-f name
E 7
I 7
.It Fl f Ns Ar name
E 7
Sets the name of the ``from'' person
(i.e., the sender of the mail).
E 2
D 7
.B \-f
E 7
I 7
.Fl f
E 7
D 2
flag;
or, if the
.B \-a
flag is given,
delivermail looks in the body of the message
for a \*(lqFrom:\*(rq or \*(lqSender:\*(rq
field in
.SM ARPANET
format.
The
.B \-f
E 2
I 2
can only be used
D 4
by the special users
E 4
I 4
by ``trusted'' users
(normally
E 4
D 7
.I root,
.I daemon,
E 7
I 7
.Em root ,
.Em daemon ,
E 7
E 2
and
D 2
.B \-a
flags can be used
only by the special users
.I root
and
E 2
D 4
.I network,
E 4
I 4
D 7
.I network)
E 7
I 7
.Em network )
E 7
E 4
or if the person you are trying to become
is the same as the person you are.
D 2
The
.B \-r
flag is entirely equivalent to the
E 2
I 2
D 7
.TP 1.2i
.BI \-h N
E 7
I 7
.It Fl h Ns Ar N
E 7
Set the hop count to
D 7
.I N.
E 7
I 7
.Ar N .
E 7
The hop count is incremented every time the mail is
processed.
When it reaches a limit,
the mail is returned with an error message,
the victim of an aliasing loop.
I 4
If not specified,
``Received:'' lines in the message are counted.
I 10
D 11
.It Fl k Ar N
Checkpoint the queue file after every
.Ar N
successful deliveries (default 10).
This avoids excessive duplicate deliveries
when sending to long mailing lists
interrupted by system crashes.
E 11
E 10
E 4
D 7
.TP 1.2i
.B \-n
E 7
I 7
.It Fl n
E 7
Don't do aliasing.
D 7
.TP 1.2i
.BI \-o x\|value
E 7
I 7
.It Fl o Ns Ar x Em value
E 7
Set option
D 7
.I x
E 7
I 7
.Ar x
E 7
to the specified
D 7
.I value.
E 7
I 7
.Em value .
E 7
Options are described below.
I 16
.It Fl p Ns Ar protocol
Set the name of the protocol used to receive the message.
This can be a simple protocol name such as ``UUCP''
or a protocol and hostname, such as ``UUCP:ucbvax''.
E 16
D 7
.TP 1.2i
.BI \-q[ time ]
E 7
I 7
.It Fl q Ns Bq Ar time
E 7
Processed saved messages in the queue at given intervals.
If
D 4
.IT time
E 4
I 4
D 7
.I time
E 7
I 7
.Ar time
E 7
E 4
is omitted,
process the queue once.
D 4
.IT Time
E 4
I 4
D 7
.I Time
E 7
I 7
.Xr Time
E 7
E 4
is given as a tagged number,
D 7
with `s' being seconds,
`m' being minutes,
`h' being hours,
`d' being days,
E 7
I 7
with
.Ql s
being seconds,
.Ql m
being minutes,
.Ql h
being hours,
.Ql d
being days,
E 7
and
D 7
`w' being weeks.
E 7
I 7
.Ql w
being weeks.
E 7
For example,
D 7
``\-q1h30m'' or ``\-q90m''
E 7
I 7
.Ql \-q1h30m
or
.Ql \-q90m
E 7
would both set the timeout to one hour thirty minutes.
I 4
If
D 7
.I time
E 7
I 7
.Ar time
E 7
is specified,
D 7
.I sendmail
E 7
I 7
.Nm sendmail
E 7
will run in background.
This option can be used safely with
D 7
.BR \-bd .
E 4
.TP 1.2i
.BI \-r name
E 7
I 7
.Fl bd .
I 28
.It Fl qI Ns Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of the queue id.
.It Fl qR Ns Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of one of the recipients.
.It Fl qS Ns Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of the sender.
E 28
.It Fl r Ns Ar name
E 7
An alternate and obsolete form of the
E 2
D 7
.B \-f
E 7
I 7
.Fl f
E 7
D 2
flag; it is provided for ease of interface only.
E 2
I 2
flag.
D 7
.TP 1.2i
.B \-t
E 7
I 7
.It Fl t
E 7
Read message for recipients.
D 4
To:, Cc:, and Bcc: lines will be scanned for people to send to.
E 4
I 4
To:, Cc:, and Bcc: lines will be scanned for recipient addresses.
E 4
The Bcc: line will be deleted before transmission.
D 4
Any addresses in the argument list will be suppressed.
E 4
I 4
Any addresses in the argument list will be suppressed,
that is,
they will
D 7
.I not
E 7
I 7
.Em not
E 7
receive copies even if listed in the message header.
E 4
D 7
.TP 1.2i
.B \-v
E 7
I 7
.It Fl v
E 7
Go into verbose mode.
Alias expansions will be announced, etc.
I 24
.It Fl X Ar logfile
Log all traffic in and out of mailers in the indicated log file.
This should only be used as a last resort
for debugging mailer bugs.
It will log a lot of data very quickly.
E 24
E 2
D 7
.PP
E 7
I 7
.El
D 21
.Pp
E 21
I 21
.Ss Options
E 21
E 7
D 2
The
.BI \-e x
flag controls the disposition of error output,
as follows:
.TP 3n
.B e
Print errors on the standard output,
and echo a copy of the message when done.
It is assumed that a network server will
return the message back to the user.
.TP
.B m
Mail errors back to the user.
.TP
.B p
Print errors on the standard output.
.TP
.B q
Throw errors away;
only exit status is returned.
.TP
.B w
Write errors back to the user's terminal,
but only if the user is still logged in
and write permission is enabled;
otherwise errors are mailed back.
.LP
If the error is not mailed back,
and if the mail originated on the machine where the error occurred,
the letter is appended to the file
.I dead.letter
E 2
I 2
There are also a number of processing options that may be set.
Normally these will only be used by a system administrator.
Options may be set either on the command line
using the
D 7
.B \-o
E 7
I 7
.Fl o
E 7
flag
or in the configuration file.
D 20
These are described in detail in the
E 20
I 20
This is a partial list;
for a complete list (and details), consult the
E 20
D 7
.ul
D 4
Installation and Operation Guide.
E 4
I 4
Sendmail Installation and Operation Guide.
E 7
I 7
D 8
.%T Sendmail Installation and Operation Guide.
E 8
I 8
.%T "Sendmail Installation and Operation Guide" .
E 8
E 7
E 4
The options are:
D 7
.TP 1.2i
.RI A file
E 7
I 7
.Bl -tag -width Fl
.It Li A Ns Ar file
E 7
Use alternate alias file.
I 20
.It Li b Ns Ar nblocks
The minimum number of free blocks needed on the spool filesystem.
E 20
D 7
.TP 1.2i
c
E 7
I 7
.It Li c
E 7
On mailers that are considered ``expensive'' to connect to,
don't initiate immediate connection.
This requires queueing.
I 15
.It Li C Ar N
Checkpoint the queue file after every
.Ar N
successful deliveries (default 10).
This avoids excessive duplicate deliveries
when sending to long mailing lists
interrupted by system crashes.
I 27
.ne 1i
E 27
E 15
D 7
.TP 1.2i
.RI d x
E 7
I 7
.It Li d Ns Ar x
E 7
Set the delivery mode to
D 7
.I x.
E 7
I 7
.Ar x .
E 7
Delivery modes are
D 7
`i' for interactive (synchronous) delivery,
`b' for background (asynchronous) delivery,
E 7
I 7
.Ql i
for interactive (synchronous) delivery,
.Ql b
for background (asynchronous) delivery,
E 7
and
D 7
`q' for queue only \- i.e.,
E 7
I 7
.Ql q
for queue only \- i.e.,
E 7
actual delivery is done the next time the queue is run.
D 7
.TP 1.2i
D
E 7
I 7
.It Li D
E 7
Try to automatically rebuild the alias database
if necessary.
D 7
.TP 1.2i
.RI e x
E 7
I 7
.It Li e Ns Ar x
E 7
Set error processing to mode
D 7
.I x.
E 7
I 7
.Ar x .
E 7
Valid modes are
D 7
`m' to mail back the error message,
`w' to ``write'' back the error message
E 7
I 7
.Ql m
to mail back the error message,
.Ql w
to ``write'' back the error message
E 7
(or mail it back if the sender is not logged in),
D 7
`p' to print the errors on the terminal
E 7
I 7
.Ql p
to print the errors on the terminal
E 7
(default),
D 7
`q' to throw away error messages
E 7
I 7
.Ql q
to throw away error messages
E 7
(only exit status is returned),
D 7
and `e'
E 7
I 7
and
.Ql e
E 7
to do special processing for the BerkNet.
If the text of the message is not mailed back
by
D 7
modes `m' or `w'
E 7
I 7
modes
.Ql m
or
.Ql w
E 7
and if the sender is local to this machine,
a copy of the message is appended to the file
D 7
``dead.letter''
E 7
I 7
.Pa dead.letter
E 7
E 2
in the sender's home directory.
I 2
D 7
.TP 1.2i
.RI F mode
E 7
I 7
D 20
.It Li F Ns Ar mode
E 7
The mode to use when creating temporary files.
E 20
D 7
.TP 1.2i
f
Save UNIX-style From lines at the front of messages.
.TP 1.2i
.RI g N
E 7
I 7
.It Li f
Save
.Tn UNIX Ns \-style
From lines at the front of messages.
I 20
.It Li G
Match local mail names against the GECOS portion of the password file.
E 20
.It Li g Ar N
E 7
The default group id to use when calling mailers.
D 7
.TP 1.2i
.RI H file
The SMTP help file.
.TP 1.2i
i
E 7
I 7
.It Li H Ns Ar file
The
.Tn SMTP
help file.
I 15
.It Li h Ar N
The maximum number of times a message is allowed to ``hop''
before we decide it is in a loop.
E 15
.It Li i
E 7
Do not take dots on a line by themselves
as a message terminator.
I 20
.It Li j
Send error messages in MIME format.
.It Li K Ns Ar timeout
Set connection cache timeout.
.It Li k Ns Ar N
Set connection cache size.
E 20
I 11
D 15
.It Li k Ar N
Checkpoint the queue file after every
.Ar N
successful deliveries (default 10).
This avoids excessive duplicate deliveries
when sending to long mailing lists
interrupted by system crashes.
E 15
E 11
D 7
.TP 1.2i
.RI L n
E 7
I 7
.It Li L Ns Ar n
E 7
The log level.
I 20
.It Li l
Pay attention to the Errors-To: header.
E 20
D 7
.TP 1.2i
m
E 7
I 7
.It Li m
E 7
Send to ``me'' (the sender) also if I am in an alias expansion.
I 20
.It Li n
Validate the right hand side of aliases during a
.Xr newaliases 1
command.
E 20
D 7
.TP 1.2i
o
E 7
I 7
.It Li o
E 7
If set, this message may have
old style headers.
If not set,
this message is guaranteed to have new style headers
(i.e., commas instead of spaces between addresses).
If set, an adaptive algorithm is used that will correctly
determine the header format in most cases.
D 7
.TP 1.2i
.RI Q queuedir
E 7
I 7
.It Li Q Ns Ar queuedir
E 7
Select the directory in which to queue messages.
D 7
.TP 1.2i
.RI r timeout
E 7
I 7
D 20
.It Li r Ns Ar timeout
E 7
The timeout on reads;
if none is set,
D 7
.I sendmail
E 7
I 7
.Nm sendmail
E 7
will wait forever for a mailer.
I 4
D 7
This option violates the word (if not the intent) of the SMTP specification,
E 7
I 7
This option violates the word (if not the intent) of the
.Tn SMTP
specification,
E 7
show the timeout should probably be fairly large.
E 20
E 4
D 7
.TP 1.2i
.RI S file
E 7
I 7
.It Li S Ns Ar file
E 7
Save statistics in the named file.
D 7
.TP 1.2i
s
E 7
I 7
.It Li s
E 7
Always instantiate the queue file,
even under circumstances where it is not strictly necessary.
I 4
This provides safety against system crashes during delivery.
E 4
D 7
.TP 1.2i
.RI T time
E 7
I 7
.It Li T Ns Ar time
E 7
D 4
Set the timeout on messages in the queue to the specified time.
After sitting in the queue for this amount of time,
they will be returned to the sender.
E 4
I 4
Set the timeout on undelivered messages in the queue to the specified time.
After delivery has failed
(e.g., because of a host being down)
for this amount of time,
failed messages will be returned to the sender.
E 4
The default is three days.
D 7
.TP 1.2i
.RI t stz,dtz
E 7
I 7
.It Li t Ns Ar stz , Ar dtz
E 7
Set the name of the time zone.
I 12
.It Li U Ns Ar userdatabase
If set, a user database is consulted to get forwarding information.
You can consider this an adjunct to the aliasing mechanism,
except that the database is intended to be distributed;
aliases are local to a particular host.
This may not be available if your sendmail does not have the
D 13
USERDB option compiled in.
E 13
I 13
.Dv USERDB
option compiled in.
E 13
E 12
D 7
.TP 1.2i
.RI u N
E 7
I 7
.It Li u Ns Ar N
E 7
Set the default user id for mailers.
I 11
D 20
.It Li w
D 14
If not set, name server lookups will us a querytype of ANY
E 14
I 14
If set, name server lookups will us a querytype of ANY
E 14
to find types
D 13
CNAME, A, and MX,
E 13
I 13
.Dv CNAME , A ,
and
.Dv MX ,
E 13
and will cause all existing records to be cached by our local server.
D 14
If there is (might be) a wildcard MX in the local domain
or its parents that are searched, you
.ul
must
D 13
set this option, which will use a querytype of CNAME only;
E 13
I 13
set this option, which will use a querytype of
E 14
I 14
If you are certain that there are no wildcard MX records in the local domain
or its parents that are searched, you can
set this option.
If the option is not set,
name server lookups will use a querytype of
E 14
.Dv CNAME
only;
E 13
otherwise, it would cause all fully-qualified names
to match as names in the local domain.
E 20
I 20
.It Li Y
Fork each job during queue runs.
May be convenient on memory-poor machines.
.It Li 7
Strip incoming messages to seven bits.
E 20
E 11
E 2
D 7
.PP
E 7
I 7
.El
.Pp
E 7
D 4
If the first character of the user name
is a vertical bar,
the rest of the user name is used as the name of a program
E 4
I 4
In aliases,
the first character of a name may be
a vertical bar to cause interpretation of
the rest of the name as a command
E 4
to pipe the mail to.
D 4
It may be necessary to quote the name of the user
E 4
I 4
It may be necessary to quote the name
E 4
to keep
D 2
.I delivermail
E 2
I 2
D 7
.I sendmail
E 7
I 7
.Nm sendmail
E 7
E 2
from suppressing the blanks from between arguments.
I 4
For example, a common alias is:
E 4
D 7
.PP
I 4
D 6
	msgs: "|/usr/ucb/msgs -s"
E 6
I 6
	msgs: "|/usr/bin/msgs -s"
E 6
.PP
Aliases may also have the syntax ``:include:\c
.IR filename ''
E 7
I 7
.Pp
.Bd -literal -offset indent -compact
msgs: "|/usr/bin/msgs -s"
.Ed
.Pp
Aliases may also have the syntax
.Dq :include: Ns Ar filename
E 7
to ask
D 7
.I sendmail
E 7
I 7
.Xr sendmail
E 7
to read the named file for a list of recipients.
For example, an alias such as:
D 7
.PP
	poets: ":include:/usr/local/lib/poets.list"
.PP
E 7
I 7
.Pp
.Bd -literal -offset indent -compact
poets: ":include:/usr/local/lib/poets.list"
.Ed
.Pp
E 7
would read
D 7
.I /usr/local/lib/poets.list
E 7
I 7
.Pa /usr/local/lib/poets.list
E 7
for the list of addresses making up the group.
D 7
.PP
E 4
D 2
The message is normally edited to eliminate \*(lqFrom\*(rq
lines that might confuse other mailers.
In particular,
\*(lqFrom\*(rq lines in the header are deleted,
and \*(lqFrom\*(rq lines in the body are prepended by `>'.
The
.B \-s
flag saves \*(lqFrom\*(rq lines in the header.
.PP
The
.B \-h
flag gives a \*(lqhop-count\*(rq, i.e.,
a measure of how many times this message
has been processed by
.I delivermail
(presumably on different machines).
Each time
.I delivermail
processes a message,
it increases the hop-count by one;
if it exceeds 30
.I delivermail
assumes that an alias loop has occurred
and it aborts the message.
The hop-count defaults to zero.
.PP
.I Delivermail
E 2
I 2
.I Sendmail
E 7
I 7
.Pp
.Nm Sendmail
E 7
E 2
returns an exit status
describing what it did.
D 2
The codes are defined in <sysexits.h>
E 2
I 2
The codes are defined in
D 7
.RI < sysexits.h >
E 2
.ta 3n +\w'EX_UNAVAILABLE'u+3n
.de XX
.ti \n(.iu
..
.in +\w'EX_UNAVAILABLE'u+6n
.XX
 	EX_OK	Successful completion on all addresses.
.XX
 	EX_NOUSER	User name not recognized.
.XX
 	EX_UNAVAILABLE	Catchall meaning necessary resources
E 7
I 7
.Aq Pa sysexits.h :
.Bl -tag -width EX_UNAVAILABLE -compact -offset indent
.It Dv EX_OK
Successful completion on all addresses.
.It Dv EX_NOUSER
User name not recognized.
.It Dv EX_UNAVAILABLE
Catchall meaning necessary resources
E 7
were not available.
D 7
.XX
 	EX_SYNTAX	Syntax error in address.
.XX
 	EX_SOFTWARE	Internal software error,
E 7
I 7
.It Dv EX_SYNTAX
Syntax error in address.
.It Dv EX_SOFTWARE
Internal software error,
E 7
including bad arguments.
D 7
.XX
 	EX_OSERR	Temporary operating system error,
such as \*(lqcannot fork\*(rq.
.XX
 	EX_NOHOST	Host name not recognized.
I 2
.XX
	EX_TEMPFAIL	Message could not be sent immediately,
E 7
I 7
.It Dv EX_OSERR
Temporary operating system error,
such as
.Dq cannot fork .
.It Dv EX_NOHOST
Host name not recognized.
.It Dv EX_TEMPFAIL
Message could not be sent immediately,
E 7
but was queued.
D 7
.PP
E 7
I 7
.El
.Pp
E 7
If invoked as
D 7
.I newaliases,
.I sendmail
E 7
I 7
.Nm newaliases ,
.Nm sendmail
E 7
will rebuild the alias database.
If invoked as
D 7
.I mailq,
.I sendmail
E 7
I 7
.Nm mailq ,
.Nm sendmail
E 7
will print the contents of the mail queue.
E 2
D 7
.SH FILES
I 2
Except for
D 6
/usr/lib/sendmail.cf,
E 6
I 6
/etc/sendmail.cf,
E 6
these pathnames are all specified in
D 6
/usr/lib/sendmail.cf.
E 6
I 6
/etc/sendmail.cf.
E 7
I 7
.Sh FILES
Except for the file
.Pa /etc/sendmail.cf
itself,
the following pathnames are all specified in
.Pa /etc/sendmail.cf.
E 7
E 6
Thus,
these values are only approximations.
D 7
.PP
E 2
.if t .ta 2i
.if n .ta 3i
D 6
/usr/lib/aliases	raw data for alias names
E 6
I 6
/etc/aliases	raw data for alias names
E 6
.br
I 2
D 6
/usr/lib/aliases.pag
E 6
I 6
/etc/aliases.pag
E 6
.br
E 2
D 6
/usr/lib/aliases.dir	data base of alias names
E 6
I 6
/etc/aliases.dir	data base of alias names
E 6
.br
D 2
/usr/lib/aliases.pag
E 2
I 2
D 6
/usr/lib/sendmail.cf	configuration file
E 6
I 6
/etc/sendmail.cf	configuration file
E 6
E 2
.br
D 2
/bin/mail	to deliver uucp mail
E 2
I 2
D 6
/usr/lib/sendmail.fc	frozen configuration
E 6
I 6
/etc/sendmail.fc	frozen configuration
E 6
E 2
.br
I 2
D 6
/usr/lib/sendmail.hf	help file
E 6
I 6
/usr/share/misc/sendmail.hf	help file
E 6
.br
D 6
/usr/lib/sendmail.st	collected statistics
E 6
I 6
/var/log/sendmail.st	collected statistics
E 6
.br
D 4
/usr/bin/uux	to deliver uucp mail
.br
E 2
/usr/net/bin/v6mail	to deliver local mail
.br
D 2
/usr/net/bin/sendmail	to deliver Berknet mail
E 2
I 2
/usr/net/bin/sendberkmail	to deliver Berknet mail
E 2
.br
/usr/lib/mailers/arpa	to deliver ARPANET mail
.br
E 4
D 2
/tmp/mail*	temp file
E 2
I 2
D 6
/usr/spool/mqueue/*	temp files
E 6
I 6
/var/spool/mqueue/*	temp files
E 6
E 2
D 4
.br
E 4
D 2
/tmp/xscript*	saved transcript
E 2
.SH SEE\ ALSO
D 2
biff(1), binmail(1), mail(1), newaliases(1), aliases(5)
E 2
I 2
D 4
biff(1), binmail(1), mail(1), aliases(5), sendmail.cf(5),
rmail(1), mailaddr(7);
E 4
I 4
D 5
binmail(1), mail(1), rmail(1),
syslog(3),
aliases(5), sendmail.cf(5),
mailaddr(7),
rc(8);
E 5
I 5
binmail(1), mail(1), rmail(1), syslog(3),
aliases(5), mailaddr(7), rc(8);
E 5
E 4
.br
DARPA Internet Request For Comments
RFC819, RFC821, RFC822;
.br
.ul
D 4
Sendmail \- An Internetwork Mail Router;
E 4
I 4
Sendmail \- An Internetwork Mail Router
(SMM:9);
E 4
.br
.ul
D 4
Sendmail Installation and Operation Guide.
E 2
.SH BUGS
D 2
.I Delivermail
sends one copy of the letter
to each user;
it should send one copy
of the letter to each host
and distribute to multiple users there
whenever possible.
.PP
.I Delivermail
assumes the addresses can be represented as one word.
E 2
I 2
.I Sendmail
converts blanks in addresses to dots.
E 2
This is incorrect according to the
I 2
old
E 2
.SM ARPANET
D 2
mail protocol RFC 733 (NIC 41952),
but is consistent with the real world.
E 2
I 2
mail protocol RFC733 (NIC 41952),
but is consistent with the
new protocols
(RFC822).
E 4
I 4
Sendmail Installation and Operation Guide
(SMM:8)
E 7
I 7
.Pp
.Bl -tag -width /usr/lib/sendmail.fc -compact
.It Pa /etc/aliases
raw data for alias names
D 20
.It Pa /etc/aliases.pag
.It Pa /etc/aliases.dir
E 20
I 20
.It Pa /etc/aliases.db
E 20
data base of alias names
.It Pa /etc/sendmail.cf
configuration file
D 25
.It Pa /etc/sendmail.fc
frozen configuration
E 25
.It Pa /etc/sendmail.hf
help file
.It Pa /var/log/sendmail.st
collected statistics
.It Pa /var/spool/mqueue/*
temp files
I 20
.It Pa /var/run/sendmail.pid
The process id of the daemon
E 20
.El
.Sh SEE ALSO
.Xr binmail 1 ,
.Xr mail 1 ,
.Xr rmail 1 ,
.Xr syslog 3 ,
.Xr aliases 5 ,
.Xr mailaddr 7 ,
.Xr rc 8 ;
.Pp
DARPA
Internet Request For Comments
.%T RFC819 ,
.%T RFC821 ,
.%T RFC822 .
.Rs
D 8
.%T Sendmail \- An Internetwork Mail Router
E 8
I 8
.%T "Sendmail \- An Internetwork Mail Router"
E 8
.%V SMM
.%N \&No. 9
.Re
.Rs
D 8
.%T Sendmail Installation and Operation Guide
E 8
I 8
.%T "Sendmail Installation and Operation Guide"
E 8
.%V SMM
.%N \&No. 8
.Re
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
E 7
E 4
E 2
E 1
