h39638
s 00084/00074/00050
d D 8.2 95/04/27 15:13:37 bostic 10 9
c convert edquota to mandoc format
c From: Charles Hannum <mycroft@sun-lamp.cs.berkeley.edu>
e
s 00002/00002/00122
d D 8.1 93/06/06 13:56:24 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00123
d D 6.7 91/08/01 01:33:13 cael 8 7
c fix typo (\fi should be \fI)
e
s 00001/00011/00123
d D 6.6 90/06/24 22:16:30 trent 7 6
c new copyright notice
e
s 00088/00021/00046
d D 6.5 90/05/06 14:33:58 mckusick 6 5
c update for new quota system
e
s 00010/00005/00057
d D 6.4 88/07/09 11:31:57 bostic 5 4
c install approved copyright notice
e
s 00008/00002/00054
d D 6.3 88/05/20 12:22:46 bostic 4 3
c add Berkeley specific header
e
s 00001/00001/00055
d D 6.2 86/05/19 19:15:02 karels 3 2
c spelling
e
s 00001/00001/00055
d D 6.1 85/04/27 14:55:35 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00056/00000/00000
d D 5.1 85/04/27 14:55:19 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1983 Regents of the University of California.
E 6
I 6
D 9
.\" Copyright (c) 1983, 1990 Regents of the University of California.
E 6
D 4
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
I 6
.\" This code is derived from software contributed to Berkeley by
.\" Robert Elz at The University of Melbourne.
.\"
E 6
D 7
.\" Redistribution and use in source and binary forms are permitted
D 5
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
E 5
I 5
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
E 5
E 4
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH EDQUOTA 8 "18 July 1983"
E 2
I 2
D 10
.TH EDQUOTA 8 "%Q%"
E 2
.UC 5
.SH NAME
edquota \- edit user quotas
.SH SYNOPSIS
.B edquota
[
D 6
.B \-p
.I proto-user
E 6
I 6
.I \-u
] [
.I \-p
proto-username
E 6
]
D 6
.IR users ...
E 6
I 6
username ...
.br
.B edquota
.I \-g
[
.I \-p
proto-groupname
]
groupname ...
.br
.B edquota
.I -t
[
.I -u
]
.br
.B edquota
.I -t
.I -g
.br
E 6
.SH DESCRIPTION
.I Edquota
D 6
is a quota editor.  One or more users
may be specified on the command line.
E 6
I 6
is a quota editor.
By default, or if the \fI-u\fP flag is specified,
E 10
I 10
.Dd "%Q%"
.Dt EDQUOTA 8
.Os
.Sh NAME
.Nm edquota
.Nd edit user quotas
.Sh SYNOPSIS
.Nm edquota
.Op Fl u
.Op Fl p Ar proto-username
.Ar username ...
.Nm edquota
.Fl g
.Op Fl p Ar proto-groupname
.Ar groupname ...
.Nm edquota
.Fl t
.Op Fl u
.Nm edquota
.Fl t
.Fl g
.Sh DESCRIPTION
.Nm Edquota
is a quota editor.  
By default, or if the 
.Fl u
flag is specified,
E 10
one or more users may be specified on the command line.
E 6
For each user a temporary file is created
with an ASCII representation of the current
D 6
disc quotas for that user and an editor is
then invoked on the file.  The quotas may then
be modified, new quotas added, etc.  Upon
leaving the editor,
E 6
I 6
disk quotas for that user.
The list of filesystems with user quotas is determined from
D 10
.IR /etc/fstab .
E 10
I 10
.Pa /etc/fstab .
E 10
An editor is invoked on the ASCII file.
The editor invoked is 
D 10
.IR vi (1)
unless the environment variable EDITOR specifies otherwise.
.PP
E 10
I 10
.Xr vi 1
unless the environment variable 
.Ev EDITOR 
specifies otherwise.
.Pp
E 10
The quotas may then be modified, new quotas added, etc.
Setting a quota to zero indicates that no quota should be imposed.
Setting a hard limit to one indicates that no allocations should
be permitted.
Setting a soft limit to one with a hard limit of zero
indicates that allocations should be permitted on
D 10
only a temporary basis (see \fI-t\fP below).
E 10
I 10
only a temporary basis (see 
.Fl t 
below).
E 10
The current usage information in the file is for informational purposes;
only the hard and soft limits can be changed.
D 10
.PP
E 10
I 10
.Pp
E 10
On leaving the editor,
E 6
D 10
.I edquota
E 10
I 10
.Nm edquota
E 10
reads the temporary file and modifies the binary
quota files to reflect the changes made.
D 10
.PP
E 10
I 10
.Pp
E 10
If the 
D 10
.B \-p
option is specified,
.I edquota
E 10
I 10
.Fl p
flag is specified,
.Nm edquota
E 10
will duplicate the quotas of the prototypical user
D 6
specified for each user specified.  This is the normal
mechanism used to initialize quotas for groups
of users.
E 6
I 6
specified for each user specified.
This is the normal mechanism used to
initialize quotas for groups of users.
E 6
D 10
.PP
D 6
The editor invoked is 
.IR vi (1)
unless the environment variable EDITOR specifies otherwise.
E 6
I 6
If the \fI-g\fP flag is specified,
.I edquota
E 10
I 10
.Pp
If the 
.Fl g 
flag is specified,
.Nm edquota
E 10
is invoked to edit the quotas of
one or more groups specified on the command line.
D 10
The \fI-p\fP flag can be specified in conjunction with
the \fI-g\fP flag to specify a prototypical group
E 10
I 10
The 
.Fl p 
flag can be specified in conjunction with
the 
.Fl g 
flag to specify a prototypical group
E 10
to be duplicated among the listed set of groups.
E 6
D 10
.PP
E 10
I 10
.Pp
E 10
I 6
Users are permitted to exceed their soft limits
for a grace period that may be specified per filesystem.
Once the grace period has expired,
the soft limit is enforced as a hard limit.
The default grace period for a filesystem is specified in
D 10
.IR /usr/include/ufs/quota.h .
D 8
The \fi-t\fP flag can be used to change the grace period.
E 8
I 8
The \fI-t\fP flag can be used to change the grace period.
E 8
By default, or when invoked with the \fI-u\fP flag,
the grace period is set for all the filesystems with user
E 10
I 10
.Pa /usr/include/ufs/ufs/quota.h .
The 
.Fl t
flag can be used to change the grace period.
By default, or when invoked with the 
.Fl u
flag, the grace period is set for all the filesystems with user
E 10
quotas specified in
D 10
.IR /etc/fstab .
When invoked with the \fI-g\fP flag the grace period is
E 10
I 10
.Pa /etc/fstab .
When invoked with the 
.Fl g
flag the grace period is
E 10
set for all the filesystems with group quotas specified in
D 10
.IR /etc/fstab .
E 10
I 10
.Pa /etc/fstab .
E 10
The grace period may be specified in days, hours, minutes, or seconds.
Setting a grace period to zero indicates that the default
grace period should be imposed.
Setting a grace period to one second indicates that no
grace period should be granted.
D 10
.PP
E 10
I 10
.Pp
E 10
E 6
Only the super-user may edit quotas.
D 10
.SH FILES
.DT
D 6
\fIquotas\fP		at the root of each file system with quotas
E 6
I 6
\fIquota.user\fP	at the filesystem root with user quotas
E 6
.br
D 6
/etc/fstab	to find file system names and locations
E 6
I 6
\fIquota.group\fP	at the filesystem root with group quotas
.br
/etc/fstab	to find filesystem names and locations
E 6
.SH SEE ALSO
D 6
quota(1), quota(2), quotacheck(8), quotaon(8), repquota(8)
E 6
I 6
quota(1),
quotactl(2),
fstab(5),
quotacheck(8), quotaon(8), repquota(8)
E 6
.SH DIAGNOSTICS
E 10
I 10
.Sh FILES
.Bl -tag -width 24n -compact
.It Pa quota.user
at the filesystem root with user quotas
.It Pa quota.group
at the filesystem root with group quotas
.It Pa /etc/fstab
to find filesystem names and locations
.El
.Sh SEE ALSO
.Xr quota 1 ,
.Xr quotactl 2 ,
.Xr fstab 5 ,
.Xr quotacheck 8 ,
.Xr quotaon 8 ,
.Xr repquota 8
.Sh DIAGNOSTICS
E 10
Various messages about inaccessible files; self-explanatory.
D 6
.SH BUGS
D 3
The format of the temporary file is inscruitable.
E 3
I 3
The format of the temporary file is inscrutable.
E 6
E 3
E 1
