h37177
s 00002/00002/00098
d D 8.1 93/06/04 13:13:29 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00066/00067/00034
d D 6.9 91/03/10 23:36:55 cael 10 9
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00100
d D 6.8 90/06/23 17:48:27 trent 9 8
c new copyright notice
e
s 00014/00003/00097
d D 6.7 89/02/14 17:52:38 bostic 8 7
c add Berkeley specific copyright notice
e
s 00002/00002/00098
d D 6.6 86/05/22 11:51:29 anne 7 6
c grammar
e
s 00000/00005/00100
d D 6.5 86/05/13 10:25:54 karels 6 5
c remove unix domain change notices
e
s 00001/00001/00104
d D 6.4 86/03/29 05:08:45 lepreau 5 4
c spelling
e
s 00001/00001/00104
d D 6.3 85/06/28 16:19:25 sechrest 4 3
c Improved English
e
s 00028/00000/00077
d D 6.2 85/05/22 18:31:40 mckusick 3 2
c update the error return codes to reflect those in 4.3BSD
e
s 00001/00001/00076
d D 6.1 85/05/15 11:52:50 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00077/00000/00000
d D 5.1 85/05/15 11:52:44 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 8
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 8
I 8
D 11
.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1983, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
.\"
D 9
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 9
I 9
.\" %sccs.include.redist.man%
E 9
E 8
.\"
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
.\"     %W% (Berkeley) %G%
E 10
.\"
D 2
.TH BIND 2 "27 July 1983"
E 2
I 2
D 10
.TH BIND 2 "%Q%"
E 2
.UC 5
.SH NAME
bind \- bind a name to a socket
.SH SYNOPSIS
.nf
.ft B
#include <sys/types.h>
#include <sys/socket.h>
.PP
.ft B
bind(s, name, namelen)
int s;
struct sockaddr *name;
int namelen;
.fi
.SH DESCRIPTION
.I Bind
E 10
I 10
.Dd %Q%
.Dt BIND 2
.Os BSD 4.2
.Sh NAME
.Nm bind
.Nd bind a name to a socket
.Sh SYNOPSIS
.Fd #include <sys/types.h>
.Fd #include <sys/socket.h>
.Ft int
.Fn bind "int s" "struct sockaddr *name" "int namelen"
.Sh DESCRIPTION
.Fn Bind
E 10
assigns a name to an unnamed socket.
When a socket is created 
with
D 10
.IR socket (2)
E 10
I 10
.Xr socket 2
E 10
it exists in a name space (address family)
but has no name assigned.
D 10
.I Bind
E 10
I 10
.Fn Bind
E 10
D 7
requests the
.IR name ,
E 7
I 7
requests that
D 10
.IR name 
E 10
I 10
.Fa name
E 10
E 7
be assigned to the socket.
D 10
.SH NOTES
E 10
I 10
.Sh NOTES
E 10
Binding a name in the UNIX domain creates a socket in the file
D 4
system which must be deleted by the caller when it is no longer
E 4
I 4
system that must be deleted by the caller when it is no longer
E 4
needed (using
D 10
.IR unlink (2)).
D 6
The file created
is a side-effect of the current implementation,
and will not be created in future versions
of the UNIX ipc domain.
E 6
.PP
E 10
I 10
.Xr unlink 2 ) .
.Pp
E 10
The rules used in name binding vary between communication domains.
Consult the manual entries in section 4 for detailed information.
D 10
.SH "RETURN VALUE
E 10
I 10
.Sh RETURN VALUES
E 10
If the bind is successful, a 0 value is returned.
D 10
A return value of \-1 indicates an error, which is
further specified in the global \fIerrno\fP.
.SH ERRORS
The \fIbind\fP call will fail if:
.TP 20
[EBADF]
\fIS\fP is not a valid descriptor.
.TP 20
[ENOTSOCK]
\fIS\fP is not a socket.
.TP 20
[EADDRNOTAVAIL]
E 10
I 10
A return value of -1 indicates an error, which is
further specified in the global
.Va errno .
.Sh ERRORS
The
.Fn bind
call will fail if:
.Bl -tag -width EADDRNOTAVA
.It Bq Er EBADF
.Fa S
is not a valid descriptor.
.It Bq Er ENOTSOCK
.Fa S
is not a socket.
.It Bq Er EADDRNOTAVAIL
E 10
The specified address is not available from the local machine.
D 10
.TP 20
[EADDRINUSE]
E 10
I 10
.It Bq Er EADDRINUSE
E 10
The specified address is already in use.
D 10
.TP 20
[EINVAL]
E 10
I 10
.It Bq Er EINVAL
E 10
The socket is already bound to an address.
D 10
.TP 20
D 5
[EACCESS]
E 5
I 5
[EACCES]
E 10
I 10
.It Bq Er EACCES
E 10
E 5
The requested address is protected, and the current user
has inadequate permission to access it.
D 10
.TP 20
[EFAULT]
The \fIname\fP parameter is not in a valid part of the user
E 10
I 10
.It Bq Er EFAULT
The
.Fa name
parameter is not in a valid part of the user
E 10
address space.
I 3
D 10
.PP
E 10
I 10
.El
.Pp
E 10
The following errors are specific to binding names in the UNIX domain.
D 6
These errors may not apply in future versions of the UNIX ipc domain.
E 6
D 10
.TP 15
[ENOTDIR]
E 10
I 10
.Bl -tag -width EADDRNOTAVA
.It Bq Er ENOTDIR
E 10
A component of the path prefix is not a directory.
D 10
.TP 15
[EINVAL]
E 10
I 10
.It Bq Er EINVAL
E 10
The pathname contains a character with the high-order bit set.
D 10
.TP 15
[ENAMETOOLONG]
E 10
I 10
.It Bq Er ENAMETOOLONG
E 10
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
D 10
.TP 15
[ENOENT]
E 10
I 10
.It Bq Er ENOENT
E 10
A prefix component of the path name does not exist.
D 10
.TP 15
[ELOOP]
E 10
I 10
.It Bq Er ELOOP
E 10
Too many symbolic links were encountered in translating the pathname.
D 10
.TP 15
[EIO]
E 10
I 10
.It Bq Er EIO
E 10
An I/O error occurred while making the directory entry or allocating the inode.
D 10
.TP 15
[EROFS]
E 10
I 10
.It Bq Er EROFS
E 10
The name would reside on a read-only file system.
D 10
.TP 15
[EISDIR]
A null pathname was specified.
E 3
.SH SEE ALSO
connect(2), listen(2), socket(2), getsockname(2)
E 10
I 10
.It Bq Er EISDIR
An empty pathname was specified.
.El
.Sh SEE ALSO
.Xr connect 2 ,
.Xr listen 2 ,
.Xr socket 2 ,
.Xr getsockname 2
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 10
E 1
