h11716
s 00003/00001/00130
d D 8.3 95/05/02 15:32:58 mckusick 14 13
c note that attempts by the non-super-user to set the super-user only flags
c are silently ignored (from pendry)
e
s 00005/00002/00126
d D 8.2 94/07/28 03:38:35 pendry 13 12
c changes for whiteouts and union filesystem
e
s 00002/00002/00126
d D 8.1 93/06/09 18:56:27 bostic 12 11
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00002/00127
d D 6.10 93/06/09 18:56:23 bostic 11 9
c fixed the under development line
e
s 00002/00002/00127
d R 8.1 93/06/04 13:13:41 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00010/00010/00119
d D 6.9 93/03/04 15:51:27 bostic 9 8
c rename file flags to UF_* and SF_*, minimize name space problems
e
s 00038/00008/00091
d D 6.8 93/03/03 20:05:17 bostic 8 7
c don't use octal modes, list the #defines; describe system flag behavior
e
s 00003/00002/00096
d D 6.7 93/03/03 17:53:49 bostic 7 6
c needs stat.h, flags are longs
e
s 00001/00001/00097
d D 6.6 91/07/25 17:42:12 cael 6 5
c fix misspelling
e
s 00014/00007/00084
d D 6.5 91/07/23 14:21:17 cael 5 4
c .Os changes, miscellaneous cleanups
e
s 00058/00065/00033
d D 6.4 91/03/10 23:37:05 cael 4 3
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00097
d D 6.3 90/06/23 17:45:24 trent 3 2
c new copyright notice
e
s 00001/00001/00107
d D 6.2 90/03/07 17:33:19 mckusick 2 1
c minor error inspec
e
s 00108/00000/00000
d D 6.1 89/06/06 23:17:26 mckusick 1 0
c date and time created 89/06/06 23:17:26 by mckusick
e
u
U
t
T
I 1
D 12
.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
E 12
I 12
.\" Copyright (c) 1989, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 12
.\"
D 3
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 3
I 3
D 5
.\" %sccs.include.redist.man%
E 5
I 5
.\" %sccs.include.redist.roff%
E 5
E 3
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\"     %W% (Berkeley) %G%
E 5
I 5
.\"	%W% (Berkeley) %G%
E 5
E 4
.\"
D 4
.TH CHFALGS 2 "%Q%"
.UC 7
.SH NAME
chflags, fchflags \- set file flags
.SH SYNOPSIS
.nf
.ft B
chflags(path, flags)
char *path;
long flags;
.LP
.ft B
fchflags(fd, flags)
int fd;
long flags;
.fi
.ft R
.SH DESCRIPTION
E 4
I 4
.Dd %Q%
D 6
.Dt CHFALGS 2
E 6
I 6
.Dt CHFLAGS 2
E 6
D 5
.Os BSD 4.4
E 5
I 5
.Os
E 5
.Sh NAME
.Nm chflags ,
.Nm fchflags
.Nd set file flags
.Sh SYNOPSIS
I 7
.Fd #include <sys/stat.h>
E 7
.Fd #include <unistd.h>
.Ft int
D 7
.Fn chflags "const char *path"  "long flags"
E 7
I 7
.Fn chflags "const char *path"  "u_long flags"
E 7
.Ft int
D 7
.Fn fchflags "int fd" "long flags"
E 7
I 7
.Fn fchflags "int fd" "u_long flags"
E 7
.Sh DESCRIPTION
E 4
The file whose name
D 4
is given by \fIpath\fP
E 4
I 4
is given by
.Fa path
E 4
or referenced by the descriptor
D 4
.I fd
E 4
I 4
.Fa fd
E 4
has its flags changed to
D 4
.IR flags .
.PP
E 4
I 4
.Fa flags .
.Pp
E 4
D 8
Only the owner of a file (or the super-user) may change the flags.
The owner may only change the lower 16 bits of the flags;
the super-user may change all 32 bits of the flags.
E 8
I 8
The flags specified are formed by
.Em or Ns 'ing
the following values
.Pp
D 9
.Bl -tag -width "SYS_IMMUTABLE" -compact -offset indent
.It NODUMP
E 9
I 9
.Bl -tag -width "SF_IMMUTABLE" -compact -offset indent
.It UF_NODUMP
E 9
Do not dump the file.
D 9
.It USR_IMMUTABLE
E 9
I 9
.It UF_IMMUTABLE
E 9
The file may not be changed.
D 9
.It USR_APPEND
E 9
I 9
.It UF_APPEND
E 9
The file may only be appended to.
I 13
.It UF_OPAQUE
The directory is opaque when viewed through a union stack.
E 13
.\".It ARCHIVED
.\"File is archived.
D 9
.It SYS_IMMUTABLE
E 9
I 9
.It SF_IMMUTABLE
E 9
The file may not be changed.
D 9
.It SYS_APPEND
E 9
I 9
.It SF_APPEND
E 9
The file may only be appended to.
.El
.Pp
The
D 9
.Dq USR_IMMUTABLE
E 9
I 9
.Dq UF_IMMUTABLE
E 9
and
D 9
.Dq USR_APPEND
E 9
I 9
.Dq UF_APPEND
E 9
flags may be set or unset by either the owner of a file or the super-user.
.Pp
The
D 9
.Dq SYS_IMMUTABLE
E 9
I 9
.Dq SF_IMMUTABLE
E 9
and
D 9
.Dq SYS_APPEND
E 9
I 9
.Dq SF_APPEND
E 9
flags may only be set or unset by the super-user.
D 14
They may be set at any time, but normally may only be unset when
E 14
I 14
Attempts by the non-super-user to set the super-user only flags
are silently ignored.
These flags may be set at any time, but normally may only be unset when
E 14
the system is in single-user mode.
(See
.Xr init 8
for details.)
E 8
D 4
.SH RETURN VALUE
E 4
I 4
.Sh RETURN VALUES
E 4
Upon successful completion, a value of 0 is returned.
D 4
Otherwise, \-1 is returned and the global variable
.I errno
E 4
I 4
Otherwise, -1 is returned and the global variable
.Va errno
E 4
is set to indicate the error.
D 4
.SH ERRORS
.I Chflags
fails if one or more of the following are true:
.TP 15
[ENOTDIR]
E 4
I 4
.Sh ERRORS
.Fn Chflags
D 8
fails if:
E 8
I 8
will fail it:
E 8
.Bl -tag -width Er
.It Bq Er ENOTDIR
E 4
A component of the path prefix is not a directory.
D 4
.TP 15
[EINVAL]
E 4
I 4
.It Bq Er EINVAL
E 4
The pathname contains a character with the high-order bit set.
D 4
.TP 15
[ENAMETOOLONG]
E 4
I 4
.It Bq Er ENAMETOOLONG
E 4
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
D 4
.TP 15
[ENOENT]
E 4
I 4
.It Bq Er ENOENT
E 4
The named file does not exist.
D 4
.TP 15
[EACCES]
E 4
I 4
.It Bq Er EACCES
E 4
Search permission is denied for a component of the path prefix.
D 4
.TP 15
[ELOOP]
E 4
I 4
.It Bq Er ELOOP
E 4
Too many symbolic links were encountered in translating the pathname.
D 4
.TP 15
[EPERM]
E 4
I 4
.It Bq Er EPERM
E 4
The effective user ID does not match the owner of the file and
the effective user ID is not the super-user.
D 4
.TP 15
[EROFS]
E 4
I 4
.It Bq Er EROFS
E 4
The named file resides on a read-only file system.
D 4
.TP 15
[EFAULT]
.I Path
E 4
I 4
.It Bq Er EFAULT
.Fa Path
E 4
points outside the process's allocated address space.
D 4
.TP 15
[EIO]
E 4
I 4
.It Bq Er EIO
E 4
D 5
An I/O error occurred while reading from or writing to the file system.
E 5
I 5
An
.Tn I/O
error occurred while reading from or writing to the file system.
E 5
D 4
.PP
D 2
.I Fchmod
E 2
I 2
.I Fchflags
E 4
I 4
.El
.Pp
.Fn Fchflags
E 4
E 2
will fail if:
D 4
.TP 15
[EBADF]
E 4
I 4
.Bl -tag -width Er
.It Bq Er EBADF
E 4
The descriptor is not valid.
D 4
.TP 15
[EINVAL]
.I Fd
E 4
I 4
.It Bq Er EINVAL
.Fa Fd
E 4
refers to a socket, not to a file.
D 4
.TP 15
[EPERM]
E 4
I 4
.It Bq Er EPERM
E 4
The effective user ID does not match the owner of the file and
the effective user ID is not the super-user.
D 4
.TP 15
[EROFS]
E 4
I 4
.It Bq Er EROFS
E 4
The file resides on a read-only file system.
D 4
.TP 15
[EIO]
E 4
I 4
.It Bq Er EIO
E 4
D 5
An I/O error occurred while reading from or writing to the file system.
E 5
I 5
An
.Tn I/O
error occurred while reading from or writing to the file system.
E 5
D 4
.SH "SEE ALSO"
chmod(2), open(2), chown(2), stat(2)
E 4
I 4
.El
.Sh SEE ALSO
D 8
.Xr chmod 2 ,
.Xr open 2 ,
.Xr chown 2 ,
.Xr stat 2
E 8
I 8
D 13
.Xr chflags 1,
.Xr init 8
E 13
I 13
.Xr chflags 1 ,
.Xr init 8 ,
.Xr mount_union 8
E 13
E 8
.Sh HISTORY
The
D 5
.Nm
function call is currently under development.
E 5
I 5
.Nm chflags
and
.Nm fchflags
D 11
function calls are
.Ud .
E 11
I 11
functions first appeared in 4.4BSD.
E 11
E 5
E 4
E 1
