h09535
s 00002/00002/00068
d D 8.1 93/06/09 18:55:01 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00002/00068
d D 6.6 93/06/09 18:54:58 bostic 7 5
c fixed the under development line
e
s 00002/00002/00068
d R 8.1 93/06/04 13:15:17 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00069
d D 6.5 91/11/27 10:47:51 bostic 5 4
c fhandle_t is a structure itself.
e
s 00009/00006/00061
d D 6.4 91/07/23 14:21:16 cael 4 3
c .Os changes, miscellaneous cleanups
e
s 00043/00050/00024
d D 6.3 91/03/10 23:37:55 cael 3 2
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00073
d D 6.2 90/06/23 17:46:03 trent 2 1
c new copyright notice
e
s 00084/00000/00000
d D 6.1 89/07/02 20:11:51 mckusick 1 0
c date and time created 89/07/02 20:11:51 by mckusick
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1989 The Regents of the University of California.
E 3
I 3
D 8
.\" Copyright (c) 1989, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
D 2
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 2
I 2
D 4
.\" %sccs.include.redist.man%
E 4
I 4
.\" %sccs.include.redist.roff%
E 4
E 2
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
D 4
.\"     %W% (Berkeley) %G%
E 4
I 4
.\"	%W% (Berkeley) %G%
E 4
E 3
.\"
D 3
.TH GETFH 2 "%Q%"
.UC 7
.SH NAME
getfh \- get file handle
.SH SYNOPSIS
.nf
.ft B
#include <sys/types.h>
#include <sys/mount.h>
.LP
.ft B
getfh(path, fhp)
char *path;
struct fhandle_t *fhp;
.fi
.ft R
.SH DESCRIPTION
.I Getfh
E 3
I 3
.Dd %Q%
.Dt GETFH 2
D 4
.Os BSD 4.4
E 4
I 4
.Os
E 4
.Sh NAME
.Nm getfh
.Nd get file handle
.Sh SYNOPSIS
.Fd #include <sys/types.h>
.Fd #include <sys/mount.h>
.Ft int
D 5
.Fn getfh "char *path" "struct fhandle_t *fhp"
E 5
I 5
.Fn getfh "char *path" "fhandle_t *fhp"
E 5
.Sh DESCRIPTION
.Fn Getfh
E 3
returns a file handle for the specified file or directory
in the file handle pointed to by
D 3
.I fhp .
E 3
I 3
.Fa fhp .
E 3
This system call is restricted to the superuser.
D 3
.SH RETURN VALUE
E 3
I 3
.Sh RETURN VALUES
E 3
Upon successful completion, a value of 0 is returned.
D 3
Otherwise, \-1 is returned and the global variable
.I errno
E 3
I 3
Otherwise, -1 is returned and the global variable
.Va errno
E 3
is set to indicate the error.
D 3
.SH ERRORS
.I Getfh
E 3
I 3
.Sh ERRORS
.Fn Getfh
E 3
fails if one or more of the following are true:
D 3
.TP 15
ENOTDIR
E 3
I 3
.Bl -tag -width Er
.It Bq ENOTDIR
E 3
A component of the path prefix of
D 3
.I path
E 3
I 3
.Fa path
E 3
is not a directory.
D 3
.TP 15
EINVAL
.I path
E 3
I 3
.It Bq EINVAL
.Fa path
E 3
contains a character with the high-order bit set.
D 3
.TP 15
ENAMETOOLONG
E 3
I 3
.It Bq ENAMETOOLONG
E 3
The length of a component of
D 3
.I path
E 3
I 3
.Fa path
E 3
exceeds 255 characters,
or the length of
D 3
.I path
E 3
I 3
.Fa path
E 3
exceeds 1023 characters.
D 3
.TP 15
ENOENT
E 3
I 3
.It Bq ENOENT
E 3
The file referred to by
D 3
.I path
E 3
I 3
.Fa path
E 3
does not exist.
D 3
.TP 15
EACCES
E 3
I 3
.It Bq EACCES
E 3
Search permission is denied for a component of the path prefix of
D 3
.IR path .
.TP 15
ELOOP
E 3
I 3
.Fa path .
.It Bq ELOOP
E 3
Too many symbolic links were encountered in translating
D 3
.IR path .
.TP 15
EFAULT
.I Fhp
E 3
I 3
.Fa path .
.It Bq EFAULT
.Fa Fhp
E 3
points to an invalid address.
D 3
.TP 15
EIO
E 3
I 3
.It Bq EIO
E 3
D 4
An I/O error occurred while reading from or writing to the file system.
E 4
I 4
An
.Tn I/O
error occurred while reading from or writing to the file system.
E 4
I 3
.El
.Sh HISTORY
The
D 4
.Nm
function call is currently under development.
E 4
I 4
.Nm getfh
D 7
function call is
.Ud .
E 7
I 7
function
first appeared in 4.4BSD.
E 7
E 4
E 3
E 1
