h43220
s 00002/00001/00073
d D 8.2 93/12/11 23:08:20 mckusick 8 7
c copyediting for Usenix manuals
e
s 00002/00002/00072
d D 8.1 93/06/04 13:16:47 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00051/00039/00023
d D 6.5 91/03/10 23:39:16 cael 6 5
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00061
d D 6.4 90/06/23 17:46:59 trent 5 4
c new copyright notice
e
s 00014/00003/00058
d D 6.3 89/02/14 17:52:47 bostic 4 3
c add Berkeley specific copyright notice
e
s 00008/00005/00053
d D 6.2 86/05/14 10:03:23 karels 3 2
c fixes and updates
e
s 00001/00001/00057
d D 6.1 85/05/15 11:57:13 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00058/00000/00000
d D 5.1 85/05/15 11:57:02 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
E 4
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH LISTEN 2 "12 February 1983"
E 2
I 2
D 6
.TH LISTEN 2 "%Q%"
E 2
.UC 5
.SH NAME
listen \- listen for connections on a socket
.SH SYNOPSIS
.nf
.ft B
listen(s, backlog)
int s, backlog;
.fi
.SH DESCRIPTION
E 6
I 6
.Dd %Q%
.Dt LISTEN 2
.Os BSD 4.2
.Sh NAME
.Nm listen
.Nd listen for connections on a socket
.Sh SYNOPSIS
.Fd #include <sys/socket.h>
.Ft int
.Fn listen "int s" "int backlog"
.Sh DESCRIPTION
E 6
To accept connections, a socket
is first created with
D 6
.IR socket (2),
E 6
I 6
.Xr socket 2 ,
E 6
D 3
a backlog for incoming connections is specified with
.IR listen (2)
E 3
I 3
a willingness to accept incoming connections and
a queue limit for incoming connections are specified with
D 6
.IR listen (2),
E 6
I 6
.Fn listen ,
E 6
E 3
and then the connections are
accepted with
D 6
.IR accept (2).
E 6
I 6
.Xr accept 2 .
E 6
The
D 6
.I listen
E 6
I 6
.Fn listen
E 6
call applies only to sockets of type
D 6
SOCK_STREAM
E 6
I 6
.Dv SOCK_STREAM
E 6
or
D 3
SOCK_PKTSTREAM.
E 3
I 3
D 6
SOCK_SEQPACKET.
E 3
.PP
E 6
I 6
.Dv SOCK_SEQPACKET.
.Pp
E 6
The
D 6
.I backlog
E 6
I 6
.Fa backlog
E 6
parameter defines the maximum length the queue of
pending connections may grow to.
If a connection
D 3
request arrives with the queue full the client will
receive an error with an indication of ECONNREFUSED.
E 3
I 3
request arrives with the queue full the client may
D 6
receive an error with an indication of ECONNREFUSED,
E 6
I 6
receive an error with an indication of
.Er ECONNREFUSED ,
E 6
or, if the underlying protocol supports retransmission,
the request may be ignored so that retries may succeed.
E 3
D 6
.SH "RETURN VALUE
A 0 return value indicates success; \-1 indicates an error.
.SH "ERRORS
The call fails if:
.TP 20
[EBADF]
The argument \fIs\fP is not a valid descriptor.
.TP 20
[ENOTSOCK]
The argument \fIs\fP is not a socket.
.TP 20
[EOPNOTSUPP]
The socket is not of a type that supports the operation \fIlisten\fP.
.SH "SEE ALSO"
accept(2), connect(2), socket(2)
.SH BUGS
E 6
I 6
.Sh RETURN VALUES
A 0 return value indicates success; -1 indicates an error.
.Sh ERRORS
D 8
.Fn Listen will fail if:
E 8
I 8
.Fn Listen 
will fail if:
E 8
.Bl -tag -width [EOPNOTSUPP]
.It Bq Er EBADF
The argument
.Fa s
is not a valid descriptor.
.It Bq Er ENOTSOCK
The argument
.Fa s
is not a socket.
.It Bq Er EOPNOTSUPP
The socket is not of a type that supports the operation
.Fn listen .
.El
.Sh SEE ALSO
.Xr accept 2 ,
.Xr connect 2 ,
.Xr socket 2
.Sh BUGS
E 6
The
D 6
.I backlog
E 6
I 6
.Fa backlog
E 6
is currently limited (silently) to 5.
I 6
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 6
E 1
