h15131
s 00017/00000/00047
d D 8.2 94/06/21 09:41:51 mckusick 6 5
c add an errors section
e
s 00002/00002/00045
d D 8.1 93/06/09 18:58:34 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00003/00046
d D 6.3 93/06/09 18:58:31 bostic 4 2
c fixed the under development line
e
s 00002/00002/00047
d R 8.1 93/06/04 13:18:08 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00037/00020/00012
d D 6.2 91/08/07 03:36:39 cael 2 1
c mdoc version three
e
s 00032/00000/00000
d D 6.1 91/05/27 21:44:44 mckusick 1 0
c date and time created 91/05/27 21:44:44 by mckusick
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1991 Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1991, 1991 Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
D 2
.\" %sccs.include.redist.man%
E 2
I 2
.\" %sccs.include.redist.roff%
E 2
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH MSYNC 2 "%Q%"
.UC 7
.SH NAME
msync \- synchronize a mapped region
.SH SYNOPSIS
.nf
msync(addr, len)
.B caddr_t addr;
.B int len;
.fi
.SH DESCRIPTION
.PP
The \fImsync\fP system call
E 2
I 2
.Dd %Q%
.Dt MSYNC 2
.Os
.Sh NAME
.Nm msync
.Nd synchronize a mapped region
.Sh SYNOPSIS
.Fn msync "caddr_t addr" "int len"
.Sh DESCRIPTION
The
.Fn msync
system call
E 2
writes any modified pages back to the filesystem and updates
the file modification time.
D 2
If \fIlen\fP is 0, all modified pages within the region containing \fIaddr\fP
E 2
I 2
If
.Fa len
is 0, all modified pages within the region containing
.Fa addr
E 2
will be flushed;
D 2
if \fIlen\fP is non-zero, only the pages containing \fIaddr\fP and \fIlen\fP
E 2
I 2
if
.Fa len
is non-zero, only the pages containing
.Fa addr
and
.Fa len
E 2
succeeding locations will be examined.
Any required synchronization of memory caches
will also take place at this time.
Filesystem operations on a file that is mapped for shared modifications
D 2
are unpredictable except after an \fImsync\fP.
.SH "SEE ALSO"
msync.2, munmap.2, mprotect.2, madvise.2, mincore.2
E 2
I 2
are unpredictable except after an
.Fn msync .
I 6
.Sh ERRORS
The following errors may be reported:
.Bl -tag -width Er
.It Bq Er EINVAL
The
.Fa addr
parameter was not page aligned.
.It Bq Er EINVAL
The
.Fa addr
parameter did not specify an address part of a mapped region.
.It Bq Er EINVAL
The
.Fa len
parameter was negative.
.It Bq Er EIO
An I/O error occured while writing to the file system.
E 6
.Sh SEE ALSO
.Xr madvise 2 ,
.Xr munmap 2 ,
.Xr mprotect 2 ,
.Xr mincore 2
.Sh HISTORY
The
.Fn msync
D 4
function call is
.Ud .

E 4
I 4
function first appeared in 4.4BSD.
E 4
E 2
E 1
