h01081
s 00002/00002/00050
d D 8.3 94/05/27 15:42:20 hibler 8 7
c don't require the range to be completely allocated
e
s 00023/00002/00029
d D 8.2 94/04/15 17:05:37 mckusick 7 6
c add return values
e
s 00002/00002/00029
d D 8.1 93/06/09 18:58:46 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00002/00030
d D 6.4 93/06/09 18:58:43 bostic 5 3
c fixed the under development line
e
s 00002/00002/00030
d R 8.1 93/06/04 13:18:14 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00031
d D 6.3 92/06/23 17:01:36 bostic 3 2
c len is a size_t
e
s 00024/00017/00008
d D 6.2 91/08/07 03:36:40 cael 2 1
c mdoc version three
e
s 00025/00000/00000
d D 6.1 91/05/27 21:44:45 mckusick 1 0
c date and time created 91/05/27 21:44:45 by mckusick
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1991 Regents of the University of California.
E 2
I 2
D 6
.\" Copyright (c) 1991, 1991 Regents of the University of California.
E 2
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 2
.\" %sccs.include.redist.man%
E 2
I 2
.\" %sccs.include.redist.roff%
E 2
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH MUNMAP 2 "%Q%"
.UC 7
.SH NAME
munmap \- remove a mapping
.SH SYNOPSIS
.nf
munmap(addr, len)
.B caddr_t addr;
.B int len;
.fi
.SH DESCRIPTION
.PP
The \fImunmap\fP system call
E 2
I 2
.Dd %Q%
.Dt MUNMAP 2
.Os
.Sh NAME
.Nm munmap
.Nd remove a mapping
.Sh SYNOPSIS
D 3
.Fn munmap "caddr_t addr" "int len"
E 3
I 3
.Fn munmap "caddr_t addr" "size_t len"
E 3
.Sh DESCRIPTION
The
.Fn munmap
system call
E 2
deletes the mappings for the specified address range,
and causes further references to addresses within the range
to generate invalid memory references.
D 2
.SH "SEE ALSO"
msync.2, munmap.2, mprotect.2, madvise.2, mincore.2
E 2
I 2
D 7
.Sh SEE ALSO
E 7
I 7
.Sh RETURN VALUES
Upon successful completion,
.Nm munmap
returns zero.
Otherwise, a value of -1 is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Fn Munmap
will fail if:
.Bl -tag -width Er
.It Bq Er EINVAL
The
.Fa addr
parameter was not page aligned, the
.Fa len
parameter was negative, or
D 8
some part of the region being unmapped is not part of the currently
valid address space.
E 8
I 8
some part of the region being unmapped is outside the
valid address range for a process.
E 8
.Sh "SEE ALSO"
.Xr getpagesize 2 ,
E 7
.Xr msync 2 ,
D 7
.Xr madvise 2 ,
E 7
I 7
.Xr munmap 2 ,
E 7
.Xr mprotect 2 ,
I 7
.Xr madvise 2 ,
E 7
.Xr mincore 2
.Sh HISTORY
The
.Fn munmap
D 5
function call is
.Ud .
E 5
I 5
function first appeared in 4.4BSD.
E 5
E 2
E 1
