h49016
s 00002/00002/00101
d D 8.1 93/06/04 13:18:34 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00098/00053/00005
d D 6.4 93/03/02 17:59:17 bostic 6 5
c non-proprietary versoin from BSDI
e
s 00003/00002/00055
d D 6.3 91/04/29 04:41:08 cael 5 4
c proprietary copyright
e
s 00002/00005/00055
d D 6.2 86/05/14 11:12:13 karels 4 3
c update for VAX
e
s 00001/00001/00059
d D 6.1 85/05/09 16:06:49 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00010/00016/00050
d D 5.1 85/05/09 16:06:41 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00066/00000/00000
d D 4.1 85/05/09 16:06:34 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1980 Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1993 The Regents of the University of California.
E 6
D 5
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
D 6
.\"	%sccs.include.proprietary.roff%
E 6
I 6
.\" This code is derived from software contributed to Berkeley by
.\" Donn Seeley of BSDI.
E 6
E 5
.\"
I 6
.\" %sccs.include.redist.roff%
.\"
E 6
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH PROFIL 2 
E 2
I 2
D 3
.TH PROFIL 2 "12 February 1983"
E 3
I 3
D 6
.TH PROFIL 2 "%Q%"
E 3
E 2
.UC 4
.SH NAME
profil \- execution time profile
.SH SYNOPSIS
.nf
.B profil(buff, bufsiz, offset, scale)
.B char *buff;
.B int bufsiz, offset, scale;
.fi
.SH DESCRIPTION
.I Buff
points to an area of core whose length (in bytes) is given by
.IR bufsiz .
After this call, the user's program counter (pc)
D 2
is examined each clock tick (60th second);
E 2
I 2
is examined each clock tick (10 milliseconds);
E 2
.I offset
is subtracted from it, and the result multiplied by
.IR scale .
If the resulting number corresponds to a word
inside
.I buff,
that word is incremented.
.PP
The scale is interpreted as an unsigned,
D 4
fixed-point fraction with binary point at the
D 2
left: 0177777(8) gives a 1-1 mapping of pc's to words
E 2
I 2
left: 0x10000 gives a 1-1 mapping of pc's to words
E 4
I 4
fixed-point fraction with 16 bits of fraction:
0x10000 gives a 1-1 mapping of pc's to words
E 4
E 2
in
.I buff;
D 2
077777(8) maps each pair of instruction words
E 2
I 2
0x8000 maps each pair of instruction words
E 2
together.
D 2
02(8) maps all instructions onto the beginning of
E 2
I 2
D 4
0x2 maps all instructions onto the beginning of
E 2
.I buff
(producing a non-interrupting core clock).
E 4
.PP
Profiling is turned off by giving a
.I scale
of 0 or 1.
It is rendered
ineffective by giving a
.I bufsiz
of 0.
Profiling is turned off when an
D 2
.I exec
E 2
I 2
.I execve
E 2
is executed, but remains on in child and parent both
after a
.IR fork .
D 2
Profiling may be turned off if an update in
E 2
I 2
Profiling is turned off if an update in
E 2
.I buff
would cause a memory fault.
I 2
.SH "RETURN VALUE
A 0, indicating success, is always returned.
E 2
.SH "SEE ALSO"
D 2
monitor(3), prof(1)
.SH "ASSEMBLER (PDP-11)"
(profil = 44.)
.br
.B sys profil; buff; bufsiz; offset; scale
.SH BUGS
Profiling does not work for interpreters; if a signal were given
to a process when its cpu-time clock ticked then profiling interpreters
would be possible.
E 2
I 2
gprof(1), setitimer(2), monitor(3)
E 6
I 6
.Dd "%Q%"
.Dt PROFIL 2
.Os
.Sh NAME
.Nm profil
.Nd control process profiling
.Sh SYNOPSIS
.Ft int
.Fn profil "char *samples" "int size" "int offset" "int scale"
.Sh DESCRIPTION
The
.Fn profil
function enables or disables
program counter profiling of the current process.
If profiling is enabled,
then at every clock tick,
the kernel updates an appropriate count in the
.Fa samples
buffer.
.Pp
The buffer
.Fa samples
contains
.Fa size
bytes and is divided into
a series of 16-bit bins.
Each bin counts the number of times the program counter
was in a particular address range in the process
when a clock tick occurred while profiling was enabled.
For a given program counter address,
the number of the corresponding bin is given
by the relation:
.Bd -literal -offset indent
[(pc - offset) / 2] * scale / 65536
.Ed
.Pp
The
.Fa offset
parameter is the lowest address at which
the kernel takes program counter samples.
The
.Fa scale
parameter ranges from 1 to 65536 and
can be used to change the span of the bins.
A scale of 65536 maps each bin to 2 bytes of address range;
a scale of 32768 gives 4 bytes, 16384 gives 8 bytes and so on.
Intermediate values provide approximate intermediate ranges.
A
.Fa scale
value of 0 disables profiling.
.Sh RETURN VALUES
If the
.Fa scale
value is nonzero and the buffer
.Fa samples
contains an illegal address,
.Fn profil
returns \-1,
profiling is terminated and
.Va errno
is set appropriately.
Otherwise
.Fn profil
returns 0.
.Sh FILES
.Bl -tag -width /usr/lib/gcrt0.o -compact
.It Pa /usr/lib/gcrt0.o
profiling C run-time startup file
.It Pa gmon.out
conventional name for profiling output file
.El
.Sh ERRORS
The following error may be reported:
.Bl -tag -width Er
.It Bq Er EFAULT
The buffer
.Fa samples
contains an invalid address.
.El
.Sh SEE ALSO
.Xr gprof 1
.\" .Sh HISTORY
.\" wish I knew...  probably v7.
.Sh BUGS
This routine should be named
.Fn profile .
.Pp
The
.Fa samples
argument should really be a vector of type
.Fa "unsigned short" .
.Pp
The format of the gmon.out file is undocumented.
E 6
E 2
E 1
