h21971
s 00002/00002/00068
d D 8.1 93/06/04 13:18:47 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00000/00069
d D 6.9 92/07/27 13:43:20 bostic 10 9
c add symlink(7)
e
s 00049/00047/00020
d D 6.8 91/03/10 23:39:55 cael 9 8
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00066
d D 6.7 90/06/23 17:46:54 trent 8 7
c new copyright notice
e
s 00001/00001/00076
d D 6.6 89/08/25 12:08:24 bostic 7 6
c typo
e
s 00014/00003/00063
d D 6.5 89/05/18 14:15:36 bostic 6 5
c add Berkeley specific copyright notice
e
s 00003/00000/00063
d D 6.4 85/08/26 23:33:07 mckusick 5 4
c update error messages (mostly from sun!guy)
e
s 00001/00001/00062
d D 6.3 85/06/30 16:44:28 sechrest 4 3
c added comma
e
s 00010/00016/00053
d D 6.2 85/05/22 18:31:54 mckusick 3 2
c update the error return codes to reflect those in 4.3BSD
e
s 00001/00001/00068
d D 6.1 85/05/15 11:58:02 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00069/00000/00000
d D 5.1 85/05/15 11:57:56 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 9
.\" Copyright (c) 1983 The Regents of the University of California.
E 9
I 9
D 11
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 9
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
.\"
D 8
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 8
I 8
.\" %sccs.include.redist.man%
E 8
E 6
.\"
D 9
.\"	%W% (Berkeley) %G%
E 9
I 9
.\"     %W% (Berkeley) %G%
E 9
.\"
D 2
.TH READLINK 2 "2 July 1983"
E 2
I 2
D 9
.TH READLINK 2 "%Q%"
E 2
.UC 5
.SH NAME
readlink \- read value of a symbolic link
.SH SYNOPSIS
.nf
.ft B
cc = readlink(path, buf, bufsiz)
int cc;
char *path, *buf;
int bufsiz;
.fi
.ft R
.SH DESCRIPTION
.I Readlink
E 9
I 9
.Dd %Q%
.Dt READLINK 2
.Os BSD 4.2
.Sh NAME
.Nm readlink
.Nd read value of a symbolic link
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
.Fn readlink "const char *path" "char *buf" "int bufsiz"
.Sh DESCRIPTION
.Fn Readlink
E 9
places the contents of the symbolic link
D 9
.I name
E 9
I 9
.Fa path
E 9
in the buffer
D 4
.I buf
E 4
I 4
D 9
.I buf,
E 9
I 9
.Fa buf ,
E 9
E 4
which has size
D 9
.IR bufsiz . 
The contents of the link are not null terminated when returned.
.SH "RETURN VALUE
E 9
I 9
.Fa bufsiz .
.Nm Readlink
does not append a
.Dv NUL
character to
.Fa buf .
.Sh RETURN VALUES
E 9
The call returns the count of characters placed in the buffer
D 9
if it succeeds, or a \-1 if an error occurs, placing the error
code in the global variable \fIerrno\fP.
.SH "ERRORS
.I Readlink
E 9
I 9
if it succeeds, or a -1 if an error occurs, placing the error
code in the global variable
.Va errno .
.Sh ERRORS
.Fn Readlink
E 9
D 7
will fail and the file mode will be unchanged if:
E 7
I 7
will fail if:
E 7
D 9
.TP 15
D 3
[EPERM]
The \fIpath\fP argument contained a byte with the high-order bit set.
.TP 15
[ENOENT]
The pathname was too long.
.TP 15
E 3
[ENOTDIR]
E 9
I 9
.Bl -tag -width ENAMETOOLONG
.It Bq Er ENOTDIR
E 9
A component of the path prefix is not a directory.
D 9
.TP 15
I 3
[EINVAL]
E 9
I 9
.It Bq Er EINVAL
E 9
The pathname contains a character with the high-order bit set.
D 9
.TP 15
[ENAMETOOLONG]
E 9
I 9
.It Bq Er ENAMETOOLONG
E 9
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
D 9
.TP 15
E 3
[ENOENT]
E 9
I 9
.It Bq Er ENOENT
E 9
The named file does not exist.
D 9
.TP 15
D 3
[ENXIO]
The named file is not a symbolic link.
.TP 15
E 3
[EACCES]
E 9
I 9
.It Bq Er EACCES
E 9
D 3
Search permission is denied on a component of the path prefix.
E 3
I 3
Search permission is denied for a component of the path prefix.
E 3
D 9
.TP 15
D 3
[EPERM]
The effective user ID does not match the owner of the file and
the effective user ID is not the super-user.
E 3
I 3
[ELOOP]
E 9
I 9
.It Bq Er ELOOP
E 9
Too many symbolic links were encountered in translating the pathname.
E 3
D 9
.TP 15
[EINVAL]
E 9
I 9
.It Bq Er EINVAL
E 9
The named file is not a symbolic link.
D 9
.TP 15
I 5
[EIO]
E 9
I 9
.It Bq Er EIO
E 9
An I/O error occurred while reading from the file system.
D 9
.TP 15
E 5
[EFAULT]
.I Buf
E 9
I 9
.It Bq Er EFAULT
.Fa Buf
E 9
extends outside the process's allocated address space.
D 3
.TP 15
[ELOOP]
Too many symbolic links were encountered in translating the pathname.
E 3
D 9
.SH SEE ALSO
stat(2), lstat(2), symlink(2)
E 9
I 9
.El
.Sh SEE ALSO
.Xr stat 2 ,
.Xr lstat 2 ,
.Xr symlink 2
I 10
.Xr symlink 7 ,
E 10
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 9
E 1
