h14602
s 00003/00009/00054
d D 8.2 94/04/16 12:28:25 bostic 10 9
c setgroups now takes gid_t's, they are 32-bits
e
s 00002/00002/00061
d D 8.1 93/06/04 13:19:27 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00048/00037/00015
d D 6.7 91/03/10 23:40:22 cael 8 7
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00051
d D 6.6 90/06/23 17:46:25 trent 7 6
c new copyright notice
e
s 00014/00003/00048
d D 6.5 89/05/18 14:15:45 bostic 6 5
c add Berkeley specific copyright notice
e
s 00001/00001/00050
d D 6.4 87/04/10 10:07:30 bostic 5 4
c initgroups is 3, not 3X
e
s 00006/00000/00045
d D 6.3 86/05/13 15:01:48 karels 4 3
c mention gid_t
e
s 00001/00001/00044
d D 6.2 86/04/20 03:45:27 lepreau 3 2
c NGRPS -> NGROUPS
e
s 00001/00001/00044
d D 6.1 85/05/15 11:59:40 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00045/00000/00000
d D 5.1 85/05/15 11:59:33 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 8
.\" Copyright (c) 1983 The Regents of the University of California.
E 8
I 8
D 9
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 8
.\" All rights reserved.
E 9
I 9
D 10
.\" Copyright (c) 1983, 1991, 1993
E 10
I 10
.\" Copyright (c) 1983, 1991, 1993, 1994
E 10
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
D 7
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
E 6
.\"
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 2
.TH SETGROUPS 2 "7 July 1983"
E 2
I 2
D 8
.TH SETGROUPS 2 "%Q%"
E 2
.UC 5
.SH NAME
setgroups \- set group access list
.SH SYNOPSIS
.nf
.ft B
#include <sys/param.h>
.PP
.ft B
setgroups(ngroups, gidset)
int ngroups, *gidset;
.fi
.SH DESCRIPTION
.I Setgroups
E 8
I 8
.Dd %Q%
.Dt SETGROUPS 2
.Os BSD 4.2
.Sh NAME
.Nm setgroups
.Nd set group access list
.Sh SYNOPSIS
D 10
.Fd #include <unistd.h>
E 10
.Fd #include <sys/param.h>
I 10
.Fd #include <unistd.h>
E 10
.Ft int
D 10
.Fn setgroups "int ngroups" "const int *gidset"
E 10
I 10
.Fn setgroups "int ngroups" "const gid_t *gidset"
E 10
.Sh DESCRIPTION
.Fn Setgroups
E 8
sets the group access list of the current user process
according to the array 
D 8
.IR gidset .
E 8
I 8
.Fa gidset .
E 8
The parameter
D 8
.I ngroups
E 8
I 8
.Fa ngroups
E 8
indicates the number of entries in the array and must be no
D 3
more than NGRPS, as defined in
E 3
I 3
D 8
more than NGROUPS, as defined in
E 3
.RI < sys/param.h >.
.PP
E 8
I 8
more than
.Dv NGROUPS ,
as defined in
.Ao Pa sys/param.h Ac .
.Pp
E 8
Only the super-user may set new groups.
D 8
.SH "RETURN VALUE
A 0 value is returned on success, \-1 on error, with
a error code stored in \fIerrno\fP.
.SH "ERRORS
The \fIsetgroups\fP call will fail if:
.TP 15
[EPERM]
E 8
I 8
.Sh RETURN VALUES
A 0 value is returned on success, -1 on error, with
an error code stored in
.Va errno .
.Sh ERRORS
The
.Fn setgroups
call will fail if:
.Bl -tag -width Er
.It Bq Er EPERM
E 8
The caller is not the super-user.
D 8
.TP 15
[EFAULT]
The address specified for \fIgidset\fP is outside the process
E 8
I 8
.It Bq Er EFAULT
The address specified for
.Fa gidset
is outside the process
E 8
address space.
D 8
.SH "SEE ALSO
D 5
getgroups(2), initgroups(3X)
E 5
I 5
getgroups(2), initgroups(3)
E 5
I 4
.SH BUGS
E 8
I 8
.El
.Sh SEE ALSO
.Xr getgroups 2 ,
.Xr initgroups 3
D 10
.Sh BUGS
E 8
The
D 8
.I gidset
E 8
I 8
.Fa gidset
E 8
array should be of type
D 8
.BR gid_t ,
E 8
I 8
.Em gid_t ,
E 8
but remains integer for compatibility with earlier systems.
E 10
I 8
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 8
E 4
E 1
