h52483
s 00002/00002/00061
d D 8.1 93/06/04 13:19:32 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00046/00041/00017
d D 6.3 91/03/10 23:40:25 cael 5 4
c man page macro and text revisions (-mdoc version 3)
e
s 00017/00009/00041
d D 6.2 91/02/19 14:57:46 bostic 4 3
c rename setpgrp to setpgid, add setpgrp compat call, update man page
e
s 00001/00001/00049
d D 6.1 85/05/09 17:46:42 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00028/00038/00022
d D 5.1 85/05/09 17:46:17 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00060/00000/00000
d D 4.1 85/05/09 17:45:50 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1980, 1991 Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
E 5
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
D 2
.TH SETPGRP 2J
E 2
I 2
D 3
.TH SETPGRP 2 "12 February 1983"
E 3
I 3
D 5
.TH SETPGRP 2 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
setpgrp, getpgrp \- set/get process group
E 2
I 2
D 4
setpgrp \- set process group
E 4
I 4
setpgid, setpgrp \- set process group
E 4
E 2
.SH SYNOPSIS
D 2
.B int getpgrp(pid)
.PP
.B setpgrp(pid, pgrp)
.PP
.B cc ... \-ljobs
E 2
I 2
.ft B
D 4
setpgrp(pid, pgrp)
E 4
I 4
setpgid(pid_t pid, pid_t pgrp);
E 4
.br
D 4
int pid, pgrp;
E 4
I 4
setpgrp(pid_t pid, pid_t pgrp);
E 4
.ft R
E 2
.SH DESCRIPTION
D 2
The process group of the specified process is returned by
.I getpgrp.
E 2
D 4
.I Setpgrp
E 4
I 4
.I Setpgid
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt SETPGID 2
.Os BSD 4
.Sh NAME
.Nm setpgid ,
.Nm setpgrp
.Nd set process group
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
.Fn setpgid pid_tpid pid_tpgrp
.Ft int
.Fn setpgrp pid_tpid pid_tpgrp
.Sh DESCRIPTION
.Fn Setpgid
E 5
E 4
sets the process group of the specified process
D 5
.I pid
E 5
I 5
.Ar pid
E 5
to the specified
D 2
.I pgrp.
E 2
I 2
D 5
.IR pgrp .
E 5
I 5
.Ar pgrp .
E 5
E 2
If
D 5
.I pid
E 5
I 5
.Ar pid
E 5
is zero, then the call applies to the current process.
D 5
.PP
E 5
I 5
.Pp
E 5
If the invoker is not the super-user, then the affected process
must have the same effective user-id as the invoker or be a descendant
of the invoking process.
D 2
.PP
This call is used by
.IR csh (1)
to create
process groups
in implementing job control.
The TIOCGPGRP and TIOCSPGRP calls
described in
.IR tty (4)
are used to get/set the process group of the control terminal.
.PP
See
.IR jobs(3)
for a general discussion of job control.
E 2
I 2
D 5
.SH "RETURN VALUE
D 4
.I Setpgrp
returns when the operation was successful.  If
the request failed, \-1 is returned and the global
variable
E 4
I 4
.I Setpgid
E 5
I 5
.Sh RETURN VALUES
.Fn Setpgid
E 5
returns 0 when the operation was successful.
D 5
If the request failed, \-1 is returned and the global variable
E 4
.I errno
E 5
I 5
If the request failed, -1 is returned and the global variable
.Va errno
E 5
indicates the reason.
D 5
.SH ERRORS
D 4
.I Setpgrp
E 4
I 4
.I Setpgid
E 4
will fail and the process group will not be altered if
one of the following occur:
.TP 15
[ESRCH]
E 5
I 5
.Sh ERRORS
.Fn Setpgid
will fail and the process group will not be altered if:
.Bl -tag -width indent
.It Bq Er ESRCH
E 5
The requested process does not exist.
D 5
.TP 15
[EPERM]
E 5
I 5
.It Bq Er EPERM
E 5
The effective user ID of the requested process is different
from that of the caller and the process is not a descendent
of the calling process.
E 2
D 5
.SH "SEE ALSO"
D 2
jobs(3), getuid(2), tty(4)
.SH BUGS
The job control facilities are not available in standard version 7 UNIX.
These facilities are still under development and may change in future
releases of the system as better inter-process communication facilities
and support for virtual terminals become available.  The options and
specifications of these system calls and even the calls themselves
are thus subject to change.
.PP
A system call
.I setpgrp
has been implemented in other versions of UNIX which are not widely
used outside of Bell Laboratories; these implementations
have, in general, slightly different semantics.
E 2
I 2
getpgrp(2)
I 4
.SH STANDARDS
.I Setpgid
conforms to IEEE Std 1003.1-1988 (``POSIX'').
.SH COMPATIBILITY
.I Setpgrp
E 5
I 5
.El
.Sh SEE ALSO
.Xr getpgrp 2
.Sh STANDARDS
.Fn Setpgid
conforms to IEEE Std 1003.1-1988
.Pq Dq Tn POSIX .
.Sh COMPATIBILITY
.Fn Setpgrp
E 5
is identical to
D 5
.IR setpgid ,
E 5
I 5
.Fn setpgid ,
E 5
and is retained for calling convention compatibility with historical
D 5
versions of BSD.
E 5
I 5
versions of
.Bx .
E 5
E 4
E 2
E 1
