h18756
s 00033/00023/00015
d D 6.4 91/03/10 23:40:28 cael 6 5
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00037
d D 6.3 90/06/23 17:46:20 trent 5 4
c new copyright notice
e
s 00014/00003/00034
d D 6.2 89/05/18 14:15:47 bostic 4 2
c add Berkeley specific copyright notice
e
s 00005/00001/00036
d R 6.2 86/01/07 14:04:29 donn 3 2
c int => gid_t
e
s 00004/00005/00033
d D 6.1 85/05/15 12:00:10 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00038/00000/00000
d D 5.1 85/05/15 12:00:03 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 6
.\" Copyright (c) 1983 The Regents of the University of California.
E 6
I 6
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
.\"
D 5
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 5
I 5
.\" %sccs.include.redist.man%
E 5
E 4
.\"
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH SETREGID 2 "12 February 1983"
E 2
I 2
D 6
.TH SETREGID 2 "%Q%"
E 2
.UC 5
.SH NAME
setregid \- set real and effective group ID
.SH SYNOPSIS
.ft B
setregid(rgid, egid)
.br
int rgid, egid;
.ft R
.SH DESCRIPTION
E 6
I 6
.Dd %Q%
.Dt SETREGID 2
.Os BSD 4.2
.Sh NAME
.Nm setregid
.Nd set real and effective group ID
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
.Fn setregid "int rgid" "int egid"
.Sh DESCRIPTION
E 6
The real and effective group ID's of the current process
are set to the arguments.
D 2
Only the super-user may change the real group ID
of a process.  Unpriviledged users may change the
effective group ID to the real group ID, but to
no other.
E 2
I 2
Unprivileged users may change the real group
ID to the effective group ID and vice-versa; only the super-user may
make other changes.
E 2
D 6
.PP
Supplying a value of \-1 for either the real or effective
E 6
I 6
.Pp
Supplying a value of -1 for either the real or effective
E 6
group ID forces the system to substitute the current
D 6
ID in place of the \-1 parameter.
.SH "RETURN VALUE
E 6
I 6
ID in place of the -1 parameter.
.Sh RETURN VALUES
E 6
Upon successful completion, a value of 0 is returned.  Otherwise,
D 6
a value of \-1 is returned and \fIerrno\fP is set to indicate the error.
.SH "ERRORS
.TP 15
[EPERM]
E 6
I 6
a value of -1 is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Bl -tag -width [EPERM]
.It Bq Er EPERM
E 6
The current process is not the super-user and a change
other than changing the effective group-id to the real group-id
was specified.
D 6
.SH "SEE ALSO"
getgid(2), setreuid(2), setgid(3)
E 6
I 6
.El
.Sh SEE ALSO
.Xr getgid 2 ,
.Xr setreuid 2 ,
.Xr setgid 3
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 6
E 1
