h62121
s 00002/00002/00094
d D 8.1 93/06/04 13:19:38 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00044/00008/00052
d D 6.7 93/02/26 18:03:31 mckusick 8 7
c update from Mike Karels at BSDI
e
s 00003/00017/00057
d D 6.6 93/02/03 15:44:58 mckusick 7 6
c update to reflect saved ID's
e
s 00001/00000/00073
d D 6.5 92/06/04 11:18:39 bostic 6 5
c add unistd.h to includes
e
s 00065/00045/00008
d D 6.4 91/04/19 14:48:51 cael 5 4
c macro and text revision (-mdoc version 3)
e
s 00001/00001/00052
d D 6.3 86/05/12 19:58:33 karels 4 3
c typo
e
s 00015/00006/00038
d D 6.2 86/01/07 14:10:37 mckusick 3 2
c int => uid_t and int => gid_t
e
s 00001/00001/00043
d D 6.1 85/05/15 16:29:04 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00044/00000/00000
d D 5.1 85/05/15 16:28:58 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 9
.\" Copyright (c) 1983, 1991 Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 5
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
D 2
.TH SETUID 3 "1 April 1983" 
E 2
I 2
D 5
.TH SETUID 3 "%Q%" 
E 2
.UC 5
.SH NAME
setuid, seteuid, setruid, setgid, setegid, setrgid \- set user and group ID
.SH SYNOPSIS
.nf
D 3
.B setuid(uid)
.B seteuid(euid)
.B setruid(ruid)
E 3
I 3
.ft B
#include <sys/types.h>
E 3
.PP
D 3
.B setgid(gid)
.B setegid(egid)
.B setrgid(rgid)
E 3
I 3
.ft B
.nf
setuid(uid)
seteuid(euid)
setruid(ruid)
uid_t uid, euid, ruid;
.PP
.ft B
.nf
setgid(gid)
setegid(egid)
setrgid(rgid)
gid_t gid, egid, rgid;
E 3
.fi
.SH DESCRIPTION
.I Setuid
.RI ( setgid )
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
D 7
.Dt SETUID 3
E 7
I 7
.Dt SETUID 2
E 7
.Os BSD 4.2
.Sh NAME
.Nm setuid ,
.Nm seteuid ,
D 7
.Nm setruid ,
E 7
.Nm setgid ,
.Nm setegid ,
D 7
.Nm setrgid
E 7
.Nd set user and group ID
.Sh SYNOPSIS
.Fd #include <sys/types.h>
I 6
.Fd #include <unistd.h>
E 6
.Ft int
.Fn setuid "uid_t uid"
.Ft int
.Fn seteuid "uid_t euid"
.Ft int
D 7
.Fn setruid "uid_t ruid"
.Ft int
E 7
.Fn setgid "gid_t gid"
.Ft int
.Fn setegid "gid_t egid"
D 7
.Ft int
.Fn setrgid "gid_t rgid"
E 7
.Sh DESCRIPTION
The
.Fn setuid
function
D 8
.Pq Fn setgid
E 5
sets both the real and effective
D 5
user ID (group ID) of the current process to
E 5
I 5
user ID (group ID) of the current process
E 5
as specified.
E 8
I 8
sets the real and effective
user IDs and the saved set-user-ID of the current process
to the specified value.
The
.Fn setuid
function is permitted if the specified ID is equal to the real user ID
of the process, or if the effective user ID is that of the super user.
E 8
D 5
.PP
.I Seteuid
.RI ( setegid )
E 5
I 5
.Pp
The
I 8
.Fn setgid
function
sets the real and effective
group IDs and the saved set-group-ID of the current process
to the specified value.
The
.Fn setgid
function is permitted if the specified ID is equal to the real group ID
of the process, or if the effective user ID is that of the super user.
.Pp
The
E 8
.Fn seteuid
function
.Pq Fn setegid
E 5
sets the effective user ID (group ID) of the
current process.
I 8
The effective user ID may be set to the value
of the real user ID or the saved set-user-ID (see
.Xr intro 2
and
.Xr execve 2 ) ;
in this way, the effective user ID of a set-user-ID executable
may be toggled by switching to the real user ID, then re-enabled
by reverting to the set-user-ID value.
Similarly, the effective group ID may be set to the value
of the real group ID or the saved set-user-ID.
E 8
D 5
.PP
.I Setruid
D 4
.RI ( setruid )
E 4
I 4
.RI ( setrgid )
E 5
I 5
.Pp
D 7
The
.Fn setruid
function
.Pq Fn setrgid
E 5
E 4
sets the real user ID (group ID) of the
current process.
E 7
D 5
.PP
These calls are only permitted to the super-user
or if the argument is the real or effective ID.
.SH "SEE ALSO"
setreuid(2), setregid(2), getuid(2), getgid(2)
.SH DIAGNOSTICS
Zero is returned if the user (group) ID is set;
\-1 is returned otherwise.
E 5
I 5
.Sh RETURN VALUES
Upon success, these functions return 0;
otherwise \-1 is returned.
.Pp
If the user is not the super user, or the uid
D 7
specified is not the real or effective ID, these
functions return \-1.
E 7
I 7
specified is not the real, effective ID, or saved ID,
these functions return \-1.
E 7
.Sh SEE ALSO
D 7
.Xr setreuid 2 ,
.Xr setregid 2 ,
E 7
.Xr getuid 2 ,
.Xr getgid 2
D 8
.Sh HISTORY
A
E 8
I 8
.Sh STANDARDS
The
E 8
.Fn setuid
and
.Fn setgid
D 8
syscall appeared in 
.At v6 .
E 8
I 8
functions are compliant with the
.St -p1003.1-88
specification with
.Li _POSIX_SAVED_IDS
not defined.
The
.Fn seteuid
and
.Fn setegid
functions are extensions based on the 
.Tn POSIX
concept of
.Li _POSIX_SAVED_IDS ,
and have been proposed for a future revision of the standard.
E 8
E 5
E 1
