h15051
s 00002/00002/00053
d D 8.1 93/06/04 13:19:41 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00042/00031/00013
d D 6.4 91/03/10 23:40:34 cael 5 4
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00043
d D 6.3 90/06/23 17:46:12 trent 4 3
c new copyright notice
e
s 00014/00003/00040
d D 6.2 89/05/18 14:15:53 bostic 3 2
c add Berkeley specific copyright notice
e
s 00001/00001/00042
d D 6.1 85/05/15 12:00:23 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00043/00000/00000
d D 5.1 85/05/15 12:00:17 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 5
.\" Copyright (c) 1983 The Regents of the University of California.
E 5
I 5
D 6
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 5
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 4
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 4
I 4
.\" %sccs.include.redist.man%
E 4
E 3
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH SHUTDOWN 2 "27 July 1983"
E 2
I 2
D 5
.TH SHUTDOWN 2 "%Q%"
E 2
.UC 5
.SH NAME
shutdown \- shut down part of a full-duplex connection
.SH SYNOPSIS
.nf
.ft B
shutdown(s, how)
int s, how;
.fi
.SH DESCRIPTION
E 5
I 5
.Dd %Q%
.Dt SHUTDOWN 2
.Os BSD 4.2
.Sh NAME
.Nm shutdown
.Nd shut down part of a full-duplex connection
.Sh SYNOPSIS
.Fd #include <sys/socket.h>
.Ft int
.Fn shutdown "int s" "int how"
.Sh DESCRIPTION
E 5
The
D 5
.I shutdown
E 5
I 5
.Fn shutdown
E 5
call causes all or part of a full-duplex connection on
the socket associated with
D 5
.I s
E 5
I 5
.Fa s
E 5
to be shut down.
D 5
If \fIhow\fP is 0, then further receives will be disallowed.
If \fIhow\fP is 1, then further sends will be disallowed.
If \fIhow\fP is 2, then further sends and receives will be disallowed.
.SH DIAGNOSTICS
A 0 is returned if the call succeeds, \-1 if it fails.
.SH ERRORS
E 5
I 5
If
.Fa how
is 0, further receives will be disallowed.
If
.Fa how
is 1, further sends will be disallowed.
If
.Fa how
is 2, further sends and receives will be disallowed.
.Sh DIAGNOSTICS
A 0 is returned if the call succeeds, -1 if it fails.
.Sh ERRORS
E 5
The call succeeds unless:
D 5
.TP 15
[EBADF]
.I S
E 5
I 5
.Bl -tag -width ENOTCONNAA
.It Bq Er EBADF
.Fa S
E 5
is not a valid descriptor.
D 5
.TP 15
[ENOTSOCK]
.I S
E 5
I 5
.It Bq Er ENOTSOCK
.Fa S
E 5
is a file, not a socket.
D 5
.TP 15
[ENOTCONN]
E 5
I 5
.It Bq Er ENOTCONN
E 5
The specified socket is not connected.
D 5
.SH "SEE ALSO"
connect(2), socket(2)
E 5
I 5
.El
.Sh SEE ALSO
.Xr connect 2 ,
.Xr socket 2
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 5
E 1
