h33973
s 00001/00001/00053
d D 8.2 95/05/16 11:58:29 mckusick 6 5
c typo
e
s 00002/00002/00052
d D 8.1 93/06/04 13:20:03 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00053
d D 6.4 92/07/28 11:23:44 bostic 4 3
c include <signal.h>, not <sys/signal.h>
e
s 00006/00006/00048
d D 6.3 91/07/23 14:21:20 cael 3 2
c .Os changes, miscellaneous cleanups
e
s 00037/00028/00017
d D 6.2 91/03/10 23:40:48 cael 2 1
c man page macro and text revisions (-mdoc version 3)
e
s 00045/00000/00000
d D 6.1 90/07/01 16:34:51 karels 1 0
c new manual page, derived from compat-43/sig*.2
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1983 The Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
D 3
.\" %sccs.include.redist.man%
E 3
I 3
.\" %sccs.include.redist.roff%
E 3
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
D 3
.\"     %W% (Berkeley) %G%
E 3
I 3
.\"	%W% (Berkeley) %G%
E 3
E 2
.\"
D 2
.TH SIGSUSPEND 2 "%Q%"
.UC 7
.SH NAME
sigsuspend \- atomically release blocked signals and wait for interrupt
.SH SYNOPSIS
.B #include <signal.h>
.ft B
sigsuspend(sigmask)
.br
sigset_t *sigmask;
.ft R
.SH DESCRIPTION
.I Sigsuspend
E 2
I 2
.Dd %Q%
.Dt SIGSUSPEND 2
D 3
.Os BSD 4.4
E 3
I 3
.Os
E 3
.Sh NAME
.Nm sigsuspend
.Nd atomically release blocked signals and wait for interrupt
.Sh SYNOPSIS
D 4
.Fd #include <sys/signal.h>
E 4
I 4
.Fd #include <signal.h>
E 4
.Ft int
.Fn sigsuspend "const sigset_t *sigmask"
.Sh DESCRIPTION
.Fn Sigsuspend
E 2
temporarily changes the blocked signal mask to the set to which
D 2
.I sigmask
E 2
I 2
.Fa sigmask
E 2
points,
and then waits for a signal to arrive;
on return the previous set of masked signals is restored.
The signal mask set
is usually empty to indicate that all
signals are to be unblocked for the duration of the call.
D 2
The
.I sigsuspend
function
always terminates by being interrupted, returning \-1 with
.I errno
set to EINTR.
.PP
E 2
I 2
.Pp
E 2
In normal usage, a signal is blocked using
D 2
.IR sigprocmask (2),
E 2
I 2
.Xr sigprocmask 2
E 2
to begin a critical section, variables modified on the occurrence
of the signal are examined to determine that there is no work
to be done, and the process pauses awaiting work by using
D 2
.I sigsuspend
E 2
I 2
.Fn sigsuspend
E 2
with the previous mask returned by
D 2
.IR sigprocmask .
.SH SEE ALSO
sigprocmask(2), sigaction(2), sigsetops(3)
E 2
I 2
.Xr sigprocmask .
.Sh RETURN VALUES
The
.Fn sigsuspend
function
always terminates by being interrupted, returning -1 with
.Va errno
set to
.Dv EINTR .
.Sh SEE ALSO
.Xr sigprocmask 2 ,
.Xr sigaction 2 ,
.Xr sigsetops 3
.Sh STANDARDS
The
D 3
.Fn sigsupend
E 3
I 3
D 6
.Nm sigsupend
E 6
I 6
.Nm sigsuspend
E 6
E 3
function call
D 3
conforms to IEEE Std 1003.1-1988
.Pq Dq Tn POSIX .
E 3
I 3
conforms to
.St -p1003.1-88 .
E 3
E 2
E 1
