h01203
s 00002/00002/00063
d D 8.1 93/06/04 13:20:09 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00045/00042/00020
d D 6.4 91/03/10 23:40:55 cael 5 4
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00061
d D 6.3 90/06/23 17:45:42 trent 4 3
c new copyright notice
e
s 00014/00003/00058
d D 6.2 89/02/14 17:52:57 bostic 3 2
c add Berkeley specific copyright notice
e
s 00001/00001/00060
d D 6.1 85/05/15 12:01:41 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00061/00000/00000
d D 5.1 85/05/15 12:01:34 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 5
.\" Copyright (c) 1983 The Regents of the University of California.
E 5
I 5
D 6
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 5
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 4
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 4
I 4
.\" %sccs.include.redist.man%
E 4
E 3
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH SOCKETPAIR 2 "27 July 1983"
E 2
I 2
D 5
.TH SOCKETPAIR 2 "%Q%"
E 2
.UC 5
.SH NAME
socketpair \- create a pair of connected sockets
.SH SYNOPSIS
.nf
.ft B
#include <sys/types.h>
#include <sys/socket.h>
.PP
.ft B
socketpair(d, type, protocol, sv)
int d, type, protocol;
int sv[2];
.fi
.SH DESCRIPTION
E 5
I 5
.Dd %Q%
.Dt SOCKETPAIR 2
.Os BSD 4.2
.Sh NAME
.Nm socketpair
.Nd create a pair of connected sockets
.Sh SYNOPSIS
.Fd #include <sys/types.h>
.Fd #include <sys/socket.h>
.Ft int
.Fn socketpair "int d" "int type" "int protocol" "int *sv"
.Sh DESCRIPTION
E 5
The
D 5
.I socketpair
E 5
I 5
.Fn socketpair
E 5
call creates an unnamed pair of connected sockets in
the specified domain
D 5
.IR d ,
E 5
I 5
.Fa d ,
E 5
of the specified
D 5
.IR type ,
E 5
I 5
.Fa type ,
E 5
and using the optionally specified
D 5
.IR protocol .
E 5
I 5
.Fa protocol .
E 5
The descriptors used in referencing the new sockets
are returned in
D 5
.IR sv [0]
E 5
I 5
.Fa sv Ns [0]
E 5
and
D 5
.IR sv [1].
E 5
I 5
.Fa sv Ns [1] .
E 5
The two sockets are indistinguishable.
D 5
.SH DIAGNOSTICS
A 0 is returned if the call succeeds, \-1 if it fails.
.SH ERRORS
E 5
I 5
.Sh DIAGNOSTICS
A 0 is returned if the call succeeds, -1 if it fails.
.Sh ERRORS
E 5
The call succeeds unless:
D 5
.TP 20
[EMFILE]
E 5
I 5
.Bl -tag -width EPROTONOSUPPORTA
.It Bq Er EMFILE
E 5
Too many descriptors are in use by this process.
D 5
.TP 20
[EAFNOSUPPORT]
E 5
I 5
.It Bq Er EAFNOSUPPORT
E 5
The specified address family is not supported on this machine.
D 5
.TP 20
[EPROTONOSUPPORT]
E 5
I 5
.It Bq Er EPROTONOSUPPORT
E 5
The specified protocol is not supported on this machine.
D 5
.TP 20
[EOPNOSUPPORT]
E 5
I 5
.It Bq Er EOPNOSUPPORT
E 5
The specified protocol does not support creation of socket pairs.
D 5
.TP 20
[EFAULT]
The address \fIsv\fP does not specify a valid part of the
E 5
I 5
.It Bq Er EFAULT
The address
.Fa sv
does not specify a valid part of the
E 5
process address space.
D 5
.SH "SEE ALSO"
read(2), write(2), pipe(2)
.SH BUGS
This call is currently implemented only for the UNIX domain.
E 5
I 5
.Sh SEE ALSO
.Xr read 2 ,
.Xr write 2 ,
.Xr pipe 2
.Sh BUGS
This call is currently implemented only for the
.Tn UNIX
domain.
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
E 5
E 1
