h22129
s 00002/00002/00085
d D 8.1 93/06/04 13:20:22 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00054/00055/00033
d D 6.7 91/03/10 23:41:06 cael 9 8
c man page macro and text revisions (-mdoc version 3)
e
s 00001/00011/00087
d D 6.6 90/06/23 17:45:38 trent 8 7
c new copyright notice
e
s 00014/00003/00084
d D 6.5 89/05/18 14:16:07 bostic 7 6
c add Berkeley specific copyright notice
e
s 00004/00000/00083
d D 6.4 86/03/09 17:54:32 donn 6 5
c Document the return value (now that there is actually a program
c which uses it!).
e
s 00025/00000/00058
d D 6.3 85/08/26 23:32:27 mckusick 5 4
c update error messages (mostly from sun!guy)
e
s 00025/00000/00033
d D 6.2 85/05/22 18:31:37 mckusick 4 3
c update the error return codes to reflect those in 4.3BSD
e
s 00001/00001/00032
d D 6.1 85/05/09 18:32:01 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00016/00012/00017
d D 5.1 85/05/09 18:31:16 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00029/00000/00000
d D 4.1 85/05/09 18:30:42 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 7
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 9
.\" Copyright (c) 1980 The Regents of the University of California.
E 9
I 9
D 10
.\" Copyright (c) 1980, 1991 The Regents of the University of California.
E 9
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 8
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 8
I 8
.\" %sccs.include.redist.man%
E 8
E 7
.\"
D 9
.\"	%W% (Berkeley) %G%
E 9
I 9
.\"     %W% (Berkeley) %G%
E 9
.\"
D 2
.TH VSWAPON 2V
E 2
I 2
D 3
.TH SWAPON 2 "27 July 1983"
E 3
I 3
D 9
.TH SWAPON 2 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
vswapon \- add a swap device for interleaved paging/swapping
E 2
I 2
swapon \- add a swap device for interleaved paging/swapping
E 2
.SH SYNOPSIS
.nf
D 2
.B vswapon(name)
.B char *name;
E 2
I 2
.B swapon(special)
.B char *special;
E 2
.fi
.SH DESCRIPTION
D 2
.I Vswapon
makes the argument block device available to the system for
allocation for paging and swapping.  The number of blocks to be
made available, as well as the names of all potentially available
devices are known to the system, and are present in the system
configuration file (e.g. /usr/src/sys/conf/confhp.c).
E 2
I 2
.I Swapon
E 9
I 9
.Dd %Q%
.Dt SWAPON 2
.Os BSD 4
.Sh NAME
.Nm swapon
.Nd add a swap device for interleaved paging/swapping
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
.Fn swapon "const char *special"
.Sh DESCRIPTION
.Fn Swapon
E 9
makes the block device 
D 9
.I special 
E 9
I 9
.Fa special
E 9
available to the system for
allocation for paging and swapping.  The names of potentially
available devices are known to the system and defined at system
configuration time.  The size of the swap area on 
D 9
.I special 
E 9
I 9
.Fa special
E 9
is calculated at the time the device is first made available
for swapping.
I 6
D 9
.SH "RETURN VALUE
If an error has occurred, a value of \-1 is returned and
.I errno
E 9
I 9
.Sh RETURN VALUES
If an error has occurred, a value of -1 is returned and
.Va errno
E 9
is set to indicate the error.
E 6
I 4
D 9
.SH ERRORS
.I Swapon
E 9
I 9
.Sh ERRORS
.Fn Swapon
E 9
succeeds unless:
D 9
.TP 15
[ENOTDIR]
E 9
I 9
.Bl -tag -width ENAMETOOLONG
.It Bq Er ENOTDIR
E 9
A component of the path prefix is not a directory.
D 9
.TP 15
[EINVAL]
E 9
I 9
.It Bq Er EINVAL
E 9
The pathname contains a character with the high-order bit set.
D 9
.TP 15
[ENAMETOOLONG]
E 9
I 9
.It Bq Er ENAMETOOLONG
E 9
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
D 9
.TP 15
[ENOENT]
E 9
I 9
.It Bq Er ENOENT
E 9
The named device does not exist.
D 9
.TP 15
[EACCES]
E 9
I 9
.It Bq Er EACCES
E 9
Search permission is denied for a component of the path prefix.
D 9
.TP 15
[ELOOP]
E 9
I 9
.It Bq Er ELOOP
E 9
Too many symbolic links were encountered in translating the pathname.
D 9
.TP 15
[EPERM]
E 9
I 9
.It Bq Er EPERM
E 9
The caller is not the super-user.
I 5
D 9
.TP 15
[ENOTBLK]
.I Special
E 9
I 9
.It Bq Er ENOTBLK
.Fa Special
E 9
is not a block device.
D 9
.TP 15
[EBUSY]
The device specified by \fIspecial\fP has already
E 9
I 9
.It Bq Er EBUSY
The device specified by
.Fa special
has already
E 9
been made available for swapping
D 9
.TP 15
[EINVAL]
The device configured by \fIspecial\fP was not
E 9
I 9
.It Bq Er EINVAL
The device configured by
.Fa special
was not
E 9
configured into the system as a swap device.
D 9
.TP 15
[ENXIO]
E 9
I 9
.It Bq Er ENXIO
E 9
The major device number of 
D 9
.I special
E 9
I 9
.Fa special
E 9
is out of range (this indicates no device driver exists
for the associated hardware).
D 9
.TP 15
[EIO]
E 9
I 9
.It Bq Er EIO
E 9
An I/O error occurred while opening the swap device.
D 9
.TP 15
[EFAULT]
.I Special
E 9
I 9
.It Bq Er EFAULT
.Fa Special
E 9
points outside the process's allocated address space.
E 5
E 4
E 2
D 9
.SH "SEE ALSO"
D 2
swapon(8)
E 2
I 2
swapon(8), config(8)
E 2
.SH BUGS
E 9
I 9
.Sh SEE ALSO
.Xr swapon 8 ,
.Xr config 8
.Sh BUGS
E 9
There is no way to stop swapping on a disk so that the pack may be
dismounted.
D 9
.PP
E 9
I 9
.Pp
E 9
D 2
This call is peculiar to this version of UNIX.
E 2
I 2
This call will be upgraded in future versions of the system.
I 9
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.0 .
E 9
E 2
E 1
