h07931
s 00025/00019/00054
d D 8.4 94/10/18 15:31:33 mckusick 4 3
c unwhiteout => undelete
e
s 00001/00001/00072
d D 8.3 94/08/23 13:47:53 pendry 3 2
c typo: EXIST -> EEXIST
e
s 00000/00000/00073
d D 8.2 94/07/28 03:38:38 pendry 2 1
c changes for whiteouts and union filesystem
e
s 00073/00000/00000
d D 8.1 94/07/15 07:18:03 pendry 1 0
c date and time created 94/07/15 07:18:03 by pendry
e
u
U
t
T
I 1
.\" Copyright (c) 1994
.\"	Jan-Simon Pendry
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
D 4
.Dt UNWHITEOUT 2
E 4
I 4
.Dt UNDELETE 2
E 4
.Os BSD 4
.Sh NAME
D 4
.Nm unwhiteout
.Nd remove whiteout entry
E 4
I 4
.Nm undelete
.Nd attempt to recover a deleted file
E 4
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
D 4
.Fn unwhiteout "const char *path"
E 4
I 4
.Fn undelete "const char *path"
E 4
.Sh DESCRIPTION
The
D 4
.Fn unwhiteout
function
removes the whiteout named by
.Fa path
from its directory.
Any objects in a lower layer of the
union stack will become visible once more.
E 4
I 4
.Fn undelete
function attempts to recover the deleted file named by
.Fa path .
Currently, this works only when the named object
is a whiteout in a union filesystem.
The system call removes the whiteout causing
any objects in a lower layer of the
union stack to become visible once more.
.Pp
Eventually, the
.Nm undelete
functionality may be expanded to other filesystems able to recover
deleted files such as the log-structured filesystem.
E 4
.Sh RETURN VALUES
Upon successful completion, a value of 0 is returned.
Otherwise, a value of -1 is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
The
D 4
.Fn unwhiteout
E 4
I 4
.Fn undelete
E 4
succeeds unless:
.Bl -tag -width ENAMETOOLONGAA
.It Bq Er ENOTDIR
A component of the path prefix is not a directory.
.It Bq Er EINVAL
The pathname contains a character with the high-order bit set.
.It Bq Er ENAMETOOLONG
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
D 3
.It Bq Er EXIST
E 3
I 3
.It Bq Er EEXIST
E 3
The path does not reference a whiteout.
.It Bq Er ENOENT
D 4
The whiteout does not exist.
E 4
I 4
The named whiteout does not exist.
E 4
.It Bq Er EACCES
Search permission is denied for a component of the path prefix.
.It Bq Er EACCES
D 4
Write permission is denied on the directory containing the link
to be removed.
E 4
I 4
Write permission is denied on the directory containing the name
to be undeleted.
E 4
.It Bq Er ELOOP
Too many symbolic links were encountered in translating the pathname.
.It Bq Er EPERM
D 4
The directory containing the file is marked sticky,
E 4
I 4
The directory containing the name is marked sticky,
E 4
and the containing directory is not owned by the effective user ID.
.It Bq Er EIO
D 4
An I/O error occurred while deleting the directory entry.
E 4
I 4
An I/O error occurred while updating the directory entry.
E 4
.It Bq Er EROFS
D 4
The whiteout resides on a read-only file system.
E 4
I 4
The name resides on a read-only file system.
E 4
.It Bq Er EFAULT
.Fa Path
points outside the process's allocated address space.
.El
.Sh SEE ALSO
.Xr unlink 2 ,
.Xr mount_union 8
.Sh HISTORY
An
D 4
.Nm
E 4
I 4
.Nm undelete
E 4
function call first appeared in 4.4BSD-Lite.
E 1
