h00754
s 00008/00008/00094
d D 8.2 95/04/27 15:51:09 bostic 7 6
c database files couldn't live in /var, and were moved back
c into /etc.
c From: Charles Hannum <mycroft@NetBSD.ORG>
e
s 00002/00002/00100
d D 8.1 93/06/06 14:04:44 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00101
d D 5.5 93/01/13 11:10:19 bostic 5 4
c /etc/password -> /etc/passwd
e
s 00071/00053/00031
d D 5.4 91/09/09 14:10:03 cael 4 3
c mdoc version three
e
s 00002/00002/00082
d D 5.3 91/06/29 13:18:09 bostic 3 2
c pwd db files are in /etc, not /var/db
e
s 00000/00011/00084
d D 5.2 91/05/06 18:11:15 bostic 2 1
c don't describe the format in the man page, so nobody depends on it
e
s 00095/00000/00000
d D 5.1 91/03/08 14:07:14 bostic 1 0
c date and time created 91/03/08 14:07:14 by bostic
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 4
.\" %sccs.include.redist.man%
E 4
I 4
.\" %sccs.include.redist.roff%
E 4
.\"
.\"	%W% (Berkeley) %G%
.\"
D 4
.TH PWD_MKDB 8 "%Q%
.UC 7
.SH NAME
pwd_mkdb \- generate the password databases
.SH SYNOPSIS
.nf
.ft B
pwd_mkdb [ \-p ] file
.SH DESCRIPTION
.I Pwd_mkdb
E 4
I 4
.Dd %Q%
.Dt PWD_MKDB 8
.Os
.Sh NAME
.Nm pwd_mkdb
.Nd "generate the password databases"
.Sh SYNOPSIS
.Nm pwd_mkdb
.Op Fl p
.Ar file
.Sh DESCRIPTION
.Nm Pwd_mkdb
E 4
creates
D 4
.IR db (3)
E 4
I 4
.Xr db 3
E 4
style secure and insecure databases for the specified file.
D 3
These databases are then installed into ``/var/db/spwd.db'' and
``/var/db/pwd.db'' respectively.
E 3
I 3
D 4
These databases are then installed into ``/etc/spwd.db'' and
``/etc/pwd.db'' respectively.
E 3
The file is installed into ``/etc/master.passwd''.
E 4
I 4
These databases are then installed into
.Dq Pa /etc/spwd.db
and
.Dq Pa /etc/pwd.db
respectively.
The file is installed into
.Dq Pa /etc/master.passwd .
E 4
The file must be in the correct format (see
D 4
.IR passwd (5)).
E 4
I 4
.Xr passwd 5 ) .
E 4
It is important to note that the format used in this system is
different from the historic Version 7 style format.
D 4
.PP
E 4
I 4
.Pp
E 4
The options are as follows:
D 4
.TP
\-p
Create a Version 7 style password file and install it into ``/etc/password''.
.PP
E 4
I 4
.Bl -tag -width flag
.It Fl p
Create a Version 7 style password file and install it into
D 5
.Dq Pa /etc/password .
E 5
I 5
.Dq Pa /etc/passwd .
E 5
.El
.Pp
E 4
D 2
The databases actually contain three copies of the original data.
Each password file entry is converted into a rough approximation of a
``struct passwd'', with the strings placed inline.
This object is then stored as the data for three separate keys.
The first key is the pw_name field prepended by the _PW_KEYBYNAME character.
The second key is the pw_uid field prepended by the _PW_KEYBYUID character.
The third key is the line number in the original file prepended by the
_PW_KEYBYNUM character.
(The special characters are prepended to ensure that the keys do not
collide.)
.PP
E 2
The two databases differ in that the secure version contains the user's 
encrypted password and the insecure version has an asterisk (``*'')
D 4
.PP
E 4
I 4
.Pp
E 4
The databases are used by the C library password routines (see
D 4
.IR getpwent (3)).
.PP
.I Pwd_mkdb
E 4
I 4
.Xr getpwent 3 ) .
.Pp
.Nm Pwd_mkdb
E 4
exits zero on success, non-zero on failure.
D 4
.SH FILES
/var/db/pwd.db			The insecure password database file
.br
/var/db/pwd.db.tmp		A temporary file
.br
/var/db/spwd.db		The secure password database file
.br
/var/db/spwd.db.tmp		A temporary file
.br
/etc/master.passwd		The current password file
.br
/etc/passwd			A Version 7 format password file
.SH BUGS
E 4
I 4
.Sh FILES
.Bl -tag -width Pa -compact
D 7
.It Pa /var/db/pwd.db
The insecure password database file.
.It Pa /var/db/pwd.db.tmp
A temporary file.
.It Pa /var/db/spwd.db
The secure password database file.
.It Pa /var/db/spwd.db.tmp
A temporary file.
E 7
.It Pa /etc/master.passwd
The current password file.
.It Pa /etc/passwd
A Version 7 format password file.
I 7
.It Pa /etc/pwd.db
The insecure password database file.
.It Pa /etc/pwd.db.tmp
A temporary file.
.It Pa /etc/spwd.db
The secure password database file.
.It Pa /etc/spwd.db.tmp
A temporary file.
E 7
.El
.Sh BUGS
E 4
Because of the necessity for atomic update of the password files,
D 4
.I pwd_mkdb
E 4
I 4
.Nm pwd_mkdb
E 4
uses
D 4
.IR rename (2)
E 4
I 4
.Xr rename 2
E 4
to install them.
This, however, requires that the file specified on the command line live
D 4
on the same file system as the ``/etc'' directory.
.PP
E 4
I 4
on the same file system as the
.Dq Pa /etc
directory.
.Pp
E 4
There are the obvious races with multiple people running
D 4
.I pwd_mkdb
E 4
I 4
.Nm pwd_mkdb
E 4
on different password files at the same time.
The front-ends to 
D 4
.IR pwd_mkdb ,
.IR chpass (1),
.IR passwd (1)
E 4
I 4
.Nm pwd_mkdb ,
.Xr chpass 1 ,
.Xr passwd 1
E 4
and
D 4
.IR vipw (8),
E 4
I 4
.Xr vipw 8 ,
E 4
handle the locking necessary to avoid this problem.
D 4
.SH COMPATIBILITY
E 4
I 4
.Sh COMPATIBILITY
E 4
Previous versions of the system had a program similar to
D 4
.I pwd_mkdb, 
.IR mkpasswd (8),
E 4
I 4
.Nm pwd_mkdb ,
.Xr mkpasswd 8 ,
E 4
which built
D 4
.I dbm (3)
E 4
I 4
.Xr dbm 3
E 4
style databases for the password file but depended on the calling programs
to install them.
The program was renamed in order that previous users of the program
not be surprised by the changes in functionality.
D 4
.SH SEE ALSO
chpass(1), passwd(1), db(3), getpwent(3), passwd(5), vipw(8)
E 4
I 4
.Sh SEE ALSO
.Xr chpass 1 ,
.Xr passwd 1 ,
.Xr db 3 ,
.Xr getpwent 3 ,
.Xr passwd 5 ,
.Xr vipw 8
E 4
E 1
