h43638
s 00002/00002/00094
d D 8.1 93/06/04 16:25:24 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00054/00043/00042
d D 6.9 91/04/19 14:30:41 cael 10 9
c macro and text revision (-mdoc version 3)
e
s 00001/00011/00084
d D 6.8 90/06/23 17:42:35 trent 9 8
c new copyright notice
e
s 00006/00000/00089
d D 6.7 90/02/13 09:44:02 bostic 8 7
c obsolete
e
s 00018/00007/00071
d D 6.6 89/02/14 17:03:07 bostic 7 6
c add Berkeley specific copyright
e
s 00002/00001/00076
d D 6.5 86/05/14 18:14:45 karels 6 5
c cleanups
e
s 00002/00009/00075
d D 6.4 86/05/12 17:41:37 karels 5 4
c move from 3X to 3
e
s 00002/00004/00082
d D 6.3 86/05/09 21:56:40 lepreau 4 3
c port is int not u_short
e
s 00003/00000/00083
d D 6.2 86/03/14 04:09:18 donn 3 2
c documented include file
e
s 00009/00005/00074
d D 6.1 85/05/15 16:28:34 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00079/00000/00000
d D 5.1 85/05/15 16:28:27 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 7
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 7
I 7
D 10
.\" Copyright (c) 1983 The Regents of the University of California.
E 10
I 10
D 11
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 10
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 7
.\"
I 7
D 9
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 9
I 9
.\" %sccs.include.redist.man%
E 9
.\"
E 7
D 10
.\"	%W% (Berkeley) %G%
E 10
I 10
.\"     %W% (Berkeley) %G%
E 10
.\"
D 2
.TH REXEC 3X "17 March 1982"
E 2
I 2
D 5
.TH REXEC 3X "%Q%"
E 5
I 5
D 10
.TH REXEC 3 "%Q%"
E 5
E 2
.UC 5
.SH NAME
rexec \- return stream to a remote command
.SH SYNOPSIS
.nf
I 3
.PP
D 4
.B "#include <sys/types.h>"
.PP
E 4
E 3
.B "rem = rexec(ahost, inport, user, passwd, cmd, fd2p);"
.B char **ahost;
D 4
.B u_short inport;
E 4
I 4
.B int inport;
E 4
.B "char *user, *passwd, *cmd;"
.B int *fd2p;
.fi
.SH DESCRIPTION
I 8
.ft B
E 10
I 10
.Dd %Q%
.Dt REXEC 3
.Os BSD 4.2
.Sh NAME
.Nm rexec
.Nd return stream to a remote command
.Sh SYNOPSIS
.Ft int
.Fn rexec ahost "int inport" "char *user" "char *passwd" "char *cmd" "int *fd2p"
.Sh DESCRIPTION
.Bf -symbolic
E 10
This interface is obsoleted by krcmd(3).
D 10
.br
E 10
It is available from the compatibility library, libcompat.
D 10
.ft R
.PP
E 8
.I Rexec
E 10
I 10
.Ef
.Pp
The
.Fn rexec
function
E 10
looks up the host
D 10
.I *ahost
E 10
I 10
.Fa *ahost
E 10
using
D 7
.IR gethostbyname (3N),
E 7
I 7
D 10
.IR gethostbyname (3),
E 10
I 10
.Xr gethostbyname 3 ,
E 10
E 7
returning \-1 if the host does not exist.
Otherwise
D 10
.I *ahost
E 10
I 10
.Fa *ahost
E 10
is set to the standard name of the host.
If a username and password are both specified, then these
are used to authenticate to the foreign host; otherwise
the environment and then the user's
D 10
.I .netrc
E 10
I 10
.Pa .netrc
E 10
file in his
home directory are searched for appropriate information.
If all this fails, the user is prompted for the information.
D 10
.PP
E 10
I 10
.Pp
E 10
The port
D 10
.I inport
specifies which well-known DARPA Internet port to use for
D 2
the connection; it will normally be the value returned from
the call ``getservbyname("exec", "tcp")'' (see 
.IR getservent (3N)).
E 2
I 2
the connection; the call ``getservbyname("exec", "tcp")'' (see 
D 7
.IR getservent (3N))
E 7
I 7
.IR getservent (3))
E 10
I 10
.Fa inport
specifies which well-known
.Tn DARPA
Internet port to use for
the connection; the call
.Ql getservbyname(\\*qexec\\*q, \\*qtcp\\*q)
(see 
.Xr getservent 3 )
E 10
E 7
will return a pointer to a structure, which contains the
necessary port.
E 2
The protocol for connection is described in detail in
D 7
.IR rexecd (8C).
E 7
I 7
D 10
.IR rexecd (8).
E 7
.PP
E 10
I 10
.Xr rexecd 8 .
.Pp
E 10
D 6
If the call succeeds, a socket of type SOCK_STREAM is returned to
E 6
I 6
If the connection succeeds,
D 10
a socket in the Internet domain of type SOCK_STREAM is returned to
E 10
I 10
a socket in the Internet domain of type
.Dv SOCK_STREAM
is returned to
E 10
E 6
the caller, and given to the remote command as
D 10
.B stdin
E 10
I 10
.Em stdin
E 10
and
D 10
.BR stdout .
E 10
I 10
.Em stdout .
E 10
If
D 10
.I fd2p
E 10
I 10
.Fa fd2p
E 10
D 4
is non-zero, then a auxiliary channel to a control
E 4
I 4
is non-zero, then an auxiliary channel to a control
E 4
process will be setup, and a descriptor for it will be placed
in
D 10
.IR *fd2p .
E 10
I 10
.Fa *fd2p .
E 10
The control process will return diagnostic
output from the command (unit 2) on this channel, and will also
D 10
accept bytes on this channel as being UNIX signal numbers, to be
E 10
I 10
accept bytes on this channel as being
.Tn UNIX
signal numbers, to be
E 10
D 2
forwarded to the process group of the command.
E 2
I 2
forwarded to the process group of the command.  The diagnostic
information returned does not include remote authorization failure,
as the secondary connection is set up after authorization has been
verified.
E 2
If
D 10
.I fd2p
E 10
I 10
.Fa fd2p
E 10
is 0, then the 
D 10
.B stderr
E 10
I 10
.Em stderr
E 10
(unit 2 of the remote
command) will be made the same as the 
D 10
.B stdout
E 10
I 10
.Em stdout
E 10
and no
provision is made for sending arbitrary signals to the remote process,
although you may be able to get its attention by using out-of-band data.
D 10
.SH SEE ALSO
D 5
rcmd(3X), rexecd(8C)
.SH BUGS
There is no way to specify options to the
.I socket
call
which
.I rexec
makes.
E 5
I 5
D 7
rcmd(3), rexecd(8C)
E 7
I 7
rcmd(3), rexecd(8)
E 10
I 10
.Sh SEE ALSO
.Xr rcmd 3 ,
.Xr rexecd 8
.Sh HISTORY
The
.Fn rexec
function appeared in 
.Bx 4.2 .
E 10
E 7
E 5
E 1
