h54821
s 00005/00004/00083
d D 6.6 91/05/10 13:32:04 cael 6 5
c mdoc version three
e
s 00076/00043/00011
d D 6.5 91/03/16 18:12:07 cael 5 4
c macro and text revision (-mdoc version 3)
e
s 00002/00012/00052
d D 6.4 90/06/24 22:16:20 trent 4 3
c new copyright & pathname (dlpmcc)
e
s 00017/00003/00047
d D 6.3 88/10/19 09:41:30 bostic 3 2
c add Berkeley specific copyright
e
s 00006/00000/00044
d D 6.2 88/05/04 15:49:17 bostic 2 1
c update from Keith Muller
e
s 00044/00000/00000
d D 6.1 87/05/01 19:21:19 mckusick 1 0
c from CCI
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1987 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 5
.\" Copyright (c) 1987 The Regents of the University of California.
E 5
I 5
D 6
.\" Copyright (c) 1987, 1991 The Regents of the University of California.
E 6
I 6
.\" Copyright (c) 1987, 1991, 1991 The Regents of the University of California.
E 6
E 5
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Computer Consoles Inc.
D 5
.\"
E 5
D 4
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 4
I 4
D 6
.\" %sccs.include.redist.man%
E 6
E 4
E 3
.\"
I 6
.\"	%sccs.include.redist.roff%
.\"
E 6
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 5
.TH DLMPCC 8 "%Q%"
.UC 7
.SH NAME
dlmpcc \- download MPCC
.SH SYNOPSIS
\fBdlmpcc\fR  [ n ]
.SH DESCRIPTION
\fIDlmpcc\fR downloads CCI's Multi-Protocol
Communication Controller (MPCC).
E 5
I 5
.Dd %Q%
.Dt DLMPCC 8
.Os
.Sh NAME
.Nm dlmpcc
.Nd download
D 6
MPCC
E 6
I 6
.Tn MPCC
E 6
.Sh SYNOPSIS
.Nm dlmpcc
.Op n
.Sh DESCRIPTION
.Nm Dlmpcc
downloads
.Tn CCI's
Multi-Protocol
Communication Controller
.Pq Tn MPCC .
E 5
The controller provides high-speed
D 5
synchronous communications for the \s-1POWER 5\s+1 and \s-1POWER 6\s+1 families of computers.
E 5
I 5
synchronous communications for the
.Tn POWER
5 and
.Tn POWER
6 families of computers.
E 5
This utility allows you to 
D 5
download any or all of the MPCC boards.
The configuration file \fBmpcctab\fR determines
the protocol attributes for each MPCC board. See
\fImpcctab\fR(4) for details. 
.LP
If you specify the command with no argument, then \fIdlmpcc\fR
scans the configuration file and downloads all configured boards
with corresponding protocol software. The 
option \fIn\fR allows you to specify one or
more MPCC boards for downloading. The valid values range from
\fB0-15\fR. For example, the following command line orders \fIdlmpcc\fR
E 5
I 5
download any or all of the
.Tn MPCC
boards.
The configuration file
.Pa mpcctab
determines
the protocol attributes for each
.Tn MPCC
board. See
.Xr mpcctab 4
for details. 
.Pp
If you specify the command with no argument, then
.Xr dlmpcc
scans the configuration file
.Pa mpcctab
and downloads all configured boards
with corresponding protocol software.
.Pp
Available option:
.Pp
.Bl -tag -width Ds
.It Ar n
Specify one or
more
.Tn MPCC
boards for downloading. The valid values range from
.Sy 0-15 .
For example, the following command line orders
.Nm dlmpcc
E 5
to download only the protocol software identified with board 2:
D 5
.nf

        dlmpcc  2

.fi
The next command line orders the download
of the protocols identified with
E 5
I 5
.Pp
.Dl dlmpcc  2
.Pp
The next command line orders the download of the protocols identified with
E 5
boards 0 and 3: 
D 5
.nf

        dlmpcc  0  3
.fi 
I 2
.LP
Typically, this download function is performed at boot time from the
/etc/rc.local file with an entry similar to:
.nf
D 4
        /etc/dlmpcc > /dev/console 2>&1
E 4
I 4
        /usr/sbin/dlmpcc > /dev/console 2>&1
E 4
.fi
E 2
.SH SEE ALSO
mpcctab(4)
E 5
I 5
.Pp
.Dl dlmpcc  0  3
.El
.Pp
Typically, this download function is performed at boot time from the
.Pa /etc/rc.local
file with an entry similar to:
.Bd -literal -offset indent
/usr/sbin/dlmpcc > /dev/console 2>&1
.Ed
.Sh SEE ALSO
D 6
.Xr mpcctab 4
E 6
I 6
.Xr mpcctab 4 ,
E 6
.Xr rc 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.3 tahoe .
E 5
E 1
