h42592
s 00001/00001/00097
d D 8.4 94/04/19 06:37:57 bostic 9 8
c spell
e
s 00001/00001/00097
d D 8.3 94/04/18 07:41:46 bostic 8 7
c typo
e
s 00003/00004/00095
d D 8.2 94/04/16 12:05:47 bostic 7 6
c prettiness police
e
s 00002/00002/00097
d D 8.1 93/06/06 22:22:10 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00003/00096
d D 5.3 93/03/23 18:58:06 cael 5 4
c update .Os and history from .Ud to .Bx 4.4
e
s 00081/00051/00018
d D 5.2 91/04/23 22:54:33 cael 4 3
c mdoc version three/bsd copyright
e
s 00001/00011/00068
d D 5.1 91/04/18 18:41:30 bostic 3 2
c yank to 5.1, new copyright; att/bsd/shared
e
s 00033/00045/00046
d D 1.2 90/06/29 00:41:43 marc 2 1
c cencode -> vis; rewrite
e
s 00091/00000/00000
d D 1.1 90/05/15 14:28:10 marc 1 0
c date and time created 90/05/15 14:28:10 by marc
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1989 The Regents of the University of California.
E 4
I 4
D 6
.\" Copyright (c) 1989, 1991 The Regents of the University of California.
E 4
.\" All rights reserved.
E 6
I 6
D 7
.\" Copyright (c) 1989, 1991, 1993
E 7
I 7
.\" Copyright (c) 1989, 1991, 1993, 1994
E 7
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 3
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 3
I 3
.\" %sccs.include.redist.roff%
E 3
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\"     %W% (Berkeley) %G%
E 4
.\"
D 2
.TH <VIS> <1> "%Q%"
E 2
I 2
D 4
.TH VIS 1 "%Q%"
E 2
.UC 7
.SH NAME
vis \- display non-printable characters in a visual format
.SH SYNOPSIS
.B vis
[
D 2
.B \-nwcgoifsh
E 2
I 2
.B \-nwctsobfl
E 2
] [
.B \-F
foldwidth
] [ file ... ]
.SH DESCRIPTION
\fIVis\fP is a filter for converting non-printable characters
into a visual representation.  It differs from cat -v in that
E 4
I 4
.Dd %Q%
.Dt VIS 1
D 5
.Os
E 5
I 5
.Os BSD 4.4
E 5
.Sh NAME
.Nm vis
.Nd display non-printable characters in a visual format
.Sh SYNOPSIS
.Nm vis
.Op Fl cbflnostw
.Op Fl F Ar foldwidth
.Op Ar file ...
.Sh DESCRIPTION
.Nm Vis
is a filter for converting non-printable characters
into a visual representation.  It differs from
.Ql cat -v
in that
E 4
D 2
the form is unique and invertible.  A detailed description of the
various visual formats is given in cencode(3).
E 2
I 2
the form is unique and invertible.  By default, all non-graphic
characters except space, tab, and newline are encoded.
A detailed description of the
D 4
various visual formats is given in vis(3).
E 2
.SH OPTIONS
D 2
The c, g, and o flags select a particular display format.  All
three can be requested independent of each other, since two
of them only operate on a subset of the non-printable characters.
E 2
.IP -c
E 4
I 4
various visual formats is given in
.Xr vis 3 .
.Pp
D 7
Options supported by
.Nm vis :
E 7
I 7
The options are as follows:
E 7
.Bl -tag -width Ds
.It Fl b
Turns off prepending of backslash before up-arrow control sequences
and meta characters, and disables the doubling of backslashes.  This
produces output which is neither invertible or precise, but does
represent a minimum of change to the input.  It is similar to
.Dq Li cat -v .
.It Fl c
E 4
Request a format which displays a small subset of the
non-printable characters using C-style backslash sequences.
D 2
.IP -g
Request a format which displays non-printable characters
using a \\^C notation for control characters, and \\M notation
for meta characters (chars with the 8th bit set).  All non-printables,
except space and meta-space when using the \-w flag, can be encoded 
using this format.
E 2
D 4
.IP -o
Request a format which displays non-printable characters as
D 2
an octal number, \\ddd.  All non-printable characters can
be displayed using this format.
E 2
I 2
an octal number, \\ddd.
.IP -t
Tabs are also encoded.
E 2
.IP -w
D 2
Normally
.B vis
considers white space (space-tab-newline) as printable.  The -w
flag causes white space to be encoded in a visual form.
.IP -i
Causes
.B vis
to invert visually encoded data back to its original form.  When
using -i, it is unnecessary to select an encoding format, since
all formats are unique and invertible.
E 2
I 2
White space (space-tab-newline) is also encoded.
.IP -s
Only characters considered unsafe to send to a terminal are encoded.
This flag allows backspace, bell, and carriage return in addition
to the default space, tab and newline.
E 2
.IP -f
and
.IP -F
E 4
I 4
.It Fl F
E 4
Causes
D 4
.B vis
to fold output lines to foldwidth columns (default 80), like fold(1), except
E 4
I 4
.Nm vis
to fold output lines to foldwidth columns (default 80), like
.Xr fold 1 ,
except
E 4
D 2
that a hidden newline sequence is used, which is removed
when inverting the file back to its original form with -i.
E 2
I 2
that a hidden newline sequence is used, (which is removed
D 4
when inverting the file back to its original form with unvis(1)).
E 4
I 4
when inverting the file back to its original form with
.Xr unvis 1 ) .
E 4
E 2
If the last character in the encoded file does not end in a newline,
D 2
.B vis
automatically appends a hidden newline to the end.  This makes
various editors and other utilities happy.
.IP -s
Causes vis to strip the 8th bit on all characters.  This obviously
produces non-invertible output.
E 2
I 2
a hidden newline sequence is appended to the output.
This makes
D 8
the output usuable with various editors and other utilities which
E 8
I 8
the output usable with various editors and other utilities which
E 8
typically don't work with partial lines.
E 2
D 4
.IP -n
E 4
I 4
.It Fl f
Same as
.Fl F .
.It Fl l
D 9
Mark newlines with the visable sequence
E 9
I 9
Mark newlines with the visible sequence
E 9
.Ql \e$ ,
followed by the newline.
.It Fl n
E 4
D 2
Normally, if none of -c, -g, or -o are selected, vis turns on
all three flags.  The -n flag forces vis to disable any encoding,
except for backslash stuffing and line length folding.
.IP -h
When using -i to invert data, this causes
.B vis
to treat the hat (^) as a special character all the time (normally, all
visual sequences are preceded by a backslash).  This option
is provided for compatibility with the common convention that ^C
introduces a control character sequence; however, the new invertible
sequence, \\^C, is recommended as the preferred representation.
E 2
I 2
Turns off any encoding, except for the fact that backslashes are
D 4
still doubled and hidden newline sequences inserted if -f or -F
is selected.  When combined with the -f flag, vis becomes like
an invertible version of the fold(1) utility.  That is, the output
can be unfolded by running the output through unvis(1).
.IP -b
Turns off prepending of backslash before up-arrow control sequences
and Meta characters, and disables the doubling of backslashes.  This
produces output which is neither invertible or precise, but does
represent a minimum of change to the input.  It is similar to cat -v.
.IP -l
Mark newlines with the visable sequence '\\$', followed by the newline.
E 2
.SH "SEE ALSO
D 2
cencode(3)
E 2
I 2
unvis(1) vis(3)
E 4
I 4
still doubled and hidden newline sequences inserted if
.Fl f
or
.Fl F
is selected.  When combined with the
.Fl f
flag,
.Nm vis
becomes like
an invertible version of the
.Xr fold 1
utility.  That is, the output
can be unfolded by running the output through
.It Fl o
Request a format which displays non-printable characters as
an octal number, \eddd.
.It Fl s
Only characters considered unsafe to send to a terminal are encoded.
This flag allows backspace, bell, and carriage return in addition
to the default space, tab and newline.
.Xr unvis 1 .
.It Fl t
Tabs are also encoded.
.It Fl w
White space (space-tab-newline) is also encoded.
.El
.Sh SEE ALSO
D 7
.Xr unvis 1
E 7
I 7
.Xr unvis 1 ,
E 7
.Xr vis 3
.Sh HISTORY
The
.Nm
D 5
command is
.Ud .
E 5
I 5
command appears in
.Bx 4.4 .
E 5
E 4
E 2
E 1
