.TH SCALECH 8 "February 1984"
.SH NAME
scalech \- shrink a character format font
.SH SYNOPSIS
.br
.B scalech
[
.BI \-s %
]
filename
.SH DESCRIPTION
.I Scalech
reads the character font
.I filename
and scales down each glyph by a percentage given by the
.B \-s
option, then writes the font to standard output.  If no
.B \-s
option is specified, the default shrink factor is 50 percent.  If
.I filename
is missing standard input is read.  See vft2ch(8) for a description
of the character font format.
.PP
The scaling of each glyph is done with respect to its
reference point.  Since scaling a raster image
is not a clean operation the resulting glyphs may
need some smoothing out by hand.  This can be accomplished
by hand-editing the output with
.I vi
or by using the font editor (slug) on a SUN workstation
that edits the ``.@'' format.
.SH "SEE ALSO"
.nf
vfontinfo(1), ch2vft(8),
doublech(8), vft2ch(8)
.SH AUTHOR
David Slattengren
