.TH VSORT 8 "February 1984"
.SH NAME
vsort \- ditroff translator for dver
.SH SYNOPSIS
.br
.B vsort
filename
.SH DESCRIPTION
.PP
.I Vsort
reads
.I ditroff
output file
.I filename
(or standard input if
.I filename
is missing), performs a vertical sort, and positions document pages
together to be printed across a Versatec Electrostatic Plotter's paper.
.I Vsort
writes, to standard output, ditroff output language with one small
addition.  Its output is meant to be read by
.IR dver (8)
to be converted to rasters for the printer.
.PP
The addition
.I vsort
makes to
.IR ditroff 's
output is a new command,
.BR P ,
that forces
.I dver
to output a section of raster.
.I Vsort
breaks up
.IR ditroff 's
output into one-inch horizontal bands and makes sure everything
that should be on each band is present between `P' commands.
.IR Vsort 's
output is also accepted by
.I dterm
and
.IR dsun .
.SH "SEE ALSO"
.nf
dver(8)
.SH AUTHOR
David Slattengren
