h06024
s 00002/00002/00005
d D 8.1 93/06/08 12:42:57 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00003/00003
d D 6.2 91/04/17 12:21:18 bostic 4 3
c new copyright; att/bsd/shared
e
s 00000/00000/00006
d D 6.1 86/05/23 12:02:38 kjd 3 2
c document distributed with 4.3BSD
e
s 00000/00000/00006
d D 5.1 86/05/23 12:02:32 kjd 2 1
c document distributed with 4.2BSD
e
s 00006/00000/00000
d D 4.1 86/05/23 12:02:26 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 5
.\" Copyright (c) 1980 The Regents of the University of California.
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1980, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" %sccs.include.redist.roff%
E 4
.\"
.\"	%W% (Berkeley) %G%
.\"
E 1
