h03779
s 00002/00002/00043
d D 8.1 93/06/08 12:41:57 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00003/00041
d D 6.4 91/04/17 12:21:09 bostic 6 5
c new copyright; att/bsd/shared
e
s 00003/00007/00041
d D 6.3 90/06/20 18:58:39 leres 5 4
c Put "revisors" on one line to conserve vertical space.
e
s 00009/00001/00039
d D 6.2 90/06/19 20:34:30 leres 4 3
c Updates from Mark Andrews (mark%alias@yonge.csri.toronto.edu).
e
s 00034/00000/00006
d D 6.1 86/05/23 11:58:50 kjd 3 2
c document distributed with 4.3BSD
e
s 00000/00024/00006
d D 5.1 86/05/23 11:58:45 kjd 2 1
c document distributed with 4.2BSD
e
s 00030/00000/00000
d D 4.1 86/05/23 11:58:40 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
D 7
.\" Copyright (c) 1980 The Regents of the University of California.
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1980, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
.\" %sccs.include.redist.roff%
E 6
.\"
.\"	%W% (Berkeley) %G%
.\"
I 3
.eh 'USD:7-%''Mail Reference Manual'
.oh 'Mail Reference Manual''USD:7-%'
.if n \
.nr fs .5v
.\".he 'Mail Reference Manual'\n(mo/\n(dy/\n(yr'%'
.tp
.sp 1.0i
.sz 12
.rb
.(l C
MAIL REFERENCE MANUAL
.)l
.sz 10
.sp 2
.i
.(l C
Kurt Shoens
.)l
.r
.(l C
Revised by
.)l
D 5
.i
E 5
.(l C
D 5
Craig Leres
.)l
E 5
I 5
.i
Craig Leres\ \c
E 5
.r
D 5
.(l C
D 4
Version 5.2
E 4
I 4
and
.)l
E 5
I 5
and\ \c
E 5
.i
D 5
.(l C
E 5
Mark Andrews
.)l
.r
.(l C
Version 5.5
E 4


\*(td
.)l
.pn 2
E 3
D 2
.if n \
.nr fs .5v
.he 'Mail Reference Manual'\n(mo/\n(dy/\n(yr'%'
.tp
.sp 1.5i
.sz 12
.rb
.(l C
MAIL REFERENCE MANUAL
.)l
.sz 10
.sp 2
.i
.(l C
Kurt Shoens
.)l
.r
.(l C
Version 1.3


\*(td
.)l
.pn 2
E 2
E 1
