h56369
s 00002/00002/00102
d D 8.1 93/06/06 16:41:30 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00056/00092/00048
d D 6.5 92/01/09 10:37:54 bostic 7 6
c make source match the man page, handle -number/+number more cleanly
e
s 00003/00000/00137
d D 6.4 91/06/27 17:26:18 bostic 6 5
c add POSIX/IEEE contribution notice
e
s 00130/00060/00007
d D 6.3 91/04/26 03:46:19 cael 5 4
c mdoc version three/POSIX'd/bsd copyright
e
s 00005/00000/00062
d D 6.2 91/04/18 18:35:12 bostic 4 3
c new copyright; att/bsd/shared
e
s 00001/00001/00061
d D 6.1 85/04/29 18:07:57 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00012/00025/00050
d D 5.1 85/04/29 18:07:43 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00075/00000/00000
d D 4.1 85/04/29 18:07:34 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 5
.\" Copyright (c) 1985 The Regents of the University of California.
E 5
I 5
D 8
.\" Copyright (c) 1991 Regents of the University of California.
E 5
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
I 6
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 6
D 5
.\" %sccs.include.proprietary.roff%
E 5
I 5
.\" %sccs.include.redist.roff%
E 5
.\"
E 4
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
.\"
D 2
.TH UNIQ 1 
E 2
I 2
D 3
.TH UNIQ 1  "10 February 1983"
E 3
I 3
D 5
.TH UNIQ 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
uniq \- report repeated lines in a file
.SH SYNOPSIS
.B uniq
[
.B \-udc
[
.BR + n
] [
.BR \- n
]
] [ input [ output ] ]
.SH DESCRIPTION
.I Uniq
D 2
reads the input
file comparing adjacent lines.
In the normal case, the second and succeeding copies
of repeated lines are
E 2
I 2
reads the input file comparing adjacent lines.
In the normal case, the second and succeeding copies of repeated lines are
E 2
removed; the remainder is written on the output file.
D 2
Note that repeated lines must be adjacent
in order to be found;
see
E 2
I 2
Note that repeated lines must be adjacent in order to be found; see
E 2
.IR  sort (1).
E 5
I 5
.Dd %Q%
.Dt UNIQ 1
.Os
.Sh NAME
.Nm uniq
D 7
.Nd Report or filter out repeated lines in a file.
E 7
I 7
.Nd report or filter out repeated lines in a file
E 7
.Sh SYNOPSIS
.Nm uniq
.Op Fl c | Fl d | Fl u
.Op Fl f Ar fields
.Op Fl s Ar chars
.Oo
.Ar input_file
.Op Ar output_file
.Oc
D 7
.Pp
Deprecated Version:
.Pp
.Nm uniq
.Op Fl cdu
.Op Fl Ns Ar n
.Op Cm \(pl Ns Ar n
.Oo
.Ar input_file
.Op Ar output_file
.Oc
E 7
.Sh DESCRIPTION
The
.Nm uniq
D 7
utility reads an input file or the standard input
comparing adjacent
lines, and writes one copy of each input line on the output.
The second and succeeding copies of repeated adjacent input
lines are not written.
Repeated lines in the input are not detected if they are
not adjacent, so it is important to
.Xr sort 1
the files first.
E 7
I 7
utility reads the standard input comparing adjacent lines, and writes
a copy of each unique input line to the standard output.
The second and succeeding copies of identical adjacent input lines are
not written.
Repeated lines in the input will not be detected if they are not adjacent,
so it may be necessary to sort the files first.
E 7
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl c
D 7
Precede each output line with a count of the number
of times the line occurred in the input. For example:
.Bd -literal -offset indent
duplicate_count line_number
.Ed
.Pp
where the duplicate count is a blank padded field of
up to four digits followed by a space.
E 7
I 7
Precede each output line with the count of the number of times the line
occurred in the input, followed by a single space.
E 7
.It Fl d
D 7
Suppress the writing of lines that are not repeated
in the input.
E 7
I 7
Don't output lines that are not repeated in the input.
E 7
.It Fl f Ar fields
D 7
Ignore the first fields on each input line when
doing comparisons, where fields is a positive
decimal integer.
A field is a string of non-blank
characters separated from adjacent fields
E 7
I 7
Ignore the first
.Ar fields
in each input line when doing comparisons.
A field is a string of non-blank characters separated from adjacent fields
E 7
by blanks.
I 7
Field numbers are one based, i.e. the first field is field one.
E 7
.It Fl s Ar chars
D 7
Ignore the first chars characters when doing
comparisons, where chars is a positive decimal
integer.
E 7
I 7
Ignore the first
.Ar chars
characters in each input line when doing comparisons.
E 7
If specified in conjunction with the
.Fl f
D 7
option, the first chars characters after the first
fields fields will be ignored.
E 7
I 7
option, the first
.Ar chars
characters after the first
.Ar fields
fields will be ignored.
Character numbers are one based, i.e. the first character is character one.
E 7
.It Fl u
D 7
Suppress the writing of lines that are repeated in
the input.
.It Fl Ns Ar n
(Deprecated; replaced by
.Fl f ) .
Ignore the first n
fields on each input line when doing comparisons,
where n is a number.
A field is a string of non-blank
characters separated from adjacent fields
by blanks.
.It Cm \&\(pl Ns Ar n
(Deprecated; replaced by
.Fl s ) .
Ignore the first
.Ar m
characters when doing comparisons, where
.Ar m
is a
number.
E 7
I 7
Don't output lines that are repeated in the input.
.\".It Fl Ns Ar n
.\"(Deprecated; replaced by
.\".Fl f ) .
.\"Ignore the first n
.\"fields on each input line when doing comparisons,
.\"where n is a number.
.\"A field is a string of non-blank
.\"characters separated from adjacent fields
.\"by blanks.
.\".It Cm \&\(pl Ns Ar n
.\"(Deprecated; replaced by
.\".Fl s ) .
.\"Ignore the first
.\".Ar m
.\"characters when doing comparisons, where
.\".Ar m
.\"is a
.\"number.
E 7
.El
.Pp
D 7
The following operands are available:
.Bl -tag -width output_filex
.It Ar input_file
A pathname of the input file.
E 5
If the
D 5
.B \-u
D 2
flag is used,
just the lines that are not repeated
in the original file are output.
The
E 2
I 2
flag is used, just the lines that are not repeated
in the original file are output.  The
E 2
.B \-d
D 2
option specifies that
one copy of just the repeated lines is to
be written.
E 2
I 2
option specifies that one copy of just the repeated lines is to be written.
E 2
The normal mode output is the union of the
.B \-u
and
.B \-d
mode outputs.
.PP
E 5
I 5
.Ar input_file
operand is not specified, the standard input is
used.
.It Ar output_file
A pathname of the output file.
This name shall
always be different from
.Ar input_file.
If the
.Ar output_file
operand is not specified, the standard
output is used.  If
.Ar output_file
is created and an error occurs or a sugnal is caught the
.Ar output_file
is not removed.
.El
.\" .Pp
.\" The following environment variables affect the execution of
.\" uniq:
.\" .Tl Em LC_CTYPE
.\" The locale for character classification, used to
.\" determine the characters constituting a blank in
.\" the current locale.
E 7
I 7
If additional arguments are specified on the command line, the first
such argument is used as the name of an input file, the second is used
as the name of an output file.
E 7
.Pp
E 5
The
D 5
.B \-c
option supersedes
.B \-u
and
.B \-d
D 2
and generates
an output report in default style
but with each line preceded by a count of the
number of times it occurred.
E 2
I 2
and generates an output report in default style
but with each line preceded by a count of the number of times it occurred.
E 2
.PP
E 5
I 5
D 7
.Xr uniq
E 7
I 7
.Nm uniq
E 7
utility exits 0 on success, and >0 if an error occurs.
I 7
.Sh COMPATIBILITY
The historic
.Cm \&\(pl Ns Ar number
and
.Fl Ns Ar number
options have been deprecated but are still supported in this implementation.
.Sh SEE ALSO
.Xr sort 1
E 7
.Sh STANDARDS
E 5
The
D 5
.I n
D 2
arguments specify skipping an initial portion of each line
in the comparison:
E 2
I 2
arguments specify skipping an initial portion of each line in the comparison:
E 2
.TP 8
.BI \- n
The first
.IR n 
D 2
fields
together with any blanks before each are ignored.
E 2
I 2
fields together with any blanks before each are ignored.
E 2
A field is defined as a string of non-space, non-tab characters
separated by tabs and spaces from its neighbors.
.TP 8
.BI + n
The first
.IR n 
D 2
characters are ignored.
Fields are skipped before characters.
E 2
I 2
characters are ignored.  Fields are skipped before characters.
E 2
.PP
.SH "SEE ALSO"
sort(1), comm(1)
E 5
I 5
D 7
.Xr uniq
E 7
I 7
.Nm uniq
E 7
utility is expected to be
.St -p1003.2
compatible.
E 5
E 1
