h64626
s 00002/00002/00095
d D 8.1 93/06/06 16:13:02 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00013/00013/00084
d D 6.5 91/07/27 16:18:40 cael 8 7
c mdoc version three
e
s 00002/00000/00095
d D 6.4 91/03/14 00:27:39 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00095
d R 6.4 91/03/13 20:38:05 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00091/00038/00004
d D 6.3 90/07/24 22:51:34 cael 5 4
c .Xr botch fix
e
s 00003/00003/00039
d D 6.2 90/06/24 19:15:24 cael 4 3
c converted man page
e
s 00001/00001/00041
d D 6.1 85/04/29 15:01:29 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00018/00049/00024
d D 5.1 85/04/29 15:01:15 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00073/00000/00000
d D 4.1 85/04/29 15:01:05 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
E 4
I 4
D 9
.\" Copyright (c) 1980, 1990 Regents of the University of California.
E 4
D 5
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 5
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\"		%W% (Berkeley) %G%
E 5
I 5
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
E 5
E 4
.\"
D 2
.TH SCRIPT 1
E 2
I 2
D 3
.TH SCRIPT 1 "26 March 1982"
E 3
I 3
D 4
.TH SCRIPT 1 "%Q%"
E 4
I 4
D 5
.TH SCRIPT 1 "%Q"
E 4
E 3
E 2
.UC 4
.SH NAME
script \- make typescript of terminal session
.SH SYNOPSIS
.B script
[
.B \-a
D 2
] [
.B \-q
] [
.B \-S
shell
E 2
] [ file ]
.SH DESCRIPTION
.I Script
E 5
I 5
D 8
.\"     %W% (Berkeley) %G%
E 8
I 8
.\"	%W% (Berkeley) %G%
E 8
.\"
I 7
D 8
.Vx
.Vx
E 8
E 7
.Dd %Q%
.Dt SCRIPT 1
.Os BSD 4
.Sh NAME
.Nm script
.Nd make typescript of terminal session
.Sh SYNOPSIS
.Nm script
.Op Fl a
.Op Ar file
.Sh DESCRIPTION
.Nm Script
E 5
makes a typescript of everything printed on your terminal.
D 2
The typescript is saved in a file, and can be sent to the
line printer later with
.I lpr.
If a file name is given, the typescript
is saved there.  If not, the typescript is saved in the file
.I typescript.
E 2
I 2
D 5
The typescript is written to 
.IR file ,
or appended to
.IR file
if the
.B \-a
option is given.
It can be sent to the line printer later with
.IR lpr .
If no file name is given, the typescript
is saved in the file
.IR typescript .
E 2
.PP
D 2
To exit script, type control D.  This sends an end of file to
all processes you have started up, and causes script to exit.
For this reason, control D behaves as though you had typed an
infinite number of control D's.
E 2
I 2
The script ends when the forked shell exits.
E 2
.PP
This program is useful when using a crt and a hard-copy
record of the dialog is desired, as for a student handing
in a program that was developed on a crt when hard-copy
terminals are in short supply.
D 2
.PP
.B \-S
lets you specify the shell to use.
The default depends on the system:
If the variable SHELL is set in the environment, it is used if possible.
.PP
The
.B \-q
flag asks for ``quiet mode'', where the ``script started''
and ``script done'' messages are turned off.
The
.B \-a
flag causes script to append to the typescript file
instead of creating a new file.
.SH AUTHOR
Mark Horton
E 2
.SH BUGS
D 2
Since UNIX has no way to write an end-of-file down a pipe without closing
the pipe, there is no way to simulate a single control D without
ending script.
.PP
The new shell has its standard input coming
from a pipe rather than a tty, so stty will not work, and neither
will ttyname.
In particular, this means that screen editors such as
.IR vi (1)
and the job control facilities of
.IR csh (1)
are inoperative.
.PP
When the user interrupts a printing process,
.I script
attempts to flush the output backed up in the pipe for better response.
Usually the next prompt also gets flushed.
E 2
I 2
.I Script
places 
.B everything
in the log file.  This is not what the naive user expects.
E 5
I 5
It is useful for students who need a hardcopy record of an interactive
session as proof of an assignment, as the typescript file 
can be printed out later with
.Xr lpr 1 .
.Pp
If the argument
.Ar file
is given,
.Nm
saves all dialogue in
.Ar file .
If no file name is given, the typescript is saved in the file
.Pa typescript  .
.Pp
Option:
D 8
.Tw Ds
.Tp Fl a
E 8
I 8
.Bl -tag -width Ds
.It Fl a
E 8
Append the output to
.Ar file
or
.Pa typescript ,
retaining the prior contents.
D 8
.Tp
E 8
I 8
.El
E 8
.Pp
The script ends when the forked shell exits (a
.Em control-D
to exit
the Bourne shell
D 8
.Pf \&( Xr sh 1 ) ,
E 8
I 8
.Pf ( Xr sh 1 ) ,
E 8
and
.Em exit , 
.Em logout
or
.Em control-d
(if
.Em ignoreeof
is not set) for the
C-shell,
.Xr csh 1 ) .
.Pp
Certain interactive commands, such as
.Xr vi 1 ,
create garbage in the typescript file.
.Nm Script
works best with commands that do not manipulate the
screen, the results are meant to emulate a hardcopy
terminal.
.Sh ENVIRONMENT
The following environment variable is utilized by
.Nm script :
D 8
.Tw SHELL
.Tp Ev SHELL
E 8
I 8
.Bl -tag -width SHELL
.It Ev SHELL
E 8
If the variable
.Ev SHELL
exists, the shell forked by
.Nm script
will be that shell. If
.Ev SHELL
is not set, the Bourne shell
is assumed. (Most shells set this variable automatically).
D 8
.Tp
E 8
I 8
.El
E 8
.Sh SEE ALSO
.Xr csh 1
(for the
.Em history
mechanism).
.Sh HISTORY
D 8
.Nm Script
appeared in 3 BSD.
E 8
I 8
The
.Nm script
command appeared in
.Bx 3.0 .
E 8
.Sh BUGS
.Nm Script
places
.Sy everything
in the log file, including linefeeds and backspaces.
This is not what the naive user expects.
E 5
E 2
E 1
