h11675
s 00001/00000/00298
d D 8.4 94/06/01 20:45:55 ah 16 15
c page breaks for 4.4BSD manuals
e
s 00062/00035/00236
d D 8.3 94/03/19 19:38:52 sklower 15 14
c keeping up with recent flags, and documenting them
e
s 00001/00001/00270
d D 8.2 93/12/11 23:43:21 mckusick 14 13
c copyediting for Usenix manuals
e
s 00002/00002/00269
d D 8.1 93/06/05 11:12:49 bostic 13 12
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00180/00172/00091
d D 6.11 91/03/16 17:08:38 cael 12 11
c macro and text revision (-mdoc version 3)
e
s 00017/00005/00246
d D 6.10 90/09/03 14:27:14 sklower 11 10
c document recent changes
e
s 00001/00001/00250
d D 6.9 90/07/26 16:55:40 sklower 10 9
c refer to route(4) and esis(4) manual pages.
e
s 00002/00012/00249
d D 6.8 90/06/24 21:53:07 trent 9 8
c new copyright & pathname (route)
e
s 00009/00006/00252
d D 6.7 90/05/23 16:05:31 sklower 8 7
c you can no longer combine flush with any other operation;
c attempt (in vain) to clarify netmask parameter.
e
s 00074/00013/00184
d D 6.6 90/05/23 15:51:35 sklower 7 6
c provide way to specify and lock metrics, delete reference to -k option,
c explain assumptions about dotted number internet notation
e
s 00032/00028/00165
d D 6.5 90/04/16 12:58:41 sklower 6 5
c check in for alpha-2 tape to wisconsin, honig, nbs, cray
e
s 00052/00024/00141
d D 6.4 89/08/21 13:55:39 sklower 5 4
c interim support for ISO
e
s 00016/00007/00149
d D 6.3 88/09/19 21:49:24 bostic 4 3
c Berkeley header
e
s 00060/00031/00096
d D 6.2 86/05/24 21:09:15 karels 3 2
c updates
e
s 00001/00001/00126
d D 6.1 85/04/27 15:43:18 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00127/00000/00000
d D 5.1 85/04/27 15:42:52 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 12
.\" Copyright (c) 1983 The Regents of the University of California.
E 12
I 12
D 13
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 12
.\" All rights reserved.
E 13
I 13
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 13
E 4
.\"
I 4
D 9
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 9
I 9
.\" %sccs.include.redist.man%
E 9
.\"
E 4
D 12
.\"	%W% (Berkeley) %G%
E 12
I 12
.\"     %W% (Berkeley) %G%
E 12
.\"
D 2
.TH ROUTE 8C "5 May 1983"
E 2
I 2
D 4
.TH ROUTE 8C "%Q%"
E 4
I 4
D 12
.TH ROUTE 8 "%Q%"
E 4
E 2
.UC 5
.SH NAME
D 5
route \- manually manipulate the routing tables
E 5
I 5
route \- manually manipulate the routing tables (Interim)
E 5
.SH SYNOPSIS
D 9
.B /etc/route
E 9
I 9
.B route
E 9
[
I 5
D 6
.B \-i
] [
E 5
.B \-f
] [
E 6
I 3
.B \-n
] [
I 5
.B \-q
] [
I 6
.B \-v
D 7
] [
E 6
.B \-k
.I vmunix
E 7
D 6
] [
.B \-x
] [
.B \-o
] [
E 5
E 3
.I command args
E 6
]
I 6
.I command
[ [
.I modifiers
]
.I args
]
E 6
.SH DESCRIPTION
.I Route
E 12
I 12
.Dd %Q%
.Dt ROUTE 8
D 15
.Os BSD 4.2
E 15
I 15
.Os BSD 4.4
E 15
.Sh NAME
.Nm route
D 15
.Nd manually manipulate the routing tables (Interim)
E 15
I 15
.Nd manually manipulate the routing tables.
E 15
.Sh SYNOPSIS
.Nm route
D 15
.Op Fl n
.Op Fl q
.Op Fl v
E 15
I 15
.Op Fl nqv
E 15
.Ar command
.Oo
.Op Ar modifiers
.Ar args
.Oc
.Sh DESCRIPTION
.Nm Route
E 12
D 15
is a program used to manually manipulate the network
routing tables.  It normally is not needed, as the
system routing table management daemon,
E 15
I 15
is a utility used to manually manipulate the network
routing tables.  It normally is not needed, as a
system routing table management daemon such as
E 15
D 12
.IR routed (8C),
E 12
I 12
.Xr routed 8 ,
E 12
should tend to this task.
D 12
.PP
.I Route
D 3
accepts three commands:
E 3
I 3
D 5
accepts two commands:
E 5
I 5
D 6
accepts three commands:
E 6
I 6
D 11
accepts five commands:
E 11
I 11
accepts six commands:
E 11
E 6
E 5
E 3
.IR add ,
D 3
to add a route;
E 3
I 3
D 5
to add a route, and
E 5
I 5
to add a route,
I 6
.IR flush ,
to remove all routes,
E 6
E 5
E 3
.IR delete ,
D 3
to delete a route; and
.IR change ,
to modify an existing route.
E 3
I 3
D 5
to delete a route.
E 5
I 5
D 6
to delete a route, and
E 6
I 6
to delete a specific route,
.IR change ,
to changes aspects of a route (such as its gateway),
I 11
.IR get ,
to lookup and display the route for a destination,
E 11
and
E 6
.IR monitor ,
D 11
to report any changes to the routing information base,
E 11
I 11
to continuously report any changes to the routing information base,
E 12
I 12
.Pp
D 15
Options supported by
E 15
I 15
The
E 15
.Nm route :
I 15
utility supports a limited number of general options,
but a rich command language, enabling the user to specify
any arbitrary request that could be delivered via the
programmatic interface discussed in 
.Xr route 4 .
E 15
.Pp
.Bl -tag -width Ds
.It Fl n
D 15
Prevent attempts to print host and network names symbolically
when reporting actions.
E 15
I 15
Bypasses attempts to print host and network names symbolically
when reporting actions.  (The process of translating between symbolic
names and numerical equivalents can be quite time consuming, and
may require correct operation of the network; thus it may be expedient
to forgo this, especially when attempting to repair networking operations),
E 15
.It Fl v
(verbose) Print additional details.
.It Fl q
Suppress all output.
.El
.Pp
D 15
Commands accepted by
E 15
I 15
The
E 15
.Nm route :
I 15
utility provides six commands:
E 15
.Pp
.Bl -tag -width Fl -compact
.It Cm add
Add a route.
.It Cm flush
Remove all routes.
.It Cm delete
Delete a specific route.
.It Cm change
Change aspects of a route (such as its gateway).
.It Cm get
Lookup and display the route for a destination.
.It Cm monitor
Continuously report any changes to the routing information base,
E 12
E 11
D 14
routing lookup misses, or suspected network partionings.
E 14
I 14
routing lookup misses, or suspected network partitionings.
E 14
E 5
E 3
D 12
.PP
E 12
I 12
.El
.Pp
E 12
D 5
All commands have the following syntax:
E 5
I 5
The monitor command has the syntax
D 12
.ti +0.25i
D 6
.B /etc/route 
E 6
I 6
.B route 
E 6
[
D 7
.I -n 
E 7
I 7
.B -n 
E 7
]
D 7
.I monitor
E 7
I 7
.B monitor
E 7
E 5
.PP
E 12
I 12
.Pp
.Bd -filled -offset indent -compact
.Nm route Op Fl n
.Cm monitor
.Ed
.Pp
E 12
I 7
The flush command has the syntax
D 12
.ti +0.25i
.B route
[
.B -n
]
[
.B -n
]
.B flush
[
.I family
]
.PP
where the address family may be specified by any of the
.BR -osi ,
.BR -xns ,
E 12
I 12
.Pp
.Bd -filled -offset indent -compact
.Nm route Op Fl n
.Cm flush
.Op Ar family
.Ed
.Pp
D 15
Where the address family may be specified by any of the
E 15
I 15
If the 
.Cm flush
command is specified, 
.Nm route
will ``flush'' the routing tables of all gateway entries.
When the address family may is specified by any of the
E 15
.Fl osi ,
.Fl xns ,
E 12
or
D 12
.B -inet
E 12
I 12
.Fl inet
E 12
D 15
keywords.
E 15
I 15
modifiers, only routes having destinations with addresses in the
delineated family will be deleted.
E 15
D 12
.PP
E 12
I 12
.Pp
E 12
E 7
I 5
The other commands have the following syntax:
D 12
.PP
E 5
D 3
.ti +0.5i
E 3
I 3
.ti +0.25i
E 3
D 6
.B /etc/route 
E 6
I 6
.B route 
E 6
I 5
[
D 6
.I -n -i -f -x -o
E 6
I 6
.I -n 
E 6
]
E 5
.I command
D 3
.B destination gateway
E 3
[
D 3
.B metric
E 3
I 3
D 6
.B net
E 6
I 6
.B -net
E 6
|
D 6
.B host
E 6
I 6
.B -host
E 6
E 3
]
I 3
.I destination gateway
D 7
[
D 5
.I metric
E 5
I 5
.I mask
E 5
]
E 7
E 3
.PP
E 12
I 12
.Pp
.Bd -filled -offset indent -compact
.Nm route Op Fl n
.Ar command
.Op Fl net No \&| Fl host
.Ar destination gateway
.Ed
.Pp
E 12
where
D 12
.I destination
E 12
I 12
.Ar destination
E 12
D 3
is a host or network for which
the route is ``to'',
E 3
I 3
is the destination host or network,
E 3
D 12
.I gateway
E 12
I 12
.Ar gateway
E 12
D 3
is the gateway to which packets should be addressed, and
E 3
I 3
D 5
is the next-hop gateway to which packets should be addressed, and
E 3
.I metric
D 3
is an optional count indicating the number of hops to
E 3
I 3
is a count indicating the number of hops to
E 3
the
.IR destination .
D 3
If no metric is specified, 
.I route
assumes a value of 0.
E 3
I 3
The metric is required for
.I add
commands; it must be zero if the destination is on a directly-attached network,
and nonzero if the route utilizes one or more gateways.
If adding a route with metric 0,
the gateway given is the address of this host on the common network,
indicating the interface to be used for transmission.
E 5
I 5
D 15
is the next-hop gateway to which packets should be addressed.
E 5
E 3
Routes to a particular host are distinguished from those to
a network by interpreting the Internet address associated with
D 12
.IR destination .
E 12
I 12
.Ar destination .
E 12
D 3
If the 
E 3
I 3
The optional keywords
E 15
I 15
is the next-hop intermediary via which packets should be routed.
Routes to a particular host may be distinguished from those to
a network by interpreting the Internet address specified as the
.Ar destination argument.
The optional modifiers
E 15
D 6
.B net
E 6
I 6
D 12
.B -net
E 12
I 12
.Fl net
E 12
E 6
and
D 6
.B host
E 6
I 6
D 12
.B -host
E 12
I 12
.Fl host
E 12
E 6
force the destination to be interpreted as a network or a host, respectively.
Otherwise, if the 
E 3
D 12
.I destination
D 3
has a ``local address part'' of INADDR_ANY, then the route is
E 3
I 3
has a ``local address part'' of INADDR_ANY,
E 12
I 12
.Ar destination
has a ``local address part'' of
INADDR_ANY ,
E 12
or if the
D 12
.I destination
E 12
I 12
.Ar destination
E 12
is the symbolic name of a network, then the route is
E 3
assumed to be to a network; otherwise, it is presumed to be a
D 5
route to a host.  If the route is to a destination connected
E 5
I 5
D 7
route to a host.  If the route is via an interface rather than
E 7
I 7
route to a host.
D 12
.PP
E 12
I 12
.Pp
E 12
For example,
D 12
128.32 is interpreted as
.I -host
128.0.0.32,
128.32.130 is interpreted as
.I -host
128.32.0.130;
.I -net 128.32
E 12
I 12
.Li 128.32
E 12
is interpreted as
D 12
128.32.0.0,
E 12
I 12
.Fl host Li 128.0.0.32 ;
.Li 128.32.130
is interpreted as
.Fl host Li 128.32.0.130 ;
.Fl net Li 128.32
is interpreted as
.Li 128.32.0.0;
E 12
and 
D 12
.I -net 128.32.130
E 12
I 12
.Fl net Li 128.32.130
E 12
is interpreted as
D 12
128.32.130.0.
.PP
E 12
I 12
.Li 128.32.130.0 .
.Pp
E 12
D 15
If the route is via an interface rather than
E 7
E 5
via a gateway, the 
E 15
I 15
If the destination is directly reachable
via an interface requiring
no intermediary system to act as a gateway, the 
E 15
D 5
.I metric
should be greater than 0.  All symbolic names specified for a
E 5
I 5
D 6
.I -i
flag should be specified;
E 6
I 6
D 12
.I -interface
E 12
I 12
.Fl interface
E 12
modifier should be specified;
E 6
the gateway given is the address of this host on the common network,
indicating the interface to be used for transmission.
D 12
.PP
E 12
I 12
.Pp
E 12
D 6
The optional flags
.I -x
E 6
I 6
The optional modifiers
D 12
.I -xns,
E 12
I 12
.Fl xns ,
I 15
.Fl osi ,
E 15
E 12
E 6
and
D 6
.I -o
specify that the addresses are in the XNS or OSI address families,
E 6
I 6
D 12
.I -osi
specify that all subsequent addresses are in the XNS or OSI address families,
E 12
I 12
D 15
.Fl osi
E 15
I 15
.Fl link 
E 15
specify that all subsequent addresses are in the
.Tn XNS
D 15
or
E 15
.Tn OSI
address families,
I 15
or are specified as link-level addresses,
E 15
E 12
E 6
and the names must be numeric specifications rather than
symbolic names.
D 6
For OSI addresses a third paramter is the address mask,
E 6
I 6
D 7
For OSI addresses a third parameter is the address mask,
E 6
as given in an ESIS redirect.
I 6
(preceded by the -netmask modifier)
E 7
I 7
D 8
To acheieve the effect of an OSI ESIS redirect with the netmask option,
one can specify
E 8
I 8
D 12
.PP
E 12
I 12
.Pp
E 12
The optional
E 8
D 12
.I -netmask
E 12
I 12
.Fl netmask
E 12
D 8
qualifier followed by an OSI address (to be interpreted as a network mask).
E 8
I 8
qualifier is intended
D 12
to acheieve the effect of an OSI ESIS redirect with the netmask option.
E 12
I 12
to achieve the effect of an
.Tn OSI
.Tn ESIS
D 15
redirect with the netmask option.
E 15
I 15
redirect with the netmask option,
or to manually add subnet routes with
netmasks different from that of the implied network interface
(as would otherwise be communicated using the OSPF or ISIS routing protocols).
E 15
E 12
One specifies an additional ensuing address parameter
(to be interpreted as a network mask).
E 8
D 12
One can override the implicit network mask generated in the inet case
by making sure this option follows the destination parameter.
E 7
E 6
.PP
E 12
I 12
D 15
The implicit network mask generated in the inet case
E 15
I 15
The implicit network mask generated in the AF_INET case
E 15
can be overridden by making sure this option follows the destination parameter.
.Pp
I 15
Routes have associated flags which influence operation of the protocols
when sending to destinations matched by the routes.
These flags may be set (or sometimes cleared)
by indicating the following corresponding modifiers:
.Bd -literal
-cloning   RTF_CLONING    - generates a new route on use
-xresolve  RTF_XRESOLVE   - emit mesg on use (for external lookup)
-iface    ~RTF_GATEWAY    - destination is directly reachable
-static    RTF_STATIC     - manually added route
-nostatic ~RTF_STATIC     - pretend route added by kernel or daemon
-reject    RTF_REJECT     - emit an ICMP unreachable when matched
-blackhole RTF_BLACKHOLE  - silently discard pkts (during updates)
-proto1    RTF_PROTO1     - set protocol specific routing flag #1
-proto2    RTF_PROTO2     - set protocol specific routing flag #2
-llinfo    RTF_LLINFO     - validly translates proto addr to link addr
.Ed
.Pp
E 15
E 12
I 7
The optional modifiers
D 12
.IR -rtt ,
.IR -rttvar ,
.IR -sendpipe ,
.IR -recvpipe ,
.IR -mtu ,
.IR -hopcount ,
.IR -expire ,
E 12
I 12
.Fl rtt ,
.Fl rttvar ,
.Fl sendpipe ,
.Fl recvpipe ,
.Fl mtu ,
.Fl hopcount ,
.Fl expire ,
E 12
and
D 12
.I -ssthresh 
E 12
I 12
.Fl ssthresh
E 12
D 15
provide initial values to metrics maintained in the routing entry.
E 15
I 15
provide initial values to quantities maintained in the routing entry
by transport level protocols, such as TCP or TP4.
E 15
These may be individually locked by preceding each such modifier to
be locked by
the
D 12
.I -lock
E 12
I 12
.Fl lock
E 12
meta-modifier, or one can 
specify that all ensuing metrics may be locked by the
D 12
.I -lockrest
E 12
I 12
.Fl lockrest
E 12
meta-modifier.
D 12
.PP
E 12
I 12
.Pp
E 12
I 11
In a
D 12
.IR change or
.I add
E 12
I 12
.Cm change
or
.Cm add
E 12
command where the destination and gateway are not sufficient to specify
D 12
the route (as in the ISO case where several interfaces may have the
E 12
I 12
the route (as in the
.Tn ISO
case where several interfaces may have the
E 12
same address), the
D 12
.IR -ifp or
.I -ifa
E 12
I 12
.Fl ifp
or
.Fl ifa
E 12
modifiers may be used to determine the interface or interface address.
D 12
.PP
E 12
I 12
.Pp
E 12
E 11
E 7
All symbolic names specified for a
E 5
D 12
.I destination 
E 12
I 12
.Ar destination
E 12
or 
D 12
.I gateway
E 12
I 12
.Ar gateway
E 12
D 3
are looked up first in the host name database,
.IR hosts (5).
If this lookup fails, the name is then looked for
in the network name database,
.IR networks (5).
E 3
I 3
are looked up first as a host name using
D 12
.IR gethostbyname (3N).
E 12
I 12
.Xr gethostbyname 3 .
E 12
If this lookup fails,
D 12
.IR getnetbyname (3N)
E 12
I 12
.Xr getnetbyname 3
E 12
is then used to interpret the name as that of a network.
E 3
D 12
.PP
.I Route
E 12
I 12
.Pp
.Nm Route
E 12
D 5
uses a raw socket and the SIOCADDRT and SIOCDELRT
.IR ioctl 's
to do its work.  As such, only the super-user may modify
E 5
I 5
uses a routing socket and the new message types
D 7
RTM_ADD and RTM_DELETE.
E 7
I 7
D 11
RTM_ADD, RTM_DELETE, and RTM_CHANGE.
E 11
I 11
D 12
RTM_ADD, RTM_DELETE, RTM_GET, and RTM_CHANGE.
E 12
I 12
RTM_ADD,
RTM_DELETE,
RTM_GET,
and
RTM_CHANGE.
E 12
E 11
E 7
As such, only the super-user may modify
E 5
the routing tables.
I 16
.ne 1i
E 16
D 12
.PP
E 12
I 12
D 15
.Pp
E 12
If the 
D 6
.B \-f
option is specified, 
E 6
I 6
D 12
.B flush
E 12
I 12
.Cm flush
E 12
command is specified, 
E 6
D 12
.I route
E 12
I 12
.Nm route
E 12
will ``flush'' the routing tables of all gateway entries.
D 8
If this is used in conjunction with one of the commands
described above, the tables are flushed prior to the command's
application.
E 8
I 8
One can choose to flush only those routes whose destinations
are of a given address family, by specifying an optional keyword
describing which address family.
E 15
E 8
I 3
D 12
.PP
The
.B \-n
option prevents attempts to print host and network names symbolically
when reporting actions.
I 7
The
.B \-v
option causes additional details to be printed.
The
.B \-q
option supresses all output.
E 7
E 3
.SH DIAGNOSTICS
D 3
.B ``add %s: gateway %s flags %x''
E 3
I 3
``\fBadd [ host | network ] %s: gateway %s flags %x\fP''
E 3
.br
E 12
I 12
.Sh DIAGNOSTICS
.Bl -tag -width Ds
.It Sy "add [host \&| network ] %s: gateway %s flags %x"
E 12
The specified route is being added to the tables.  The
values printed are from the routing table entry supplied
in the 
D 12
.I ioctl
E 12
I 12
.Xr ioctl 2
E 12
call.
I 3
If the gateway address used was not the primary address of the gateway
(the first one returned by
D 12
.IR gethostbyname ),
E 12
I 12
.Xr gethostbyname 3 ) ,
E 12
the gateway address is printed numerically as well as symbolically.
E 3
D 12
.PP
D 3
.B ``delete %s: gateway %s flags %x''
E 3
I 3
``\fBdelete [ host | network ] %s: gateway %s flags %x\fP''
E 3
.br
E 12
I 12
.It Sy "delete [ host &| network ] %s: gateway %s flags %x" 
E 12
As above, but when deleting an entry.
D 12
.PP
D 3
.B ``%s %s done''
E 3
I 3
``\fB%s %s done\fP''
E 3
.br
E 12
I 12
.It Sy "%s %s done"
E 12
When the 
D 11
.B \-f
flag is specified, each routing table entry deleted
E 11
I 11
D 12
.B flush
E 12
I 12
.Cm flush
E 12
command is specified, each routing table entry deleted
E 11
is indicated with a message of this form.
D 12
.PP
D 3
.B  ``not in table''
E 3
I 3
``\fBNetwork is unreachable\fP''
E 3
.br
E 12
I 12
.It Sy "Network is unreachable"
E 12
I 3
An attempt to add a route failed because the gateway listed was not
on a directly-connected network.
The next-hop gateway must be given.
D 12
.PP
``\fBnot in table\fP''
.br
E 12
I 12
.It Sy "not in table"
E 12
E 3
A delete operation was attempted for an entry which
wasn't present in the tables.
D 12
.PP
D 3
.B ``routing table overflow''
E 3
I 3
``\fBrouting table overflow\fP''
E 3
.br
E 12
I 12
.It Sy "routing table overflow"
E 12
An add operation was attempted, but the system was
low on resources and was unable to allocate memory
to create the new entry.
D 12
.SH "SEE ALSO"
D 4
intro(4N),
D 3
routed(8C)
.SH BUGS
The change operation is not implemented, one should add
the new route, then delete the old one.
E 3
I 3
routed(8C),
XNSrouted(8C)
E 4
I 4
D 10
netintro(4), routed(8), XNSrouted(8)
E 10
I 10
netintro(4), route(4), esis(4), routed(8), XNSrouted(8)
E 12
I 12
.El
.Sh SEE ALSO
.Xr netintro 4 ,
.Xr route 4 ,
.Xr esis 4 ,
.Xr routed 8 ,
.Xr XNSrouted 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
.Sh BUGS
The first paragraph may have slightly exaggerated
.Xr routed Ns 's
abilities.
E 12
E 10
E 4
E 3
E 1
