(File |demo/tower.l|)
(otherpeg lambda quote copy delete car)
(do-or lambda car interpret return do bigp not cdr null and zerop cond)
(do-and lambda car interpret cdr return cond null do)
(interpret lambda nreverse setq null liszt-internal-do mapcar toh do-or do-and apply eq cdr cons interpret car dtpr atom cond)
(toh-applyrule lambda rhs bind-to interpret nreverse cdr atom cond car cons setq null quote *rdata liszt-internal-do mapcar findicators1 *rdata-only *rvalues-only inspect-datum *rvalue-only lhs match let)
(toh lambda list quote changedomain)
(move lambda fput-datum fput fremove-facet fremove freplace-datum freplace terpr list patom nreverse cdr atom cond car cons setq null quote fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only inspect-datum fvalue-only let)
