h20135
s 00002/00002/00042
d D 8.1 93/06/04 12:44:16 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00006/00027/00038
d D 5.5 91/10/27 11:30:29 bostic 5 4
c list the specific ASCII characters handled by the isXXX() functions
e
s 00003/00017/00062
d D 5.4 91/10/23 17:00:18 bostic 4 3
c add isblank(3); call things functions consistently, don't list the
c rest of the world in the SEE ALSO section
e
s 00002/00001/00077
d D 5.3 91/07/31 19:56:23 cael 3 2
c reposition display
e
s 00004/00000/00074
d D 5.2 91/06/29 14:31:44 bostic 2 1
c add ANSI contribution notice
e
s 00074/00000/00000
d D 5.1 91/05/02 04:12:57 cael 1 0
c date and time created 91/05/02 04:12:57 by cael
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
I 2
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
E 2
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt ISSPACE 3
.Os
.Sh NAME
.Nm isspace
.Nd white-space character test
.Sh SYNOPSIS
.Fd #include <ctype.h>
.Ft int
D 4
.Fn isspace "int c"
E 4
I 4
.Fn isspace "int c";
E 4
.Sh DESCRIPTION
The
.Fn isspace
D 5
function tests for the standard white-space characters
.\" or for any
.\" of an implementation-defined set of characters
for which
.Xr isalnum 3
is false.
The standard white-space characters are the following:
D 3
.Bl -tag -width xxxxx -offset indent
E 3
I 3
.Pp
.Bl -tag -width xxxxx -offset indent -compact
E 3
.It Sq \0
Space character.
.It Li \ef
Form feed.
.It Li \en
New-line.
.It Li \er
Carriage return.
.It Li \et
Horizontal tab.
.It Li \ev
And vertical tab.
E 5
I 5
function tests for the standard white-space characters.
In the ASCII character set, this includes the following characters:
.sp
.Bl -column \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__
.It \&011\ ht \t012\ nl \t013\ vt \t014\ np \t015\ cr
.It \&040\ sp
E 5
.El
D 5
.Pp
In the 
.Em ``C''
locale,
.Fn isspace
returns true only for the standard white-space characters.
E 5
.Sh RETURN VALUES
The
.Fn isspace
D 4
macro returns zero if the character tests false and
E 4
I 4
function returns zero if the character tests false and
E 4
returns non-zero if the character tests true.
.Sh SEE ALSO
D 4
.Xr isascii 3 ,
.Xr isalnum 3 ,
.Xr isalpha 3 ,
.Xr iscntrl 3 ,
.Xr isdigit 3 ,
.Xr isgraph 3 ,
.Xr islower 3 ,
.Xr isprint 3 ,
.Xr ispunct 3 ,
.Xr isupper 3 ,
.Xr isxdigit 3 ,
.Xr toascii 3 ,
.Xr tolower 3 ,
.Xr toupper 3 ,
.Xr stdio 3
E 4
I 4
.Xr ctype 3 ,
E 4
.Xr ascii 7
.Sh STANDARDS
The
.Fn isspace
function conforms to
.St -ansiC .
E 1
