h00841
s 00001/00001/00060
d D 8.2 93/12/11 22:37:50 mckusick 6 5
c copyediting for Usenix manuals
e
s 00002/00002/00059
d D 8.1 93/06/04 12:44:02 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00024/00001/00037
d D 5.4 91/10/27 11:30:25 bostic 4 3
c list the specific ASCII characters handled by the isXXX() functions
e
s 00003/00017/00035
d D 5.3 91/10/23 17:00:13 bostic 3 2
c add isblank(3); call things functions consistently, don't list the
c rest of the world in the SEE ALSO section
e
s 00004/00000/00048
d D 5.2 91/06/29 14:31:10 bostic 2 1
c add ANSI contribution notice
e
s 00048/00000/00000
d D 5.1 91/05/02 04:12:55 cael 1 0
c date and time created 91/05/02 04:12:55 by cael
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
I 2
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
E 2
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt ISGRAPH 3
.Os
.Sh NAME
.Nm isgraph
D 6
.Nd printing character test (space character exculsive)
E 6
I 6
.Nd printing character test (space character exclusive)
E 6
.Sh SYNOPSIS
.Fd #include <ctype.h>
.Ft int
D 3
.Fn isgraph "int c"
E 3
I 3
.Fn isgraph "int c";
E 3
.Sh DESCRIPTION
The
.Fn isgraph
D 4
function tests for any printing character except space (' ').
E 4
I 4
function tests for any printing character except space.
In the ASCII character set, this includes the following characters:
.sp
.Bl -column \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__
.It \&041\ ``!'' \t042\ ``"'' \t043\ ``#'' \t044\ ``$'' \t045\ ``%''
.It \&046\ ``&'' \t047\ ``''' \t050\ ``('' \t051\ ``)'' \t052\ ``*''
.It \&053\ ``+'' \t054\ ``,'' \t055\ ``-'' \t056\ ``.'' \t057\ ``/''
.It \&060\ ``0'' \t061\ ``1'' \t062\ ``2'' \t063\ ``3'' \t064\ ``4''
.It \&065\ ``5'' \t066\ ``6'' \t067\ ``7'' \t070\ ``8'' \t071\ ``9''
.It \&072\ ``:'' \t073\ ``;'' \t074\ ``<'' \t075\ ``='' \t076\ ``>''
.It \&077\ ``?'' \t100\ ``@'' \t101\ ``A'' \t102\ ``B'' \t103\ ``C''
.It \&104\ ``D'' \t105\ ``E'' \t106\ ``F'' \t107\ ``G'' \t110\ ``H''
.It \&111\ ``I'' \t112\ ``J'' \t113\ ``K'' \t114\ ``L'' \t115\ ``M''
.It \&116\ ``N'' \t117\ ``O'' \t120\ ``P'' \t121\ ``Q'' \t122\ ``R''
.It \&123\ ``S'' \t124\ ``T'' \t125\ ``U'' \t126\ ``V'' \t127\ ``W''
.It \&130\ ``X'' \t131\ ``Y'' \t132\ ``Z'' \t133\ ``['' \t134\ ``\''
.It \&135\ ``]'' \t136\ ``^'' \t137\ ``_'' \t140\ ```'' \t141\ ``a''
.It \&142\ ``b'' \t143\ ``c'' \t144\ ``d'' \t145\ ``e'' \t146\ ``f''
.It \&147\ ``g'' \t150\ ``h'' \t151\ ``i'' \t152\ ``j'' \t153\ ``k''
.It \&154\ ``l'' \t155\ ``m'' \t156\ ``n'' \t157\ ``o'' \t160\ ``p''
.It \&161\ ``q'' \t162\ ``r'' \t163\ ``s'' \t164\ ``t'' \t165\ ``u''
.It \&166\ ``v'' \t167\ ``w'' \t170\ ``x'' \t171\ ``y'' \t172\ ``z''
.It \&173\ ``{'' \t174\ ``|'' \t175\ ``}'' \t176\ ``~''
.El
E 4
.Sh RETURN VALUES
The
.Fn isgraph
D 3
macro returns zero if the character tests false and
E 3
I 3
function returns zero if the character tests false and
E 3
returns non-zero if the character tests true.
.Sh SEE ALSO
D 3
.Xr isascii 3 ,
.Xr isalnum 3 ,
.Xr isalpha 3 ,
.Xr iscntrl 3 ,
.Xr isdigit 3 ,
.Xr islower 3 ,
.Xr isprint 3 ,
.Xr ispunct 3 ,
.Xr isspace 3 ,
.Xr isupper 3 ,
.Xr isxdigit 3 ,
.Xr toascii 3 ,
.Xr tolower 3 ,
.Xr toupper 3 ,
.Xr stdio 3
E 3
I 3
.Xr ctype 3 ,
E 3
.Xr ascii 7
.Sh STANDARDS
The
.Fn isgraph
function conforms to
.St -ansiC .
E 1
