h11005
s 00002/00002/00060
d D 8.1 93/06/04 12:44:46 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00005/00002/00057
d D 5.2 91/06/29 14:44:57 bostic 2 1
c add ANSI contribution notice
e
s 00059/00000/00000
d D 5.1 91/05/02 04:13:00 cael 1 0
c date and time created 91/05/02 04:13:00 by cael
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1989, 1991 The Regents of the University of California.
.\" All rights reserved.
E 3
I 3
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 3
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
E 2
.\" %sccs.include.redist.man%
.\"
D 2
.\"     %W% (Berkeley) %G%
E 2
I 2
.\"	%W% (Berkeley) %G%
E 2
.\"
.Dd %Q%
.Dt TOUPPER 3
.Os
.Sh NAME
.Nm toupper
.Nd lower case to upper case letter conversion
.Sh SYNOPSIS
.Fd #include <ctype.h>
.Ft int
.Fn toupper "int c"
.Sh DESCRIPTION
The
.Fn toupper
function converts a lower-case letter to the corresponding 
upper-case letter.
.SH RETURN VALUES
If the argument is a lower-case letter, the
.Fn toupper
function returns the corresponding upper-case letter if there is
one; otherwise the argument is returned unchanged.
.\" In the 
.\" .Em ``C''
.\" locale,
.\" .Fn toupper
.\" maps only the characters for which
.\" .Xr islower
.\" is true to the corresponding characters for which
.\" .Xr isupper
.\" is true.	
.Sh SEE ALSO
.Xr isascii 3 ,
.Xr isalnum 3 ,
.Xr isalpha 3 ,
.Xr iscntrl 3 ,
.Xr isdigit 3 ,
.Xr isgraph 3 ,
.Xr islower 3 ,
.Xr isprint 3 ,
.Xr ispunct 3 ,
.Xr isspace 3 ,
.Xr isupper 3 ,
.Xr isxdigit 3 ,
.Xr toascii 3 ,
.Xr toupper 3 ,
.Xr stdio 3
.Xr ascii 7
.Sh STANDARDS
The
.Fn tolower
function conforms to
.St -ansiC .
E 1
