h10583
s 00002/00002/00048
d D 8.1 93/06/06 14:50:07 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00009/00011/00041
d D 5.7 91/07/22 13:40:59 cael 8 7
c version three mdoc
e
s 00003/00001/00049
d D 5.6 91/03/14 00:19:09 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00050
d R 5.6 91/03/13 20:33:59 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00005/00002/00045
d D 5.5 90/11/21 13:12:01 bostic 5 4
c we don't support -P or -p anymore, either
e
s 00018/00011/00029
d D 5.4 90/09/06 19:24:45 bostic 4 3
c add the +offset syntax for od(1) compatibility
e
s 00004/00004/00036
d D 5.3 90/07/24 22:49:46 cael 3 2
c .Xr botch fix
e
s 00027/00017/00013
d D 5.2 90/06/24 19:14:06 cael 2 1
c converted man page
e
s 00032/00000/00000
d D 5.1 90/05/08 08:55:44 bostic 1 0
c date and time created 90/05/08 08:55:44 by bostic
e
u
U
t
T
I 1
D 9
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
D 8
.\"     %W% (Berkeley) %G%
E 8
I 8
.\"	%W% (Berkeley) %G%
E 8
E 2
.\"
I 7
D 8
.Vx
.Vx
E 8
E 7
D 2
.TH OD 1 "%Q%"
.UC 7
E 2
I 2
.Dd %Q
D 7
.Os BSD 4.4
E 7
I 7
.Os
E 7
.Dt OD 1
E 2
D 3
.SH NAME
E 3
I 3
.Sh NAME
E 3
D 2
od \- octal, decimal, hex, ascii dump
.SH SYNOPSIS
od [ \-aBbcDdeFfHhIiLlOoPpvXx ] [ file ]
.SH DESCRIPTION
.I Od
E 2
I 2
.Nm od
.Nd octal, decimal, hex, ascii dump
.Sh SYNOPSIS
.Nm od
D 5
.Op Fl aBbcDdeFfHhIiLlOoPpvXx
E 5
I 5
.Op Fl aBbcDdeFfHhIiLlOovXx
E 5
I 4
D 8
.Cx [
.Op Sy \&+
E 8
I 8
.Sm off
.Oo
.Op Cm \&+
E 8
.Li offset
D 8
.Op Sy \&.
.Op Sy Bb
.Cx ]
.Cx
E 8
I 8
.Op Cm \&.
.Op Cm Bb
.Oc
E 8
E 4
.Ar file
.Sh DESCRIPTION
.Nm Od
E 2
has been deprecated in favor of
D 2
.IR hexdump (1).
.PP
.IR Hexdump ,
E 2
I 2
.Xr hexdump 1 .
.Pp
D 4
.Xr Hexdump 1 ,
E 4
I 4
.Xr Hexdump ,
E 4
E 2
if called as
D 2
.IR od ,
E 2
I 2
.Nm od ,
E 2
provides compatibility for the options listed above.
D 2
.PP
E 2
I 2
.Pp
E 2
D 4
It does not provide compatibility for the options ``-s'' and ``-w'',
nor is compatibility provided for the extended argument syntax of
D 2
``[ [\fB+\fP]offset[\fB.\fP][\fBb\fP] [label] ]''.
.SH SEE ALSO
hexdump(1)
.SH BUGS
E 2
I 2
D 3
``[
.Cx Op Sy \&+
E 3
I 3
.Cx ``[
.Op Sy \&+
E 3
.Li offset
.Op Sy \&.
.Op Sy b
D 3
.Cx [label] ]''.
E 3
I 3
.Cx [label]]''.
E 3
.Cx
E 4
I 4
It does not provide compatibility for the
.Fl s
option (see
D 8
.Xr strings 1)
E 8
I 8
.Xr strings 1 )
E 8
or the
I 5
.Fl P ,
.Fl p ,
or
E 5
.Fl w
D 5
option, nor is compatibility provided for the ``label'' component
E 5
I 5
options, nor is compatibility provided for the ``label'' component
E 5
of the offset syntax.
E 4
.Sh SEE ALSO
D 4
.Xr hexdump 1
E 4
I 4
.Xr hexdump 1 ,
.Xr strings 1
E 4
.Sh BUGS
E 2
Quite a few.
E 1
