h21618
s 00002/00002/00059
d D 8.1 93/06/06 16:03:49 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00013/00010/00048
d D 6.7 91/05/09 17:05:19 cael 10 9
c mdoc version three/deleted references to 4.4
e
s 00002/00000/00056
d D 6.6 91/03/14 00:15:47 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00056
d R 6.6 91/03/13 20:32:25 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00026/00034/00030
d D 6.5 91/01/18 18:45:03 bostic 7 6
c new version
e
s 00029/00027/00035
d D 6.4 90/07/24 22:50:33 cael 6 5
c .Xr botch fix
e
s 00045/00034/00017
d D 6.3 90/06/26 01:00:58 cael 5 4
c converted man page
e
s 00019/00003/00032
d D 6.2 85/05/03 20:32:48 mckusick 4 3
c add -t option (arnold@ucsfcgl)
e
s 00001/00001/00034
d D 6.1 85/04/29 17:52:24 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00016/00021/00019
d D 5.1 85/04/29 17:52:13 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00040/00000/00000
d D 4.1 85/04/29 17:52:05 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
D 11
.\" Copyright (c) 1990 Regents of the University of California.
D 6
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 6
I 6
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 6
E 5
.\"
I 6
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
.\"
E 6
D 2
.TH RANLIB 1
E 2
I 2
D 3
.TH RANLIB 1 "8 February 1983"
E 3
I 3
D 5
.TH RANLIB 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
ranlib \- convert archives to random libraries
.SH SYNOPSIS
.B ranlib
D 4
archive ...
E 4
I 4
[
.B \-t
] archive ...
E 4
.SH DESCRIPTION
.I Ranlib
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
I 9
D 10
.Vx
.Vx
E 10
E 9
I 6
.Dd %Q%
E 6
.Dt RANLIB 1
D 6
.Os ATT 7th
E 6
I 6
D 10
.BSD 4.4
E 10
I 10
.Os
E 10
E 6
.Sh NAME
.Nm ranlib
D 6
.Nd convert archives to random libraries
E 6
I 6
D 7
.Nd preprocess archives for efficient linking
E 7
I 7
.Nd table-of-contents for archive libraries
E 7
E 6
.Sh SYNOPSIS
.Nm ranlib
.Op Fl t
D 6
.Ar archive ...
E 6
I 6
D 7
.Ar archive_file ...
E 7
I 7
.Ar file ...
E 7
E 6
.Sh DESCRIPTION
.Nm Ranlib
E 5
D 6
converts each
D 5
.I archive
E 5
I 5
.Ar archive
E 5
D 2
to a form which can be loaded
more rapidly by the loader,
by adding a table of contents named
.B _\^_.SYMDEF
E 2
I 2
to a form which the loader can load more rapidly.
E 6
I 6
D 7
is a preprocessor for the loading utility
E 7
I 7
creates a table of external references for archive libraries,
normally used by the loader,
E 7
.Xr ld 1 .
E 6
D 5
.I Ranlib
does this by adding a table of contents called 
D 4
.B _.SYMDEF
E 4
I 4
.B __.SYMDEF
E 5
I 5
D 7
.Nm Ranlib
D 6
does this by adding a table of contents called
E 6
I 6
creates a randomized library from the given
.Ar archive_file
with
the file entry named
E 6
.Sy \&__.SYMDEF
E 5
E 4
E 2
D 6
to the beginning of the archive.
D 2
It uses
E 2
I 2
D 5
.I Ranlib
uses 
E 2
.IR ar (1)
E 5
I 5
.Nm Ranlib
uses
.Xr ar  1
E 5
D 2
to reconstruct the archive,
so that sufficient temporary file space must
be available in the file system containing the
current directory.
.SH SEE ALSO
E 2
I 2
to reconstruct the archive, so that sufficient temporary file space must
be available in the file system which contains the current directory.
I 4
D 5
.PP
If given the
.B \-t
option,
ranlib only "touches" the archives and does not modify them.
E 5
I 5
.Pp
E 6
I 6
prepended.
The
.Sy \&__.SYMDEF
file entry is a dictionary the loader can detect and interpret
to resolve external references at link time.
To generate the library, the
.Xr ar 1
utility is used.
E 7
I 7
This table is is named ``__.SYMDEF'' and is prepended to the archive.
Files in the archive which are not executable and symbols which are
uninteresting to the loader are ignored.
.Pp
The options are as follows:
E 7
D 10
.Tw 8n
E 6
.Tp Fl t
E 10
I 10
.Bl -tag -width indent
.It Fl t
E 10
D 7
Ranlib only "touches" the archives and does not modify them.
E 5
This is useful after copying an archive
or using the
E 7
I 7
Set the modification time of the __.SYMDEF file.
This time is compared by the loader with the modification time of the
archive to verify that the table is up-to-date with respect to the
archive.
If the modification time has been changed without any change to the
archive (for example, by a
.Xr cp 1 ) ,
the
E 7
D 5
.B \-t
E 5
I 5
.Fl t
I 7
option can be used to ``touch'' the modification time so that it
appears that the table is up-to-date.
This is also useful after using the
.Fl t
E 7
E 5
option of
D 5
.IR make (1)
E 5
I 5
D 7
.Xr make  1
E 5
in order to avoid having
D 5
.IR ld (1)
E 5
I 5
.Xr ld  1
E 5
complain about
D 5
an \*(lqout of date\*(rq symbol table.
E 4
.SH "SEE ALSO"
E 2
D 4
ld(1), ar(1), lorder(1)
E 4
I 4
ld(1), ar(1), lorder(1), make(1)
E 4
.SH BUGS
E 5
I 5
an
.Dq out of date
symbol table.
E 7
I 7
.Xr make 1 .
E 7
D 10
.Tp
E 10
I 10
.El
E 10
I 7
.Sh FILES
D 10
/tmp/ranlib.XXXXXX	temporary file names
E 10
I 10
.Bl -tag -width /tmp/ranlib.XXXXXX -compact
.It Pa /tmp/ranlib.XXXXXX
Temporary file names.
.El
E 10
E 7
.Sh SEE ALSO
D 6
.Xr ld 1 ,
E 6
.Xr ar 1 ,
I 6
.Xr ld 1 ,
E 6
.Xr lorder 1 ,
D 6
.Xr make 1
E 6
I 6
D 7
.Xr make 1 ,
.Xr nm 1
E 7
I 7
.Xr nm 1 ,
.Xr ranlib 5
E 7
E 6
.Sh HISTORY
D 10
.Nm Ranlib
appeared in Version 7 AT&T UNIX.
E 10
I 10
A
.Nm ranlib
command appeared in
.At v7 .
E 10
D 7
.Sh BUGS
E 5
D 6
Because generation of a library by
D 5
.I ar
E 5
I 5
.Xr ar
E 5
D 2
and randomization by
E 2
I 2
and randomization of the library by
E 2
D 5
.I ranlib
E 5
I 5
.Nm ranlib
E 5
D 2
are separate,
phase errors are possible.
The loader
.I ld
warns when the modification date of
a library is more recent than
the creation of its dictionary;
but this means you get the warning even if you
only copy the library.
E 2
I 2
are separate processes, phase errors are possible.  The loader,
D 5
.IR ld ,
E 5
I 5
.Xr ld  ,
E 5
warns when the modification date of a library is more recent than the
creation date of its dictionary;  but this means that you get the
warning even if you only copy the library.
E 6
I 6
The archiving is a separate process and phase
errors may occur (see the
.Fl t
option above).
E 7
E 6
E 2
E 1
