h24518
s 00001/00002/00103
d D 8.4 95/05/01 21:50:53 mckusick 11 10
c mount_lofs is gone
e
s 00013/00000/00092
d D 8.3 94/03/27 11:52:23 bostic 10 9
c add in -o option
e
s 00006/00003/00086
d D 8.2 94/03/27 11:50:08 bostic 9 8
c Jan-Simon Pendry's and my new mount code
e
s 00002/00002/00087
d D 8.1 93/06/09 19:08:15 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00003/00087
d D 5.6 93/06/09 19:08:12 bostic 7 5
c fixed the under development line
e
s 00002/00002/00088
d R 8.1 93/06/05 11:04:41 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00031/00087
d D 5.5 93/02/24 16:19:31 bostic 5 4
c fix headers
e
s 00000/00001/00118
d D 5.4 93/02/24 16:18:54 bostic 4 3
c prettiness police
e
s 00025/00011/00094
d D 5.3 92/07/11 15:27:37 heideman 3 2
c Minor formatting changes
e
s 00032/00025/00073
d D 5.2 92/07/11 14:48:31 heideman 2 1
c Converted from null layer to umap layer
e
s 00098/00000/00000
d D 5.1 92/07/10 16:29:26 heideman 1 0
c date and time created 92/07/10 16:29:26 by heideman
e
u
U
t
T
I 1
D 5
.\"
E 5
D 8
.\" Copyright (c) 1992 The Regents of the University of California
.\" Copyright (c) 1990, 1992 Jan-Simon Pendry
E 8
I 8
D 9
.\" Copyright (c) 1992, 1993
E 9
I 9
.\" Copyright (c) 1992, 1993, 1994
E 9
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\" All rights reserved.
.\"
.\" This code is derived from software donated to Berkeley by
.\" Jan-Simon Pendry and from John Heidemann of the UCLA Ficus project.
.\"
D 4
.\"
E 4
D 2
.\" %sccs.include.redist.roff%
E 2
I 2
D 5
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
E 5
I 5
.\" %sccs.include.redist.roff%
E 5
E 2
.\"
D 2
.\"     %W% (Berkeley) %G%
E 2
I 2
D 5
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
E 5
I 5
.\"	%W% (Berkeley) %G%
E 5
E 2
.\"
I 2
D 5
.\"     @(#)mount_umap.8	1.1 (Berkeley) 7/10/92
E 2
.\"
D 2
.Dd %Q%
E 2
I 2
.\"
.Dd July 10, 1992
E 5
I 5
.Dd "%Q%"
E 5
E 2
.Dt MOUNT_UMAP 8
.Os BSD 4.4
.Sh NAME
.Nm mount_umap
.Nd sample file system layer
.Sh SYNOPSIS
.Nm mount_umap
I 10
.Op Fl o Ar options
E 10
D 9
.Op Fl F Ar fsoptions
.Ar target mount-point uid-mapfile gid-mapfile
E 9
I 9
.Ar target
.Ar mount-point
.Ar uid-mapfile
.Ar gid-mapfile
E 9
.Sh DESCRIPTION
The
.Nm mount_umap
command is used to mount a sub-tree of an existing file system
that uses a different set of uids and gids than the local system.
Such a file system could be mounted from a remote site via NFS or
it could be a file system on removable media brought from some
D 3
foreign location that uses a different password file and yellow pages.
E 3
I 3
foreign location that uses a different password file.
I 10
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
.El
.Pp
E 10
E 3
The
.Nm mount_umap
command uses a set of files provided by the user to make correspondences
between uids and gids in the sub-tree's original environment and
some other set of ids in the local environment.  For instance, user
smith might have uid 1000 in the original environment, while having
uid 2000 in the local environment.  The
.Nm mount_umap
command allows the subtree from smith's original environment to be
mapped in such a way that all files with owning uid 1000 look like
they are actually owned by uid 2000.  
.Pp
D 3
The target should be the current location of the sub-tree in the
local system's name space.  The mount-point should be a directory
where the mapped subtree is to be placed.  The uid-mapfile and
gid-mapfile describe the mappings to be made between identifiers.
E 3
I 3
.Em target 
should be the current location of the sub-tree in the
local system's name space.  
.Em mount-point 
should be a directory
where the mapped subtree is to be placed.  
.Em uid-mapfile 
and
.Em gid-mapfile 
describe the mappings to be made between identifiers.
E 3
Briefly, the format of these files is a count of the number of
mappings on the first line, with each subsequent line containing
a single mapping.  Each of these mappings consists of an id from
the original environment and the corresponding id in the local environment,
D 3
separated by white space.  The uid-mapfile should contain all uid
mappings, and the gid-mapfile should contain all gid mappings.
Any uids not mapped in the uid-mapfile will be treated as user NOBODY,
and any gids not mapped in the gid-mapfile will be treated as group
E 3
I 3
separated by white space.  
.Em uid-mapfile 
should contain all uid
mappings, and 
.Em gid-mapfile 
should contain all gid mappings.
Any uids not mapped in 
.Em uid-mapfile 
will be treated as user NOBODY,
and any gids not mapped in 
.Em gid-mapfile 
will be treated as group
E 3
NULLGROUP.  At most 64 uids can be mapped for a given subtree, and
at most 16 groups can be mapped by a given subtree.
.Pp
The mapfiles can be located anywhere in the file hierarchy, but they
must be owned by root, and they must be writable only by root.  
.Nm mount_umap
will refuse to map the sub-tree if the ownership or permissions on
these files are improper.  It will also balk if the count of mappings
in the first line of the map files is not correct.
.Pp
The layer created by the
.Nm mount_umap
command is meant to serve as a simple example of file system layering.
It is not meant for production use.  The implementation is not very
D 3
sophisticated, and not particularly fast.
E 3
I 3
sophisticated.
E 3
D 2

This command makes use of the layered file system, described
command makes a sub-tree of an existing filesystem visible
in another part of the global filesystem namespace,
while also performing mappings of uids and gids.  
This allows existing files and directories to be accessed
using a different pathname.
.Pp
Virtual file system sub-trees created by the null layer should
be identical to those created by the loopback
The virtual copy of a file system sub-tree created by the null
layer should be nearly identical to one created by
.Xr mount_lofs 8 .
The purpose of the null layer is to serve as a basis for future
layer development.
.Pp
An example of a layer constructed from the null layer is
the umap layer (see
.Xr mount_umap 8 ).
E 2
.Sh SEE ALSO
I 9
.Xr mount 8 ,
E 9
D 2
UCLA Technical Report CSD-910056,
"Stackable Layers: an Architecture for File System Development".
E 2
I 2
D 3
.Xr mount_null 8
E 3
I 3
D 11
.Xr mount_null 8 ,
E 3
.Xr mount_lofs 8
E 11
I 11
.Xr mount_null 8
E 11
E 2
.Sh HISTORY
The
D 2
null file system layer
E 2
I 2
D 7
umap file system layer
E 2
is
.Ud
E 7
I 7
.Nm mount_umap
utility first appeared in 4.4BSD.
E 7
E 1
