h00412
s 00002/00002/00043
d D 8.1 93/06/04 15:10:08 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00031/00023/00014
d D 5.3 91/04/19 14:46:08 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00037
d D 5.2 91/04/19 14:41:15 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00032/00000/00000
d D 5.1 90/05/15 13:54:06 bostic 1 0
c date and time created 90/05/15 13:54:06 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 4
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek.
.\"
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH BCOPY 3 "%Q%"
.UC 7
.SH NAME
bcopy \- copy byte string
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

void
bcopy(const char *src, char *dst, size_t len);
.ft R
.fi
.SH DESCRIPTION
.B Bcopy
E 3
I 3
.Dd %Q%
.Dt BCOPY 3
.Os BSD 4.2
.Sh NAME
.Nm bcopy
.Nd copy byte string
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft void
.Fn bcopy "const void *src" "void *dst" "size_t len"
.Sh DESCRIPTION
The
.Fn bcopy
function
E 3
copies
D 3
.I len
E 3
I 3
.Fa len
E 3
bytes from string
D 3
.I src
E 3
I 3
.Fa src
E 3
to string
D 3
.IR dst .
E 3
I 3
.Fa dst .
E 3
The two strings may overlap.
If
D 3
.I len
E 3
I 3
.Fa len
E 3
is zero, no bytes are copied.
D 3
.SH SEE ALSO
memccpy(3), memcpy(3), memmove(3), strcpy(3), strncpy(3)
E 3
I 3
.Sh SEE ALSO
.Xr memccpy 3 ,
.Xr memcpy 3 ,
.Xr memmove 3 ,
.Xr strcpy 3 ,
.Xr strncpy 3
.Sh HISTORY
A
.Fn bcopy
function appeared in 
.Bx 4.2 .
E 3
E 1
