h64885
s 00001/00002/00034
d D 8.2 94/04/19 07:05:50 bostic 5 4
c spell
e
s 00002/00002/00034
d D 8.1 93/06/04 15:10:21 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00024/00021/00012
d D 5.3 91/04/19 14:45:49 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00033
d D 5.2 91/04/19 14:41:03 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00025/00000/00000
d D 5.1 90/05/15 13:56:06 bostic 1 0
c date and time created 90/05/15 13:56:06 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 4
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek.
D 3
.\"
E 3
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH FFS 3  "%Q%"
.UC 7
.SH NAME
ffs \- find first bit set in a bit string
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

int
ffs(int value);
.ft R
.fi
.SH DESCRIPTION
.B Ffs
E 3
I 3
.Dd %Q%
.Dt FFS 3
.Os
.Sh NAME
.Nm ffs
.Nd find first bit set in a bit string
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft int
.Fn ffs "int value"
.Sh DESCRIPTION
The
.Fn ffs
D 5
fucntion
E 3
finds the first bit set in
E 5
I 5
function finds the first bit set in
E 5
D 3
.I value
E 3
I 3
.Fa value
E 3
and returns the index of that bit.
Bits are numbered starting from 1, starting at the right-most
bit.
A return value of 0 means that the argument was zero.
D 3
.SH SEE\ ALSO
bitstring(3)
E 3
I 3
.Sh SEE ALSO
.Xr bitstring 3
.Sh HISTORY
The
.Fn ffs
function appeared in
.Bx 4.3 .
E 3
E 1
