h43282
s 00002/00002/00053
d D 8.1 93/06/04 15:10:38 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00001/00052
d D 5.4 91/06/29 14:34:41 bostic 4 3
c add ANSI contribution notice
e
s 00041/00028/00012
d D 5.3 91/04/19 14:45:36 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00040
d D 5.2 91/04/19 14:40:58 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00035/00000/00000
d D 5.1 90/05/15 14:01:13 bostic 1 0
c date and time created 90/05/15 14:01:13 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" This code is derived from software contributed to Berkeley by
D 4
.\" Chris Torek.
E 4
I 4
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
E 4
D 3
.\"
E 3
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH MEMCHR 3 "%Q%"
.UC 7
.SH NAME
memchr \- locate byte in byte string
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

int
memchr(const void *b, int c, size_t len);
.ft R
.fi
.SH DESCRIPTION
.B Memchr
E 3
I 3
.Dd %Q%
.Dt MEMCHR 3
.Os
.Sh NAME
.Nm memchr
.Nd locate byte in byte string
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft void *
.Fn memchr "const void *b" "int c" "size_t len"
.Sh DESCRIPTION
The
.Fn memchr
function
E 3
locates the first occurrence of
D 3
.I c
E 3
I 3
.Fa c
E 3
(converted to an unsigned char)
in string
D 3
.IR b .
It returns a pointer to the byte located,
E 3
I 3
.Fa b .
.Sh RETURN VALUES
The
.Fn memchr
function
returns a pointer to the byte located,
E 3
or NULL if no such byte exists within
D 3
.I len
E 3
I 3
.Fa len
E 3
bytes.
D 3
.SH SEE ALSO
index(3), rindex(3), strchr(3), strcspn(3), strpbrk(3), strrchr(3),
strsep(3), strspn(3), strstr(3), strtok(3)
.SH STANDARDS
.I Memchr
conforms to ANSI X3.159-1989 (``ANSI C'').
E 3
I 3
.Sh SEE ALSO
.Xr index 3 ,
.Xr rindex 3 ,
.Xr strchr 3 ,
.Xr strcspn 3 ,
.Xr strpbrk 3 ,
.Xr strrchr 3 ,
.Xr strsep 3 ,
.Xr strspn 3 ,
.Xr strstr 3 ,
.Xr strtok 3
.Sh STANDARDS
The
.Fn memchr
function
conforms to
.St -ansiC .
E 3
E 1
