h41571
s 00002/00000/00121
d D 8.3 94/07/28 05:03:27 pendry 9 8
c added whiteout
e
s 00007/00007/00114
d D 8.2 93/12/11 22:38:06 mckusick 8 7
c copyediting for Usenix manuals
e
s 00002/00002/00119
d D 8.1 93/06/09 18:59:37 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00002/00120
d D 5.5 93/06/09 18:59:34 bostic 6 4
c fixed the under development line
e
s 00002/00002/00120
d R 8.1 93/06/04 15:12:11 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00002/00118
d D 5.4 91/07/31 22:54:42 cael 4 3
c prettied up a list
e
s 00065/00079/00055
d D 5.3 91/04/19 14:46:02 cael 3 2
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00134
d D 5.2 91/04/19 14:41:11 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00133/00000/00000
d D 5.1 90/05/10 21:25:41 bostic 1 0
c date and time created 90/05/10 21:25:41 by bostic
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 7
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
.\" %sccs.include.redist.man%
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH STRMODE 3 "%Q%"
.UC 7
.SH NAME
strmode \- convert inode status information into a symbolic string
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

void
strmode(mode_t mode, char *bp);
.ft R
.fi
.SH DESCRIPTION
.I Strmode
E 3
I 3
.Dd %Q%
.Dt STRMODE 3
.Os
.Sh NAME
.Nm strmode
.Nd convert inode status information into a symbolic string
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft void
.Fn strmode "mode_t mode" "char *bp"
.Sh DESCRIPTION
The
.Fn strmode
function
E 3
converts a file
D 3
.I mode
E 3
I 3
.Fa mode
E 3
(the type and permission information associated with an inode, see
D 3
.IR stat (2))
E 3
I 3
.Xr stat 2 )
E 3
into a symbolic string which is stored in the location referenced by
D 3
.IR bp .
E 3
I 3
.Fa bp .
E 3
D 4
This stored string is eleven characters in length plus a trailing NULL.
E 4
I 4
This stored string is eleven characters in length plus a trailing
.Dv NULL .
E 4
D 3
.PP
E 3
I 3
.Pp
E 3
The first character is the inode type, and will be one of the following:
D 3
.TP
\-
E 3
I 3
D 4
.Bl -tag -width xxxx
E 4
I 4
.Pp
.Bl -tag -width flag -offset indent -compact
E 4
.It \-
E 3
regular file
D 3
.br
.ns
.TP
b
E 3
I 3
.It b
E 3
block special
D 3
.br
.ns
.TP
c
E 3
I 3
.It c
E 3
character special
D 3
.br
.ns
.TP
d
E 3
I 3
.It d
E 3
directory
D 3
.br
.ns
.TP
l
E 3
I 3
.It l
E 3
symbolic link
D 3
.br
.ns
.TP
p
E 3
I 3
.It p
E 3
fifo
D 3
.br
.ns
.TP
s
E 3
I 3
.It s
E 3
socket
I 9
.It w
whiteout
E 9
D 3
.br
.ns
.TP
?
E 3
I 3
.It ?
E 3
unknown inode type
D 3
.PP
E 3
I 3
.El
.Pp
E 3
The next nine characters encode three sets of permissions, in three
characters each.
The first three characters are the permissions for the owner of the
file, the second three for the group the file belongs to, and the
third for the ``other'', or default, set of users.
D 3
.PP
E 3
I 3
.Pp
E 3
Permission checking is done as specifically as possible.
If read permission is denied to the owner of a file in the first set
D 8
of permssions, the owner of the file will not be able to read the file.
E 8
I 8
of permissions, the owner of the file will not be able to read the file.
E 8
This is true even if the owner is in the file's group and the group
permissions allow reading or the ``other'' permissions allow reading.
D 3
.PP
E 3
I 3
.Pp
E 3
If the first character of the three character set is an ``r'', the file is
readable for that set of users; if a dash ``\-'', it is not readable.
D 3
.PP
E 3
I 3
.Pp
E 3
If the second character of the three character set is a ``w'', the file is
writable for that set of users; if a dash ``\-'', it is not writable.
D 3
.PP
E 3
I 3
.Pp
E 3
The third character is the first of the following characters that apply:
D 3
.TP
S
E 3
I 3
.Bl -tag -width xxxx
.It S
E 3
If the character is part of the owner permissions and the file is not
D 8
executable or the directory is not searchable, by the owner, and the
E 8
I 8
executable or the directory is not searchable by the owner, and the
E 8
set-user-id bit is set.
D 3
.TP
S
E 3
I 3
.It S
E 3
If the character is part of the group permissions and the file is not
D 8
executable or the directory is not searchable, by the group, and the
E 8
I 8
executable or the directory is not searchable by the group, and the
E 8
set-group-id bit is set.
D 3
.TP
T
E 3
I 3
.It T
E 3
If the character is part of the other permissions and the file is not
D 8
executable or the directory is not searchable, by others, and the ``sticky''
E 8
I 8
executable or the directory is not searchable by others, and the ``sticky''
E 8
D 3
(S_ISVTX) bit is set.
.TP
s
E 3
I 3
.Pq Dv S_ISVTX
bit is set.
.It s
E 3
If the character is part of the owner permissions and the file is
D 8
executable or the directory searchable, by the owner, and the set-user-id
E 8
I 8
executable or the directory searchable by the owner, and the set-user-id
E 8
bit is set.
D 3
.TP
s
E 3
I 3
.It s
E 3
If the character is part of the group permissions and the file is
D 8
executable or the directory searchable, by the group, and the set-group-id
E 8
I 8
executable or the directory searchable by the group, and the set-group-id
E 8
bit is set.
D 3
.TP
t
E 3
I 3
.It t
E 3
If the character is part of the other permissions and the file is
D 8
executable or the directory searchable, by others, and the ``sticky''
E 8
I 8
executable or the directory searchable by others, and the ``sticky''
E 8
D 3
(S_ISVTX) bit is set.
.TP
x
E 3
I 3
.Pq Dv S_ISVTX
bit is set.
.It x
E 3
The file is executable or the directory is searchable.
D 3
.TP
\-
E 3
I 3
.It \-
E 3
None of the above apply.
D 3
.PP
E 3
I 3
.El
.Pp
E 3
The last character is a plus sign ``+'' if any there are any alternate
or additional access control methods associated with the inode, otherwise
it will be a space.
D 3
.SH RETURN VALUE
.I Strmode
E 3
I 3
.Sh RETURN VALUES
The
.Fn strmode
function
E 3
always returns 0.
D 3
.SH SEE ALSO
chmod(1), find(1), stat(2), getmode(3), setmode(3)
E 3
I 3
.Sh SEE ALSO
.Xr chmod 1 ,
.Xr find 1 ,
.Xr stat 2 ,
.Xr getmode 3 ,
.Xr setmode 3
.Sh HISTORY
The
.Fn strmode
D 6
function
.Ud .
E 6
I 6
function first appeared in 4.4BSD.
E 6
E 3
E 1
