h38131
s 00002/00002/00051
d D 8.1 93/06/04 15:12:40 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00052
d D 5.4 91/08/05 08:10:35 cael 4 3
c fix boo boo
e
s 00003/00001/00050
d D 5.3 91/06/29 14:42:05 bostic 3 2
c add ANSI contribution notice
e
s 00040/00028/00011
d D 5.2 91/04/19 14:40:41 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00033/00000/00000
d D 5.1 90/05/15 14:54:51 bostic 1 0
c date and time created 90/05/15 14:54:51 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" This code is derived from software contributed to Berkeley by
D 3
.\" Chris Torek.
E 3
I 3
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
E 3
D 2
.\"
E 2
.\" %sccs.include.redist.man%
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH STRSPN 3 "%Q%"
.UC 7
.SH NAME
strspn \- span a string
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

size_t
strspn(const char *s, const char *charset);
.ft R
.fi
.SH DESCRIPTION
.B Strcspn
E 2
I 2
.Dd %Q%
.Dt STRSPN 3
.Os
.Sh NAME
.Nm strspn
.Nd span a string
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft size_t
.Fn strspn "const char *s" "const char *charset"
.Sh DESCRIPTION
The
D 4
.Xr strcspn
E 4
I 4
.Fn strcspn
E 4
function
E 2
spans the initial part of the null-terminated string
D 2
.I s
E 2
I 2
.Fa s
E 2
as long as the characters from
D 2
.I s
E 2
I 2
.Fa s
E 2
occur in string
D 2
.IR charset .
.B Strspn
E 2
I 2
.Fa charset .
.Sh RETURN VALUES
The
.Fn strspn
function
E 2
returns the number of characters spanned.
D 2
.SH SEE ALSO
index(3), memchr(3), rindex(3), strchr(3), strcspn(3), strpbrk(3), strrchr(3),
strsep(3), strstr(3), strtok(3)
.SH STANDARDS
.B Strspn
conforms to ANSI X3.159-1989 (``ANSI C'').
E 2
I 2
.Sh SEE ALSO
.Xr index 3 ,
.Xr memchr 3 ,
.Xr rindex 3 ,
.Xr strchr 3 ,
.Xr strcspn 3 ,
.Xr strpbrk 3 ,
.Xr strrchr 3 ,
.Xr strsep 3 ,
.Xr strstr 3 ,
.Xr strtok 3
.Sh STANDARDS
The
.Fn strspn
function
conforms to
.St -ansiC .
E 2
E 1
