h19953
s 00002/00002/00158
d D 8.1 93/06/04 15:11:57 bostic 13 12
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00000/00156
d D 5.12 91/06/29 14:40:56 bostic 12 11
c add ANSI contribution notice
e
s 00101/00113/00055
d D 5.11 91/04/19 14:46:15 cael 11 10
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00168
d D 5.10 91/04/19 14:41:19 cael 10 9
c macro and text revision (-mdoc version 3)
e
s 00001/00001/00167
d D 5.9 91/01/19 17:27:59 bostic 9 8
c typo on %l
e
s 00002/00001/00166
d D 5.8 90/12/04 20:33:42 bostic 8 7
c note that %s is an extension
e
s 00006/00000/00161
d D 5.7 90/11/30 12:44:00 bostic 7 6
c add %s for number of seconds since the Epoch
e
s 00001/00011/00160
d D 5.6 90/06/23 17:43:42 trent 6 5
c new copyright notice
e
s 00004/00000/00167
d D 5.5 90/05/17 12:01:55 bostic 5 4
c forgot to include string.h
e
s 00017/00001/00150
d D 5.4 89/04/09 21:58:47 bostic 4 3
c add Sun flags to correct deficiencies in X3J11 spec
e
s 00002/00002/00149
d D 5.3 89/04/09 21:43:22 bostic 3 2
c do it the way Sun did it, I think it's right for S5, too (sigh)
e
s 00021/00006/00130
d D 5.2 89/03/12 13:09:32 bostic 2 1
c add System V/P1003.2 formats
e
s 00136/00000/00000
d D 5.1 89/03/09 16:52:06 bostic 1 0
c date and time created 89/03/09 16:52:06 by bostic
e
u
U
t
T
I 1
D 11
.\" Copyright (c) 1989 The Regents of the University of California.
E 11
I 11
D 13
.\" Copyright (c) 1989, 1991 The Regents of the University of California.
E 11
.\" All rights reserved.
E 13
I 13
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 13
.\"
I 12
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
E 12
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
.\"
D 11
.\"	%W% (Berkeley) %G%
E 11
I 11
.\"     %W% (Berkeley) %G%
E 11
.\"
D 11
.TH STRFTIME 3 "%Q"
.AT 3
.SH NAME
strftime \- format date and time
.SH SYNOPSIS
.nf
.ft B
#include <sys/types.h>
#include <time.h>
I 5
#include <string.h>
E 5

size_t
strftime(char *s, size_t maxsize, const char *format,
	const struct tm *timeptr);
.ft R
.fi
.SH DESCRIPTION
E 11
I 11
.Dd %Q%
.Dt STRFTIME 3
.Os
.Sh NAME
.Nm strftime
.Nd format date and time
.Sh SYNOPSIS
.Fd #include <sys/types.h>
.Fd #include <time.h>
.Fd #include <string.h>
.Ft size_t
.Fn strftime "char *buf" "size_t maxsize" "const char *format" "const struct tm *timeptr"
.Sh DESCRIPTION
E 11
The
D 11
.I strftime
E 11
I 11
.Fn strftime
E 11
function formats the information from
D 11
.I timeptr
E 11
I 11
.Fa timeptr
E 11
into the buffer
D 11
.I buf
E 11
I 11
.Fa buf
E 11
according to the string pointed to by
D 11
.IR format .
.PP
E 11
I 11
.Fa format .
.Pp
E 11
The
D 11
.I format
E 11
I 11
.Fa format
E 11
string consists of zero or more conversion specifications and
ordinary characters.
All ordinary characters are copied directly into the buffer.
D 11
A conversion specification consists of a percent sign (``%'')
E 11
I 11
A conversion specification consists of a percent sign
.Dq Ql %
E 11
and one other character.
D 11
.PP
E 11
I 11
.Pp
E 11
No more than
D 11
.I maxsize
E 11
I 11
.Fa maxsize
E 11
characters will be placed into the array.
If the total number of resulting characters, including the terminating
null character, is not more than
D 11
.IR maxsize ,
.I strftime
E 11
I 11
.Fa maxsize ,
.Fn strftime
E 11
returns the number of characters in the array, not counting the
terminating null.
Otherwise, zero is returned.
D 11
.PP
E 11
I 11
.Pp
E 11
Each conversion specification is replaced by the characters as
follows which are then copied into the buffer.
D 11
.TP
.B %A
E 11
I 11
.Bl -tag -width "xxxx"
.It Cm \&%A
E 11
is replaced by the full weekday name.
D 11
.TP
.B %a
E 11
I 11
.It Cm %a
E 11
is replaced by the abbreviated weekday name, where the abbreviation
is the first three characters.
D 11
.TP
.B %B
E 11
I 11
.It Cm \&%B
E 11
is replaced by the full month name.
D 11
.TP
D 2
.B %b
E 2
I 2
.B %b or %h
E 11
I 11
.It Cm %b  or  %h
E 11
E 2
is replaced by the abbreviated month name, where the abbreviation is
the first three characters.
D 11
.TP
I 4
.B %C
is equivalent to ``%a %b %e %H:%M:%S %Y'' (the format produced by
.IR asctime (3).
.TP
E 4
.B %c
D 3
is equivalent to ``%a %b %d %X %Z %Y''.
E 3
I 3
is equivalent to ``%m/%d/%y''.
E 3
.TP
I 2
.B %D
is replaced by the date in the format ``mm/dd/yy''.
.TP
E 2
.B %d
E 11
I 11
.It Cm \&%C
is equivalent to
.Dq Li %a %b %e %H:%M:%S %Y
(the format produced by
.Xr asctime 3 .
.It Cm %c
is equivalent to
.Dq Li %m/%d/%y .
.It Cm \&%D
is replaced by the date in the format
.Dq Ql mm/dd/yy .
.It Cm %d
E 11
is replaced by the day of the month as a decimal number (01-31).
D 11
.TP
I 4
.B %e
E 11
I 11
.It Cm %e
E 11
is replaced by the day of month as a decimal number (1-31); single
digits are preceded by a blank.
D 11
.TP
E 4
.B %H
E 11
I 11
.It Cm \&%H
E 11
is replaced by the hour (24-hour clock) as a decimal number (00-23).
D 11
.TP
.B %I
E 11
I 11
.It Cm \&%I
E 11
is replaced by the hour (12-hour clock) as a decimal number (01-12).
D 11
.TP
.B %j
E 11
I 11
.It Cm %j
E 11
is replaced by the day of the year as a decimal number (001-366).
D 11
.TP
I 4
.B %k
E 11
I 11
.It Cm %k
E 11
is replaced by the hour (24-hour clock) as a decimal number (0-23);
single digits are preceded by a blank.
D 11
.TP
.B %l
E 11
I 11
.It Cm %l
E 11
D 9
is replaced by the hour (12-hour clock) as a decimal number (01-12);
E 9
I 9
is replaced by the hour (12-hour clock) as a decimal number (1-12);
E 9
single digits are preceded by a blank.
D 11
.TP
E 4
I 2
.B %M
E 11
I 11
.It Cm \&%M
E 11
is replaced by the minute as a decimal number (00-59).
D 11
.TP
E 2
.B %m
E 11
I 11
.It Cm %m
E 11
is replaced by the month as a decimal number (01-12).
D 11
.TP
D 2
.B %M
is replaced by the minute as a decimal number (00-59).
E 2
I 2
.B %n
E 11
I 11
.It Cm %n
E 11
is replaced by a newline.
E 2
D 11
.TP
.B %p
is replaced by either ``AM'' or ``PM'' as appropriate.
.TP
I 2
.B %R
is equivalent to ``%H:%M''.
.TP
.B %r
is equivalent to ``%I:%M:%S %p''.
.TP
.B %t
E 11
I 11
.It Cm %p
is replaced by either
.Dq Tn AM
or
.Dq Tn PM
as appropriate.
.It Cm \&%R
is equivalent to
.Dq Li %H:%M
.It Cm %r
is equivalent to
.Dq Li %I:%M:%S %p .
.It Cm %t
E 11
is replaced by a tab.
D 11
.TP
E 2
.B %S
E 11
I 11
.It Cm \&%S
E 11
is replaced by the second as a decimal number (00-60).
D 11
.TP
I 7
.B %s
E 11
I 11
.It Cm %s
E 11
is replaced by the number of seconds since the Epoch, UCT (see
D 11
.IR mktime (3)).
.TP
E 7
I 2
.B %T or %X
is equivalent to ``%H:%M:%S''.
.TP
E 2
.B %U
E 11
I 11
.Xr mktime 3 ) .
.It Cm \&%T No or Cm \&%X
is equivalent to
.Dq Li %H:%M:%S .
.It Cm \&%U
E 11
is replaced by the week number of the year (Sunday as the first day of
the week) as a decimal number (00-53).
D 11
.TP
.B %W
E 11
I 11
.It Cm \&%W
E 11
is replaced by the week number of the year (Monday as the first day of
the week) as a decimal number (00-53).
D 11
.TP
.B %w
E 11
I 11
.It Cm %w
E 11
is replaced by the weekday (Sunday as the first day of the week)
as a decimal number (0-6).
D 2
.TP
.B %X
is equivalent to ``%H:%M:%S''.
E 2
D 11
.TP
.B %x
D 3
is equivalent to ``%a %b %d %Y''.
E 3
I 3
is equivalent to ``%m/%d/%y %H:%M:%S''.
E 3
.TP
.B %Y
E 11
I 11
.It Cm %x
is equivalent to
.Dq Li %m/%d/%y %H:%M:%S .
.It Cm \&%Y
E 11
is replaced by the year with century as a decimal number.
D 11
.TP
.B %y
E 11
I 11
.It Cm %y
E 11
is replaced by the year without century as a decimal number (00-99).
D 11
.TP
.B %Z
E 11
I 11
.It Cm \&%Z
E 11
is replaced by the time zone name.
D 11
.TP
.B %%
is replaced by ``%''.
.SH "SEE ALSO"
D 4
date(1), printf(1), printf(3)
E 4
I 4
date(1), ctime(3), printf(1), printf(3)
I 5
I 7
.SH BUGS
E 11
I 11
.It Cm %%
is replaced by
.Ql % .
.El
.Sh SEE ALSO
.Xr date 1 ,
.Xr ctime 3 ,
.Xr printf 1 ,
.Xr printf 3
.Sh STANDARDS
The
.Fn strftime
function
conforms to
.St -ansiC .
The
.Ql %s
conversion specification is an extension.
.Sh BUGS
E 11
D 8
The is no conversion specification for the phase of the moon.
E 8
I 8
There is no conversion specification for the phase of the moon.
E 8
E 7
D 11
.SH STANDARDS
.B Strftime
conforms to ANSI X3.159-1989 (``ANSI C'').
I 8
The ``%s'' conversion specification is an extension.
E 11
E 8
E 5
E 4
E 1
