h53720
s 00002/00002/00037
d D 8.1 93/06/04 15:13:05 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00038
d D 6.6 91/05/01 15:03:08 sellgren 8 7
c char *'s to void *'s
e
s 00029/00026/00010
d D 6.5 91/04/19 14:46:00 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00000/00000/00036
d D 6.4 91/04/19 14:41:10 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00002/00000/00034
d D 6.3 90/05/17 12:01:58 bostic 5 4
c forgot to include string.h
e
s 00021/00012/00013
d D 6.2 90/05/17 11:46:55 bostic 4 3
c new man page, from scratch
e
s 00001/00001/00024
d D 6.1 85/05/15 15:54:43 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00001/00023
d D 5.1 85/05/15 15:54:12 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00024/00000/00000
d D 4.1 85/05/15 15:53:26 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 7
.\" Copyright (c) 1990 The Regents of the University of California.
E 7
I 7
D 9
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
.\" %sccs.include.redist.man%
.\"
E 4
I 1
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH SWAB 3 
E 2
I 2
D 3
.TH SWAB 3  "19 January 1983"
E 3
I 3
D 7
.TH SWAB 3  "%Q%"
E 3
E 2
.AT 3
I 2
.nf
E 2
.SH NAME
swab \- swap bytes
.SH SYNOPSIS
.nf
D 4
.B swab(from, to, nbytes)
.B char *from, *to;
E 4
I 4
.ft B
I 5
#include <string.h>

E 5
void
swab(const char *src, char *dst, size_t len);
.ft R
E 4
.fi
.SH DESCRIPTION
E 7
I 7
.Dd %Q%
.Dt SWAB 3
.Os
.Sh NAME
.Nm swab
.Nd swap adjacent bytes
.Sh SYNOPSIS
.Fd #include <string.h>
.Ft void
D 8
.Fn swab "const char *src" "char *dst" "size_t len"
E 8
I 8
.Fn swab "const void *src" "void *dst" "size_t len"
E 8
.Sh DESCRIPTION
E 7
D 4
.I Swab
E 4
I 4
The function
D 7
.I swab
E 7
I 7
.Fn swab
E 7
E 4
copies
D 4
.I nbytes
bytes pointed to by
.I from
to the position pointed to by
.I to,
exchanging adjacent even and odd bytes.
It is useful for carrying binary data between
PDP11's and other machines.
.I Nbytes
E 4
I 4
D 7
.I len
E 7
I 7
.Fa len
E 7
bytes from the location referenced by
D 7
.I src
E 7
I 7
.Fa src
E 7
to the location referenced by
D 7
.IR dst ,
E 7
I 7
.Fa dst ,
E 7
swapping adjacent bytes.
D 7
.PP
.I Len
E 4
should be even.
I 4
.SH SEE ALSO
bzero(3), memset(3)
E 7
I 7
.Pp
The argument
.Fa len
must be even number.
.Sh SEE ALSO
.Xr bzero 3 ,
.Xr memset 3
.Sh HISTORY
A
.Fn swab
function appeared in
.At v7 .
E 7
E 4
E 1
