h31628
s 00011/00009/00164
d D 5.7 93/05/31 13:56:37 mckusick 7 6
c minor format nits
e
s 00066/00069/00107
d D 5.6 91/03/14 01:41:23 cael 6 5
c updated to -mdoc version 3
e
s 00019/00012/00157
d D 5.5 90/07/24 22:43:00 cael 5 4
c .Xr botch fix
e
s 00126/00075/00043
d D 5.4 90/06/11 05:55:05 cael 4 3
c converted man page
e
s 00001/00003/00117
d D 5.3 88/03/29 15:13:17 bostic 3 2
c we don't have un32(7) in the Berkeley manual
e
s 00034/00058/00086
d D 5.2 88/03/29 15:04:18 bostic 2 1
c AT&T doesn't use the man macros...
e
s 00144/00000/00000
d D 5.1 88/03/29 14:52:27 bostic 1 0
c date and time created 88/03/29 14:52:27 by bostic
e
u
U
t
T
I 1
D 2
.ll 68
.ce
UNIX\(rg
.FS "\&"
UNIX is a registered trademark of AT&T
.FE
System V
.sp 2
.in +1
NAME
.br
.in +5
E 2
I 2
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 4
.\"
D 4
.TH CPIO 1 "%Q%"
.UC 7
.SH NAME
E 2
cpio - copy file archives in and out
D 2
.in -5
.sp
SYNOPSIS
.br
.in +5
E 2
I 2
.SH SYNOPSIS
E 2
cpio -o [ acBv ]
E 4
I 4
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
D 5
.Dd %Q%
E 5
D 6
.\"	@(#)cpio.1	5.3 (Berkeley) 3/29/88
.\"
E 6
I 5
.Dd %Q%
E 5
.Dt CPIO 1
D 6
.Os BSD 4.4
E 6
I 6
.Os
E 6
.Sh NAME
.Nm cpio
.Nd copy file archives in and out
.Sh SYNOPSIS
.Nm cpio
D 6
.Fl o
.Op Fl acBv
E 4
D 2
.sp
E 2
I 2
.br
E 2
D 4
cpio -i [ BcdmrtuvfsSb6 ] [ patterns ]
E 4
I 4
.Nm cpio
E 6
.Fl i
.Op Fl BcdmrtuvfsSb6
.Op Ar patterns
E 4
D 2
.sp
cpio -p [ adlmruv ] directory
.sp
.in -5
DESCRIPTION
E 2
D 6
.br
E 6
D 2
.in +5
E 2
I 2
D 4
cpio -p [ adlmruv ] directory
.SH DESCRIPTION
E 2
Cpio -o (copy out) reads the standard input to obtain a list
E 4
I 4
.Nm cpio
I 6
.Fl o
.Op Fl acBv
.Nm cpio
E 6
.Fl p
.Op Fl adlmruv
.Ar directory
.Sh DESCRIPTION
.Nm Cpio
has three functional modes; copy out, copy in and pass.
.Pp
Functional Options:
I 5
D 6
.Tw Ds
E 5
.Tp Fl o
Copy out \- reads the standard input to obtain a list
E 4
of path names and copies those files onto the standard
output together with path name and status information.
Output is padded to a 512-byte boundary.
D 4
.sp
Cpio -i (copy in) extracts files from the standard input,
which is assumed to be the product of a previous cpio -o.
E 4
I 4
.Pp
.Tp Fl i
Copy in \- extracts files from the standard input,
E 6
I 6
.Bl -tag -width 4n
.It Fl i
.Em Copy in .
Extracts files from the standard input,
E 6
which is assumed to be the product of a previous
.Nm cpio
.Fl o .
E 4
Only files with names that match patterns are selected.
D 4
Patterns are given in the name-generating notation of sh(1).
In patterns, meta-characters ?, *, and [...] match the
E 4
I 4
Patterns are given in the name-generating notation of
.Xr sh 1 .
D 5
In patterns, meta-characters ?, *, and
.Op ...
E 5
I 5
In patterns, meta-characters
D 6
.Sq Li \&? ,
.Sq Li \&* ,
E 6
I 6
.Ql \&? ,
.Ql \&* ,
E 6
and
D 6
.Sq Li [...]
E 6
I 6
.Ql [...]
E 6
E 5
match the
E 4
D 5
slash / character.  Multiple patterns may be specified and
if no patterns are specified, the default for patterns is *
E 5
I 5
slash
D 6
.Sq Li \&/
E 6
I 6
.Ql \&/
E 6
character.  Multiple patterns may be specified and
if no patterns are specified, the default for patterns is
D 6
.Sq Li \&*
E 6
I 6
.Ql \&*
E 6
E 5
(i.e., select all files).  The extracted files are
conditionally created and copied into the current directory
tree based upon the options described below.  The
D 4
permissions of the files will be those of the previous cpio
-o.  The owner and group of the files will be that of the
E 4
I 4
permissions of the files will be those of the previous
.Nm cpio
.Fl o .
The owner and group of the files will be that of the
E 4
D 7
current user unless the user is super-user, which causes
E 7
I 7
current user unless the user is the super-user, which causes
E 7
D 4
cpio to retain the owner and group of the files of the
previous cpio -o.
.sp
Cpio -p (pass) reads the standard input to obtain a list of
E 4
I 4
.Nm cpio
to retain the owner and group of the files of the
previous
.Nm cpio
.Fl o .
D 6
.Pp
.Tp Fl p
Pass \- reads the standard input to obtain a list of
E 6
I 6
.It Fl o
.Em Copy out .
Reads the standard input to obtain a list
of path names and copies those files onto the standard
output together with path name and status information.
Output is padded to a 512-byte boundary.
.It Fl p
.Em Pass.
Reads the standard input to obtain a list of
E 6
E 4
path names of files that are conditionally created and
copied into the destination directory tree based upon the
options described below.
D 4
.sp
The meanings of the available options are:
D 2
.VL 6 0 1
.LI a
E 2
I 2
.IP a
E 4
I 4
D 6
.Tp
E 6
I 6
.El
E 6
.Pp
D 7
Options for the above functional options:
E 7
I 7
Options for the above functional option:
E 7
I 5
D 6
.Tw Ds
E 5
.Tp Fl a
E 4
E 2
Reset access times of input files after they have been
copied.
D 2
.LI B
E 2
I 2
D 4
.IP B
E 2
Input/output is to be blocked 5,120 bytes to the record  
(does not apply to the pass options; meaningful only 
with data directed to or from /dev/rmt/??).
D 2
.LI d
E 2
I 2
.IP d
E 4
I 4
.Tp Fl B
E 6
I 6
.Bl -tag -width 4n
.It Fl B
E 6
Input/output is to be blocked 5,120 bytes to the record
(does not apply to the pass options; meaningful only
with data directed to or from
D 7
.Pa /dev/rmt/??).
E 7
I 7
.Pa /dev/rmt0).
E 7
D 6
.Tp Fl d
E 4
E 2
Directories are to be created as needed.
D 2
.LI c
E 2
I 2
D 4
.IP c
E 4
I 4
.Tp Fl c
E 6
I 6
.It Fl S
Swap halfwords.  Use only with the
.Fl i
option.
.It Fl a
Reset access times of input files after they have been
copied.
.It Fl b
D 7
halfwords.  Use only with the
E 7
I 7
Swap halfwords.  Use only with the
E 7
.Fl i
option.
.It Fl c
E 6
E 4
E 2
Write header information in ASCII character form for
portability.
D 2
.LI r
E 2
I 2
D 4
.IP r
E 4
I 4
D 6
.Tp Fl r
E 6
I 6
.It Fl d
Directories are to be created as needed.
.It Fl f
Copy in all files except those in patterns.
.It Fl l
Whenever possible, link files rather than copying them.
Usable only with the
.Fl p
option.
.It Fl m
Retain previous file modification time.  This option is
ineffective on directories that are being copied.
.It Fl r
E 6
E 4
E 2
Interactively rename files.  If the user types a null
D 7
line, the files is skipped.
E 7
I 7
line, the file is skipped.
E 7
D 2
.LI t
E 2
I 2
D 4
.IP t
E 4
I 4
D 6
.Tp Fl t
E 6
I 6
.It Fl s
Swap bytes.  Use only with the
.Fl i
option.
.It Fl t
E 6
E 4
E 2
Print a table of contents of the input.  No files are
created.
D 2
.LI u
E 2
I 2
D 4
.IP u
E 4
I 4
D 6
.Tp Fl u
E 6
I 6
.It Fl u
E 6
E 4
E 2
Copy unconditionally (normally, an older file will not
replace a newer file with the same name).
D 2
.LI v
E 2
I 2
D 4
.IP v
E 2
Verbose: causes a list of file names to be printed.  
E 4
I 4
D 6
.Tp Fl v
E 6
I 6
.It Fl v
E 6
Verbose: causes a list of file names to be printed.
E 4
D 7
When used with the t option, the table of contents
E 7
I 7
When used with the
.Fl t
option, the table of contents
E 7
D 4
looks like the output of an ls -l command (see ls(1)).
D 2
.LI l
E 2
I 2
.IP l
E 4
I 4
looks like the output of an
D 5
.Li ls -l
E 5
I 5
.Ql ls -l
E 5
command (see
.Xr ls 1 ) .
D 6
.Tp Fl l
E 4
E 2
Whenever possible, link files rather than copying them.
D 4
Usable only with the -p option.
D 2
.LI m
E 2
I 2
.IP m
E 4
I 4
Usable only with the
.Fl p
option.
.Tp Fl m
E 4
E 2
Retain previous file modification time.  This option is
ineffective on directories that are being copied.
D 2
.LI f
E 2
I 2
D 4
.IP f
E 4
I 4
.Tp Fl f
E 4
E 2
Copy in all files except those in patterns.
D 2
.LI s
E 2
I 2
D 4
.IP s
E 2
Swap bytes.  Use only with the -i option.
D 2
.LI S
E 2
I 2
.IP S
E 2
Swap halfwords.  Use only with the -i option.
D 2
.LI b
E 2
I 2
.IP b
E 2
Swap both bytes and halfwords.  Use only with the -i
E 4
I 4
.Tp Fl s
Swap bytes.  Use only with the
.Fl i
E 4
option.
D 2
.LI 6 
E 2
I 2
D 4
.IP 6
E 4
I 4
.Tp Fl S
Swap halfwords.  Use only with the
.Fl i
option.
.Tp Fl b
halfwords.  Use only with the
.Fl i
option.
.Tp Fl 6
E 6
I 6
.It Fl 6
E 6
E 4
E 2
Process an old (i.e., UNIX System Sixth Edition format)
D 4
file.  Only useful with -i (copy in).
D 2
.LE
.sp
.in -5
EXAMPLES
.br
.in +5
E 2
I 2
.SH EXAMPLES
E 4
I 4
file.  Only useful with
D 5
.FL i
E 5
I 5
.Fl i
E 5
(copy in).
D 6
.Tp
E 6
I 6
.El
E 6
.Sh EXAMPLES
E 4
E 2
The first example below copies the contents of a directory
into an archive; the second duplicates a directory
hierarchy:
D 4
.sp
.in +5
ls | cpio -o >/dev/rmt/0m
.sp
cd olddir
.br
find . -depth -print | cpio -pdl newdir
.br
.sp
.in -5
E 4
I 4
.Pp
D 5
.Dl ls  cpio -o >/dev/rmt/0m
E 5
I 5
D 6
.Dl ls  \&| cpio -o >/dev/rmt/0m
E 6
I 6
.Bd -literal -offset indent
D 7
ls  \&| cpio -o > edev/rmt/0m
E 7
I 7
ls  \&| cpio -o > /dev/rmt0
E 7

cd olddir
find \&. -depth -print \&|  cpio -pdl newdir
E 6
E 5
.Pp
D 6
.Dl cd olddir
D 5
.Dl find . -depth -print  cpio -pdl newdir
E 5
I 5
.Dl find . -depth -print \&|  cpio -pdl newdir
E 5
.Pp
E 6
E 4
D 2
The trivial case ``find . -depth -print | cpio -oB >/dev/fmt/0m''
E 2
I 2
The trivial case
D 4
.nf
.in +5
``find . -depth -print | cpio -oB >/dev/fmt/0m''
.in -5
.fi
E 4
I 4
.Pp
D 5
.Dl find . -depth -print  cpio -oB >/dev/fmt/0m
E 5
I 5
D 6
.Dl find . -depth -print \&|  cpio -oB >/dev/fmt/0m
E 6
I 6
D 7
.Dl find \&. -depth -print \&|  cpio -oB >/dev/fmt/0m
E 7
I 7
.Dl find \&. -depth -print \&|  cpio -oB >/dev/rmt0
E 7
E 6
E 5
.Pp
E 4
E 2
can be handled more efficiently by:
D 2
.sp
E 2
D 4
.in +5
find . -cpio /dev/rmt/0m
I 2
.in -5
E 2
.sp
D 2
.in -10
SEE ALSO
.br
.in +5
E 2
I 2
.SH SEE ALSO
E 2
ar(1), find(1), ls(1).
.br
cpio(4) in the UNIX System User Reference Manual.
D 2
.sp
.in -5
BUGS
.br
.in +5
E 2
I 2
.SH BUGS
E 4
I 4
.Pp
D 6
.Dl find . -cpio /dev/rmt/0m
.Pp
E 6
I 6
D 7
.Dl find \&. -cpio /dev/rmt/0m
E 7
I 7
.Dl find \&. -cpio /dev/rmt0
E 7
E 6
.Sh SEE ALSO
.Xr ar 1 ,
.Xr find 1 ,
D 5
.Xr ls 1 .
E 5
I 5
.Xr ls 1 ,
E 5
.Xr cpio 4
D 5
in the UNIX System User Reference Manual.
E 5
.Sh HISTORY
The
.Nm cpio
command appeared in System V AT&T UNIX.  This program is derived
from the System V AT&T sources which were contributed to the public
domain by AT&T.
.Sh BUGS
E 4
E 2
Path names are restricted to 128 characters.  If there are
too many unique linked files, the program runs out of memory
to keep track of them and, thereafter, linking information
is lost.  Only the super-user can copy special files.  The
D 3
-B option does not work with certain magnetic tape drives
(see un32(7) in the UNIX System Administrator Reference 
Manual).
E 3
I 3
D 4
-B option does not work with certain magnetic tape drives.
E 4
I 4
.Fl B
option does not work with certain magnetic tape drives.
E 4
E 3
D 2
.sp
E 2
E 1
