.\" Copyright (c) 1994
.\"	The President and Fellows of Harvard University
.\"	@(#)lffs_roll.8	(Harvard) 12/27/94
.\"
.Dd December 27, 1994
.Dt LFFS_ROLL 8
.Os BSD 4
.Sh NAME
.Nm lffs_roll
.Nd journaled file system recovery utility
.Sh SYNOPSIS
.Nm lffs_roll
.Op Fl s Ar startlsn
.Op Fl b Ar altsb
.Op Fl p
.Op Fl n
.Op Fl v
.Ar device
.Ar filesystem
.Sh DESCRIPTION
.Nm lffs_roll
interprets
.Ar filesystem
as a log for the filesystem that resides on
.Ar device .
It is normally used in the script
.Pa /etc/rc
during automatic reboot.
The following flags are interpreted by
.Nm lffs_roll .
.Bl -tag -width indent
.It Fl b
Use the block specified immediately after the flag as
the super block for the filesystem. 
.It Fl s
Use the number following the flag as the LSN of the log record with
which to begin recovery.  If the -s
flag is not specified recovery begins at the most recent checkpoint.
If the file system was unmounted cleanly, there should be no recovery
actions.
.It Fl v
Run in verbose mode.  For each log record processed, print the
record type and its parameters.  As recovery operations are processed,
.Nm lffs_roll
will output each recovery action.
.It Fl n
Do not actually modify the file system.  This is useful in conjunction
with the -v
option to determine what recovery actions would be taken.
.It Fl p
Process only the preread phase.  During this phase each log record is
read, but no recovery actions are taken.
.Bl -tag -width indent
.El
.Sh DIAGNOSTICS
The diagnostics produced by 
.Nm lffs_roll
are largely nonexistent at the moment.  If lffs_roll encounters a recovery
operation that it cannot process, it fails.  This will have to change.
.Sh SEE ALSO
.Xr fstab 5 ,
.Xr fs 5 ,
.Xr fsdb 8 ,
.Xr newfs 8 ,
.Xr mkfs 8 ,
.Xr reboot 8
