h11304
s 00002/00002/00082
d D 8.1 93/06/06 14:30:00 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00002/00082
d D 5.6 93/06/01 17:08:29 bostic 6 5
c cleanup by George Lavender
e
s 00003/00000/00081
d D 5.5 91/06/27 17:16:12 bostic 5 4
c add POSIX/IEEE contribution notice
e
s 00017/00026/00064
d D 5.4 91/05/06 00:23:24 cael 4 3
c mdoc version three/bsd copyright
e
s 00003/00003/00087
d D 5.3 90/07/24 22:43:24 cael 3 2
c .Xr botch fix
e
s 00054/00049/00036
d D 5.2 90/06/11 05:55:31 cael 2 1
c converted man page
e
s 00084/00000/00000
d D 5.1 89/12/25 12:01:12 bostic 1 0
c date and time created 89/12/25 12:01:12 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1989 The Regents of the University of California.
E 2
I 2
D 7
.\" Copyright (c) 1989, 1990 The Regents of the University of California.
E 2
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
.\"
I 5
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 5
D 2
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 2
I 2
D 4
.\" %sccs.include.redist.man%
E 4
I 4
.\" %sccs.include.redist.roff%
E 4
E 2
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH CUT 1 "%Q%"
.UC 7
.SH NAME
cut - select portions of each line of a file
.SH SYNOPSIS
.nf
cut -c list [file ...]
cut -f list [-s] [-d string] [file ...]
.fi
.SH DESCRIPTION
E 2
I 2
.Dd %Q%
.Dt CUT 1
D 4
.Os BSD 4.4
E 4
I 4
.Os
E 4
.Sh NAME
.Nm cut
.Nd select portions of each line of a file
.Sh SYNOPSIS
.Nm cut
D 4
.Ar list
E 4
I 4
.Fl c Ar list
E 4
.Ar
D 4
.br
E 4
.Nm cut
D 4
.Ar list
.Op Fl s
E 4
I 4
.Fl f Ar list
E 4
.Op Fl d Ar string
I 4
.Op Fl s
E 4
.Ar
.Sh DESCRIPTION
E 2
The
D 2
.I cut
E 2
I 2
.Nm cut
E 2
utility selects portions of each line (as specified by
D 2
.IR list )
E 2
I 2
.Ar list  )
E 2
from each
D 2
.I file
E 2
I 2
.Ar file
E 2
(or the standard input by default), and writes them to the
standard output.
The items specified by
D 2
.I list
E 2
I 2
.Ar list
E 2
can be in terms of column position or in terms of fields delimited
D 3
by a special character.
E 3
I 3
by a special character. Column numbering starts from 1.
E 3
D 2
.PP
.I List
E 2
I 2
.Pp
.Ar List
E 2
D 3
is a comma or whitespace separated set of one-based numbers and/or
E 3
I 3
is a comma or whitespace separated set of increasing numbers and/or
E 3
number ranges.
D 2
Number ranges consist of a number, a dash (``-''), and a second number
E 2
I 2
Number ranges consist of a number, a dash
D 4
.Li (``\-'') ,
E 4
I 4
.Pq Li \- ,
E 4
and a second number
E 2
and select the fields or columns from the first number to the second,
inclusive.
Numbers or number ranges may be preceded by a dash, which selects all
fields or columns from 1 to the first number.
Numbers or number ranges may be followed by a dash, which selects all
fields or columns from the last number to the end of the line.
Numbers and number ranges may be repeated, overlapping, and in any order.
It is not an error to select fields or columns not present in the
input line.
D 2
.PP
E 2
I 2
.Pp
E 2
The options are as follows:
D 2
.TP
-c list
E 2
I 2
D 4
.Tw Fl
.Tp Cx Fl c
.Cx \&\ \&
.Ar list
.Cx
E 4
I 4
.Bl -tag -width Fl
.It Fl c Ar list
E 4
E 2
The
D 2
.I list
E 2
I 2
.Ar list
E 2
specifies character positions.
D 2
.TP
-f list
E 2
I 2
D 4
.Tp Cx Fl f
.Cx \&\ \&
.Ar list
.Cx
E 4
I 4
.It Fl d Ar string
D 6
Use
.Ar char
E 6
I 6
Use the first character of
.Ar string
E 6
as the field delimiter character instead of the tab character.
.It Fl f Ar list
E 4
E 2
The
D 2
.I list
E 2
I 2
.Ar list
E 2
specifies fields, delimited in the input by a single tab character.
Output fields are separated by a single tab character.
D 2
.TP
-d char
E 2
I 2
D 4
.Tp Cx Fl d
.Cx \&\ \&
.Ar char
.Cx
E 2
Use
D 2
.I char
E 2
I 2
.Ar char
E 2
as the field delimiter character instead of the tab character.
D 2
.TP
-s
E 2
I 2
.Tp Fl s
E 4
I 4
.It Fl s
E 4
E 2
Suppresses lines with no field delimiter characters.
Unless specified, lines with no delimiters are passed through unmodified.
D 2
.PP
.I Cut
E 2
I 2
D 4
.Tp
E 4
I 4
.El
E 4
.Pp
.Nm Cut
E 2
D 3
exit 0 on success, 1 if an error occurred.
E 3
I 3
exits 0 on success, 1 if an error occurred.
E 3
D 2
.SH ENVIRONMENT
.SH "SEE ALSO"
paste(1)
.SH STANDARDS
E 2
I 2
.Sh SEE ALSO
.Xr paste 1
.Sh STANDARDS
E 2
The
D 2
.I cut
E 2
I 2
.Nm cut
E 2
D 4
function is expected to be POSIX 1003.2 compatible.
E 4
I 4
utility is expected to conform to
.St -p1003.2 .
E 4
E 1
