h23257
s 00002/00002/00290
d D 8.1 93/06/04 16:31:20 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00000/00289
d D 5.3 92/08/05 12:37:23 bostic 3 2
c replace regexp with POSIX regex
e
s 00214/00104/00075
d D 5.2 91/04/20 08:20:55 cael 2 1
c -mdoc (version 3)
e
s 00179/00000/00000
d D 5.1 90/05/03 17:47:31 bostic 1 0
c date and time created 90/05/03 17:47:31 by bostic
e
u
U
t
T
I 1
D 2
.TH REGEXP 3 local
.DA 30 Nov 1985
.SH NAME
regcomp, regexec, regsub, regerror \- regular expression handler
.SH SYNOPSIS
.ft B
.nf
#include <regexp.h>

regexp *regcomp(exp)
char *exp;

int regexec(prog, string)
regexp *prog;
char *string;

regsub(prog, source, dest)
regexp *prog;
char *source;
char *dest;

regerror(msg)
char *msg;
.SH DESCRIPTION
These functions implement
.IR egrep (1)-style
E 2
I 2
D 4
.\" Copyright 1991 The Regents of the University of California.
.\" All rights reserved.
E 4
I 4
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 4
.\"
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt REGEXP 3
.Os
.Sh NAME
.Nm regcomp ,
.Nm regexec ,
.Nm regsub ,
.Nm regerror
.Nd regular expression handlers
.Sh SYNOPSIS
.Fd #include <regexp.h>
.Ft regexp *
.Fn regcomp "const char *exp"
.Ft int
.Fn regexec "const regexp *prog" "const char *string"
.Ft void
.Fn regsub "const regexp *prog" "const char *source" "char *dest"
.Sh DESCRIPTION
I 3
This interface is made obsolete by
.Xr regex 3 .
.Pp
E 3
The
.Fn regcomp ,
.Fn regexec ,
.Fn regsub ,
and
.Fn regerror
functions
implement
.Xr egrep 1 Ns -style
E 2
regular expressions and supporting facilities.
D 2
.PP
.I Regcomp
E 2
I 2
.Pp
The
.Fn regcomp
function
E 2
compiles a regular expression into a structure of type
D 2
.IR regexp ,
E 2
I 2
.Xr regexp ,
E 2
and returns a pointer to it.
The space has been allocated using
D 2
.IR malloc (3)
E 2
I 2
.Xr malloc 3
E 2
and may be released by
D 2
.IR free .
.PP
.I Regexec
matches a NUL-terminated \fIstring\fR against the compiled regular expression
in \fIprog\fR.
E 2
I 2
.Xr free .
.Pp
The
.Fn regexec
function
matches a
.Dv NUL Ns -terminated
.Fa string
against the compiled regular expression
in
.Fa prog .
E 2
It returns 1 for success and 0 for failure, and adjusts the contents of
D 2
\fIprog\fR's \fIstartp\fR and \fIendp\fR (see below) accordingly.
.PP
E 2
I 2
.Fa prog Ns 's
.Em startp
and
.Em endp
(see below) accordingly.
.Pp
E 2
The members of a
D 2
.I regexp
E 2
I 2
.Xr regexp
E 2
structure include at least the following (not necessarily in order):
D 2
.PP
.RS
E 2
I 2
.Bd -literal -offset indent
E 2
char *startp[NSUBEXP];
D 2
.br
E 2
char *endp[NSUBEXP];
D 2
.RE
.PP
E 2
I 2
.Ed
.Pp
E 2
where
D 2
.I NSUBEXP
E 2
I 2
.Dv NSUBEXP
E 2
is defined (as 10) in the header file.
D 2
Once a successful \fIregexec\fR has been done using the \fIregexp\fR,
each \fIstartp\fR-\fIendp\fR pair describes one substring
within the \fIstring\fR,
with the \fIstartp\fR pointing to the first character of the substring and
the \fIendp\fR pointing to the first character following the substring.
The 0th substring is the substring of \fIstring\fR that matched the whole
E 2
I 2
Once a successful
.Fn regexec
has been done using the
.Fn regexp ,
each
.Em startp Ns - Em endp
pair describes one substring
within the
.Fa string ,
with the
.Em startp
pointing to the first character of the substring and
the
.Em endp
pointing to the first character following the substring.
The 0th substring is the substring of
.Fa string
that matched the whole
E 2
regular expression.
The others are those substrings that matched parenthesized expressions
within the regular expression, with parenthesized expressions numbered
in left-to-right order of their opening parentheses.
D 2
.PP
.I Regsub
copies \fIsource\fR to \fIdest\fR, making substitutions according to the
most recent \fIregexec\fR performed using \fIprog\fR.
Each instance of `&' in \fIsource\fR is replaced by the substring
indicated by \fIstartp\fR[\fI0\fR] and
\fIendp\fR[\fI0\fR].
Each instance of `\e\fIn\fR', where \fIn\fR is a digit, is replaced by
E 2
I 2
.Pp
The
.Fn regsub
function
copies
.Fa source
to
.Fa dest ,
making substitutions according to the
most recent
.Fn regexec
performed using
.Fa prog .
Each instance of `&' in
.Fa source
is replaced by the substring
indicated by
.Em startp Ns Bq
and
.Em endp Ns Bq .
Each instance of
.Sq \e Ns Em n ,
where
.Em n
is a digit, is replaced by
E 2
the substring indicated by
D 2
\fIstartp\fR[\fIn\fR] and
\fIendp\fR[\fIn\fR].
To get a literal `&' or `\e\fIn\fR' into \fIdest\fR, prefix it with `\e';
to get a literal `\e' preceding `&' or `\e\fIn\fR', prefix it with
E 2
I 2
.Em startp Ns Bq Em n
and
.Em endp Ns Bq Em n .
To get a literal `&' or
.Sq \e Ns Em n
into
.Fa dest ,
prefix it with `\e';
to get a literal `\e' preceding `&' or
.Sq \e Ns Em n ,
prefix it with
E 2
another `\e'.
D 2
.PP
.I Regerror
is called whenever an error is detected in \fIregcomp\fR, \fIregexec\fR,
or \fIregsub\fR.
The default \fIregerror\fR writes the string \fImsg\fR,
E 2
I 2
.Pp
The
.Fn regerror
function
is called whenever an error is detected in
.Fn regcomp ,
.Fn regexec ,
or
.Fn regsub .
The default
.Fn regerror
writes the string
.Fa msg ,
E 2
with a suitable indicator of origin,
on the standard
error output
D 2
and invokes \fIexit\fR(2).
.I Regerror
E 2
I 2
and invokes
.Xr exit 2 .
The
.Fn regerror
function
E 2
can be replaced by the user if other actions are desirable.
D 2
.SH "REGULAR EXPRESSION SYNTAX"
A regular expression is zero or more \fIbranches\fR, separated by `|'.
E 2
I 2
.Sh REGULAR EXPRESSION SYNTAX
A regular expression is zero or more
.Em branches ,
separated by `|'.
E 2
It matches anything that matches one of the branches.
D 2
.PP
A branch is zero or more \fIpieces\fR, concatenated.
E 2
I 2
.Pp
A branch is zero or more
.Em pieces ,
concatenated.
E 2
It matches a match for the first, followed by a match for the second, etc.
D 2
.PP
A piece is an \fIatom\fR possibly followed by `*', `+', or `?'.
E 2
I 2
.Pp
A piece is an
.Em atom
possibly followed by `*', `+', or `?'.
E 2
An atom followed by `*' matches a sequence of 0 or more matches of the atom.
An atom followed by `+' matches a sequence of 1 or more matches of the atom.
An atom followed by `?' matches a match of the atom, or the null string.
D 2
.PP
E 2
I 2
.Pp
E 2
An atom is a regular expression in parentheses (matching a match for the
D 2
regular expression), a \fIrange\fR (see below), `.'
E 2
I 2
regular expression), a
.Em range
(see below), `.'
E 2
(matching any single character), `^' (matching the null string at the
beginning of the input string), `$' (matching the null string at the
end of the input string), a `\e' followed by a single character (matching
that character), or a single character with no other significance
(matching that character).
D 2
.PP
A \fIrange\fR is a sequence of characters enclosed in `[]'.
E 2
I 2
.Pp
A
.Em range
is a sequence of characters enclosed in `[]'.
E 2
It normally matches any single character from the sequence.
If the sequence begins with `^',
D 2
it matches any single character \fInot\fR from the rest of the sequence.
E 2
I 2
it matches any single character
.Em not
from the rest of the sequence.
E 2
If two characters in the sequence are separated by `\-', this is shorthand
D 2
for the full list of ASCII characters between them
E 2
I 2
for the full list of
.Tn ASCII
characters between them
E 2
(e.g. `[0-9]' matches any decimal digit).
To include a literal `]' in the sequence, make it the first character
(following a possible `^').
To include a literal `\-', make it the first or last character.
D 2
.SH AMBIGUITY
E 2
I 2
.Sh AMBIGUITY
E 2
If a regular expression could match two different parts of the input string,
it will match the one which begins earliest.
D 2
If both begin in the same place	but match different lengths, or match
E 2
I 2
If both begin in the same place but match different lengths, or match
E 2
the same length in different ways, life gets messier, as follows.
D 2
.PP
E 2
I 2
.Pp
E 2
In general, the possibilities in a list of branches are considered in
left-to-right order, the possibilities for `*', `+', and `?' are
considered longest-first, nested constructs are considered from the
outermost in, and concatenated constructs are considered leftmost-first.
The match that will be chosen is the one that uses the earliest
possibility in the first choice that has to be made.
If there is more than one choice, the next will be made in the same manner
(earliest possibility) subject to the decision on the first choice.
And so forth.
D 2
.PP
For example, `(ab|a)b*c' could match `abc' in one of two ways.
E 2
I 2
.Pp
For example,
.Sq Li (ab|a)b*c
could match
`abc' in one of two ways.
E 2
The first choice is between `ab' and `a'; since `ab' is earlier, and does
lead to a successful overall match, it is chosen.
Since the `b' is already spoken for,
the `b*' must match its last possibility\(emthe empty string\(emsince
it must respect the earlier choice.
D 2
.PP
E 2
I 2
.Pp
E 2
In the particular case where no `|'s are present and there is only one
`*', `+', or `?', the net effect is that the longest possible
match will be chosen.
D 2
So `ab*', presented with `xabbbby', will match `abbbb'.
Note that if `ab*' is tried against `xabyabbbz', it
E 2
I 2
So
.Sq Li ab* ,
presented with `xabbbby', will match `abbbb'.
Note that if
.Sq Li ab* ,
is tried against `xabyabbbz', it
E 2
will match `ab' just after `x', due to the begins-earliest rule.
(In effect, the decision on where to start the match is the first choice
to be made, hence subsequent choices must respect it even if this leads them
to less-preferred alternatives.)
D 2
.SH SEE ALSO
egrep(1), expr(1)
.SH DIAGNOSTICS
\fIRegcomp\fR returns NULL for a failure
(\fIregerror\fR permitting),
E 2
I 2
.Sh RETURN VALUES
The
.Fn regcomp
function
returns
.Dv NULL
for a failure
.Pf ( Fn regerror
permitting),
E 2
where failures are syntax errors, exceeding implementation limits,
or applying `+' or `*' to a possibly-null operand.
D 2
.SH HISTORY
Both code and manual page were
written at U of T.
They are intended to be compatible with the Bell V8 \fIregexp\fR(3),
E 2
I 2
.Sh SEE ALSO
.Xr ed 1 ,
.Xr ex 1 ,
.Xr expr 1 ,
.Xr egrep 1 ,
.Xr fgrep 1 ,
.Xr grep 1 ,
.Xr regex 3
.Sh HISTORY
Both code and manual page for
.Fn regcomp ,
.Fn regexec ,
.Fn regsub ,
and
.Fn regerror
were written at the University of Toronto
and appeared in
.Bx 4.3 tahoe .
They are intended to be compatible with the Bell V8
.Xr regexp 3 ,
E 2
but are not derived from Bell code.
D 2
.SH BUGS
E 2
I 2
.Sh BUGS
E 2
Empty branches and empty regular expressions are not portable to V8.
D 2
.PP
E 2
I 2
.Pp
E 2
The restriction against
applying `*' or `+' to a possibly-null operand is an artifact of the
simplistic implementation.
D 2
.PP
Does not support \fIegrep\fR's newline-separated branches;
neither does the V8 \fIregexp\fR(3), though.
.PP
E 2
I 2
.Pp
Does not support
.Xr egrep Ns 's
newline-separated branches;
neither does the V8
.Xr regexp 3 ,
though.
.Pp
E 2
Due to emphasis on
compactness and simplicity,
it's not strikingly fast.
It does give special attention to handling simple cases quickly.
E 1
