/* A lexical scanner generated by flex */

/* scanner skeleton version:
 *
 * $Header: flex/RCS/flex.skel,v 2.13 90/05/26 17:24:13 vern Exp $
 *
 *	@(#)lex.skel	5.5 (Berkeley) 5/6/91
 */

#define FLEX_SCANNER

#include <stdio.h>
#include <stdlib.h>

#ifdef __STDC__

#define YY_USE_PROTOS
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "awk.lx.l"
#define INITIAL 0
#define A 1
#define str 2
#define sc 3
#define reg 4
#define comment 5
# line 4 "awk.lx.l"
/*
Copyright (c) 1984, 19885, 1986, 1987 AT&T
	All Rights Reserved

THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.

The copyright notice above does not evidence any
actual or intended publication of such source code.
*/

#include	"awk.h"
#include	"y.tab.h"

#undef	input	/* defeat lex */
#undef	unput

extern YYSTYPE	yylval;
extern int	infunc;

int	lineno	= 1;
int	bracecnt = 0;
int	brackcnt  = 0;
int	parencnt = 0;
#define DEBUG
#ifdef	DEBUG
#	define	RET(x)	{if(dbg)printf("lex %s [%s]\n", tokname(x), yytext); return(x); }
#else
#	define	RET(x)	return(x)
#endif

#define	CADD	cbuf[clen++] = yytext[0]; \
		if (clen >= CBUFLEN-1) { \
			ERROR "string/reg expr %.10s... too long", cbuf SYNTAX; \
			BEGIN A; \
		}

uchar	cbuf[CBUFLEN];
uchar	*s;
int	clen, cflag;
# line 50 "awk.lx.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 98
typedef int yy_state_type;
static const short int yy_accept[250] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   98,   97,   80,    3,    1,   12,   76,    2,
       37,   80,   80,   79,   80,   80,   80,   80,   80,   39,
        4,   16,   31,   20,   75,   75,   75,   75,   80,   78,
       33,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   80,   77,   14,
       96,   86,   85,   96,   84,   82,   83,   84,    3,   13,
       15,    2,   34,   36,   36,   28,   10,   32,   26,   22,
       24,   23,   25,   39,   27,   39,   39,    0,   17,   18,
       19,   21,   75,   75,   75,   38,    5,   29,   75,   75,

       75,   75,   75,   42,   75,   75,   75,   75,   75,   75,
       43,   58,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   11,   95,   87,
       94,   93,   92,   90,   88,   91,   89,   81,   36,   35,
       30,   39,    0,   39,   75,    7,   75,   75,   75,   75,
       68,   75,   75,   75,   65,   41,   75,   75,   75,   75,
       64,   75,   63,   75,   75,   75,   75,   75,   67,   75,
       75,   75,   75,   54,   75,   75,   75,   75,   94,   75,
       75,   75,   75,   75,   75,   44,   46,    8,   75,   55,
       75,   75,   75,   45,   75,   71,   75,   75,   75,   66,

       75,   75,   75,   75,   75,   75,   94,    6,   69,   47,
       60,   75,   75,   75,   75,   56,   75,   57,   49,   75,
       52,   75,   72,   75,   75,   75,   75,   40,   75,   61,
       75,   75,   62,   50,    9,   75,   53,   70,   75,   75,
       75,   75,   59,   51,   74,   73,   48,    8,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,    1,
       10,   11,   12,    1,   13,   14,   15,   16,   16,   17,
       16,   16,   16,   16,   16,   16,   16,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   22,   24,   25,   26,
       27,   22,   28,   22,   22,   22,   22,   29,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
        1,   30,   31,   32,   22,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   22,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   22,   53,   54,
       55,   22,    1,   56,   57,   58,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const short int yy_base[259] =
    {   0,
        0,    0,    0,    0,   56,   57,    0,    0,   60,   61,
        0,    0,  295,  296,  296,  292,  296,   45,  296,    0,
       50,  273,  283,  296,   57,   58,   60,   55,  271,   67,
      296,  270,  269,   68,    0,  263,  258,  260,  282,  296,
      264,  232,  233,   39,   56,   51,   49,   59,   61,   61,
      248,  243,  230,   75,   69,  232,  237,  220,  296,  296,
      296,  296,  296,  120,  296,  296,  296,    0,  273,  296,
      296,    0,   97,    0,  248,  296,  296,  253,  296,  296,
      296,  296,  296,  103,  296,  106,  116,  122,  296,  296,
      296,  296,    0,  245,  247,    0,  296,  296,  237,  232,

      222,   24,  224,    0,  216,  101,  216,  219,  212,  210,
        0,   64,  216,  221,  208,  204,  216,  211,  204,  209,
      102,  204,  219,  217,  200,  103,  208,  296,  296,  296,
      110,  296,  296,  296,  296,  296,  296,  296,    0,    0,
      296,  143,  140,  145,  220,    0,  202,  213,  195,  193,
        0,  206,  205,  190,    0,    0,  205,  196,  204,  200,
        0,  197,    0,  200,  183,  188,  196,  179,    0,  189,
      188,  177,  182,  176,  174,  178,  176,  179,  147,  192,
      203,  177,  181,  176,  165,    0,    0,  164,  173,    0,
      159,  161,  171,    0,  159,    0,  160,  157,  162,    0,

      170,  154,  167,  150,  155,  164,  296,    0,    0,    0,
        0,  155,  162,  156,  149,    0,  151,    0,  141,  133,
        0,  126,    0,  127,  131,  137,  136,    0,  120,    0,
      124,  130,    0,    0,    0,  128,    0,    0,  103,  100,
      110,   99,    0,    0,    0,    0,    0,    0,  296,  180,
      183,  186,  189,  126,  108,  192,  195,   94
    } ;

static const short int yy_def[259] =
    {   0,
      250,  250,  249,    3,  251,  251,  250,  250,  252,  252,
      250,  250,  249,  249,  249,  249,  249,  249,  249,  253,
      254,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  255,  255,  255,  255,  249,  249,
      249,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  249,  249,  249,
      249,  249,  249,  256,  249,  249,  249,  257,  249,  249,
      249,  253,  249,  258,  258,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  255,  255,  255,  255,  249,  249,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  258,  258,
      249,  249,  249,  249,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  249,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  249,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,    0,  249,
      249,  249,  249,  249,  249,  249,  249,  249
    } ;

static const short int yy_nxt[355] =
    {   0,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   35,   36,   35,   37,   35,   35,   35,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   35,
       49,   35,   50,   51,   52,   35,   53,   35,   54,   55,
       56,   35,   57,   35,   35,   58,   59,   60,   62,   62,
       63,   63,   66,   66,   70,   73,   73,   78,  150,   80,
       84,   84,   82,  151,   67,   67,   79,   81,   75,   83,
       86,  101,   87,   87,  102,   64,   64,   91,   92,   68,
       68,   88,  103,  105,  107,  109,  139,  113,  111,  160,

      108,  104,   71,   88,  106,  112,  114,  118,  110,  120,
       93,  119,   73,   73,  161,  121,  122,  123,   84,   84,
      124,  142,  142,  125,  130,  179,  179,   88,   74,   86,
       88,   87,   87,  143,  143,  131,  131,  144,  144,   88,
       88,  154,   88,  248,  170,  176,  247,  155,  246,  132,
      171,  245,   88,  133,  177,  144,  144,  134,  142,  142,
      144,  144,  207,  207,  135,  244,  243,   88,  136,  242,
      137,  241,  240,  239,  238,  237,  236,  235,  234,   88,
       14,   14,   14,   61,   61,   61,   65,   65,   65,   72,
      233,   72,  129,  232,  129,  138,  231,  138,  230,  229,

      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  178,  175,
      174,  173,  172,  169,  168,  167,  166,  165,  164,  163,
      162,  159,  158,  157,  156,  153,  152,  149,  148,  147,
      146,  145,  141,  140,   69,  128,  127,  126,  117,  116,
      115,  100,   99,   98,   97,   96,   95,   94,   90,   89,
       85,   77,   76,   69,  249,   13,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249
    } ;

static const short int yy_chk[355] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    6,
        5,    6,    9,   10,   18,   21,   21,   25,  102,   26,
       28,   28,   27,  102,    9,   10,   25,   26,   21,   27,
       30,   44,   30,   30,   44,    5,    6,   34,   34,    9,
       10,   30,   45,   46,   47,   48,  258,   50,   49,  112,

       47,   45,   18,   30,   46,   49,   50,   54,   48,   55,
      255,   54,   73,   73,  112,   55,   55,   55,   84,   84,
       55,   86,   86,   55,   64,  131,  131,   84,  254,   87,
       86,   87,   87,   88,   88,   64,   64,   88,   88,   84,
       87,  106,   86,  242,  121,  126,  241,  106,  240,   64,
      121,  239,   87,   64,  126,  143,  143,   64,  142,  142,
      144,  144,  179,  179,   64,  236,  232,  142,   64,  231,
       64,  229,  227,  226,  225,  224,  222,  220,  219,  142,
      250,  250,  250,  251,  251,  251,  252,  252,  252,  253,
      217,  253,  256,  215,  256,  257,  214,  257,  213,  212,

      206,  205,  204,  203,  202,  201,  199,  198,  197,  195,
      193,  192,  191,  189,  188,  185,  184,  183,  182,  181,
      180,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      168,  167,  166,  165,  164,  162,  160,  159,  158,  157,
      154,  153,  152,  150,  149,  148,  147,  145,  127,  125,
      124,  123,  122,  120,  119,  118,  117,  116,  115,  114,
      113,  110,  109,  108,  107,  105,  103,  101,  100,   99,
       95,   94,   78,   75,   69,   58,   57,   56,   53,   52,
       51,   43,   42,   41,   39,   38,   37,   36,   33,   32,
       29,   23,   22,   16,   13,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;


	switch (yybgin-yysvec-1) {	/* witchcraft */
	case 0:
		BEGIN A;
		break;
	case sc:
		BEGIN A;
		RET('}');
	}


    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 250 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 249 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 60 "awk.lx.l"
{ lineno++; RET(NL); }
	YY_BREAK
case 2:
# line 61 "awk.lx.l"
{ lineno++; RET(NL); }	/* strip comment lines */
	YY_BREAK
case 3:
# line 62 "awk.lx.l"
{ ; }
	YY_BREAK
case 4:
# line 63 "awk.lx.l"
{ RET(';'); }
	YY_BREAK
case 5:
# line 65 "awk.lx.l"
{ lineno++; }
	YY_BREAK
case 6:
# line 66 "awk.lx.l"
{ RET(XBEGIN); }
	YY_BREAK
case 7:
# line 67 "awk.lx.l"
{ RET(XEND); }
	YY_BREAK
case 8:
# line 68 "awk.lx.l"
{ if (infunc) ERROR "illegal nested function" SYNTAX; RET(FUNC); }
	YY_BREAK
case 9:
# line 69 "awk.lx.l"
{ if (!infunc) ERROR "return not in function" SYNTAX; RET(RETURN); }
	YY_BREAK
case 10:
# line 70 "awk.lx.l"
{ RET(AND); }
	YY_BREAK
case 11:
# line 71 "awk.lx.l"
{ RET(BOR); }
	YY_BREAK
case 12:
# line 72 "awk.lx.l"
{ RET(NOT); }
	YY_BREAK
case 13:
# line 73 "awk.lx.l"
{ yylval.i = NE; RET(NE); }
	YY_BREAK
case 14:
# line 74 "awk.lx.l"
{ yylval.i = MATCH; RET(MATCHOP); }
	YY_BREAK
case 15:
# line 75 "awk.lx.l"
{ yylval.i = NOTMATCH; RET(MATCHOP); }
	YY_BREAK
case 16:
# line 76 "awk.lx.l"
{ yylval.i = LT; RET(LT); }
	YY_BREAK
case 17:
# line 77 "awk.lx.l"
{ yylval.i = LE; RET(LE); }
	YY_BREAK
case 18:
# line 78 "awk.lx.l"
{ yylval.i = EQ; RET(EQ); }
	YY_BREAK
case 19:
# line 79 "awk.lx.l"
{ yylval.i = GE; RET(GE); }
	YY_BREAK
case 20:
# line 80 "awk.lx.l"
{ yylval.i = GT; RET(GT); }
	YY_BREAK
case 21:
# line 81 "awk.lx.l"
{ yylval.i = APPEND; RET(APPEND); }
	YY_BREAK
case 22:
# line 82 "awk.lx.l"
{ yylval.i = INCR; RET(INCR); }
	YY_BREAK
case 23:
# line 83 "awk.lx.l"
{ yylval.i = DECR; RET(DECR); }
	YY_BREAK
case 24:
# line 84 "awk.lx.l"
{ yylval.i = ADDEQ; RET(ASGNOP); }
	YY_BREAK
case 25:
# line 85 "awk.lx.l"
{ yylval.i = SUBEQ; RET(ASGNOP); }
	YY_BREAK
case 26:
# line 86 "awk.lx.l"
{ yylval.i = MULTEQ; RET(ASGNOP); }
	YY_BREAK
case 27:
# line 87 "awk.lx.l"
{ yylval.i = DIVEQ; RET(ASGNOP); }
	YY_BREAK
case 28:
# line 88 "awk.lx.l"
{ yylval.i = MODEQ; RET(ASGNOP); }
	YY_BREAK
case 29:
# line 89 "awk.lx.l"
{ yylval.i = POWEQ; RET(ASGNOP); }
	YY_BREAK
case 30:
# line 90 "awk.lx.l"
{ yylval.i = POWEQ; RET(ASGNOP); }
	YY_BREAK
case 31:
# line 91 "awk.lx.l"
{ yylval.i = ASSIGN; RET(ASGNOP); }
	YY_BREAK
case 32:
# line 92 "awk.lx.l"
{ RET(POWER); }
	YY_BREAK
case 33:
# line 93 "awk.lx.l"
{ RET(POWER); }
	YY_BREAK
case 34:
# line 95 "awk.lx.l"
{ yylval.cp = fieldadr(atoi(yytext+1)); RET(FIELD); }
	YY_BREAK
case 35:
# line 96 "awk.lx.l"
{ unputstr("(NF)"); return(INDIRECT); }
	YY_BREAK
case 36:
# line 97 "awk.lx.l"
{ int c, n;
		  c = input(); unput(c);
		  if (c == '(' || c == '[' || infunc && (n=isarg(yytext+1)) >= 0) {
			unputstr(yytext+1);
			return(INDIRECT);
		  } else {
			yylval.cp = setsymtab(yytext+1,"",0.0,STR|NUM,symtab);
			RET(IVAR);
		  }
		}
	YY_BREAK
case 37:
# line 107 "awk.lx.l"
{ RET(INDIRECT); }
	YY_BREAK
case 38:
# line 108 "awk.lx.l"
{ yylval.cp = setsymtab(yytext, "", 0.0, NUM, symtab); RET(VARNF); }
	YY_BREAK
case 39:
# line 110 "awk.lx.l"
{
		  yylval.cp = setsymtab(yytext, tostring(yytext), atof(yytext), CON|NUM, symtab);
		  RET(NUMBER); }
	YY_BREAK
case 40:
# line 114 "awk.lx.l"
{ RET(WHILE); }
	YY_BREAK
case 41:
# line 115 "awk.lx.l"
{ RET(FOR); }
	YY_BREAK
case 42:
# line 116 "awk.lx.l"
{ RET(DO); }
	YY_BREAK
case 43:
# line 117 "awk.lx.l"
{ RET(IF); }
	YY_BREAK
case 44:
# line 118 "awk.lx.l"
{ RET(ELSE); }
	YY_BREAK
case 45:
# line 119 "awk.lx.l"
{ RET(NEXT); }
	YY_BREAK
case 46:
# line 120 "awk.lx.l"
{ RET(EXIT); }
	YY_BREAK
case 47:
# line 121 "awk.lx.l"
{ RET(BREAK); }
	YY_BREAK
case 48:
# line 122 "awk.lx.l"
{ RET(CONTINUE); }
	YY_BREAK
case 49:
# line 123 "awk.lx.l"
{ yylval.i = PRINT; RET(PRINT); }
	YY_BREAK
case 50:
# line 124 "awk.lx.l"
{ yylval.i = PRINTF; RET(PRINTF); }
	YY_BREAK
case 51:
# line 125 "awk.lx.l"
{ yylval.i = SPRINTF; RET(SPRINTF); }
	YY_BREAK
case 52:
# line 126 "awk.lx.l"
{ yylval.i = SPLIT; RET(SPLIT); }
	YY_BREAK
case 53:
# line 127 "awk.lx.l"
{ RET(SUBSTR); }
	YY_BREAK
case 54:
# line 128 "awk.lx.l"
{ yylval.i = SUB; RET(SUB); }
	YY_BREAK
case 55:
# line 129 "awk.lx.l"
{ yylval.i = GSUB; RET(GSUB); }
	YY_BREAK
case 56:
# line 130 "awk.lx.l"
{ RET(INDEX); }
	YY_BREAK
case 57:
# line 131 "awk.lx.l"
{ RET(MATCHFCN); }
	YY_BREAK
case 58:
# line 132 "awk.lx.l"
{ RET(IN); }
	YY_BREAK
case 59:
# line 133 "awk.lx.l"
{ RET(GETLINE); }
	YY_BREAK
case 60:
# line 134 "awk.lx.l"
{ RET(CLOSE); }
	YY_BREAK
case 61:
# line 135 "awk.lx.l"
{ RET(DELETE); }
	YY_BREAK
case 62:
# line 136 "awk.lx.l"
{ yylval.i = FLENGTH; RET(BLTIN); }
	YY_BREAK
case 63:
# line 137 "awk.lx.l"
{ yylval.i = FLOG; RET(BLTIN); }
	YY_BREAK
case 64:
# line 138 "awk.lx.l"
{ yylval.i = FINT; RET(BLTIN); }
	YY_BREAK
case 65:
# line 139 "awk.lx.l"
{ yylval.i = FEXP; RET(BLTIN); }
	YY_BREAK
case 66:
# line 140 "awk.lx.l"
{ yylval.i = FSQRT; RET(BLTIN); }
	YY_BREAK
case 67:
# line 141 "awk.lx.l"
{ yylval.i = FSIN; RET(BLTIN); }
	YY_BREAK
case 68:
# line 142 "awk.lx.l"
{ yylval.i = FCOS; RET(BLTIN); }
	YY_BREAK
case 69:
# line 143 "awk.lx.l"
{ yylval.i = FATAN; RET(BLTIN); }
	YY_BREAK
case 70:
# line 144 "awk.lx.l"
{ yylval.i = FSYSTEM; RET(BLTIN); }
	YY_BREAK
case 71:
# line 145 "awk.lx.l"
{ yylval.i = FRAND; RET(BLTIN); }
	YY_BREAK
case 72:
# line 146 "awk.lx.l"
{ yylval.i = FSRAND; RET(BLTIN); }
	YY_BREAK
case 73:
# line 147 "awk.lx.l"
{ yylval.i = FTOUPPER; RET(BLTIN); }
	YY_BREAK
case 74:
# line 148 "awk.lx.l"
{ yylval.i = FTOLOWER; RET(BLTIN); }
	YY_BREAK
case 75:
# line 150 "awk.lx.l"
{ int n, c;
		  c = input(); unput(c);	/* look for '(' */
		  if (c != '(' && infunc && (n=isarg(yytext)) >= 0) {
			yylval.i = n;
			RET(ARG);
		  } else {
			yylval.cp = setsymtab(yytext,"",0.0,STR|NUM,symtab);
			if (c == '(') {
				RET(CALL);
			} else {
				RET(VAR);
			}
		  }
		}
	YY_BREAK
case 76:
# line 164 "awk.lx.l"
{ BEGIN str; clen = 0; }
	YY_BREAK
case 77:
# line 166 "awk.lx.l"
{ if (--bracecnt < 0) ERROR "extra }" SYNTAX; BEGIN sc; RET(';'); }
	YY_BREAK
case 78:
# line 167 "awk.lx.l"
{ if (--brackcnt < 0) ERROR "extra ]" SYNTAX; RET(']'); }
	YY_BREAK
case 79:
# line 168 "awk.lx.l"
{ if (--parencnt < 0) ERROR "extra )" SYNTAX; RET(')'); }
	YY_BREAK
case 80:
# line 170 "awk.lx.l"
{ if (yytext[0] == '{') bracecnt++;
		  else if (yytext[0] == '[') brackcnt++;
		  else if (yytext[0] == '(') parencnt++;
		  RET(yylval.i = yytext[0]); /* everything else */ }
	YY_BREAK
case 81:
# line 175 "awk.lx.l"
{ cbuf[clen++] = '\\'; cbuf[clen++] = yytext[1]; }
	YY_BREAK
case 82:
# line 176 "awk.lx.l"
{ ERROR "newline in regular expression %.10s...", cbuf SYNTAX; lineno++; BEGIN A; }
	YY_BREAK
case 83:
# line 177 "awk.lx.l"
{ BEGIN A;
		  cbuf[clen] = 0;
		  yylval.s = tostring(cbuf);
		  unput('/');
		  RET(REGEXPR); }
	YY_BREAK
case 84:
# line 182 "awk.lx.l"
{ CADD; }
	YY_BREAK
case 85:
# line 184 "awk.lx.l"
{ BEGIN A;
		  cbuf[clen] = 0; s = tostring(cbuf);
		  cbuf[clen] = ' '; cbuf[++clen] = 0;
		  yylval.cp = setsymtab(cbuf, s, 0.0, CON|STR, symtab);
		  RET(STRING); }
	YY_BREAK
case 86:
# line 189 "awk.lx.l"
{ ERROR "newline in string %.10s...", cbuf SYNTAX; lineno++; BEGIN A; }
	YY_BREAK
case 87:
# line 190 "awk.lx.l"
{ cbuf[clen++] = '"'; }
	YY_BREAK
case 88:
# line 191 "awk.lx.l"
{ cbuf[clen++] = '\n'; }
	YY_BREAK
case 89:
# line 192 "awk.lx.l"
{ cbuf[clen++] = '\t'; }
	YY_BREAK
case 90:
# line 193 "awk.lx.l"
{ cbuf[clen++] = '\f'; }
	YY_BREAK
case 91:
# line 194 "awk.lx.l"
{ cbuf[clen++] = '\r'; }
	YY_BREAK
case 92:
# line 195 "awk.lx.l"
{ cbuf[clen++] = '\b'; }
	YY_BREAK
case 93:
# line 196 "awk.lx.l"
{ cbuf[clen++] = '\\'; }
	YY_BREAK
case 94:
# line 197 "awk.lx.l"
{ int n;
		  sscanf(yytext+1, "%o", &n); cbuf[clen++] = n; }
	YY_BREAK
case 95:
# line 199 "awk.lx.l"
{ cbuf[clen++] = yytext[1]; }
	YY_BREAK
case 96:
# line 200 "awk.lx.l"
{ CADD; }
	YY_BREAK
case 97:
# line 202 "awk.lx.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(A):
case YY_STATE_EOF(str):
case YY_STATE_EOF(sc):
case YY_STATE_EOF(reg):
case YY_STATE_EOF(comment):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 250 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 250 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 249);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 202 "awk.lx.l"


startreg()
{
	BEGIN reg;
	clen = 0;
}

/* input() and unput() are transcriptions of the standard lex
   macros for input and output with additions for error message
   printing.  God help us all if someone changes how lex works.
*/

uchar	ebuf[300];
uchar	*ep = ebuf;

input()
{
	register int c;
	extern uchar *lexprog;

	if (yysptr > yysbuf)
		c = U(*--yysptr);
	else if (yyin == NULL)
		c = *lexprog++;
	else
		c = getc(yyin);
	if (c == '\n')
		yylineno++;
	else if (c == EOF)
		c = 0;
	if (ep >= ebuf + sizeof ebuf)
		ep = ebuf;
	return *ep++ = c;
}

unput(c)
{
	yytchar = c;
	if (yytchar == '\n')
		yylineno--;
	*yysptr++ = yytchar;
	if (--ep < ebuf)
		ep = ebuf + sizeof(ebuf) - 1;
}


unputstr(s)
	char *s;
{
	int i;

	for (i = strlen(s)-1; i >= 0; i--)
		unput(s[i]);
}
