h00432
s 00002/00003/00156
d D 8.2 94/04/18 07:44:22 bostic 9 8
c typo
e
s 00002/00002/00157
d D 8.1 93/06/06 16:24:19 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00087/00083/00072
d D 6.5 91/08/09 16:53:53 cael 7 6
c mdoc version three
e
s 00002/00002/00153
d D 6.4 91/04/20 16:15:08 bostic 6 5
c wrong copyright notice!
e
s 00005/00004/00150
d D 6.3 91/04/18 18:07:52 bostic 5 4
c new copyright; att/bsd/shared
e
s 00008/00004/00146
d D 6.2 90/06/24 19:17:06 cael 4 3
c converted man page
e
s 00001/00001/00149
d D 6.1 85/04/29 17:57:39 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00058/00021/00092
d D 5.1 85/04/29 17:57:26 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00113/00000/00000
d D 4.1 85/04/29 17:57:16 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1990 The Regents of the University of California.
E 6
I 6
D 8
.\" Copyright (c) 1985 The Regents of the University of California.
E 6
.\" All rights reserved.
E 8
I 8
D 9
.\" Copyright (c) 1985, 1993
E 9
I 9
.\" Copyright (c) 1985, 1993, 1994
E 9
.\"	The Regents of the University of California.  All rights reserved.
E 8
E 5
E 4
.\"
I 4
D 5
.\"     %W% (Berkeley) %G%
E 5
I 5
D 6
.\" %sccs.include.redist.roff%
E 6
I 6
.\" %sccs.include.proprietary.roff%
E 6
.\"
.\"	%W% (Berkeley) %G%
E 5
.\"
E 4
D 2
.TH SPELL 1 
E 2
I 2
D 3
.TH SPELL 1 "12 September 1983"
E 3
I 3
D 7
.TH SPELL 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
spell, spellin, spellout \- find spelling errors
.SH SYNOPSIS
.B spell
D 2
[ option ] ...
[ file ] ...
E 2
I 2
[
.B \-v
] [
.B \-b
] [
.B \-x
] [
.B \-d
hlist ] [
.B \-s
hstop ] [
.B \-h
spellhist
] [ file ] ...
E 2
.PP
.B spellin
[ list ]
.PP
.B spellout
[
.B \-d
] list
.SH DESCRIPTION
.I Spell
E 7
I 7
.Dd %Q%
.Dt SPELL 1
.Os ATT 7th
.Sh NAME
.Nm spell ,
.Nm spellin ,
.Nm spellout
.Nd find spelling errors
.Sh SYNOPSIS
.Nm spell
.Op Fl v
.Op Fl b
.Op Fl x
.Op Fl d Ar hlist
.Op Fl s Ar hstop
.Op Fl h Ar spellhist
.Op Ar file
.Ar ...
.Nm spellin
.Op Ar list
.Nm spellout
.Op Fl d
Ar list
.Sh DESCRIPTION
.Nm Spell
E 7
collects words from the named documents,
and looks them up in a spelling list.
Words that neither occur among nor are derivable
(by applying certain inflections,
prefixes or suffixes) from words in the spelling list
are printed on the standard output.
If no files are named,
words are collected from the standard input.
D 7
.PP
.I Spell
E 7
I 7
.Pp
.Nm Spell
E 7
ignores most
D 7
.I troff,
.I tbl
E 7
I 7
.Xr troff 1 ,
.Xr tbl 1
E 7
and
D 7
.IR  eqn (1)
E 7
I 7
.Xr eqn 1
E 7
constructions.
D 7
.PP
E 7
I 7
.Pp
E 7
Under the
D 7
.B \-v
E 7
I 7
.Fl v
E 7
option, all words not literally in the spelling list are printed,
and plausible derivations from spelling list words are indicated.
D 7
.PP
E 7
I 7
.Pp
E 7
Under the 
D 7
.B \-b
E 7
I 7
.Fl b
E 7
option, British spelling is checked.
Besides preferring
D 7
.ft I
centre, colour, speciality, travelled,
.ft R
E 7
I 7
.Em centre , colour , speciality , travelled ,
E 7
etc.,
this option insists upon
D 7
.I -ise
E 7
I 7
.Fl ise
E 7
in words like
D 7
.I standardise,
E 7
I 7
.Em standardise,
E 7
D 2
Fowler and the OED to the contrary
notwithstanding.
E 2
I 2
Fowler and the OED to the contrary notwithstanding.
E 2
D 7
.PP
E 7
I 7
.Pp
E 7
Under the 
D 7
.B \-x
E 7
I 7
.Fl x
E 7
option, every plausible stem is printed with `=' for each word.
D 7
.PP
E 7
I 7
.Pp
E 7
D 2
The spelling list is based on many sources,
and while more haphazard than an ordinary
dictionary, is also more effective in respect to
E 2
I 2
The spelling list is based on many sources.
While it is more haphazard than an ordinary
dictionary, it is also more effective with
E 2
proper names and popular technical words.
Coverage of
the specialized vocabularies of biology,
medicine and chemistry is light.
D 7
.PP
E 7
I 7
.Pp
E 7
D 2
Pertinent auxiliary files may be specified by
name arguments, indicated below with their
default settings.
E 2
I 2
The auxiliary files used for the spelling list,
stop list, and history file may be specified by
arguments following the
D 7
.BR \-d ,
.BR \-s ,
E 7
I 7
.Fl d ,
.Fl s ,
E 7
and
D 7
.B \-h
E 7
I 7
.Fl h
E 7
options.
The default files are indicated below.
E 2
Copies of all output
D 2
are accumulated in the history file.
E 2
I 2
may be accumulated in the history file.
E 2
The stop list filters out misspellings (e.g. thier=thy\-y+ier)
that would otherwise pass.
D 7
.PP
E 7
I 7
.Pp
E 7
Two routines help maintain the hash lists used by
D 7
.I spell.
E 7
I 7
.Nm spell.
E 7
D 2
Both expect a list of words, one per line,
E 2
I 2
Both expect a set of words, one per line,
E 2
from the standard input.
D 7
.I Spellin
E 7
I 7
.Nm Spellin
E 7
D 2
adds the words on the standard input to the
E 2
I 2
combines the words from the standard input and the
E 2
preexisting
D 7
.I list
E 7
I 7
.Ar list
E 7
D 2
and places a new list on the standard output.
E 2
I 2
file and places a new list on the standard output.
E 2
If no 
D 7
.I list
E 7
I 7
.Ar list
E 7
D 2
is specified, the new list is created from scratch.
E 2
I 2
file is specified, the new list is created from scratch.
E 2
D 7
.I Spellout
E 7
I 7
.Nm Spellout
E 7
D 2
looks up each word in the standard input and prints
E 2
I 2
looks up each word from the standard input and prints
E 2
on the standard output
those that are missing from (or present on, with
option
D 7
.BR \-d )
E 7
I 7
.Fl d )
E 7
D 2
the hash list.
E 2
I 2
the hashed
D 7
.I list
E 7
I 7
.Ar list
E 7
file.
For example, to verify that
D 7
.I hookey
E 7
I 7
.Em hookey
E 7
is not on the default spelling list, add it to your own
private list, and then use it with
D 7
.IR spell ,
.PP
.RS
.nf
E 7
I 7
.Nm spell ,
.Pp
.Bd -literal -offset indent -compact
E 7
D 4
echo  hookey  |  spellout  /usr/dict/hlista
echo  hookey  |  spellin  /usr/dict/hlista  >  myhlist
E 4
I 4
echo  hookey  |  spellout  /usr/share/dict/hlista
echo  hookey  |  spellin  /usr/share/dict/hlista  >  myhlist
E 4
spell  \-d  myhlist  huckfinn
D 7
.RE
E 2
.SH FILES
D 2
D=/usr/dict/hlist[ab]: hashed spelling lists, American & British
E 2
I 2
/usr/dict/hlist[ab]	hashed spelling lists, American & British, default for
.B \-d
E 2
.br
D 2
S=/usr/dict/hstop: hashed stop list
E 2
I 2
/usr/dict/hstop		hashed stop list, default for
.B \-s
E 2
.br
D 2
H=/usr/dict/spellhist: history file
E 2
I 2
/dev/null		history file, default for
.B \-h
E 2
.br
I 2
/tmp/spell.$$\(**		temporary files
.br
E 2
D 4
/usr/lib/spell
E 4
I 4
/usr/libexec/spell
E 4
.br
I 2
.SH SEE ALSO
E 2
deroff(1), sort(1), tee(1), sed(1)
.SH BUGS
E 7
I 7
.Ed
.Sh FILES
.Bl -tag -width /usr/dict/hlist[ab]xx -compact
.It Pa /usr/dict/hlist[ab]
Hashed spelling lists, American & British, default for
.Fl d .
.It Pa /usr/dict/hstop
Hashed stop list, default for
.Fl s .
.It Pa /dev/null
History file, default for
.Fl h .
.It Pa /tmp/spell.$$\(**
Temporary files.
.It Pa /usr/libexec/spell
D 9
Binary exectuted by the
shell script
E 9
I 9
Binary executed by the shell script
E 9
.Pa /usr/bin/spell .
.El
.Sh SEE ALSO
.Xr deroff 1 ,
.Xr sort 1 ,
.Xr tee 1 ,
.Xr sed 1
.Sh BUGS
E 7
The spelling list's coverage is uneven;
new installations will probably wish to 
monitor the output for several months to gather
local additions.
D 7
.br
E 7
I 7
.Pp
E 7
British spelling was done by an American.
I 7
.Sh HISTORY
The
.Nm spell
command appeared in
.At v6 .
E 7
E 1
