#!/bin/sh

INTERFACE=sl3

while [ $# -ge 1 ]; do
	ifconfig ${INTERFACE}
	case $1 in
		up)
			ifconfig ${INTERFACE} up
			;;

		down)
			ifconfig ${INTERFACE} down
			;;

		add)
			ifconfig ${INTERFACE} vangogh 150.138.100.1
			;;

		adds)
			route add 192.107.121.0  150.138.100.1
			;;

		changes)
			route change 192.107.121.0 150.138.100.1
			;;

		delete|del)
			ifconfig ${INTERFACE} delete vangogh 150.138.100.1
			;;

		deletes|dels)
			route delete 192.107.121.0
			;;

		dz)
			ifconfig ${INTERFACE} delete 0.0.0.0 0.0.0.0
			;;
	
		*)
			echo $1"?"
			;;
	esac
	shift
done

ifconfig ${INTERFACE}
