h08000
s 00002/00002/00119
d D 8.1 93/06/06 16:02:33 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00023/00036/00098
d D 6.7 91/08/08 18:17:35 cael 10 9
c mdoc version three
e
s 00005/00005/00129
d D 6.6 91/04/18 16:31:15 bostic 9 8
c new copyright; att/bsd/shared
e
s 00002/00000/00132
d D 6.5 91/03/14 00:25:28 cael 8 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00132
d R 6.5 91/03/13 20:36:55 cael 7 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00001/00131
d D 6.4 90/07/24 22:50:20 cael 6 5
c .Xr botch fix
e
s 00003/00004/00129
d D 6.3 90/06/26 01:00:38 cael 5 4
c converted man page
e
s 00082/00059/00051
d D 6.2 90/06/11 05:59:23 cael 4 3
c converted man page
e
s 00001/00001/00109
d D 6.1 85/04/29 17:51:54 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00004/00003/00106
d D 5.1 85/04/29 17:51:44 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00109/00000/00000
d D 4.1 85/04/29 17:51:35 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 5
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 4
.\"
D 2
.TH PTX 1
E 2
I 2
D 3
.TH PTX 1 "18 January 1983"
E 3
I 3
D 4
.TH PTX 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
ptx \- permuted index
.SH SYNOPSIS
.B ptx
[ option ] ...
[ input [ output ] ]
.SH DESCRIPTION
.I Ptx
E 4
I 4
.\" %sccs.include.redist.man%
E 5
I 5
D 9
.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 9
I 9
D 11
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 9
E 5
.\"
D 9
.\"     %W% (Berkeley) %G%
E 9
I 9
.\" %sccs.include.proprietary.roff%
E 9
.\"
I 8
D 9
.Vx
E 9
I 9
.\"	%W% (Berkeley) %G%
.\"
E 9
D 10
.Vx
E 10
E 8
.Dd %Q%
.Dt PTX 1
.Os ATT 7th
.Sh NAME
.Nm ptx
.Nd permuted index
.Sh SYNOPSIS
.Nm ptx
.Op  option
D 10
\&...
D 6
.Op  input Op  output
E 6
I 6
.Op input [output]
E 10
I 10
.Ar ...
.Op input Op output
E 10
E 6
.Sh DESCRIPTION
.Nm Ptx
E 4
generates a permuted index to file
D 4
.I input
E 4
I 4
.Ar input
E 4
on file
D 4
.I output
E 4
I 4
.Ar output
E 4
(standard input and output default).
It has three phases: the first does the permutation, generating
one line for each keyword in an input line.
The keyword is rotated to the front.
The permuted file is then
sorted.
Finally, the sorted lines are rotated so the keyword
comes at the middle of the page.
D 4
.I Ptx
E 4
I 4
.Nm Ptx
E 4
produces output in the form:
D 4
.br
.IP
\&.xx "tail" "before keyword" "keyword and after" "head"
.LP
E 4
I 4
.Pp
.Dl \&.xx "tail" "before keyword" "keyword and after" "head"
.Pp
E 4
D 10
where .xx may be an
E 10
I 10
where
.Ar \&.xx
may be an
E 10
D 4
.I nroff
E 4
I 4
.Xr nroff 1
E 4
or
D 4
.IR troff (1)
E 4
I 4
.Xr troff  1
E 4
macro
for user-defined formatting.
The
D 4
.I before keyword
E 4
I 4
.Ar before keyword
E 4
and
D 4
.I keyword and after
E 4
I 4
.Ar keyword and after
E 4
fields incorporate as much of the line as will fit
around the keyword when it is printed at the middle of the page.
D 4
.I Tail
E 4
I 4
.Ar Tail
E 4
and
D 4
.I head,
E 4
I 4
.Ar head ,
E 4
at least one of which is an empty string "",
are wrapped-around pieces small enough to fit
in the unused space at the opposite end of the line.
When original text must be discarded, `/' marks the spot.
D 4
.PP
E 4
I 4
.Pp
E 4
The following options can be applied:
D 4
.TP
.BR \-f
E 4
I 4
D 10
.Tw Fl
.Tp Fl f
E 10
I 10
.Bl -tag -width flag
.It Fl f
E 10
E 4
Fold upper and lower case letters for sorting.
D 4
.TP 
.BR \-t
E 4
I 4
D 10
.Tp Fl t
E 10
I 10
.It Fl t
E 10
E 4
Prepare the output for the phototypesetter;
the default line length is 100 characters.
D 4
.TP 
.BI \-w " n"
E 4
I 4
D 10
.Tp Cx Fl w
.Ws
.Ar n
.Cx
E 10
I 10
.It Fl w Ar n 
E 10
E 4
Use the next argument,
D 4
.I n,
E 4
I 4
.Ar n ,
E 4
as the width of the output line.
The default line length is 72 characters.
D 4
.TP
.BI \-g " n"
E 4
I 4
D 10
.Tp Cx Fl g
.Ws
.Ar n
.Cx
E 10
I 10
.It Fl g Ar n 
E 10
E 4
Use the next argument,
D 4
.I n,
E 4
I 4
.Ar n ,
E 4
as the number of characters to allow for each gap
among the four parts of the line as finally printed.
The default gap is 3 characters.
D 4
.TP 
.BR \-o " only"
Use as keywords only the words given in the \fIonly\fR file.
.TP 
.BR \-i " ignore"
E 4
I 4
D 10
.Tp Cx Fl o
.Ws
.Ar only
.Cx
E 10
I 10
.It Fl o Ar only 
E 10
Use as keywords only the words given in the
.Ar only
file.
D 10
.Tp Cx Fl i
.Ws
.Ar ignore
.Cx
E 10
I 10
.It Fl i Ar ignore 
E 10
E 4
Do not use as keywords any words given in the
D 4
.I
E 4
ignore
file.
D 2
If the \fB\-i\fR and \fB\-o\fR options are missing, use /usr/lib/eign
E 2
I 2
D 4
If the \fB\-i\fR and \fB\-o\fR options are missing, use
.I /usr/lib/eign
E 2
as the 
.I
E 4
I 4
If the
.Fl i
and
.Fl o
options are missing, use
.Pa /usr/share/dict/eign
as the
E 4
ignore
file.
D 4
.TP 
.BR \-b " break"
Use the characters in the 
.I
E 4
I 4
D 10
.Tp Cx Fl b
.Ws
.Ar break
.Cx
E 10
I 10
.It Fl b Ar break 
E 10
Use the characters in the
E 4
break
file to separate words.
In any case, tab, newline, and space characters are always used as break characters.
D 4
.TP
.BR \-r
E 4
I 4
D 10
.Tp Fl r
E 10
I 10
.It Fl r
E 10
E 4
Take any leading nonblank characters of each input line to
be a reference identifier (as to a page or chapter)
separate from the text of the line.
Attach that identifier as a 5th field on each output line.
D 4
.PP
E 4
I 4
D 10
.Tp
E 10
I 10
.El
E 10
.Pp
E 4
The index for this manual was generated using
D 4
.I ptx.
.SH FILES
D 2
/bin/sort
E 2
I 2
/usr/bin/sort
E 2
.br
/usr/lib/eign
.SH BUGS
E 4
I 4
.Nm ptx .
.Sh FILES
D 10
.Dw /usr/share/dict.eign
.Di L
.Dp /usr/bin/sort
.Dp /usr/share/dict/eign
.Dp
E 10
I 10
.Bl -tag -width /usr/share/dict.eign -compact
.It /usr/bin/sort
.It /usr/share/dict/eign
.El
E 10
.Sh HISTORY
D 10
.Nm Ptx
appeared in Version 7 AT&T UNIX
E 10
I 10
The
.Nm ptx
command appeared in
.At v7 .
E 10
.Sh BUGS
E 4
Line length counts do not account for overstriking or
proportional spacing.
D 4
.br
E 4
E 1
