h42927
s 00002/00002/00196
d D 8.1 93/06/09 19:24:25 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00005/00198
d D 5.4 93/06/09 19:24:20 bostic 5 3
c fixed the under development line
e
s 00002/00002/00201
d R 8.1 93/06/06 14:08:26 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00099/00076/00104
d D 5.3 91/05/10 14:13:27 cael 3 2
c modc version three
e
s 00007/00000/00173
d D 5.2 90/09/30 21:23:25 bostic 2 1
c forgot to describe effects of multiple selectors
e
s 00173/00000/00000
d D 5.1 90/09/30 20:41:03 bostic 1 0
c break configuration info out of syslogd(8)
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1990 The Regents of the University of California.
E 3
I 3
D 6
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 3
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 3
.\" %sccs.include.redist.man%
E 3
I 3
.\" %sccs.include.redist.roff%
E 3
.\"
D 3
.\"	%W% (Berkeley) %G%
E 3
I 3
.\"     %W% (Berkeley) %G%
E 3
.\"
D 3
.TH SYSLOG.CONF 5 "%Q%"
.UC 7
.SH NAME
syslog.conf \- syslogd configuration file
.SH DESCRIPTION
.I Syslog.conf
is the configuration file for the
.IR syslogd (8)
E 3
I 3
.Dd %Q%
.Dt SYSLOG.CONF 5
.Os
.Sh NAME
.Nm syslog.conf
.Nd
.Xr syslogd 8
configuration file
.Sh DESCRIPTION
The
.Nm syslog.conf
file is the configuration file for the
.Xr syslogd 8
E 3
program.
It consists of lines with two fields: the
D 3
.I selector
E 3
I 3
.Em selector
E 3
field which specifies the types of messages and priorities to which the
line applies, and an
D 3
.I action
E 3
I 3
.Em action
E 3
field which specifies the action to be taken if a message
D 3
.IR syslogd
E 3
I 3
.Xr syslogd
E 3
receives matches the selection criteria.
The
D 3
.I selector
E 3
I 3
.Em selector
E 3
field is separated from the
D 3
.I action
E 3
I 3
.Em action
E 3
field by one or more tab characters.
D 3
.PP
.I Selectors
E 3
I 3
.Pp
The
.Em Selectors
function
E 3
are encoded as a
D 3
.IR facility ,
E 3
I 3
.Em facility ,
E 3
a period (``.''), and a
D 3
.IR level ,
E 3
I 3
.Em level ,
E 3
with no intervening white-space.
Both the
D 3
.I facility
E 3
I 3
.Em facility
E 3
and the
D 3
.I level
E 3
I 3
.Em level
E 3
are case insensitive.
D 3
.PP
E 3
I 3
.Pp
E 3
The
D 3
.I facility
E 3
I 3
.Em facility
E 3
describes the part of the system generating the message, and is one of
the following keywords: auth, authpriv, cron, daemon, kern, lpr, mail,
mark, news, syslog, user, uucp and local0 through local7.
These keywords (with the exception of mark) correspond to the
D 3
similar ``LOG_'' values specified to the
.I openlog
E 3
I 3
similar
.Dq Dv LOG_
values specified to the
.Xr openlog 3
E 3
and
D 3
.I syslog
E 3
I 3
.Xr syslog 3
E 3
library routines.
D 3
.PP
E 3
I 3
.Pp
E 3
The
D 3
.I level
E 3
I 3
.Em level
E 3
describes the severity of the message, and is a keyword from the
following ordered list (higher to lower): emerg, alert, crit, err,
warning, notice and debug.
These keywords correspond to the
D 3
similar ``LOG_'' values specified to the
.I syslog
E 3
I 3
similar
.Pq Dv LOG_
values specified to the
.Xr syslog
E 3
library routine.
D 3
.PP
E 3
I 3
.Pp
E 3
See
D 3
.IR syslog (3)
E 3
I 3
.Xr syslog 3
E 3
for a further descriptions of both the
D 3
.I facility
E 3
I 3
.Em facility
E 3
and
D 3
.I level
E 3
I 3
.Em level
E 3
keywords and their significance.
D 3
.PP
E 3
I 3
.Pp
E 3
If a received message matches the specified
D 3
.I facility
E 3
I 3
.Em facility
E 3
and is of the specified
D 3
.I level
.BR "(or a higher level)" ,
E 3
I 3
.Em level
.Em (or a higher level) ,
E 3
the action specified in the
D 3
.I action
E 3
I 3
.Em action
E 3
field will be taken.
D 3
.PP
E 3
I 3
.Pp
E 3
Multiple
D 3
.I selectors
E 3
I 3
.Em selectors
E 3
may be specified for a single
D 3
.I action
E 3
I 3
.Em action
E 3
by separating them with semicolon (``;'') characters.
I 2
It is important to note, however, that each
D 3
.I selector
E 3
I 3
.Em selector
E 3
can modify the ones preceding it.
E 2
D 3
.PP
E 3
I 3
.Pp
E 3
Multiple
D 3
.I facilities
E 3
I 3
.Em facilities
E 3
may be specified for a single
D 3
.I level
E 3
I 3
.Em level
E 3
by separating them with comma (``,'') characters.
D 3
.PP
E 3
I 3
.Pp
E 3
An asterisk (``*'') can be used to specify all
D 3
.I facilities
E 3
I 3
.Em facilities
E 3
or all
D 3
.IR levels .
.PP
E 3
I 3
.Em levels .
.Pp
E 3
The special
D 3
.I facility
E 3
I 3
.Em facility
E 3
``mark'' receives a message at priority ``info'' every 20 minutes
(see
D 3
.IR syslogd (8)).
E 3
I 3
.Xr syslogd 8 ) .
E 3
This is not enabled by a
D 3
.I facility
E 3
I 3
.Em facility
E 3
field containing an asterisk.
D 3
.PP
E 3
I 3
.Pp
E 3
The special
D 3
.I level
E 3
I 3
.Em level
E 3
``none'' disables a particular
D 3
.IR facility .
.PP
E 3
I 3
.Em facility .
.Pp
E 3
The
D 3
.I action
E 3
I 3
.Em action
E 3
field of each line specifies the action to be taken when the
D 3
.I selector
E 3
I 3
.Em selector
E 3
field selects a message.
There are four forms:
D 3
.IP \(bu 3n
E 3
I 3
.Bl -bullet
.It
E 3
A pathname (beginning with a leading slash).
Selected messages are appended to the file.
D 3
.IP \(bu 3n
E 3
I 3
.It
E 3
A hostname (preceded by an at (``@'') sign).
Selected messages are forwarded to the
D 3
.I syslogd
E 3
I 3
.Xr syslogd
E 3
program on the named host.
D 3
.IP \(bu 3n
E 3
I 3
.It
E 3
A comma separated list of users.
Selected messages are written to those users
if they are logged in.
D 3
.IP \(bu 3n
E 3
I 3
.It
E 3
An asterisk.
Selected messages are written to all logged-in users.
D 3
.PP
E 3
I 3
.El
.Pp
E 3
Blank lines and lines whose first non-blank character is a hash (``#'')
character are ignored.
D 3
.SH EXAMPLES
.PP
E 3
I 3
.Sh EXAMPLES
.Pp
E 3
A configuration file might appear as follows:
D 3
.sp
.nf
E 3
I 3
.Bd -literal
E 3
# Log all kernel messages, authentication messages of
# level notice or higher and anything of level err or
# higher to the console.
# Don't log private authentication messages!
*.err;kern.*;auth.notice;authpriv.none	/dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none		/var/log/messages

# The authpriv file has restricted access.
authpriv.*						/var/log/secure

# Log all the mail messages in one place.
mail.*							/var/log/maillog

# Everybody gets emergency messages, plus log them on another
# machine.
*.emerg							*
*.emerg							@arpa.berkeley.edu

# Root and Eric get alert and higher messages.
*.alert							root,eric

# Save mail and news errors of level err and higher in a
# special file.
uucp,news.crit						/var/log/spoolerr
D 3
.fi
.SH FILES
/etc/syslog.conf	\fIsyslogd\fP(8) configuration file
I 2
.SH BUGS
E 3
I 3
.Ed
.Sh FILES
.Bl -tag -width /etc/syslog.conf -compact
.It Pa /etc/syslog.conf
The
.Xr syslogd 8
configuration file.
.El
.Sh BUGS
E 3
The effects of multiple selectors are sometimes not intuitive.
For example ``mail.crit,*.err'' will select ``mail'' facility messages at
the level of ``err'' or higher, not at the level of ``crit'' or higher.
E 2
D 3
.SH "SEE ALSO"
syslog(3), syslogd(8)
E 3
I 3
.Sh SEE ALSO
.Xr syslog 3 ,
.Xr syslogd 8
D 5
.Sh HISTORY
The
.Nm syslog.conf
file format is
.Ud .
E 5
E 3
E 1
