.TH MLDISTRIB 1 "July 21, 1992"
.UC 4
.SH NAME
mldistrib \- redistribute email to a mailing list
.SH SYNOPSIS
.B mldistrib
[
.B \-d
]
listname
ownername
[
.I "sendmail flags"
\&... ]
member...
.SH DESCRIPTION
.PP
Large mailing lists can be implemented using
.I mldistrib
to reprocess the messages.
This changes the envelope to point back at a local list maintainer,
and adjusts some of the message headers.
.PP
The
.I listname
is the name of this list;
it is inserted into a
``Resent-To:'' field in the header.
The
.I ownername
is the address that will get error reports;
by convention, it is
.IB listname -request
(which is itself an alias to a person).
The owner is inserted into the envelope sender
and into
``Resent-From:''
and
``Sender:''
headers.
.PP
When the message is processed, the following headers are deleted:
``Errors-To:'', ``Received:'', ``Via'', ``Resent-*'',
``Return-Path:'', and ``X-Mailer:''.
.PP
After editing the header,
.I mldistrib
calls
.IR sendmail (8)
with the indicated
.I "flags"
from the command line.
It also passes
.B \-f
.I ownername
and
.B \-oi
(to ignore any dots in the body of the message).
.SH EXAMPLE
A typical set of entries in the
.I /etc/aliases
file using
.I mldistrib
might read:
.DS
bind-request:	elan
bind-list:	:include:/etc/sendmail.include/bind.list
bind:		"|/usr/libexec/mldistrib bind bind-request \-odq bind-list"
.DE
In this example, the
.B \-odq
flag is used so that sendmail will queue the message
instead of immediately trying to do delivery;
this is good on especially large lists.
.SH SEE ALSO
.IR sendmail (8)
.SH BUGS
Arguably,
.I mldistrib
should only be changing the envelope fields;
unfortunately,
many extant mail transport systems
improperly handle envelope data.
