h61329
s 00001/00001/00103
d D 8.3 94/04/18 07:29:06 bostic 10 9
c typo
e
s 00001/00002/00103
d D 8.2 93/12/11 23:44:37 mckusick 9 8
c copyediting for Usenix manuals
e
s 00002/00002/00103
d D 8.1 93/06/06 11:47:17 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00005/00102
d D 5.7 92/02/09 08:40:47 pendry 7 6
c merge in new release
e
s 00004/00004/00103
d D 5.6 91/08/05 06:48:19 cael 6 5
c fix history
e
s 00008/00003/00099
d D 5.5 91/05/12 15:59:35 pendry 5 4
c checkpoint for network tape
e
s 00003/00003/00099
d D 5.4 91/04/25 08:28:07 bostic 4 3
c new copyright; att/bsd/shared
e
s 00020/00010/00082
d D 5.3 91/03/17 13:42:18 pendry 3 2
c from amd5.3 alpha11
e
s 00061/00063/00031
d D 5.2 91/03/16 18:11:31 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00094/00000/00000
d D 5.1 90/06/29 12:10:04 mckusick 1 0
c from Jan Pendry
e
u
U
t
T
I 5
.\"
E 5
I 1
D 2
.\" $Id: amq.8,v 5.2 90/06/23 22:21:16 jsp Rel $
E 2
.\" Copyright (c) 1990 Jan-Simon Pendry
.\" Copyright (c) 1990 Imperial College of Science, Technology & Medicine
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 8
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Jan-Simon Pendry at Imperial College, London.
D 2
.\"
E 2
D 3
.\" %sccs.include.redist.man%
E 3
.\"
I 3
D 4
.\" %sccs include.redist.man%
E 4
I 4
D 5
.\" %sccs.include.redist.roff%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
E 4
.\"
E 3
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
D 4
.\"     %W% (Berkeley) %G%
E 4
I 4
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\"     %W% (Berkeley) %G%
E 5
E 4
E 2
.\"
D 2
.TH AMQ 8 "%Q%"
.SH NAME
amq \- automounter query tool
.SH SYNOPSIS
.B amq
[
.BI \-h " hostname"
] [
.B \-f
] [
.B \-m
] [
.B \-s
] [
.B \-u
]
[
.I directory
] .\|.\|.
.SH DESCRIPTION
.B Amq
E 2
I 2
D 3
.Dd %Q%
E 3
I 3
D 4
.Dd March 17, 1991
E 4
I 4
D 5
.Dd "%Q%"
E 5
I 5
D 7
.\" $Id: amq.8,v 5.2.1.2 91/05/07 22:20:44 jsp Alpha $
E 7
I 7
.\" $Id: amq.8,v 5.2.2.1 1992/02/09 15:11:41 jsp beta $
E 7
.\"
.Dd March 16, 1991
E 5
E 4
E 3
.Dt AMQ 8
.Os
.Sh NAME
.Nm amq
.Nd automounter query tool
.Sh SYNOPSIS
.Nm amq
.Op Fl f
.Op Fl h Ar hostname
I 3
.Op Fl M Ar mountmap_entry
E 3
.Op Fl m
.Op Fl s
.Op Fl u
I 3
.Op Fl v
E 3
.Op Ar directory
.Ar ...
.Sh DESCRIPTION
.Nm Amq
E 2
D 3
provides a simple way of determining the current state of
E 3
I 3
provides a simple way of determining the current state of the
E 3
D 2
.B amd
E 2
I 2
.Xr amd 8
E 2
program.
Communication is by
D 2
.SM RPC.
E 2
I 2
.Tn RPC .
E 2
Three modes of operation are supported by the current protocol.
By default a list of mount points and auto-mounted filesystems
is output.
An alternative host can be specified using the
D 2
.I \-h
E 2
I 2
.Fl h
E 2
option.
D 2
.LP
E 2
I 2
.Pp
E 2
If directory names are given, as output by default,
then per-filesystem information is displayed.
D 2
.SH OPTIONS
The
.I \-h
option specifies an alternate host to query.
E 2
I 2
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f
D 3
Request automounter to flush the internal
mount map cache.
E 3
I 3
Request automounter to flush the internal caches.
E 3
.It Fl h Ar hostname
Query alternate host
.Ar hostname .
E 2
By default the local host is used.  In an
D 2
.SM HP-UX
E 2
I 2
.Tn HP-UX
E 2
cluster, the root server is queried by default, since
that is the system on which the automounter is normally run.
D 2
.LP
The
.I \-f
option asks the automounter to flush the internal
mount map cache.
The
.I \-m
option asks the automounter to provide a list of mounted filesystems,
E 2
I 2
.It Fl m
D 3
Request automounter to provide a list of mounted filesystems,
E 3
I 3
Request the automounter to provide a list of mounted filesystems,
E 3
E 2
including the number of references to each filesystem and any error
D 10
which occured while mounting.
E 10
I 10
which occurred while mounting.
E 10
D 2
The
.I \-s
option asks the automounter to provide system-wide mount statistics.
.LP
The
.I \-u
option asks the automounter to unmount the named filesystems
E 2
I 2
.It Fl s
D 3
Request automounter to provide system-wide mount statistics.
E 3
I 3
Request the automounter to provide system-wide mount statistics.
E 3
.It Fl u
D 3
Request automounter to unmount the named filesystems
E 3
I 3
Request the automounter to unmount the named filesystems
E 3
E 2
instead of providing information about them.  Unmounts are requested,
not forced.  They merely cause the mounted filesystem to timeout,
which will be picked up by
D 2
.BR amd 's
E 2
I 2
.Xr amd Ns \'s
E 2
main scheduler thus causing the normal timeout action to be taken.
I 3
.It Fl v
Request the automounter to provide version information.  This is a subset
of the information provided by
D 9
.Xr amd Ns \'s
.It Fl v
E 9
I 9
.Xr amd Ns \'s Fl v
E 9
option.
.It Fl M
Request automounter to add the given map entry to the root map and then
trigger a mount request for it.
E 3
D 2
.SH FILES
.PD 0
.TP 20
.B amq.x
.SM RPC
E 2
I 2
.El
.Sh FILES
.Bl -tag -width amq.xxxxx -compact
.Bl -tag -width Ds
.It Pa amq.x
.Tn RPC
E 2
protocol description.
D 2
.SH CAVEATS
.B Amq
E 2
I 2
.El
.Sh CAVEATS
.Nm Amq
E 2
uses a Sun registered
D 2
.SM RPC
E 2
I 2
.Tn RPC
E 2
program number (300019 decimal) which may not
D 2
be in the /etc/rpc database.
.SH "SEE ALSO"
.BR amd (8)
.SH AUTHOR
Jan-Simon Pendry <jsp@doc.ic.ac.uk>, Department of Computing, Imperial College, London, UK.
E 2
I 2
be in the
.Pa /etc/rpc
database.
.Sh SEE ALSO
.Xr amd 8
.Sh AUTHOR
.An Jan-Simon Pendry
<jsp@doc.ic.ac.uk>, Department of Computing, Imperial College, London, UK.
.Sh HISTORY
D 3
The
.Nm
E 3
I 3
D 6
.Nm Amq
I 5
.\" %sccs.include.redist.man%
.\" %sccs.include.redist.man%
E 5
E 3
.At
E 6
I 6
D 7
The
.Nm amq
tool is
.Ud .
E 7
I 7
.Nm Amq
.At
E 7
E 6
E 2
E 1
