h62359
s 00002/00002/00063
d D 8.1 93/06/09 19:16:25 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00005/00065
d D 5.3 93/06/09 19:16:22 bostic 4 2
c fixed the under development line
e
s 00002/00002/00068
d R 8.1 93/06/05 13:44:52 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00048/00039/00022
d D 5.2 91/03/28 00:45:57 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00061/00000/00000
d D 5.1 90/05/10 15:10:35 bostic 1 0
c date and time created 90/05/10 15:10:35 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" %sccs.include.redist.man%
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH FD 4 "%Q%"
.UC 7
.SH NAME
fd, stdin, stdout, stderr \- file descriptor files
.SH DESCRIPTION
E 2
I 2
.Dd %Q%
.Dt FD 4
.Os
.Sh NAME
.Nm fd ,
.Nm stdin ,
.Nm stdout ,
.Nm stderr
.Nd file descriptor files
.Sh DESCRIPTION
E 2
The files
D 2
.I /dev/fd/0
E 2
I 2
.Pa /dev/fd/0
E 2
through
D 2
.I /dev/fd/#
E 2
I 2
.Pa /dev/fd/#
E 2
refer to file descriptors which can be accessed through the file
system.
If the file descriptor is open and the mode the file is being opened
with is a subset of the mode of the existing descriptor, the call:
D 2
.sp
.RS
E 2
I 2
.Bd -literal -offset indent
E 2
fd = open("/dev/fd/0", mode);
D 2
.RE
.sp
E 2
I 2
.Ed
.Pp
E 2
and the call:
D 2
.sp
.RS
E 2
I 2
.Bd -literal -offset indent
E 2
fd = fcntl(0, F_DUPFD, 0);
D 2
.RE
.sp
E 2
I 2
.Ed
.Pp
E 2
are equivalent.
D 2
.PP
E 2
I 2
.Pp
E 2
Opening the files
D 2
.IR /dev/stdin ,
.I /dev/stdout
E 2
I 2
.Pa /dev/stdin ,
.Pa /dev/stdout
E 2
and
D 2
.I /dev/stderr
E 2
I 2
.Pa /dev/stderr
E 2
is equivalent to the following calls:
D 2
.sp
.RS
E 2
I 2
.Bd -literal -offset indent
E 2
fd = fcntl(STDIN_FILENO,  F_DUPFD, 0);
D 2
.br
E 2
fd = fcntl(STDOUT_FILENO, F_DUPFD, 0);
D 2
.br
E 2
fd = fcntl(STDERR_FILENO, F_DUPFD, 0);
D 2
.RE
.PP
E 2
I 2
.Ed
.Pp
E 2
Flags to the
D 2
.IR open (2)
call other than O_RDONLY, O_WRONLY and O_RDWR are ignored.
.SH FILES
/dev/fd/#
.br
/dev/stdin
.br
/dev/stdout
.br
/dev/stderr
.SH SEE ALSO
tty(4)
E 2
I 2
.Xr open 2
call other than
.Dv O_RDONLY , 
.Dv O_WRONLY
and
.Dv O_RDWR
are ignored.
.Sh FILES
.Bl -tag -width /dev/stderr -compact
.It Pa /dev/fd/#
.It Pa /dev/stdin
.It Pa /dev/stdout
.It Pa /dev/stderr
.El
.Sh SEE ALSO
.Xr tty 4
D 4
.Sh HISTORY
The
.Nm
descriptor implementation
.Ud
E 4
E 2
E 1
