h57356
s 00002/00002/00028
d D 8.1 93/06/05 13:46:44 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00002/00002/00028
d D 6.3 91/07/19 20:07:00 cael 5 4
c Os change
e
s 00029/00011/00001
d D 6.2 91/03/28 00:46:10 cael 4 3
c macro and text revision (-mdoc version 3)
e
s 00001/00001/00011
d D 6.1 85/05/15 17:00:42 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00007/00009
d D 5.1 85/05/15 17:00:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00016/00000/00000
d D 4.1 85/05/15 17:00:30 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 6
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
E 4
.\"
D 2
.TH NULL 4 
E 2
I 2
D 3
.TH NULL 4 "9 February 1983"
E 3
I 3
D 4
.TH NULL 4 "%Q%"
E 3
E 2
.AT 3
.SH NAME
null \- data sink
.SH DESCRIPTION
D 2
Data written on 
a null special file
is discarded.
E 2
I 2
Data written on a null special file is discarded.
E 2
.PP
D 2
Reads from 
a null special file
always return 0 bytes.
E 2
I 2
Reads from a null special file always return 0 bytes.
E 2
.SH FILES
/dev/null
E 4
I 4
.\" %sccs.include.redist.man%
.\"
D 5
.\"     %W% (Berkeley) %G%
E 5
I 5
.\"	%W% (Berkeley) %G%
E 5
.\"
.Dd %Q%
.Dt NULL 4
D 5
.Os BSD 4.4
E 5
I 5
.Os
E 5
.Sh NAME
.Nm null
.Nd the null device
.Sh DESCRIPTION
The
.Nm
device accepts and reads data as any ordinary (and willing)
file \-
but throws it away. The length of the
.Nm null
device is always zero.
.Sh FILES
.Bl -tag -width /dev/null
.It Pa /dev/null
.El
.Sh HISTORY
A
.Nm
device appeared in
.At v7 .
E 4
E 1
