#!/bin/sh -x
cp /dev/null index
cp /dev/null masterindx
digrind -t -Pop > /dev/null h/*
cat index >>masterindx
cp /dev/null index
digrind -t -Pop > /dev/null net/*.h net/*.c netimp/*.h netimp/*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null netinet/*.h netinet/*.c netns/*.h netns/*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null sys/[i-s]*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null sys/[t-u]*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null sys/v*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null vax/*.h vax/*.c vax/*.s
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null vaxif/*.h vaxif/*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null vaxmba/*.h vaxmba/*.c
cat index >>masterindx
cp /dev/null index
digrind -Pop -t > /dev/null vaxuba/*.h vaxuba/*.c
cat index >>masterindx
sort masterindx >index
