h25810
s 00002/00002/00077
d D 8.1 93/06/09 19:11:59 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00005/00078
d D 5.3 93/06/09 19:11:56 bostic 4 2
c fixed the under development line
e
s 00002/00002/00081
d R 8.1 93/06/05 13:39:52 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00056/00042/00027
d D 5.2 91/03/27 23:24:38 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00069/00000/00000
d D 5.1 90/06/29 19:03:50 bostic 1 0
c date and time created 90/06/29 19:03:50 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
I 4
.\"
E 4
D 2
.\"
E 2
.\" %sccs.include.redist.man%
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH CT 4 "%Q%"
.UC 7
.SH NAME
ct \- CS/80 cartridge tape interface
.SH SYNOPSIS
.B "tape ct0 at hpib? slave ?"
.SH DESCRIPTION
E 2
I 2
.Dd %Q%
.Dt CT 4 hp300
.Os
.Sh NAME
.Nm \&ct
.Nd
.Tn CS/80
cartridge tape interface
.Sh SYNOPSIS
.Cd "tape ct0 at hpib? slave ?"
.Sh DESCRIPTION
E 2
The cartridge tape interface as found in the 7946 and 9144 products
provides a standard tape drive interface as described in
D 2
.IR mtio (4)
E 2
I 2
.Xr mtio 4
E 2
with the following exceptions:
D 2
.TP 3
1.
E 2
I 2
.Bl -enum
.It
E 2
There is only one density.
D 2
.TP 3
2.
Only the ``raw'' interface is supported.
.TP 3
3.
The MTIOCTOP
.I ioctl
E 2
I 2
.It
Only the
.Dq raw
interface is supported.
.It
The
.Dv MTIOCTOP
.Xr ioctl 2
E 2
is limited.
D 2
In particular, the command, MTFSR is not supported.
.TP 3
4.
The MTIOCGET
.I ioctl
E 2
I 2
In particular, the command,
.Dv MTFSR
E 2
is not supported.
D 2
.TP 3
5.
E 2
I 2
.It
The
.Dv MTIOCGET
.Xr ioctl
is not supported.
.It
E 2
The record size for read and write operations must be between
1K and 64K inclusive.
D 2
.PP
E 2
I 2
.El
.Pp
E 2
Special files
D 2
.I rct0
E 2
I 2
.Pa rct0
E 2
through
D 2
.I rct3
E 2
I 2
.Pa rct3
E 2
refer to rewind on close interfaces to drives 0 to 3.
D 2
.I Rct4
E 2
I 2
Files
.Pa rct4
E 2
through
D 2
.I rct7
E 2
I 2
.Pa rct7
E 2
refer to no-rewind interfaces.
D 2
.I Rct8
E 2
I 2
Files
.Pa rct8
E 2
through
D 2
.I rct11
E 2
I 2
.Pa rct11
E 2
refer to streaming rewind on close interfaces. (Only 9144 type devices
can stream.)
D 2
.I Rct12
E 2
I 2
Lastly,
.Pa rct12
E 2
through
D 2
.I rct15
E 2
I 2
.Pa rct15
E 2
refer to streaming no-rewind interfaces.
D 2
.SH BUGS
E 2
I 2
.Sh SEE ALSO
.Xr mt 1 ,
.Xr tar 1 ,
.Xr tp 1 ,
.Xr mtio 4 .
D 4
.Sh HISTORY
The
.Nm \&ct
driver
.Ud
E 4
.Sh BUGS
E 2
Read and writes of less than 1024 bytes will not behave as expected.
D 2
.SH "SEE ALSO"
mt(1),
tar(1),
tp(1),
mtio(4).
E 2
E 1
