h07174
s 00002/00002/00097
d D 8.1 93/06/09 19:12:46 bostic 5 4
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00005/00098
d D 5.3 93/06/09 19:12:43 bostic 4 2
c fixed the under development line
e
s 00002/00002/00101
d R 8.1 93/06/05 13:40:06 bostic 3 2
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00070/00040/00033
d D 5.2 91/03/27 23:24:40 cael 2 1
c macro and text revision (-mdoc version 3)
e
s 00073/00000/00000
d D 5.1 90/06/29 19:03:52 bostic 1 0
c date and time created 90/06/29 19:03:52 by bostic
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 5
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 5
I 5
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 5
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
I 4
.\"
E 4
D 2
.\"
E 2
.\" %sccs.include.redist.man%
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH DCL 4 "%Q%"
.UC 7
.SH NAME
dcl \- HP 98628A communications link
.SH SYNOPSIS
.B "device		dcl0	at scode? flags 0x1"
.SH DESCRIPTION
The 98628A is a buffered EIA RS-232C (CCITT V.28) communications interface.
E 2
I 2
.Dd %Q%
.Dt DCL 4 hp300
.Os
.Sh NAME
.Nm dcl
.Nd
.Tn HP
98628A communications link
.Sh SYNOPSIS
.Cd "device dcl0 at scode? flags 0x1"
.Sh DESCRIPTION
The 98628A is a buffered
.Tn EIA
.Tn RS-232C
.Pf ( Tn CCITT
.Tn V.28 )
communications interface.
E 2
It has one port with full modem control.
D 2
.PP
Each line attached to the 98628A behaves as described in
.IR tty (4).
E 2
I 2
.Pp
E 2
Input and output for each line may set to one of following baud rates;
0, 50, 75, 110, 134.5, 150, 200, 300, 600, 1200, 1800, 2400, 4800,
D 2
9600, 19200. See 
.IR tty (4)
for the encoding.
.PP
.I Flags
should be set to 1 if the line should be treated as hard-wired with
E 2
I 2
9600, 19200.
.Pp
An optional argument
.Ar flags
may be set to 1 if the line should be treated as hard-wired with
E 2
carrier always present, or to 0 if modem control is desired.
D 2
.PP
Use HP cable "98626 & 98628 opts.002, RS232-C DCE CABLE, 5061-4216" to attach non-modem devices.
Use HP cable "98626 & 98628 opts.001, RS232-C DTE CABLE, 5061-4215" to attach modems.
.PP
E 2
I 2
.Pp
Use
.Tn HP
cable "98626 & 98628 opts.002,
.Tn RS232-C
.Tn DCE CABLE ,
5061-4216" to attach non-modem devices.
Use
.Tn HP
cable "98626 & 98628 opts.001,
.Tn RS232-C
.Tn DTE CABLE ,
5061-4215" to attach modems.
.Pp
E 2
The 98628A has a 256 byte input silo and a 256 output silo. Input interrupts
happen on a per character basis.
D 2
.PP
The high water and low water marks in the kernel tty routines are totally
E 2
I 2
.Pp
The high water and low water marks in the kernel tty routines are completely
E 2
inappropriate for a device like this with a large input buffer.  Don't use
tandem mode if possible.  A fast system can handle input at 19.2K baud without
receive overflow.
D 2

For output to devices that make heavy use of XON/XOFF a write size of less
E 2
I 2
.Pp
For output to devices that make heavy use of
.Tn XON/XOFF
a write size of less
E 2
then 256 will improve performance marginally.
D 2
.SH FILES
/dev/ttyl[0-9]
.SH "SEE ALSO"
tty(4)
.SH DIAGNOSTICS
\fBdcl%d: error 0x%x RESET CARD\fR Where the errors are in coded as
.DS
E 2
I 2
.Sh FILES
.Bl -tag -width /dev/ttyl[0-9] -compact
.It Pa /dev/ttyl[0-9]
.El
.Sh DIAGNOSTICS
.Bl -diag
.It dcl%d: error 0x%x RESET CARD.
Where the errors are encoded:
.Bd -unfilled -offset indent
E 2
0x06 card failure
0x0d uart receive overflow
0x0e receive overflow
0x0f missing external clock
0x10 cts false too long
0x11 lost carrier
0x12 activity timeout
0x13 connection not established
0x19 illegal databits/parity
0x1a register address out of range
0x1b register value out of range
0x-- unknown error
D 2
.DE
.SH BUGS
E 2
I 2
.Ed
.El
.Sh SEE ALSO
.Xr tty 4
D 4
.Sh HISTORY
The
.Nm
driver
.Ud
E 4
.Sh BUGS
E 2
Breaks received at a faster rate then 1 break every second will be 
recognized as a single break.
D 2

E 2
I 2
.Pp
E 2
Console use is not supported.
D 2

The RS-422/423/499, MTS-DSN/DL modes of the card are not supported.
E 2
I 2
.Pp
The
.Tn RS-422/423/499 ,
.Tn MTS-DSN/DL
modes of the card are not supported.
E 2
E 1
