h62044
s 00001/00001/00222
d D 8.3 94/04/19 08:31:32 bostic 10 9
c spell
e
s 00003/00003/00220
d D 8.2 93/12/11 23:44:41 mckusick 9 8
c copyediting for Usenix manuals
e
s 00002/00002/00221
d D 8.1 93/06/06 14:00:02 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00139/00123/00084
d D 6.6 91/03/16 18:12:47 cael 7 6
c macro and text revision (-mdoc version 3)
e
s 00004/00014/00203
d D 6.5 90/06/24 22:22:50 trent 6 5
c new copyright & pathnames (lpd & spool)
e
s 00014/00003/00203
d D 6.4 88/09/29 09:32:19 bostic 5 4
c add Berkeley copyright notice
e
s 00002/00001/00204
d D 6.3 85/12/08 17:18:53 mckusick 4 3
c add more description of /etc/hosts.lpd (from mcvax!jaap)
e
s 00010/00008/00195
d D 6.2 85/11/17 14:09:49 eric 3 2
c fix documentation of -L option
e
s 00017/00002/00186
d D 6.1 85/04/27 15:33:26 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00188/00000/00000
d D 5.1 85/04/27 15:32:57 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 7
.\" Copyright (c) 1983 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
.\" %sccs.include.redist.man%
E 6
E 5
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 2
.TH LPD 8 "18 July 1983"
E 2
I 2
D 7
.TH LPD 8 "%Q%"
E 2
.UC 5
.ad
.SH NAME
lpd \- line printer daemon
.SH SYNOPSIS
D 6
.B /usr/lib/lpd
E 6
I 6
.B lpd
E 6
D 3
[ -l ] [ -L logfile ] [ port # ]
E 3
I 3
[
.B \-l
] [ port # ]
E 3
.SH DESCRIPTION
.I Lpd
E 7
I 7
.Dd %Q%
.Dt LPD 8
.Os BSD 4.2
.Sh NAME
.Nm lpd
.Nd line printer spooler daemon
.Sh SYNOPSIS
.Nm lpd
.Op Fl l
.Op Ar port#
.Sh DESCRIPTION
.Nm Lpd
E 7
is the line printer daemon (spool area handler) and is normally invoked
at boot time from the
D 7
.IR rc (8)
E 7
I 7
.Xr rc 8
E 7
file.  It makes a single pass through the
D 7
.IR printcap (5)
E 7
I 7
.Xr printcap 5
E 7
file to find out about the existing printers and
prints any files left after a crash. It then uses the system calls
D 7
.IR listen (2)
E 7
I 7
.Xr listen 2
E 7
and
D 7
.IR accept (2)
E 7
I 7
.Xr accept 2
E 7
to receive requests to print files in the queue,
transfer files to the spooling area, display the queue,
or remove jobs from the queue.  In each case, it forks a child to handle
the request so the parent can continue to listen for more requests.
D 7
The Internet port number used to rendezvous
with other processes is normally obtained with
.IR getservbyname (3)
but can be changed with the
.IR port #
D 3
argument. The
.B \-L
option changes the file used for writing error conditions from the
system console to
.I logfile.
E 3
I 3
argument.
E 7
I 7
.Pp
Available options:
.Bl -tag -width Ds
.It Fl l
E 7
E 3
The
D 7
.B \-l
E 7
I 7
.Fl l
E 7
flag causes
D 7
.I lpd
E 7
I 7
.Nm lpd
E 7
to log valid requests received from the network. This can be useful
for debugging purposes.
D 7
.PP
Access control is provided by two means. First, All requests must come from
E 7
I 7
.It Ar "port#"
The Internet port number used to rendezvous
with other processes is normally obtained with
.Xr getservbyname 3
but can be changed with the
.Ar port#
argument.
.El
.Pp
Access control is provided by two means. First, all requests must come from
E 7
one of the machines listed in the file
D 2
.IR /etc/hosts.equiv .
E 2
I 2
D 7
.I /etc/hosts.equiv
E 7
I 7
.Pa /etc/hosts.equiv
E 7
or
D 7
.IR /etc/hosts.lpd .
E 2
Second, if the ``rs'' capability is specified in the
.I printcap
E 7
I 7
.Pa /etc/hosts.lpd .
Second, if the
.Li rs
capability is specified in the
.Xr printcap
E 7
entry for the printer being accessed,
D 7
.I lpr
E 7
I 7
.Em lpr
E 7
requests will only be honored for those users with accounts on the
machine with the printer.
D 7
.PP
E 7
I 7
.Pp
E 7
The file
I 2
D 7
.I minfree
E 7
I 7
.Em minfree
E 7
in each spool directory contains the number of disk blocks to leave free
so that the line printer queue won't completely fill the disk.
The
D 7
.I minfree
E 7
I 7
.Em minfree
E 7
file can be edited with your favorite text editor.
D 7
.PP
The file
E 2
.I lock
in each spool directory is used to prevent multiple daemons from
becoming active simultaneously, and to store information
about the daemon process for
.IR lpr (1),
.IR lpq (1),
and
.IR lprm (1).
After the daemon has successfully set the lock, it scans the directory
E 7
I 7
.Pp
The daemon begins processing files
after it has successfully set the lock for exclusive
D 10
access (descibed a bit later),
E 10
I 10
access (described a bit later),
E 10
and scans the spool directory
E 7
for files beginning with 
D 7
.IR cf .
E 7
I 7
.Em cf .
E 7
Lines in each
D 7
.I cf
E 7
I 7
.Em cf
E 7
file specify files to be printed or non-printing actions to be
performed.  Each such line begins with a key character
to specify what to do with the remainder of the line.
D 7
.in +3
.IP J
E 7
I 7
.Bl -tag -width Ds
.It J
E 7
Job Name.  String to be used for the job name on the burst page.
D 7
.IP C
E 7
I 7
.It C
E 7
Classification.  String to be used for the classification line
on the burst page.
D 7
.IP L
E 7
I 7
.It L
E 7
Literal.  The line contains identification info from
the password file and causes the banner page to be printed.
D 7
.IP T
E 7
I 7
.It T
E 7
Title.  String to be used as the title for
D 7
.IR pr (1).
.IP H
E 7
I 7
.Xr pr 1 .
.It H
E 7
Host Name.  Name of the machine where
D 7
.I lpr
E 7
I 7
.Xr lpr
E 7
was invoked.
D 7
.IP P
E 7
I 7
.It P
E 7
Person.  Login name of the person who invoked
D 7
.IR lpr .
E 7
I 7
.Xr lpr .
E 7
This is used to verify ownership by
D 7
.IR lprm .
.IP M
E 7
I 7
.Xr lprm .
.It M
E 7
Send mail to the specified user when the current print job completes.
D 7
.IP f
E 7
I 7
.It f
E 7
Formatted File.  Name of a file to print which is already formatted.
D 7
.IP l
E 7
I 7
.It l
E 7
Like ``f'' but passes control characters and does not make page breaks.
D 7
.IP p
E 7
I 7
.It p
E 7
Name of a file to print using
D 7
.IR pr (1)
E 7
I 7
.Xr pr 1
E 7
as a filter.
D 7
.IP t
E 7
I 7
.It t
E 7
Troff File.  The file contains
D 7
.IR troff (1)
E 7
I 7
.Xr troff 1
E 7
output (cat phototypesetter commands).
I 2
D 7
.IP n
E 7
I 7
.It n
E 7
Ditroff File.  The file contains device independent troff
output.
E 2
D 7
.IP d
E 7
I 7
.It r
E 7
DVI File.  The file contains
D 7
.IR Tex (l)
output (DVI format from Standford).
.IP g
E 7
I 7
.Tn Tex l
output
D 9
DVI format from Standford).
E 9
I 9
DVI format from Standford.
E 9
.It g
E 7
Graph File.  The file contains data produced by
D 7
.IR plot (3X).
.IP c
E 7
I 7
.Xr plot 3 .
.It c
E 7
Cifplot File. The file contains data produced by
D 7
.IR cifplot .
.IP v
E 7
I 7
.Em cifplot .
.It v
E 7
The file contains a raster image.
D 7
.IP r
The file contains text data with FORTRAN carriage control characters.
.IP 1
E 7
I 7
.It r
The file contains text data with
FORTRAN carriage control characters.
.It \&1
E 7
Troff Font R. Name of the font file to use instead of the default.
D 7
.IP 2
E 7
I 7
.It \&2
E 7
Troff Font I. Name of the font file to use instead of the default.
D 7
.IP 3
E 7
I 7
.It \&3
E 7
Troff Font B. Name of the font file to use instead of the default.
D 7
.IP 4
E 7
I 7
.It \&4
E 7
Troff Font S. Name of the font file to use instead of the default.
D 7
.IP W
E 7
I 7
.It W
E 7
Width. Changes the page width (in characters) used by
D 7
.IR pr (1)
E 7
I 7
.Xr pr 1
E 7
and the text filters.
D 7
.IP I
E 7
I 7
.It I
E 7
Indent.  The number of characters to indent the output by (in ascii).
D 7
.IP U
E 7
I 7
.It U
E 7
Unlink.  Name of file to remove upon completion of printing.
D 7
.IP N
E 7
I 7
.It N
E 7
File name.  The name of the file which is being printed, or a blank
for the standard input (when 
D 7
.I lpr
E 7
I 7
.Xr lpr
E 7
is invoked in a pipeline).
D 7
.in -5
.PP
E 7
I 7
.El
.Pp
E 7
D 3
If a file can not be opened, a message will be placed
in the log file (normally the console).
E 3
I 3
D 9
If a file can not be opened, a message will be logged via
E 9
I 9
If a file cannot be opened, a message will be logged via
E 9
D 7
.IR syslog (3)
E 7
I 7
.Xr syslog 3
E 7
using the
D 7
.I LOG_LPR
E 7
I 7
.Em LOG_LPR
E 7
facility.
E 3
D 7
.I Lpd
E 7
I 7
.Nm Lpd
E 7
will try up to 20 times
to reopen a file it expects to be there, after which it will
skip the file to be printed.
D 7
.PP
.I Lpd
E 7
I 7
.Pp
.Nm Lpd
E 7
uses
D 7
.IR flock (2)
E 7
I 7
.Xr flock 2
E 7
to provide exclusive access to the lock file and to prevent multiple
D 9
deamons from becoming active simultaneously.  If the daemon should be killed
E 9
I 9
daemons from becoming active simultaneously.  If the daemon should be killed
E 9
or die unexpectedly, the lock file need not be removed.
D 7
The lock file is kept in a readable ASCII form
E 7
I 7
The lock file is kept in a readable
.Tn ASCII
form
E 7
and contains two lines.
The first is the process id of the daemon and the second is the control
file name of the current job being printed.  The second line is updated to
reflect the current status of
D 7
.I lpd
E 7
I 7
.Nm lpd
E 7
for the programs
D 7
.IR lpq (1)
E 7
I 7
.Xr lpq 1
E 7
and
D 7
.IR lprm (1).
.SH FILES
.nf
.ta \w'/etc/printcap           'u
/etc/printcap	printer description file
D 6
/usr/spool/*	spool directories
I 2
/usr/spool/*/minfree	minimum free space to leave
E 6
I 6
/var/spool/*	spool directories
/var/spool/*/minfree	minimum free space to leave
E 6
E 2
/dev/lp*	line printer devices
/dev/printer	socket for local requests
/etc/hosts.equiv	lists machine names allowed printer access
I 2
D 4
/etc/hosts.lpd	lists machine names allowed printer access
E 4
I 4
/etc/hosts.lpd	lists machine names allowed printer access,
		but not under same administrative control.
E 4
E 2
.fi
.SH "SEE ALSO"
lpc(8),
pac(1),
lpr(1),
lpq(1),
lprm(1),
I 3
syslog(3),
E 3
printcap(5)
.br
.ul
4.2BSD Line Printer Spooler Manual
E 7
I 7
.Xr lprm 1 .
.Sh FILES
.Bl -tag -width "/var/spool/*/minfree" -compact
.It Pa /etc/printcap
printer description file
.It Pa /var/spool/*
spool directories
.It Pa /var/spool/*/minfree
minimum free space to leave
.It Pa /dev/lp*
line printer devices
.It Pa /dev/printer
socket for local requests
.It Pa /etc/hosts.equiv
lists machine names allowed printer access
.It Pa /etc/hosts.lpd
lists machine names allowed printer access,
but not under same administrative control.
.El
.Sh SEE ALSO
.Xr lpc 8 ,
.Xr pac 1 ,
.Xr lpr 1 ,
.Xr lpq 1 ,
.Xr lprm 1 ,
.Xr syslog 3 ,
.Xr printcap 5
.Rs
.%T "4.2 BSD Line Printer Spooler Manual"
.Re
.Sh HISTORY
An
.Nm
daemon appeared in Version 6 AT&T UNIX.
E 7
E 1
