(File |dhl/rframes.l|)
(add-if-deleted-instance lambda fname nreverse cdr atom cond car cons setq null quote fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only inspect-datum fvalue-only frame+ fput-datum)
(add-if-added-instance lambda fname nreverse cdr atom cond car cons setq null quote fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only inspect-datum fvalue-only frame+ fput-datum)
(get-all-things lambda nreverse cdr atom cond car cons setq null quote inspect-datum fvalue-only fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only)
(remove-domain-instance lambda fname nreverse cdr atom cond car cons setq null quote fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only inspect-datum fvalue-only fremove-datum fremove)
(add-domain-instance lambda fname nreverse cdr atom cond car cons setq null quote fdata liszt-internal-do mapcar findicators1 fdata-only fvalues-only inspect-datum fvalue-only fput-datum fput)
