h55874
s 00002/00002/00117
d D 8.1 93/06/06 14:09:31 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00009/00000/00110
d D 6.7 93/05/11 11:49:35 bostic 9 8
c new version from Vernon Schryver (vjs@sgi.com); see ../timed/CHANGES for details
e
s 00086/00060/00024
d D 6.6 91/03/16 18:13:48 cael 8 7
c macro and text revision (-mdoc version 3)
e
s 00006/00016/00078
d D 6.5 90/06/24 22:47:13 trent 7 6
c new copyright & pathnames
e
s 00001/00001/00093
d D 6.4 88/09/20 10:16:01 bostic 6 5
c (4P) -> (4)
e
s 00010/00005/00084
d D 6.3 88/07/09 11:32:10 bostic 5 4
c install approved copyright notice
e
s 00008/00003/00081
d D 6.2 87/12/23 14:31:46 bostic 4 3
c add Berkeley header; NASA wants it
e
s 00000/00000/00084
d D 6.1 86/05/28 11:42:42 karels 3 2
c out
e
s 00011/00010/00073
d D 1.2 86/05/28 10:31:00 karels 2 1
c updates and cleanups
e
s 00083/00000/00000
d D 1.1 85/06/24 13:27:26 gusella 1 0
c date and time created 85/06/24 13:27:26 by gusella
e
u
U
t
T
I 1
D 4

E 4
D 8
.\" Copyright (c) 1980 Regents of the University of California.
E 8
I 8
D 10
.\" Copyright (c) 1980, 1991 Regents of the University of California.
E 8
D 4
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
.\" All rights reserved.
E 10
I 10
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 10
.\"
D 7
.\" Redistribution and use in source and binary forms are permitted
D 5
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
E 5
I 5
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
.\" %sccs.include.redist.man%
E 7
E 5
E 4
.\"
D 8
.\"	%W% (Berkeley) %G%
E 8
I 8
.\"     %W% (Berkeley) %G%
E 8
.\"
D 8
.TH TIMEDC 8 "%Q%"
.UC 6
E 8
I 8
.Dd %Q%
.Dt TIMEDC 8
.Os BSD 4.3
E 8
.ad
D 8
.SH NAME
timedc \- timed control program
.SH SYNOPSIS
D 7
.B /etc/timedc
E 7
I 7
.B timedc
E 7
[ command [ argument ... ] ]
.SH DESCRIPTION
.I Timedc
is used to control the operation of the \fItimed\fP program.
E 8
I 8
.Sh NAME
.Nm timedc
.Nd timed control program
.Sh SYNOPSIS
.Nm timedc
.Oo Ar command\ \&
.Op Ar argument ...
.Oc
.Sh DESCRIPTION
.Nm Timedc
is used to control the operation of the
.Xr timed 8
program.
E 8
It may be used to:
D 8
.IP \(bu
measure the differences between machines' clocks,
.IP \(bu
D 2
find the location where the master timed is running,
E 2
I 2
find the location where the master time server is running,
E 2
.IP \(bu
D 2
cause election timers on several machines to expire at the same time,
E 2
I 2
enable or disable tracing of messages received by \fItimed\fP, and
E 2
.IP \(bu
D 2
enable or disable tracing of messages received by \fItimed\fP.
E 2
I 2
perform various debugging actions.
E 2
.PP
E 8
I 8
.Bl -bullet
.It
Measure the differences between machines' clocks,
.It 
Find the location where the master time server is running,
.It
Enable or disable tracing of messages received by
.Xr timed ,
and
.It
Perform various debugging actions.
.El
.Pp
E 8
Without any arguments,
D 8
.I timedc
E 8
I 8
.Nm timedc
E 8
will prompt for commands from the standard input.
If arguments are supplied,
D 8
.IR timedc
E 8
I 8
.Nm timedc
E 8
interprets the first argument as a command and the remaining
arguments as parameters to the command.  The standard input
may be redirected causing
D 8
.I timedc
E 8
I 8
.Nm timedc
E 8
to read commands from a file.
Commands may be abbreviated;
recognized commands are:
D 8
.TP
? [ command ... ]
.TP
help [ command ... ]
.br
E 8
I 8
.Pp
.Bl -tag -width Ds -compact
.It Ic \&? Op Ar command ...
I 9
.Pp
E 9
.It Ic help Op Ar command ...
E 8
Print a short description of each command specified in the argument list,
or, if no arguments are given, a list of the recognized commands.
D 8
.TP
clockdiff host ...
.br
E 8
I 8
.Pp
.It Ic clockdiff Ar host ...
E 8
Compute the differences between the clock of the host machine
and the clocks of the machines given as arguments.
D 8
.TP
D 2
testing host ...
E 2
I 2
trace { on | off }
E 2
.br
D 2
Cause timed election timers to expire in the specified
hosts. It is used to test the election algorithm.
.TP
tracing { on | off }
.br
E 2
Enable or disable the tracing of incoming messages to \fItimed\fP
D 7
in the file /usr/adm/timed.log.
E 7
I 7
in the file /var/log/timed.log.
E 7
.TP
quit
.br
E 8
I 8
.Pp
I 9
.It Ic msite Op Ar host ...
Show the master time server for specified host(s).
.Pp
E 9
.It Xo
.Ic trace
.Li \&{ Ar on Li \&|
.Ar off \&}
.Xc
Enable or disable the tracing of incoming messages to
.Xr timed
in the file
.Pa /var/log/timed.log.
I 9
.Pp
.It Ic election Ar host
Asks the daemon
on the target host to reset its "election" timers and to ensure that
a time master has been elected.
E 9
.Pp
.It Ic quit
E 8
Exit from timedc.
I 2
D 8
.PP
E 8
I 8
.El
.Pp
E 8
Other commands may be included for use in testing and debugging
D 8
.IR timed ;
E 8
I 8
.Xr timed ;
E 8
the help command and
the program source may be consulted for details.
E 2
D 8
.SH FILES
.nf
D 7
.ta \w'/usr/adm/masterlog       'u
/usr/adm/timed.log		tracing file for timed
/usr/adm/timed.masterlog	log file for master timed
E 7
I 7
.ta \w'/var/log/masterlog       'u
/var/log/timed.log		tracing file for timed
/var/log/timed.masterlog	log file for master timed
E 7
.fi
.SH "SEE ALSO"
D 2
date(1), adjtime(2), timed(8), 
E 2
I 2
D 6
date(1), adjtime(2), icmp(4P), timed(8), 
E 6
I 6
date(1), adjtime(2), icmp(4), timed(8), 
E 6
.br
E 2
\fITSP: The Time Synchronization Protocol for UNIX 4.3BSD\fP, 
R. Gusella and S. Zatti
.SH DIAGNOSTICS
.nf
.ta \w'?Ambiguous command      'u
?Ambiguous command	abbreviation matches more than one command
?Invalid command	no match found
?Privileged command	command can be executed by root only
.fi
E 8
I 8
.Sh FILES
.Bl -tag -width /var/log/timed.masterlog -compact
.It Pa /var/log/timed.log
tracing file for timed
.It Pa /var/log/timed.masterlog
log file for master timed
.El
.Sh SEE ALSO
.Xr date 1 ,
.Xr adjtime 2 ,
.Xr icmp 4 ,
.Xr timed 8 ,
.Rs
.%T "TSP: The Time Synchronization Protocol for UNIX 4.3BSD"
.%A R. Gusella
.%A S. Zatti
.Re
.Sh DIAGNOSTICS
.Bl -tag -width Ds -compact
.It ?Ambiguous command
abbreviation matches more than one command
.It ?Invalid command
no match found
.It ?Privileged command
command can be executed by root only
.El
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.3 .
E 8
E 1
