h39430
s 00006/00000/00102
d D 8.3 94/07/24 16:29:11 eric 8 7
c add -d flag to allow duplicate keys in B-Trees
e
s 00005/00004/00097
d D 8.2 93/09/22 09:05:30 eric 7 6
c fix -f flag to match ORA book
e
s 00002/00002/00099
d D 8.1 93/06/17 17:52:00 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00049/00043/00052
d D 6.2 93/06/16 12:34:54 eric 5 3
c convert from -man to -mdoc
e
s 00002/00002/00093
d R 8.1 93/06/07 10:22:21 bostic 4 3
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00000/00000/00095
d D 6.1 92/12/21 16:10:01 eric 3 2
c Release 6
e
s 00010/00000/00085
d D 5.2 92/12/12 09:44:47 eric 2 1
c add -f flag to map upper->lower case in the keys
e
s 00085/00000/00000
d D 5.1 92/11/16 09:14:26 eric 1 0
c date and time created 92/11/16 09:14:26 by eric
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1988, 1991 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
D 5
.TH MAKEMAP 8 November\ 16,\ 1992
.UC 6
.sh NAME
makemap \- create database maps for sendmail
.SH SYNOPSIS
.B makemap
[
\-N
] [
I 2
\-f
] [
E 2
\-o
] [
\-r
] [
\-v
]
maptype mapname
.SH DESCRIPTION
.I Makemap
E 5
I 5
.Dd November 16, 1992
.Dt MAKEMAP 8
.Os BSD 4.4
.Sh NAME
.Nm makemap
.Nd create database maps for sendmail
.Sh SYNOPSIS
.Nm
.Op Fl N
I 8
.Op Fl d
E 8
.Op Fl f
.Op Fl o
.Op Fl r
.Op Fl v
.Ar maptype
.Ar mapname
.Sh DESCRIPTION
.Nm
E 5
creates the database maps used by the keyed map lookups in
D 5
.IR sendmail (8).
E 5
I 5
.Xr sendmail 8 .
E 5
It reads input from the standard input
and outputs them to the indicated
D 5
.IR mapname .
.PP
E 5
I 5
.Ar mapname .
.Pp
E 5
Depending on how it is compiled,
D 5
.I makemap
E 5
I 5
.Nm
E 5
handles up to three different database formats,
selected using the
D 5
.I maptype
E 5
I 5
.Ar maptype
E 5
parameter.
They may be
D 5
.IP dbm
E 5
I 5
.Bl -tag -width Fl
.It Li dbm
E 5
DBM format maps.
This requires the
D 5
.IR ndbm (3)
E 5
I 5
.Xr ndbm 3
E 5
library.
D 5
.IP btree
E 5
I 5
.It Li btree
E 5
B-Tree format maps.
This requires the new Berkeley
D 5
.IR db (3)
E 5
I 5
.Xr db 3
E 5
library.
D 5
.IP hash
E 5
I 5
.It Li hash
E 5
Hash format maps.
This also requires the
D 5
.IR db (3)
E 5
I 5
.Xr db 3
E 5
library.
D 5
.PP
E 5
I 5
.El
.Pp
E 5
In all cases,
D 5
.I makemap
E 5
I 5
.Nm
E 5
reads lines from the standard input consisting of two
words separated by white space.
The first is the database key,
the second is the value.
The value may contain
``%\fIn\fP''
strings to indicated parameter substitution.
Literal parentheses should be doubled
(``%%'').
Blank lines and lines beginning with ``#'' are ignored.
D 5
.SH FLAGS
.IP \-N
E 5
I 5
.Ss Flags
.Bl -tag -width Fl
.It Fl N
E 5
Include the null byte that terminates strings
in the map.
This must match the \-N flag in the sendmail.cf
``K'' line.
I 8
.It Fl d
Allow duplicate keys in the map.
This is only allowed on B-Tree format maps.
If two identical keys are read,
they will both be inserted into the map.
E 8
I 2
D 5
.IP \-f
E 5
I 5
.It Fl f
E 5
D 7
Fold all upper case letters in the key
to lower case;
this is intended to mesh with the
E 7
I 7
Normally all upper case letters in the key
are folded to lower case.
This flag disables that behaviour.
This is intended to mesh with the
E 7
\-f flag in the
D 5
.B K
E 5
I 5
\fBK\fP
E 5
line in sendmail.cf.
D 7
The value is not case folded.
E 7
I 7
The value is never case folded.
E 7
E 2
D 5
.IP \-o
E 5
I 5
.It Fl o
E 5
Append to an old file.
This allows you to augment an existing file.
D 5
.IP \-r
E 5
I 5
.It Fl r
E 5
Allow replacement of existing keys.
Normally
D 5
.I makemap
E 5
I 5
.Nm
E 5
complains if you repeat a key,
and does not do the insert.
D 5
.IP \-v
E 5
I 5
.It Fl v
E 5
Verbosely print what it is doing.
D 5
.SH SEE ALSO
sendmail(8)
E 5
I 5
.El
.Sh SEE ALSO
.Xr sendmail 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.4 .
E 5
E 1
