h25687
s 00002/00002/00248
d D 8.1 93/06/06 15:27:14 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00075/00095/00175
d D 6.4 91/05/09 22:58:01 cael 7 6
c mdoc version three/deleted AUTHOR section
e
s 00002/00000/00268
d D 6.3 91/03/14 00:14:28 cael 6 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00268
d R 6.3 91/03/13 20:31:44 cael 5 4
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00161/00148/00107
d D 6.2 90/06/11 05:58:27 cael 4 3
c converted man page
e
s 00001/00001/00254
d D 6.1 85/04/29 14:52:08 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00009/00004/00246
d D 5.1 85/04/29 14:51:47 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00250/00000/00000
d D 4.1 85/04/29 14:51:29 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 8
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
E 4
.\"
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
E 4
.\"
D 2
.TH PC 1
E 2
I 2
D 3
.TH PC 1 "6 June 1983"
E 3
I 3
D 4
.TH PC 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
pc \- Pascal compiler
.SH SYNOPSIS
.B pc
[ option ] [
.B \-i
name ...
] name ...
.SH DESCRIPTION
.I Pc
E 4
I 4
.\"     %W% (Berkeley) %G%
.\"
I 6
D 7
.Vx
.Vx
E 7
E 6
.Dd %Q%
.Dt PC 1
.Os BSD 4
.Sh NAME
D 7
.Nm pc
E 7
I 7
.Nm \&pc
E 7
.Nd Pascal compiler
.Sh SYNOPSIS
D 7
.Nm pc
E 7
I 7
.Nm \&pc
E 7
.Op  option
.Op Fl i Ar name \&...
.Ar name \&...
.Sh DESCRIPTION
D 7
.Nm Pc
E 7
I 7
.Nm \&Pc
E 7
E 4
is a Pascal compiler.
If given an argument file ending with
D 4
.BR .p ,
it will compile the file 
E 4
I 4
.Pa \&.p ,
it will compile the file
E 4
and load it
into an executable file called, by default,
D 4
.IR a.out .
.PP
A program may be separated into more than one 
.B .p
E 4
I 4
.Pa a.out  .
.Pp
A program may be separated into more than one
.Pa \&.p
E 4
file.
D 4
.I Pc
E 4
I 4
D 7
.Nm Pc
E 7
I 7
.Nm \&Pc
E 7
E 4
will compile a number of argument
D 4
.B .p
E 4
I 4
.Pa \&.p
E 4
files into object files (with
the extension
D 4
.B .o
E 4
I 4
.Pa \&.o
E 4
in place of
D 4
.BR .p ).
Object files may then be loaded 
E 4
I 4
.Pa \&.p ) .
Object files may then be loaded
E 4
into an executable
D 4
.I a.out
E 4
I 4
.Pa a.out
E 4
file.
D 4
Exactly one object file must supply a 
.B program
E 4
I 4
Exactly one object file must supply a
.Ar program
E 4
statement to successfully create an executable a.out file.
D 4
The rest of the files must consist only of 
E 4
I 4
The rest of the files must consist only of
E 4
declarations which logically nest within the program.
References to objects shared between separately compiled files
are allowed if the objects are declared in
D 4
.BR include d
E 4
I 4
.Ic included
E 4
header files, whose names must end with
D 4
.BR .h .
E 4
I 4
.Pa \&.h .
E 4
Header files may only be included at the outermost level,
and thus declare only globally available objects.
To allow
D 4
.BR function s
E 4
I 4
D 7
.Cx Ic function
.Cx s
.Cx
E 7
I 7
.Ic function Ns s
E 7
E 4
and
D 4
.BR procedure s
E 4
I 4
D 7
.Cx Ic procedure
.Cx s
.Cx
E 7
I 7
.Ic procedure Ns s
E 7
E 4
to be declared, an
D 4
.B external
E 4
I 4
.Ic external
E 4
directive has been added, whose use is similar to the
D 4
.B forward
E 4
I 4
.Ic forward
E 4
directive but restricted to appear only in
D 4
.B .h
E 4
I 4
.Pa \&.h
E 4
files.
D 4
.B Function
and 
.B procedure
E 4
I 4
.Ic Function
and
.Ic procedure
E 4
bodies may not appear in
D 4
.B .h
E 4
I 4
.Pa \&.h
E 4
files.
A binding phase of the compiler checks that declarations
are used consistently, to enforce the type checking rules of Pascal.
D 4
.PP
Object files 
E 4
I 4
.Pp
Object files
E 4
created by other language processors may be loaded together with
D 4
object files created by 
.IR pc .
E 4
I 4
object files created by
D 7
.Nm pc  .
E 7
I 7
.Nm \&pc  .
E 7
E 4
The
D 4
.BR function s
E 4
I 4
D 7
.Cx Ic function
.Cx s
.Cx
E 7
I 7
.Ic function Ns s
E 7
E 4
and
D 4
.BR procedure s
E 4
I 4
D 7
.Cx Ic procedure
.Cx s
.Cx
E 7
I 7
.Ic procedure Ns s
E 7
E 4
they define must have been declared
in
D 4
.B .h
E 4
I 4
.Pa \&.h
E 4
files included by all the
D 4
.B .p
E 4
I 4
.Pa \&.p
E 4
files which call those
routines.
Calling conventions are as in C,
with
D 4
.B var
E 4
I 4
.Ic var
E 4
parameters passed by address.
D 4
.PP
E 4
I 4
.Pp
E 4
D 7
See the Berkeley Pascal User's Manual for details.
E 7
I 7
See the
.%T "Berkeley Pascal User's Manual"
for details.
E 7
D 4
.PP
E 4
I 4
.Pp
E 4
The following options have the same meaning as in
D 4
.IR cc (1)
E 4
I 4
.Xr cc  1
E 4
and
D 4
.IR f77 (1).
E 4
I 4
.Xr f77  1  .
E 4
See
D 4
.IR ld (1)
E 4
I 4
D 7
.Xr ld  1
E 7
I 7
.Xr \&ld  1
E 7
E 4
for load-time options.
D 4
.TP 6
.B \-c
E 4
I 4
D 7
.Tw Fl
.Tp Fl c
E 7
I 7
.Bl -tag -width indent
.It Fl c
E 7
E 4
Suppress loading and produce `.o' file(s) from source file(s).
D 4
.TP 6
.B \-g
E 4
I 4
D 7
.Tp Fl g
E 7
I 7
.It Fl g
E 7
E 4
Have the compiler produce additional symbol table information for
D 2
.IR sdb (1).
E 2
I 2
D 4
.IR dbx (1).
E 2
.TP 6
.BR \-w
E 4
I 4
.Xr dbx  1  .
D 7
.Tp Fl w
E 7
I 7
.It Fl w
E 7
E 4
Suppress warning messages.
D 4
.TP 6
.B \-p
E 4
I 4
D 7
.Tp Fl p
E 7
I 7
.It Fl p
E 7
E 4
Prepare object files for profiling, see
D 4
.IR  prof (1).
.TP 6
.SM
.B \-O
E 4
I 4
.Xr prof  1  .
D 7
.Tp Fl O
E 7
I 7
.It Fl O
E 7
E 4
Invoke an
object-code improver.
D 4
.TP 6
.SM
.B \-S
E 4
I 4
D 7
.Tp Fl S
E 7
I 7
.It Fl S
E 7
E 4
Compile the named program, and leave the
assembler-language output on the corresponding file suffixed `.s'.
(No `.o' is created.).
D 4
.TP 6
.BR \-o " output"
E 4
I 4
D 7
.Tp Cx Fl o
.Ws
.Ar output
.Cx
E 7
I 7
.It Fl o Ns Ar output
E 7
E 4
Name the final output file
D 4
.I output
E 4
I 4
.Ar output
E 4
instead of
D 4
.I a.out.
.PP
E 4
I 4
.Pa a.out .
D 7
.Tp
E 7
I 7
.El
E 7
.Pp
E 4
The following options are peculiar to
D 4
.IR pc .
.TP 6
.B \-C
E 4
I 4
.Nm pc  .
D 7
.Tw Fl
.Tp Fl C
E 7
I 7
.Bl -tag -width indent
.It Fl C
E 7
E 4
Compile code to perform runtime checks,
verify
D 4
.B assert
E 4
I 4
.Ic assert
E 4
D 2
statements,
E 2
I 2
calls,
E 2
and initialize all variables to zero as in
D 4
.IR pi .
.TP 6
.B  \-b
E 4
I 4
.Nm pi  .
D 7
.Tp Fl b
E 7
I 7
.It Fl b
E 7
E 4
Block buffer the file
D 4
.I output.
.TP 6
.B  \-i
E 4
I 4
.Ar output .
D 7
.Tp Fl i
E 7
I 7
.It Fl i
E 7
E 4
Produce a listing for
the specified procedures, functions and
D 4
.B include
E 4
I 4
.Ar include
E 4
files.
D 4
.TP 6
.B  \-l
E 4
I 4
D 7
.Tp Fl l
E 7
I 7
.It Fl l
E 7
E 4
Make a program listing during translation.
D 4
.TP 6
.B  \-s
E 4
I 4
D 7
.Tp Fl s
E 7
I 7
.It Fl s
E 7
E 4
Accept standard Pascal only;
non-standard constructs cause warning diagnostics.
D 4
.TP 6
I 2
.BR \-t " directory"
E 4
I 4
D 7
.Tp Cx Fl t
.Ws
.Ar directory
.Cx
E 7
I 7
.It Fl t Ar directory
E 7
E 4
Use the given
D 4
.I directory
E 4
I 4
.Ar directory
E 4
for compiler temporary files.
D 4
.TP 6
E 2
.B  \-z
E 4
I 4
D 7
.Tp Fl z
E 7
I 7
.It Fl z
E 7
E 4
Allow execution profiling with
D 4
.I pxp
E 4
I 4
.Nm pxp
E 4
by generating statement counters, and arranging for the
creation of the profile data file
D 4
.I pmon.out
E 4
I 4
.Pa pmon.out
E 4
when the resulting object is executed.
I 7
.El
E 7
D 4
.PP
E 4
I 4
.Pp
D 7
.Tp
E 7
E 4
Other arguments
are taken
to be loader option arguments,
perhaps libraries of
D 4
.IR pc
E 4
I 4
D 7
.Nm pc
E 7
I 7
.Nm \&pc
E 7
E 4
compatible routines.
Certain flags can also be controlled in comments within the program
as described in the
D 4
.I "Berkeley Pascal User's Manual."
.SH FILES
.ta 2.5i
file.p	pascal source files
E 4
I 4
D 7
.Em "Berkeley Pascal User's Manual."
E 7
I 7
.%T "Berkeley Pascal User's Manual."
E 7
.Sh FILES
D 7
.Dw /usr/lib.pc2.*strings
.Di L
.Dp Pa file.p
pascal source files
.Dp Pa /usr/lib/pc0
compiler
.Dp Pa /lib/f1
code generator
.Dp Pa /usr/lib/pc2
runtime integrator (inline expander)
.Dp Pa /lib/c2
peephole optimizer
.Dp Pa /usr/lib/pc3
separate compilation consistency checker
.Dp Pa /usr/lib/pc2.*strings
text of the error messages
.Dp Pa /usr/lib/how_pc
basic usage explanation
.Dp Pa /usr/lib/libpc.a
intrinsic functions and I/O library
.Dp Pa /usr/lib/libm.a
math library
.Dp Pa /lib/libc.a
standard library, see
.Xr intro 3
.Dp
E 7
I 7
.Bl -tag -width /usr/lib.pc2.*strings -compact
.It Pa file.p
Pascal source files.
.It Pa /usr/lib/pc0
Compiler.
.It Pa /lib/f1
Code generator.
.It Pa /usr/lib/pc2
Runtime integrator (inline expander).
.It Pa /lib/c2
Peephole optimizer.
.It Pa /usr/lib/pc3
Separate compilation consistency checker.
.It Pa /usr/lib/pc2.*strings
Text of the error messages.
.It Pa /usr/lib/how_pc
Basic usage explanation.
.It Pa /usr/lib/libpc.a
Intrinsic functions and
.Tn I/O
library.
.It Pa /usr/lib/libm.a
Math library.
.It Pa /lib/libc.a
Standard library, see
.Xr intro 3 .
.El
E 7
.Sh SEE ALSO
D 7
.Em Berkeley Pascal User's Manual
E 4
.br
D 4
/usr/lib/pc0	compiler
.br
/lib/f1	code generator
.br
/usr/lib/pc2	runtime integrator (inline expander)
.br
/lib/c2	peephole optimizer
.br
/usr/lib/pc3	separate compilation consistency checker
.br
D 2
/usr/lib/pc2.0strings	text of the error messages
E 2
I 2
/usr/lib/pc2.*strings	text of the error messages
E 2
.br
/usr/lib/how_pc	basic usage explanation
.br
/usr/lib/libpc.a	intrinsic functions and I/O library
.br
/usr/lib/libm.a	math library
.br
/lib/libc.a	standard library, see \fIintro\fP(3)
.SH "SEE ALSO"
Berkeley Pascal User's Manual
.br
pi(1),
pxp(1),
pxref(1),
sdb(1)
.SH DIAGNOSTICS
E 4
I 4
.Xr pi 1 ,
E 7
I 7
.Xr \&pi 1 ,
E 7
.Xr pxp 1 ,
.Xr pxref 1 ,
D 7
.\" .Xr sdb 1
E 7
I 7
.Rs
.%T "Berkeley Pascal User's Manual"
.Re
E 7
.Sh HISTORY
D 7
.Nm Pc
appeared in 4.0 BSD.
E 7
I 7
The
.Nm \&pc
appeared in
.Bx 4.0 .
E 7
.Sh DIAGNOSTICS
E 4
For a basic explanation do
D 4
.IP
.B pc
.PP
See 
.IR pi (1).
E 4
I 4
.Pp
D 7
.Df I
.Nm pc
.De 
E 7
I 7
.Bd -literal -offset indent
pc
.Ed 
E 7
.Pp
See
D 7
.Xr pi  1  .
E 7
I 7
.Xr \&pi 1  .
E 7
E 4
for an explanation of the error message format.
D 7
Internal errors cause messages containing the word SNARK.
D 4
.SH AUTHORS
E 4
I 4
.Sh AUTHORS
E 4
Charles B. Haley, William N. Joy, and Ken Thompson
.br
Retargetted to the second pass of the portable
D 4
.IR C
E 4
I 4
.Ar C
E 4
compiler by Peter Kessler
.br
Runtime library and inline optimizer by M. Kirk McKusick
.br
Separate compilation consistency checking by Louise Madrid
E 7
I 7
Internal errors cause messages containing the word
.Tn SNARK .
E 7
D 4
.SH BUGS
E 4
I 4
.Sh BUGS
E 4
The keyword
D 4
.B packed
E 4
I 4
.Ic packed
E 4
is recognized but has no effect.
D 4
.PP
E 4
I 4
.Pp
E 4
The binder is not as strict as described here,
with regard to the rules about external declarations only
in `.h' files and including `.h' files only at the outermost level.
It will be made to perform these checks in its next incarnation,
so users are warned not to be sloppy.
D 4
.PP
E 4
I 4
.Pp
E 4
The
D 4
.B \-z
E 4
I 4
.Fl z
E 4
flag doesn't work for separately compiled files.
D 4
.PP
E 4
I 4
.Pp
E 4
Because the
D 4
.B \-s
E 4
I 4
.Fl s
E 4
option is usurped by the compiler,
it is not possible to pass the strip option to the loader.
D 4
Thus programs which are to be stripped, must be run through 
.IR strip (1)
E 4
I 4
Thus programs which are to be stripped, must be run through
.Xr strip  1
E 4
after they are compiled.
E 1
