h05965
s 00002/00002/00089
d D 8.1 93/06/06 15:48:06 bostic 11 10
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00003/00002/00088
d D 6.7 91/07/30 18:24:17 cael 10 9
c pretty-up lists
e
s 00024/00024/00066
d D 6.6 91/06/02 21:22:37 cael 9 8
c mdoc version three
e
s 00002/00000/00088
d D 6.5 91/03/14 00:14:12 cael 8 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00088
d R 6.5 91/03/13 20:31:34 cael 7 6
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00000/00000/00088
d D 6.4 90/07/24 22:49:34 cael 6 5
c .Xr botch fix
e
s 00070/00070/00018
d D 6.3 90/06/11 05:57:59 cael 5 4
c converted man page
e
s 00044/00036/00044
d D 6.2 89/09/10 17:46:59 bostic 4 3
c new version from Hans Huebner
e
s 00006/00003/00074
d D 6.1 85/04/29 14:40:10 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00007/00020/00070
d D 5.1 85/04/29 14:40:01 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00090/00000/00000
d D 4.1 85/04/29 14:39:52 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 11
.\" Copyright (c) 1980, 1990 The Regents of the University of California.
.\" All rights reserved.
E 11
I 11
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 11
E 5
.\"
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
.\" %sccs.include.redist.man%
E 5
.\"
D 2
.TH NM 1 
E 2
I 2
D 3
.TH NM 1 "7 February 1983"
E 3
I 3
D 5
.TH NM 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
nm \- print name list
.SH SYNOPSIS
.B nm
[
D 2
.B \-agnopru
E 2
I 2
D 3
.B \-gnopru
E 3
I 3
D 4
.B \-agnopru
E 4
I 4
.B \-agnopruw
E 4
E 3
E 2
]
[ file ... ]
.SH DESCRIPTION
.I Nm
prints the name list (symbol table) of each object
.I file
D 2
in the argument list.
If an argument
is an archive, a listing for each object
file in the archive will be produced.
If no
E 2
I 2
D 4
in the argument list.  If an argument is an archive, a listing for each object
file in the archive will be produced.  If no
E 4
I 4
in the argument list.
If an argument is an archive, a listing for each object file in the
archive will be produced.
If no
E 4
E 2
.I file
D 2
is given, the symbols in
`a.out'
are listed.
E 2
I 2
D 4
is given, the symbols in "a.out" are listed.
E 4
I 4
is given, the symbols in ``a.out'' are listed.
E 4
E 2
.PP
D 4
Each symbol name is preceded by its value (blanks if undefined)
and one of the letters
.SM
.B U
(undefined),
.SM
.B A
(absolute),
.SM
.B  T
(text segment symbol),
.SM
.B D
(data segment symbol),
.SM
.B B
(bss segment symbol),
.SM
.B C
(common symbol),
.SM
.B f
file name,
or
.B \-
D 3
for sdb symbol table entries (see
E 3
I 3
for debugger symbol table entries (see
E 3
.B \-a
below).
D 2
If the symbol is local (non-external) the type letter is in
lower case.
E 2
I 2
If the symbol is local (non-external) the type letter is in lower case.
E 2
The output is sorted alphabetically.
.PP
Options are:
E 4
I 4
The options are as follows:
E 4
I 3
.TP
.B  \-a
Print symbol table entries inserted for use by debuggers.
E 3
.TP
D 2
.B \-a
Include all symbols in candidates for printing; normally
symbols destined for
.IR sdb (1)
are excluded.
.TP
E 2
.B  \-g
Print only global (external) symbols.
.TP
.B \-n
Sort numerically rather than alphabetically.
.TP
.B  \-o
D 2
Prepend file or archive element name to each
output line rather than only once.
E 2
I 2
Prepend file or archive element name to each output line rather than only once.
E 2
.TP
.B  \-p
Don't sort; print in symbol-table order.
.TP
.B  \-r
Sort in reverse order.
.TP
.B  \-u
Print only undefined symbols.
I 4
.TP
.B  \-w
E 5
I 5
.\"     %W% (Berkeley) %G%
.\"
I 8
D 9
.Vx
.Vx
E 9
E 8
.Dd %Q%
.Dt NM 1
.Os BSD 4
.Sh NAME
.Nm nm
.Nd display name list (symbol table)
.Sh SYNOPSIS
.Nm nm
.Op Fl agnopruw
.Ar
.Sh DESCRIPTION
The symbol table (name list) of each object in
.Ar file(s)
is displayed.
If a library (archive) is given,
.Nm 
displays a list for each
object archive member.
If
.Ar file
is not present,
.Nm
searches for the file
.Pa a.out
and if present, displays the symbol
table for
.Pa a.out .
D 9
.Pp
.Tp Fl a
E 9
I 9
D 10
.Bl -tag -width Fl
E 10
I 10
.Bl -tag -width flag
E 10
.It Fl a
E 9
Display symbol table entries inserted for use by debuggers.
D 9
.Tp Fl g
E 9
I 9
.It Fl g
E 9
Restrict display to external (global) symbols.
D 9
.Tp Fl n
E 9
I 9
.It Fl n
E 9
Present results in numerical order.
D 9
.Tp Fl o
E 9
I 9
.It Fl o
E 9
Display full path or library name of object on every line.
D 9
.Tp Fl p
E 9
I 9
.It Fl p
E 9
Do not sort at all.
D 9
.Tp Fl r
E 9
I 9
.It Fl r
E 9
Reverse order sort.
D 9
.Tp Fl u
E 9
I 9
.It Fl u
E 9
Display undefined symbols only.
D 9
.Tp Fl w
E 9
I 9
.It Fl w
E 9
E 5
Warn about non-object archive members.
Normally, nm will silently ignore all archive members which are not
object files.
D 5
.PP
E 5
I 5
D 9
.Tp
E 9
I 9
.El
E 9
.Pp
E 5
Each symbol name is preceded by its value (a blank field if the symbol
is undefined) and one of the following letters:
D 5
.TP
.B \-
E 5
I 5
D 9
.Tw Ds
.Tp Fl
E 9
I 9
D 10
.Bl -tag -width Ds -compact
E 10
I 10
.Pp
.Bl -tag -width Ds -compact -offset indent
E 10
.It Fl
E 9
E 5
debugger symbol table entries (see the
D 5
.B \-a
E 5
I 5
.Fl a
E 5
option).
D 5
.TP
.B A
E 5
I 5
D 9
.Tp Li A
E 9
I 9
.It Li A
E 9
E 5
absolute
D 5
.TP
.B B
E 5
I 5
D 9
.Tp Li B
E 9
I 9
.It Li B
E 9
E 5
bss segment symbol
D 5
.TP
.B C
E 5
I 5
D 9
.Tp Li C
E 9
I 9
.It Li C
E 9
E 5
common symbol
D 5
.TP
.B D
E 5
I 5
D 9
.Tp Li D
E 9
I 9
.It Li D
E 9
E 5
data segment symbol
D 5
.TP
.B f
E 5
I 5
D 9
.Tp Li f
E 9
I 9
.It Li f
E 9
E 5
file name
D 5
.TP
.B T
E 5
I 5
D 9
.Tp Li T
E 9
I 9
.It Li T
E 9
E 5
text segment symbol
D 5
.TP
.B U
E 5
I 5
D 9
.Tp Li U
E 9
I 9
.It Li U
E 9
E 5
undefined
D 5
.PP
E 5
I 5
D 9
.Tp
E 9
I 9
.El
E 9
.Pp
E 5
If the symbol is local (non-external) the type letter is in lower case.
The output is sorted alphabetically.
E 4
D 5
.SH SEE ALSO
ar(1), ar(5), a.out(5), stab(5)
E 5
I 5
.Sh SEE ALSO
.Xr ar 1 ,
.Xr ar 5 ,
.Xr a.out 5 ,
.Xr stab 5
.Sh HISTORY
D 9
.Nm Nm
appeared in Version 6 AT&T UNIX.
E 9
I 9
An
.Nm nm
command appeared in
.At v6 .
E 9
E 5
E 1
