h24391
s 00023/00016/00041
d D 1.2 87/08/11 23:48:05 pc 2 1
c Mods for 4.3
e
s 00057/00000/00000
d D 1.1 84/08/01 14:14:48 pc 1 0
c date and time created 84/08/01 14:14:48 by pc
e
u
U
t
T
I 1
D 2
.TH DOADUMP 8 "UKC local %G%"
E 2
I 2
.TH DUMPDEV 8L "UKC \- %G%" "Unix Programmer's Manual"
E 2
.SH NAME
D 2
doadump,dumpall \- perform cyclic file system dumps
E 2
I 2
dumpdev,dumpall \- perform cyclic file system dumps
E 2
.SH SYNOPSIS
D 2
.B /etc/doadump
E 2
I 2
.B /etc/dumpdev
E 2
.I file-system
.br
.B /etc/dumpall
.SH DESCRIPTION
D 2
.I Doadump
is used to perform cyclic dumps of the filesystem given as an argument.
It uses the locally added tape labelling facilities of the
.I dump
(8)
E 2
I 2
.I Dumpdev
is used to perform cyclic dumps for the filesystem given as an argument.
It uses the tape labelling facilities of the
.IR dump (8)
E 2
command and some data files on /etc/dumpdata which give the current
dump state and a description of the cycle which is to be used.
.PP
The main data file is
.B /etc/dumpdata/dumpcycle
which contains lines of data which specify which tape set and dump level
are to be used for a particular dump in the cycle.
The file can contain lines starting with `#' which are comments.
The columns on the file are tab separated and are:
D 2
.TP "\w'Cycle number'u+3"
E 2
I 2
.TP "\w'Map extension'u+3"
E 2
Name
D 2
the name of the device to be dumped, this is the block device name
( hp0a not rhp0a).
E 2
I 2
the name of the device to be dumped, this is the block device name;
for example, hp0a not rhp0a.
E 2
.IP "Cycle Number"
This is a number which defines the state number in the cycle to which this
line refers.
.IP "Next Cycle"
The entry gives the next entry in the cycle.
.IP "Dump level"
The dump level which is to be used for the dump.
D 2
.IP "Tapes"
A single tape, a tape range or a list of tapes which are to be used for the
E 2
I 2
.IP "Tape stem"
The
.B l
parameter to the
.I dump
program giving the constant part of the tape label.
.IP "Map extension"
The optional
.B m
argument, giving 
a single tape, a tape range or a list of tapes which are to be used for the
E 2
dump in that state.
.PP
The program maintains a file called /etc/dumpdata/<device>.state
which contains the
cycle number of the last dump action on that file system.
.PP
The program
.I /etc/dumpall
uses the
D 2
.I dump
(8)
program to determine which file systems require dumping and calls doadump
E 2
I 2
.IR dump (8)
program to determine which file systems require dumping and calls dumpdev
E 2
appropriately.
.SH FILES
/etc/dumpdata/dumpcycle
.br
/etc/dumpdata/<device>.state
.SH "SEE ALSO"
dump(8), restore(8), dumplabel(8)
.SH AUTHOR
Peter Collinson, UKC
E 1
