h32232
s 00044/00025/00010
d D 1.3 87/08/11 23:48:01 pc 3 2
c Mods for 4.3
e
s 00001/00001/00034
d D 1.2 84/08/02 09:36:21 pc 2 1
c remove the typo making label specs optional
e
s 00035/00000/00000
d D 1.1 84/08/01 13:51:44 pc 1 0
c date and time created 84/08/01 13:51:44 by pc
e
u
U
t
T
I 1
D 3
.TH DUMPLABEL 8 "UKC local %G%"
E 3
I 3
.TH DUMPLABEL 8L "UKC \- %G%" "Unix Programmer's Manual"
E 3
.SH NAME
D 3
dumplabel,dumplabpr \- file system dump labeller and label print
E 3
I 3
dumplabel \- file system dump labeller and label print
E 3
.SH SYNOPSIS
.B /etc/dumplabel
D 3
[ -f tapename ]
[ -r ]
D 2
[ label spec ]
E 2
I 2
label spec
E 2
.br
.B /etc/dumplabpr
[ tapename ]
E 3
I 3
[
.B \-f
tapename ] [
.B \-r
] [
.B \-l
label-stem ] [ label-spec ]
E 3
.SH DESCRIPTION
The program
.I dumplabel
allows initial labelling of tapes to be used for file system dumps by the
D 3
.I dump
(8) program.
If the -f switch is given, the following argument is used as the device which
E 3
I 3
.IR dump (8)
program.
If the 
.B f
switch is given, the following argument is used as the device which
E 3
is to be used for labelling (default /dev/rmt8).
D 3
The -r switch rewinds the tape and puts the tape offline after each label is
made.
The optional arguments may be followed by one or more tape label
specificiations.
A tape label is assumed to be a six character string of three letters
followed by three digits.
The tape specification may contain a range of the form LLLnnn-eee, where
nnn is a decimal number lower than eee.
If a tape range is given, the operator is prompted to mount tapes.
E 3
I 3
The
.B r
switch rewinds the tape and puts the tape offline after each label is made.
These optional arguments may be followed by one or more tape label specificiations.
If none specifications
are present, the tape is opened, the header read and the label printed.
E 3
.PP
D 3
The program /etc/dumplabpr
prints the tape label on the currently mounted tape.
If the tape drive to be used is not /dev/rmt8, then the command can
be followed by an alternative tape device name.
E 3
I 3
The label specification is similar in style to the arguments for the dump program.
The 
.B l
argument gives the label stem, with an optional `%s' being used to show
the position in the string which is replaced by the variable section
given by the remaining program arguments.
For example
.IP
dumplabel -l TA%s 000,100-103,aaa,NAA-NAC
.PP
will generate TA000, TA100, TA101, TA102, TA103, TAaaa, TANAA, TANAB and TANAC.
If the
.B l
switch is omitted, then the label is taken from the program argument.
This means that
.IP
dumplabel -l sources
.PP
is equivalent to
.IP
dumplabel sources
.PP
Labels are limited to 15 characters.
E 3
.SH "SEE ALSO"
D 3
dump(8), restore(8)
E 3
I 3
dump(8), restore(8), dumpdev(8), dumpall(8)
E 3
E 1
