/* DO NOT EDIT THIS FILE */
#include <stddef.h>
#include <db.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/signal.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/ioctl.h>
#include <sys/tty.h>
#include <sys/systm.h>
#include <sys/proc.h>
#include <sys/vnode.h>
#include <ufs/ufs/quota.h>
#include <ufs/ufs/inode.h>
#include "lffs.h"
#include "lffs_auto.h"

CREATE_args *
CREATE_READ(char *buf)
{
	CREATE_args	*argp;
	int	n;
	u_long u;

	argp = (CREATE_args *)malloc(sizeof(CREATE_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->new_inum, sizeof(argp->new_inum));
	buf += sizeof(argp->new_inum);
	bcopy(buf, &argp->new_gen, sizeof(argp->new_gen));
	buf += sizeof(argp->new_gen);
	bcopy(buf, &argp->new_uid, sizeof(argp->new_uid));
	buf += sizeof(argp->new_uid);
	bcopy(buf, &argp->new_gid, sizeof(argp->new_gid));
	buf += sizeof(argp->new_gid);
	bcopy(buf, &argp->new_mode, sizeof(argp->new_mode));
	buf += sizeof(argp->new_mode);
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->new_name = buf;
	buf += n + 1;
	bcopy(buf, &argp->dir_inum, sizeof(argp->dir_inum));
	buf += sizeof(argp->dir_inum);
	bcopy(buf, &argp->dir_gen, sizeof(argp->dir_gen));
	buf += sizeof(argp->dir_gen);
	bcopy(buf, &argp->dir_nlink, sizeof(argp->dir_nlink));
	buf += sizeof(argp->dir_nlink);
	return(argp);
}
IALLOC_args *
IALLOC_READ(char *buf)
{
	IALLOC_args	*argp;
	int	n;
	u_long u;

	argp = (IALLOC_args *)malloc(sizeof(IALLOC_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->new_inum, sizeof(argp->new_inum));
	buf += sizeof(argp->new_inum);
	return(argp);
}
REMOVE_args *
REMOVE_READ(char *buf)
{
	REMOVE_args	*argp;
	int	n;
	u_long u;

	argp = (REMOVE_args *)malloc(sizeof(REMOVE_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->rem_name = buf;
	buf += n + 1;
	bcopy(buf, &argp->dir_inum, sizeof(argp->dir_inum));
	buf += sizeof(argp->dir_inum);
	bcopy(buf, &argp->dir_gen, sizeof(argp->dir_gen));
	buf += sizeof(argp->dir_gen);
	return(argp);
}
LINK_args *
LINK_READ(char *buf)
{
	LINK_args	*argp;
	int	n;
	u_long u;

	argp = (LINK_args *)malloc(sizeof(LINK_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->new_name = buf;
	buf += n + 1;
	bcopy(buf, &argp->new_link_nlink, sizeof(argp->new_link_nlink));
	buf += sizeof(argp->new_link_nlink);
	bcopy(buf, &argp->link_inum, sizeof(argp->link_inum));
	buf += sizeof(argp->link_inum);
	bcopy(buf, &argp->link_gen, sizeof(argp->link_gen));
	buf += sizeof(argp->link_gen);
	bcopy(buf, &argp->dir_inum, sizeof(argp->dir_inum));
	buf += sizeof(argp->dir_inum);
	bcopy(buf, &argp->dir_gen, sizeof(argp->dir_gen));
	buf += sizeof(argp->dir_gen);
	bcopy(buf, &argp->new_dir_nlink, sizeof(argp->new_dir_nlink));
	buf += sizeof(argp->new_dir_nlink);
	return(argp);
}
SYMLINK_args *
SYMLINK_READ(char *buf)
{
	SYMLINK_args	*argp;
	int	n;
	u_long u;

	argp = (SYMLINK_args *)malloc(sizeof(SYMLINK_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->new_inum, sizeof(argp->new_inum));
	buf += sizeof(argp->new_inum);
	bcopy(buf, &argp->new_gen, sizeof(argp->new_gen));
	buf += sizeof(argp->new_gen);
	bcopy(buf, &argp->new_uid, sizeof(argp->new_uid));
	buf += sizeof(argp->new_uid);
	bcopy(buf, &argp->new_gid, sizeof(argp->new_gid));
	buf += sizeof(argp->new_gid);
	bcopy(buf, &argp->new_mode, sizeof(argp->new_mode));
	buf += sizeof(argp->new_mode);
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->new_name = buf;
	buf += n + 1;
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->link_name = buf;
	buf += n + 1;
	bcopy(buf, &argp->dir_inum, sizeof(argp->dir_inum));
	buf += sizeof(argp->dir_inum);
	bcopy(buf, &argp->dir_gen, sizeof(argp->dir_gen));
	buf += sizeof(argp->dir_gen);
	return(argp);
}
RENAME_args *
RENAME_READ(char *buf)
{
	RENAME_args	*argp;
	int	n;
	u_long u;

	argp = (RENAME_args *)malloc(sizeof(RENAME_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->ren_inum, sizeof(argp->ren_inum));
	buf += sizeof(argp->ren_inum);
	bcopy(buf, &argp->ren_gen, sizeof(argp->ren_gen));
	buf += sizeof(argp->ren_gen);
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->old_name = buf;
	buf += n + 1;
	bcopy(buf, &n, sizeof(n));
	buf += sizeof(n);
	argp->new_name = buf;
	buf += n + 1;
	bcopy(buf, &argp->old_dir_inum, sizeof(argp->old_dir_inum));
	buf += sizeof(argp->old_dir_inum);
	bcopy(buf, &argp->old_dir_gen, sizeof(argp->old_dir_gen));
	buf += sizeof(argp->old_dir_gen);
	bcopy(buf, &argp->old_dir_nlink, sizeof(argp->old_dir_nlink));
	buf += sizeof(argp->old_dir_nlink);
	bcopy(buf, &argp->new_dir_inum, sizeof(argp->new_dir_inum));
	buf += sizeof(argp->new_dir_inum);
	bcopy(buf, &argp->new_dir_gen, sizeof(argp->new_dir_gen));
	buf += sizeof(argp->new_dir_gen);
	bcopy(buf, &argp->new_dir_nlink, sizeof(argp->new_dir_nlink));
	buf += sizeof(argp->new_dir_nlink);
	return(argp);
}
ALLOC_args *
ALLOC_READ(char *buf)
{
	ALLOC_args	*argp;
	int	n;
	u_long u;

	argp = (ALLOC_args *)malloc(sizeof(ALLOC_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->inum, sizeof(argp->inum));
	buf += sizeof(argp->inum);
	bcopy(buf, &argp->gen, sizeof(argp->gen));
	buf += sizeof(argp->gen);
	bcopy(buf, &argp->lbn, sizeof(argp->lbn));
	buf += sizeof(argp->lbn);
	bcopy(buf, &argp->pbn, sizeof(argp->pbn));
	buf += sizeof(argp->pbn);
	bcopy(buf, &argp->nfrags, sizeof(argp->nfrags));
	buf += sizeof(argp->nfrags);
	return(argp);
}
ABORT_args *
ABORT_READ(char *buf)
{
	ABORT_args	*argp;
	int	n;
	u_long u;

	argp = (ABORT_args *)malloc(sizeof(ABORT_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->inum, sizeof(argp->inum));
	buf += sizeof(argp->inum);
	bcopy(buf, &argp->gen, sizeof(argp->gen));
	buf += sizeof(argp->gen);
	bcopy(buf, &argp->atype, sizeof(argp->atype));
	buf += sizeof(argp->atype);
	return(argp);
}
LOGICAL_args *
LOGICAL_READ(char *buf)
{
	LOGICAL_args	*argp;
	int	n;
	u_long u;

	argp = (LOGICAL_args *)malloc(sizeof(LOGICAL_args));
	if (argp == NULL)
		return(NULL);
	bcopy(buf, &argp->machine, sizeof(u_long));
	buf += sizeof(u_long);
	bcopy(buf, &argp->time, sizeof(struct timeval));
	buf += sizeof(struct timeval);
	bcopy(buf, &argp->type, sizeof(argp->type));
	buf += sizeof(argp->type);
	bcopy(buf, &argp->inum, sizeof(argp->inum));
	buf += sizeof(argp->inum);
	bcopy(buf, &argp->gen, sizeof(argp->gen));
	buf += sizeof(argp->gen);
	bcopy(buf, &argp->lbn, sizeof(argp->lbn));
	buf += sizeof(argp->lbn);
	return(argp);
}
void *
lffs_switch(char *buf, long type)
{
	switch(type) {
		case REC_CREATE:
			return(CREATE_READ(buf));
		case REC_IALLOC:
			return(IALLOC_READ(buf));
		case REC_REMOVE:
			return(REMOVE_READ(buf));
		case REC_LINK:
			return(LINK_READ(buf));
		case REC_SYMLINK:
			return(SYMLINK_READ(buf));
		case REC_RENAME:
			return(RENAME_READ(buf));
		case REC_ALLOC:
			return(ALLOC_READ(buf));
		case REC_ABORT:
			return(ABORT_READ(buf));
		case REC_LOGICAL:
			return(LOGICAL_READ(buf));
		default:
		return(NULL);
	}
}
