/* DO NOT EDIT THIS FILE */
#include <stddef.h>
#include <db.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/signal.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/ioctl.h>
#include <sys/tty.h>
#include <sys/systm.h>
#include <sys/proc.h>
#include <sys/vnode.h>
#include <ufs/ufs/quota.h>
#include <ufs/ufs/inode.h>
#include "lffs.h"
#include "lffs_auto.h"

void
CREATE_PRINT(CREATE_args *argp)
{
	printf("%s: type:%d, new_inum:%d, new_gen:0x%x, new_uid:%d, new_gid:%d, new_mode:0x%hx, new_name:%s, dir_inum:%d, dir_gen:0x%x, dir_nlink:%hd\n",
	    log_names[argp->type], argp->type, argp->new_inum, argp->new_gen, 
	    argp->new_uid, argp->new_gid, argp->new_mode, argp->new_name, 
	    argp->dir_inum, argp->dir_gen, argp->dir_nlink);
}
void
IALLOC_PRINT(IALLOC_args *argp)
{
	printf("%s: type:%d, new_inum:%d\n",
	    log_names[argp->type], argp->type, argp->new_inum);
}
void
REMOVE_PRINT(REMOVE_args *argp)
{
	printf("%s: type:%d, rem_dip:0x%x, rem_name:%s, dir_inum:%d, dir_gen:0x%x\n",
	    log_names[argp->type], argp->type, argp->rem_dip, argp->rem_name, 
	    argp->dir_inum, argp->dir_gen);
}
void
LINK_PRINT(LINK_args *argp)
{
	printf("%s: type:%d, new_name:%s, new_link_nlink:%hd, link_inum:%d, link_gen:0x%x, dir_inum:%d, dir_gen:0x%x, new_dir_nlink:%hd\n",
	    log_names[argp->type], argp->type, argp->new_name, argp->new_link_nlink, 
	    argp->link_inum, argp->link_gen, argp->dir_inum, argp->dir_gen, 
	    argp->new_dir_nlink);
}
void
SYMLINK_PRINT(SYMLINK_args *argp)
{
	printf("%s: type:%d, new_inum:%d, new_gen:0x%x, new_uid:0x%x, new_gid:0x%x, new_mode:0x%hx, new_name:%s, link_name:%s, dir_inum:%d, dir_gen:0x%x\n",
	    log_names[argp->type], argp->type, argp->new_inum, argp->new_gen, 
	    argp->new_uid, argp->new_gid, argp->new_mode, argp->new_name, 
	    argp->link_name, argp->dir_inum, argp->dir_gen);
}
void
RENAME_PRINT(RENAME_args *argp)
{
	printf("%s: type:%d, ren_inum:%d, ren_gen:0x%x, old_name:%s, new_name:%s, old_dir_inum:%d, old_dir_gen:0x%x, old_dir_nlink:%hd, new_dir_inum:%d, new_dir_gen:0x%x, new_dir_nlink:%hd\n",
	    log_names[argp->type], argp->type, argp->ren_inum, argp->ren_gen, 
	    argp->old_name, argp->new_name, argp->old_dir_inum, argp->old_dir_gen, 
	    argp->old_dir_nlink, argp->new_dir_inum, argp->new_dir_gen, argp->new_dir_nlink);
}
void
ALLOC_PRINT(ALLOC_args *argp)
{
	printf("%s: type:%d, inum:%d, gen:0x%x, lbn:0x%x, pbn:0x%x, nfrags:0x%x\n",
	    log_names[argp->type], argp->type, argp->inum, argp->gen, 
	    argp->lbn, argp->pbn, argp->nfrags);
}
void
ABORT_PRINT(ABORT_args *argp)
{
	printf("%s: type:%d, inum:%d, gen:0x%x, atype:0x%x\n",
	    log_names[argp->type], argp->type, argp->inum, argp->gen, 
	    argp->atype);
}
void
LOGICAL_PRINT(LOGICAL_args *argp)
{
	printf("%s: type:%d, inum:%d, gen:0x%x, lbn:0x%x\n",
	    log_names[argp->type], argp->type, argp->inum, argp->gen, 
	    argp->lbn);
}
void *
lffs_print(long type, void *rp)
{
	switch(type) {
		case REC_CREATE:
			CREATE_PRINT(rp);
			return;
		case REC_IALLOC:
			IALLOC_PRINT(rp);
			return;
		case REC_REMOVE:
			REMOVE_PRINT(rp);
			return;
		case REC_LINK:
			LINK_PRINT(rp);
			return;
		case REC_SYMLINK:
			SYMLINK_PRINT(rp);
			return;
		case REC_RENAME:
			RENAME_PRINT(rp);
			return;
		case REC_ALLOC:
			ALLOC_PRINT(rp);
			return;
		case REC_ABORT:
			ABORT_PRINT(rp);
			return;
		case REC_LOGICAL:
			LOGICAL_PRINT(rp);
			return;
	}
}
