h56347
s 00022/00016/00024
d D 8.2 94/03/31 16:06:09 bostic 11 10
c POSIX 1003.2B/D9 symbolic links
e
s 00002/00002/00038
d D 8.1 93/06/06 14:38:30 bostic 10 9
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00005/00036
d D 6.6 91/07/29 23:07:39 cael 9 8
c mdoc version three
e
s 00006/00007/00035
d D 6.5 91/06/17 15:42:58 bostic 8 7
c minor cleanup, add BUGS section
e
s 00003/00001/00039
d D 6.4 91/03/14 00:16:50 cael 7 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00040
d R 6.4 91/03/13 20:32:56 cael 6 5
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00000/00000/00040
d D 6.3 90/07/24 22:45:02 cael 5 4
c .Xr botch fix
e
s 00039/00022/00001
d D 6.2 90/06/24 19:03:31 cael 4 3
c converted man page
e
s 00001/00001/00022
d D 6.1 85/04/29 20:08:34 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00022
d D 5.1 85/04/29 20:07:57 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00023/00000/00000
d D 4.1 85/04/29 20:07:38 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 4
.\"	%W% (Berkeley) %G%
E 4
I 4
D 10
.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
E 10
I 10
D 11
.\" Copyright (c) 1990, 1993
E 11
I 11
.\" Copyright (c) 1990, 1993, 1994
E 11
.\"	The Regents of the University of California.  All rights reserved.
E 10
E 4
.\"
D 2
.TH FILE 1 
E 2
I 2
D 3
.TH FILE 1  "18 January 1983"
E 3
I 3
D 4
.TH FILE 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
file \- determine file type
.SH SYNOPSIS
.B file
file ...
.SH DESCRIPTION
.I File
performs a series of tests on each argument
in an attempt to classify it.
If an argument appears to be ascii,
.I file
examines the first 512 bytes
and tries to guess its language.
.SH BUGS
It often makes mistakes.
In particular it often suggests that
command files are C programs.
.PP
Does not recognize Pascal or LISP.
E 4
I 4
.\" %sccs.include.redist.man%
.\"
.\"     %W% (Berkeley) %G%
.\"
I 7
D 9
.Vx
.Vx
E 9
E 7
.Dd %Q%
.Dt FILE 1
D 7
.Os BSD 4.4
E 7
I 7
.Os
E 7
.Sh NAME
.Nm file
.Nd identify file content
.Sh SYNOPSIS
.Nm file
D 11
.Ar
E 11
I 11
.Op Fl h
.Ar file ...
E 11
.Sh DESCRIPTION
.Nm File
D 11
tests the given argument(s) and reports
the content type(s). 
If
the file type is text,
it attempts to determine
the type of text (e.g.
E 11
I 11
tests the specified files and attempts to classify them.
If a file is a text file,
it attempts to determine the type of text (e.g.
E 11
.Xr csh 1
D 8
commands or C code)
.Pp
As several tests
are used and
.Nm file
E 8
I 8
D 11
commands or C code).
E 11
I 11
commands or C source code).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
If a symbolic link is specified, identify the file as a symbolic
link.
By default, symbolic links are only identified if they reference
non-existent files.
.El
.Sh COMPATIBILITY
Previous implementations of the
.Nm file
utility did not follow symbolic links by default.
E 11
.Sh BUGS
As many tests are used and
D 11
.Nm
E 8
stops testing on the first successful one,
it can make mistakes.
D 8
.Pp
.Nm File
E 8
I 8
In particular, 
.Nm
E 8
D 9
does not recognize Pascal or LISP.
.\" .Sh ENVIRONMENT
E 9
I 9
does not recognize Pascal or
.Tn LISP .
E 11
I 11
.Nm file
stops testing on the first successful one, it can often make mistakes.
E 11
E 9
.Sh HISTORY
A
.Nm file
D 9
command appeared in Version 6 AT&T UNIX.
E 9
I 9
command appeared in
.At v6 .
E 9
E 4
E 1
