h04684
s 00002/00002/00077
d D 8.1 93/06/05 11:22:01 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00023/00000/00056
d D 5.5 93/05/03 15:49:15 hibler 5 4
c document -A (annex) and -F (flowcontrol) options
e
s 00003/00003/00053
d D 5.4 93/03/23 18:57:24 cael 4 3
c update .Os and history from .Ud to .Bx 4.4
e
s 00005/00003/00051
d D 5.3 91/05/09 16:29:47 cael 3 2
c delete references to 4.4
e
s 00046/00035/00008
d D 5.2 91/04/22 15:15:12 cael 2 1
c mdoc conversion
e
s 00043/00000/00000
d D 5.1 90/10/20 17:44:34 mckusick 1 0
c date and time created 90/10/20 17:44:34 by mckusick
e
u
U
t
T
I 1
D 2
.\" Copyright (c) 1990 The Regents of the University of California.
E 2
I 2
D 6
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 2
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
.\"
D 3
.\" %sccs.include.redist.man%
E 3
I 3
.\" %sccs.include.redist.roff%
E 3
.\"
D 2
.\"	%W% (Berkeley) %G%
E 2
I 2
.\"     %W% (Berkeley) %G%
E 2
.\"
D 2
.TH STARTSLIP 1 "%Q%"
.UC 7
.SH NAME
startslip \- dial up and log in to a slip server
.SH SYNOPSIS
.B startslip
[
.B \-d
] [
.B \-s
string
]
dev user passwd
.SH DESCRIPTION
.I Startslip
opens the specified device.
If the
.B \-s
option is specified, the optional string is written to the device.
For a dialup modem,
the string is used to specify a dial sequence.
E 2
I 2
.Dd %Q%
.Dt STARTSLIP 1
D 3
.Os BSD 4.4
E 3
I 3
D 4
.Os
E 4
I 4
.Os BSD 4.4
E 4
E 3
.Sh NAME
.Nm startslip
.Nd dial up and login to a slip server
.Sh SYNOPSIS
.Nm startslip
.Op Fl d
.Op Fl s Ar string
I 5
.Op Fl A Ar annexname
.Op Fl F Ar flowcontrol
E 5
.Ar device user passwd
.Sh DESCRIPTION
.Nm Startslip
opens the specified
.Ar device .
.Pp
E 2
Once carrier is asserted
D 2
.I startslip
attempts to login as the specified user with the given password.
If successful, it sets the device into the slip line discipline.
If carrier drops and a SIGHUP is sent to
.I startslip ,
E 2
I 2
.Nm startslip
attempts to login as the specified
.Ar user
with the given
.Ar password .
If successful, it puts the device into the slip line discipline.
If carrier drops and a
.Dv SIGHUP
is sent to
.Nm startslip ,
E 2
it closes the device and attempts to repeat the dialup and login sequence.
D 2
.PP
If the
.B \-d
option is specified,
.B startslip
E 2
I 2
.Pp
Available options:
.Bl -tag -width Ar
.It Fl d
.Nm Startslip
E 2
prints out debugging information about what it is trying to do.
D 2
.SH "SEE ALSO"
sliplogin(8)
E 2
I 2
.It Fl s Ar string
The optional
.Ar string
is written to
.Ar device .
For a dialup modem,
the string is used to specify a dial sequence.
I 5
.It Fl A Ar annexname
.Nm Startslip
assumes it is connecting to a Xylogics Annex box and engages in an
appropriate dialog using the
.Ar user
and
.Ar passwd
arguments.
The
.Ar annexname
argument is a string that is used to match against the Annex prompt
to determine when a connection has been established.
.It Fl F Ar flowcontrol
Determines the type of flow control used on
.Ar device .
Choices for
.Ar flowcontrol
are
``none'' for no flow control (the default),
``hw'' for hardware RTS/CTS flow control and
``sw'' for software XON/XOFF flow control.
E 5
.El
D 3
.Pp
E 3
.Sh SEE ALSO
.Xr sliplogin 8
.Sh HISTORY
I 3
The
.Nm startslip
D 4
command is
E 3
.Ud .
E 4
I 4
appeared in
.Bx 4.4 .
E 4
E 2
E 1
