.TH AEDPLOT 1 
.UC 4
.SH NAME
aedplot \- plot on AED512 display
.SH SYNOPSIS
.B aedplot
[
.B \-g
display ] [ file ]
.br
.SH DESCRIPTION
.I Aedplot
reads a set of plotting commands and outputs a command sequence
that will generate a picture on an AED512 color graphics display.
The input to
.I aedplot
consists of a sequence of plotting commands in the standard format
described in plot(5).  The output consists of an
equivalent set of commands to
the AED display.  If
.I file
is specified, then input is taken from it.  Otherwise
the plotting commands are read from the standard input.
If the
.B \-g
switch is specified, then
.I display
is the name of the file (generally the name of the special
file for a serial line connecting to a graphics display)
to which output is written.
If the
.B \-g
switch is not specified, then
.I aedplot
checks to see if there is
an AED display associated with the terminal from which the program is
being run.  If so, that display is used.
.SH "SEE ALSO"
plot(1), plot(5)
.SH AUTHOR
John Ousterhout
.SH BUGS
Arcs are not drawn correctly.  At present, arc commands result
in the generation of a straight line segment between the end
points of the arc.  Large circles are not drawn at all;  this
is a problem with the AED display microcode.
