.TH CHECKOUT DDBS 
.SH NAME
checkout(DDBS)	verify correctness of data file form
.SH SYNOPSIS
checkout [-d dictionary_file] specification_file data_file
.SH DESCRIPTION
\fICheckout\fR checks the correctness of DDBS data file
entries in two ways.
First, all key words are checked against those in the
specification file to make sure all are allowed and there are
no duplications within any single entry.
Second, \fIcheckout\fR checks to see that data entered in each
field is of the correct type (numeric, alphanumeric, etc.).
\fICheckout\fR is useful to verify changes made to a data file
with one of the editors (e.g., vi or ex).
.SH EXAMPLE
Run the following data file through \fIcheckout\fR:
.nf

dt 770108
nm doe, j.p.
ph 814-1234
$
dt 770108
nm doe, j.d.
ph 814-1234
$
dt Jan. 8, 1977
nm smith, m.j.
ph 526-4321
$
dt 770110
nm johnson, a.b.
ph 524-9876
$
.PP
and \fIcheckout\fR will print the following error message:
.nf

datafile
item   3, line 9 is bad. Bad integer field               Jan. 8, 1977
.PP
After editing the file and changing ``Jan. 8, 1977'' to ``770108'', if you
run the data file again through \fIcheckout\fR, the only response will be:

datafile
% 				
.PP
No comment means the data file is OK.
.SH "SEE ALSO"
.nf
ddcodes(DDBS)   ddbs Specification file codes
r_files(II)	ddbs Raw data files
f_files(II)	ddbs Specification files
checkin(DDBS)	input/append to and verify a data file
