.TH CPR L
.SH NAME
cpr \- print files to printer connected to Concept-108
.SH SYNOPSIS
.B cpr
[
.B \-e
] [
.B \-f
] [
file ...
]
.SH DESCRIPTION
.I Cpr
prints the named
.IR file s
(standard input default)
to a printer connected to the printer port
of a Concept-108 terminal.
Backspaces and overstrikes are converted to use carriage returns
so that naive printers
(e.g., the Okidata Microline series)
will print correctly.
.PP
The
.B \-e
flag will echo output on the terminal
while printing.
The
.B \-f
flag will add an extra form feed after printing.
.PP
If the
.SM SYSLINE
environment variable is defined,
the value will be interpreted as an integer process id,
and a
.SM SIGSTOP
signal will be sent before printing
to avoid interference from the
.IR sysline (1)
program.
A
.SM SIGCONT
signal will be sent after printing.
.PP
The terminal must be preconfigured to handle flow control
to the printer.
.SH CAVEATS
This program has only been tested with a Concept-108
connected to an Okidata Microline 83A.
.SH SEE ALSO
sysline(1)
