.TH DOORCARD LOCAL
.UC 4
.SH NAME
doorcard \- make name cards for doors
.SH SYNOPSIS
.B doorcard
.SH DESCRIPTION
.I Doorcard
reads the standard input for a list of 1 to 5 names,
and prints on the standard output
a set of troff commands
to place the names in a box
of proper dimensions for the nameplates
on the doors of Evans Hall.
The point size
for the names
are picked according to the number of names.
For example,
to print the names
``Richard Nixon'',
``Spiro Agnew'',
and
``Ronald Ziegler''
on a door card,
put the names on three seperate lines in a file and say:
.IP
.B doorcard <
.I file
.B | troff
.SH BUGS
Should handle larger numbers of names,
probably by columnarization.
