.TH MTROLL 1
.SH NAME
Trollinfo \- Shell script to install the meta relations 
.SH SYNOPSIS
.B mtroll
database
.SH DESCRIPTION
Mtroll is a shell script to create and update the
\fIrelations\fR relation and \fIattributes\fR relation in the database.
The structure of the relations is 
.DS
relation relations[key relname] of
	rel_name		:string;
	rel_attrs		:integer;
	rel_keys		:integer;
	rel_owner		:string;
	rel_comment		:string
end;
 
relation attributes[key att_rel,att_name] of
	att_rel, att_name	:string;
	att_keynr		:integer; {key number when applicable}
	att_domain		:string;  {domain encoding}
	att_alias		:string;  {alias used within focus}
	att_comment   		:string;  {alternative description}
	att_example		:string;  {example attribute value}
end;
.DE
The attributes relation is used by Focus to set attribute aliases and
to provide the information for the 'explain' command.
.SH "SEE ALSO"
focus, troll
.SH BUGS
The relations must be filled manually.  Thus, there is no guarantee of
consistency between its
content and the actual relations in the database.
