.TH NCHK 1 duke
.SH NAME
nchk - check for news
.SH SYNOPSIS
nchk
[
.B \-yne
]
[
news args
]
.SH DESCRIPTION
.I Nchk
returns an exit status of
zero
if you have news,
and
one
if you haven't.
The
.B y
option
prints "You have news." if you have news,
and the
.B n
option
prints "No news." if you haven't.
.PP
The
.B e
option causes
.I nchk
to exec the
.IR netnews (1)
program with the given
.I "news args"
if there is news.
.PP
For compatibility with the
.IR msgs (1)
program, the
.B q
option is the same as
.BR y ,
and the
.B f
option is the same as
.BR e .
.SH FILES
.TP 30
/usr/spool/news/.bitfile
Bitmap maintained by
.I netnews(1)
.SH SEE ALSO
netnews(1), msgs(1)
