.TH RECNEWS 1
.SH NAME
recnews \- receive unprocessed articles via mail
.SH SYNOPSIS
recnews [ newsgroup [ sender ] ]
.SH DESCRIPTION
.I recnews
reads a letter from the standard input; determines the article title,
sender, and newsgroup; and gives the body to inews with the right
arguments for insertion.
.PP
If
.I newsgroup
is omitted, the to line of the letter will be used.  If
.I sender
is omitted, the sender will be determined from the from line of the letter.
The title is determined from the subject line.
.SH SEE ALSO
inews(1),
uurec(1),
sendnews(1),
readnews(1),
newscheck(1)
