.TH RECOVER 1
.SH NAME
Recover \- Shell script to recover from crashes
.SH SYNOPSIS
.B recover
database
.SH DESCRIPTION
Recover is a shell script to get rid of lock files, core files,
and Troll temporaries after a Troll crash or a system crash where
Troll was in use.
.SH "SEE ALSO"
.SH BUGS
Transaction recovery is not yet implemented.
.SH AUTHORS
