.TH RESCUE 1 5/23/80
.UC
.SH NAME
rescue \- rescue messages from MH data base
.SH SYNOPSIS
.B rescue
name ...
.SH DESCRIPTION
.I Rescue
reads the named files, which are assumed to be MH messages, and
outputs on standard output a file compatible with mail(1) and Mail(1).
.I Rescue
checks the input files and only accepts those whose names are
decimal numbers, disregarding those beginning with a comma or named
``cur'' or ``select.''
.SH DIAGNOSTICS
Complains about non-MH files encountered.
When finished,
.I rescue
prints the number of ARPA style dates that could not be converted
to UNIX format.  These dates are replaced with the current date.
.SH AUTHOR
Kurt Shoens
.SH BUGS
Time zone information in dates is thrown away.
