.TH TROLLSORT 1 
.SH NAME
trollsort	- utility to sort Troll copy files
.SH SYNOPSIS
.B trollsort
[-u] {[-a<fieldrange>] [-d<fieldrange>]}
.SH DESCRIPTION
The trollsort utility is a variation of the sort(1) command.
It can be used to sort Troll/USE copy files before bulk insertion or
before printing the result of a database retrieval.
The command reads tuples from standard input and writes the
sorted list on standard output. 
An optional sort list may be given to direct sort order.
The sort list consists of field ranges together with the ascending or
descending sort order flag.
Each field range is either an integer indicating the field in the
tuple constructor (starting counting at 1) or a range of fields
specified by a lower and upper bound (<number>-<number>)
Omission of the sort list results in sorting the tuples in
ascending field order.
.br
The flag -u indicates removal of duplicates during sorting.
Note that the uniqueness property is checked for the indicated attributes only.
.SH FILES
.SH SEE ALSO
sort(1)
.SH DIAGNOSTICS
.SH BUGS
Very large tuples may cause the buffers to overflow and cause
the process to abort.
.SH AUTHOR
Martin L. Kersten
