.TH UNDUMP 1 "University of Utah"
.SH NAME
undump \- convert a core dump to an executable a.out file
.SH SYNOPSIS
undump new-a.out-file [old-a.out-file] [core-file]
.SH DESCRIPTION
Undump takes a core dump file and the executable "a.out" file which
caused it and produces a new executable file with all static
variables initialised to the values they held at the time of the
core dump.  It is primarily useful for programs which take a long time
to initialise themselves, e.g. Emacs.  The idea is to go through all of
the initialisations and then create a core dump (e.g. with the abort()
call).  One then uses undump to make a new executable file with all of it
done.  This usually implies the use of a global flag variable which says
whether or not initialisation has been done.
.PP
Undump's arguments, old-a.out-file and core-file, default to "a.out" and
"core", respectively.
.PP
A few things to keep in mind about undump:
.IP
It doesn't preserve open files.
.IP
The program will be re-entered at the beginning of main(), not at the point
where the core dump occurred.
.SH BUGS
Probably should have an option to not require
old-a.out-file if the core came from a 407 file.
