/* A lexical scanner generated by flex */

/* scanner skeleton version:
 *
 * $Header: flex/RCS/flex.skel,v 2.13 90/05/26 17:24:13 vern Exp $
 *
 *	@(#)lex.skel	5.2 (Berkeley) 6/18/90
 */

#define FLEX_SCANNER

#include <stdio.h>

#ifdef __STDC__

#ifndef DONT_HAVE_STDLIB_H
#include <stdlib.h>
#else
void *malloc( unsigned );
void free( void* );
#endif

#define YY_USE_PROTOS
#define YY_USE_CONST
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#ifndef __STDC__
#include <stdlib.h>
#endif

#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#endif


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* there's no standard place to get these definitions */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "picl.l"
#define INITIAL 0
#define A 1
#define str 2
#define def 3
#define sc 4
#define br 5
#define thru 6
#define sh 7
# line 10 "picl.l"
#undef	input
#undef	unput
#include <stdio.h>
#include <ctype.h>
#include "pic.h"
#include "y.tab.h"

extern	float	atof();
extern	struct	symtab	symtab[];
extern	char	*filename, *copythru();

#define	CADD	cbuf[clen++]=yytext[0]; if(clen>=CBUFLEN-1) {yyerror("string too long", cbuf); BEGIN A;}
#define	CBUFLEN	500
char	cbuf[CBUFLEN];
int	c, clen, cflag, delim;
int	ifsw	= 0;	/* 1 if if statement in progress */
# line 33 "picl.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 141
typedef int yy_state_type;
static const short int yy_accept[541] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  141,  140,  139,    1,
        3,  109,  131,  138,  139,  139,  139,  129,    4,  106,
      139,  105,  130,  130,  139,  139,    6,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  139,    5,    9,  130,  137,
      133,  132,  137,  125,  116,  116,  123,  122,  104,  138,
      107,   78,  129,   35,   36,   28,    0,   31,   32,   29,
       34,   33,   30,   80,   81,  129,  129,    0,  129,    0,
        0,    0,    0,   77,  103,  101,  102,  130,  130,   19,

        2,  130,  130,  130,   87,  130,  130,   88,  130,  130,
      130,  130,  130,  130,   63,  130,  130,  130,  113,  130,
      130,  130,  130,  130,  130,  130,  130,   54,  118,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,   25,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,   86,  130,   61,  130,  130,  130,  108,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,  130,  134,  136,  135,  125,
      116,  122,    0,    0,    0,    0,    0,   82,    0,   39,
        0,   41,    0,    0,   40,    0,    0,   42,    0,    0,

        0,  129,    0,  129,  128,   79,  130,  130,   24,   13,
      130,  130,  130,  130,  130,   11,   65,  130,  130,  130,
      130,  130,   94,  130,  130,  130,   67,  130,  130,  130,
      130,  130,   92,  130,  130,  111,  130,  130,  130,  100,
      130,  130,  130,  130,  130,   91,   98,   99,  130,  130,
      130,   56,  130,  130,  130,  130,  130,  121,   93,  130,
      130,  130,  130,  130,  130,   26,  130,  130,  130,  130,
       27,  130,   55,  130,    9,    9,    8,    7,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,  130,   35,    0,

        0,   38,    0,    0,    0,   84,    0,    0,    0,   33,
        0,   83,  110,  130,  130,  130,  130,  130,  130,  130,
       69,  130,  130,  114,   68,  130,   57,  130,   62,  130,
      130,  120,    0,   71,  130,   85,  130,  130,  130,   90,
       59,   17,  130,   18,  130,  130,  130,   97,  130,  130,
      130,   22,   58,  130,  130,  130,  130,   96,  130,  119,
      130,  130,    0,  130,  130,  130,  130,   89,    9,    9,
        8,    7,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,  130,    0,    0,   28,
        0,   31,    0,    0,    0,    0,    0,   30,    0,   74,

       15,   95,   75,  130,  130,  130,  130,  130,  130,  130,
      130,  130,    0,  130,    0,  127,  130,  130,   66,    0,
       72,  130,   10,  130,   20,   60,   73,  130,  130,  130,
      130,  130,  130,  115,    0,  130,  117,    0,   55,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,  130,    0,    0,    0,   32,    0,   29,   34,   37,
       83,  130,  130,   76,   12,  130,   68,  130,  130,   67,
        0,  130,   53,  130,  130,    0,    0,   56,    0,    0,
       16,   70,  130,    0,  130,   43,    0,  130,    0,    9,
        9,    9,    9,    9,    9,    9,    9,    9,  130,   35,

       36,   84,   23,    0,    0,  130,  124,  130,   50,   14,
      130,   47,    0,    0,    0,   21,    0,  126,  130,   48,
        9,    9,    9,  112,    0,    0,  130,   57,  130,   44,
       49,   46,   52,  126,  130,   45,   51,   64,   66,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   13,
       12,   12,   12,   12,   12,   12,   12,    1,   14,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   20,
       18,   21,   18,   18,   18,   18,   18,   18,   18,   22,
       18,   18,   23,   18,   18,   18,   18,   18,   18,   18,
       24,   25,   26,    1,   18,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    1,   53,   54,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1
    } ;

static const short int yy_base[553] =
    {   0,
        0,    0,    0,   44,   53,   54,   79,    0,    0,    0,
        0,    0,  133,    0,  187,    0,  793,  794,  794,  794,
      794,  776,  794,    0,  783,  773,  230,  271,  794,   48,
      773,  772,    0,  756,  760,  782,  794,  216,  214,  258,
       34,  270,   27,  217,   34,  278,  250,  743,  751,  738,
      291,  294,   36,  207,  219,  728,  794,  329,  740,  794,
      794,  794,  298,    0,  794,    0,  794,    0,  794,    0,
      794,  794,  312,  738,  747,  226,  221,  746,  307,  251,
      335,  735,   41,  794,  794,  333,    0,  373,  794,  745,
      744,  727,  738,  754,  794,  794,  794,    0,  726,  794,

      794,  728,  738,  228,  740,  257,  223,    0,  717,  725,
      723,  719,  721,  256,    0,  716,  728,  732,  284,  713,
      294,  727,  714,   29,  711,  713,  718,    0,    0,  324,
      707,  719,  710,  702,  715,  697,  706,  697,  700,    0,
      708,  319,  697,  708,  693,  700,  385,  248,  691,  317,
      693,  709,  346,  693,  304,    0,  683,  688,  358,  794,
        0,  379,  374,  691,  700,  368,  365,  699,  368,  327,
      372,  688,  370,    0,    0,  698,  794,  794,  794,    0,
        0,    0,  681,  686,  680,  694,  688,  794,  690,  794,
      677,  794,  690,  686,  794,  671,  690,  794,  674,  670,

      684,  403,  394,  407,  794,  794,  682,  664,    0,    0,
      670,  670,  668,  659,  661,    0,    0,  660,  663,  675,
      674,  651,    0,  667,  665,  660,  652,  657,  650,  660,
      663,  689,    0,  654,  646,    0,  651,  656,  650,    0,
      652,  640,  639,  653,  638,    0,    0,    0,  651,  635,
      640,  644,  648,  646,  642,  630,  643,  398,    0,  642,
      626,  636,  392,  624,  625,  628,  324,  663,  635,  630,
        0,  618,  617,  628,  416,    0,    0,    0,  615,  620,
      614,  628,  622,    0,  624,    0,  611,    0,  624,  620,
        0,  605,  624,    0,  608,  604,  618,  615,  600,  599,

      598,  794,  610,  596,  595,  605,  605,  592,  593,  794,
      590,  589,    0,  603,  584,  619,  582,  599,  588,  597,
        0,  589,  589,    0,  594,  584,  592,  591,    0,  617,
      578,    0,  408,    0,  573,    0,  584,  570,  571,    0,
      611,    0,  568,    0,  579,  566,  564,    0,  564,  563,
      562,    0,    0,  573,  566,  578,  564,    0,  557,    0,
      555,  428,  420,  569,  562,  595,  564,    0,  423,  427,
        0,    0,  551,  550,  549,    0,  561,  547,  546,  556,
      556,  543,  544,    0,  541,  540,  544,  543,  552,  794,
      548,  794,  547,  533,  533,  544,  531,  794,  542,    0,

        0,    0,    0,  544,  535,  529,  541,  522,  540,  538,
      522,  537,  427,  521,  533,    0,  518,  533,  527,  429,
        0,  557,    0,  515,    0,  555,    0,  554,  526,  526,
      509,  550,  520,  439,  520,  442,    0,  433,    0,  510,
      519,    0,  515,    0,  514,  500,  500,  511,  498,    0,
      509,  498,  502,  496,  493,  794,  493,  794,  794,  794,
      794,  494,  529,  525,    0,  489,    0,  443,  482,    0,
      474,  461,  794,  459,  458,  452,  444,    0,  446,  447,
        0,    0,  451,  448,  448,  794,  451,  441,  448,  440,
      434,  430,    0,  430,    0,    0,    0,    0,  470,  794,

      794,  794,    0,  450,  452,  427,  455,  427,  794,    0,
      431,  794,  435,  434,  433,    0,  432,    0,  432,  794,
        0,    0,    0,  794,  280,  262,  240,    0,  220,  794,
      794,  794,  794,    0,  456,  794,  794,    0,    0,  794,
      493,  498,  503,  505,  510,  512,  514,  516,  521,  526,
      530,  532
    } ;

static const short int yy_def[553] =
    {   0,
      541,  541,  540,    3,  542,  542,  540,    7,  541,  541,
      541,  541,  540,   13,  540,   15,  540,  540,  540,  540,
      540,  540,  540,  543,  540,  540,  540,  540,  540,  540,
      540,  540,  544,  544,  540,  540,  540,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  540,  540,  545,  544,  540,
      540,  540,  540,  546,  540,  547,  540,  548,  540,  543,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,   28,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  544,  544,  540,

      540,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  540,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  544,  540,  540,  540,  546,
      547,  548,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  540,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  545,  545,  549,  550,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  544,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  540,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  540,  544,  544,  544,  544,  544,  545,  545,
      549,  550,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  544,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  544,

      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  540,  544,  540,  544,  544,  544,  544,  540,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  544,  540,  540,  544,  544,  540,  544,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  544,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      540,  544,  540,  544,  544,  540,  540,  544,  540,  540,
      544,  544,  544,  540,  544,  540,  551,  544,  540,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  544,  540,

      540,  540,  544,  540,  540,  544,  540,  544,  540,  544,
      544,  540,  540,  540,  540,  544,  540,  552,  544,  540,
      545,  545,  545,  540,  540,  540,  544,  544,  544,  540,
      540,  540,  540,  552,  544,  540,  540,  544,  544,    0,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540
    } ;

static const short int yy_nxt[849] =
    {   0,
       19,   20,   21,   20,   22,   23,   24,   25,   19,   26,
       27,   28,   28,   29,   30,   31,   32,   33,   33,   33,
       34,   33,   33,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   33,   44,   45,   33,   33,   46,   47,   48,
       49,   50,   33,   51,   52,   53,   54,   33,   55,   33,
       33,   33,   56,   57,   58,   61,   61,   94,   62,   62,
      116,  124,   59,   95,  117,  129,  234,  125,  118,  153,
      126,  200,  235,  130,  119,  201,  154,   63,   63,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   64,   64,   64,   64,

       64,   64,   18,   18,   18,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   18,   18,   65,   65,   18,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       66,   66,   66,   66,   66,   66,   65,   65,   65,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   65,   65,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   68,   68,   68,   68,   68,   68,
       67,   67,   67,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   67,
       67,   73,   73,  102,  106,  157,  155,  127,  156,  158,
      539,  187,  185,  159,  107,  103,  210,   74,   75,  104,
       76,  105,  128,   77,  108,  186,  188,   78,  215,   79,
      538,  211,  216,   80,   81,   82,  136,  193,   83,   84,
       85,   86,   87,   87,  137,  194,  109,  259,  110,   88,
      138,  111,  112,  537,  213,  113,  120,  222,  114,  260,

      223,   88,  214,  177,  131,   89,  115,  121,  132,  122,
       90,  536,  133,  134,   91,   92,   93,  142,  135,  123,
      146,  143,  178,   73,   73,  144,  145,  147,  148,  227,
       88,  230,  228,  269,  149,  150,  151,  190,  231,  152,
      162,  162,   88,  179,  202,  202,   89,  191,  252,  270,
      163,   88,  239,  289,  262,  192,  164,  165,  253,  166,
      263,  290,  167,   88,  361,  195,  168,   89,  169,  240,
      362,  241,  170,  171,  172,  196,  266,  173,  174,  175,
      197,  203,  203,  198,  204,  204,  258,  273,  258,  267,
      162,  162,  277,  277,  281,  283,  278,  275,  286,  258,

      296,  258,  291,  274,  297,  204,  204,  282,  287,  275,
      284,  333,  292,  276,  202,  202,  288,  293,  204,  204,
      294,   88,  356,  363,  369,  369,  357,  370,  370,  434,
      413,  434,  420,   88,  370,  370,  438,   89,  370,  370,
      434,   89,  434,  487,  507,  487,  507,  477,  415,  479,
      480,  484,  487,  504,  487,  505,  507,  487,  507,  487,
      435,  276,  535,  533,  532,  531,  530,  471,  529,  476,
      528,  527,  524,  489,  523,  284,  488,  522,  521,  520,
      519,  362,  516,  512,  513,  511,  514,  515,  517,  324,
      525,  510,  526,   18,   18,   18,   18,   18,   60,   60,

       60,   60,   60,   70,   70,  509,   70,   70,   98,   98,
      161,  161,  508,  161,  161,  180,  180,  181,  181,  182,
      182,  371,  371,  506,  371,  371,  372,  372,  505,  372,
      372,  518,  504,  503,  518,  534,  534,  502,  188,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  486,  485,  484,  483,  482,  481,  480,  479,  478,
      477,  475,  474,  128,  473,  472,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,

      436,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  368,  367,  366,  365,  364,  363,  360,  359,  358,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,

      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  295,  285,
      280,  279,  272,  271,  268,  265,  264,  261,  257,  256,
      255,  254,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  238,  237,  236,  233,  232,  229,  226,  225,
      224,  221,  220,  219,  218,  217,  212,  209,  208,  207,
      206,  205,  205,  205,  205,  199,  189,  184,  183,  176,
      160,  141,  140,  139,  101,  100,   99,   97,   96,   72,
       71,   69,  540,   17,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540
    } ;

static const short int yy_chk[849] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    5,    6,   30,    5,    6,
       41,   43,    4,   30,   41,   45,  124,   43,   41,   53,
       43,   83,  124,   45,   41,   83,   53,    5,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   27,   27,   38,   39,   55,   54,   44,   54,   55,
      529,   77,   76,   55,   39,   38,  104,   27,   27,   38,
       27,   38,   44,   27,   39,   76,   77,   27,  107,   27,
      527,  104,  107,   27,   27,   27,   47,   80,   27,   27,
       27,   28,   28,   28,   47,   80,   40,  148,   40,   28,
       47,   40,   40,  526,  106,   40,   42,  114,   40,  148,

      114,   28,  106,   63,   46,   28,   40,   42,   46,   42,
       28,  525,   46,   46,   28,   28,   28,   51,   46,   42,
       52,   51,   63,   73,   73,   51,   51,   52,   52,  119,
       73,  121,  119,  155,   52,   52,   52,   79,  121,   52,
       58,   58,   73,   63,   86,   86,   73,   79,  142,  155,
       58,   86,  130,  170,  150,   79,   58,   58,  142,   58,
      150,  170,   58,   86,  267,   81,   58,   86,   58,  130,
      267,  130,   58,   58,   58,   81,  153,   58,   58,   58,
       81,   88,   88,   81,   88,   88,  147,  159,  147,  153,
      162,  162,  163,  163,  166,  167,  163,  162,  169,  258,

      173,  258,  171,  159,  173,  203,  203,  166,  169,  162,
      167,  333,  171,  162,  202,  202,  169,  171,  204,  204,
      171,  202,  263,  363,  275,  275,  263,  275,  275,  362,
      413,  362,  420,  202,  369,  369,  438,  202,  370,  370,
      434,  204,  434,  436,  468,  436,  468,  477,  333,  479,
      480,  484,  487,  504,  487,  505,  507,  535,  507,  535,
      363,  370,  519,  517,  515,  514,  513,  413,  511,  420,
      508,  506,  499,  438,  494,  492,  436,  491,  490,  489,
      488,  485,  483,  476,  477,  475,  479,  480,  484,  474,
      504,  472,  505,  541,  541,  541,  541,  541,  542,  542,

      542,  542,  542,  543,  543,  471,  543,  543,  544,  544,
      545,  545,  469,  545,  545,  546,  546,  547,  547,  548,
      548,  549,  549,  466,  549,  549,  550,  550,  464,  550,
      550,  551,  463,  462,  551,  552,  552,  457,  455,  454,
      453,  452,  451,  449,  448,  447,  446,  445,  443,  441,
      440,  435,  433,  432,  431,  430,  429,  428,  426,  424,
      422,  419,  418,  417,  415,  414,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  399,  397,  396,  395,  394,
      393,  391,  389,  388,  387,  386,  385,  383,  382,  381,
      380,  379,  378,  377,  375,  374,  373,  367,  366,  365,

      364,  361,  359,  357,  356,  355,  354,  351,  350,  349,
      347,  346,  345,  343,  341,  339,  338,  337,  335,  331,
      330,  328,  327,  326,  325,  323,  322,  320,  319,  318,
      317,  316,  315,  314,  312,  311,  309,  308,  307,  306,
      305,  304,  303,  301,  300,  299,  298,  297,  296,  295,
      293,  292,  290,  289,  287,  285,  283,  282,  281,  280,
      279,  274,  273,  272,  270,  269,  268,  266,  265,  264,
      262,  261,  260,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  245,  244,  243,  242,  241,  239,  238,  237,
      235,  234,  232,  231,  230,  229,  228,  227,  226,  225,

      224,  222,  221,  220,  219,  218,  215,  214,  213,  212,
      211,  208,  207,  201,  200,  199,  197,  196,  194,  193,
      191,  189,  187,  186,  185,  184,  183,  176,  172,  168,
      165,  164,  158,  157,  154,  152,  151,  149,  146,  145,
      144,  143,  141,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  127,  126,  125,  123,  122,  120,  118,  117,
      116,  113,  112,  111,  110,  109,  105,  103,  102,   99,
       94,   93,   92,   91,   90,   82,   78,   75,   74,   59,
       56,   50,   49,   48,   36,   35,   34,   32,   31,   26,
       25,   22,   17,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;


	switch (yybgin-yysvec-1) {	/* witchcraft */
	case 0:
		BEGIN A;
		break;
	case sc:
		BEGIN A;
		return('}');
	case br:
		BEGIN A;
		return(']');
	}


    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	if ( yy_bp[-1] == '\n' )
	    ++yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 541 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 540 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 46 "picl.l"
;
	YY_BREAK
case 2:
# line 47 "picl.l"
;
	YY_BREAK
case 3:
# line 48 "picl.l"
{ return(ST); }
	YY_BREAK
case 4:
# line 49 "picl.l"
{ return(ST); }
	YY_BREAK
case 5:
# line 50 "picl.l"
{ BEGIN sc; return(ST); }
	YY_BREAK
case 6:
# line 51 "picl.l"
{ BEGIN br; return(ST); }
	YY_BREAK
case 7:
# line 53 "picl.l"
{ if (curfile == infile) yyerror(".PS found inside .PS/.PE"); }
	YY_BREAK
case 8:
# line 54 "picl.l"
{ if (curfile == infile) {
			yylval.i = yytext[2];
			return(EOF);
		  }
		}
	YY_BREAK
case 9:
# line 59 "picl.l"
{ yylval.p = tostring(yytext); return(TROFF); }
	YY_BREAK
case 10:
# line 61 "picl.l"
return(yylval.i = PRINT);
	YY_BREAK
case 11:
# line 62 "picl.l"
return(yylval.i = BOX);
	YY_BREAK
case 12:
# line 63 "picl.l"
return(yylval.i = CIRCLE);
	YY_BREAK
case 13:
# line 64 "picl.l"
return(yylval.i = ARC);
	YY_BREAK
case 14:
# line 65 "picl.l"
return(yylval.i = ELLIPSE);
	YY_BREAK
case 15:
# line 66 "picl.l"
return(yylval.i = ARROW);
	YY_BREAK
case 16:
# line 67 "picl.l"
return(yylval.i = SPLINE);
	YY_BREAK
case 17:
# line 68 "picl.l"
return(yylval.i = LINE);
	YY_BREAK
case 18:
# line 69 "picl.l"
return(yylval.i = MOVE);
	YY_BREAK
case 19:
# line 70 "picl.l"
return(yylval.i = BLOCK);
	YY_BREAK
case 20:
# line 71 "picl.l"
return(RESET);
	YY_BREAK
case 21:
# line 72 "picl.l"
return(SPRINTF);
	YY_BREAK
case 22:
# line 74 "picl.l"
return(SAME);
	YY_BREAK
case 23:
# line 75 "picl.l"
return(BETWEEN);
	YY_BREAK
case 24:
# line 76 "picl.l"
return(AND);
	YY_BREAK
case 25:
# line 78 "picl.l"
;
	YY_BREAK
case 26:
# line 79 "picl.l"
;
	YY_BREAK
case 27:
# line 80 "picl.l"
;
	YY_BREAK
case 28:
# line 82 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 29:
# line 83 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 30:
# line 84 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 31:
# line 85 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 32:
# line 86 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 33:
# line 87 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 34:
# line 88 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 35:
# line 89 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 36:
# line 90 "picl.l"
{ yylval.i = CENTER; return(CORNER); }
	YY_BREAK
case 37:
# line 91 "picl.l"
{ yylval.i = START; return(CORNER); }
	YY_BREAK
case 38:
# line 92 "picl.l"
{ yylval.i = END; return(CORNER); }
	YY_BREAK
case 39:
# line 93 "picl.l"
{ yylval.i = NE; return(CORNER); }
	YY_BREAK
case 40:
# line 94 "picl.l"
{ yylval.i = SE; return(CORNER); }
	YY_BREAK
case 41:
# line 95 "picl.l"
{ yylval.i = NW; return(CORNER); }
	YY_BREAK
case 42:
# line 96 "picl.l"
{ yylval.i = SW; return(CORNER); }
	YY_BREAK
case 43:
# line 98 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 44:
# line 99 "picl.l"
{ yylval.i = NORTH; return(CORNER); }
	YY_BREAK
case 45:
# line 100 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 46:
# line 101 "picl.l"
{ yylval.i = SOUTH; return(CORNER); }
	YY_BREAK
case 47:
# line 102 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 48:
# line 103 "picl.l"
{ yylval.i = WEST; return(CORNER); }
	YY_BREAK
case 49:
# line 104 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 50:
# line 105 "picl.l"
{ yylval.i = EAST; return(CORNER); }
	YY_BREAK
case 51:
# line 106 "picl.l"
{ yylval.i = CENTER; return(CORNER); }
	YY_BREAK
case 52:
# line 107 "picl.l"
{ yylval.i = START; return(CORNER); }
	YY_BREAK
case 53:
# line 108 "picl.l"
{ yylval.i = END; return(CORNER); }
	YY_BREAK
case 54:
# line 110 "picl.l"
{ yylval.i = HEIGHT; return(ATTR); }
	YY_BREAK
case 55:
# line 111 "picl.l"
{ yylval.i = WIDTH; return(ATTR); }
	YY_BREAK
case 56:
# line 112 "picl.l"
{ yylval.i = RADIUS; return(ATTR); }
	YY_BREAK
case 57:
# line 113 "picl.l"
{ yylval.i = DIAMETER; return(ATTR); }
	YY_BREAK
case 58:
# line 114 "picl.l"
{ yylval.i = SIZE; return(ATTR); }
	YY_BREAK
case 59:
# line 115 "picl.l"
{ yylval.i = LEFT; return(DIR); }
	YY_BREAK
case 60:
# line 116 "picl.l"
{ yylval.i = RIGHT; return(DIR); }
	YY_BREAK
case 61:
# line 117 "picl.l"
{ yylval.i = UP; return(DIR); }
	YY_BREAK
case 62:
# line 118 "picl.l"
{ yylval.i = DOWN; return(DIR); }
	YY_BREAK
case 63:
# line 119 "picl.l"
{ yylval.i = CW; return(ATTR); }
	YY_BREAK
case 64:
# line 120 "picl.l"
{ yylval.i = CW; return(ATTR); }
	YY_BREAK
case 65:
# line 121 "picl.l"
{ yylval.i = CCW; return(ATTR); }
	YY_BREAK
case 66:
# line 122 "picl.l"
{ yylval.i = INVIS; return(ATTR); }
	YY_BREAK
case 67:
# line 123 "picl.l"
return(yylval.i = DOT);
	YY_BREAK
case 68:
# line 124 "picl.l"
return(yylval.i = DASH);
	YY_BREAK
case 69:
# line 125 "picl.l"
return(yylval.i = CHOP);
	YY_BREAK
case 70:
# line 127 "picl.l"
{ yylval.i = SPREAD; return TEXTATTR; }
	YY_BREAK
case 71:
# line 128 "picl.l"
{ yylval.i = FILL; return TEXTATTR; }
	YY_BREAK
case 72:
# line 129 "picl.l"
{ yylval.i = LJUST; return TEXTATTR; }
	YY_BREAK
case 73:
# line 130 "picl.l"
{ yylval.i = RJUST; return TEXTATTR; }
	YY_BREAK
case 74:
# line 131 "picl.l"
{ yylval.i = ABOVE; return TEXTATTR; }
	YY_BREAK
case 75:
# line 132 "picl.l"
{ yylval.i = BELOW; return TEXTATTR; }
	YY_BREAK
case 76:
# line 133 "picl.l"
{ yylval.i = CENTER; return TEXTATTR; }
	YY_BREAK
case 77:
# line 135 "picl.l"
{ yylval.i = HEAD1; return(HEAD); }
	YY_BREAK
case 78:
# line 136 "picl.l"
{ yylval.i = HEAD2; return(HEAD); }
	YY_BREAK
case 79:
# line 137 "picl.l"
{ yylval.i = HEAD12; return(HEAD); }
	YY_BREAK
case 80:
# line 139 "picl.l"
return(yylval.i = DOTX);
	YY_BREAK
case 81:
# line 140 "picl.l"
return(yylval.i = DOTY);
	YY_BREAK
case 82:
# line 141 "picl.l"
return(yylval.i = DOTHT);
	YY_BREAK
case 83:
# line 142 "picl.l"
return(yylval.i = DOTWID);
	YY_BREAK
case 84:
# line 143 "picl.l"
return(yylval.i = DOTRAD);
	YY_BREAK
case 85:
# line 145 "picl.l"
return(yylval.i = FROM);
	YY_BREAK
case 86:
# line 146 "picl.l"
return(yylval.i = TO);
	YY_BREAK
case 87:
# line 147 "picl.l"
return(yylval.i = AT);
	YY_BREAK
case 88:
# line 148 "picl.l"
return(yylval.i = BY);
	YY_BREAK
case 89:
# line 149 "picl.l"
return(yylval.i = WITH);
	YY_BREAK
case 90:
# line 150 "picl.l"
return(yylval.i = LAST);
	YY_BREAK
case 91:
# line 152 "picl.l"
return(LOG);
	YY_BREAK
case 92:
# line 153 "picl.l"
return(EXP);
	YY_BREAK
case 93:
# line 154 "picl.l"
return(SIN);
	YY_BREAK
case 94:
# line 155 "picl.l"
return(COS);
	YY_BREAK
case 95:
# line 156 "picl.l"
return(ATAN2);
	YY_BREAK
case 96:
# line 157 "picl.l"
return(SQRT);
	YY_BREAK
case 97:
# line 158 "picl.l"
return(RAND);
	YY_BREAK
case 98:
# line 159 "picl.l"
return(MAX);
	YY_BREAK
case 99:
# line 160 "picl.l"
return(MIN);
	YY_BREAK
case 100:
# line 161 "picl.l"
return(INT);
	YY_BREAK
case 101:
# line 163 "picl.l"
return(EQ);
	YY_BREAK
case 102:
# line 164 "picl.l"
return(GE);
	YY_BREAK
case 103:
# line 165 "picl.l"
return(LE);
	YY_BREAK
case 104:
# line 166 "picl.l"
return(NEQ);
	YY_BREAK
case 105:
# line 167 "picl.l"
return(GT);
	YY_BREAK
case 106:
# line 168 "picl.l"
return(LT);
	YY_BREAK
case 107:
# line 169 "picl.l"
return(ANDAND);
	YY_BREAK
case 108:
# line 170 "picl.l"
return(OROR);
	YY_BREAK
case 109:
# line 171 "picl.l"
return(NOT);	
	YY_BREAK
case 110:
# line 173 "picl.l"
return(yylval.i = HERE);
	YY_BREAK
case 111:
# line 175 "picl.l"
return(FOR);
	YY_BREAK
case 112:
# line 176 "picl.l"
{ endfor(); }
	YY_BREAK
case 113:
# line 177 "picl.l"
{ yylval.p = delimstr("loop body"); return(DOSTR); }
	YY_BREAK
case 114:
# line 179 "picl.l"
return(COPY);
	YY_BREAK
case 115:
# line 180 "picl.l"
{ BEGIN thru; return(THRU); }
	YY_BREAK
case 116:
# line 181 "picl.l"
{ yylval.p = copythru(yytext); BEGIN A; return(DEFNAME); }
	YY_BREAK
case 117:
# line 182 "picl.l"
return(UNTIL);
	YY_BREAK
case 118:
# line 184 "picl.l"
{ ifsw = 1; return(IF); }
	YY_BREAK
case 119:
# line 185 "picl.l"
{ if (!ifsw) { yylval.i = THEN; return(ATTR); }
		  yylval.p = delimstr("then part"); ifsw = 0;
		  return(THENSTR); }
	YY_BREAK
case 120:
# line 188 "picl.l"
{ yylval.p = delimstr("else part"); return(ELSESTR); }
	YY_BREAK
case 121:
# line 190 "picl.l"
{ BEGIN sh;
		  if ((delim = input()) == '{') delim = '}';	/* no nested {} */
		  shell_init(); }
	YY_BREAK
case 122:
# line 193 "picl.l"
{ struct symtab *p;
		  if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		  } else {
			p = lookup(yytext, 0);
			if (p != NULL && p->s_type == DEFNAME) {
				c = input();
				unput(c);
				if (c == '(')
					dodef(p);
				else
					pbstr(p->s_val.p);
			} else
				shell_text(yytext);
		  }
		}
	YY_BREAK
case 123:
# line 210 "picl.l"
{ if (yytext[0] == delim) {
			shell_exec();
			BEGIN A;
		  } else
			shell_text(yytext);
		}
	YY_BREAK
case 124:
# line 217 "picl.l"
{ BEGIN def; }
	YY_BREAK
case 125:
# line 218 "picl.l"
{ definition(yytext); BEGIN A; }
	YY_BREAK
case 126:
# line 219 "picl.l"
{ undefine(yytext); }
	YY_BREAK
case 127:
# line 221 "picl.l"
{ yylval.i = 1; return(NTH); }
	YY_BREAK
case 128:
# line 222 "picl.l"
{ yylval.i = atoi(yytext); return(NTH); }
	YY_BREAK
case 129:
# line 223 "picl.l"
{
		  	yylval.f = atof(yytext); return(NUMBER); }
	YY_BREAK
case 130:
# line 226 "picl.l"
{	struct symtab *p;
		p = lookup(yytext);
		if (p != NULL && p->s_type == DEFNAME) {
			c = input();
			unput(c);
			if (c == '(')	/* it's name(...) */
				dodef(p);
			else {	/* no argument list */
				pbstr(p->s_val);
				dprintf("pushing back `%s'\n", p->s_val);
			}
		} else if (islower(yytext[0])) {
			yylval.p = tostring(yytext);
			return(VARNAME);
		} else {
			yylval.p = tostring(yytext);
			return(PLACENAME);
		}
	}
	YY_BREAK
case 131:
# line 246 "picl.l"
{ BEGIN str; clen=0; }
	YY_BREAK
case 132:
# line 247 "picl.l"
{ cbuf[clen]=0; yylval.p = tostring(cbuf); BEGIN A; return(TEXT); }
	YY_BREAK
case 133:
# line 248 "picl.l"
{ yyerror("newline in string"); BEGIN A; return(ST); }
	YY_BREAK
case 134:
# line 249 "picl.l"
{ cbuf[clen++]='"'; }
	YY_BREAK
case 135:
# line 250 "picl.l"
{ cbuf[clen++]='\t'; }
	YY_BREAK
case 136:
# line 251 "picl.l"
{ cbuf[clen++]='\\'; }
	YY_BREAK
case 137:
# line 252 "picl.l"
{ CADD; }
	YY_BREAK
case 138:
# line 254 "picl.l"
;
	YY_BREAK
case 139:
# line 256 "picl.l"
return(yylval.i = yytext[0]);
	YY_BREAK
case 140:
# line 258 "picl.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(A):
case YY_STATE_EOF(str):
case YY_STATE_EOF(def):
case YY_STATE_EOF(sc):
case YY_STATE_EOF(br):
case YY_STATE_EOF(thru):
case YY_STATE_EOF(sh):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    register YY_CHAR *yy_bp = yytext;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
	++yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 541 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 541 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 540);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 258 "picl.l"

