h04256
s 00001/00001/00032
d D 8.2 93/12/11 23:43:01 mckusick 9 8
c copyediting for Usenix manuals
e
s 00002/00002/00031
d D 8.1 93/06/04 18:56:35 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00032
d D 6.5 91/07/01 15:15:51 cael 7 6
c fixed .Os
e
s 00025/00017/00008
d D 6.4 91/03/16 17:05:25 cael 6 5
c macro and text revision (-mdoc version 3)
e
s 00015/00037/00010
d D 6.3 91/01/19 18:54:49 bostic 5 4
c from scratch; add Berkeley specific copyright notice
e
s 00001/00001/00046
d D 6.2 90/06/24 21:21:16 trent 4 3
c new pathname (makekey)
e
s 00001/00001/00046
d D 6.1 85/04/27 14:16:58 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00007/00010/00040
d D 5.1 85/04/27 14:16:26 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00050/00000/00000
d D 4.1 85/04/27 14:16:00 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 5
D 6
.\" Copyright (c) 1990 The Regents of the University of California.
E 6
I 6
D 8
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
E 6
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
.\" %sccs.include.redist.man%
.\"
E 5
I 1
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH MAKEKEY 8 "4/1/81"
E 2
I 2
D 3
.TH MAKEKEY 8 "4 February 1983"
E 3
I 3
D 6
.TH MAKEKEY 8 "%Q%"
E 3
E 2
.AT 3
.SH NAME
D 5
makekey \- generate encryption key
E 5
I 5
makekey \- encrypt a key
E 5
.SH SYNOPSIS
D 4
.B /usr/lib/makekey
E 4
I 4
.B makekey
E 4
.SH DESCRIPTION
.I Makekey
D 5
improves the usefulness of encryption schemes depending on a key by
increasing the amount of time required to search the key space.  It
reads 10 bytes from its standard input, and writes 13 bytes on its
standard output.  The output depends on the input in a way intended to
D 2
be difficult to compute (i.e. to require a substantial fraction of a
second).
E 2
I 2
be difficult to compute (that is, to require a substantial fraction of
a second).
E 2
.PP
The first eight input bytes
(the
.IR "input key" )
can be arbitrary ASCII characters.
D 2
The last 
two (the
E 2
I 2
The last two (the
E 2
.IR salt )
are best chosen from the set of digits, upper- and lower-case
letters, and `.' and `/'.
The salt characters are repeated as the first two characters of the output.
The remaining 11 output characters are chosen from the same set as the salt
and constitute the
.I "output key."
.PP
The transformation performed is essentially the following:
the salt is used to select one of 4096 cryptographic
machines all based on the National Bureau of Standards
DES algorithm, but modified in 4096 different ways.
Using the input key as key,
D 2
a constant string is fed into the machine and recirculated
a number of times.
E 2
I 2
a constant string is fed into the machine and recirculated a number of times.
E 2
The 64 bits that come out are distributed into the
66 useful key bits in the result.
.PP
.I Makekey
D 2
is intended for programs that perform encryption
(e.g.
E 2
I 2
is intended for programs that perform encryption (for instance,
E 2
.I ed
and
.IR crypt (1)).
D 2
Usually its input and output will be pipes.
E 2
I 2
Usually makekey's input and output will be pipes.
E 5
I 5
reads a key (10 bytes) and a salt (2 bytes) from the standard input
and writes the string returned by
.IR crypt (3)
to the standard output.
E 6
I 6
.Dd %Q%
.Dt MAKEKEY 8
D 7
.Os ATT 7th
E 7
I 7
.Os
E 7
.Sh NAME
.Nm makekey
.Nd make encrypted keys or passwords
.Sh SYNOPSIS
.Nm makekey
.Sh DESCRIPTION
.Nm Makekey
D 9
encypts a key and salt which it reads from the standard input
E 9
I 9
encrypts a key and salt which it reads from the standard input
E 9
and writes the result to the standard output.
The key is expected to be
ten bytes; the salt is expected to be two bytes.
E 6
See
D 6
.IR crypt (3)
E 6
I 6
.Xr crypt 3
E 6
for more information on what characters the key and salt can contain
and how the encrypted value is calculated.
E 5
E 2
D 6
.SH SEE ALSO
D 5
crypt(1), ed(1)
E 5
I 5
login(1), crypt(1), crypt(3)
E 6
I 6
.Sh SEE ALSO
.Xr login 1 ,
.Xr crypt 1 ,
.Xr crypt 3
.Sh HISTORY
A
.Nm
command appeared in Version 7 AT&T UNIX.
E 6
E 5
E 1
