h33072
s 00000/00000/00005
d D 8.1 93/06/04 12:47:36 bostic 2 1
c 4.4BSD snapshot (revision 8.1)
e
s 00005/00000/00000
d D 5.1 92/06/26 06:57:10 bostic 1 0
c date and time created 92/06/26 06:57:10 by bostic
e
u
U
t
T
I 1
#	%W% (Berkeley) %G%

SRCS+=	bcmp.s bcopy.s bzero.s ffs.s index.s memchr.c memcmp.c memset.c \
	rindex.s strcat.c strcmp.s strcpy.c strcspn.c strlen.s strncat.c \
	strncmp.c strncpy.c strpbrk.c strsep.c strspn.c strstr.c
E 1
