h45489
s 00002/00002/00160
d D 8.1 93/06/06 16:52:32 bostic 12 11
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00026/00017/00136
d D 4.6 91/07/27 17:28:04 cael 11 10
c mdoc version three
e
s 00002/00003/00151
d D 4.5 91/04/26 16:09:06 bostic 10 9
c new copyright; att/bsd/shared
e
s 00002/00000/00152
d D 4.4 91/03/14 00:28:40 cael 9 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00001/00000/00152
d R 4.4 91/03/13 20:38:40 cael 8 7
c add .Vx so tmac.andoc will call tmac.mdoc-old
e
s 00087/00080/00065
d D 4.3 90/06/11 05:57:16 cael 7 6
c converted man page
e
s 00077/00022/00068
d D 4.2 88/12/21 22:42:22 minshall 6 5
c These are the current versions (actually already 2 years old).
e
s 00000/00000/00090
d D 4.1 88/12/04 15:10:53 minshall 5 4
c Release 4.1
e
s 00014/00003/00076
d D 1.4 88/10/25 15:52:25 bostic 4 3
c Berkeley copyright notice
e
s 00008/00003/00071
d D 1.3 86/01/11 16:11:04 mckusick 3 2
c convert to standard format
e
s 00002/00002/00072
d D 1.2 85/12/16 10:38:39 minshall 2 1
c Add SCCS id.
e
s 00074/00000/00000
d D 1.1 85/12/16 10:34:03 minshall 1 0
c date and time created 85/12/16 10:34:03 by minshall
e
u
U
t
T
I 1
D 2
.\" @(#)mset.1	1.3
.TH MSET 1 "22 March 1985"
E 2
I 2
D 3
.\" %W% %G%
.TH MSET 1 "%G%"
E 2
.ds ]W UCB Computer Center
E 3
I 3
D 4
.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 7
.\" Copyright (c) 1986 The Regents of the University of California.
E 7
I 7
D 12
.\" Copyright (c) 1986, 1990 The Regents of the University of California.
E 7
.\" All rights reserved.
E 12
I 12
.\" Copyright (c) 1986, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 12
.\"
D 7
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 7
I 7
D 10
.\" %sccs.include.redist.man%
E 10
I 10
.\" %sccs.include.redist.roff%
E 10
E 7
E 4
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
D 10
.\"     %W% (Berkeley) %G%
E 10
I 10
.\"	%W% (Berkeley) %G%
E 10
E 7
.\"
I 9
D 10
.Vx
E 10
D 11
.Vx
E 11
E 9
D 7
.TH MSET 1 "%Q%"
.UC 6
E 3
.SH NAME
mset \- retrieve ASCII to IBM 3270 keyboard map
.SH SYNOPSIS
.B mset
I 6
[-picky] [-shell] [keyboardname]
E 6
.SH DESCRIPTION
.I Mset
E 7
I 7
.Dd %Q%
.Dt MSET 1
.Os BSD 4.3
.Sh NAME
.Nm mset
D 11
.Nd retrieve ASCII to IBM 3270 keyboard map
E 11
I 11
.Nd retrieve
.Tn ASCII
to
.Tn IBM
3270 keyboard map
E 11
.Sh SYNOPSIS
.Nm mset
.Op Fl picky
.Op Fl shell
.Op Ar keyboardname
.Sh DESCRIPTION
.Nm Mset
E 7
retrieves mapping information
D 11
for the ASCII keyboard to IBM 3270 terminal
E 11
I 11
for the
.Tn ASCII
keyboard to
.Tn IBM
3270 terminal
E 11
special functions.
Normally, these mappings are found
in
D 7
.I /etc/map3270
E 7
I 7
.Pa /usr/share/misc/map3270
E 7
(see
D 7
.IR map3270 (5)).
E 7
I 7
.Xr map3270  5  ) .
E 7
This information is used by the
D 7
.I tn3270
E 7
I 7
.Xr tn3270
E 7
command (see
D 7
.IR tn3270 (1)).
.PP
E 7
I 7
.Xr tn3270  1  ) .
.Pp
E 7
D 6
.I Mset
can be used store the mapping information in the process environment
E 6
I 6
The default
D 7
.I mset
E 7
I 7
.Nm mset
E 7
output can be used to store the mapping information in the process environment
E 6
in order to avoid scanning
D 7
.I /etc/map3270
E 7
I 7
.Nm map3270
E 7
each time
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
is invoked.
To do this, place the following command in your
D 7
.I .login
E 7
I 7
.Pa .login
E 7
file:
I 11
.Bd -literal -offset indent
set noglob; setenv MAP3270 "\(gamset\(ga"; unset noglob
.Ed
E 11
D 7
.ti 5n
.sp
     set noglob; setenv \s-1MAP3270\s0 "\(gamset\(ga"; unset noglob
.PP
E 7
I 7
.Pp
D 11
.Dl set noglob; setenv MAP3270 "\(gamset\(ga"; unset noglob
.Pp
E 11
E 7
D 6
.I Mset
first determines the user's terminal type from the environment variable
.BR TERM .
Normally
E 6
I 6
If the
D 7
.I keyboardname
E 7
I 7
.Ar keyboardname
E 7
argument is not supplied,
E 6
D 7
.I mset
E 7
I 7
.Nm mset
E 7
I 6
attempts to determine the name of the keyboard the user is using,
by checking the
D 7
.B KEYBD
E 7
I 7
.Ev KEYBD
E 7
environment variable.
If the
D 7
.B KEYBD
E 7
I 7
.Ev KEYBD
E 7
environment variable is not set, then
D 7
.I mset
E 7
I 7
.Nm mset
E 7
uses the user's terminal type from the environment variable
D 7
.B TERM
E 7
I 7
.Ev TERM
E 7
as the keyboard name.
Normally,
D 7
.I mset
E 7
I 7
.Nm mset
E 7
E 6
then uses the file
D 7
.I /etc/map3270
E 7
I 7
.Xr map3270 5
E 7
to find the keyboard mapping for that terminal.
However, if the environment variable
D 7
.B MAP3270
E 7
I 7
.Ev MAP3270
E 7
D 6
exists and contains the entry for the specified terminal, then that
E 6
I 6
exists and contains the entry for the specified keyboard, then that
E 6
definition is used.
If the value of
D 7
.B MAP3270
E 7
I 7
.Ev MAP3270
E 7
begins with a slash (`/') then it is assumed to be the full pathname
of an alternate mapping file and that file is searched first.
D 6
In any case, if the mapping for the terminal is not found in
E 6
I 6
In any case, if the mapping for the keyboard is not found in
E 6
the environment, nor in an alternate map file, nor in the standard map file,
D 6
then the same search is performed for an entry for a terminal type of
.B unknown.
E 6
I 6
then the same search is performed for an entry for a keyboard with the name
D 7
.BR unknown .
E 7
I 7
.Ar unknown  .
E 7
E 6
If that search also fails,
then a default mapping
is used.
I 6
D 7
.PP
E 7
I 7
.Pp
E 7
The arguments to
D 7
.I mset
E 7
I 7
.Nm mset
E 7
are:
D 7
.sp
.TP +2
-picky
When processing the various map3270 entries (for the user's keyboard,
E 7
I 7
.Pp
D 11
.Tw Fl
.Tp Fl picky
E 11
I 11
.Bl -tag -width Fl
.It Fl picky
E 11
When processing the various
.Pa map3270
entries (for the user's keyboard,
E 7
and all those encountered before the one for the user's keyboard),
D 7
.I mset
E 7
I 7
.Nm mset
E 7
normally will not complain about entries for unknown functions (like
D 7
\*(lqPFX1\*(rq); the
.I -picky
E 7
I 7
.Dq PFX1 ;
the
.Fl picky
E 7
argument causes
D 7
.I mset
E 7
I 7
.Nm mset
E 7
to issue warning messages about these unknown entries.
D 7
.TP
-shell
If the map3270 entry is longer than the shell's 1024 environmental variable
E 7
I 7
D 11
.Tp Fl shell
E 11
I 11
.It Fl shell
E 11
If the
.Pa map3270
entry is longer than the shell's 1024 environmental variable
E 7
length limit, the default
D 7
.I mset
E 7
I 7
.Nm mset
E 7
output cannot be used to store the mapping information in the process
environment to avoid scanning
D 7
.I /etc/map3270
E 7
I 7
.Pa map3270
E 7
each time
D 7
.I tn3270
E 7
I 7
.Nm tn3270
E 7
is invoked.
The
D 7
.I -shell
E 7
I 7
.Fl shell
E 7
argument causes
D 7
.I mset
E 7
I 7
.Nm mset
E 7
to generate shell commands to set the environmental variables
D 7
.BR MAP3270 ,
.BR MAP3270A ,
E 7
I 7
.Ev MAP3270  ,
.Ev MAP3270A ,
E 7
and so on, breaking up the entry to fit within the shell environmental
variable length limit.
To set these variables, place the following command in your
D 7
.I .login
E 7
I 7
.Pa .login
E 7
file:
D 7
.sp
mset -shell > tmp ; source tmp ; /bin/rm tmp
.TP
keyboardname
When searching for the map3270 entry that matches the user's keyboard,
.I mset
E 7
I 7
D 11
.Pp
.Dl mset -shell > tmp ; source tmp ; /bin/rm tmp
.Tp Ar keyboardname
E 11
I 11
.Bd -literal -offset indent
mset -shell > tmp ; source tmp ; /bin/rm tmp
.Ed
.It Ar keyboardname
E 11
When searching for the
.Pa map3270
entry that matches the user's keyboard,
.Nm mset
E 7
will use
D 7
.I keyboardname
E 7
I 7
.Ar keyboardname
E 7
instead of determining the keyboard name from the
D 7
.B KEYBD
E 7
I 7
.Ev KEYBD
E 7
or
D 7
.B TERM
E 7
I 7
.Ev TERM
E 7
environmental variables.
E 6
D 7
.SH FILES
D 6
/etc/map3270        keyboard mapping for known terminals
E 6
I 6
/etc/map3270        keyboard mapping for known keyboards
E 6
.SH SEE ALSO
tn3270(1), map3270(5)
E 7
I 7
.Sh FILES
D 11
.Dw /usr/share/misc/map3270
.Di L
.Dp Pa /usr/share/misc/map3270
E 11
I 11
.Bl -tag -width /usr/share/misc/map3270 -compact
.It Pa /usr/share/misc/map3270
E 11
keyboard mapping for known keyboards
D 11
.Dp
.Sh ENVIRONMENT
E 11
I 11
.El
E 11
.Sh SEE ALSO
.Xr tn3270 1 ,
.Xr map3270 5
.Sh HISTORY
I 11
The
E 11
.Nm mset
D 11
appeared in 4.3 BSD.
E 11
I 11
command appeared in
.Bx 4.3 .
E 11
E 7
D 6
.SH BUGS
If the entry for the specific terminal
exceeds 1024 bytes, \fIcsh\fR(1) will fail
to set the environment variable.
.I Mset
should probably
detect this case and
output the path to the
.I map3270
file
instead of the terminal entry.
E 6
E 1
