h44579
s 00041/00047/00062
d D 8.2 94/04/04 09:11:43 bostic 7 6
c minor reworking for clarity
e
s 00002/00002/00107
d D 8.1 93/06/06 14:18:18 bostic 6 5
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00041/00026/00068
d D 6.4 91/03/14 01:38:30 cael 5 4
c updated to -mdoc version 3
e
s 00002/00002/00092
d D 6.3 90/07/24 22:40:30 cael 4 3
c .Xr botch fix
e
s 00063/00055/00031
d D 6.2 90/06/11 05:52:36 cael 3 2
c converted man page
e
s 00001/00001/00085
d D 6.1 85/04/29 21:08:49 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00086/00000/00000
d D 5.1 85/04/29 21:08:23 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 3
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 3
I 3
D 6
.\" Copyright (c) 1983, 1990 The Regents of the University of California.
.\" All rights reserved.
E 6
I 6
.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 6
E 3
.\"
I 5
.\" %sccs.include.redist.man%
E 5
D 3
.\"	%W% (Berkeley) %G%
E 3
.\"
D 2
.TH APPLY 1 "24 February 1979"
E 2
I 2
D 3
.TH APPLY 1 "%Q%"
E 2
.UC 5
.SH NAME
apply \- apply a command to a set of arguments
.SH SYNOPSIS
.B apply
[
.B \-a\fIc\fP
] [
.B \-\fIn\fP
] command args ...
.SH DESCRIPTION
.I Apply
E 3
I 3
.\"     %W% (Berkeley) %G%
.\"
.Dd %Q%
.Dt APPLY 1
.Os BSD 4.2
.Sh NAME
.Nm apply
.Nd apply a command to a set of arguments
.Sh SYNOPSIS
.Nm apply
D 5
.Op Fl ac
.Op Fl n
E 5
I 5
.Op Fl a Ns Ar c
D 7
.Op Fl Ns Ar n
E 5
.Ar command args ...
E 7
I 7
.Op Fl Ns Ar #
.Ar command argument ...
E 7
.Sh DESCRIPTION
.Nm Apply
E 3
runs the named
D 3
.I command
E 3
I 3
.Ar command
E 3
on each
argument
D 3
.I arg
E 3
I 3
D 7
.Ar arg
E 7
I 7
.Ar argument
E 7
E 3
in turn.
I 5
.Pp
D 7
Options available are:
.Bl -tag -width "-ac"
.It Fl Ns Ar n
E 5
Normally arguments are chosen singly; the optional number
D 3
.I n
E 3
I 3
.Fl n
E 3
specifies the number of arguments to be passed to
D 3
.I command.
E 3
I 3
.Ar command .
E 3
If
D 3
.I n
E 3
I 3
.Fl n
E 3
is zero,
D 3
.I command
E 3
I 3
.Ar command
E 3
is run without arguments once for each
D 3
.I arg.
Character sequences of the form %\fId\fP
E 3
I 3
D 5
.Ar arg
E 5
I 5
.Ar arg .
E 7
E 5
Character sequences of the form
D 4
Cx %
E 4
I 4
D 5
.Cx %
E 4
.Ar d
.Cx
E 5
I 5
D 7
.Pf \&% Ar d
E 7
I 7
.Dq Li \&%d
E 7
E 5
E 3
in
D 3
.I command,
E 3
I 3
.Ar command ,
E 3
where
D 3
.I d
E 3
I 3
D 7
.Ar d
E 3
is a digit from 1 to 9,
are replaced by the
D 3
\fId\fP'th following unused
.I arg.
E 3
I 3
D 5
.Ar d\'th
E 5
I 5
.Ar d Ns \'th
E 7
I 7
.Dq Li d
is a digit from 1 to 9, are replaced by the
.Li d Ns \'th
E 7
E 5
following unused
D 7
.Ar arg .
E 3
If any such sequences occur,
D 3
.I n
E 3
I 3
.Fl n
E 3
is ignored,
and the number of arguments passed to
D 3
.I command
E 3
I 3
.Ar command
E 3
is the maximum value of
D 3
.I d
E 3
I 3
.Ar d
E 3
in
E 7
I 7
.Ar argument .
In this case, the largest digit number of arguments are discarded for
each execution of
E 7
D 3
.I command.
E 3
I 3
.Ar command .
I 7
.Pp
The options are as follows:
.Bl -tag -width "-ac"
.It Fl Ns Ar #
Normally arguments are taken singly; the optional number
.Fl #
specifies the number of arguments to be passed to
.Ar command .
If the number is zero,
.Ar command
is run, without arguments, once for each
.Ar argument .
.Pp
If any sequences of
.Dq Li \&%d
occur in command, the
.Fl n
option is ignored.
E 7
E 3
D 5
The character `%' may be changed by the
E 5
I 5
.It Fl a Ns Ar c
D 7
The character
.Ql %
may be changed by the
E 7
I 7
The use of the character
.Dq Li %
as a magic character may be changed with the
E 7
E 5
D 3
.B \-a
E 3
I 3
.Fl a
E 3
option.
D 3
.PP
Examples:
.RS
apply echo *
.RE
E 3
I 3
D 5
.SH ENVIRONMENT
.Nm apply
checks the environment variable
.Ev SHELL
to find out which shell to use.
E 5
I 5
.El
D 7
.Sh ENVIRONMENT
The following environment variable is used by
E 7
I 7
.Sh ENVIRONMENT VARIABLES
The following environment variable affects the execution of
E 7
.Nm apply :
.Bl -tag -width SHELL
.It Ev SHELL
D 7
Pathname of shell to use. If this option is not defined,
a default shell is used.
E 7
I 7
Pathname of shell to use.
If this variable is not defined, the Bourne shell is used.
E 7
.El
E 5
.Sh EXAMPLES
D 5
.Ds
.Tw apply \-2 cmp a1 b1 a2 b2 ...
.Tp Li apply echo a*
E 5
I 5
.Bl -tag -width apply -compact
.It Li "apply echo a*"
E 5
E 3
is similar to ls(1);
D 3
.RS
apply \-2 cmp a1 b1 a2 b2 ...
.RE
E 3
I 3
D 5
.Tp Li apply \-2 cmp a1 b1 a2 b2 ...
E 5
I 5
D 7
.It Li "apply \-2 cmp a1 b1 a2 b2 ..."
E 7
I 7
.It Li "apply \-2 cmp a1 b1 a2 b2 a3 b3"
E 7
E 5
E 3
compares the `a' files to the `b' files;
D 3
.RS
apply \-0 who 1 2 3 4 5
.RE
E 3
I 3
D 5
.Tp Li apply \-0 who 1 2 3 4 5
E 5
I 5
.It Li "apply \-0 who 1 2 3 4 5"
E 5
E 3
runs who(1) 5 times; and
D 3
.RS
apply \(aaln %1 /usr/joe\(aa *
.RE
links all files in the current directory to the directory /usr/joe.
.SH "SEE ALSO"
sh(1)
.SH AUTHOR
E 3
I 3
D 5
.Tp Li apply \(aaln %1 /usr/joe\(aa *
E 5
I 5
.It Li "apply \'ln %1 /usr/joe\'" *
E 5
links all files in the current directory to the directory
.Pa /usr/joe .
D 5
.Tp
.De
E 5
I 5
.El
E 5
D 7
.Sh SEE ALSO
.Xr sh 1
E 7
I 7
.Sh Files
.Bl -tag -width /bin/sh -compact
.It Pa /bin/sh
Default shell
.El
E 7
D 5
.Sh HISTORY
.Nm Apply
appeared in 4.2BSD.
E 5
.Sh AUTHOR
E 3
Rob Pike
D 3
.SH BUGS
E 3
I 3
.Sh BUGS
E 3
Shell metacharacters in
D 3
.I command
E 3
I 3
.Ar command
E 3
may have bizarre effects; it is best to enclose complicated
D 4
commands in single quotes \(aa\ \(aa.
E 4
I 4
D 5
commands in single quotes (\(aa\ \(aa).
E 5
I 5
commands in single quotes
.Pq Sq .
E 5
E 4
D 3
.sp
E 3
I 3
D 7
.Pp
E 3
D 5
There is no way to pass a literal `%2' if `%' is the
E 5
I 5
There is no way to pass a literal
.Ql %2
if
.Ql %
is the
E 5
argument expansion character.
E 7
I 5
.Sh HISTORY
The
.Nm
command appeared in 
.Bx 4.2 .
E 5
E 1
