h57940
s 00001/00001/00018
d D 8.2 94/04/18 20:46:37 bostic 2 1
c spelling
e
s 00019/00000/00000
d D 8.1 94/04/18 20:46:12 bostic 1 0
c date and time created 94/04/18 20:46:12 by bostic
e
u
U
t
T
I 1
.\"  @(#)chkey.1	2.1 88/08/10 4.0 RPCSRC; from 1.6 88/02/29 SMI;
.TH CHKEY 1 "9 September 1987"
.SH NAME
chkey \- change your encryption key
.SH SYNOPSIS
.B chkey
.SH DESCRIPTION
.IX  "chkey command"  ""  "\fLchkey\fP command"
D 2
.IX  "encryption key, change, \fLchkey\fR commmand"
E 2
I 2
.IX  "encryption key, change, \fLchkey\fR command"
E 2
.B chkey
prompts the user for their login password, and uses it to encrypt
a new encryption key for the user to be stored in the
.BR publickey (5)
database.
.SH "SEE ALSO"
.BR keylogin (1),
.BR publickey (5),
.BR keyserv (8C),
.BR newkey (8)
E 1
