'\" t
.TH NETTY 1
.SH NAME
netty \- terminal program for use on the DMD 5620 terminal
.SH SYNOPSIS
netty [-i] [-e] [-v] [-D] [-B] [-s shell] [-b [banner_prog]]
.SH DESCRIPTION
.I Netty
is a terminal program for use in a layer on the DMD 5620 terminal.
It includes an optional banner line, user-tailored mouse menus and function
keys, and a sufficient set of cursor controls to be usable with
\fIvi\fR(1) and other programs that use the \fIcurses\fR(3) library and/or the
\fIterminfo\fR(7) database (pg, rogue, etc.).
.SS Options
.TP 5
.B -i
leave space for icons at the bottom of the current layer
.TP 5
.B -e
ignore eof for exec'ed shell
.TP 5
.B -v
for \fIvi\fR(1) users
.TP 5
.B -s
shell or program to exec in the layer
.TP 5
.B -b
banner line program
.P
After \fInetty\fR has completed the download it exec's a shell
to take over in the layer.  If
.I "-s shell"
is specified
.I shell
will be exec'ed.  Otherwise the shell variable SHELL
is used.  If SHELL is undefined then /bin/sh is used.

If the banner line option is provided \fInetty\fR will
be configured so that one of the lines of the layer will
be reserved as a banner line.
This line would normally be a black stripe at the top of the layer,
but could have a dot pattern if \fB-D\fR is specified, or appear at
the bottom of the layer if \fB-B\fR is specified.
(\fB-D\fR and \fB-B\fR are ignored if \fB-b\fR is not specified.)

The banner program sends messages to the banner line, and should be supplied
by the user.

.SS "The \fINetty \fPEnvironment"
.I load_netty
sets the TERM variable to "netty" (or to "netty-vi", if "-v" is specified)
and assigns a TERMCAP variable when invoked.
.I load_netty (netty)
also makes your keyboard-cursor blink.
.P
.I Netty
provides a user-tailored menu on button 2 of the mouse.
The user may add menu selections using the "Escape M" and "Escape m"
sequences as shown below, or with the \fIsend_netty\fR command.
The default
.I netty
menu is as follows:
.TP 12
clear
clears the screen.
.TP 12
invert
inverts video (black type on green background and vice-versa).
On selecting this option the INVERT menu label becomes upper-case
indicating the current mode.
.TP 12
mit scroll
enables/disables MIT-style scrolling (where cursor moves back to top
of screen after reaching bottom; menu label becomes upper-case).
.TP 12
more
enable/disables MORE-style
scrolling (where scrolling stops at end of each screenful until hitting
any key or a muse button; menu label becomes upper-case).
.TP 12
reset
clears the screen, resets the modes to black-on-green with normal scrolling,
and resets all menu labels to lower-case.
.P
.I Netty
also recognizes the following sequences on output
(these are used by the menu, \fIvi\fR , and other application programs, but
may also be invoked directly by the user using \fIecho\fR(1)):
.P
Control sequences:

.in +5
.TS
l l.
^G   	Ring bell
^L	Clear screen
.TE
.in -5
.P
Escape sequences:
.br

.in +5
.ti -3
Modes:
.TS
l l.
^R	Toggle Invert
^P	Toggle MIT scrolling
^W	Toggle MORE processing
R~	Inverse Video on and off
P~	MIT Scrolling on and off
W~	MORE processing on and off
U~	Underline on and off
C~	Graphics Character set on and off
{~	Mouse mode on and off
[~	\fIvi\fR mode on and off
]~	\fIvi\fR line-number mode on and off
X~	ixon mode on and off
.TE

.ti -3
Editing:
.TS
l l.
Yxy	Cursor movement
I~	Insert mode on and off
d	Delete a character
Z	Clear to end of line
A	Up one line
Dx	Delete x lines
Sx	Scroll x lines
Ox	Open x lines
.TE

.ti -3
Other:
.TS
l l.
#~	Select menu (@-netty, A-secondary menu, B-vi)
M~!m!	Download menu item (e.g., echo "\e033MC!pwd!")
m~!v!	Download menu value (e.g., echo "\e033mC!pwd\er!")
F~!v!	Download arrow and function keys
	(e.g., echo "\e033FA!who!")
T	Download a DMD mouse texture
	(e.g., echo "\e033T\ec"; cat Tfile)
b!m!	Send a message to the banner line
	(e.g., echo "\e033b!`date`!")
Bxyxy	Draw a border line from point to point
	(horizontal or vertical, x1=x2 || y1=y2),
	especially useful for \fIviews\fR, as defined below
vxylw	Define a view - Concept100 style window
.xy!t!!r!
	Set icon number y at location x with title t and
	return value r
^	Dispose of banner line and icon area - full screen
.TE
.in
.P
Notations:
.TP 7
~
a letter in the range
"@ABCD...Z" for specifying the numbers "0 1 2 3 4 ... 26".  For
setting modes the letters "@" and "A" (0 and 1) should be used.
.TP 7
xy
the letters "x" and "y" are used to specify column and row positions
encoded as one letter.
(The encoding is performed by adding 32 to the desired number,
obtaining the ASCII value of that character, e.g.,
x=59 would be encoded as 59+32=91='['.)
.TP 7
lw
"l" and "w" are used to specify length and
width encoded as one letter each (as above).
.TP 7
!m!
used to send arbitrary length strings to the DMD terminal.
The sequence "!m!" should be interpreted as
a delimiting character ("!"), the message string ("m"), and the
delimiting character again ("!").
Note that "\er" (carriage-return) should be used to terminate the string
if it is to be executed.
.P
The return values from menu selection or from function keys are
transmitted as if they were entered by the user from the keyboard.
Sequences that are prefixed by "##" will be executed locally.
.SS "Usage of the graphics character set"
Typing ESC followed by capital 'C' puts your window in the graphics-character set mode.
In this mode, the following characters have special meaning:
.TS
l l.

q	horizontal line

x	vertical line

l	upper-lefthand corner

k	upper-righthand corner

m	lower-lefthand corner

j	lower-righthand corner
.TE
.P
The RETURN, BACKSPACE and TAB keys work as normal, and all other characters are
interpreted as a space.
To restore to normal character mode, type ESC followed by 'C' and '@',
or select the RESET button in the \fInetty\fR mouse menu.
.SS "Editing under \fINetty\fR"
.I Netty
provides an editor-oriented menu for \fIvi\fR and other editors.
(If you are a \fIvi\fR user, you should invoke \fInetty\fR with the "-v"
option, or else set TERM to "netty-vi".)
When this is invoked, a new menu replaces the menu on button 2 of the
mouse (the \fInetty\fR menu returns when the editor is exited).
The default menu for \fIvi\fR is:

.in +5
.nf
Top of File
Bottom of File
Page Back
Page Forward
Scroll Back
Scroll Forward
Set Mark
Show Mark
Insert Last Kill
Kill Marked Area
.fi
.in

This is easily modified so that every user may keep a personalized
local copy if desired.
Button 1 (left button) is used for pointing, moving the \fIvi\fR cursor to the
current position of the mouse cursor.
.SS "Auxiliary Files"
The
.I netty
package comes with the following programs and other files, all under
$DMD/lib/netty:

.in +4
.ti -4
\(bu send_netty

This command provides a user fiendly interface for downloading new menus,
icons, mouse textures, and function key definitions.  Enter
.B
send_netty -?
.R
for a list of options and parameters.
.ti -4
\(bu Blit_Time2

This is a banner line program that displays the time and appointments,
read in from a file.
It is called as:

.ce
\fBBlit_Time2 <bin> <interval>\fR

where <bin> is a directory where temporary commands will be placed,
and <interval> is the interval in seconds between updates.

Blit_Time2 toggles between displaying a status message (date, time, number
of users, number of mail messages) and an appointment message, as is read
in from the cron-style file "$HOME/.cron_file".
The status message is displayed for <interval> seconds, and then Blit_Time2
runs thru your .cron_time file (if it exists), and displays sequentially
all the messages that match.
See \fIcron\fR(1M).

<bin> is used to put temporary commands created by Blit_Time2.
These include:

.in +4
.ti -2
- Set_Time - indicates in the banner-line when a background process has finished.
.br
(e.g., sh -c "make; Set_Time"&).

.ti -2
- ReSet_Time - Turns off above indicator.

.ti -2
- Kill_Time - Kills Blit_Time2
.in

.ti -4
Other files:

.TS
l l.
Text_Cursor	Sample texture files
Text_Cursor2
Text_Cursor3
Text_Cursor4
Text_kitten
cron_for_Time	Sample cron file Blit_Time2
netty.m	The downloaded program
netty.ti	Terminfo terminal description file - compile tic
whip_config	Config file for layers -f whip_config
whip_layers.sh	Shell file for running whip_config
.TE
.in -4
.SH "SEE ALSO"
cron(1M), hp2621(1), jim(1).
.SH WARNINGS
\fIVi\fR(1) may not work properly after reshaping a \fInetty\fR layer.
.\"	@(#)netty.1	%W% of %D%
