h32469
s 00002/00002/00026
d D 8.1 93/06/06 22:33:46 bostic 7 6
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00022/00015/00006
d D 6.4 91/04/24 14:57:55 cael 6 5
c mdoc version three
e
s 00008/00004/00013
d D 6.3 91/04/18 19:03:15 bostic 5 4
c new copyright; att/bsd/shared
e
s 00001/00004/00016
d D 6.2 88/01/09 18:18:36 bostic 4 3
c don't mention "rubout".
e
s 00001/00001/00019
d D 6.1 85/04/29 15:12:57 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00006/00011/00014
d D 5.1 85/04/29 15:12:50 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00025/00000/00000
d D 4.1 85/04/29 15:12:43 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 5
I 5
D 6
.\" Copyright (c) 1985 The Regents of the University of California.
E 6
I 6
D 7
.\" Copyright (c) 1980, 1991 Regents of the University of California.
E 6
.\" All rights reserved.
E 7
I 7
.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 7
E 5
.\"
I 5
.\" %sccs.include.redist.roff%
.\"
E 5
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
.\"     %W% (Berkeley) %G%
E 6
.\"
D 2
.TH YES 1 
E 2
I 2
D 3
.TH YES 1  "18 January 1983"
E 3
I 3
D 6
.TH YES 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
yes \- be repetitively affirmative
.SH SYNOPSIS
.B yes
[
D 2
.B expletive
E 2
I 2
.I expletive
E 2
]
.SH DESCRIPTION
D 2
.B Yes
repeatedly outputs \*(lqy\*(rq,
or if
.B expletive
is given,
that is output repeatedly.
Termination is by rubout.
.SH BUGS
Boring.
E 2
I 2
D 4
.I Yes
repeatedly outputs \*(lqy\*(rq, or if
.I expletive
is given, that is output repeatedly.  Termination is by rubout.
E 4
I 4
D 5
\fIYes\fP outputs \fIexpletive\fP, or, by default, \*(lqy\*(rq, forever.
E 5
I 5
.I Yes
E 6
I 6
.Dd %Q%
.Dt YES 1
.Os BSD 4
.Sh NAME
.Nm yes
.Nd be repetitively affirmative
.Sh SYNOPSIS
.Nm yes
.Op Ar expletive
.Sh DESCRIPTION
.Nm Yes
E 6
outputs
D 6
.IR expletive ,
or, by default, ``y'', forever.
E 6
I 6
.Ar expletive ,
or, by default,
.Dq y ,
forever.
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
E 6
E 5
E 4
E 2
E 1
