h00260
s 00001/00001/00047
d D 8.3 94/04/19 08:51:48 bostic 11 10
c spelling
e
s 00002/00002/00046
d D 8.2 93/12/11 23:44:52 mckusick 10 9
c copyediting for Usenix manuals
e
s 00002/00002/00046
d D 8.1 93/06/06 14:12:00 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00047
d D 6.6 92/06/22 13:35:49 bostic 8 7
c typo, syn -> sync
e
s 00004/00004/00044
d D 6.5 91/08/05 07:16:41 cael 7 6
c fix history
e
s 00006/00004/00042
d D 6.4 91/07/01 15:34:21 cael 6 5
c fix .Os
e
s 00045/00038/00001
d D 6.3 91/03/16 18:14:09 cael 5 4
c macro and text revision (-mdoc version 3)
e
s 00001/00001/00038
d D 6.2 90/06/24 22:49:12 trent 4 3
c new pathname (update)
e
s 00001/00001/00038
d D 6.1 85/04/27 14:18:10 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00003/00036
d D 5.1 85/04/27 14:17:44 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00039/00000/00000
d D 4.1 85/04/27 14:17:24 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 5
.\"	%W% (Berkeley) %G%
E 5
I 5
D 6
.\"	@(#)update.8	6.2 (Berkeley) 6/24/90
E 6
I 6
D 9
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
E 6
E 5
.\"
D 2
.TH UPDATE 8 "4/1/81"
E 2
I 2
D 3
.TH UPDATE 8  "4 February 1983"
E 3
I 3
D 5
.TH UPDATE 8 "%Q%"
E 3
E 2
.AT 3
.SH NAME
update \- periodically update the super block
.SH SYNOPSIS
D 4
.B /etc/update
E 4
I 4
.B update
E 4
.SH DESCRIPTION
.I Update
is a program that executes
the
.IR sync (2)
primitive every 30 seconds.
This insures that the file system
is fairly up to date in case of a crash.
This command should not be executed directly,
but should be executed out of the
initialization shell command file.
.SH "SEE ALSO"
D 2
sync(2), sync(1), init(8)
E 2
I 2
sync(2), sync(8), init(8), rc(8)
E 2
.SH BUGS
With
.I update
running,
if the CPU is
halted just as
the
.I sync
is executed,
a file system can be damaged.
This is partially due to DEC hardware that
writes zeros when NPR requests fail.
A fix would be to have
D 2
.IR sync (1)
E 2
I 2
.IR sync (8)
E 2
temporarily increment the system time by at
least 30 seconds to trigger the execution of
.I update.
This would give 30 seconds grace to halt the CPU.
E 5
I 5
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
.\"
D 7
.\"     %W% (Berkeley) %G%
E 7
I 7
.\"	%W% (Berkeley) %G%
E 7
.\"
.Dd %Q%
.Dt UPDATE 8
D 6
.Os ATT 7th
E 6
I 6
.Os
E 6
.Sh NAME
.Nm update
.Nd flush internal filesystem caches to disk frequently
.Sh SYNOPSIS
.Nm update
.Sh DESCRIPTION
The
.Nm update
command helps protect the integrity of disk volumes
by flushing
D 10
voliatile cached filesystem data
E 10
I 10
volatile cached filesystem data
E 10
to disk at thirty second intervals.
.Nm Update
uses the
.Xr sync 2
function call to do the task.
.Pp
.Nm Update
is commonly invoked at startup time by
.Xr rc 8
when the system goes multi-user.
.Sh SEE ALSO
.Xr sync 2 ,
.Xr fsck 8 ,
.Xr init 8 ,
.Xr rc 8 ,
.Xr sync 8
.Sh BUGS
D 10
It is possible on some systems, that a
E 10
I 10
It is possible on some systems that a
E 10
D 6
.Nm sync
E 6
I 6
D 8
.Xr syn
E 8
I 8
.Xr sync
E 8
E 6
D 11
occuring simultaneously with a crash may cause
E 11
I 11
occurring simultaneously with a crash may cause
E 11
file system damage. See
.Xr fsck 8 .
.Sh HISTORY
An
D 7
.Nm
E 7
I 7
.Nm update
E 7
D 6
command appeared in Version 6 AT&T UNIX.
E 6
I 6
command appeared in
D 7
.At v6.
E 7
I 7
.At v6 .
E 7
E 6
E 5
E 1
