h43714
s 00002/00002/00050
d D 8.1 93/06/06 16:39:19 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00004/00004/00048
d D 6.5 91/07/30 18:35:57 cael 8 7
c formalize HISTORY
e
s 00003/00000/00049
d D 6.4 91/06/27 17:26:02 bostic 7 6
c add POSIX/IEEE contribution notice
e
s 00032/00034/00017
d D 6.3 91/04/23 16:35:51 cael 6 4
c mdoc version three
e
s 00005/00015/00036
d R 6.3 90/06/24 19:21:24 cael 5 4
c converted man page
e
s 00041/00006/00010
d D 6.2 89/12/07 10:43:44 bostic 4 3
c redone from scratch from the POSIX manual page
e
s 00001/00001/00015
d D 6.1 85/04/29 18:07:22 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00005/00002/00011
d D 5.1 85/04/29 18:07:10 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00013/00000/00000
d D 4.1 85/04/29 18:06:59 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 4
D 6
.\" Copyright (c) 1989 The Regents of the University of California.
E 6
I 6
D 9
.\" Copyright (c) 1990 The Regents of the University of California.
E 6
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
I 7
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
E 7
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 8
.\" %sccs.include.redist.man%
E 8
I 8
.\" %sccs.include.redist.roff%
E 8
E 6
.\"
E 4
I 1
D 6
.\"	%W% (Berkeley) %G%
E 6
I 6
D 8
.\"     %W% (Berkeley) %G%
E 8
I 8
.\"	%W% (Berkeley) %G%
E 8
E 6
.\"
D 2
.TH TTY 1 
E 2
I 2
D 3
.TH TTY 1 "10 February 1983"
E 3
I 3
D 6
.TH TTY 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
D 4
tty \- get terminal name
E 4
I 4
tty \- return user's terminal name
E 4
.SH SYNOPSIS
.B tty
I 2
[ -s ]
E 2
.SH DESCRIPTION
E 6
I 6
.Dd %Q%
.Dt TTY 1
.Os
.Sh NAME
.Nm tty
.Nd return user's terminal name
.Sh SYNOPSIS
.Nm tty
.Op Fl s
.Sh DESCRIPTION
E 6
I 4
The
D 6
.I tty
E 6
I 6
.Nm tty
E 6
utility writes the name of the terminal attached to standard input
to standard output.
The name that is written is the string returned by
D 6
.IR ttyname (3).
E 6
I 6
.Xr ttyname 3 .
E 6
If the standard input is not a terminal, the message ``not a tty''
is written.
The options are as follows:
D 6
.TP
-s
E 6
I 6
.Bl -tag -width Ds
.It Fl s
E 6
Don't write the terminal name; only the exit status is affected
when this option is specified.
The
D 6
.I -s
option is deprecated in favor of the ``test -t 0'' command.
.PP
E 4
.I Tty
E 6
I 6
.Fl s
option is deprecated in favor of the
.Dq Li "test -t 0"
command.
.El
.Pp
.Nm Tty
E 6
D 2
prints the pathname of the user's terminal.
E 2
I 2
D 4
prints the pathname of the user's terminal unless the \-s
(silent) is given. In either case, the exit value is zero if the
standard input is a terminal and one if it is not.
E 2
.SH DIAGNOSTICS
`not a tty' if the standard input file is not a terminal.
E 4
I 4
exits 0 if the standard input is a terminal, 1 if the standard input is
not a terminal, and >1 if an error occurs.
D 6
.SH SEE\ ALSO
test(1), ttyname(3)
.SH STANDARDS
E 6
I 6
.Sh SEE ALSO
.Xr test 1 ,
.Xr ttyname 3
.Sh STANDARDS
E 6
The
D 6
.I tty
function is expected to be POSIX 1003.2 compatible.
E 6
I 6
.Nm tty
function is expected to be
D 8
.Tn POSIX
1003.2 compatible.
E 8
I 8
.St -p1003.2
compatible.
E 8
E 6
E 4
E 1
