h15089
s 00002/00002/00029
d D 8.1 93/05/31 15:56:15 bostic 8 7
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00012/00015/00019
d D 6.5 93/05/12 14:04:01 bostic 7 6
c new version of adventure from Jim Gillogly (jim@rand.org)
e
s 00018/00012/00016
d D 6.4 91/08/09 21:39:30 cael 6 5
c mdoc version three
e
s 00017/00010/00011
d D 6.3 91/04/08 17:08:11 bostic 5 4
c new copyright; att/bsd/shared
e
s 00001/00001/00020
d D 6.2 86/05/06 14:14:44 anne 4 3
c spelling, grammar, diction
e
s 00001/00001/00020
d D 6.1 85/05/20 17:09:00 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00004/00007/00017
d D 5.1 85/05/20 17:08:50 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00024/00000/00000
d D 4.1 85/05/20 17:08:38 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 5
D 7
.\" Copyright (c) 1991 The Regents of the University of California.
E 7
I 7
D 8
.\" Copyright (c) 1991, 1993 The Regents of the University of California.
E 7
.\" All rights reserved.
E 8
I 8
.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 8
.\"
D 7
.\" The game adventure was original written by Will Crowther and Don
.\" Woods, in Fortran.  It was later translated to C and enhanced by
.\" Jim Gillogly.
E 7
I 7
.\" The game adventure was originally written in Fortran by Will Crowther
.\" and Don Woods.  It was later translated to C and enhanced by Jim
.\" Gillogly.  This code is derived from software contributed to Berkeley
.\" by Jim Gillogly at The Rand Corporation.
E 7
.\"
.\" %sccs.include.redist.man%
.\"
E 5
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH ADVENTURE 6
E 2
I 2
D 3
.TH ADVENTURE 6 "1 February 1983"
E 3
I 3
D 6
.TH ADVENTURE 6 "%Q%"
E 3
E 2
D 5
.AT 3
E 5
I 5
.UC 3
E 5
.SH NAME
adventure \- an exploration game
.SH SYNOPSIS
D 5
.B /usr/games/adventure
E 5
I 5
.B adventure
E 5
.SH DESCRIPTION
E 6
I 6
.Dd %Q%
.Dt ADVENTURE 6
D 7
.Os BSD 3
E 7
I 7
.Os
E 7
.Sh NAME
.Nm adventure
D 7
.Nd "an exploration game"
E 7
I 7
.Nd an exploration game
E 7
.Sh SYNOPSIS
.Nm adventure
I 7
.Op saved-file
E 7
.Sh DESCRIPTION
E 6
D 5
The object of the game is to
locate and explore Colossal Cave, find the treasures hidden there,
and bring them back to the building with you.
D 2
The program is
self-describing to a point, but part of the game is to discover
E 2
I 2
D 4
The program is self-describing to a point, but part of the game is to discover
E 4
I 4
The program is self-descriptive to a point, but part of the game is to discover
E 4
E 2
its rules.
E 5
I 5
The object of the game is to locate and explore Colossal Cave, find the
treasures hidden there, and bring them back to the building with you.
D 6
The program is self-descriptive to a point, but part of the game is to
E 6
I 6
D 7
The program is self-descriptive
to a point, but part of the game is to
E 7
I 7
The program is self-descriptive to a point, but part of the game is to
E 7
E 6
discover its rules.
E 5
D 6
.PP
D 2
To terminate a game, type
`quit';
to save a game for later resumption, type
`suspend'.
E 2
I 2
D 5
To terminate a game, type `quit';
to save a game for later resumption, type `suspend'.
E 5
I 5
To terminate a game, enter ``quit''; to save a game for later resumption,
enter ``suspend''.
E 5
E 2
.SH BUGS
E 6
I 6
.Pp
To terminate a game, enter
D 7
.Ql quit ;
to save a game for later resumption,
enter
.Ql suspend .
.Sh BUGS
E 6
D 5
.PP
E 5
Saving a game creates a large executable file instead of just
the information needed to resume the game.
E 7
I 7
.Dq quit ;
to save a game for later resumption, enter
.Dq suspend .
E 7
E 1
