h39013
s 00002/00002/00130
d D 8.1 93/06/06 22:20:43 bostic 9 8
c 4.4BSD snapshot (revision 8.1); add 1993 to copyright
e
s 00001/00001/00131
d D 6.7 91/07/31 23:34:56 cael 8 7
c clean up
e
s 00085/00078/00047
d D 6.6 91/05/10 14:21:16 cael 7 6
c mdoc version three
e
s 00001/00011/00124
d D 6.5 90/06/23 18:00:43 trent 6 5
c new copyright notice
e
s 00002/00002/00133
d D 6.4 90/06/23 16:32:30 trent 5 4
c changed /usr/lib/vgrindefs to /usr/share/misc/vgrindefs
e
s 00014/00003/00121
d D 6.3 89/04/30 21:57:24 bostic 4 3
c add Berkeley specific header
e
s 00001/00001/00123
d D 6.2 87/09/30 08:38:27 bostic 3 2
c typo; bug report 4.3BSD/man/16
e
s 00001/00001/00123
d D 6.1 85/05/15 18:57:40 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00124/00000/00000
d D 5.1 85/05/15 18:57:18 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
D 4
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
I 4
D 7
.\" Copyright (c) 1989 The Regents of the University of California.
E 7
I 7
D 9
.\" Copyright (c) 1989, 1991 The Regents of the University of California.
E 7
.\" All rights reserved.
E 9
I 9
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
E 9
.\"
D 6
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
E 6
I 6
D 7
.\" %sccs.include.redist.man%
E 7
I 7
.\" %sccs.include.redist.roff%
E 7
E 6
E 4
.\"
D 7
.\"	%W% (Berkeley) %G%
E 7
I 7
.\"     %W% (Berkeley) %G%
E 7
.\"
D 7
.tr ||
D 2
.TH VGRINDEFS 5 "11 February 1981"
E 2
I 2
.TH VGRINDEFS 5 "%Q%"
E 2
.UC 5
.SH NAME
vgrindefs \- vgrind's language definition data base
.SH SYNOPSIS
D 5
.B /usr/lib/vgrindefs
E 5
I 5
.B /usr/share/misc/vgrindefs
E 5
.SH DESCRIPTION
.I Vgrindefs
contains all language definitions for vgrind.  The data base is
E 7
I 7
.Dd %Q%
.Dt VGRINDEFS 5
.Os BSD 4.2
.Sh NAME
.Nm vgrindefs
.Nd language definition data base for
.Xr vgrind 1
.Sh SYNOPSIS
.Nm vgrindefs
.Sh DESCRIPTION
The
.Nm vgrindefs
file
contains all language definitions for
.Xr vgrind 1 .
The data base is
E 7
very similar to 
D 7
.IR termcap (5).
.SH FIELDS
E 7
I 7
.Xr termcap 5 .
.Sh FIELDS
E 7
The following table names and describes each field.  
D 7
.PP
.nf
.ta \w'k0-k9  'u +\w'Type  'u
\fBName	Type	Description\fR
pb	str	regular expression for start of a procedure
bb	str	regular expression for start of a lexical block
be	str	regular expression for the end of a lexical block
cb	str	regular expression for the start of a comment
ce	str	regular expression for the end of a comment
sb	str	regular expression for the start of a string
se	str	regular expression for the end of a string
lb	str	regular expression for the start of a character constant
le	str	regular expression for the end of a character constant
tl	bool	present means procedures are only defined at the top 
		lexical level
oc	bool	present means upper and lower case are equivalent
kw	str	a list of keywords separated by spaces
.fi
.PP
.B Example
.PP
E 7
I 7
.Pp
.Bl -column Namexxx Tpexxx
.Sy Name	Type	Description
.It "pb	str	regular expression for start of a procedure"
.It "bb	str	regular expression for start of a lexical block"
.It "be	str	regular expression for the end of a lexical block"
.It "cb	str	regular expression for the start of a comment"
.It "ce	str	regular expression for the end of a comment"
.It "sb	str	regular expression for the start of a string"
.It "se	str	regular expression for the end of a string"
.It "lb	str	regular expression for the start of a character constant"
.It "le	str	regular expression for the end of a character constant"
.It "tl	bool	present means procedures are only defined at the top lexical level"
.It "oc	bool	present means upper and lower case are equivalent"
.It "kw	str	a list of keywords separated by spaces"
.El
.Pp
.Sh EXAMPLES
E 7
The following entry, which describes the C language, is 
typical of a language entry.
D 7
.PP
.nf
E 7
I 7
.Bd -literal
E 7
C|c:\
D 7
	:pb=^\ed?*?\ed?\ep\ed?\(\ea?\):bb={:be=}:cb=/*:ce=*/:sb=":se=\ee":\e
	:lb=':le=\ee':tl:\e
	:kw=asm auto break case char continue default do double else enum\e
	extern float for fortran goto if int long register return short\e
	sizeof static struct switch typedef union unsigned while #define\e
	#else #endif #if #ifdef #ifndef #include #undef # define else endif\e
	if ifdef ifndef include undef:
.fi
.PP
E 7
I 7
D 8
:pb=^\ed?*?\ed?\ep\ed?\(\ea?\):bb={:be=}:cb=/*:ce=*/:sb=":se=\ee":\e
E 8
I 8
:pb=^\ed?*?\ed?\ep\ed?\e(\ea?\e):bb={:be=}:cb=/*:ce=*/:sb=":se=\ee":\e
E 8
:lb=':le=\ee':tl:\e
:kw=asm auto break case char continue default do double else enum\e
extern float for fortran goto if int long register return short\e
sizeof static struct switch typedef union unsigned while #define\e
#else #endif #if #ifdef #ifndef #include #undef # define else endif\e
if ifdef ifndef include undef:
.Ed
.Pp
E 7
Note that the first field is just the language name (and any variants
of it).  Thus the C language could be specified to
D 7
.IR vgrind (1)
E 7
I 7
.Xr vgrind 1
E 7
as "c" or "C".
D 7
.PP
E 7
I 7
.Pp
E 7
Entries may continue onto multiple lines by giving a \e as the last
character of a line.
Capabilities in
D 7
.I vgrindefs
E 7
I 7
.Nm vgrindefs
E 7
are of two types:
Boolean capabilities which indicate that the language has
some particular feature
and string
capabilities which give a regular expression or 
keyword list.
D 7
.PP
.B REGULAR EXPRESSIONS
.PP
.I Vgrindefs
E 7
I 7
.Sh REGULAR  EXPRESSIONS
.Nm Vgrindefs
E 7
uses regular expression which are very similar to those of 
D 7
.IR ex (1)
E 7
I 7
.Xr ex 1
E 7
and
D 7
.IR lex (1).
E 7
I 7
.Xr lex 1 .
E 7
The characters `^', `$', `:' and `\e'
are reserved characters and must be
D 7
"quoted" with a preceding \e if they
E 7
I 7
"quoted" with a preceding
.Ql \e
if they
E 7
are to be included as normal characters.
The metasymbols and their meanings are:
D 7
.IP $
E 7
I 7
.Bl -tag -width indent
.It $
E 7
the end of a line
D 7
.IP ^
E 7
I 7
.It \&^
E 7
the beginning of a line
D 7
.IP \ed
E 7
I 7
.It \ed
E 7
a delimiter (space, tab, newline, start of line)
D 7
.IP \ea
E 7
I 7
.It \ea
E 7
matches any string of symbols (like .* in lex)
D 7
.IP \ep
E 7
I 7
.It \ep
E 7
matches any alphanumeric name.  In a procedure definition (pb) the string
that matches this symbol is used as the procedure name.
D 7
.IP ()
E 7
I 7
.It ()
E 7
grouping
D 7
.IP |
E 7
I 7
.It \&|
E 7
alternation
D 7
.IP ?
E 7
I 7
.It ?
E 7
last item is optional
D 7
.IP \ee
E 7
I 7
.It \ee
E 7
preceding any string means that the string will not match an
input string if the input string is preceded by an escape character (\e).
This is typically used for languages (like C) which can include the
D 3
string delimiter in a string b escaping it.
E 3
I 3
string delimiter in a string by escaping it.
E 3
D 7
.PP
E 7
I 7
.El
.Pp
E 7
Unlike other regular expressions in the system,  these match words
and not characters.  Hence something like "(tramp|steamer)flies?"
would match "tramp", "steamer", "trampflies", or "steamerflies".
D 7
.PP
.B KEYWORD LIST
.PP
E 7
I 7
.Sh KEYWORD  LIST
E 7
The keyword list is just a list of keywords in the language separated
by spaces.  If the "oc" boolean is specified, indicating that upper
and lower case are equivalent, then all the keywords should be 
specified in lower case.
D 7
.SH FILES
.DT
D 5
/usr/lib/vgrindefs	file containing terminal descriptions
E 5
I 5
/usr/share/misc/vgrindefs	file containing terminal descriptions
E 5
.SH SEE ALSO
vgrind(1), troff(1)
.SH AUTHOR
Dave Presotto
.SH BUGS
E 7
I 7
.Sh FILES
.Bl -tag -width /usr/share/misc/vgrindefs -compact
.It Pa /usr/share/misc/vgrindefs
File containing terminal descriptions.
.El
.Sh SEE ALSO
.Xr vgrind 1 ,
.Xr troff 1
.Sh HISTORY
The
.Nm
file format appeared in
.Bx 4.2 .
E 7
E 1
